### ISSUE TITLE
Map doesnot set back it region to initial location

### ISSUE THREAD

**Issue by GeekRishabh** [react-community/react-native-maps#1001]
I have added a button that sets rather update user current location is the GPS was off before the component was render . I am trying to set the map back to the region where the user /device current location is . I am able to change the state and set a new marker at current location but the map display on the screen is still the same region as set to initial region .
map is not dragged to the current location in simple words.On click although passing the region coordinates .It shows the region we have set by  default 
#67 
Is any one having the same issue or have done this .
![image](https://cloud.githubusercontent.com/assets/23093075/22467927/805939da-e7ec-11e6-8ffb-3ea8e5b85ec3.png)

**Comment by spikebrehm** [comment]
It's hard to tell just from your description. Can you include some sample code?

**Comment by alvelig** [comment]
See example https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
