### ISSUE TITLE
The MapView dont show me the UserLocation on Android

### ISSUE THREAD

**Issue by avedismb** [react-community/react-native-maps#1011]
It shows me the map correctrly but without the user location.

This is my code:

MapView
        showsUserLocation={true}
        showsMyLocationButton={true}
        style={{ height: 600 }}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}

Any idea ?

Thanks.

**Comment by spikebrehm** [comment]
Probably you have to enable a permission or something in Google Play Services for this to work.  Does it work in other apps that utilize Goole Maps?

**Comment by avedismb** [comment]
No, I didnt test it in other app or in IOS. Maybe is that , I will investigate that.

**Comment by jeffreymendez1993** [comment]
this is a current bug on android

**Comment by philberg** [comment]
+1

**Comment by AugustoAleGonZhipCode** [comment]
Check the permissions on my application the current location works perfect. What it is not supported is the followsUserLocation

**Comment by Ethan0007** [comment]
try to landscape your device the showsUserLocation will show.

**Comment by alvelig** [comment]
Duplicate of #1033
