### ISSUE TITLE
How to change the color of one marker out of many from an event

### ISSUE THREAD

**Issue by salilbajaj** [react-community/react-native-maps#1015]
![screen shot 2017-02-02 at 6 44 28 pm](https://cloud.githubusercontent.com/assets/14991148/22550787/ce641fdc-e977-11e6-8879-5adb936fec2b.png)
So i have this setup where there are multiple markers and there are workspaces in tile format below. I have the id of the current active tile. I need to map that active tile with marker by changing marker's color. So i need to refer the particular marker and access its properties(pinColor basically).
Any help would be appreciated.

**Comment by salilbajaj** [comment]
And this is the code am using
`<MapView style={{width:devWidth,height:devHeight/1.6}}
    initialRegion={{
      latitude: this.state.enteredData.lat,
      longitude: this.state.enteredData.lng,
       latitudeDelta: this.state.viewReceived?(this.state.viewReceived.northeast.lat-this.state.viewReceived.southwest.lat)+0.08:0.1922,
      longitudeDelta: this.state.viewReceived?(this.state.viewReceived.northeast.lng-this.state.viewReceived.southwest.lng)+0.08:0.1521
    }}
  >
    <MapView.Circle center={{
      latitude: this.state.enteredData.lat,
      longitude: this.state.enteredData.lng
    }} radius={this.state.myList[this.state.myList.length-1].distanceMeters} strokeColor='#00ACA4' geodesic={true} fillColor='rgba(0,172,164,0.1)' />
     
    
    {
        this.state.myList.map((item, idx) => {
            let cord={
              latitude:item.loc.coordinates[0],
              longitude:item.loc.coordinates[1]
            }
              return (
                   <MapView.Marker ref="marker"  identifier={item._id} pinColor='#e12f27' key={idx}
                                coordinate={cord}
                          />
                        )
              })
       }
  
  
  </MapView>`

**Comment by salilbajaj** [comment]
`<MapView style={{width:devWidth,height:devHeight/1.6}}
    initialRegion={{
      latitude: this.state.enteredData.lat,
      longitude: this.state.enteredData.lng,
       latitudeDelta: this.state.viewReceived?(this.state.viewReceived.northeast.lat-this.state.viewReceived.southwest.lat)+0.08:0.1922,
      longitudeDelta: this.state.viewReceived?(this.state.viewReceived.northeast.lng-this.state.viewReceived.southwest.lng)+0.08:0.1521
    }}
  >
    <MapView.Circle center={{
      latitude: this.state.enteredData.lat,
      longitude: this.state.enteredData.lng
    }} radius={this.state.myList[this.state.myList.length-1].distanceMeters} strokeColor='#00ACA4' geodesic={true} fillColor='rgba(0,172,164,0.1)' />
     
    
    {
        this.state.myList.map((item, idx) => {
            let cord={
              latitude:item.loc.coordinates[0],
              longitude:item.loc.coordinates[1]
            }
              return (
                   <MapView.Marker ref="marker"  identifier={item._id} pinColor='#e12f27' key={idx}
                                coordinate={cord}
                          />
                        )
              })
       }
  
  
  </MapView>`

**Comment by salilbajaj** [comment]
`{
        this.state.myList.map((item, idx) => {
            let cord={
              latitude:item.loc.coordinates[0],
              longitude:item.loc.coordinates[1]
            }
              return (
                   <MapView.Marker ref="marker"  identifier={item._id} pinColor='#e12f27' key={idx}
                                coordinate={cord}
                          />
                        )
              })
       }`

**Comment by shekharskamble** [comment]
@salilbajaj have you resolved your issue? I am having exact similar problem want to highlight particular marker based on selection...

**Comment by salilbajaj** [comment]
` <MapView style={{ width: devWidth, height: devHeight * 5 / 8 }}
            initialRegion={{
              latitude: this.state.enteredData.lat,
              longitude: this.state.enteredData.lng,
              latitudeDelta: this.state.viewReceived ? (this.state.viewReceived.northeast.lat - this.state.viewReceived.southwest.lat) + 0.08 : 0.4222,
              longitudeDelta: this.state.viewReceived ? (this.state.viewReceived.northeast.lng - this.state.viewReceived.southwest.lng) + 0.08 : 0.3621
            }}
          >
            {this.getCircle()}
            {
              this.state.myList ? this.state.myList.map((item, idx) => {
                let color = '#00ACA4';
                let mypinsize = 15;
                if (item.venueId == this.state.idColor) {
                  color = '#e12f27';
                } else {
                  color = '#00ACA4'
                
                }
                let cord = {
                  latitude: item.loc.coordinates[0],
                  longitude: item.loc.coordinates[1]
                }
                return (
                  <MapView.Marker onSelect={() => {
                    this.scrollToWork(idx)
                  }} ref="marker" style={{ width: 10, height: 10 }} identifier={item._id} pinColor={color} key={idx}
                    coordinate={cord}
                  />
                )
              }) : null
            }
          </MapView>`



try this

**Comment by salilbajaj** [comment]
` <MapView style={{ width: devWidth, height: devHeight * 5 / 8 }}
            initialRegion={{
              latitude: this.state.enteredData.lat,
              longitude: this.state.enteredData.lng,
              latitudeDelta: this.state.viewReceived ? (this.state.viewReceived.northeast.lat - this.state.viewReceived.southwest.lat) + 0.08 : 0.4222,
              longitudeDelta: this.state.viewReceived ? (this.state.viewReceived.northeast.lng - this.state.viewReceived.southwest.lng) + 0.08 : 0.3621
            }}
          >
            {this.getCircle()}
            {
              this.state.myList ? this.state.myList.map((item, idx) => {
                let color = '#00ACA4';
                let mypinsize = 15;
                if (item.venueId == this.state.idColor) {
                  color = '#e12f27';
                  mypinsize = 45;
                } else {
                  color = '#00ACA4'
                  mypinsize = 15;
                }
                let cord = {
                  latitude: item.loc.coordinates[0],
                  longitude: item.loc.coordinates[1]
                }
                return (
                  <MapView.Marker onSelect={() => {
                    this.scrollToWork(idx)
                  }} ref="marker" pinSize={mypinsize} style={{ width: 10, height: 10 }} identifier={item._id} pinColor={color} key={idx}
                    coordinate={cord}
                  />
                )
              }) : null
            }
          </MapView>`

**Comment by shekharskamble** [comment]
@salilbajaj Thank you very much will give it a try and let you know...

**Comment by GabrielScalici** [comment]
Allowed colors for Marker are : red, tomato, orange, yellow, green,  gold, wheat, linen, tan, blue, aqua, teal, violet, purple, indigo, turquoise, navy and plum.
Like: 
<MapView.Marker
            pinColor={'green'}
...
