### ISSUE TITLE
RN-0.40, maps -0.12.4 build fail with Duplicate definition for class "RTCView" and so on

### ISSUE THREAD

**Issue by Mactub07** [react-community/react-native-maps#1017]
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:13:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTComponent.h:26:11: warning: duplicate protocol definition of 'RCTComponent' is ignored
@protocol RCTComponent <NSObject>
          ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:12:
../../react-native/React/Views/RCTComponent.h:26:11: note: previous definition is here
@protocol RCTComponent <NSObject>
          ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:13:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTComponent.h:62:20: error: redefinition of 'RCTIsReactRootView'
static inline BOOL RCTIsReactRootView(NSNumber *reactTag)
                   ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:12:
../../react-native/React/Views/RCTComponent.h:62:20: note: previous definition is here
static inline BOOL RCTIsReactRootView(NSNumber *reactTag)
                   ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:21:1: error: duplicate interface definition for class 'RCTView'
@interface RCTView : UIView
^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:21:12: note: previous definition is here
@interface RCTView : UIView
           ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:26:49: error: property has a previous declaration
@property (nonatomic, copy) RCTDirectEventBlock onAccessibilityTap;
                                                ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:26:49: note: property declared here
@property (nonatomic, copy) RCTDirectEventBlock onAccessibilityTap;
                                                ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:27:49: error: property has a previous declaration
@property (nonatomic, copy) RCTDirectEventBlock onMagicTap;
                                                ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:27:49: note: property declared here
@property (nonatomic, copy) RCTDirectEventBlock onMagicTap;
                                                ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:32:48: error: property has a previous declaration
@property (nonatomic, assign) RCTPointerEvents pointerEvents;
                                               ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:32:48: note: property declared here
@property (nonatomic, assign) RCTPointerEvents pointerEvents;
                                               ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:48:41: error: property has a previous declaration
@property (nonatomic, assign) NSInteger reactZIndex;
                                        ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:48:41: note: property declared here
@property (nonatomic, assign) NSInteger reactZIndex;
                                        ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:57:36: error: property has a previous declaration
@property (nonatomic, assign) BOOL removeClippedSubviews;
                                   ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:57:36: note: property declared here
@property (nonatomic, assign) BOOL removeClippedSubviews;
                                   ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:70:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:70:39: note: property declared here
@property (nonatomic, assign) CGFloat borderRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:71:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderTopLeftRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:71:39: note: property declared here
@property (nonatomic, assign) CGFloat borderTopLeftRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:72:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderTopRightRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:72:39: note: property declared here
@property (nonatomic, assign) CGFloat borderTopRightRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:73:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderBottomLeftRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:73:39: note: property declared here
@property (nonatomic, assign) CGFloat borderBottomLeftRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:74:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderBottomRightRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:74:39: note: property declared here
@property (nonatomic, assign) CGFloat borderBottomRightRadius;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:79:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderTopColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:79:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderTopColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:80:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderRightColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:80:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderRightColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:81:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderBottomColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:81:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderBottomColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:82:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderLeftColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:82:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderLeftColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:83:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:83:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderColor;
                                         ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:88:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderTopWidth;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:88:39: note: property declared here
@property (nonatomic, assign) CGFloat borderTopWidth;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
../../react-native/React/Views/RCTView.h:89:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderRightWidth;
                                      ^
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.m:6:
In file included from /Users/dennis/WebstormProjects/yonoton-app-enduser-github/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygon.h:15:
In file included from ../../react-native/React/Views/RCTView.h:15:
/Users/dennis/Library/Developer/Xcode/DerivedData/yonotonApp-eyknbekhqhvfpigypbpdesjxqcqh/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:89:39: note: property declared here
@property (nonatomic, assign) CGFloat borderRightWidth;
                                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.

**Comment by tjdavies** [comment]
use the build "0.13.0"

**Comment by Mactub07** [comment]
now it works , thanks

**Comment by arsanjea** [comment]
Had the same issue, this solved it.
Thanks!

**Comment by pattle** [comment]
Having the same issue, what's the best way to upgrade from 0.12.4 to 0.13.0?

**Comment by pattle** [comment]
I also had this problem and I've updated to 0.13.0.  The build succeeds now but the map doesn't appear.  Because I ran `react-native link` before I installed 0.13.0 do I need to unlink and do it again?  If I do how do I do this?

**Comment by arsanjea** [comment]
Can you post your code?

Sincerely,
Jean-Marc Arsan

C +1 (310) 435-9983

**Comment by tedjames** [comment]
Hey @pattle, I'm having the same issue. Nothing appear for me at all... #1025

**Comment by rockia** [comment]
Hey @pattle， you can do following to unlink it.

`react-native unlink react-native-maps`

and then you can just link it again.

I had the same issue and it was solved with `0.13.0`. Just replace your version with this line in your package.json :

`"react-native-maps": "0.13.0",`

I tried with `react-native-maps": "^0.13.0`, but seems not working. I am not sure why. 

Here was my steps to make it work:

1. Unlink react-native-maps
2. Remove node_modules folder
3. Update package.json
4. npm install again

**Comment by afshinm** [comment]
Actually the correct way is: 

  1- `react-native unlink react-native-maps`
  2- `npm uninstall react-native-maps`
  3- `npm install react-native-maps@0.13.0`
  4- `react-native link react-native-maps`

and done. you don't need to remove the `node_modules` entirely.

**Comment by tedjames** [comment]
@UtkarshPramodGupta That's apple maps.You need to configure Google maps and integrate it into your xcode project.

**Comment by UtkarshPramodGupta** [comment]
@tedjames I did everything as directed in the [installation instructions](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md) for Google Maps but it ain't working. :/

**Comment by UtkarshPramodGupta** [comment]
@tedjames I'm sorry I didn't know I have to specify in my code to use google maps like the following. Well, now it works fine. Thanks a lot for your time:)
```
import MapView, {PROVIDER_GOOGLE} from 'react-native-maps';
   <MapView provider={PROVIDER_GOOGLE} 
         style={styles.map}
         region={{
           latitude: 37.78825,
           longitude: -122.4324,
           latitudeDelta: 0.015,
           longitudeDelta: 0.0121,
         }}
       >
       </MapView>
```

**Comment by ithieund** [comment]
@afshinm 
CC: @airbnbelena , @bipinairbnb 

I tried your suggestion but still get the blank map.
Please see the screenshot.
<img width="187" alt="screenshot at mar 21 16-48-57" src="https://cloud.githubusercontent.com/assets/4217195/24141509/396bb012-0e56-11e7-92f7-d4226ca22a25.png">


Do you have any idea to fix this?
Thanks.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
