### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by jamesone** [react-community/react-native-maps#102]
So I've been trying to get this package working for a while now and am getting an error: `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`

I'm using webpack and es6. Here is my web pack config.

```
module: {
        loaders: [
        { test: /\.jpe?g$|\.gif$|\.png$/i, loader: "file-loader" },
        // {
        //     test: /\.js$/,
        //     exclude: /node_modules/,
        //     loaders: ['babel-loader']
        // },
        {
            test: /\.jsx?$|\.js?$/,
            include: [
                path.resolve(__dirname, 'src'),
                path.resolve(__dirname, './config'),
                path.resolve(__dirname, 'node_modules/react-native/Libraries/react-native'),
                path.resolve(__dirname, 'node_modules/react-native/Libraries/Image'),
                path.resolve(__dirname, 'node_modules/react-native-navbar'),
                path.resolve(__dirname, 'node_modules/tcomb-form-native'),
                path.resolve(__dirname, 'node_modules/apsl-react-native-button'),
                path.resolve(__dirname, 'node_modules/react-native-maps/components'),
                path.resolve(__dirname, 'node_modules/react-native-google-places-autocomplete'),
                path.resolve(__dirname, 'node_modules/@exponent'),
                path.resolve(__dirname, 'node_modules/react-clone-referenced-element')
            ],
            loader: 'babel',
            query: {
                presets: ['es2015', 'stage-0', 'react']
            },
        },

        ]
    },
```

Is there any more information I should provide?

**Comment by micksabox** [comment]
What version of node are you using? Had this same issue on another project due to the incorrect version of node running, even though I was using nvm and thought I was using the latest one.

**Comment by jamesone** [comment]
Node version: v5.2.0 & npm version: 3.7.2

Interesting. What was the fix?

**Comment by micksabox** [comment]
Sorry, should have included the fix before. I opened the program (Atom) using node from the terminal/command line, ensuring that the correct version of node was used (via nvm). Then it worked. When I just launched Atom regularly, it didn’t.

I seemed to have installed node incorrectly because I’m still having problems with it. Hope this helps.

**Comment by jamesone** [comment]
Wait, so what version of node did you get to fix this error? @micksabox

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
