### ISSUE TITLE
Android: Blank map when using applicationIdSuffix

### ISSUE THREAD

**Issue by Amurmurmur** [react-community/react-native-maps#1021]
Apparently the issue for me was that I had `applicationIdSuffix` in `buildTypes`.

When removed those for staging/debug builds, blank issue got solved.

Though I do believe that it could be the issue, kind sad I cant use suffix, it is really useful, for development, when having 2 different builds on one device for testing. :/

**Comment by Snorlock** [comment]
Im struggeling with the same at the moment, there is something over here: https://github.com/facebook/react-native/pull/8950, but doesnt seem to get moving.

**Comment by alvelig** [comment]
Comment if the issue persists.
