### ISSUE TITLE
On 0.10.x+ no methods are available

### ISSUE THREAD

**Issue by niftylettuce** [react-community/react-native-maps#1026]
I cannot call `fitToElements` or any other method using `this.refs.map` for example.  The methods are undefined.

**Comment by niftylettuce** [comment]
Okay this is ONLY for `<MapView.Animated>` (not `<MapView`).

Possible duplicate of #896

**Comment by quanvuong** [comment]
I'm having the same issue

**Comment by alvelig** [comment]
Closing in favor of #896
