### ISSUE TITLE
custom map overlay

### ISSUE THREAD

**Issue by devfd** [react-community/react-native-maps#103]
Hello,

In my project I am currently using `AIRMap` and `AIRMapManager` custom categories for a heatmap overlay. Everything smooth and fine but I though maybe you would know a better and cleaner way to handle this.

Thanks for this very fine library

**Comment by Pocket-titan** [comment]
@devfd I'm also working with heatmaps in react native & have not found any existing library that adds this feature. Could you elaborate a bit more on how you're creating a heatmap overlay? I'm interested in creating a native module for this. Thanks!

**Comment by pjamrozowicz** [comment]
@devfd @Pocket-titan Could you explain how did you manage to make heatmap in react native? I would really appreciate an example.

**Comment by hajrice** [comment]
Did anyone find a good solution for doing heatmaps over google maps?

**Comment by pjamrozowicz** [comment]
@hajrice You can take a look at this pull request and use it https://github.com/airbnb/react-native-maps/pull/1549.
I personally have a fork of this repo too with heatmaps over google maps on android and over ios maps with DTMHeatmap extension on ios. I'm working on it now though to support more options like radius, setting gradient colors etc. and I want to use google maps sdk on ios too. I should finish in 2 weeks if you are interested.

**Comment by hajrice** [comment]
@pjamrozowicz Thanks, I appreciate it. I'm looking to launch before then. I really appreciate your comment though. Thanks again! 👍

**Comment by Stophface** [comment]
I am using `<MapView.UrlTile .../> to add a `Custom Tile Overlay`.

```
<MapView 
   ...>
  <MapView.UrlTile
    urlTemplate={this.state.urlTemplate}
  />
</MapView>
```

 It sort of works. There are two problems:

1. When I pinch, drag and zoom in/out, it displays the underlaying tiles (on Android Google Maps). Once the pinching, dragging, zooming is done, it only then loads the `Tiles` passed with `<MapView.UrlTile .../>`. It looks like basically it loads two maps. First the underlaying, and then the one passed through `<MapView.UrlTile .../>`.
Here a Video: [https://www.file-upload.net/download-12828114/maps_prob1.mov.html](https://www.file-upload.net/download-12828114/maps_prob1.mov.html) (19.41 MB, download link)

2. The names of the underlaying map shine through. Looking at the image I can see "Nashville", "Louisville", .... All the names shining through. Why is that?
[https://ibb.co/jXP6q6](https://ibb.co/jXP6q6)

**Comment by alvelig** [comment]
#1359 should do

**Comment by pjamrozowicz** [comment]
It took a while but if someone is looking for a heatmap, you might want to try this:
https://github.com/pjamrozowicz/react-native-heatmaps/

**Comment by Stophface** [comment]
@pjamrozowicz Super nice! Very useful. How did you compute the MapExtent? In `Todos` you write 

- "Fix handling points which are near the map edge in weight based algorithm."

That means somehow you must be able to extract the extent of the MapView (which area is visibile to the user). How do you do that?

**Comment by pjamrozowicz** [comment]
@Stophface Thank you very much! 
Google Maps library handles getting current visible area (or rather map tiles) and run getTile function from TileProvider interface for this area. This function gets coordinates of the tile and current zoom as parameters. So all I do is calculate map coordinates based on the tile coordinates. It works a bit different in iOS vs Android, but you might get the idea here:

    public Tile getTile(int x, int y, int zoom) {
        double tileWidth = WORLD_WIDTH / Math.pow(2, zoom); // WORLD_WIDTH = 1

        // Bounds of the current tile
        double minX = x * tileWidth;
        double minY = y * tileWidth;
    ...
    }

To understand why I’m calculating tileWidth like that you can check this out: https://developers.google.com/maps/documentation/android-api/tileoverlay

**Comment by Stophface** [comment]
@pjamrozowicz Ah okay. You do it native. I though you might do it in JS. Thanks! :)

**Comment by g3r4n** [comment]
@devfd we should support Overlay now : [docs](https://github.com/react-community/react-native-maps/blob/master/docs/overlay.md) and [example](https://github.com/react-community/react-native-maps/blob/master/example/examples/ImageOverlayWithURL.js)

**Comment by rborn** [comment]
Going to close as per https://github.com/react-community/react-native-maps/issues/103#issuecomment-367671687
