### ISSUE TITLE
RN 0.41.2 + react-native-maps 0.13.0 fails linking ld: 179 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by aphex3k** [react-community/react-native-maps#1034]
I attached an example project below. After downloading the zip file run the following step to reproduce it

    npm install
    cd ios
    pod install
    cd ..
    react-native run-ios

I also appended the full log from my terminal using Xcode 8, macOS Sierra 10.12.3, cocoapods version 1.2.0, npm version 4.1.2

1. [RocketReact.zip](https://github.com/airbnb/react-native-maps/files/761650/RocketReact.zip)
1. [full_log.txt.gz](https://github.com/airbnb/react-native-maps/files/761662/full_log.txt.gz)

**Comment by aphex3k** [comment]
I had a close look and it seems like react-native creates a xcode project file that has more projects as "Libraries" dependencies. These are however the same ones when using cocoapods to include react-native-maps (which has dependencies to the React pod which installs the same headers as the already included ones).

**Comment by aphex3k** [comment]
I fixed it by changing my _OTHER_LDFLAGS_.

I removed the `"$(inherited)"` argument and added the now missing 

    "-framework"
    "JavaScriptCore"
    "-lstdc++"
back

**Comment by ABleas** [comment]
It might be related to the breaking change where all references to React modules `#import "RCT....h"` should be updated to `#import <React/RCT....h>` as of RN 0.40.0?

I have duplicate refs in the AirMaps project because of this.

**Comment by rastapasta** [comment]
I can confirm that its related to the `#import <React..` breaking change.
Updating all of the imports (like in #923) makes it sweetly working again.

Wrote a quick and dirty shell command to crawl through your project's `node_modules`'s `react-native-maps` copy to replace the `#import`s, just run it from your project's root and you're good to go (until there's a more profane approach or PR that won't break thingies like the last one)

```perl
find node_modules/react-native-maps/ios/ -name *.[mh] -exec perl -p -i -e \
's%(?<=import )"([^"]+?)"%(index($1,"RCT")+index($1,"UIV")==-2 or
index($1,"MoreMap")>0)?"\"$1\"":"<React/$1>"%ge' {} \;
```

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
