### ISSUE TITLE
[Utility] Google polyline format -> LatLng Array

### ISSUE THREAD

**Issue by Yhozen** [react-community/react-native-maps#1046]
Hello guys, this is my first package ever I know it's simple but I think it's worth sharing so check this [rn-maps-polyline](https://www.npmjs.com/package/rn-maps-polyline)

**Comment by rborn** [comment]
@Yhozen that's a great package. 
I'll close the issue though as it's not exactly one, and people can find it anyway searching into the old ones. 
Thanks again for your package :)
