### ISSUE TITLE
How to use GoogleMap in iOS without using a pod? 

### ISSUE THREAD

**Issue by MrVisitor** [react-community/react-native-maps#1056]
I use react-native 0.41.2 and react-native-maps 0.13.0

**Comment by jordenchang55** [comment]
There is [instruction](https://developers.google.com/maps/documentation/ios-sdk/start) for installing Google Maps for iOS without pod. But react-native-maps seems to do something by pod. Still trying to figure out the way.

**Comment by alvelig** [comment]
@jordenchang55 is right. You need to go through it manually.

I recently made a fresh example build with pods and GoogleMaps with no issues
https://github.com/alvelig/react-native-maps-pods-example.

Try to check it out or build through the README.MD. If it does not help, let me know.
