### ISSUE TITLE
[Android] Adding 50+ markers dramatically drops JS and UI FPS when panning

### ISSUE THREAD

**Issue by bosung90** [react-community/react-native-maps#1063]
I have Android Galaxy S6 running Android 6.0.1

I have about 50 default markers on the map.

However, when I pan around the map, it causes FPS to drop to 10~20 fps for both JS and UI.

I don't have this problem on iOS, having even 500 markers is fine. 

On iOS, drop in JS fps does not cause drop in UI fps, but it looks like it does on Android.

Using Circle instead of Marker fixes this issue but I want to use Marker for custom look.

```
package.json

"react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-maps": "^0.13.0",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
```

**Comment by vjeranc** [comment]
Is it release or debug build? Debug seems to suffer a lot when there's a lot of markers but Release build on Nexus 5x works even with hundreds of markers.

**Comment by note89** [comment]
Have the same issue, it differs quite a lot between devices. 
OnePlus Two and Nexus 5X lags very much for us. Nexus 4 works better.

**Comment by SimenFjellstad** [comment]
Have you bound your mapregion to the consuming react component's state? If so, is the consuming component's render function called a lot when you pan the map?

I've experienced such issues where binding the map region to state would cause re-renders that would oversatisfy the RCTBridge

**Comment by alvelig** [comment]
I would recommend use clustering (see #213 react-native-super-cluster) and not to control your region in state as here: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

Let me know if it persists after these changes.
