### ISSUE TITLE
Duplicate definitions of React headers when compiling for iOS.

### ISSUE THREAD

**Issue by alxmhe** [react-community/react-native-maps#1093]
When installing from react-native link, the file AIRMaps.xcodeproj is included in XCode and the installation is the same as Option 3 (https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md)
While it is working for Android, it was impossible to build on iOS because React (0.42) was already set in XCode and would use different headers, leading to multiple duplicate entries for properties and classes included from React.
I had to change the configuration of 'Header Search Paths' (Option 3, Step 3) from $(SRCROOT)/../../react-native/React to $(BUILT_PRODUCTS_DIR)/include/React in order to connect to the correct headers files and make the map work on iOS.

**Comment by zakster12** [comment]
I have the same issue

**Comment by alxmhe** [comment]
In Libraries/AirMaps.xcodeproj > Build Settings > Search Paths,
setting 'Always Search User Paths' to "Yes"
and adding "$(SRCROOT)/../../react-native/React" (recursive) to 'User Header Search Paths'
seems fixes this issue even after reusing the command "react-native link" (that would normally overwrite 'Header Search Paths').

**Comment by alxmhe** [comment]
Actually it doesn't fix the issue when adding a new module with yarn. So it's still not the preferred way. Anyone else encountered this issue ?

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
