### ISSUE TITLE
Change showsMyLocationButton's position to bottom

### ISSUE THREAD

**Issue by pewh** [react-community/react-native-maps#1094]
Currently `showsMyLocationButton` show button on right-top. Can I change this button to right-bottom?
Current position is overlap with my navbar. Thanks.

![g](https://cloud.githubusercontent.com/assets/881358/23646503/ad3470e2-0343-11e7-911a-7adbd01323e3.png)

**Comment by Lars-m** [comment]
Add a paddint to the top of your map (with the height of your Navbar) and none of the map will be covered by your navbar

**Comment by pewh** [comment]
I know how to add padding, but my use-case is adding "overlap effect" between container & navbar as an aesthetic design. So, changing style of `MyLocationButton` via props is very helpful for me.

**Comment by sidd123456** [comment]
@Lars-m can i change the shape of mylocation button

**Comment by SidharthRaveendran** [comment]
Is there any solution for this in the latest?

**Comment by alvelig** [comment]
This should be customized. Please wait for #1874 or see #209 as an idea.

**Comment by sivasaiakhil** [comment]
can you explain in detail how can I change it to right-bottom?

**Comment by shoki61** [comment]
`<MapView                
                    mapPadding={{
                        top: 0,
                        right: 0,
                        bottom: 800,
                        left: 0
                    }}
                />`

**Comment by Je12emy** [comment]
> > `<MapView mapPadding={{ top: 0, right: 0, bottom: 800, left: 0 }} />`
> 
> Can you please say me how to adjust map padding ?

Using ` <MapView mapPadding={{ top: 0, right: 0, bottom: 800, left: 0 }} />` ended up cutting the button in my case, try adjusting you map styling with `PaddingTop` to push it just bellow the navigation bar. In my case I had a navigation bar with a height of 45:
```
container: {
    flex: 1,
    paddingTop: 40
 },
```
