### ISSUE TITLE
This package should not depend on Google Maps

### ISSUE THREAD

**Issue by JasperStam** [react-community/react-native-maps#1098]
I run a app with react-native 0.41.2 and react-native-maps 0.12.4
I want to use Open Street Maps as tileserver, but when running the app on a Genymotion emulator it crashes on startup with a fatal error, caused by a missing GoogleMapOption

This is a package for viewing a map, it should in no way be dependent on a single map provider.
I don't want to configure Google Play Services when I don't use them.

The logcat error:

```
E/AndroidRuntime( 2440): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime( 2440): Process: com.REDACTED, PID: 2440
E/AndroidRuntime( 2440): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 2440): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 2440): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 2440): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 2440): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 2440): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 2440): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 2440): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 2440): Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
E/AndroidRuntime( 2440): 	at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
E/AndroidRuntime( 2440): 	at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
E/AndroidRuntime( 2440): 	at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
E/AndroidRuntime( 2440): 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:206)
E/AndroidRuntime( 2440): 	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:71)
E/AndroidRuntime( 2440): 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:145)
E/AndroidRuntime( 2440): 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:142)
E/AndroidRuntime( 2440): 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
E/AndroidRuntime( 2440): 	at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:958)
E/AndroidRuntime( 2440): 	at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:863)
E/AndroidRuntime( 2440): 	at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
E/AndroidRuntime( 2440): 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
E/AndroidRuntime( 2440): 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
E/AndroidRuntime( 2440): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 2440): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 2440): 	... 3 more
W/ActivityManager(  746):   Force finishing activity 1 com.REDACTED/.MainActivity
```

**Comment by lelandrichardson** [comment]
@JasperStam I agree with what you're saying, but I'm not quite sure how we can do this. Do you have any suggestions? How are you configuring open street maps as the tile server? If you'd like to make this happen, I'll support a PR that decouples this library from google play services.

**Comment by JasperStam** [comment]
To configure open street maps as a tile server in non react-native maps, you only have to change the tile URL to: http://c.tile.openstreetmap.org/{z}/{x}/{y}.png , the same as you would add a MapView.UrlTile to react-native-maps. 

The problem with using a UrlTile with this package is that the Google Maps tileserver, and the required API settings are still being required by the package. I don't know if optional dependencies are possible with react-native. 

I will try to find some time to create a fork that doesn't depend on Google Maps.

**Comment by Jonovono** [comment]
Hey, I don't about this specific use case, but I am curious in the general solution to having optional dependencies for a react native project. Was there ever a solution to this @JasperStam ?

I am working on a project now that will have a few optional dependencies that all users should need to install.

The way I was thinking of install this was to have separate npm packages. So for the root you would do like `npm install root-map` and if you wanted google maps with it you would also install `npm install root-map-google`. And then you could link the two up or something.

But I am curious how others have solved this!

**Comment by fqborges** [comment]
As I said in the linked issue above, I am working on a branch (https://github.com/fqborges/react-native-maps/tree/osmdroid), replacing google maps with osmdroid (https://github.com/osmdroid/osmdroid).

My goals are to get used to the codebase, and have a functional version using osmdroid. Then I will try to extract providers (gmaps, osmdroid) out of the main library. It seems a lot of work but I am slowly getting there.

There are still people interested on this?

**Comment by alvelig** [comment]
Duplicate #773

**Comment by alvelig** [comment]
See #2348
