### ISSUE TITLE
fitToCoordinates() does not work with navigator.geolocation.getCurrentPosition()

### ISSUE THREAD

**Issue by Larney11** [react-community/react-native-maps#1099]
fitToCoordinates() does not work with navigator.geolocation.getCurrentPosition().

When I call fitToCoordinates() and then call navigator.geolocation.getCurrentPosition() it seems that the view zooms in to just the last coordinate object inside the array of coordinates.

The fitToCoordinates() works perfectly when navigator.geolocation.getCurrentPosition() is not called.

Any ideas?

**Comment by lelandrichardson** [comment]
I'm not sure I understand what you mean. Can you post some code with the behavior that you expect versus what is happening?

**Comment by alvelig** [comment]
Not related. navigator.geolocation.getCurrentPosition() is out of scope of this lib
