### ISSUE TITLE
[feature request] map view on load complete

### ISSUE THREAD

**Issue by jp928** [react-community/react-native-maps#1109]
I wish map view could have event load complete or finish so that I could start animations on the callouts.

**Comment by AuroreM** [comment]
Is the (`onMapReady`)[https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md#events] responding your need ?

**Comment by jp928** [comment]
@AuroreM This is what I am looking for. Thanks.

**Comment by AuroreM** [comment]
@lelandrichardson I think you can close this issue :)
