### ISSUE TITLE
Future PR : Possibility to choose initial zoom (totally documented)

### ISSUE THREAD

**Issue by yolosaucisson** [react-community/react-native-maps#1114]
I would like to know if it's possible to add the possibility to choose the initial zoom of the map?

# Android :
In the source code, i saw that : 
`map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(lat, lng), 10));`

The 10 represent the zoom and it can't be modify.
This line can be found at line 308 of the "react-native-maps/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java" file.

This is the comment before it : 
```
// in this case, our map has not been laid out yet, so we save the bounds in a local
// variable, and make a guess of zoomLevel 10. Not to worry, though: as soon as layout
// occurs, we will move the camera to the saved bounds. Note that if we tried to move
// to the bounds now, it would trigger an exception.
```
And the documentation [here](https://developers.google.com/android/reference/com/google/android/gms/maps/CameraUpdateFactory)

# iOS : 
According to the documentation, this is probably here: "ios/AirGoogleMaps/AIRGoogleMapManager.m"

Line 101 and 130 :  
`[mapView animateWithCameraUpdate:[GMSCameraUpdate fitBounds:bounds withPadding:55.0f]];`

And the documentation [here](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_camera_update)

**Comment by alvelig** [comment]
animateToRegion does it pretty well: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
