### ISSUE TITLE
Wrong location showing?

### ISSUE THREAD

**Issue by bramvbilsen** [react-community/react-native-maps#1117]
Hi guys,

I've got a problem implementing the maps into my app. I've installed react-native-maps and was able to get a working map on the screen, but it's showing the wrong location...

This is my code for the mapview (it's nested inside of a scrollview, perhaps that helps):
`                    <MapView
                        style={styles.map}
                        scrollEnabled={true}
                        zoomEnabled={true}
                        pitchEnabled={false}
                        rotateEnabled={false}
                        initialRegion={{
                            latitude: this.props.data.latitude,
                            longitude: this.props.data.longitude,
                            latitudeDelta: 2,
                            longitudeDelta: 2,
                        }}
                    >
                    <MapView.Marker
                      title={this.props.data.location}
                      coordinate={{
                          latitude: this.props.data.latitude,
                          longitude: this.props.data.longitude,
                          latitudeDelta: 2,
                          longitudeDelta: 2,
                      }}
                    />
                    </MapView>
`
The coordinates in "this.props.data" are for latitude: 33.8847361 and longitude: -118.4109089. This should be somewhere in California according to Google Maps, yet my map is showing a location somewhere in Asia. Does anyone have an idea on what's going wrong?

**Comment by mienaikoe** [comment]
I'm seeing the same problem. Using coordinates in Delaware, and it's showing someplace in China.

**Comment by alvelig** [comment]
Let us know if the issue still persists

**Comment by kamalkrishna3000** [comment]
I am also facing same issue

**Comment by muganwas** [comment]
I'm facing the same issue, the only difference is that it sometimes loads the correct location. The problem is on iOS, I haven't had the sam on android.
