### ISSUE TITLE
Marker not rendering

### ISSUE THREAD

**Issue by avdept** [react-community/react-native-maps#1122]
Hello, I have strange issue, while <MapView.Marker/> doens't rendering if i pass data outside of current component 

`<MapView.Marker pinColor={'#d62424'} coordinate={{...this.state}} title="One"/>`
Coords are present. And when i drag map, then marker renders fine. If instead of this.state data i will pass hardcoded values like {latitude: xxx, longitude: xxx} it renders fine also. 
It also renders fine with this.state data if MapView uses `showsUserLocation`. Any ideas whats wrong ?

Currently fixed it by using `animateToRegion` to my marker's coordinates

**Comment by andreconghau** [comment]
HI,
I also got it. It did show any marker in Mapview.

Here is my code:
            <View style={styles.container}>
                <MapView
                    style={ styles.map }
                    initialRegion={this.state.region}
                />
                <MapView.Marker
                    coordinate={{  latitude: 10.7667286,longitude: 106.7044843}}
                    pinColor={'#d62424'}
                    title={"Hi"}
                />
            </View>

anybody help.

**Comment by lelandrichardson** [comment]
I'm sorry, i'm not sure I understand the issue?  Can you provide more code for the example, and explain what is happening vs. what you expect to happen?

**Comment by avdept** [comment]
If i pass data to coordinate prop from state object, and when componentDidMount - state object is empty, but after my requests are done - then state populated with new data. And in this moment I expect my marker to appear on screen.

**Comment by jsaucedo** [comment]
@avdept did you find a solution for this?

**Comment by avdept** [comment]
@jsaucedo  When i received new data, i did `this.forceUpdate()`

**Comment by zambrey** [comment]
@avdept this.forceUpdate() worked for me.

**Comment by alvelig** [comment]
Might be related to #483
