### ISSUE TITLE
Question: Upper limit of rendering a route between hundreds of markers?

### ISSUE THREAD

**Issue by emmajam** [react-community/react-native-maps#1131]
Wondering if it is possible to render 200+ markers, with a route between them all in a single view? Or if there is a limit to the number of markers/waypoints?

Cheers!

**Comment by lelandrichardson** [comment]
@emmajam It probably depends on whether or not you plan on updating the markers a lot, or if they're failry static. 200 seems like a lot, so might not perform great in either case, but should be pretty easy to test out.

**Comment by rborn** [comment]
I'll close this as it's an old question with no feedback from the author.
