### ISSUE TITLE
IOS OnMapPress called when press the marker

### ISSUE THREAD

**Issue by felangga** [react-community/react-native-maps#1132]
This problem using Google Maps and doesn't occurred on Android.

**Comment by WernlingTan** [comment]
In my case, that is same.
Who can help me?

**Comment by saadmutahar** [comment]
@hysan 
The same error is occurred in latest version of maps.
When I press the marker, it triggers the onPress of parent Maps also. Can you please have a look for this.

I am uses these versions. 

"react-native": "0.59.8",
"react-native-maps": "0.25.0"

Thanks

**Comment by saadmutahar** [comment]
It's fixed the issue for me, As I forgot to add the stopPropagation event on marker click. 

Thanks.

**Comment by mmamani93** [comment]
Hi there, I am trying to create a custom behavior when any part of the map is pressed:
In case a Marker is pressed, I want to change the color of the marker. And the color turns back to normal when any other part of the map is pressed. This is working fine in iOS but not in Android.
Im not english native so Im having some difficulties to understand this thread completely, does it mean that `onPress` events will not be triggered in Android at any cost?
Is there any workaround to handle Markers press for both platforms?

Thanks in advance!
