### ISSUE TITLE
About IOS configuration

### ISSUE THREAD

**Issue by tianhaoz95** [react-community/react-native-maps#1137]
According to the doc, it seems that I don't need to configure anything on IOS if I only want to use apple map. Is that correct? Since apple only function is enough for me and every time I use pod to config it causes bug. However, when I do noting but react link, the map works on Android but is blank on IOS. Any idea?

**Comment by smooJitter** [comment]
I would was just thinking the same.  The documents seem to suggest both react-native  link   as well as the pod (option 1) installation are needed.

**Comment by tianhaoz95** [comment]
for step 1 in option 1, it mentions that "If you do not need GoogleMaps support for iOS, then you can probably completely skip this step". 

So I tried doing option 1 following I think all the steps, but it ended up breaking not only the map but the whole program. It didn't compile.  >_<

**Comment by tianhaoz95** [comment]
Have you figured out how to make it work on IOS?

**Comment by smooJitter** [comment]
Sort of but I have not coded anything yet.  

1. react-native unlink react-native-maps
2. npm uninstall react-native-maps
3. npm install react-native-maps --save
4. react-native link react-native-maps

At this least the build works.  The instructions are confusing in two ways, first I'm not sure what "step" is unnecessary.  I would encourage the maintainers to write the instillation assuming the user will not need GoogleMaps support.  Then have a separate write-up for the GoogleMaps use case.  Regarding pods, the instructions look frightening  but straight forward, assuming there are no other pods

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues
https://github.com/alvelig/react-native-maps-pods-example.

Or just a bare naked ios: https://github.com/alvelig/react-native-maps-example.

Try to check it out or build through the README.MD. If it does not help, let me know.
