### ISSUE TITLE
[Android] View inside Marker with 0.13.1

### ISSUE THREAD

**Issue by eard7** [react-community/react-native-maps#1153]
Hi, first of all thanks for your hard work.
I'm using react-native 0.42.3, and after upgrading to react-native-maps 0.13.1, i'm getting the following error.

```
com.facebook.react.views.text.ReactTextView cannot be cast to android.view.viewGroup

addFeature
AirMapView.java  427

addFeature
AirMapView.java  429

addView
AirMapManager.java  266
```

I think the problem comes from this custom component i'm using
```
import React, {Component} from 'react';
import {View, Text} from 'react-native';
import MapView from 'react-native-maps';

export default class MarkerCluster extends Component{

	constructor(props) {
		super(props);
		this.state = {...props};
	}

	shouldComponentUpdate(nextProps, nextState) {
		return nextProps.coordinate.latitude != this.state.coordinate.latitude && nextProps.coordinate.longitude != this.state.coordinate.longitude;
	}

	render() {
		return (<MapView.Marker {...this.props}>
			<View style={{borderWidth:3, borderColor: 'white', backgroundColor: 'black', borderRadius: 15, width:30, height:30, justifyContent: 'center', alignItems:'center'}}>
				<Text style={{color:'white', textAlign: 'center'}}>{this.props.clusterLength}</Text>
			</View>
		</MapView.Marker>);
	}
}
```

If i downgrade to react native maps 0.13.0, the code works as expected.

Hope this helps to solve the issue,
Thanks!

**Comment by lelandrichardson** [comment]
@eard7 can you try adding `collapsible={false}` to the `View` inside your marker and see if that changes anything?

**Comment by garzdin** [comment]
@lelandrichardson I can confirm .. this happens only on Android.
Dependencies:
```
react: 16.0.0-alpha.6
react-native: 0.43.3
react-native-maps: ^0.14.0
```

![screenshot_1492035015](https://cloud.githubusercontent.com/assets/15079364/24981617/d20f741e-1fdd-11e7-9102-7df95a7c1615.png)

**Comment by aserrano1971** [comment]
I'm having exactly the same issue just adding a TouchableOpacity with a text inside whereas in iOS is working perfectly.

`...
const myIcon = (<Icon name="rocket" size={30} color="#900" />)
....
<TouchableOpacity style={[styles.bubble, styles.button]}>
  {myIcon}
</TouchableOpacity>
`

**Comment by kevinnguy** [comment]
I'm also having this issue but it happens infrequently. I can't nail down why this error is triggering.

```
<MapView.Marker
  ref={ref => { this.markers[id] = ref; }}
  key={`${id}`}
  identifier={`${id}`}
  title={title}
  description={description}
  coordinate={address.coordinates}
  onPress={() => this.showCallout(`${id}`)}
  onCalloutPress={() => this.onCalloutPress(id)} >
  <View style={styles.marker}>
    <Text 
      style={styles.deliveryID}
      allowFontScaling={false}>
      {order}
    </Text>
  </View>
</MapView.Marker>
```

**Comment by kelset** [comment]
Happening here too, in RN 0.44 with `react-native-maps` 15.0 - adding `collapsible={false}` as suggested by @lelandrichardson doesn't fix it.

**Comment by sercanov** [comment]
Having the same issue, collapsible doesnt help

**Comment by rubensbarreto** [comment]
Same issue here with 0.46, using Expo v19.
On iphone it works just fine, on Android happens every single time, removing touchable opacity from the Marker and adding collapsible={true} had no effect:

            <MapView.Marker
              key={marker.key}
              coordinate={marker.coordinates}
              title={marker.title}
              description={marker.description}
              image={marker.image}
            >
              <MapView.Callout>
                <View>
                  <Text>{marker.title}</Text>
                  <Button light block
                    onPress={() => navigate('PlaceDetailScreen', { id: marker.key, title: marker.title })}
                  >
                    <Text>Detalhes</Text>
                  </Button>
                </View>
              </MapView.Callout>
            </MapView.Marker>

**Comment by die20** [comment]
Hey guys, 

I was experiencing this problem as well. 

My setup was like this:
`<MapView>`
        `<Icon onPress={()=>this.doSomething()}>`
`</MapView>`

when I removed the Icon from the MapView component it worked on android. 

It works on iOS with the Icon in MapView.

**Comment by kelset** [comment]
This issue is still present in RN 0.46.4 & `react-native-maps` v16.2.
Any update on workarounds or how to fix it?

**Comment by aylesm** [comment]
Seeing the same issue RN 0.46.2 & react-native-maps@0.15.3

**Comment by antonmyrberg** [comment]
RN@0.48.1 &  react-native-maps@0.17.0, same issue caused by using `TouchableOpacity` inside of MapView.

**Comment by kidmysoul** [comment]
have the same problem. some TouchableOpacity inside of MapView causes this problem but  some not.

**Comment by ml9951** [comment]
Also having this problem.  Any solution?

**Comment by nezaidu** [comment]
My solution is:
![image](https://user-images.githubusercontent.com/3225817/33125970-561807be-cf8b-11e7-9929-4ca57f288a9b.png)
Note **isAndroid** variable

**Comment by alvelig** [comment]
Please, review this commit: https://github.com/react-community/react-native-maps/commit/6220583a19cf62f942b4166927aafeeeb1003a81

The original problem was not reproduced, but the following problems with Text and TextEdit within MapView for Android are fixed there.

As soon as it passes through QA (you are the QA) we will merge it to master and release it on the next iteration.

**Comment by kelset** [comment]
Awesome! Thanks for fixing it @alvelig :)

**Comment by pquattro** [comment]
Can you make same with ReactImageView ?

**Comment by alvelig** [comment]
@pquattro why?

**Comment by pquattro** [comment]
because, same error. if you want make special marker (with different color for exemple), and you want to add a legend (by image explanation)...

**Comment by alvelig** [comment]
@pquattro wrap your image in a view. If it does not help, open a new issue with a link to a minimal project reproducing the problem (or fork examples)

**Comment by TheoGit** [comment]
@pquattro did the ReactImageView ever get resolved?  I'm having the same problem.  This is a production show-stopper.

**Comment by nezaidu** [comment]
same thing with TouchableOpacity on RN 55 and maps ^0.17.1

**Comment by allthetime** [comment]
this is still an issue why is this closed?

**Comment by tgreco** [comment]
2025 and this is still an issue for Android. The workaround I have is to use react-native-fast-image instead of default react native image component on Android.
