### ISSUE TITLE
Add animated markers example to the AnimatedViews.js

### ISSUE THREAD

**Issue by grundmanise** [react-community/react-native-maps#1158]
In the doc's paragraph '**Using the MapView with the Animated API**'  is written:

> Further, Marker views can use the animated API to enhance the effect.

I am tryign to accomplish the same thing, i.e. gradually animate marker's size & opacity depending on the `scroll offset` https://github.com/airbnb/react-native-maps/issues/1146

I don't know whether my  approach is correct or I can achieve the same effect without creating `Interpolators` for each marker and get the same result?

So the question is: maybe anyone could add an example of how to correctly animate markers depending on the scroll/card offset to the AnimatedViews.js?

**Comment by rborn** [comment]
It seems to be done here: https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedMarkers.js
