### ISSUE TITLE
Can't render map, only red dot

### ISSUE THREAD

**Issue by manuelsalomon** [react-community/react-native-maps#1160]
Hi, I'm using genymotion to deploy and can't see the map in screen, only see red dot in left-top corner.
My code
`

  render() {
    return (
     
      <View style={styles.container}>
         <MapView initialRegion={{
            latitude: -34.599134,
            longitude:  -58.382191,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421}}/>
      </View>
      );
    }
  }`

Manifest 
`
    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <meta-data 
        android:name="com.google.android.geo.API_KEY"
        android:value="{MY API KEY}"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">`

**Comment by TheRealSecret** [comment]
Have the same problem, found any solution as of yet Manuel?

**Comment by hadiab** [comment]
Have the same problem, only red border

**Comment by TheRealSecret** [comment]
Had the same problem, @hadiab @manuelsalomon followed the steps in this post and it resolved the problem for me, hope it helps. 

https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0

good luck

**Comment by hadiab** [comment]
these instructions is how to enable Google Maps on IOS,
didn't work on Android

**Comment by anahitsk123** [comment]
I have the same issue, any news on that? Could anyone solve the issue ?

**Comment by nmquebb** [comment]
Does `styles.container` have `flex: 1` on it so it expands to take up its parent?

**Comment by zengyanzi** [comment]
is there any solution please?
here is my APP result, only red border
![image](https://cloud.githubusercontent.com/assets/21092607/25063605/3e0594c6-223d-11e7-8d0e-728324c4fe0d.png)

**Comment by chapeljuice** [comment]
+1
<img width="562" alt="screen shot 2017-05-18 at 1 20 06 pm" src="https://cloud.githubusercontent.com/assets/862642/26221846/c1afda36-3bcc-11e7-8fae-10411f10070a.png">

**Comment by justinobney** [comment]
Have you enabled maps in XCode?

![image](https://user-images.githubusercontent.com/1054188/27618198-7e302d00-5b80-11e7-8870-5f8dd43f6e6b.png)

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
No pods: https://github.com/alvelig/react-native-maps-example
Try to check it out or build through the README.MD. If it does not help, let me know.
