### ISSUE TITLE
Android+GenyMotion+ ':react-native-maps:compileReleaseJavaWithJavac FAILED'

### ISSUE THREAD

**Issue by 3LP** [react-community/react-native-maps#117]
Hello, I am running react-native v0.20, I followed the installation instructions, using **rnmp** **link.**  I am using Genymotion Emulator, Samsung S6.  I have used my API key for AndroidManifest.xml.  When I **react-native** **run-android** I receive the message that the Build Fails.  However, the App runs in the emulator, but the Map is blank, absent...not there.  I have all the proper API's and Google Play enabled in Google Developer console.  This is the warning I am getting,

`:react-native-maps:processReleaseJavaRes UP-TO-DATE
:react-native-maps:compileReleaseJavaWithJavac
/Users/ggt/corporate/netconnect/dev/activily/react-native/Droid/Activily/node_modules/react-native-maps/android/src/main/java/com/AirMaps/AirMapPolygon.java:32: illegal start of type
        this.coordinates = new ArrayList<>(coordinates.size());
                                         ^
/Users/ggt/corporate/netconnect/dev/activily/react-native/Droid/Activily/node_modules/react-native-maps/android/src/main/java/com/AirMaps/AirMapView.java:51: illegal start of type
    private ArrayList<AirMapFeature> features = new ArrayList<>();
                                                              ^
/Users/ggt/corporate/netconnect/dev/activily/react-native/Droid/Activily/node_modules/react-native-maps/android/src/main/java/com/AirMaps/AirMapView.java:52: illegal start of type
    private HashMap<Marker, AirMapMarker> markerMap = new HashMap<>();
                                                                  ^
/Users/ggt/corporate/netconnect/dev/activily/react-native/Droid/Activily/node_modules/react-native-maps/android/src/main/java/com/AirMaps/AirMapView.java:53: illegal start of type
    private HashMap<Polyline, AirMapPolyline> polylineMap = new HashMap<>();
                                                                        ^
/Users/ggt/corporate/netconnect/dev/activily/react-native/Droid/Activily/node_modules/react-native-maps/android/src/main/java/com/AirMaps/AirMapView.java:54: illegal start of type
    private HashMap<Polygon, AirMapPolygon> polygonMap = new HashMap<>();
                                                                     ^
/Users/ggt/corporate/netconnect/dev/activily/react-native/Droid/Activily/node_modules/react-native-maps/android/src/main/java/com/AirMaps/AirMapView.java:55: illegal start of type
    private HashMap<Circle, AirMapCircle> circleMap = new HashMap<>();
                                                                  ^
/Users/ggt/corporate/netconnect/dev/activily/react-native/Droid/Activily/node_modules/react-native-maps/android/src/main/java/com/AirMaps/SizeReportingShadowNode.java:25: illegal start of type
        HashMap<String, Float> data = new HashMap<>();
                                                  ^
7 errors
:react-native-maps:compileReleaseJavaWithJavac FAILED`

**Comment by christopherdro** [comment]
@3LP Any chance you can revert your changes from running `rnpm` and try adding the project manually?

**Comment by kcfgl** [comment]
I'm actually having the same issue.  It is failing to build at this line: 

`:react-native-maps:compileReleaseJavaWithJavac FAILED`

I'm sure I'm missing something, was a solution to the problem every worked out?  Thanks.

**Comment by mcconkiee** [comment]
i'm having the same issue - tried installing manually

**Comment by rdmchenry** [comment]
same issue here too

**Comment by avspeed** [comment]
Any help with this ? I am running into the same exact issue ?

Thanks

**Comment by rdmchenry** [comment]
I updated my Java, Gradle and react-native versions to the latest and I am no longer getting the build error and am now seeing the Google play services not installed error message in place of the map which is expected as I am running in the visual studio Android emulator which does not have play services installed.

**Comment by GuelorEmanuel** [comment]
Did anyone solve this issue?

**Comment by gilbox** [comment]
@rdmchenry installing Google play services is a requirement to run in emulator

**Comment by rdmchenry** [comment]
Yes, I know. I just didn't get that far but did get past the build error.

Ryan McHenry
Get Outlook for Android



On Wed, Oct 26, 2016 at 12:56 PM -0700, "Gil Birman" <notifications@github.com<mailto:notifications@github.com>> wrote:


@rdmchenry<https://github.com/rdmchenry> installing Google play services is a requirement to run in emulator

-

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
