### ISSUE TITLE
How Can I get Current Location Lat long in react native-maps

### ISSUE THREAD

**Issue by lavarajallu** [react-community/react-native-maps#1183]
Please Click it once and Read more

http://stackoverflow.com/questions/43176862/how-can-i-get-current-location-latlong-in-react-native-maps

Thanks in Advance

**Comment by Vivekburada** [comment]
import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants, Location, Permissions } from 'expo';

export default class App extends Component {
  state = {
    locationResult: null
  };

  componentDidMount() {
    this._getLocationAsync();
  }

  _getLocationAsync = async () => {
   let { status } = await Permissions.askAsync(Permissions.LOCATION);
   if (status !== 'granted') {
     this.setState({
       locationResult: 'Permission to access location was denied',
     });
   }

   let location = await Location.getCurrentPositionAsync({});
   this.setState({ locationResult: JSON.stringify(location) });
 };

  render() {
    return (
      <View style={styles.container}>
        <Text>
          Location: {this.state.locationResult}
        </Text>
      
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
});

**Comment by alvelig** [comment]
see https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
