### ISSUE TITLE
followsUserLocation not updating visible region

### ISSUE THREAD

**Issue by alexthegoodman** [react-community/react-native-maps#1186]
Is this guy missing something somewhere? Probably.

followsUserLocation is not functioning (and on a side-note, neither is the location button). Could there be some sort of conflict between settings like scrollEnabled, onRegionChangeComplete, or the Google Provider? Thoughts? showsUserLocation does work correctly by the way.

`<MapView
                    provider={PROVIDER_GOOGLE}
                    style={styles.mapView}
                    onPress={this.mapPress}
                    onRegionChangeComplete={this.checkLocation}
                    showsUserLocation={true}
                    followsUserLocation={true}
                    showsCompass={true}
                    loadingEnabled={true}
                    height={height}
                    ref={(ref) => this._map = ref}
                    initialRegion={{
                        latitude: parsePosition.coords.latitude,
                        longitude: parsePosition.coords.longitude,
                        latitudeDelta: LATITUDE_DELTA,
                        longitudeDelta: LONGITUDE_DELTA,
                    }}
                >`

Thanks a bunch!

**Comment by alexthegoodman** [comment]
Any updates here?

**Comment by alvelig** [comment]
Please fill up the issue according to the new template if the issue still persists.
