### ISSUE TITLE
Blank screen with array of markers as coordinates

### ISSUE THREAD

**Issue by topher** [react-community/react-native-maps#1189]
I'm attempting to render a list of markers from a container but its not rendering. Not sure where the issue is assuming its in the formatting of my props

```
// Presentational View
const LBTopView = (props) => {
  console.log(props, 'Props from LBTopView Presentational component')
  return (
    <ScrollableTabView
      tabBarPosition='overlayBottom'
      style={styles.scrollableTabViewStyle}
    >
      <MapView
        region={props.region}
        onRegionChange={props.onRegionChange}
      >
        {props.markers.map(marker => (
          <MapView.Marker
            coordinate={marker}
            // title={marker.title}
            // description={marker.description}
          />
        ))}
      </MapView>
        <Icon name="bar-chart" size={50} color={'#000000'} style={styles.photo} />
        <Icon name="vcard-o" size={50} color={'#000000'} style={styles.photo} />
    </ScrollableTabView>
  );
};
```

![screen shot 2017-04-04 at 7 10 44 pm](https://cloud.githubusercontent.com/assets/20007602/24686773/ba71d744-196a-11e7-908f-b577076a5792.png)
![screen shot 2017-04-04 at 7 22 31 pm](https://cloud.githubusercontent.com/assets/20007602/24687040/3f6b7616-196c-11e7-847c-3464785bea29.png)

**Comment by nmquebb** [comment]
Markers use `{ latitude: x, longitude: y }`so you'd need:

```
...

const coords = {
  latitude: marker.lat, 
  longitude: marker.lon
};

return <MapView.Marker coordinate={coords} />

...
```

Also be sure that `styles.scrollableTabViewStyle` has `{ flex: 1 }` to cover the page.

**Comment by alvelig** [comment]
@nmquebb's answer + `<MapView style={StyleSheet.absoluteFillObject} ... />

**Comment by Jun711** [comment]
When I map a list of markers, instead of [this](https://github.com/react-community/react-native-maps#rendering-a-list-of-markers-on-a-map ), I need to have a return statement inside the map function to make it work. 

```
<MapView
  region={this.state.region}
  onRegionChange={this.onRegionChange}
>
  {this.state.markers.map(marker => (
    return(<MapView.Marker
      coordinate={marker.latlng}
      title={marker.title}
      description={marker.description}
    />)
  ))}
</MapView>
```
