### ISSUE TITLE
[!] No podspec found for `React` in `../../node_modules/react-native`

### ISSUE THREAD

**Issue by davidhenley** [react-community/react-native-maps#1197]
Using the example Podfile, I get this when running pod install in ios folder.

react-native 0.42.3

**Comment by moronicgeek** [comment]
Ran into this myself. Try changing the path to the node_modules folder

Mine was ../node_modules/react-native

**Comment by hansfpc** [comment]
Same problem here

**Comment by hansfpc** [comment]
[!] No podspec found for `react-native-google-maps` in `../../`
 now

**Comment by esvignolo** [comment]
same problem :(

**Comment by tuneZola** [comment]
Why do you need these lines in the Pod file

`
# pod 'react-native-maps', path: './../'
# pod 'react-native-google-maps', path: './../node_modules/react-native-google-maps'  
`

Both don't contain Podfiles and will fail? I also didn't have the need for them in previous versions?

**Comment by esvignolo** [comment]
Nop, only because i don't want use gmaps on iOS. I comment this lines (#)

**Comment by raymallperez** [comment]
Same here, I need to use Google Maps for this and I'm getting this error.

**Comment by pjamrozowicz** [comment]
@raymallperez Copy these files:
https://github.com/airbnb/react-native-maps/blob/master/react-native-google-maps.podspec
https://github.com/airbnb/react-native-maps/blob/master/react-native-maps.podspec
into your project and then edit your Podfile accordingly (edit paths to these files).

It looks like that for me (part with pod paths):
`pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'`
`pod 'React', path: '../node_modules/react-native', :subspecs => [`
   ` 'Core',`
 `   'RCTActionSheet',`
`    'RCTAnimation',`
  `  'RCTGeolocation',`
 `   'RCTImage',`
 `   'RCTLinkingIOS',`
`    'RCTNetwork',`
   ` 'RCTSettings',`
`    'RCTText',`
   ` 'RCTVibration',`
  `  'RCTWebSocket'`
`  ]`

 ` pod 'GoogleMaps' `
 ` pod 'react-native-maps', path: '../'`
 ` pod 'react-native-google-maps', path: '../' `

**Comment by rifuso** [comment]
I found that those podspec files have references to the package.json of their respective projects so copying them as-is will result in an error. These lines are problematic

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
s.version      = package['version']

You can delete the first one and in the second one set it manually to "0.15.0"

**Comment by mattwoolnough** [comment]
run `npm install` in the example directory to install the files into node_modules before running `pod install` in the example/ios directory.

**Comment by AshokICreate** [comment]
_1. Setup Example Project First [](https://github.com/airbnb/react-native-maps/blob/master/docs/examples-setup.md)
2. Point yoga and react correct location.
3. if you getting this error at this stage_ 

> No podspec found for `react-native-google-maps` in `../../`

Copy `react-native-google-maps.podspec` and `react-native-maps.podspec` to location where your package.json file present.

Make Sure it's present at below location.
  `pod 'react-native-maps', path: '../'
  pod 'react-native-google-maps', path: '../'`

```
# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

# Change 'MapAppMobile' to match the target in your Xcode project.
target 'MapAppMobile' do

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../'
  pod 'react-native-google-maps', path: '../'  # <~~ if you need GoogleMaps support on iOS

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end

```

**Comment by Twinski** [comment]
This kind of stuff has been bugging me for a while now and I found out that my npm is acting "weird". 

If I do "npm install", it installs some stuff but "node_modules/react-native" stays empty which is weird and unwanted effect.. 

"yarn install" does the trick for me! The "node_modules/react-native" gets filled properly with its sourcefiles. 

So try to run "yarn install" and then "cd ios" and "pod install".
Tadaaa!

**Comment by Tom29** [comment]
got this error

> [!] Unable to satisfy the following requirements:
> 
> - `React/BatchedBridge (from `../node_modules/react-native`)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native`)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
> 
No matter what i've tried

**Comment by Tom29** [comment]
@pjamrozowicz why there is no `'BatchedBridge'`
I've done the same but got this error: #1434 
But follow the 1434 instruction, i got `React/BatchedBridge (from../node_modules/react-native) required by Podfile`

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by bamne123** [comment]
It requires exact path for the podspec file, so just specify path it ios folder. It will work fine.

**Comment by fedeghe** [comment]
@alvelig worked for me.... thank You... I roamed too much for that

**Comment by aryalprakash** [comment]
Adding pod like this solved my issue.
`pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'`

**Comment by joshsiegl1** [comment]
In my case just a simple `yarn install` didn't do the trick, I actually had to remove the node_modules folder and do a fresh install. I think the reason is because I was mixing `npm install save "..."` with yarn commands. 

Removing node_modules and doing a fresh install worked for me.

**Comment by jdavidteki** [comment]
I just added /ios after ../node_modules/react-native-firebase in my podfile and the error cleared

**Comment by jbburf** [comment]
I'm still seeing this issue after automatically upgrading with `react-native upgrade` and a full delete and rebuild on node_modules

**Comment by cyb3rsalih** [comment]
adding `  pod 'RNSVG', :path => "../node_modules/react-native-svg/"` to pod file solves my problem

**Comment by abduliOS** [comment]
I have Same issue,After running long hours , Accidentally removed this package from package.json again i am adding now it is working fine..

If it is  remove for some reason means ,just remove this line from podfile and do "rm -rf pods/ && pod install" it will work

**Comment by francorobles** [comment]
Experienced this. In my case, it was a missing package.

**Comment by ciaranmccaughey** [comment]
What worked for me was using yarn instead of npm. 

I ran `yarn add react-native-maps -E` instead of `npm install react-native-maps`. 

The package was missing under node_modules folder, using yarn did the trick.

**Comment by ghetinavlad** [comment]
> What worked for me was using yarn instead of npm.
> 
> I ran `yarn add react-native-maps -E` instead of `npm install react-native-maps`.
> 
> The package was missing under node_modules folder, using yarn did the trick.

worked for me... thanks a lot mate

**Comment by hrdyjan1** [comment]
> What worked for me was using yarn instead of npm.
> 
> I ran `yarn add react-native-maps -E` instead of `npm install react-native-maps`.
> 
> The package was missing under node_modules folder, using yarn did the trick.

Unbelievable.... We ran `yarn add react-native-maps` on Windows and made the same mistake. After we turned it down on MacOS `yarn add react-native-maps` the error disappeared.

**Comment by Nikita-Shuminskiy** [comment]
help me plz! 

<img width="925" alt="Image" src="https://github.com/user-attachments/assets/861a82b3-525c-4992-91e3-b5fcab079203" />

**Comment by HarshitMadhav** [comment]
@Nikita-Shuminskiy  delete `pods folder`, `node_modules`, `yarn.lock` then yarn to reinstall node_modules and then run `pod install` again

**Comment by FavazSlider** [comment]
@Ahmed-Bilal-01  so what we can do?

**Comment by HarshitMadhav** [comment]
Resolved it by adding this to podfile, it mentioned in the documentation as well

```
# React Native Maps dependencies

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path
```

**Comment by KumuduniNisansalaAngammana** [comment]
Read important notes of  [https://github.com/react-native-maps/react-native-maps] , if fabric is disabled you cannot use react-native-maps  version > 1.21.0 

if  fabric is not disabled and react-native-maps  version > 1.21.0   fix issue with:
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path

my issue now :  cannot find interface declaration for 'RNMapsMarkerView'

**Comment by kquoc887** [comment]
Issue now : cannot find interface declaration for 'RNMapsMapView'

![Image](https://github.com/user-attachments/assets/bc254cb8-115e-44f3-8821-a983ab2d9e4d)

=> I’m also experiencing the same issue. How can I fix this error?

**Comment by IKESI21** [comment]
> Resolved it by adding this to podfile, it mentioned in the documentation as well
> 
> ```
> # React Native Maps dependencies
> 
> rn_maps_path = '../node_modules/react-native-maps'
> pod 'react-native-maps/Google', :path => rn_maps_path
> ```

Make sure after that to:

`rm -rf Pods/ Podfile.lock`

**Comment by Klencodes** [comment]
"expo": "~54.0.2",

CHANGE  
pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
TO
  pod 'react-native-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
