### ISSUE TITLE
react-native link corrupts the APPNAME.xcodeworkspace file

### ISSUE THREAD

**Issue by moronicgeek** [react-community/react-native-maps#1198]
Hey there,

Tried installing react native maps in an iOS project but following the automatic instructions.
npm install --save react-native-maps 
Then ran 
React-native link react-native-maps

Then tried to open APPNAME.xcodeworkspace file for my app and get an error saying that the file is corrupted

**Comment by mtt87** [comment]
+1 For me it's corrupting `YOUR_APP.xcodeproj`

**Comment by guoliang1206** [comment]
+1 same problem ,cannot parse your project file

**Comment by Violetdusk** [comment]
+1 same problem.

**Comment by jtewright** [comment]
Yep, in my case it had done this:

Which should be like this:
```
HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native-userdefaults-ios""$(SRCROOT)/../node_modules/react-native-social-share/iOS";
```
```
HEADER_SEARCH_PATHS = (
					"$(SRCROOT)/../node_modules/react-native-userdefaults-ios",
					"$(SRCROOT)/../node_modules/react-native-social-share/iOS",
				);
```

**Comment by alvelig** [comment]
airbnb#1313
Also you may try: https://github.com/alvelig/react-native-maps-pods-example
