### ISSUE TITLE
Fix image based marker size example in production

### ISSUE THREAD

**Issue by sytolk** [react-community/react-native-maps#1205]
When I render CachedMap.js with image marker example:
https://github.com/airbnb/react-native-maps#image-based-markers
I have this issue:
https://github.com/airbnb/react-native-maps/issues/725
in emulator:
![device-2017-04-04-164053](https://cloud.githubusercontent.com/assets/1415463/24788103/5adcbef0-1b74-11e7-962f-b63625703e22.png)
in real device:
![screenshot_2017-04-04-16-34-03-003_com test1](https://cloud.githubusercontent.com/assets/1415463/24788121/71b5d2a6-1b74-11e7-9eec-ae91811f6eab.png)

What is the best option to fix this issue in examples ?

**Comment by alvelig** [comment]
#1476
