### ISSUE TITLE
Add image as overlay

### ISSUE THREAD

**Issue by AdrianZghibarta** [react-community/react-native-maps#1212]
Hi guys .. first of all, thanks for an awesome library. I have one small question. There is any possibility to add images as overlay on the map? I saw that you can draw your own polygon, but haven't see the documentation for adding an image as overlay. Thanks.

**Comment by fmelp** [comment]
+1

**Comment by yoongfook** [comment]
+1

**Comment by markmssd** [comment]
+1

**Comment by codedre** [comment]
@AdrianZghibarta  I was able to achieve this by using [MapTIler](https://www.maptiler.com) to generate tiles that line up over the map. Once you host them copy the xyz url and use 
`MapView.UrlTile urlTemplate={http://c.tile.openstreetmap.org/{z}/{x}/{y}.png} />`

**Comment by alvelig** [comment]
Duplicate #1030

**Comment by alvelig** [comment]
Duplicate of #103
