### ISSUE TITLE
Google Street View and my position

### ISSUE THREAD

**Issue by imanc** [react-community/react-native-maps#1217]
Hi,
I0m not sure this is the place to ask for this, sorry if I am wrong. 
Is there the street view functionality anywhere?
Is there a bug in show the user position button or compass?

Thank you

**Comment by scotbond** [comment]
Here you go https://www.npmjs.com/package/react-native-streetview

**Comment by chrise86** [comment]
Sorry to drag up an old issue, but has anyone managed to get street view working at all?

**Comment by vkumarNobul** [comment]
+1. Am planning to implement this soon. Anyone who does this before can guide would be appreciated.

**Comment by vincentvella** [comment]
The issue I've found with using that package in the past (at least 2-3 months ago) was that there's no "Streetview unavailable for that location" callback which leads to a lot of black/blank screens if the user does not explicitly press on the road. I believe that package might need a little TLC to implement into RN Maps.

**Comment by vkumarNobul** [comment]
@vincentvella , thanks for the heads up. That helps.

**Comment by BrodaNoel** [comment]
Anyone found an alternative way to implement this?

**Comment by danharper83** [comment]
I'd like this feature otherwise I'm stuck with webview. Is it possible to make it work with this library? I'd be interested in sponsoring this.
