### ISSUE TITLE
Google Map install -> 'AIRMapCoordinate.h' file not found

### ISSUE THREAD

**Issue by Panda313** [react-community/react-native-maps#1218]
Hi guys,

First : thanks for the amazing job. The lib is really sweet !

It works fine for plan on iOS but I wanted to switch to gmap. I manually installed google map in the project, works fine. But when I follow the steps to install gmap handling in react-native-maps I got this error. Exactly, I just drag&droped the folder AirGoogleMap into my xcode project, added the mentionned path in the Header Search Path and made it recursive

Any idea ? It's weird because this file is in AirMap lib...

Config : 
"react": "^15.4.2",
"react-native": "^0.42.2",
"react-native-maps": "^0.14.0"

Cheers

**Comment by hemedani** [comment]
using version 0.13.1

**Comment by kesha-antonov** [comment]
+1

**Comment by colus001** [comment]
Having same problem after upgrading 0.13.0 to 0.14.0 +1

**Comment by Benjamin-Dobell** [comment]
The path to the AirMaps headers in your node_modules has changed. In your iOS project update your target's `Build Settings -> Header Search Paths` to include:

```
$(SRCROOT)/../node_modules/react-native-maps/lib/ios/AirMaps
```

Previously it was `$(SRCROOT)/../node_modules/react-native-maps/`.

**Comment by melvynkim** [comment]
@Benjamin-Dobell Thank you very much. You cured my morning headache today :)

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by MuhammadNayabButt** [comment]
I tried lot of things and in the end I realised not one answer was enough. So I compiled and write it into an article . I tried my best and hope it will help everyone
https://medium.com/@nayabbutt1/google-maps-in-react-native-ios-application-3e27eece15b4
