### ISSUE TITLE
Marker rotation

### ISSUE THREAD

**Issue by fmelp** [react-community/react-native-maps#1221]
Hi there, are there any ways for custom markers to follow the rotation of the map?

I have tried implementing it with an Animated custom marker view and I can get it to rotate to any desired angle, but it's useless as I cannot figure out the heading of the map. The region spit out by on region change doesn't contain the map rotation details and maybe I'm being stupid, but can't think of any way to derive it. 

Even bearing angle doesn't make sense because it doesn't account for the rotation of the map, just the angle between two points.

Thanks in advance for any help

![screen shot 2017-04-07 at 14 20 25](https://cloud.githubusercontent.com/assets/5041936/24836803/0ebfa6dc-1d26-11e7-8767-da6f2a100775.JPG)

**Comment by the-simian** [comment]
I think this would be doable with some transform code if we could just read the Map rotation, but unfortunately: https://github.com/airbnb/react-native-maps/issues/487 I think that's unsupported.

**Comment by aaronbuchanan** [comment]
#1544 makes this doable, right?

**Comment by the-simian** [comment]
@aaronbuchanan I don't know, there's a possibility this feature might finally be implemented. I opened a thread about this directly a little over a year ago (referenced above) in case anyone found a way to make it work

**Comment by alvelig** [comment]
#1544 should close that

**Comment by ThiBsc** [comment]
You can do this to have a `Marker` who is following the map rotation (for example direction in a navigation):

```jsx
const MyMap = ({}) => {

  const mapView = useRef<MapView>();
  const [myLocation, setMyLocation] = useState();

  const setMyPositionRotation = async () => {
    // Here get your Location {latitude, longitude}, call it newLocation
    let camera = await mapView.current?.getCamera();
    let realHeading = newLocation.heading - camera?.heading;
    newLocation.heading = realHeading;
    setMyLocation(newLocation);
  }

  return (
    <MapView ref={mapView}>
      <Marker
          icon={require("myMarker.png")}
          coordinate={myLocation}
          rotation={myLocation.heading}
      />
    </MapView>
  )
}
```
