### ISSUE TITLE
Map loading 

### ISSUE THREAD

**Issue by thiagoterleski** [react-community/react-native-maps#1228]
Hi, using the prop `loadingEnabled` how can I get the finish loading event?

**Comment by januszdotnl** [comment]
I was actually looking for something similar. Such a helper would be nice however you can also solve it by using an if statement to make sure you have the necessary data / the map is loaded.

For example:
`class SomeMap extends React.Component {
  constructor() {
    super()
    this.state = {
      isLoaded: false
    }
  }

  componentDidMount() {
    this.setState({ isLoaded: true })
  }

  renderMap() {
    if (this.state.isLoaded) {
      return (
        <MapView
          initialRegion={initialPosition}
        >
        </MapView>
      )
    }
    return (
      <Text>Loading...</Text>
    )
  }

  render() {
    return (
      this.renderMap()
    )
  }
}`

Something very similar could be done with Redux. I had the issue that I first needed to get the GPS coordinates before rendering the map to prevent any errors or other goofy stuff. So next to the necessary GPS data I also added a "positionReady" boolean which I used together with the solution above.

**Comment by alvelig** [comment]
There's `onMapLoaded` event now.

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by saravanakumargn** [comment]
try with `onMapReady`
