### ISSUE TITLE
Adding an overlay inside marker

### ISSUE THREAD

**Issue by neilakoh** [react-community/react-native-maps#1229]
Is there a way to add an overlay inside marker? I am planning to add a circle overlay inside marker so that when marker moves the circle overlay follows (user radius) . . currently I created them as separate component and it is a bit heavy also the overlay moves fast leaving the marker behind because there is no animation for overlays and my marker is animated.

Thank you so much . . by the way I love the new props you guys added. :)

**Comment by neilakoh** [comment]
Hi guys, any update? It would be nice as a feature to add radius in marker.

**Comment by alvelig** [comment]
No, circle is not possible see #129
