### ISSUE TITLE
Android blinking black on load

### ISSUE THREAD

**Issue by jrichardlai** [react-community/react-native-maps#123]
Before the map loads it seems there is some blinking for the map ( tried on Android 4.x, 5.x ), does anyone has the same issues too? I'm not that familiar with Android so not sure how to fix it, but found several issues on stackoverflow
- http://stackoverflow.com/questions/14419521/moving-mapfragment-surfaceview-causes-black-background-flickering
- https://code.google.com/p/gmaps-api-issues/issues/detail?id=4639
- http://void-developer.blogspot.com/2013/07/prevent-flickering-mapfragment-in.html
  A workaround I'm using for now is using the litemode, https://github.com/lelandrichardson/react-native-maps/compare/master...jrichardlai:android-with-litemode?expand=1
  Not sure if this fit in the react-native-maps project.
  Also I'm not sure if this the best way to do it, I could not find a way to pass params to the ViewManager before instantiating the views by using props, feedback appreciated.

Thanks!

**Comment by christopherdro** [comment]
@jrichardlai Is this still an issue?

**Comment by jrichardlai** [comment]
Yes it still happens for me, is there anything special to set up the MapView for Android to not have the black blinking?

**Comment by christopherdro** [comment]
Hmm, are you trying on a device or through the simulator?

Also, what version of RN are you on?

**Comment by jrichardlai** [comment]
Both on device and simulator, I was on RN 0.21, but upgraded to 0.22 and same issue

**Comment by christopherdro** [comment]
I think this is more a device issue. @lelandrichardson Any thoughts on exposing an api for lite mode?
https://developers.google.com/maps/documentation/android-api/lite#intents_to_launch_a_map_view_or_directions_request

**Comment by jrichardlai** [comment]
So you don't have this issue? I'm gonna try out more phones tomorrow and let you know if it happens across the board for me. I'm gonna try the example app see if shows the same behavior.

**Comment by christopherdro** [comment]
Nope, never came across this one yet. 
Keep us posted.

**Comment by jrichardlai** [comment]
Hey, I tried on multiple phones the project example from react-native-maps and the issue seems to happen in all the phones we have here is a recording for 3 phones. ( it happens for the last one too but was shorter and the frame got dropped )

![out](https://cloud.githubusercontent.com/assets/159813/14030135/49315d72-f1c3-11e5-8a05-d85c8dab334d.gif)

**Comment by christopherdro** [comment]
@jrichardlai Not quite sure if I would consider that a bug. It just looks like the view loading.

**Comment by jrichardlai** [comment]
Ok, just wanted to check if that was the expected behavior. Yes I don't think its a bug either, but it feels unpleasant to have this black, was just checking if you knew a way to remove it ( change the color maybe).
Thanks again on checking in!

**Comment by lelandrichardson** [comment]
@jrichardlai is there a common way this effect is skirted around in traditional android development?  It's not clear to me what the fix is - but it seems like it could be hacked around by displaying a view while the map loads or something.

I'm open to potential workarounds.

I'm not sure, but this PR might help out: https://github.com/lelandrichardson/react-native-maps/pull/91

**Comment by jrichardlai** [comment]
Thanks! I'm gonna take a look and see if that works for us, the staggering/lagging is the reason why I used liteMode.

**Comment by jrichardlai** [comment]
@lelandrichardson it actually resolve the blink, but had to change the logic to have the loader even when not wanting to cache ( still want sometimes to scroll and have the location button )

**Comment by benjaminbillet** [comment]
@jrichardlai Hi, how did you solved the problem? I still have the issue (with the emulator, a Galaxy Nexus and a Nexus 5X).

**Comment by jrichardlai** [comment]
@benjaminbillet using caching the black stripe one gets fixed https://github.com/lelandrichardson/react-native-maps/pull/91

**Comment by benjaminbillet** [comment]
@jrichardlai But caching is not part of the master branch, is it?

**Comment by Daniellt1** [comment]
@jrichardlai Have you solved that? 

I have the same kind of blinking on Android 5.x devices. Even with enabled caching.

**Comment by Kerumen** [comment]
Same problem here. It seems to have come back with the latest version of the Google Maps SDK.

**Comment by alvelig** [comment]
This should be solved as for 0.19.0
