### ISSUE TITLE
Update latitude/longitude delta not changing zoom

### ISSUE THREAD

**Issue by foyarash** [react-community/react-native-maps#1233]
Hi,

I am trying to limit the zoom on my map.

I have something like this:

`
<MapView
          style={MapStyle.map}
          region={this.state.region}
          loadingEnabled={true}
          showsUserLocation={true}
          onRegionChange={(region) => this.onRegionChange(region)}
        />
`

My onRegionChanged function looks like this

`
onRegionChange(region) {
    if (region.latitudeDelta > this.maxLatitudeDelta) {
      region.latitudeDelta = this.maxLatitudeDelta;
    }
    if (region.longitudeDelta > this.maxLongitudeDelta) {
      region.longitudeDelta = this.maxLongitudeDelta;
    }
    this.setState({region});
  }
`

My region object has correct values when i unzoom too far away, but yet, my map keeps the same zoom, as i want it to be bounced to the values i defined.

What am I doing wrong?

**Comment by frmdstryr** [comment]
I don't think it works on iOS

**Comment by foyarash** [comment]
That's something i tried, but the problem is that it triggers infinitly the onRegionChange callback. Can you share some working code?

**Comment by PARAGJYOTI** [comment]
! From your code it seems you are setting a maxvalue for delta , which implies if the region delta is goes beyond the max delta value , keep it there at the max-zoom lavel . That is what happening . So , you Either remove the condition or increase the maxDelta values .

**Comment by foyarash** [comment]
Actually, my problem is that the setState seems to have no impact for the latitude/longitude delta, so removing the conditions or increasing the max delta values won't have any impact i guess.

**Comment by PARAGJYOTI** [comment]
@foyarash  Try onRegionChangeComplete instead of onRegionChange . It should work . And make sure you updated all params including lat and long value besides deltas .

**Comment by foyarash** [comment]
Your solution does not change anything, my region object has the good values but the setState changes nothing

**Comment by BaptWaels** [comment]
@foyarash Have you found a solution for this ?

**Comment by foyarash** [comment]
@BaptWaels nope, i didnt touch to this feature since some time, but i'm gonna try to do this in a native way

**Comment by foyarash** [comment]
I'm going to work on a fix for that, will submit a PR as soon as i finished the work

**Comment by foyarash** [comment]
Hey guys,

Here is the PR for handling zoom level https://github.com/airbnb/react-native-maps/pull/1360

Please submit any comment about what can be done better, especially for ios as that's my first time doing obj-c

**Comment by ramneekhanda** [comment]
You can do something like this to get bounding region for a marker?

getBoundingCoordinates(coordinate, distanceInKM) {
    var move = (coordinate, directionDegree, lengthDegree) => {
      x = coordinate.longitude + lengthDegree * Math.cos(directionDegree * Math.PI / 180);
      y = coordinate.latitude + lengthDegree * Math.sin(directionDegree * Math.PI / 180);
      return { latitude: y, longitude: x };
    }

    var distanceDegree = distanceInKM / 111; // each degree = 111 km
    var top = move(coordinate, 0, distanceDegree);
    var right = move(coordinate, 90, distanceDegree);
    var bottom = move(coordinate, 180, distanceDegree);
    var left = move(coordinate, 270, distanceDegree);
    return [top, left, right, bottom];
  }

**Comment by alvelig** [comment]
See example: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
