### ISSUE TITLE
[Android] Example setup not working?

### ISSUE THREAD

**Issue by lbrdar** [react-community/react-native-maps#1235]
Hi,

I'm trying to start the example from the repository, but I have issue with it. I have installed modules with npm and then tried following instructions given in the repo, but running "react-native run-android" from the example dir results in:

`Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.`

Running it from the root dir also doesn't work: 

`Android project not found. Maybe run react-native android first?`

I might be overlooking something trivial because I'm completely new to mobile development.

Thank you in advance,
Leo

**Comment by markshapiro** [comment]
Hey, just to see it working I did:
`npm i`, then `npm start` and `npm run run:android` at the same time,
saw it working on emulator with Google APIs.

**Comment by laiyifeng77** [comment]
I have the same problem with it.anyone knows why?

**Comment by alvelig** [comment]
https://github.com/alvelig/react-native-maps-example. `rm -rf node_modules` and `npm i` in your project (update to the most recent version)
