### ISSUE TITLE
'SMCalloutView.h' file not found on AirMaps.h import

### ISSUE THREAD

**Issue by topher** [react-community/react-native-maps#1236]
Not sure why my build is failing after following the install directions, and taking out the pod files for `react-native-maps` and `react-native-google-maps` after a duplicate error found https://github.com/airbnb/react-native-maps/issues/718

Now I get this error:
<img width="258" alt="screen shot 2017-04-12 at 4 52 25 pm" src="https://cloud.githubusercontent.com/assets/20007602/24984176/b69111c6-1fa0-11e7-9ddb-729ba636444f.png">

```
In file included from /path/to/project/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapUrlTileManager.m:15:
In file included from /path/to/project/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapMarker.h:17:
/path/to/project/node_modules/react-native-maps/lib/ios/AirMaps/AIRMap.h:14:9: fatal error: 'SMCalloutView.h' file not found
#import "SMCalloutView.h"
        ^
1 error generated.
```

My files are in the the AirMaps directory that I dragged in from `node_modules`, and then replaced with `RCTConvert+MapKit` `RCTConvert+AirMap` files recommended here https://github.com/airbnb/react-native-maps/issues/1193
<img width="258" alt="screen shot 2017-04-12 at 4 52 44 pm" src="https://cloud.githubusercontent.com/assets/20007602/24984159/a3fe5e42-1fa0-11e7-9aa5-9383409a9230.png">

` SMCalloutView.h` is located here
<img width="255" alt="screen shot 2017-04-12 at 4 53 38 pm" src="https://cloud.githubusercontent.com/assets/20007602/24984621/54e5948a-1fa3-11e7-8950-07b0733de6fc.png">

I've tried to bundle the app with `react-native bundle —platform ios —dev false —entry-file index.ios.js —bundle-output ./ios/release/main.jsbundle —assets-dest ./ios/release/main.jsbundle` which throws

`Scanning 806 folders for symlinks in /Users/chris/zelos/zelosApp/node_modules (12ms)
error: option '--entry-file' missing`

Not sure if this is the same or separate issues. Any thoughts?

**Comment by arabscimitar** [comment]
I faced the same problem 

1. make sure that you are building from your project main file
2. clean Your project

**Comment by jasonnathan** [comment]
This happened to me after upgrading to the latest version `"react-native-maps": "^0.15.2"`. I had to run:
`react-native unlink react-native-maps`
and then
`react-native link react-native-maps`

And it built successfully

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
