### ISSUE TITLE
Is there a callback when animation such as animateToCoordinate ends?

### ISSUE THREAD

**Issue by JLLLinn** [react-community/react-native-maps#1237]
I could not find any place that specifies if there is a callback when the animate ends. I need to do something when animateToCoordinate ends. Currently I am using a setTimeOut to do that but a neat way could be if there is a callback of animateToCoordinate.

**Comment by PARAGJYOTI** [comment]
It seems there's no such callback in animateToCoordinates , runCommand calls NativeModules.UIManager which is JAVA module with synchronus behaviour . So , setTimeOut for 500 ms is the only way to go .
``` 
 animateToCoordinate(latLng, duration) {
    this._runCommand('animateToCoordinate', [latLng, duration || 500]);
  }
```

**Comment by gopchi** [comment]
@PARAGJYOTI Could you specify how do you exactly use animateToCoordinate, because I get always an error "undefined is not a function"

I tried with this answer, but with no success - http://stackoverflow.com/questions/42032015/react-native-maps-how-to-animate-to-coordinate

**Comment by PARAGJYOTI** [comment]
@gopchi  Sure . Most probably you haven't passed a ref to the MapView Component . 
    You should set this.map to the ref ike this . 
```
<MapView
         style={styles.map}
         showsMyLocationButton={true}
         showsUserLocation={true}
         region={this.state.region}
         ref={ref => { this.map = ref; }}
         onRegionChangeComplete={this.onRegionChangeComplete.bind(this)}
       >....
</MapView>
```

And then call this.map.animateToCoordinates() like this .
```
 
 componentWillReceiveProps(np){
   
   if(this.props.markers!==np.markers){
     this.setState({markers:np.markers})
   }
   if(this.props.selectedMarkerId!==np.selectedMarkerId && this.state.markers.length>0){
     var marker=this.state.markers[np.selectedMarkerId]
     var Coords=marker.latlng
     
 ////////////////////////////////////////////////////
   
  this.map.animateToCoordinate(Coords)
     
//////////////////////////////////////////////////////


     this['marker'+[np.selectedMarkerId]].showCallout()
   }
   
 }
 ```

**Comment by gopchi** [comment]
@PARAGJYOTI Thanks, but I actually passed the ref but now that I see how you used it, maybe it is inappropriate for my use case. I use GEOLOCATION and get the current user coordinates. My idea is when the user (blue dot) moves, the map to be centered on its position.

So here is my code trying to achieve this:
`  constructor(props) {
    super(props)

    this.state = {
      currentPosition: {
        latitude: null,
        longitude: null
      }
    }

    this._getCoords = this._getCoords.bind(this);

  }


  componentDidMount() {
    
    this._getCoords()
  
}



_getCoords = () => {
      navigator.geolocation.getCurrentPosition(
                (position) => {
                  this.setState({
                    currentPosition: {
                      latitude: position.coords.latitude,
                      longitude: position.coords.longitude
                    }
                  })
                  this.map.animateToCoordinate(this.state.currentPosition)

                },
                (error) => alert(error.message),
                { timeout: 20000, maximumAge: 1000}
              );

          setInterval( () => {
              navigator.geolocation.getCurrentPosition(
                (position) => {
                  this.setState({
                    currentPosition: {
                      latitude: position.coords.latitude,
                      longitude: position.coords.longitude
                    }
                  })
                  this.map.animateToCoordinate(this.state.currentPosition)
                },
                (error) => alert(error.message),
                { timeout: 20000, maximumAge: 1000}
              );
          },5000)
}`
` <MapView.Animated
          style={styles.map}
          ref={ref => this.map = ref}
          showsUserLocation={true}
          loadingEnabled
          loadingIndicatorColor="#666666"
          loadingBackgroundColor="#eeeeee"
   >`

Note: I know that using setInterval on getting the updated position is not clean and I should use watchPosition, but I need the coordinates to update quite frequently and the watch function updates the coords after a couple of hundred metres...

**Comment by PARAGJYOTI** [comment]
@gopchi  You should set 
 var self=this , as this.map is within a function . You probably forgot to do that . If you are new this concept , here's what it looks like ,

   ```
_getCoords = () => {

 var self=this;
navigator.geolocation.getCurrentPosition(
(position) => {

   self.setState({
currentPosition: {
latitude: position.coords.latitude,
longitude: position.coords.longitude
}
})
 self.map.animateToCoordinate(this.state.currentPosition)

            },
            (error) => alert(error.message),
            { timeout: 20000, maximumAge: 1000}
          );

```

**Comment by gopchi** [comment]
Here is what I get after I do it that way:
![screenshot_2017-04-17-17-21-31](https://cloud.githubusercontent.com/assets/12885152/25091552/7bc28098-2392-11e7-9a1f-c68626338201.png)

**Comment by PARAGJYOTI** [comment]
@gopchi  I just noticed you are using a <MapView.Animated/> component , why ?  <MapView> will do everything as far as I know . and try removing timeout and maxAge for both cases . I tried your code , its working fine as i am using only <MapView/>

**Comment by JLLLinn** [comment]
@gopchi https://github.com/airbnb/react-native-maps/issues/1118#issuecomment-288688542 refer to this thread for calling that with the animation api.

**Comment by gopchi** [comment]
@PARAGJYOTI Sorry for the delay. I fixed it by removing the .Animated class.

**Comment by alvelig** [comment]
See #1620

**Comment by dben89x** [comment]
Simple solution, just set state:

```
onRegionChange = (region) => {
  if (this.state.animatingToMarker) {
    this.setState({animatingToMarker: false})
    this.doSomething()
  }
  this.setState({region: region})
}

animateMapToMarker = (e) => {
  const coordinate = e.nativeEvent.coordinate;
  var newRegion = {
    longitudeDelta: this.state.lonDelta,
    latitudeDelta: this.state.latDelta,
    longitude: coordinate.longitude,
    latitude: coordinate.latitude
  }
  this.setState({animatingToMarker: true})
  this._map.animateToRegion(newRegion, 500)
}

render() {
  return (<MapView
    ref={node => {this._map = node}}
    initialRegion={this.state.region}
    region={this.state.region}
    onRegionChangeComplete={this.onRegionChange}
    onMarkerPress={this.animateMapToMarker}
  </MapView>)
}

```
