### ISSUE TITLE
npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed

### ISSUE THREAD

**Issue by prasang7** [react-community/react-native-maps#1240]
**Problem**
I'm trying to install react-native-maps by Airbnb in my project. Installation instructions: [airbnb/react-native-maps/installation](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md)

when I run the following command in cmd: `npm install react-native-maps --save`
This is what I get: 
_`-- react-native-maps@0.14.0
npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed._

Ignoring this if I proceed with further installation, and run the following command: `react-native link react-native-maps`
This is what I get: 
_Scanning 561 folders for symlinks in C:\RNProjects\Mapp\node_modules (39ms)
rnpm-install info Linking react-native-maps ios dependency
rnpm-install info iOS module react-native-maps has been successfully linked_

^As we can see, only iOS related maps modules get installed. On checking the project directory, I was able to validate that no android related module was installed. 

**Troubleshooting**
Here's the list of thing I tried to resolve the issue, but none of them worked.

1. Tried installing `npm install react@15.4.0 --save`
Got these warnings: 
_npm WARN react-native@0.43.3 requires a peer of react@16.0.0-alpha.6 but none was installed.
npm WARN react-test-renderer@16.0.0-alpha.6 requires a peer of react@^16.0.0-alpha.6 but none was installed._
So, in order to resolve this, I tried installing react@16.0.0-alpha.6 with: `npm install react@16.0.0-alpha.6`. 
I got the same message again:
_npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed_.
 
2. Tried updating react-native `npm update react-native`.
Still getting the same warning message.

3. Tried installing the latest version of npm: `npm install npm@latest -g`.
Didn't work.

**Additional Information**

- react-native: 0.43.3
- react-native-cli: 2.0.1
- Platform: Android
- Development Operating System: Windows 10 OS

**Comment by PARAGJYOTI** [comment]
Dont worry , If peer dependencies aren't matched this throws unmet peer dependency error . But it will work . I too had the same issue .

**Comment by prasang7** [comment]
@PARAGJYOTI 
If I Ignore this and continue then there are two major issues. 

1. After running the following command: `react-native link react-native-maps`,
I get the following in cmd: 
_Scanning 561 folders for symlinks in C:\RNProjects\Mapp\node_modules (39ms)
rnpm-install info Linking react-native-maps ios dependency
rnpm-install info iOS module react-native-maps has been successfully linked_
^As we can see, only iOS related maps modules get installed. On checking the project directory, I was able to validate that no android related module was installed.

2. As mentioned here: [airbnb/react-native-maps/installation/android](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#android)
In the first instruction itself (_In your android/app/build.gradle add_: ..dependencies..) it says: _This step is not necessary if you ran "react-native link react-native-maps"_
But when I open the following gradle file using my editor, it appears that I do have to add these lines (stating that the android-related-modules of react-native-maps were not linked). When I add these lines manually, and run project, it throws errors.

**Comment by PARAGJYOTI** [comment]
Besides gradle you have to look for MainApplication.java . If MapsPackage() is included in the package there must be some problem in the version . I just upgraded to 0.14.0 and getting some error like Configuration with name default not found. It may be issue with the version . Try installing 0.12.5

**Comment by iiitmahesh** [comment]
@PARAGJYOTI  did u find any solution with new version?? 0.12.5 works fine

**Comment by pooya1361** [comment]
Same problem here!

**Comment by prasang7** [comment]
@PARAGJYOTI @iiitmahesh @pooya1361 Can someone please guide me on how to install the react-native-maps 0.12.5 version. I'm very new to the react-native. Thanks.

**Comment by PARAGJYOTI** [comment]
Don't worry guys , its totally normal to get a lots of errors during compiling with react-native run-android if you are new to react-native . I will guide you as far as I can . 
 There are some basic  things to be look carefully before you compile your app especially if you are beginner .  
    1) When you try to add a new library that's based on java into your app , they will tell you either to run react-native link some-package . What it does is simply adds some lines of codes to 3 different files , 
     First to the settings.graddle file , which contains the public path to the library in your node-modules folder . It somewhat looks like this .

           ` include ':react-native-maps'
             project(':react-native-maps').projectDir = new File(rootProject.projectDir,'../node_modules/react 
              native-maps/android')

              include ':react-native-fcm'
              project(':react-native-fcm').projectDir = new File(rootProject.projectDir, '../node_modules/react 
              native-fcm/android') `
    
   

  So , if you run react-native link react-native-maps it will automatically add the codes to settings.graddle .

  Again , 2nd is to the build.graddle file which in in the  app  directory , like  yourapp/android/app/build.graddle . Its the most important file that contains all build instructions to graddle . 
       I am pasting my entire (almost) build.graddle  script for your better understand .
         

    ` android {
       compileSdkVersion 25
     buildToolsVersion "23.0.1"
    
	    dexOptions {
      jumboMode = true
          }
	
    defaultConfig {
        applicationId "com.shopfort"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
		signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
	
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
			 signingConfig signingConfigs.release
            }
       }

       }
     }
          dependencies {   
         compile project(':react-native-vector-icons')
         compile project(':react-native-spinkit')
         compile project(':react-native-share')

         compile project(':react-native-linear-gradient')
    
          compile(project(':react-native-fcm')){
	  exclude group: "com.google.firebase" 
	  }
	  compile(project(':react-native-maps'))
	   {
	    exclude group: 'com.google.android.gms'
	     }
  
	
      compile ("com.google.firebase:firebase-core:9.8.0"){
	    force = true;
	  }
	compile ('com.google.firebase:firebase-messaging:9.8.0'){
	   	    force = true;
	}
 

	
	compile ("com.google.android.gms:play-services-base:9.8.0") {
        force = true;
         }
       compile ("com.google.android.gms:play-services-maps:9.8.0") {
        force = true;
        }
	
       compile ('com.google.android.gms:play-services-gcm:9.8.0') {
        force = true;
        }
	
     compile project(':react-native-fbsdk')
    compile project(':react-native-camera')
    compile project(':lottie-react-native')
    compile project(':gl-react-native')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
     }
    apply plugin: 'com.google.gms.google-services'`

   
##CompileSdk

So , Lets start with the first part CompileSdk version says with which version of sdk you want to compile the Scripts . Mine is 25 , note that its specially for react-native-maps .  Some days ago , airbnb implicitely  said to use compileSdk version 25 , but probably they removed it now from the documentation , but you rather try with 25 . 

#buildTools 

 The buildTools builds  the package and does everything . So before installing any library make sure you are using the proper version of build tools for that .  If that's not in your sdk package , which you can look for in the android studio sdk manager and download it . Some libraries may not tell you about anything , so you should go and check the build tools the package is using in node-modules folder within the app/build.graddle file . 
   Another thing to mind , that for the  appcompat package com.android.support:appcompat , (second line from last) you have to use the same version as buildTools  otherwise it will throw error .. As I am using build-tools 23.0.1 , so my appcompat has also the 23.0.1 version .  

  #dexOptions 

   Sometimes  you have to add dexOptions for enabling jumbo mode when you get errors like 
      UNEXPECTED TOP-LEVEL EXCEPTION:
      com.android.dex.DexException: Cannot merge new index 65536 into a non-jumbo instruction!  
  Sometimes you enable multidex , by multidex : true , and sometimes largeHeap : true for increasing memory uses .

#the signingConfigs 
    They are for releasing the  apk .  see https://facebook.github.io/react-native/docs/signed-apk-android.html for that.
         
#dependencies 👍 
     These dependecies are the the packages to be compiled . 
     every project get their path from the settings.graddle file that's been said earlier . 
   Now , some points to be noted , if you are using react-native-maps with some other google-services , a common problem may occour due to the version conflict of google-services , specially fcm (firebase cloud messaging) . To prevent that you have to exclude the group like   
      
       compile(project(':react-native-maps'))
	   {
	    exclude group: 'com.google.android.gms'
	   }
    
One thing to note again,  if you are using lower version  of gms than  the version used by react-native-maps , its wont gonna work . So , check it out in the node-modules/react-native-maps/android/app/build.graddle file , which version of gms it is using . If its 9.8.0 , you have to use the same or higher . 10.0.1 have some issues , so I suggest you to use 9.8.0 . 
 
 And lastly put the google-maps credentials on your menifest file .



 Here are some common issues faced when you are new to react-native . 
   
  1. Couldnot connect to the development server . (running on real-devices) or taking to much long while fetching data .
        Simply go the directory    /android/sdk/pltform-tools and run  'adb reverse tcp:8081 tcp:8081'
  
  2.Unfortunately app has been crashed on start . 
    It may due to many problems . You can try to log the issue by running adb logcat > somefile.txt 
  
3. Error thrown during predexDebug or dexDebug .
    if its not any bug in the java code , sometimes build may fail for unexpected reason. You can try running   `gradlew clean` on android directory .

4.couldnot create  directory 'somedirectory' 
    Its specially happens with google-services debug folder . It throws error saying couldn't delete directory debug in android/src/build/generated/debug . You have to simply delete the folder manually .

5. At the very end during release apk sometimes a error is thrown saying couldn't complete progressEvent . so you should run 'gradlew assembleRelease --console plain' 


These are some error I can remember at this moment .

Anyway , if you guys find other problem during installation I would be there . 
Happy learning , happy coding .  👍

**Comment by pooya1361** [comment]
@PARAGJYOTI  Thanks for a long troubleshooting guide.
I stuck here:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.
```

\androind\app\ **build.gradle** :
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 25
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.base10"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
  compile(project(':react-native-maps'))
   {
    exclude group: 'com.google.android.gms'
     }
     

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

android\ **settings.gradle** :

```
rootProject.name = 'base10'

include ':app'
include ':react-native-maps'
         project(':react-native-maps').projectDir = new File(rootProject.projectDir,'../node_modules/react-native-maps/android')
```

\android\app\src\main\java\com\base10\ **MainApplication.java** :
```
package com.base10;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

import com.airbnb.android.react.maps.MapsPackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new MapsPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

**Comment by PARAGJYOTI** [comment]
@pooya1361  There's nothing wrong in your code bro . Its just a issue of the package react-native-maps 0.14.0 . Simply Downgrade the version to 0.12.5 .  It will work fine .

**Comment by pooya1361** [comment]
I did so and now I get this error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:prepareComAndroidSupportAppcompatV72301Library'.
> Could not expand ZIP 'C:\Users\Haktiebolaget\AppData\Local\Android\sdk\extras\android\m2repository\com\android\support\appcompat-v7\23.0.1\appcompat-v7-23.0.1.aar'.```

**Comment by PARAGJYOTI** [comment]
@pooya1361  Try Twice or thrice . It should work . If not run cd android && gradlew clean . And build again . Its normal . Happened to me too.

**Comment by pooya1361** [comment]
@PARAGJYOTI 
I did what you said and it built successfully but now it breaks in the second window it opens with this message:
´´´
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactDebugCurrentFrame` from `c:\base10\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js`: Module does not exist in the module map or in these directories:
  c:\base10\node_modules\react-native\node_modules\react\lib
,   c:\base10\node_modules\react\lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.
    at p.catch.error (c:/base10/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:366:19)
Bundling `index.android.js`  96.2% (559/570), failed.´´´

I cleaned and rebuilt several times but it doesn't work :/

**Comment by pooya1361** [comment]
After a couple of hours struggling with the error, I deleted the whole project and created a new one and copied my files there. It finally compiled without error [Yeeay] but it shows nothing 😞 
I keep trying (fighting actually) later.

**Comment by PARAGJYOTI** [comment]
@pooya1361  oops you should have notice the error properly . it happend duo to unmeet peer dependency . So your current react version doesnot have the file required by the react-native library . So , you can get that file from an older version , or may be newer version of react . If you have further problems try using react-native 0.41.2 . Its the most stable version I have worked with if you doesn't really need all the latest components like Flatlist or VirtualizedList .

**Comment by prasang7** [comment]
@PARAGJYOTI Can you please tell me **how to downgrade react-native-map version to 0.12.5** . Thankyou.

**Comment by PARAGJYOTI** [comment]
npm i react-native-maps@0.12.5 --S

**Comment by pooya1361** [comment]
@prasang7 You can change it in package.json too

**Comment by PARAGJYOTI** [comment]
yes , if you do --S , it will automatically  get saved.

**Comment by prasang7** [comment]
Here's what I did (chronological order). 

1. Deleted **node_module** directory from the project. 
2. `npm cache clean`
3. Modified package.json with: _"react":"~15.4.1"; "react-native":"0.42.3"; "react-test-renderer":"15.4.1"_
4. `npm install all module`
5. `npm install`
6.  `npm i react-native-maps@0.12.5 --S`
7. `react-native link react-native-maps`

Once I do this, it's **successfully able to link the android and ios react-native-modules** to the project :)
Thank you @PARAGJYOTI @pooya1361

**Comment by prasang7** [comment]
But, even though I am successfully able to link the map modules, whenever I run `react-native run-android`, it throws the following error: 

**Execution failed for task ':react-native-maps:prepareComGoogleAndroidGmsPlayServicesMaps980Library'.
Could not expand ZIP 'C:\Android\sdk\extras\google\m2repository\com\google\android\gms\play-services-maps\9.8.0\play-services-maps-9.8.0.aar'.**

I searched about the error extensively on the internet, but couldn't find a probable cause. 
@PARAGJYOTI @pooya1361 Any idea what might be causing this error?

Here's the screenshot of my command prompt:
![8f0d295d-ff09-4fb3-ba6c-6ba5670e71c5](https://cloud.githubusercontent.com/assets/13434598/25170176/3c6e2e8a-2507-11e7-9e12-8ba6ebba1baf.jpg)

**Comment by PARAGJYOTI** [comment]
have you cleaned the build ? try
cd android && gradlew clean && cd .. && react-native run-android

actually sometimes it goes away after 2 3 trials .

**Comment by prasang7** [comment]
Yes, It worked like magic ❤️
Thank you.

**Comment by Biggestone** [comment]
@prasang7 I just cleaned gradlew and reset cache, after that I installed maps again. It works like a charm!

**Comment by phaptq** [comment]
I has success build in ios with tips:

init project with version 0.42.3 (to fix 'npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed').

skip step react-native link react-native-maps to use Option 3: Manually in the docs.

in Xcode open libraries -> right click AirMaps.xcodeproj -> add file to AirMaps -> go to find react-native-maps into node_module -> lib -> ios -> AirMaps -> select RCTConvert+MapKit.h/m -> add (to fix 'File RCTConvert+MapKit.m not found').

npm install --save-dev babel-plugin-module-resolver (to fix .babelrc cause error).

watchman watch-del-all. And rebuild project.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by suganthankumar** [comment]
Deleted node_modules and npm install worked.

**Comment by franva** [comment]
@suganthankumar savior! Deleted the folder and it works for me~!!!!

**Comment by DEV-Ahmedbakr** [comment]
Create empty folder called **react-native-elements** on node_modules                                                                                   and it works for me

**Comment by DYW972** [comment]
👋

When you see this type of warning, let NPM do the work simply by reseting your nodes-modules like this :

```
$ rm -rf node_modules package-lock.json
$ npm install
```
Let us know if it's working for you ...

Enjoy

🖖
