### ISSUE TITLE
(Android 7.1 API 25) Images aren't shown on Markers

### ISSUE THREAD

**Issue by pedrosimoes-nbr** [react-community/react-native-maps#1245]
Images aren't shown on Markers.

Hi, I'm developing an app for Android/iOS using the CRNA with Expo, that uses the react-native-maps@0.12.2 package.

All platforms run without any problem, except on Android 7.1+.

All images contained on Markers are not shown/loaded and the road names are not hidden using the google maps API JSON file.

Attached image showing the problem using two genymotion emulators:

At left: Android 7.0
At right: Android 7.1

![capture](https://cloud.githubusercontent.com/assets/26552384/25066161/a13fa486-2216-11e7-8d26-f7a086e9167d.PNG)

**Comment by alexHlebnikov** [comment]
Same problem here only on Android 7+. 

We using custom markers and they are visible in debug version. 
But in release version markers are disappears.

**Comment by AdrianZghibarta** [comment]
I have this issue on android 6.0.1 also

**Comment by scotbond** [comment]
make sure you size them with width and height.

**Comment by pedrosimoes-nbr** [comment]
yes, I have both defined in the style prop

**Comment by scotbond** [comment]
plz post your marker code. also try providing @2x @3x @4x image (just copy and rename).

**Comment by pedrosimoes-nbr** [comment]
I only have one image resolution available from the backend supplied using a uri.

```
return (
            <MapView.Marker
                identifier={ establishment.id }
                coordinate={{ 
                    latitude: establishment.latitude,
                    longitude: establishment.longitude,
                }}
                onPress={ e => {
                    e.stopPropagation();
                    NavigationState.push({
                        path: 'map.establishment',
                        data: establishment,
                    });
                }}
            >
                <View style={ styles.marker }>
                    <View style={ styles.markerInner }>
                        <View style={ styles.markerLeft }>
                            <Image 
                                source={{ uri: Settings.BACKEND_FOOD_CATEGORY_ICON(establishment.icon, 'darkgrey') }} 
                                style={ styles.markerIcon } />
                        </View>
                        <Text style={ styles.markerText }>
                            { establishment.name }
                        </Text>
                        <View style={ styles.markerRating }>
                            <Text style= { styles.markerRatingText }>
                                { establishment.rating.toFixed(1).toLocaleString() }
                            </Text>
                        </View>
                    </View>
                    <View style={ styles.markerArrowBorder } />
                    <View style={ styles.markerArrow } />
                    <Image 
                        source={ Images.SHADOW }
                        style={ styles.markerShadow }
                    />
                </View>
                <MapView.Callout>

                </MapView.Callout>
            </MapView.Marker>
        );
```

**Comment by scotbond** [comment]
From the Marker [doc file](https://github.com/airbnb/react-native-maps/blob/master/docs/marker.md):
"A custom image to be used as the marker's icon. Only local image resources are allowed to be used."
Anyway, it's a good practice to always pass the "image" prop into Marker (keep the children as is). it prevents missing images on Android.

**Comment by pedrosimoes-nbr** [comment]
Sorry, but I'm not using the Marker image prop ;) it is a marker with a custom view. https://github.com/airbnb/react-native-maps#rendering-a-marker-with-a-custom-view

Does it still need to have a local image defined as custom image/icon?

**Comment by scotbond** [comment]
See tugorez comment on #100

**Comment by hackdie** [comment]
+1

**Comment by pedrosimoes-nbr** [comment]
Well ... I'm realizing that this bug is very nasty, and others also had encountered it without a clear resolution yet.
Some of the solutions presented on the other issue are not suitable for my specific use case because I don't have only an image, I have a custom view with other components.

For my use case, instead of using PNG files I created a component for each one of my icons because they have SVG files with their source. 

For that, I use this project below that pre-process your SVG images to a react native component. After that just include it on your marker. 

[msvgc](https://github.com/necinc/msvgc)

I hope it will help others with the same issue

**Comment by alvelig** [comment]
Merging to #1870
