### ISSUE TITLE
Movable Marker problem

### ISSUE THREAD

**Issue by derrickyin** [react-community/react-native-maps#1247]
I've recently tried the following code:

**{markers.map((marker) => (
            <MapView.Marker
	              coordinate={{
	                latitude: marker.latitude,
	                longitude: marker.longitude
	              }}
	              title="This is a title"
	              description="This is a description"
	            >
	            </MapView.Marker>
	          ))}**

And these code inside render():

**var markers = this.state.markers || [];
console.log(markers);**

in order to obtain a dynamic marker. However, some errors occurred: "undefined is not a function (evaluating 'markers.map')"

May I know how to solve this problem?

**Comment by derrickyin** [comment]
Now I tried to change markers to array by:

**this.setState({
    		markers: [
    			{'longitude': Number(lng)},
    			{'latitude': Number(lat)}
    		],
    	});**

The error code has been changed to "marker error while updating property 'coordinate'", am I in the correct direction? Thanks.

**Comment by alvelig** [comment]
Your code is wrong. See examples
