### ISSUE TITLE
How I can rotate map?

### ISSUE THREAD

**Issue by vvmgev** [react-community/react-native-maps#1248]
I need show 3d when user click in marker
before click
![screenshot from 2017-04-17 01-17-13](https://cloud.githubusercontent.com/assets/11613729/25074437/a2fa42cc-230b-11e7-825f-58e32f100405.png)
after click
![screenshot from 2017-04-17 01-19-27](https://cloud.githubusercontent.com/assets/11613729/25074452/efeb3fbe-230b-11e7-9a67-b8db8866e42c.png)

**Comment by PARAGJYOTI** [comment]
You can call animateToCoords() . 
Here's a snippet from my code .
  ```
 componentWillReceiveProps(np){
   
   if(this.props.markers!==np.markers){
     this.setState({markers:np.markers})
   }
   if(this.props.selectedMarkerId!==np.selectedMarkerId && this.state.markers.length>0){
     var marker=this.state.markers[np.selectedMarkerId]
     var Coords=marker.latlng
     
     this.map.animateToCoordinate(Coords)
     
     this['marker'+[np.selectedMarkerId]].showCallout()
   }
   
 }
```

**Comment by vvmgev** [comment]
But it is not showing 3d mode

**Comment by MiLeung** [comment]
It doesn't look like 3d react native maps is being developed at the moment =(

**Comment by sandinosaso** [comment]
For 3D kinda (show building volume) you can change the ViewingAngle of the map (also called Tilt or  Pitch -> depending if Google or Apple).
There is a PR https://github.com/airbnb/react-native-maps/pull/1544 that adds support for what you are looking for. Hopefully, with your support by commenting on thumbs up on it, it could be merged soon.
Regards.

**Comment by alvelig** [comment]
#1544 fixes that
