### ISSUE TITLE
Marker onPress return Callout

### ISSUE THREAD

**Issue by osungjin** [react-community/react-native-maps#125]
How can I render callout if marker pressed?

```
pressMarker(marker) {
    return (
      <MapView.Callout tooltip>
        <MarkerCallout ref={marker} >
        </MarkerCallout>
      </MapView.Callout>
    );
  }

  renderMarkers() {
    return this.props.mapdata.map((marker) => {
      return (
        <MapView.Marker
          coordinate={{latitude:marker.lat,longitude:marker.lon}}
          image={require('../../../assets/images/maps/marker.png')}
          onPress={() => this.pressMarker(marker)}
          />
      );
    });
  }
```

```
<MapView.Marker>
..callout
</MapView.Marker>
```

This structure caused many loads when rendered a lot of makers.

**Comment by r-wittmann** [comment]
Hi osungjin,

just use the default structure for callouts: 
`
<MapView.Marker>
  <MapView.Callout>
    <Custom Callout or just Text>
  </MapView.Callout>
</MapView.Marker>` 

as seen here: https://github.com/lelandrichardson/react-native-maps#rendering-a-custom-marker-with-a-custom-callout

Callout is triggered by pressing on the marker.

Ray

**Comment by jeveloper** [comment]
Curious if anyone had observed this, is this still an issue in the current RN

**Comment by jeveloper** [comment]
@osungjin how did you solve this?

**Comment by khenki** [comment]
is it possible to use
onPress={() => this.newScene() }>
 on a map marker?

**Comment by alvelig** [comment]
@khenki see react-navigation

@osungjin You are doing it wrong. See docs.
```
<MapView.Marker
          coordinate={{latitude:marker.lat,longitude:marker.lon}}
          image={require('../../../assets/images/maps/marker.png')}
          >
<Callout><Text>Callout</Text></Callout>
</MapView.Marker>
```
If you experience performance problems, try rendering only visible markers.

@jeveloper no, that's not an issue.
