### ISSUE TITLE
Example crashing on TestFlight

### ISSUE THREAD

**Issue by raymallperez** [react-community/react-native-maps#1250]
Using only the example on the repo and just adding the app icons and splash screens so I can upload to TestFlight, the app is crashing immediately after launching.

# Xcode weird warnings
<img width="713" alt="screen shot 2017-04-17 at 10 57 29 pm" src="https://cloud.githubusercontent.com/assets/1222866/25112782/78dca08c-23c1-11e7-86a2-3108fd772d28.png">

# Crash Report
[attachment-2133342256532393462crashlog-B24169FE-D5CB-47EE-A8F9-D1E697C14F6B.txt](https://github.com/airbnb/react-native-maps/files/927193/attachment-2133342256532393462crashlog-B24169FE-D5CB-47EE-A8F9-D1E697C14F6B.txt)

**Comment by kroky-cs** [comment]
@raymallperez did you solve this issue?

**Comment by raymallperez** [comment]
@kroky-cs Nope, please let me know if you successfully use Google Maps on TestFlight, I will truly appreciated.

**Comment by alvelig** [comment]
Merging to #1785
