### ISSUE TITLE
.babelrc cause error in react native 43 version

### ISSUE THREAD

**Issue by rodolfobarretoweb** [react-community/react-native-maps#1258]
I "fix" remove this file

**Comment by gpawlik** [comment]
I got rid of this error by installing `babel-plugin-module-resolver` on my own `npm install --save-dev babel-plugin-module-resolver`

**Comment by JeffreyHyer** [comment]
Can confirm @gpawlik's answer solves the problem.

**Comment by rodolfobarretoweb** [comment]
@JeffreyHyer yes, it works

**Comment by carlitosspot** [comment]
@gpawlik Thanks for the pointer!

**Comment by Vivism** [comment]
Tried @gpawlik - not working.

**Comment by gpawlik** [comment]
@Vivism could you please paste here the full error message?

**Comment by notlose** [comment]
not working for me as well, 

npm install --save-dev babel-plugin-module-resolver
xxx@0.0.1 /xxx
├── babel-plugin-module-resolver@2.7.0 
└── UNMET PEER DEPENDENCY react@16.0.0-alpha.6


TransformError: xxx/.js Unknown plugin "module-resolver" specified in "xxxxx/react-native-maps/.babelrc" at 0, attempted to resolve relative to "xxxxxx/react-native-maps"

**Comment by gpawlik** [comment]
@notlose could you check if `babel-plugin-module-resolver` appears in the `node_modules` directory? Maybe removing `node_modules` directory and running `npm install` again might help...

**Comment by notlose** [comment]
@gpawlik finally get it working by serving the js with "npm start" instead of run by xcode.
thanks!

**Comment by guoliang1206** [comment]
@notlose hi bro, can you say more detail? I have the same problem with you. And I am trying to use the version 0.14.0

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
