### ISSUE TITLE
After update: native component AIRMapMarker does not exist

### ISSUE THREAD

**Issue by Catharsis68** [react-community/react-native-maps#1259]
Hey Guys,

I created a project with create react native app and react native maps. Everything worked.
I ejected the project and created a "normal" one with react native init.

Therefore I use the current versions of react-native-app / react-native

But now I got this message: `Warning: Native component for "AIRMapMarker" does not exist`

I installed react-native-maps with `npm install react-native-maps --save` and linked it `react-native link react-native-maps`.

![screen shot 2017-04-21 at 14 25 15](https://cloud.githubusercontent.com/assets/6165055/25277544/74a60fcc-269f-11e7-9eaf-5e050c46010c.png)
![screen shot 2017-04-21 at 14 26 01](https://cloud.githubusercontent.com/assets/6165055/25277543/74a53eb2-269f-11e7-9f2d-99117de6ba3e.png)

Although I receive this error. Any ideas?

my `package.json`
```{
  "name": "Awesome",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
"react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-maps": "^0.14.0",
    "react-native-vector-icons": "^4.0.1",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-plugin-module-resolver": "^2.7.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6",
    "reactotron-react-native": "^1.3.0",
    "redux-devtools": "^3.3.2"
  }
}
```

**Comment by kfwebdev** [comment]
Also seeing this issue with same dependency versions.

**Comment by Catharsis68** [comment]
found this related issue #1214

**Comment by jaimeagudo** [comment]
Experiencing the same on 
```
"react-native": "0.44.0",
"react-native-maps":  "0.15"
```
l have checked #1214 solutions without success, any updates on this?

**Comment by jaimeagudo** [comment]
I don't know wether it could be related but it has disappeared with the latest version (https://github.com/airbnb/react-native-maps/releases/tag/v0.15.2) and after fixing   https://github.com/airbnb/react-native-maps/issues/1258 with the suggested solution

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
