### ISSUE TITLE
Delta changes even when zoom level does not

### ISSUE THREAD

**Issue by Norchene** [react-community/react-native-maps#1261]
I'm trying to display a View over a MapView and I need to positionate it with absolute top and left styles.

So I need the exact geographical coordinates of the top left and bottom right corners of the current region displayed. 

I tried to use latitudeDelta and longitudeDelta (from onRegionChangeComplete) but i noticed that latitudeDelta and longitudeDelta change even if the zoom level remain the same (no zoom, only pan).

To test that display a mapView:

```
<MapView
  onRegionChange={region => console.log(region.latitudeDelta, region.longitudeDelta)}
/>
```

Just pan the map (without zooming or rotating) and see inconsistent latitudeDelta and longitudeDelta variations.

Any one know how to fix this ?

**Comment by alvelig** [comment]
Remember you are on a globe but showing a plain map. Deltas will change. 

Would that work:
<View style={StyleSheet.absoluteFillObject}>
  <MapView style={StyleSheet.absoluteFillObject}... />
  <View style={{ position: 'absolute', left: 0, top: 0 }}>
</View>
