### ISSUE TITLE
markers moving on IOS

### ISSUE THREAD

**Issue by gerardus1995** [react-community/react-native-maps#1275]
I got a android/ios app that uses gmaps with react-native-maps. I got more than 5k points so in order to not make the app slow i just render the ones that are visible right now (i get only the markers that are between top-left or bottom-right). In android everything works fine and when i move throw the map some points dissapear and others appear but in ios the points just move to the new location instead of dissapearing and appearing on the new spot. I do it with an array declared in state so every time the users moves throw the map the state is updated.

**Comment by UrbanChrisy** [comment]
Its helpful to post some code of your map and map marker components to help diagnose your problem, check if you are setting the ket of the map marker by the number in the array and if so don't or ios it doesn't work too well. Unless you set the map marker in a seperate component to not update in shouldComponentUpdate.

**Comment by gerardus1995** [comment]
I put keys depeneding on the index of array but the markers still moving every time the screen moves.

**Comment by gerardus1995** [comment]
<MapView
            ref={'mapview'}
            provider={PROVIDER_GOOGLE}
            showsUserLocation={true}
            showsMyLocationButton={true}
            style={[STYLES.map,{bottom:this.state.bottom}]}
            region={this.state.initialRegion}
            onRegionChangeComplete={(region) =>{
              var northWest = {latitude:region.latitude+(region.latitudeDelta/2), longitude: region.longitude-(region.longitudeDelta/2)};
              var southEst = {latitude:region.latitude-(region.latitudeDelta/2), longitude: region.longitude+(region.longitudeDelta/2)};
              this.fetchData(northWest,southEst);
              this.props.changeInitialRegion(region);
              if(!this.state.dragMarkers){
                this.setState({ dragMarker1: {"latitude":region.latitude, "longitude":region.longitude}, dragMarker2: {"latitude":region.latitude, "longitude":region.longitude+0.01}});
              }
            }}
            customMapStyle={mapStyle}
            moveOnMarkerPress={false}
            mapType={"standard"}
          >
           
            {(this.state.coordinates.length>0) ? 
              clusters.map((data, i) => {
                if(typeof data.type=='undefined'){
                  return <MapView.Marker key={i} coordinate={{latitude: parseFloat(data.geometry.coordinates[1]), longitude: parseFloat(data.geometry.coordinates[0])}} image={(data.properties.idType==2) ? image1 : image2 } onPress={()=>(data.properties.idType==2) ? this.openModal2(data) : this.openModal(data)}/> 
                }
                else{
                  return <MapView.Marker key={i} coordinate={{latitude: parseFloat(data.geometry.coordinates[1]), longitude: parseFloat(data.geometry.coordinates[0])}} image={image5} onPress={()=>{
                    var children = index.getLeaves(data.properties.cluster_id, zoom, limit = "infinity", offset = 0);
                    var coordinates = this.getAllCoordinates(children, index, zoom);
                    var DEFAULT_PADDING = { top: 20, right: 20, bottom: 20, left: 20 };
                    this.refs['mapview'].fitToCoordinates(coordinates, {edgePadding: DEFAULT_PADDING, animated: true});
                  }}/>                   
                }              
              })
              :
              console.log("no coordinates here")
            }
</Mapview>

**Comment by UrbanChrisy** [comment]
Yea, i had problems where when the key of the marker was set depending on the index of the array, like you have above. So what I would do move the marker out to a seperate component and set it the key to a string which adds together the lat and long, so if i had lat 36.123 and lng 145.453.
Make the key like 36.123145.453, so its unique. And if they still jump which they shouldent then set the component to no update in shouldComponentUpdate.
```Javascript
shouldComponentUpdate() {
     return false;
}
```

The reasoning behind why the markers are jumping is because when you move around the map, assumingly  the array changes, and therefore the index of the majority of items will change, therefore when the component rerenders the markers and they move to their new location based on what their index was before to now.

**Comment by jmhuret** [comment]
I was just having the same issue, and I can confirm that establishing a unique key based on the data the marker is representing, rather than just an array index, solved this for me.

Thanks for the tip!

**Comment by alvelig** [comment]
Might be related #483

**Comment by Hopefulee** [comment]
@UrbanChrisy - Thanks. It seems working for me too
