### ISSUE TITLE
No podspec found for `React` in `../../node_modules/react-native`

### ISSUE THREAD

**Issue by hoangcao10** [react-community/react-native-maps#1276]
i got error when run pod install 
No podspec found for `React` in `../../node_modules/react-native`
for react-native v. 0.43

this is Podfile:
# /map/ios/Podfile

`# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'AirMapsExplorer' to match the target in your Xcode project.
target 'map' do

  pod 'Yoga', :path => '../../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../../'
  pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end`

**Comment by rifuso** [comment]
There is some discussion on this issue here

https://github.com/airbnb/react-native-maps/issues/1197

**Comment by dscx** [comment]
Try removing the first set of '../' from both Yoga and React
Also, you will need to do a similar path for the last 2 pods, like this:
` pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
`

**Comment by zidonJ** [comment]
good, it's worked for me.

**Comment by alvelig** [comment]
https://github.com/alvelig/react-native-maps-pods-example

**Comment by danmcgill6** [comment]
if you are running this for first time you need to `npm install` first

**Comment by no-NameTillNow** [comment]
what pod does is it will install the podspec defined in the path.
you have check whether the path really exists.
sometimes it may be inside other dir (ex: ../your_app_name/node_modules/react)
