### ISSUE TITLE
Provision for searchable/autocomplete dropdown

### ISSUE THREAD

**Issue by akashbdj** [react-community/react-native-maps#1284]
Hello, 

I'm new to React Native and its ecosystem. 

I'm just asking if there is any provision in this module where I could place a searchable/autocomplete dropdown on the map which suggests places as user types in something? 

Thanks.

**Comment by alpamys-qanybet** [comment]
@akashbdj, still no answer? I am also interested in this feature.

**Comment by alvelig** [comment]
This is out of scope of the lib. Use https://github.com/devfd/react-native-geocoder and position your TextEdit (or any other autocomplete by other libs) absolutely above the map (not as child of MapView)
