### ISSUE TITLE
AirMap Circle, set radius as screen width and not meters 

### ISSUE THREAD

**Issue by ghamaide** [react-community/react-native-maps#129]
All is said in the title. Is it possible to specify the radius as a screen width and not as a distance. So that it doesn't change the zooming / unzooming the map.

**Comment by weixingsun** [comment]
try marker with image

**Comment by proProbe** [comment]
did you find a solution to this?

**Comment by bhelx** [comment]
I found a solution to this by copying the code used to make the location marker. I initially tried creating marker images but that was limited and didn't look so good.

Use the normal Marker component and define an internal View component and style that as a circle using `borderRadius`.

 https://github.com/airbnb/react-native-maps/blob/4e8326fd299500c0ba2dc2c794658bf5367663c4/example/examples/MyLocationMapMarker.js#L88

Mine looks roughly like this:

```
      <MapView.Marker
        anchor={ANCHOR}
        style={styles.mapMarker}
        coordinate={coordinate}
      >
        <View style={styles.container}>
          <View style={styles.marker}>
            <Text style={{ width: 0, height: 0 }}>
            </Text>
          </View>
        </View>
      </MapView.Marker>
```

**Comment by alvelig** [comment]
What's the use case for that? I would set a map child element. Circle is an overlay, so it is bound to coordinates, not to viewport.

Anyway, wontfix for Circle :( If you really need that feature, let me know your use case and open a new issue please.
