### ISSUE TITLE
React native map marker click issues

### ISSUE THREAD

**Issue by ZebelLizard** [react-community/react-native-maps#1295]
Hi there,
When I am using **custom image for the marker**, it does not actually trigger the callout upon press. But surprisingly it works, when it is clicked **a little bit below the marker**. It is not really giving a good user experience. **Any solutions regarding this**? The centeroffset or anchor is not really providing a good solution here..

**Comment by podvipodvert** [comment]
+ same thing

**Comment by alvelig** [comment]
That's already fixed
