### ISSUE TITLE
Mapview doesn't work

### ISSUE THREAD

**Issue by tishad770** [react-community/react-native-maps#1296]
It doesn't render on screen. 

The versions I am using are: 
`"react": "16.0.0-alpha.6",
  "react-native": "0.43.3",
  "react-native-maps": "^0.14.0"`

is it a version related issue? if not, then what am I missing here?

**Comment by guilhermepontes** [comment]
Provide more information and make sure you followed the [installation instructions](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md).

**Comment by hackdie** [comment]
having the exactly same libraries. it works fine for me.

**Comment by prajapati-parth** [comment]
@guilhermepontes The installation instructions for v0.14.0 have not been updated.
@tishad770 Please follow #1253

**Comment by guofoo** [comment]
I'm having the same issue. I'm using a clean project from create-react-native and expo v16.0.0, which includes react-native-maps 0.12.0 I believe. There's no error anywhere, just the map area is blank. Do I need to run the react-native-maps installation steps separately?

**Comment by henrikra** [comment]
@tishad770 Did you got this to work?

**Comment by gitlovenotwar** [comment]
I having the same issue. It doesn't render or doing anything.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
