### ISSUE TITLE
iOS Google Maps support

### ISSUE THREAD

**Issue by cserdean** [react-community/react-native-maps#1299]
I tried to setup GoogleMaps support for iOS but I get an error on `@import GoogleMaps //Module 'GoogleMaps' not found`

**Comment by raymallperez** [comment]
The installation guide is very unreliable, use the example installation from master repo and work from there but beware, when testing in TestFlight the app crashed for me.

**Comment by tishad770** [comment]
Same here

**Comment by codedre** [comment]
@cserdean I was able to get this working by following these instructions. Make sure to read the comments below, there are some updates that are described there. Hope it helps https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0

**Comment by anhtuank7c** [comment]
Follow my guide: https://github.com/anhtuank7c/maps-example
I integrated successfully.
React native: 0.44.2
react-native-maps: 0.15.2

**Comment by raymallperez** [comment]
@anhtuank7c were you able to successfully test on iOS TestFlight?

**Comment by anhtuank7c** [comment]
@raymallperez Can you help me to do the test?

**Comment by raymallperez** [comment]
@anhtuank7c sure, we can talk in Hangouts via Gmail: raymall.perez@gmail.com

**Comment by anhtuank7c** [comment]
@raymallperez Sure, message sent

**Comment by jsierles** [comment]
Anyone got this working on 0.45.1? Seems now to require more third party podspecs like `Folly`.

**Comment by mulles3008** [comment]
Can't get it to work either 😒 

While the tutorial of @anhtuank7c (based on RN 0.44.2) works with RN 0.44.2, I doesn't work with 0.45.1 for me. Following his tutorial, I get the following error:
```
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/erikmuller/Downloads/maps-example-master/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/JSCSamplingProfiler.o /Users/erikmuller/Downloads/maps-example-master/node_modules/react-native/React/Modules/JSCSamplingProfiler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
I also suspect the error to be related to (probably missing) podspecs, but don't know which... @jsierles have you made any progress on this?

Anyone?

**Comment by jsierles** [comment]
It works on 0.45.1 for me by only having `GoogleMaps` in the Podfile, dragging the AirMaps files into the project, and ensuring my project includes react its header paths.

**Comment by mulles3008** [comment]
@jsierles Would you mind posting you Podfile and the exact `Header Search Paths` entries? Maybe also the `Framework Search Paths` entries? When it comes to 

> dragging the AirMaps files into the project

I assume that you meant the `AirGoogleMaps` folder, not the `AirMaps` folder?

Thanks a lot for your help!

**Comment by anhtuank7c** [comment]
@mulles3008 This step existing right here: https://github.com/anhtuank7c/maps-example#step-05-open-project

**Comment by mulles3008** [comment]
@anhtuank7c Yep, that's the way I did it, but still getting the error described above. I'm not quite sure if @jsierles followed your tutorial or if he did any extra changes, that's why I'm asking. In your [tutorial](`https://github.com/anhtuank7c/maps-example`) you are not mentioning anything about setting header search paths or other Xcode settings. I saw in your video guide that you were explaining something about the header search paths, but unfortunately I don't understand Vietnamese :sweat_smile: But also with mine and your `Header Search Paths` entries being the same I can't get it to work.

Have you tried if your tutorial also works with RN v0.45.1?

Sorry if I bother you, but I'm kinda frustrated...

**Comment by anhtuank7c** [comment]
@mulles3008 actually Search Path are not necessary because it already filled by `react-native link react-native-maps` command.
I did not try on RN 45.1, finally did it work for you?

**Comment by mulles3008** [comment]
@anhtuank7c no, unfortunately not.

**Comment by anhtuank7c** [comment]
@mulles3008 https://github.com/anhtuank7c/maps-example
Still work well on RN 0.47.2, RNM 0.16.0

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
