### ISSUE TITLE
Crashing on TestFlight

### ISSUE THREAD

**Issue by raymallperez** [react-community/react-native-maps#1301]
Since I never got it working following the Installation Guide I had to clone the master repo, follow the example app installation guide and do changes as needed, all good so far.
But when I wanted to test my iOS app on devices via TestFlight the app crash on launch.
At first thought it was something in my code but I did a fresh install without adding any of my code and the app still crash when installed via TestFlight.

react-native@0.42
react-native-maps@0.14.0

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

Also would be great to know the exception failing
