### ISSUE TITLE
[Android] Privacy Guard multiple location permission request at each MapView mount

### ISSUE THREAD

**Issue by 39otrebla** [react-community/react-native-maps#1302]
Using Privacy Guard I noticed that each time I navigate to a component which renders a MapView the module tries to acquire location information, even though `showUserLocation` is set to `false` (which, anyway, is the default). Even worse, there are multiple requests at each mount, not just one.

Platform: Android M
react-native @ 0.42.3
react-native-maps @ 0.14.0

**Comment by rborn** [comment]
Please comment if this is still the case.
