### ISSUE TITLE
Version v0.15

### ISSUE THREAD

**Issue by anirom** [react-community/react-native-maps#1307]
There are a problem in this version that does not link react-native-maps to android, and if a do manual, i cant add as:

project(':react-native-openpay').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-openpay/android')

And if i remove the android folder on the path, this error appears:

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

In v13 works. I hope you can help me :).

**Comment by Amurmurmur** [comment]
Thats because you the address of the lib has changed.
It's 
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```
Make sure that in your settings.grandle you set the above.
Hopefully it solves your issue, if it does, hit that thumbs up button 👍  :)
