### ISSUE TITLE
Android scroll performance with multiple markers

### ISSUE THREAD

**Issue by hannupekka** [react-community/react-native-maps#132]
Android UI FPS drops significantly when scrolling on map with multiple (10+) markers.

```
render() {
  const markers = [
    <MapView.Marker key={0} title='foo' />,
    ...
  ];
  return (
    <MapView
      initialRegion={...}
      showsPointsOfInterest={false}
      showsCompass={false}
      showsScale={false}
      showsBuildings={false}
      showsTraffic={false}
      showsIndoors={false}
      rotateEnabled={false}>
      {markers}
    </MapView>
  );
}
```

**Comment by Pocket-titan** [comment]
Are you testing it with JS Dev Mode disabled?

**Comment by DennisMG** [comment]
I can confirm this! When rendering multiple markers the FPS drops. JS Dev Mode is disabled.

**Comment by hannupekka** [comment]
I had dev mode also disabled. BTW, my device is Nexus 5x and some other devices seemed to perform better.

**Comment by julvernois** [comment]
Hi, I have the same performance issue, did you find a solution ?

**Comment by carleryd** [comment]
I have the same problem @hannupekka , also running Nexus 5x.
250 randomly positioned simple markers run at ~8 fps on the Nexus 5x and at ~30 fps on its predecessor Nexus 4. So something is up with that device...

**Comment by saberking** [comment]
Has anyone tried this on iPhone 5C? The performance is much worse than Nexus 5X

**Comment by alvelig** [comment]
Hey, you are re-rendering your markers on every drag. Move your markers out of render().
