### ISSUE TITLE
Getting “npm ERR! code EPEERINVALID” on npm install

### ISSUE THREAD

**Issue by hustlerism** [react-community/react-native-maps#1320]
`npm install react-native-maps --save`

returns

npm WARN peerDependencies The peer dependency react@>=15.4.0 included from react-native-maps will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-native-maps" "--save"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@16.0.0-alpha.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.44.0 wants react@16.0.0-alpha.6
npm ERR! peerinvalid Peer react-native-maps@0.15.0 wants react@>=15.4.0
npm ERR! peerinvalid Peer react-test-renderer@16.0.0-alpha.6 wants react@^16.0.0-alpha.6
npm ERR! peerinvalid Peer react-navigation@1.0.0-beta.9 wants react@*

**Comment by howitworks18** [comment]
I'm having the same issue, not sure whats going on!

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
