### ISSUE TITLE
NullPointerException SurfaceView on some android devices

### ISSUE THREAD

**Issue by damathryx** [react-community/react-native-maps#1321]
Got this crash report on firebase. 
Device info:
Redmi note 3
Android 5.1
API Level 22
react-native-maps v0.13.1

`Exception java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
android.view.SurfaceView.init (SurfaceView.java:231)
android.view.SurfaceView.<init> (SurfaceView.java:193)
com.google.maps.api.android.lib6.gmm6.vector.an.<init> (:com.google.android.gms.DynamiteModulesB:231)
com.google.maps.api.android.lib6.gmm6.vector.ai.<init> (:com.google.android.gms.DynamiteModulesB:163)
com.google.maps.api.android.lib6.gmm6.api.ao.<init> (:com.google.android.gms.DynamiteModulesB:389)
com.google.maps.api.android.lib6.gmm6.api.ao.a (:com.google.android.gms.DynamiteModulesB:349)
com.google.android.gms.maps.internal.eb.a (:com.google.android.gms.DynamiteModulesB:4048)
com.google.maps.api.android.lib6.impl.az.a (:com.google.android.gms.DynamiteModulesB:403)
com.google.maps.api.android.lib6.impl.az.a (:com.google.android.gms.DynamiteModulesB:308)
com.google.maps.api.android.lib6.impl.da.a (:com.google.android.gms.DynamiteModulesB:79)
com.google.android.gms.maps.internal.z.onTransact (:com.google.android.gms.DynamiteModulesB:66)
android.os.Binder.transact (Binder.java:380)
com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate ()
com.google.android.gms.maps.MapView$zza.onCreate ()
com.google.android.gms.dynamic.zza$3.zzb ()
com.google.android.gms.dynamic.zza$1.zza ()
com.google.android.gms.maps.MapView$zzb.zzJy ()
com.google.android.gms.maps.MapView$zzb.zza ()
com.google.android.gms.dynamic.zza.zza ()
com.google.android.gms.dynamic.zza.onCreate ()
com.google.android.gms.maps.MapView.onCreate ()
com.airbnb.android.react.maps.AirMapView.<init> (AirMapView.java:93)
com.airbnb.android.react.maps.AirMapManager.createViewInstance (AirMapManager.java:62)
com.airbnb.android.react.maps.AirMapManager.createViewInstance (AirMapManager.java:29)
com.facebook.react.uimanager.ViewManager.createView (ViewManager.java:46)
com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:218)
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:152)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations (UIViewOperationQueue.java:912)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:884)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:31)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:129)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:107)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:773)
android.view.Choreographer.doCallbacks (Choreographer.java:588)
android.view.Choreographer.doFrame (Choreographer.java:557)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:761)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5276)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:908)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:703)`

What seems to be the problem?

**Comment by karpoff** [comment]
catched the same issue on Xiaomi Redmi 4 (Android 6.0.1)
react-native-maps 0.14.0
react-native 0.42.3

**Comment by iiitmahesh** [comment]
:+1:

**Comment by okarakose** [comment]
same issue here.

react-native-maps 0.15.0 and 0.14.0
react-native : 0.43.4

**Comment by Maxwell2022** [comment]
I don't think this lib is maintained anymore...

**Comment by henrikra** [comment]
We have same exact crashes too
These are the models crashing:
![image](https://cloud.githubusercontent.com/assets/12229968/26092854/ebea4c08-3a1b-11e7-96ef-f5f68d4eae7f.png)

**Comment by tineo** [comment]
Same error in LG X Style

**Comment by tineo** [comment]
The error is after update Google services

**Comment by damathryx** [comment]
downgrading to 0.13.0 might work.

**Comment by henrikra** [comment]
@felipecsl
@lelandrichardson
Do you guys know if this very common crash is being investigated?

**Comment by felipecsl** [comment]
have you tried on the latest version? v0.15.2?

**Comment by felipecsl** [comment]
I'm not actively looking into it right now FWIW, but if it's still reproducible, I could take a look

**Comment by henrikra** [comment]
We are using 0.15.0 version and we still got this error maaany times. I think 0.15.2 wont helps us at all since changelog has only changes to iOS side

**Comment by damathryx** [comment]
I can't upgrade to RN 0.44 because I'm stuck with RNM 0.13.0. RNM 0.13.0 seems  to be working on redmi note 3. Can anyone else confirm

**Comment by alvelig** [comment]
Update to latest and comment please.
