### ISSUE TITLE
MapView non responsive to region update

### ISSUE THREAD

**Issue by MicahSteinbrecher** [react-community/react-native-maps#1327]
MapView is not responding well to an updated region value. I store region in state and update it programmatically with data from an ajax request. inspecting state confirms that region is set to the correct value after getting data, but the map does not respond to the new state.

**Comment by scotbond** [comment]
completely avoid `initialRegion` prop if you're using it, use only `region` prop.

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
