### ISSUE TITLE
showsUserLocation does not work well with Google Maps

### ISSUE THREAD

**Issue by freshnewegg** [react-community/react-native-maps#1329]
When I try to use ShowsUserLocation with GoogleMaps, it gives me a white box and doesn't animate properly.
<img width="318" alt="screen shot 2017-05-14 at 3 01 36 pm" src="https://cloud.githubusercontent.com/assets/5714313/26036938/51f2b272-38b6-11e7-899f-5312e3ea7ef7.png">
<img width="615" alt="screen shot 2017-05-14 at 3 01 18 pm" src="https://cloud.githubusercontent.com/assets/5714313/26036939/545ee7ec-38b6-11e7-9c7c-7f97f1bf1d8e.png">

The same code without provider={"google"} works perfectly.

<img width="156" alt="screen shot 2017-05-14 at 3 04 03 pm" src="https://cloud.githubusercontent.com/assets/5714313/26036946/9b028e88-38b6-11e7-8cfe-7ecacaf00423.png">

Does anyone have any ideas?

**Comment by guilhermepontes** [comment]
If I am not wrong this only happens on the Simulator, on a real device it's fine.

**Comment by holden-caulfield** [comment]
At least for me, on a real device it does not have the white box background but it does not "pulsate". Not sure if others are having the same issue

**Comment by freshnewegg** [comment]
yep it works on real devices, the pulsate is not implemented i think. At some point i might do it and give a pull request.
