### ISSUE TITLE
Performance issue "animating with MapViews"

### ISSUE THREAD

**Issue by ublanke** [react-community/react-native-maps#1330]
The example with the animated callouts [Using Mapview with animated API](https://github.com/airbnb/react-native-maps#using-the-mapview-with-the-animated-api)
is lagging extremely. We ran the example out of the box from the repo.
Are we missing something?

**Comment by oussamajabnouni** [comment]
Same problem here

**Comment by metelski** [comment]
Exactly the same here. Tested on real Android & iOS devices (Huawei P8 Lite, iPhone 6). The performance of this demo is really poor - the animations are like 2-3 FPS or so. How did you manage to make that animated gif screen recording smooth enough?

**Comment by NedYork** [comment]
One thing I noticed is that when I have debugger ON, the example runs pretty smoothly. When I have it OFF, it lags. Anybody else experiencing same thing?

**Comment by JackEsad** [comment]
I have the same problem NedYork

**Comment by rborn** [comment]
Please read the comments in this issue: https://github.com/react-community/react-native-maps/issues/1896

Closing.

**Comment by rborn** [comment]
@NedYork this is a known issue with the debugger. You should always test your app in production mode anyway :)
