### ISSUE TITLE
Rotate map heading on load

### ISSUE THREAD

**Issue by codedre** [react-community/react-native-maps#1331]
Is there any way to have the map orient itself? Currently the maps heading is north but I want to rotate it to show NW when the view loads.

**Default**
![north](https://cloud.githubusercontent.com/assets/10161117/26066954/9bb1db26-3966-11e7-9bd4-6da37eccc78d.png)
**Rotated NW**
![nw](https://cloud.githubusercontent.com/assets/10161117/26066968/a360123e-3966-11e7-80d8-eb6b894885ec.png)

**Comment by mistenkt** [comment]
Really hope this feature will be added, not only on load, but to change the bearing at any time programmatically

**Comment by codedre** [comment]
Have this working now will submit a PR once I clean it up a bit

**Comment by brianarpie** [comment]
+1 would be very useful to control map orientation programmatically

**Comment by MiLeung** [comment]
+1 ^exactly

**Comment by mo22** [comment]
any progress on this? this is actually really easy to implement, I wonder why it hasn't been done / merged?

**Comment by MiLeung** [comment]
Looks like [react-native-mapbox](https://github.com/mapbox/react-native-mapbox-gl) supports programmatic rotation change with the `setDirection` method.

**Comment by willdavidow** [comment]
Looks like there's progress on a related PR #1544 - hoping one of these PR's can make its way into the project! Been really missing the ability to re-orient the MapView programmatically in RN.

**Comment by sandinosaso** [comment]
Guys, as @willdavidow said I did a PR to support programmatically change map orientation as well of the camera view angle. The PR support both types of map providers and both platform, your comments or even thumb up vote on the PR may help it get merged faster :)
Thank you https://github.com/airbnb/react-native-maps/pull/1544

**Comment by raihanrazi** [comment]
Really keen to see this feature merged.

**Comment by aaronbuchanan** [comment]
#1544 made it in fyi @raihanrazi @willdavidow @MiLeung @mo22 @brianarpie @codedre @mistenkt 

Big ups to @sandinosaso and thanks to @christopherdro for getting this in!

**Comment by wolframus** [comment]
Use MapView "camera" property which includes "heading" property. You can provider an value between 0 and 360 which unexpectedly stands for degrees.
