### ISSUE TITLE
WARN react-native-maps@0.15.0 requires a peer of react@>=15.4.0 but none was installed

### ISSUE THREAD

**Issue by npomfret** [react-community/react-native-maps#1335]
Can we remove [this](https://github.com/airbnb/react-native-maps/blob/master/package.json#L34) dependency from the build? I don't think it's valid.

**Comment by baby03201** [comment]
having same issue (+1)

**Comment by Hsnzas** [comment]
Same here

**Comment by anhtuank7c** [comment]
Same here.
![screen shot 2017-05-30 at 3 22 16 pm](https://cloud.githubusercontent.com/assets/3163410/26574524/e09d711e-454b-11e7-9d3a-6cc609baf0d5.png)

**Comment by HideOnBushTuT** [comment]
same problem

**Comment by anhtuank7c** [comment]
Temporary fix by clone master branch to your computer.
IE:
```
/Users/me/projects> git clone https://github.com/airbnb/react-native-maps.git
react-native init mapDemo
cd react-native-maps
vi package.json
====> then edit peerDependencies react: "16.0.0-alpha.6"
Save and quit vi

cd ../mapDemo
npm install --save ../react-native-maps
```

That is

**Comment by Hsnzas** [comment]
This solved it 

`yarn add react@16.0.0-alpha.6 react@15.0 react-router-native --S`

did it solve 👍🏼 yours?

**Comment by anhtuank7c** [comment]
@Hsnzas Does not work.
![screen shot 2017-05-31 at 7 55 58 am](https://cloud.githubusercontent.com/assets/3163410/26611181/b9eba744-45d6-11e7-901a-87ae52593b2f.png)

**Comment by alvelig** [comment]
Was fixed in https://github.com/react-community/react-native-maps/commit/d57edd2a095552999a961f210e610f0746f1470b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
