### ISSUE TITLE
Q: Possible to display heading on blue dot?

### ISSUE THREAD

**Issue by timfpark** [react-community/react-native-maps#1336]
I'm interested in displaying the heading of the user at any given moment on the map ala what Google Maps does like this:

<img width="110" alt="screen shot 2017-05-16 at 10 38 48 am" src="https://cloud.githubusercontent.com/assets/712001/26119986/19c2ad16-3a24-11e7-84e9-73f6c3cc9e42.png">

Is this possible currently with react-native-maps?  I haven't found a setting for it - apologies if I'm missing something in advance.

**Comment by aaronbuchanan** [comment]
It possible but it's not a built-in feature, and there's a current limitation that would require you 

related to #487 and #1221 #1331 because the map heading can change and we don't know...

**Comment by freeman1995** [comment]
so currently there is no way to get the current heading of the map?

**Comment by alvelig** [comment]
See #1069
