### ISSUE TITLE
Black overlay when navigation back from maps (Android)

### ISSUE THREAD

**Issue by salahcoffye** [react-community/react-native-maps#1337]
Map is working fine. But when I navigate back from a maps screens, I get a black overlay. This doesn't happen every time. I use `React-Navigation.
`<View style ={styles.container} >

        <MapView
            style={styles.map}
            region={this.state.mapRegion}
            showsUserLocation={true}
            followUserLocation={true}
            toolbarEnabled={false}
            cacheEnabled={true}
            loadingEnabled={true}
            onRegionChange={this.onRegionChange.bind(this)}>

            {this.state.nearByRepairs.map((marker,key)=>
                (<MapView.Marker
                        key={key}
                        coordinate={marker.latlng}
                        title={marker.title}
                        description={marker.description}
                    />
                ))}
        </MapView>

      </View>`

![18553192_10213354213230937_1183257551_o](https://cloud.githubusercontent.com/assets/6624197/26124272/7ce1e7c8-3a9b-11e7-957a-625260d0c279.png)

**Comment by Mubeena17** [comment]
1+

**Comment by mjosipovic** [comment]
+1

**Comment by uxman-sherwani** [comment]
Facing similar issue on android back. I am using wix/react-native-navigation. When I go back from Maps screen to previous one, the previous screen shows flickering. It doesn't happen when navigating back from a normal screen which doesn't show Maps

**Comment by salahcoffye** [comment]
I made a small workaround for this. Show the map only after a second.

`
    componentDidMount(){
        setTimeout(() => {
            this.setState({showMap:true})
        }, 1000);
    }
`

**Comment by waltChang1** [comment]
+1

**Comment by uxman-sherwani** [comment]
@salahcoffye your fix is for when you are navigating to a screen which shops map. My use case is:

1. Screen with FlatList.
2. User clicks on any item on the list.
3. Details Screen is pushed to navigation stack which contains a Map.
4. User navigates back to List screen (Here is the flickering issue)

**Comment by mjosipovic** [comment]
@uxman-sherwani thanks for info, my use case is exactly the same as yours

**Comment by salahcoffye** [comment]
@uxman-sherwani You can try loading the map in your Detail screen after a second. Even my issue was the same. The black screen comes when navigating back from a map screen.

**Comment by mjosipovic** [comment]
One more comment. When I set liteMode = {true} in my MapView props I could not replicate this issue.

**Comment by chuece** [comment]
I had same issue on >0.14 version.
Fixed it with downgrade to 0.13.0

**Comment by vinhduc** [comment]
I had same issue:
 When I go back from Maps screen to previous one, the previous screen shows mapview previous  and not controller mapview .

**Comment by tszajna0** [comment]
I managed to workaround putting map into a View with a border.

    <View style={{ borderWidth: 1, borderColor: 'white'}}>
      <MapView>/* ... */ </MapView>
    </View>

I don't know why this works, I only guess that map animation doesn't mark some parts of the screen dirty and they're not refreshed; in my workaround the border is marking it dirty.

**Comment by zgc2537** [comment]
@tszajna0 it does work! great.

**Comment by alvelig** [comment]
Use @tszajna0's workaround. Might not be directly related to the lib.
