### ISSUE TITLE
Map randomly resetting position on render / onRegionChange triggered multiple times on loading

### ISSUE THREAD

**Issue by mtt87** [react-community/react-native-maps#1338]
As per title, the map is randomly resetting the position to your current country zoomed out during initial (or next) render.

During rendering `onRegionChange` is always called 4 times and then `onRegionChangeComplete`.

It's funny that both cases, when it works and when it doesn't work, the console log is the same and `onRegionChange` is always passing the same `region`.

Check the first screenshot is correct, the second is wrong.

<img width="812" alt="screen shot 2017-05-17 at 00 19 09" src="https://cloud.githubusercontent.com/assets/2150927/26132244/e11ab7e2-3a96-11e7-94e4-64b16e6d9f2d.png">

<img width="813" alt="screen shot 2017-05-17 at 00 19 34" src="https://cloud.githubusercontent.com/assets/2150927/26132303/483db3fc-3a97-11e7-8d48-3cb7eefe79fd.png">

In my situation I'm living in London, but I set my simulator to have a location in Zurich.
We tested this and it happens the same with someone in Zurich, when it doesn't work it will change the region to the entire Switzerland zoomed out.

```jsx
<MapView
  region={this.props.region}
  onRegionChangeComplete={region => this.props.changeRegion(region)}
```
I've tried also with `initialRegion` and a mix of `followUserLocation` and `showsUserLocation` but doesn't make any difference.

How can I workaround this?
Some ugly `setTimeout()` ?
Any other advice?

Thank you 😄

**Comment by bettiolo** [comment]
I couldn't find a workaround for this issue as well, I had to change the functionality instead :(

**Comment by orliesaurus** [comment]
I have the same issue - can anyone suggest how to work around this issue?

**Comment by dabit3** [comment]
@orliesaurus for now I'm setting a boolean state value of `regionSet` , and not allowing on `onRegionChange` to be called until regionSet has been called. This is working for me but is quite ugly.

**Comment by mtt87** [comment]
@dabit3 do you mind sharing your code to achieve that?
In this moment even an ugly workaround is appreciated!

Thank you

**Comment by dabit3** [comment]
@mtt87  sure. It looks something like this:



```
state = {
  regionSet: false,
}

componentDidMount() {
  navigator.geolocation.
    getCurrentPosition(position => {
      const { latitude, longitude } = position.coords
      const region = {
        ...this.state.region,
        latitude,
        longitude
      }
      this.setState({ region, regionSet: true })
    })
}

onRegionChange = (region) => {
  if (!this.state.regionSet) return;
  this.setState({
    region
  });
}
```

**Comment by mtt87** [comment]
This doesn't work anymore since last version (which is still bugged!)

I'll check if it's something related to `onMapReady` callback

**Comment by mtt87** [comment]
Confirmed, it works with `onMapReady` and remove it from `componentDidMount()`

```js
          onMapReady={() => {
            this.setState({ regionSet: true });
          }}
```

**Comment by victorbadila** [comment]
+1

**Comment by kardolus** [comment]
Changing my region with both animateToCoordinate() and by manual dragging. Region changes are quite choppy with iOS11. I have tried many variations, best seems to update a local variable using onRegionChangeComplete() and then dispatch it with redux on onMapReady(). But to be honest... still choppy and unusable for production. Anyone knows what is the best practice for this? -- also opened this ticket on stackoverflow https://stackoverflow.com/questions/46371596/react-native-maps-with-redux-choppy-region-changes

**Comment by hoboman313** [comment]
I've had a similar problem and I think @mtt87's real issue here is writing `region={this.props.region}`.  You may want to bind props.region to initialRegion instead.

**Comment by mtt87** [comment]
How will I be able to move the map then?

**Comment by hoboman313** [comment]
animateToRegion() and animateToCoordinate() worked well for me. I also think they provide a better UX since the navigation doesn't happen instantly. In your case, I think it may be better to use componentWillReceiveProps() to animate to coordinates on region change.

**Comment by mtt87** [comment]
We might have different use cases, my map allows users to pan and move around, and I never move the map automatically.
Afaik that property is set into region, if you don’t set it, the map won’t move

**Comment by noumantahir** [comment]
experiencing same issue here...it wasnt happening while I was using initialRegion prop only but I need to change location using state.

**Comment by noumantahir** [comment]
dabit3's solutions with a tweak from mtt87 seems to have fixed the zoomout issues but now I am gonna have to look for a way to get current coordinates in code to use somewhere else...anyways thanks

**Comment by alvelig** [comment]
To me best practice is: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
