### ISSUE TITLE
Polyline decorators? patterns (like dashes, arrows)

### ISSUE THREAD

**Issue by fedegonzal** [react-community/react-native-maps#1339]
Hi, 

I want to know if react-native-maps have some kind of custom polyline, I need to draw arrows over the path to explain the direction to my users. Like this https://github.com/bbecquet/Leaflet.PolylineDecorator

Thanks!

**Comment by bosung90** [comment]
It does not

**Comment by arapocket** [comment]
Any plans to add this feature?

**Comment by tudorgergely** [comment]
@bosung90 any news in this regard? would be a useful feature to show users directions on top of the polyline. Thanks!

**Comment by bosung90** [comment]
@tudorgergely No idea, I don't use maps for my current project.

**Comment by amirmatin** [comment]
@fedegonzal Hi, did you find a solution to this? thanks

**Comment by lyudad** [comment]
Also looking for dashes(dots) solution

**Comment by tattivitorino** [comment]
also looking for a way to draw arrows on the polyline...

**Comment by jpetera54** [comment]
For everyone coming across this - Polyline has now `lineDashPattern` prop. 
See the [docs ](https://github.com/react-native-maps/react-native-maps/blob/master/docs/polyline.md) for more info
