### ISSUE TITLE
showsUserLocation Issue

### ISSUE THREAD

**Issue by tamalsen** [react-community/react-native-maps#1342]
I have enabled showsUserLocation in MapView (Android). But the button is not being shown when the map loads for the first time. 
Surprisingly, when I rotate my phone once, the button appears. Even I observed that if I lock the phone and unlock, the button appears. This made me think that the map might need a reload in order to make that button appear.

I observed the same thing when I have created a custom marker with an image. The marker appears after lock/unlock OR rotate/unrotate. Even more surprisingly, the click event works even if the marker is invisible.

Help me out guys!

**Comment by julienR2** [comment]
Hi ! I get the same issue here !
When rotating to horizontal it appears and stay visible when rotating back to vertical..

Any idea how to solve this ?

**Comment by alvelig** [comment]
#1332
