### ISSUE TITLE
Custom callout TouchableHighlight onPress not triggered in android

### ISSUE THREAD

**Issue by fmarsoni** [react-community/react-native-maps#135]
While in iOS it's working.
I have something like this, rendered when I have two or more elements with the same coordinates

```
<Marker key={cluster.key} coordinate={{ latitude: cluster.centroid[1], longitude: cluster.centroid[0]}}>
  <View style={styles.marker1}>
    <Text allowFontScaling={false} numberOfLines={1} style={styles.markerText}>{cluster.elements.length}</Text>
  </View>
  <Callout>
    <View>
    {cluster.elements.map(element =>
      <TouchableHighlight key={element[2]._id} onPress={_.partial(::this.onPressMuseo, element[2])} underlayColor="#b3b1af">
        <Text allowFontScaling={false} style={styles.calloutTextStyle}>{element[2].localized[i18n.getLanguage()].titolo}</Text>
      </TouchableHighlight>
    )}
    </View>
  </Callout>
</Marker>
```

**Comment by martinfilliau** [comment]
It's a known issue unfortunately, see #49 and #92

**Comment by programmersharp** [comment]
![image](https://cloud.githubusercontent.com/assets/2078015/13873511/a14b5dc8-ecfa-11e5-8f6c-74b154ab9673.png)
Wherever I click on my custom callout I get the same x and y (as you can see in the screen). So, I don't have the ability to determine where it was clicked.

**Comment by dhdo** [comment]
@programmersharp i have the same problem, i believe the x and y coordinates are the position of the callout on the screen and not where we touched it. Still trying to figure out

**Comment by alvelig** [comment]
Sorry guys, wontfix... This is what Android GoogleMaps SDK is. 
I suggest you open a view over the map an have your buttons there.
Also use cases are welcome to find workarounds.

**Comment by alvelig** [comment]
#1556 an enhancement issue for that
