### ISSUE TITLE
Programatically setting map region using animateToRegion fires onRegionChange

### ISSUE THREAD

**Issue by amitv87** [react-community/react-native-maps#1350]
`this.refs.map.animateToRegion(this.region, 1000)`
The code mentioned above moves map to the specified region but also fires **onRegionChange** .
Also the prop **region**  for **MapView** does not fire **onRegionChange** when the prop is updated via **setState**.

I believe **onRegionChange** should be fired only when user plays with the map and both the techniques should give consistent result.

**Comment by telkandrew** [comment]
I think we're having a similar issue. Have you had any resolve to this issue or do you have any ideas?

**Comment by alvelig** [comment]
Merging to #1620
