### ISSUE TITLE
setPadding support is missing

### ISSUE THREAD

**Issue by zefj** [react-community/react-native-maps#1356]
https://developers.google.com/maps/documentation/android-api/map#map_padding

Related issue: https://github.com/airbnb/react-native-maps/pull/239

This has been mentioned (and implemented) before, yet closed and left unmerged due to the examples project being broken. I haven't been able to run this library examples either, however I have tested the setPadding implementation provided in the aforementioned issue, and it works flawlessly. This is an important feature for every project that uses MapView with overlays, how (or why) has this been overlooked?

**Comment by Mrachko** [comment]
Absolutely agree. We have a panel that slides from the bottom and we can't implement such an easy functionality without violating terms of use (which is not ok for us). Please, have a look at this problem as soon as it's possible. Thanks in advance.

**Comment by benvium** [comment]
I've added a new PR for this #1467

**Comment by juergengunz** [comment]
@zefj what did you end up doing? did you manage to make it work on android and ios?

**Comment by zefj** [comment]
@juergengunz I just used the changes proposed in #239. It seemed to work on Android, don't know about iOS. It was just a small weekend project to see what react-native was about, I have long abandoned it now and haven't been using this library for a while so I'm out of the loop, sorry.
