### ISSUE TITLE
Urecognized selector sent to instance

### ISSUE THREAD

**Issue by MathieuDebit** [react-community/react-native-maps#1370]
I regularly have this random error, and honestly I don't understand where this issue come from. It can appear at any time (after adding a simple style property, or a component in a view, etc).

![image](https://cloud.githubusercontent.com/assets/6206650/26585482/85bb3672-454c-11e7-83e9-364b05ce8777.png)

Comment the added line, build the app, and de-comment it fix the issue (sometime 🙃 )

Can someone help me find a way to understand what this error means exactly? It drives me crazy ⚡️

Thanks.

**Comment by FredericBriolet** [comment]
Same problem here, and I didn't find any similar case in the issues...

**Comment by alvelig** [comment]
Try latest version from scratch and comment
