### ISSUE TITLE
iOS app crashing on simulator after trying to enable GoogleMaps

### ISSUE THREAD

**Issue by wenzelmk** [react-community/react-native-maps#1377]
I'm trying to enable GoogleMaps on the iOS version of my app. After following advice in [this issue thread](https://github.com/airbnb/react-native-maps/issues/693) and then from Option 1 in [this documentation](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md), my app is now crashing when I try to start it up. 

The terminal window tells me that the build has succeeded, and my app opens on the simulator, then immediately crashes. There are no warnings, errors, or outputs of any kind telling me what is wrong. 

I'm not sure where to go from here to troubleshoot it--I tried to undo some of the last changes I had made in my xcode project before it happened but no success. 

I can easily provide more information if needed, I just have no idea what to provide for this!

**Comment by chapeljuice** [comment]
I haven't tried it on iOS yet but one thing I realized is that when making a lot of these changes I had to completely start the emulator over again instead of just refreshing it. So (if you haven't done this already) I would try to shut down the simulator/emulator and run:
`watchman watch-del-all`
`npm clean cache`
...and then try again?

**Comment by wenzelmk** [comment]
Thanks for the suggestions @chapeljuice! I gave them a try and no luck, though--still crashing.

**Comment by wenzelmk** [comment]
Alright, removing "AirGoogleMaps" from where I had moved it to (as recommended by Option 1 in the link in my original post) stops the app from crashing, but I'm back to square one where I can't enbable GoogleMaps on iOS.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
