### ISSUE TITLE
Won't be able to pinch/rotate the map For MapView.Animated

### ISSUE THREAD

**Issue by Jankidp** [react-community/react-native-maps#1378]
Hi, All... I'm facing some issues in MapView.Animated, I am unable to zoom in or zoom out for the maps. If anyone gets the solution or idea how to fix this. please let me know. I'm using same code given in AnimatedViews.js

**Comment by douglaswissett** [comment]
I fixed this by changing paddingTop or marginTop in AnimatedView.js styles, hope this fixes it!
