### ISSUE TITLE
More than one map on a screen

### ISSUE THREAD

**Issue by georgetroughton** [react-community/react-native-maps#1388]
<img width="375" alt="screen shot 2017-06-06 at 11 46 15" src="https://cloud.githubusercontent.com/assets/864139/26825781/443bac4c-4aae-11e7-8ac3-6370709c63b1.png">
<img width="377" alt="screen shot 2017-06-06 at 11 56 50" src="https://cloud.githubusercontent.com/assets/864139/26826075/9040fcf4-4aaf-11e7-84eb-0f0754611b5f.png">
<img width="377" alt="screen shot 2017-06-06 at 11 59 43" src="https://cloud.githubusercontent.com/assets/864139/26826120/d2a2dcde-4aaf-11e7-84c0-e51e93d3de66.png">

Hi - I'm having issues with multiple maps on one page. As you can see from the screenshots not all the maps are working. 

It's not that the map can not get the location - as in the screenshots the 'Other' address works on one and not on another.

Any ideas?

Cheers

**Comment by alvelig** [comment]
Create a test app repo to reproduce that behavior if you still need that. I'll take a look.
