### ISSUE TITLE
Native component for 'AIRMapMarker' does not exist

### ISSUE THREAD

**Issue by hsavit1** [react-community/react-native-maps#1391]
this is showing up as a warning, but i can't render any mapview at all

occurs at MapMarker.js line 252

`   
 const AIRMapMarker = this.getAirComponent();
`

I have an iOS react native project created with react-native-init using React Native 0.45

instead of a map all i see is a red border outline

**Comment by jmknoll** [comment]
Same problem here. Also on react-native 0.45 with react-native-maps 0.12.4. Similar warning happens for AirMapCallout, and both seem to prevent the map from rendering at all.

**Comment by l3omtz** [comment]
if you're running on ios simulator, uninstall your app in the sim and then build again... worked for me

**Comment by kaxline** [comment]
After clearing all the react-native caches and deleting the app from the simulator, I also had to open up Xcode, clean the solution, and then delete the contents of `~/Library/Developer/Xcode/DerivedData`.

**Comment by roberto-rodriguez** [comment]
Just run this:
react-native link react-native-maps

**Comment by eamonster27** [comment]
<img width="913" alt="screen shot 2017-09-20 at 2 40 52 pm" src="https://user-images.githubusercontent.com/15204339/30664105-33feb650-9e12-11e7-9d7d-962e767b48cd.png">

Step 2 in the above image resolved my issue. Product -> Clean, Product -> Build, Play. 

Careful with react-native link. It may create duplicates in settings.gradle and MainApplication.java that break android simulator.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
