### ISSUE TITLE
SyntheticEvent lib for importing location

### ISSUE THREAD

**Issue by lastingyeh** [react-community/react-native-maps#1394]
use the examples for EventListener.js,I can't import the lib 'SyntheticEvent' from 'react-native/Libraries/Renderer/src/renderers/shared/stack/event/SyntheticEvent'

so I change the import path for this one 'react-native/Libraries/Renderer/src/renderers/shared/shared/event/SyntheticEvent'

it can work...(use  "react-native": "0.44.2")

may you confirm that path is right way to write..

thanks

**Comment by rborn** [comment]
The example files were updated so they don't contain `SyntheticEvent` anymore.
Closing.
