### ISSUE TITLE
wont open map

### ISSUE THREAD

**Issue by Radec43** [react-community/react-native-maps#1395]
on some android devices map can be open and everything works... and on some other andorid devices(mostly samsung) map can be open but when i go back the whole screen is black except the nav bar and there is the worst case scenario on some android devices where i got this error : 
https://s11.postimg.org/p0fvgkv1v/Screenshot_20170605-143044.png
on ios devices everything works fine
react-native-cli: 2.0.1
react-native: 0.40.0
"react-native-maps": "^0.13.0",
"react-navigation": "^1.0.0-beta.7",

**Comment by vnhnhm** [comment]
See [`#1358`](https://github.com/airbnb/react-native-maps/issues/1358).
