### ISSUE TITLE
[CUSTOM DOUBLE TAP EVENT]

### ISSUE THREAD

**Issue by pedrobertao** [react-community/react-native-maps#1396]
Hello everyone,
I`m currently working with a app that requires as a main component the react-native-maps. With that in mind, there were an unusual request to customize the double tap function on the map. Basically we need to set the double tap event to do function A (ZOOM) and the next double tap event to do function B (Show all the currently markers on the map). The function is the easy part but I`m not seeing any solution for this and even can`t see the double tap event on the onPress={} props of the mapview.
Does anyone have any tip on this matter ?

**Comment by WonderDev21** [comment]
I need the same method.
Could you let me the solution?
Thanks.

**Comment by rborn** [comment]
@pedrobertao @WonderDev21  it seems that the `doubleTap` event is not exposed. 
As an aside what you are trying to do will break the user expectations -  you will have the same action with 2 possible  outcomes and this is bad UX.

I'll close the issue for now.
