### ISSUE TITLE
animateToRegion division delta values problem

### ISSUE THREAD

**Issue by okarakose** [react-community/react-native-maps#1397]
**Environment**

- Native Maps version: 0.13
- React Native version: 0.43.4
- Platform(s) (iOS, Android, or both?): Android && iOS Both

**Description**
AirMapManager animateToRegion function does not work properly. it is dividing given delta values of latitude and longitude.

**Our JS Code**
    
    let region = {
        latitude: 41.041360,
        longitude: 28.920083,
        latitudeDelta: 0.01,
        longitudeDelta: 0.01
    }
    this.refs.map.animateToRegion(region, 750)

**AirMapManager.java** ( react-native-maps class )

    @Override
    public void receiveCommand(AirMapView view, int commandId, @Nullable ReadableArray args) {
        Integer duration;
        Double lat;
        Double lng;
        Double lngDelta;
        Double latDelta;
        ReadableMap region;

        switch (commandId) {
            case ANIMATE_TO_REGION:
                region = args.getMap(0);
                duration = args.getInt(1);
                lng = region.getDouble("longitude");
                lat = region.getDouble("latitude");
                lngDelta = region.getDouble("longitudeDelta");
                latDelta = region.getDouble("latitudeDelta");
                LatLngBounds bounds = new LatLngBounds(
                        new LatLng(lat - latDelta / 2, lng - lngDelta / 2), // southwest
                        new LatLng(lat + latDelta / 2, lng + lngDelta / 2)  // northeast
                );
                view.animateToRegion(bounds, duration);
                break;

Why **latDelta** and **lngDelta** values **dividing to 2** at LatLng calculation ?

**Comment by rexlow** [comment]
+1

**Comment by alvelig** [comment]
https://developer.apple.com/documentation/mapkit/mkcoordinatespan/1452417-latitudedelta

This is north-to-south and east-to-west. Region center in the crossing of this lines.
