### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by AshokICreate** [react-community/react-native-maps#1401]
**Update Installation Instructions Documentation with latest version of React-Native.**

**Update Setup Instructions Documentation for the Included Example Project with latest version of React-Native.**

**Update Example Project with latest version of React-Native.**

**Comment by shenst1** [comment]
There is no longer a ```package.json``` file in the example folder, it is in the main root, so at least that needs to be updated. I haven't been able to get the example working after that refactor.

**Comment by kafkaca** [comment]
+1

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
