### ISSUE TITLE
Possible to use user's location as initial region with using RN's geolocation?

### ISSUE THREAD

**Issue by lsps9150414** [react-community/react-native-maps#1407]
### Goal:
Open the map with the user's current location at the center.

### Using RN's geolocation:
Use RN's `geolocation ` to get user's location at `componentDidMount` and feed `LatLng` to map's `initialRegion`.
https://stackoverflow.com/questions/43176862/how-can-i-get-current-location-latlong-in-react-native-maps

### Question:
Since it's possible to center the user's location simply with the `MyLocationButton`. I'm wondering if it's possible to center the user's location at map init without the help of `geolocation`?

**Comment by alvelig** [comment]
Take: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
Or wait for: #1874
