### ISSUE TITLE
how to trigger default marker popup

### ISSUE THREAD

**Issue by texas697** [react-community/react-native-maps#141]
I am trying to trigger a marker popup by the markerId. I see the showCallout method available in the examples but, how do I pass the marker id of the marker i want to focus on?

**Comment by osungjin** [comment]
Are you solved it?

**Comment by py110** [comment]
i see the demo 
    this.refs.m1.showCallout();
i use this method in 
  componentDidMount(){
    this.refs.m1.showCallout();
  },
no result

**Comment by cmunson** [comment]
This is a timing issue. You have to wait until the marker is fully rendered before showing the popup. I think you need at least a second delay. 

`  componentDidMount() {
    setTimeout(function() {
      this.refs.newMarkerInfo.showCallout();
    }.bind(this), 2000);
  }`

**Comment by wonskarol** [comment]
@cmunson your solution works, but as you mentioned it's not the best way to solve the problem... Does anyone else have other ideas?

**Comment by alvelig** [comment]
merging to #849

**Comment by NomanGul** [comment]
How to pass marker ID? because I'm rendering many markers and wanted to show callout on specific marker... :\
