### ISSUE TITLE
Maps work only on my emulator

### ISSUE THREAD

**Issue by ElGecko76** [react-community/react-native-maps#1410]
Hi,

I have a strange problem, the map appears correctly on my emulator but it does not appear on my phone or on another PC .. 

I don't understand why, do you have an idea ?

Thanks in advance.

My code : 

`import React, {Component} from 'react';
import {StyleSheet, Text, View, AsyncStorage} from 'react-native';
import Prompt from 'react-native-prompt';
import MapView, {Marker} from 'react-native-maps';

export default class Home extends Component {

    // Sert pour le TabNavigator
    static navigationOptions =
        {
            title: 'Accueil',
            headerStyle: {backgroundColor: '#3498db'},
            headerTitleStyle: {color: 'white'}
        };

    state =
        {
            message: '',
            promptVisible: false,
            pseudoUser: '',
            latitude: 0.0,
            longitude: 0.0,
            error: null,
            markers: [{
                pseudo: 'ElGecko',
                description: 'Coucou tout le monde',
                coordinates: {
                    latitude: 49.4431,
                    longitude: 1.0993
                }
            },
                {
                    pseudo: 'Gregou',
                    description: 'Coucou hihihi',
                    coordinates: {
                        latitude: 49.4667,
                        longitude: 1.1167
                    }
                }]
        }

    // Il faut que chaque composant ai un ID unique, de base RN le fait, sauf pour les foreach/map
    uniqueId() {
        let text = '';
        const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_';

        for (let i = 0; i < 128; i += 1)
            text += possible.charAt(Math.floor(Math.random() * possible.length));

        return (text);
    }

    // Lancé avant le render, tout ce qu'on veut faire avant l’affichage va dans willmount
    componentWillMount = () =>
    {
        this.load();
        this.setDefaultPosition();
        this.setPosition();
    }

    // Charge le pseudo dans le state
    async load() {
        const value = await AsyncStorage.getItem('pseudo');
        //Alert.alert(value);
        this.setState({
            pseudoUser: value,
            promptVisible: value == '' || !value
        });

        //AsyncStorage.clear();
    }

    // Sauvegarde le pseudo sur le téléphone
    async save() {
        await AsyncStorage.setItem('pseudo', this.state.pseudoUser);
    }

    // Si un pseudo est renseigné alors on le stocke dans le state, sinon on laisse le prompt ouvert
    checkPseudo = (pseudo) => {
        if (pseudo !== '') {
            this.setState({promptVisible: false, message: pseudo});
            this.state.pseudoUser = pseudo;
            this.save();
        }
    }

    // Obtient la position actuelle
    setDefaultPosition = () =>
    {
        navigator.geolocation.getCurrentPosition((position) =>
        {
            this.setState({
                latitude: position.coords.latitude,
                longitude: position.coords.longitude,
                error: null,
                enableHighAccuracy: true,
                timeout: 60000,
                maximumAge: 1000,
                distanceFilter: 10
            });
        }, error => this.setState({error: error.message}));
    }

    // Détecte les changements de position
    setPosition = () => {
        this.watchId = navigator.geolocation.watchPosition((position) => {
            this.setState({
                latitude: position.coords.latitude,
                longitude: position.coords.longitude,
                error: null,
                enableHighAccuracy: true,
                timeout: 60000,
                maximumAge: 1000,
                distanceFilter: 10
            });
        }, error => this.setState({error: error.message}));
    }

    componentWillUnmount = () => navigator.geolocation.clearWatch(this.watchId)

    render = () => {
        return (
            <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
                <MapView
                    style={styles.map}
                    region={{
                        latitude: Number(this.state.latitude),
                        longitude: Number(this.state.longitude),
                        latitudeDelta: 2,
                        longitudeDelta: 2
                    }}>
                    {
                        this.state.markers.map(marker =>
                            (
                                <MapView.Marker
                                    key={this.uniqueId()}
                                    coordinate={marker.coordinates}
                                    title={marker.pseudo}
                                    description={marker.description}/>
                            ))
                    }
                </MapView>
                {
                    this.state.error ? <Text>Error: {this.state.error}</Text> : null
                }
                <Prompt
                    title={'Votre pseudo'}
                    placeholder={'Choisissez un pseudo'}
                    visible={this.state.promptVisible}
                    onCancel={() => this.setState({promptVisible: true})}
                    onSubmit={pseudo => this.checkPseudo(pseudo)}/>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    map: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0
    }
});`

![image](https://user-images.githubusercontent.com/19478137/27218022-a9cdbe76-527c-11e7-8377-5babfe651584.png)

**Comment by alvelig** [comment]
Google Api_KEY. See your android logs. There will be a red warning about API_KEY
