### ISSUE TITLE
Exception when unmounting/removing the map from view

### ISSUE THREAD

**Issue by freshnewegg** [react-community/react-native-maps#1414]
Hi,

Has anyone seen this before on IOS? I'm simply reseting the state in JS and this pops up.

I'm Using RN 0.40 and Maps at v0.15.2

<img width="284" alt="screen shot 2017-06-16 at 10 33 40 pm" src="https://user-images.githubusercontent.com/5714313/27249455-fc4b34fa-52e3-11e7-80cc-c0314970b4ae.png">

**Comment by alvelig** [comment]
Provide a repo to reproduce your problem, but it's likely not related.
