### ISSUE TITLE
How can I change Google copyright and showsMyLocationButton position?

### ISSUE THREAD

**Issue by hiepvv** [react-community/react-native-maps#1419]
I want to add some View and Button into my Component (has mapview already). But it will overlay Google copyright and showsMyLocationButton, so how can i change those's position. I saw Grab app can do it, but i don't how.
![19369001_1798292477147786_1628207168_o](https://user-images.githubusercontent.com/19855405/27328312-ecf3814c-55db-11e7-9e87-7c452b6bcac5.png)
![19401168_1798292457147788_406477077_o](https://user-images.githubusercontent.com/19855405/27328316-f48ee964-55db-11e7-985c-94ec229cb57e.png)
![19403329_1798297163813984_546101855_o](https://user-images.githubusercontent.com/19855405/27328330-04eac60c-55dc-11e7-8362-d129d613e6aa.png)

**Comment by SidharthRaveendran** [comment]
@hiepvv Did you find any solution for this?

**Comment by alvelig** [comment]
You can't change Google logo https://developers.google.com/maps/documentation/android-api/map#map_padding

For the button wait: #1874

**Comment by alvelig** [comment]
Created an enhancement issue for this #1875
