### ISSUE TITLE
urlTemplate of Local files

### ISSUE THREAD

**Issue by tnmendes** [react-community/react-native-maps#1420]
Already download the files of one city to the project but now I am trying to open the images (local images, URI), do you know how to hack so this work?

```
<MapView.UrlTile
            //urlTemplate="http://c.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg"
            urlTemplate='../img/tiles/{z}/{x}/{y}.png'
            zIndex={-1}
/>
```

thank you in advance

**Comment by shenst1** [comment]
Were you able to get the demo url working? I still haven't been able to do even that. However, my end goal is the same as yours (hosting locally). I isolated the UrlTile in a repo for experimentation and all I get is a beige screen on my map instead of the water color tiles.  [1404](https://github.com/airbnb/react-native-maps/issues/1404)

**Comment by tnmendes** [comment]
Hi @shenst1 yes did put everting working. Here is the code change that i did. Just for iOS

Go to the file AIRMapUrlTile > the change function createTileOverlayAndRendererIfPossible
Add this:

NSString *baseURL = [[[NSBundle mainBundle] bundleURL] absoluteString];
    NSString *urlTemplate = [baseURL stringByAppendingString:@"img/tiles/{z}/{x}/{y}.png"];
    self.tileOverlay = [[MKTileOverlay alloc] initWithURLTemplate:urlTemplate];


End Result:

- (void) createTileOverlayAndRendererIfPossible
{
    if (!_urlTemplateSet) return;
    
    NSString *baseURL = [[[NSBundle mainBundle] bundleURL] absoluteString];
    NSString *urlTemplate = [baseURL stringByAppendingString:@"img/tiles/{z}/{x}/{y}.png"];
    self.tileOverlay = [[MKTileOverlay alloc] initWithURLTemplate:urlTemplate];
    
    //self.tileOverlay = [[MKTileOverlay alloc] initWithURLTemplate:self.urlTemplate];

    self.tileOverlay.canReplaceMapContent = YES;
    self.renderer = [[MKTileOverlayRenderer alloc] initWithTileOverlay:self.tileOverlay];
}

**Comment by shenst1** [comment]
What value did you put in ```<Mapview.UrlTile urlTile="?" >```. Also, would you mind sharing your version of react-native and react-native-maps that you are using. Still not having any luck with this.

**Comment by tnmendes** [comment]
I had used this example as base:

https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js
I let the everything as it is inclusive the same link             `urlTemplate="http://c.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg"`
because is mandatory to have some link in the system even is after is not used.

You also can't forget what i did createTileOverlayAndRendererIfPossible its hack and programmatic is not correct.

**Comment by fangkyi03** [comment]
Can you load the local tile map as long as you change it?

**Comment by Stophface** [comment]
@tnmendes Your changes in the `java` file made it possible to load tiles, stored locally on the phone? Could you share what you did on the `JavaScript` side to make it work?

**Comment by tnmendes** [comment]
@Stophface was another person who made change on the Android part but from what I understand it is easy to change the system since RN-Maps are using Google maps as based.
Regarding the JavaScript file I just copy paste https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js

**Comment by alvelig** [comment]
PR#1876 closes this
