### ISSUE TITLE
Some packages of react-native removed after install react-native-maps

### ISSUE THREAD

**Issue by design6** [react-community/react-native-maps#1421]
Before I install react-native-maps, the project is run correctly but after install maps it says : 
Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

**Comment by funbytehu** [comment]
I had the same problem.
I have this workaround: reinstall node.js (npm) from here: https://nodejs.org/en/
Be sure that you install the LTS version
Init a new version (I tried with version 0.44, but may also work with 0.43 and 0.45:
`react-native init projectname --version react-native@0.44` )
Copy the resources of your project (for example, the src folder)
Add the packages you include in your project, and then run the `react-native run-ios` or `react-native run-android`
I hope you can fix it :)

**Comment by design6** [comment]
Thanks for your solution but it is still not working for me or I missed something.
