### ISSUE TITLE
Feature Request : Add navigation property .

### ISSUE THREAD

**Issue by GeekRishabh** [react-community/react-native-maps#1425]
Please add the navigation property that draws the polyline on the map component . and when we pass the new location coordinated the component rerender accordingly . 
use case >  I want to show the route from location x to location Y and the path he can choose to go . with traffic / without traffic . When his GPS or entered coordinated for initial destination changes the polyline should change accordingly . Show up the marker on polyline where the user is currently and the end point .

**Comment by vinagrito** [comment]
https://github.com/airbnb/react-native-maps/issues/1354
