### ISSUE TITLE
Markers successfully disappear, but do not re-appear

### ISSUE THREAD

**Issue by yenicelik** [react-community/react-native-maps#1426]
I am currently building an app with react-native and am using the Airbnb maps plugin to dynamically display markers. My markers are downloaded from the firebase database successfully, and the array that is downloaded always shows the correct contents. I have the full code here just in case https://codepen.io/yeni/pen/Kqyrxv?editors=0010 :)

Whenever I change the `cur_user` property of a marker to `1`, it is successfully not shown on the map. However, when I change `cur_user` back to `0`, the marker is not display (which would be the desired behavior). My code looks as follows:

 
```
    //Store file MarkersStore.js
    class MarkersStore {
  @observable markers = [];

  constructor() {
      console.log("Started downloading markers");
      var localMarkers = [];
      Fb.bikes.on('value', (snap) => {
        localMarkers = [];
        snap.forEach((marker) => {
            localMarkers.push({
              longitude: parseFloat(marker.val().positionLng),
              latitude: parseFloat(marker.val().positionLat),
              description: "Bike 1",
              title: "b" + String(marker.val().bike_no),
              bike_no: marker.val().bike_no,
              cur_user: marker.val().current_user,
              key: marker.getKey()
            })
        });
        //Once must make sure that the upper command already finished executing!
        this.markers.replace(localMarkers);
        console.log("Loaded markers");
      });
  }

}

    ...
    //Rendering file MarkersComponent.js
    render() {
    var renderingMarkers = this.fbMarkers.markers.slice() || [];
    console.log("fbMarkers are: ");
    console.log(this.fbMarkers.markers.slice());
    console.log("Rendering stuff..");
    console.log(renderingMarkers);
    console.log("Rendering ALL the stuff!");
    return (<View>
      {renderingMarkers.map( (marker) => {
        console.log("Markers are re-rendered");
        console.log(marker.bike_no);
        console.log(marker.cur_user);
        //All console logs up until here show correct results
          return (
            <View key={marker.bike_no}>{ (marker.cur_user == 0) ?
              <MapView.Marker
            navigator={this.props.navigator}
            key={marker.bike_no}
            coordinate={{longitude: marker.longitude, latitude: marker.latitude}}
            title={marker.title}
            description={marker.description}
            onPress={(coord, pos) => this.startBookingBike(marker.bike_no)}
            ><View style={styles.bikeRadius}><View style={styles.bikeMarker}>
            </View></View>
            </MapView.Marker> : null
          }</View>
          );
    })}</View>)
  }
```
Also, the autorun is successfully triggered each time I change some data in the database (and the correct retrieved data is displayed). Is there potentially any way to put the autorun feature inside the render method to successfully rerender everything?

** EDIT **
I have also opened up an issue on the official github page, as this seems to be a bug. Correct me if I'm wrong! :) https://github.com/airbnb/react-native-maps/issues/1426

**Comment by yenicelik** [comment]
@lelandrichardson Any ideas? Sry if this is pushy, but after a week of debugging, I really don't know what to do :/

**Comment by sorodrigo** [comment]
Hey I'm stuck with a similar issue, did you found a solution??

**Comment by yenicelik** [comment]
@sorodrigo Not really a solution but a work around. I simply create a new styleclass where the display-property is hidden, and just use the ternary operator to select this class depending on a certain condition that toggles the preview of the individual markers :) Hope it works! I'm not sure how scalable and bug-prone it is, but it didn't cause any problems so far for me

**Comment by alvelig** [comment]
Cmon, you must use state or connected redux store. You don't do any. Try managing your marker state or manage markers in map state
