### ISSUE TITLE
When Running react-native run-android inside example folder, throwing error in console

### ISSUE THREAD

**Issue by andrisole92** [react-community/react-native-maps#1435]
`react-native run-android`
`Command 'run-android' unrecognized. Make sure that you have run 'npm install' and that you are inside a react-native project.`

I have run npm install before, does not work anyways

**Comment by henrikra** [comment]
Run it at right folder

**Comment by andrisole92** [comment]
I am running it from `./example` folder, isn't it correct?

**Comment by henrikra** [comment]
run `npm i` in root folder not `example` folder

**Comment by andrisole92** [comment]
Okay, I did `npm i` in the root folder, then `react-native run-android` in the root folder, got: `Android project not found. Maybe run react-native android first?`

**Comment by andrisole92** [comment]
Then `cd example`, `react-native run-android`:  `Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.`

**Comment by thomasbaldwin** [comment]
Try `npm run run:android` @andrisole92

**Comment by alvelig** [comment]
@thomasbaldwin is the right way to do.

**Comment by IgorGanapolsky** [comment]
@thomasbaldwin What is **run:android**?

**Comment by alvelig** [comment]
@IgorGanapolsky see `package.json`

**Comment by montao** [comment]
I reinstalled react-native. Ridiculous but it worked.

**Comment by igorivanov0988** [comment]
cd.. enter затем react-native run-android

**Comment by erikbrgr** [comment]
Royally late but in case someone runs into this issue and the above doesn't work:

From the root folder, I ran `cd android && ./gradlew clean`, then `cd .. && npx react-native run-android`.
