### ISSUE TITLE
High CPU load and app crash due to maps component with followsUserLocation=true

### ISSUE THREAD

**Issue by svenadlung** [react-community/react-native-maps#1437]
I recognized using the component with

`showsUserLocation={true}`
`followsUserLocation={true}` 

causes high CPU usage, which leads into crashing my app (bug_type 206, > 80% average CPU usage within 60 seconds).

Take a look at the peaks in instruments (peaks are around 100% CPU usage):

![instruments](https://user-images.githubusercontent.com/11420688/27586604-4bba6172-5b41-11e7-896e-3c1598be74d8.png)

Using 
> "react": "16.0.0-alpha.6"
> "react-native": "0.43.1"
> "react-native-maps": "^0.14.0"

Anyone else facing this problems?

**Comment by alvelig** [comment]
iOS or Android? Do you mind updating your issue according to new issue template? We'll reopen then and certainly review this
