### ISSUE TITLE
Feature Request: Setting the width of a custom marker view in meters

### ISSUE THREAD

**Issue by cbartondock** [react-community/react-native-maps#1442]
I would, for example, like to be able to display a circle with text at the center specifying it's radius in meters. This text and the circle would shrink (in pixels) as one zooms out on the map because their dimensions are fixed relative to a length in meters. As far as I understand it this is not currently possible.

If anyone has any suggestions I would welcome them, if not then I would like to request this feature! Thanks for being an excellent addition to react native's ecosystem.

**Comment by alvelig** [comment]
Use MapView.Circle. That's what it's for. In the center of this circle use custom marker with text. You will have to control it's fontSize watching for zoom.
