### ISSUE TITLE
iOS example not working

### ISSUE THREAD

**Issue by thomasbaldwin** [react-community/react-native-maps#1445]
I ran `npm i` in the root folder, and then ran `npm run run:ios` but no bone. What am I doing wrong?

<img width="1436" alt="screen shot 2017-06-30 at 1 24 31 pm" src="https://user-images.githubusercontent.com/5099084/27747011-83b0f7f0-5d97-11e7-9b38-2b1476bed85d.png">

<img width="782" alt="screen shot 2017-06-30 at 1 24 40 pm" src="https://user-images.githubusercontent.com/5099084/27747015-88cad12a-5d97-11e7-80dc-89021521db3b.png">

**Comment by christopherdro** [comment]
>"The sandbox is not in sync with Podfile.lock. Run **`pod install`** or update you Cocoapods installation"

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
