### ISSUE TITLE
Example can't be install

### ISSUE THREAD

**Issue by agungjk** [react-community/react-native-maps#1457]
I run `yarn install` on example folder but failed, its like **package.json** is missing

**Comment by christopherdro** [comment]
`yarn install` should be executed on the root folder, not inside the `example` folder.

**Comment by agungjk** [comment]
@christopherdro i already run on the root project, but error occured when running to android "Android project not found. Maybe run react-native android first?"

**Comment by christopherdro** [comment]
@agungjk Might be a bit tricky to use the cli to start the project since the directory structures are a bit different than your traditional `react-native init` app.

My suggestion would be to use android studio to open the example project.

**Comment by agungjk** [comment]
@christopherdro the previous version example is working a long time ago, maybe you can update the example readme.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
