### ISSUE TITLE
Android: MapView prevents interacting with app in release build

### ISSUE THREAD

**Issue by bgnlordhelmut** [react-community/react-native-maps#1471]
Running into an issue where rendering a MapView is causing an Android release build to prevent interaction with the entire app on the specific physical device I am testing with. Touch events seem to be registering in some fashion (in logcat I'm able to see: "E unknown:React: Got DOWN touch before receiving UP or CANCEL from last gesture"), but nothing in the react native application is responding as it should. If I remove the MapView from the app code, everything works fine again and the application is fully responsive.

This is not occurring in debug mode, nor in iOS builds (either debug or release), nor on other physical Android devices. Below are some of the settings/versions/build configs:

Android device: LG V10
Android version: 6.0.0 (min sdk 16, target sdk 22)
Using react-native-maps version 0.15.2
Using React Native version 0.43.3
Using React version 16.0.0-alpha.6

Manually added the following pull requests to AirMapView.java:

- https://github.com/airbnb/react-native-maps/pull/1464/commits/cdf6a5dc8869dff19bb9c2d4a59c44aef93b9880

- https://github.com/airbnb/react-native-maps/pull/1403/commits/5bb19267747ed3e1022d82f5df5d1a12bb72cdb8

build.gradle
`configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-ads:11.+'
    force "com.google.android.gms:play-services:11.+"
    force "com.google.android.gms:play-services-location:11.+"
    force "com.google.android.gms:play-services-gcm:11.+"
    force "com.google.android.gms:play-services-analytics:11.+"
  }
}

dependencies {
    compile project(':react-native-barcodescanner')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-image-picker')
    compile project(':react-native-share')
    compile project(':react-native-push-notification')
    compile project(':realm')
    compile project(':react-native-vector-icons')
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile "com.google.android.gms:play-services-base:11.+"
    compile "com.google.android.gms:play-services-maps:11.+"
    compile project(':react-native-keychain')
    compile project(':react-native-hockeyapp')
    compile project(':react-native-device-info')
    compile project(':react-native-camera')
}`

MapView code that when removed causes the app to function normally:
`<MapView
            initialRegion={this.state.region}
            style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0}}
            showsUserLocation={true}
            region={this.state.region}
          >
            {this.state.markers.map(marker => (
              <MapView.Marker
                key={marker.key}
                coordinate={marker.coordinate}
                image={CustomIcons.iconPath("locationPin")}
              />
            ))}
          </MapView>`

Any help would be greatly appreciated. If you need any additional details please let me know and I will provide. Thank you for your assistance.

**Comment by richardradics** [comment]
+1
I've just run into this issue with almost the same config, but with `react native: 0.44.1`

**Comment by richardradics** [comment]
My logcat is full with this message when I touch the app:
`Got DOWN touch before receiving UP or CANCEL from last gesture`

**Comment by bgnlordhelmut** [comment]
@richardradics I receive the same. It seems as though another activity is picking up the events, but I am not 100% sure.

**Comment by richardradics** [comment]
@bgnlordhelmut not the release mode is the problem, but this:

```
public boolean getUseDeveloperSupport() {
            return false;
}
```
its ridiculous. do u have any idea?

**Comment by bgnlordhelmut** [comment]
@richardradics Is this something you changed to prevent the issue described?

**Comment by richardradics** [comment]
nope, the code above causes the issue. I thought that the issue appears when I build in release mode, but not - the problem comes when we disable the react native developer support

**Comment by jamiely** [comment]
@richardradics we resolved the issue we were seeing. Are you using `react-native-loading-spinner-overlay`? Some combination of the two projects of the two projects happened to cause issues for us. We resolved this by using the `Spinner` view more carefully.

**Comment by richardradics** [comment]
@jamiely yes, I'm using that library. What do you advise?

**Comment by jamiely** [comment]
@richardradics I'd first determine whether the `Spinner` is causing the problem by disabling all spinners or removing them. 

If that _is_ the problem, we resolved our issue by making sure the spinner was NOT displayed on initial construction of the parent component (via state). We also tried to make sure the logic around showing and hiding the spinner was more correct because of the asynchronicity involved.

**Comment by richardradics** [comment]
@jamiely removing the `Spinner` from the app fixes the problem

**Comment by akajack** [comment]
@jamiely Your solution works for me....THANKSSSS!!!

**Comment by 1uokun** [comment]
The same error
My solution may have nothing to do with the problem, but I hope it can help others
```java
// extends View

@Override
public boolean onTouchEvent(MotionEvent event) {
  return true;
}
```
