### ISSUE TITLE
Crash: Map ^0.15.3 and Device Info ^0.10.2.

### ISSUE THREAD

**Issue by Angelk90** [react-community/react-native-maps#1472]
Crash: Map ^ 0.15.3 and Device Info ^ 0.10.2.
As soon as you open the window where the map is located, the app will restart
I've tried the solutions I found on the internet, but I could not fix it.

Can anyone tell me if you can solve the problem?
If so, I could point out all the steps I have to do to solve it.

**Comment by pablo-coco** [comment]
@Angelk90 https://github.com/airbnb/react-native-maps/issues/1028 see @mlanter 's solution. It fixes the problem here.

**Comment by rborn** [comment]
@Angelk90 still having the issue or can  you close it? Thanks.

**Comment by alvelig** [comment]
duplicate of #1028
