### ISSUE TITLE
Current version not compatible with RN < 0.44 (ViewPropTypes)

### ISSUE THREAD

**Issue by paulmasters** [react-community/react-native-maps#1473]
ViewPropTypes replaced View.PropTypes in (I think) RN 0.44 
The peerDependency in the package.json says it's compatible with >=0.40 which is wrong.
Would it be possible to test for the existence of ViewPropTypes, and fall back to View.PropTypes to still support older versions?

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
