### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by dbarros** [react-community/react-native-maps#1478]
When I import MapView, without even rendering a MapView component, I see the following error in the iOS app:

> Cannot read property 'style' of undefined.
> `<unknown>`
> MapView.js:63:23

In the Android app I get:

> undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

I am using react-native-maps 0.15.3, react-native 0.43.0 and react 16.0.0-alpha.6.

This error occurs when I simply add this line to my app:

`import MapView from 'react-native-maps';`

Is this a version problem between React, React Native and react-native-maps with regard to the definition of `ViewPropTypes`?

EDIT: Looks like it could be [breaking change](https://github.com/airbnb/react-native-maps/issues/1473), and [here](https://github.com/airbnb/react-native-maps/issues/1453).

**Comment by leoabacade** [comment]
+1

**Comment by tmwhdgsn** [comment]
+1

**Comment by arsenalol69** [comment]
+1

**Comment by adamSellers** [comment]
+1 but with react-native 0.43.1

**Comment by rheilgm** [comment]
+1

**Comment by prevuelta** [comment]
+1

**Comment by dragosholban** [comment]
+1

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
