### ISSUE TITLE
How to Zoom In and Out in react-native-maps?

### ISSUE THREAD

**Issue by abdelghafourzguindou** [react-community/react-native-maps#1480]
I created my personal buttons to zoom in and out in react-native-maps but It's not working because this error was appeared : _typeError: expected dynamic type 'double', but had type 'null'. So how can do it?_

**This is my code:**

```
import React, {Component} from 'react';
import {View, StyleSheet,TouchableOpacity, Dimensions, Image, Text} from 'react-native';
import MapView from 'react-native-maps';
import Images from '../../config/Images';


const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

class GeoMap extends Component {

    constructor(props) {
        super(props);
        this.state = {
            mapRegion: null,
            lastLat: null,
            lastLong: null,
            latitudeDelta:  0.5,
            longitudeDelta: 0.5 * (screenWidth / screenHeight),
            statusBarHeight: 0,
        }
    }

    componentDidMount() {
        this.watchID = navigator.geolocation.watchPosition((position) => {
            // Create the object to update this.state.mapRegion through the onRegionChange function
            let region = {
                latitude:       position.coords.latitude,
                longitude:      position.coords.longitude,
                latitudeDelta: 0.5,
                longitudeDelta: 0.5 * (width / height)
            }
            this.onRegionChange(region, region.latitude, region.longitude);
            this._map.animateToRegion(region, 100);
        }, function (error) { alert(error) });
    }

    onRegionChange(region, lastLat, lastLong) {
        this.setState({
            mapRegion: region,
            lastLat: lastLat || this.state.lastLat,
            lastLong: lastLong || this.state.lastLong
        });
    }

    componentWillMount() {
        setTimeout(() => this.setState({statusBarHeight: screenHeight-74}), 500);
    }

    componentWillUnmount() {
        navigator.geolocation.clearWatch(this.watchID);
    }

    onPressZoomIn() {
        region = {
            latitude:       this.state.lastLat,
            longitude:      this.state.lastLong,
            ltDelta:        this.state.latitudeDelta * 10,
            lgDelta:        this.state.longitudeDelta * 10
            }
        this.setState={
            latitudeDelta:  region.ltDelta,
            longitudeDelta: region.lgDelta,
            lastLat: region.latitude,
            lastLong: region.longitude
        }
        this._map.animateToRegion(region, 100);
    }

    onPressZoomOut() {
        region = {
            latitude:       this.state.lastLat,
            longitude:      this.state.lastLong,
            ltDelta:        this.state.latitudeDelta / 10,
            lgDelta:        this.state.longitudeDelta / 10
            }
        this.setState={
            latitudeDelta:  region.ltDelta,
            longitudeDelta: region.lgDelta,
            lastLat: region.latitude,
            lastLong: region.longitude
        }
        this._map.animateToRegion(region, 100);
        console.log('lt : ' + region.ltDelta + ' lg : ' + region.lgDelta)
    }



    render() {

        return (
            <View style={{paddingTop: this.state.statusBarHeight}}>
                <MapView
                    ref={component => {this._map = component;}}
                    customMapStyle={mapStyle}
                    style={styles.map}
                    region={this.state.mapRegion}
                    showsUserLocation = {true}
                    followUserLocation = {true}
                    showsMyLocationButton = {true}
                    zoomEnabled = {true}
                    onRegionChange={this.onRegionChange.bind(this)}

                >
                </MapView>
                <TouchableOpacity
                    style={styles.zoomIn}
                    onPress={()=>{this.onPressZoomIn()}}
                    >
                    <Icon 
                        name="plus" 
                        style={styles.icon}
                        size={20} 
                        />
                </TouchableOpacity>
                <TouchableOpacity
                    style={styles.zoomOut}
                    onPress={()=>{this.onPressZoomOut()}}
                    >
                    <Icon 
                        name="minus" 
                        style={styles.icon}
                        size={20} 
                        />
                </TouchableOpacity>
            </View>
        );
    }
}

export default GeoMap;
```

**Comment by NorbertCU** [comment]
I'm not sure that's it, but what I see is that you declared "height" and "width" vars as "screenHeight" and "screenWidth", but you are using "height" and "width" on componentDidMount(). 

componentDidMount() {
        this.watchID = navigator.geolocation.watchPosition((position) => {
            // Create the object to update this.state.mapRegion through the onRegionChange function
            let region = {
                latitude:       position.coords.latitude,
                longitude:      position.coords.longitude,
                latitudeDelta: 0.5,
                longitudeDelta: 0.5 * (width / height) <------------- Here!
            }
            this.onRegionChange(region, region.latitude, region.longitude);
            this._map.animateToRegion(region, 100);
        }, function (error) { alert(error) });
    }
}

Hope that's it.

**Comment by theslyone** [comment]
The region object passed to the MapView.animateToRegion function should be of the form 
```
type Region {
  latitude: Number,
  longitude: Number,
  latitudeDelta: Number,
  longitudeDelta: Number,
}
```
You have passed in the latitude and longitude correctly but the delta keys are incorrect.
Change ltDelta to latitudeDelta and lgDelta to longitudeDelta and it should work fine.

As an example, here is how your onPressZoomIn should look like
```
onPressZoomIn() {
        region = {
            latitude:       this.state.lastLat,
            longitude:      this.state.lastLong,
            latitudeDelta:        this.state.latitudeDelta * 10,
            longitudeDelta:        this.state.longitudeDelta * 10
            }
        this.setState={
            latitudeDelta:  region.ltDelta,
            longitudeDelta: region.lgDelta,
            lastLat: region.latitude,
            lastLong: region.longitude
        }
        this._map.animateToRegion(region, 100);
    }
```
Ref: https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md#methods

**Comment by alvelig** [comment]
deltas are the zoom controls

**Comment by nisargrthakkar** [comment]
any update on this?

**Comment by rborn** [comment]
@nisargrthakkar have you read @theslyone example?

**Comment by nisargrthakkar** [comment]
@rborn Yes I read and try to implement but zoom in and zoom out is not properly working by custom button. I also read the comment and solved the issue with the code. But zoom in/out is not proper working.

**Comment by ddnov** [comment]
just Ctrl+left click on mouse.

**Comment by kartiikeyabaleneni** [comment]
Any  further developments on this. ?

**Comment by alanpramuk9** [comment]
this worked for me
```
class Mapper extends Component {
  constructor(props) {
    super(props)
    this.state = {
      focusedLocation: {
        latitude: 36.14319077106534,
        longitude: -86.76708101838142,
        latitudeDelta: 0.00522,
        longitudeDelta: Dimensions.get("window").width / Dimensions.get("window").height * 0.00522
      }
    };
  }
  onPressZoomIn() {
    this.region = {
      latitude: this.state.focusedLocation.latitude,
      longitude: this.state.focusedLocation.longitude,
      latitudeDelta: this.state.focusedLocation.latitudeDelta * 10,
      longitudeDelta: this.state.focusedLocation.longitudeDelta * 10
    }

    this.setState({
      focusedLocation: {
        latitudeDelta: this.region.latitudeDelta,
        longitudeDelta: this.region.longitudeDelta,
        latitude: this.region.latitude,
        longitude: this.region.longitude
      }
    })
    this.map.animateToRegion(this.region, 100);
  }

  onPressZoomOut() {
    this.region = {
      latitude: this.state.focusedLocation.latitude,
      longitude: this.state.focusedLocation.longitude,
      latitudeDelta: this.state.focusedLocation.latitudeDelta / 10,
      longitudeDelta: this.state.focusedLocation.longitudeDelta / 10
    }
    this.setState({
      focusedLocation: {
        latitudeDelta: this.region.latitudeDelta,
        longitudeDelta: this.region.longitudeDelta,
        latitude: this.region.latitude,
        longitude: this.region.longitude
      }
    })
    this.map.animateToRegion(this.region, 100);
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          region={this.state.focusedLocation}
          style={styles.map}
          mapType={"hybrid"}
          onPress={this.pickLocationHandler}
          showsUserLocation={true}
          followUserLocation={true}
          zoomEnabled={true}
          customMapStyle={mapStyle}
          ref={ref => this.map = ref}
        >
          {this.state.markers.map((marker, index) => (
            <MapView.Marker
              pinColor={'yellow'}
              onPress={e => console.log(e.nativeEvent)}
              key={index}
              coordinate={marker.coordinates}
              title={marker.title}
            />
          ))}
        </MapView>
        <TouchableOpacity
          style={styles.zoomIn}
          onPress={() => { this.onPressZoomIn() }}
        >
          <Icon
            name="add"
            style={styles.icon}
            size={20}
          />
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.zoomOut}
          onPress={() => { this.onPressZoomOut() }}
        >
          <Icon
            name="remove"
            style={styles.icon}
            size={20}
          />
        </TouchableOpacity>
      </View>
    );
  }
}
```

I am still running on an emulator and therefore do not have the lifecycle methods to account for changing region. I am initially setting region state into focusedLocation. That being said, the ZoomIn and ZoomOut functionality work for me. Hope this helps!

**Comment by VikramK** [comment]
On a simulator, cmd + left click of mouse zooms in and cmd + right click of mouse zooms out!

**Comment by ihsanktmr** [comment]
> this worked for me
> 
> ```
> class Mapper extends Component {
>   constructor(props) {
>     super(props)
>     this.state = {
>       focusedLocation: {
>         latitude: 36.14319077106534,
>         longitude: -86.76708101838142,
>         latitudeDelta: 0.00522,
>         longitudeDelta: Dimensions.get("window").width / Dimensions.get("window").height * 0.00522
>       }
>     };
>   }
>   onPressZoomIn() {
>     this.region = {
>       latitude: this.state.focusedLocation.latitude,
>       longitude: this.state.focusedLocation.longitude,
>       latitudeDelta: this.state.focusedLocation.latitudeDelta * 10,
>       longitudeDelta: this.state.focusedLocation.longitudeDelta * 10
>     }
> 
>     this.setState({
>       focusedLocation: {
>         latitudeDelta: this.region.latitudeDelta,
>         longitudeDelta: this.region.longitudeDelta,
>         latitude: this.region.latitude,
>         longitude: this.region.longitude
>       }
>     })
>     this.map.animateToRegion(this.region, 100);
>   }
> 
>   onPressZoomOut() {
>     this.region = {
>       latitude: this.state.focusedLocation.latitude,
>       longitude: this.state.focusedLocation.longitude,
>       latitudeDelta: this.state.focusedLocation.latitudeDelta / 10,
>       longitudeDelta: this.state.focusedLocation.longitudeDelta / 10
>     }
>     this.setState({
>       focusedLocation: {
>         latitudeDelta: this.region.latitudeDelta,
>         longitudeDelta: this.region.longitudeDelta,
>         latitude: this.region.latitude,
>         longitude: this.region.longitude
>       }
>     })
>     this.map.animateToRegion(this.region, 100);
>   }
> 
>   render() {
>     return (
>       <View style={styles.container}>
>         <MapView
>           region={this.state.focusedLocation}
>           style={styles.map}
>           mapType={"hybrid"}
>           onPress={this.pickLocationHandler}
>           showsUserLocation={true}
>           followUserLocation={true}
>           zoomEnabled={true}
>           customMapStyle={mapStyle}
>           ref={ref => this.map = ref}
>         >
>           {this.state.markers.map((marker, index) => (
>             <MapView.Marker
>               pinColor={'yellow'}
>               onPress={e => console.log(e.nativeEvent)}
>               key={index}
>               coordinate={marker.coordinates}
>               title={marker.title}
>             />
>           ))}
>         </MapView>
>         <TouchableOpacity
>           style={styles.zoomIn}
>           onPress={() => { this.onPressZoomIn() }}
>         >
>           <Icon
>             name="add"
>             style={styles.icon}
>             size={20}
>           />
>         </TouchableOpacity>
>         <TouchableOpacity
>           style={styles.zoomOut}
>           onPress={() => { this.onPressZoomOut() }}
>         >
>           <Icon
>             name="remove"
>             style={styles.icon}
>             size={20}
>           />
>         </TouchableOpacity>
>       </View>
>     );
>   }
> }
> ```
> 
> I am still running on an emulator and therefore do not have the lifecycle methods to account for changing region. I am initially setting region state into focusedLocation. That being said, the ZoomIn and ZoomOut functionality work for me. Hope this helps!

it is working

**Comment by mitjnextt** [comment]
Hey Any idea why it givers me this error on iOS??
Exception thrown while executing UI block: Invalid Region <center:+15.97213687, -92.41685691 span:+233.31756735, +171.26038032>

**Comment by QuocVi1994** [comment]
> Hey Any idea why it gives me this error on iOS?? Exception thrown while executing UI block: Invalid Region <center:+15.97213687, -92.41685691 span:+233.31756735, +171.26038032>

same issue, bro, do you have some clue ？

**Comment by bdtren** [comment]
Just don't set the  `region={<value>}`, handle the region changes using the mapRef.current?.animateToRegion(<value>, <duration>) instead.

**Comment by bdtren** [comment]
Just don't set the `region={value}`. 
Remove it and handle the region changes using the `mapRef.current?.animateToRegion(value, duration)` instead.
