### ISSUE TITLE
MapView showing nearby shops although I dissabled it

### ISSUE THREAD

**Issue by MichaelSzer** [react-community/react-native-maps#1488]
I am using Google as provider. 
I set on false the following props: 
`showsBuildings`, `showsPointsOfInterest` but it shows me nearby stores.

**Comment by jeroenbourgois** [comment]
I am facing the same issue

**Comment by alvelig** [comment]
#1517

**Comment by khuongdv** [comment]
> #1517

Why? Is there any helpful answer in #1517?
