### ISSUE TITLE
Custom info window

### ISSUE THREAD

**Issue by nazarTrynko** [react-community/react-native-maps#1490]
Is there a way to add custom info window?

**Comment by rakibulalam** [comment]
<MapView.Callout>
                            <Text> Md. Rakibulalam (@you can test it)</Text>
                        </MapView.Callout>

**Comment by alvelig** [comment]
If not #1556 then see docs (@rakibulalam's answer is ok)

**Comment by pawan8525** [comment]
i implemented cluster on react-native-map in mobile app but my requirement is like below , i dont know it is possible in react-native-map or not. Please help me team
Thank you for your kind cooperation.
First part show cluster that i implemented very well.
![image](https://user-images.githubusercontent.com/38987561/44912242-2c297d80-ad47-11e8-95d3-d5d62094bb0b.png)


second part when press on cluster icon it show hidden marker that is almost on same location that i don't know how to implement please see image

![image](https://user-images.githubusercontent.com/38987561/44912254-351a4f00-ad47-11e8-9517-7487e4f6bbb8.png)

Please if any plugin in react-native taht help me

**Comment by luiz13lg** [comment]
thanks a lot @rakibulalam for showing this Callout example, it was all I was looking for!!!

**Comment by rakibulalam** [comment]
you are welcome  @luiz13lg
