### ISSUE TITLE
Map prevents fetch execute fully

### ISSUE THREAD

**Issue by krizka** [react-community/react-native-maps#1492]
In my onRegionChangeComplete I make request to api with call to `fetch`. In `then` Im updating the state of markers. `fetch().then(...)` callback is paused its execution and not called until another click on map or other event happened. So, map blocking the entire update loop?
```
14:32:46.944 Map.js:52 markers start update
14:32:55.153 Map.js:55 markers end update
14:32:55.172 Map.js:103 map on press

14:33:03.166 Map.js:52 markers start update
14:33:07.731 Map.js:55 markers end update
14:33:07.742 Map.js:103 map on press
```
Here is the log, Im writing before fetch, in fetch callback and in map onPress method respectively.
Pay attention on long delay between `markers update start/end` and short before `map on press`.
**Update**: Fetch method looks the following:
``` 
fetch(url)
    .then(res => res.json()) // this one called immediately, then res.json() paused until onPress
    .then(res => callback(null, res)) // this called just before onPress called
    .catch(err => callback(err))
```

**Update2**: Only iOS simulator, ok on device

**Comment by alvelig** [comment]
try putting it in setTimeout()
