### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by thomasbaldwin** [react-community/react-native-maps#1497]
I'm just using your example demo to display a draggable marker and my app is using over 200MB of memory. This seems pretty unacceptable. Am I doing something wrong or is this just how much memory your library uses?

Please check out my stackoverflow post:

https://stackoverflow.com/questions/45225363/react-native-acceptable-amount-of-memory-usage

**Comment by alvelig** [comment]
That may depend on many factors. But still we don't see a problem in memory consumption.
