### ISSUE TITLE
How to change home directory when running `yarn`?

### ISSUE THREAD

**Issue by zhaoyi0113** [react-community/react-native-maps#1502]
I have a nodejs project and using `yarn` to build it. For some reasons, the user home directory is read-only. When I run `yarn install` in my project I get below error:

    error An unexpected error occurred: "EACCES: permission denied, mkdir '/home/jenkins/.config'".

it seems that `yarn` is trying to access user home directory. The environment is setup by CI so I can't change the home folder permission. How can I restrict `yarn` only use current application directory?

I know for `npm` I can use below environment varaible but I am not sure about how to do that in `yarn`.

    export npm_config_cache=npm-cache

**Comment by alvelig** [comment]
Not related.
