### ISSUE TITLE
 ERROR  ENOENT: no such file or directory

### ISSUE THREAD

**Issue by leoabacade** [react-community/react-native-maps#1510]
<img width="578" alt="screen shot 2017-07-26 at 12 08 24 pm" src="https://user-images.githubusercontent.com/2664504/28604190-80441f7a-71fb-11e7-8371-507478ab7f2c.png">

android 
"react-native": "0.43.4",
"react-native-maps":"0.15.3"

**Comment by alvelig** [comment]
Use latest. Try this example: https://github.com/alvelig/react-native-maps-example
