### ISSUE TITLE
MapView.Polygon onPress event only fire once

### ISSUE THREAD

**Issue by alexaung** [react-community/react-native-maps#1511]
I have added country map and this country have 14 states. So I have added different color for each state. Also added Polygon onPress event for each Polygon. But it is only fire for first time click. It is happening on iOS.

`const Geojson = props => {
  const overlays = makeOverlays(props.geojson.features);
  debugger
  return (
    <View>
      {overlays.map(overlay => {
        if (overlay.type === 'point') {
          return (
            <MapView.Marker
              key={overlay.id}
              coordinate={overlay.coordinates}
              pinColor={props.color}
            />
          );
        }
        if (overlay.type === 'polygon') {
          return (
            <MapView.Polygon
              key={overlay.id}
              coordinates={overlay.coordinates}
              holes={overlay.holes}
              strokeColor={overlay.feature.properties.stroke}
              fillColor={overlay.feature.properties.fill}
              strokeWidth={props.strokeWidth}
              onPress={() => props.onPress(overlay)}
            />
          );
        }
        if (overlay.type === 'polyline') {
          return (
            <MapView.Polyline
              key={overlay.id}
              coordinates={overlay.coordinates}
              strokeColor={props.strokeColor}
              strokeWidth={props.strokeWidth}
            />
          );
        }
      })}
    </View>
  );
};`

![img_0029](https://user-images.githubusercontent.com/1129760/28630999-d889571c-7251-11e7-86e6-bbb0242ac770.PNG)

**Comment by alexaung** [comment]
`const Geojson = props => {
  const overlays = makeOverlays(props.geojson.features);
  debugger
  return (
    <View>
      {overlays.map(overlay => {
        if (overlay.type === 'point') {
          return (
            <MapView.Marker
              key={overlay.id}
              coordinate={overlay.coordinates}
              pinColor={props.color}
            />
          );
        }
        if (overlay.type === 'polygon') {
          return (
            <MapView.Polygon
              key={overlay.id}
              coordinates={overlay.coordinates}
              holes={overlay.holes}
              strokeColor={overlay.feature.properties.stroke}
              fillColor={overlay.feature.properties.fill}
              strokeWidth={props.strokeWidth}
              onPress={() => props.onPress(overlay)}
            />
          );
        }
        if (overlay.type === 'polyline') {
          return (
            <MapView.Polyline
              key={overlay.id}
              coordinates={overlay.coordinates}
              strokeColor={props.strokeColor}
              strokeWidth={props.strokeWidth}
            />
          );
        }
      })}
    </View>
  );
};`

**Comment by dennisbejencev-an** [comment]
where did you get props.geojson.features, and what do make makeOverlays function?

**Comment by alvelig** [comment]
@alexaung please provide a minimal reproducible example!
