### ISSUE TITLE
Android linking issue

### ISSUE THREAD

**Issue by sergeylaptev** [react-community/react-native-maps#1513]
I've added maps and gms dependencies like this:
**app/build.gradle**
```
compile(project(':react-native-maps')) {
  exclude group: 'com.google.android.gms', module: 'play-services-base'
  exclude group: 'com.google.android.gms', module: 'play-services-maps'
}
compile 'com.google.android.gms:play-services-base:11.+'
compile 'com.google.android.gms:play-services-maps:11.+'
```
Everything seems to be working fine until I execute command `react-native link react-native-maps`
Linker tries to detect `compile project(':react-native-maps')` in gradle file, can't find it and adds ALL imports again. After linking my project diff looks like this:

![image](https://user-images.githubusercontent.com/5740795/28665719-4fca439c-72cd-11e7-9e04-cbddd2c154bb.png)

**Comment by ayushinigam** [comment]
I am facing the same issue. Did you find any fix for this?

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
