### ISSUE TITLE
Event, when user taps into the map but doesn't tap marker

### ISSUE THREAD

**Issue by goinnovative** [react-community/react-native-maps#1515]
Hey,

I know the onPress- and the onMarkerPress-Event. But I want to do some stuff when the user clicks outside of a marker on the map.

When it is not possible to listen to this event, is it possible to listen to a event, when the user drags the map? For onPanDrag we have to disable scroll and onRegionChangeComplete also get fired when change region by code...

**Comment by mtt87** [comment]
```jsx
<MapView
          onPress={(e) => {
            if (e.nativeEvent.action !== 'marker-press') {
              // pressed a marker
            } else {
              // pressed the map
            }
          }}
/>
```

**Comment by poleselfg** [comment]
> ```js
> <MapView
>           onPress={(e) => {
>             if (e.nativeEvent.action !== 'marker-press') {
>               // pressed a marker
>             } else {
>               // pressed the map
>             }
>           }}
> />
> ```

still works like a charm on android and ios

**Comment by alexpchin** [comment]
> > ```js
> > <MapView
> >           onPress={(e) => {
> >             if (e.nativeEvent.action !== 'marker-press') {
> >               // pressed a marker
> >             } else {
> >               // pressed the map
> >             }
> >           }}
> > />
> > ```
> 
> still works like a charm on android and ios

FYI, it's the other way around...

```
if (e.nativeEvent.action !== 'marker-press') {
  // pressed the map
} else {
  // pressed a marker
}
```
