### ISSUE TITLE
How to disable all Google Places on the map (hotels, restaurants, shoppings, ...)?

### ISSUE THREAD

**Issue by seisequarenta** [react-community/react-native-maps#1517]

**Comment by andfk** [comment]
Create a custom google map style to achieve that

**Comment by jrgarciadev** [comment]
I share the map style

```javascript
mapStyle = [
  {
    elementType: "labels",
    stylers: [
      {
        visibility: "off"
      }
    ]
  },
  {
    featureType: "administrative.land_parcel",
    stylers: [
      {
        visibility: "off"
      }
    ]
  },
  {
    featureType: "administrative.neighborhood",
    stylers: [
      {
        visibility: "off"
      }
    ]
  }
]

.....

<MapView
...
customMapStyle={mapStyle}
...
/>
```

**Comment by YoniCosta** [comment]
how can i can i do the same for APPLE maps (react-native)?

> I share the map style
> 
> ```js
> mapStyle = [
>   {
>     elementType: "labels",
>     stylers: [
>       {
>         visibility: "off"
>       }
>     ]
>   },
>   {
>     featureType: "administrative.land_parcel",
>     stylers: [
>       {
>         visibility: "off"
>       }
>     ]
>   },
>   {
>     featureType: "administrative.neighborhood",
>     stylers: [
>       {
>         visibility: "off"
>       }
>     ]
>   }
> ]
> 
> .....
> 
> <MapView
> ...
> customMapStyle={mapStyle}
> ...
> />
> ```

**Comment by IKTANIM** [comment]
The above solution works just fine but if you need more customization just follow this [Create Map Style](https://mapstyle.withgoogle.com/) you can add more customization.
