### ISSUE TITLE
Markers with custom images - images are not rendered

### ISSUE THREAD

**Issue by bl4ze** [react-community/react-native-maps#1518]
Hello. There are many reported cases with rendering issues for markers with custom images. 
Some of them are older than a year:
[1](https://github.com/airbnb/react-native-maps/issues/924)*
[2](https://github.com/airbnb/react-native-maps/issues/100)
[3](https://github.com/airbnb/react-native-maps/issues/702)
[4](https://github.com/airbnb/react-native-maps/issues/334)

I have a similar issue. 
I've tried creating image components before rendering MapView.
Tried rendering images conditionally.
Tried setting image source dynamically onComponentDidMount.
Tried rendering <Text>Math.Random()</Text> inside the image tags. 

None of the above works.

There is one more similar issue. When setting style that depends on state inside markers , the style is not being updated. You have to update some property that is being displayed (like text) so the new style is applied.

I am wondering if this is going to be fixed or shall I continue to try different workarounds?

**Comment by foyarash** [comment]
On Android I had performance issue using custom marker. My solution was to create mdpi, ldpi, hdpi, etc. drawables, and update the components/MapMarker.js, to be able to receive the drawable name as image prop. The constraint doing this is that you must have the correct size for the drawables.

On iOS, custom images works perfectly

**Comment by bl4ze** [comment]
Thanks for the reply.

The issue was that I was using png icon with size like 350x350. 

I changed the icon dimensions and size and now it is rendered properly from the first time the app loads.

**Comment by hoboman313** [comment]
@foyarash I have now read through all the marker performance issues here and you're the only one to suggest that. :) Do you experience any dropped frames with say 20+ custom markers? Mind sharing some code if it's that performant?

**Comment by foyarash** [comment]
@hoboman313 Hello,

I haven't experienced any fps drop with 20+ custom markers on MapKit with iOS, but I had using Google Maps on iOS (Android working perfectly tho, no fps drop even with 200 markers and more).

My code looks like this:

```
<MapView.Marker
        key={idx}
        coordinate={myCoordinateObject}
        {
          ...Platform.select({
            android: {
              image: yourDrawableName,
            },
          })
        } >
        {Platform.OS === 'ios' && (
          // Your custom marker, equivalent to your drawable
        )}
      </MapView.Marker>
```

Hope that helps :)

**Comment by bl4ze** [comment]
Here's some code:
` <MapView 
            customMapStyle={mapStyle_lightDream}
            style={styles.map}
            initialRegion={this.props.mapInitialRegion}
          >
              {
                this.props.markers.items.map((mrk, i) => {
                  const isActive = this.props.markers.activeMarkerIndex === i;
                  return (
                    <Marker 
                      key={i}
                      customKey={i}
                      // change text to force rerender marker due to bug. see:
                      // https://github.com/airbnb/react-native-maps/issues/924, 
                      // https://github.com/airbnb/react-native-maps/issues/1552
                      // https://github.com/airbnb/react-native-maps/issues/1518
                      marker={{...mrk, text: mrk.text + Math.random()}}
                      isActive={isActive}
                      onPress={() => this.props.selectActivePOI(i)}
                    />
                  )
                })
              } 
          </MapView> `
Where marker is custom component:
```
<View style={styles.container}>
            <MapView.Marker
                      key = { this.props.customKey }
                      ref={(ref) => { this.markerRef = ref; }}
                      onPress = {this.props.onPress}
                      coordinate={this.props.marker.establishment.location}
                      title={this.props.marker.establishment.name}>
              {/* <View style = { markerStylez }>
                <Text style={styles.markerText}>{this.props.marker.text}</Text>
              </View> */}
              <View style={styles.imageContainer}>
                <Image 
                       onLoad={() => this.forceUpdate()}
                       onLayout={() => this.forceUpdate()}
                       source={markerImage}
                       style={this.props.isActive ? styles.markerSelectedImage : styles.markerImage}
                       ref={(ref) => { this.markerImageRef = ref; }}
                       >
                </Image>
                 <Text style={styles.markerText}>{this.props.marker.text}</Text> 
              </View>
            </MapView.Marker>
          </View>
```
@foyarash, is there anything that looks suspicious here? 
Can you reproduce the issue with this code?

**Comment by foyarash** [comment]
I guess this will correctly work with MapKit iOS, not perf issue

Not sure about google maps, depends of the number of markers I guess.

The only link about drawable I can provide you is https://developer.android.com/guide/topics/resources/drawable-resource.html .

**Comment by alvelig** [comment]
Merging to #1870
