### ISSUE TITLE
MapView.Circle failing to update center and radius on iOS

### ISSUE THREAD

**Issue by aylesm** [react-community/react-native-maps#1524]
Hi,

I'm trying to dynamically changes properties on a circle.  It looks like the AIRMapCircle requires a reference to the AIRMap object.  Which is doesn't have.  This prevents an update.

Is there a workaround or fix pending for this?

**Comment by johnnyqbui** [comment]
Set a key to your Circle component with a combination of the new coord. This worked for me. Issue for this was closed here: https://github.com/airbnb/react-native-maps/issues/283#issuecomment-227812817

**Comment by lfkwtz** [comment]
This looks like it was fixed in #2101

**Comment by rborn** [comment]
Closing as per https://github.com/react-community/react-native-maps/issues/1524#issuecomment-419176736
