### ISSUE TITLE
Unable to run RNMaps

### ISSUE THREAD

**Issue by nikitph** [react-community/react-native-maps#1529]
![simulator screen shot aug 5 2017 4 57 44 pm](https://user-images.githubusercontent.com/5007879/28999557-4c83c454-79ff-11e7-9704-b7eace8bd3c3.png)

it seems to be originating from MapView.js line 63 

here is my package.json . Now i understand only the latest verison of RN is supported but i m quiet sure this is not supposed to be happening. 

"firebase": "^3.9.0",
    "firebase-admin": "^4.2.1",
    "firebase-tools": "^3.6.1",
    "geofire": "^4.1.2",
    "moment": "^2.18.1",
    "prop-types": "^15.5.10",
    "rc-time-picker": "^2.4.1",
    "react": "16.0.0-alpha.6",
    "react-datepicker": "^0.46.0",
    "react-icons": "^2.2.5",
    "react-native": "^0.43.4",
    "react-native-camera-roll-picker": "^1.1.9",
    "react-native-datepicker": "^1.5.1",
    "react-native-fetch-blob": "^0.10.5",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-maps": "^0.15.3",
    "react-native-simple-radio-button": "^2.5.0-alpha.1",
    "react-native-snap-carousel": "2.1.4",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0",
    "rn-viewpager": "^1.2.3"

**Comment by eugenehp** [comment]
Try RN 0.45+

**Comment by eykjs** [comment]
I think your problem is the same, I had. Facebook moved the "prop-types" from ReactJS to React Native in on of the newer versions. Probably in RN version 0.43, because i tried it with version 0.42 and React 15.4.2 and [it worked](https://github.com/facebook/react-native/issues/15913).

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
