### ISSUE TITLE
[Android] Issue map not render correctly

### ISSUE THREAD

**Issue by jose920405** [react-community/react-native-maps#1535]
Hello,

I have a problem loading the map in android because it does not show me any information on the map. It is not the problem of the white map that many have gone through and of which there are quite a few issues here, but rather something a little different.

In `IOS` devices:

![captura de pantalla 2017-08-08 a la s 4 55 36 p m](https://user-images.githubusercontent.com/12536184/29096766-07a70f9e-7c5c-11e7-988c-055b6a226e61.png)
_______

In `Android` devices:

![screenshot_2017-08-08-16-56-37](https://user-images.githubusercontent.com/12536184/29096831-57942ed8-7c5c-11e7-96fe-e5489c3e3326.png)
_______

As you can see, the map is rendered and even shows markers correctly, but there are no street names or addresses or anything. The map is completely flat, as if it were some rendering problem.

**Comment by luugiathuy** [comment]
@jose920405 Did you set the `customMapStyle` prop for your MapView? More details about it at https://github.com/airbnb/react-native-maps#customizing-the-map-style. I guess your custom map style does not show street names or addresses. Can you try to remove the `customMapStyle` prop and see?

**Comment by jose920405** [comment]
@luugiathuy Thanks... That was my problem 👍

**Comment by luugiathuy** [comment]
@jose920405 I think because your app is using Apple Map for iOS. You can see the `provider` prop of the MapView here https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md
