### ISSUE TITLE
Map API slow.

### ISSUE THREAD

**Issue by ivangrga** [react-community/react-native-maps#1536]
All map events are extremely slow.
When I add onClick Event to marker it takes almost second (or sometimes even more), for map/marker to fire event.
I am using PROVIDER_GOOGLE, on iOS.
Versions of map, RN and React are the same as in package.json of official usage example.

**Comment by alvelig** [comment]
You are rendering too many markers or have problems with re-renders.

**Comment by alvelig** [comment]
see #369
