### ISSUE TITLE
Images in Custom Callouts not appearing on Android

### ISSUE THREAD

**Issue by bcgilliom** [react-community/react-native-maps#154]
I tested this on a nexus 5X emulator with API 23 and a Samsung S4 with 5.0.1. It works fine on iOS. I am essentially using the code from the example and added an Image with a local source (which shows up as expected outside of the map view).

![screen shot 2016-03-29 at 10 50 12 am](https://cloud.githubusercontent.com/assets/5893743/14104274/397bd5d8-f59c-11e5-8bf9-5fb3a7cb9c24.png)

**Comment by BigPun86** [comment]
+1

**Comment by socialbit-at** [comment]
+1

**Comment by mcliquid** [comment]
+1

**Comment by jrichardlai** [comment]
Does that still happens? What is the code you are using for the Marker?

**Comment by jrichardlai** [comment]
Nevermind still seems to be happening.

**Comment by jeveloper** [comment]
Happening here too

**Comment by mcliquid** [comment]
Any news yet?

**Comment by jeveloper** [comment]
Quick update: i noticed playing with style - height, width, somehow displays an image but trying to use full h/w does not work, just shows white background.

It would be great to have this fixed, willing to donate

**Comment by BigPun86** [comment]
+1

**Comment by matiascba** [comment]
+1

**Comment by jeveloper** [comment]
Hey i think i figured it out

`  <MapView.Callout tooltip={true}>`

**Comment by Squek** [comment]
I set  tooltip={true}
but Images still doesn't appear on Android device

**Comment by jeveloper** [comment]
Tinker with dimensions of the image, set to resizeMode contain
I have it working on android 5.1 and 6.0

**Comment by Dudyboy** [comment]
When I press on Marker it will display Callout without image. When I press on Marker two more times, it will display, but on the first press it never display.

**Comment by jeveloper** [comment]
@Dudyboy i agree, observing the same behaviour, emulator and device 
Can this be a problem of rendering image tag by RN , perhaps this isnt an issue of this map lib? This is a guess.


**Please post any workaround here for marker and callout.**
thank you

**Comment by Dudyboy** [comment]
I don't know, maybe you are right. I try to find solution there ... with getSize and prefetch methods or props onLoadEnd. I think that some preload image (images), when I press on Marker and before Callout is open will solve it, but I don't know. I try to find solution, but without success.

Here is code. Thank you for any help.

```javascript
constructor(props) {
	super(props);

	this.renderMapProducts = this.renderMapProducts.bind(this);
}

renderMapProducts() {
    
    return this.props.searchResult.search.map((product) => {

        const idKey = product.id;
        const srcImage = product.image;

        return(
            <MapView.Marker
                key={idKey}
                coordinate={
                    {
                        latitude: product.latitude,
                        longitude: product.longitude
                    }
                }
            >
                <Image source={require('../../images/marker.png')} style={{width: 40, height: 45}} />
                <MapView.Callout
                    tooltip={true}
                    onPress={() => this.onCalloutPress(idKey)}
                >
                    <CustomCallout
                        image={srcImage}
                    >
                    </CustomCallout>
                </MapView.Callout>
            </MapView.Marker>
        );
    });
}

render () {
	return (
		<View
			style={styles.container}
		>
			<MapView
				ref="map"
				style={styles.map}
				initialRegion={{
					latitude: this.props.position.latitude,
					longitude: this.props.position.longitude,
					latitudeDelta: 0.0922,
					longitudeDelta: LONGITUDE_DELTA
				}}
			>
				{this.renderMapProducts()}
			</MapView>
			<View
				style={styles.searchInput}
			>
				<SearchInput
					placeholderText="Search"
				/>
			</View>

		</View>
	);
}

const styles = StyleSheet.create({
	container: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'flex-start',
		alignItems: 'center'
	},
	map: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0
	},
	searchInput: {
		paddingTop: 10,
		paddingHorizontal: 15
	}
});
```

CustomCallout component is like in examples:

```javascript
constructor(props) {
   super(props);
}

render() {
    const ROOT_URL = '...';

    return(
        <View style={[styles.container]}>
            <View style={styles.bubble}>
                <Image resizeMode="contain" style={{ width: 70, height: 70 }} source={{ uri: `${ROOT_URL}${this.props.image}` }} />
            </View>
            <View style={styles.arrowBorder} />
            <View style={styles.arrow} />
        </View>
    );
}
```

Static images, like I use in source Image in Marker with require('../../images/marker.png') works fine. Static image will work good as well in Callout too. When I try to change code in CustomCallout for example:

```javascript
<Image resizeMode="contain" style={{ width: 70, height: 70 }} source={require('../../images/marker.png')} />
```

It will display on first press. With http address in source it will display on third press.

Dependencies, I simplify it:
```json
{
  "dependencies": {
    "react": "^15.0.2",
    "react-dom": "^15.1.0",
    "react-motion": "^0.4.4",
    "react-native": "^0.26.2",
    "react-native-maps": "^0.4.2",
  }
}
```

I tested on real device, Samsung J5, Android 5.1.1.

**Comment by stephenweaver** [comment]
Same issue

**Comment by Dudyboy** [comment]
Nobody find solution to this? ...

My workaround is render all images before map and its working. But there is big 'but'... for what price is working, I have to download all images and I am worried that in someone point is fall down.

```javascript
<View
    style={mapViewStyles.container}
>
    <View>
        {this.renderAllImages()}
    </View>
    <MapView
        ref="map"
        style={mapViewStyles.map}
        initialRegion={{
            latitude: this.props.position.latitude,
            longitude: this.props.position.longitude,
            latitudeDelta: 0.0922,
            longitudeDelta: LONGITUDE_DELTA
        }}
        loadingEnabled={true}
        toolbarEnabled={true}
        loadingIndicatorColor={WHITE_COLOR}
        loadingBackgroundColor={BLUE_COLOR}
    >
        {this.renderMapProducts()}
    </MapView>
</View>
```

```javascript
renderAllImages() {
    if (Platform.OS === 'ios') {
        return false;
    } else if (Platform.OS === 'android') {
        return this.props.searchResult.map(product => {
            let imageSrc = `${MAIN_URL}${product.image}`;
            Image.prefetch(imageSrc);
            return(
                <Image
                    key={product.id}
                    source={{uri: imageSrc}}
                    style={{ width: 96, height: 96, position: 'absolute', zIndex: -1 }}
                    resizeMode="cover"
                />
            );
        });
    }
}
```
In MapViewCallout then I render callout image.

```javascript
renderCalloutImage(imageSrc) {
        return(
            <View>
                <ResponsiveImage
                    initWidth="90"
                    initHeight="90"
                    source={{uri: imageSrc}}
                />
            </View>
        );
    }
```

In this point the image is downloaded, so it will display.

Any advices? Thanks.

**Comment by georgobermayr** [comment]
+1

**Comment by cgpomeroy** [comment]
+1

**Comment by ianaz** [comment]
+1

**Comment by pleopardi** [comment]
Same problem here on Android. Prefetching images doesn't work and images on callout only show on the third opening of the callout.

**Comment by yellowspaceboots** [comment]
I am experiencing the exact same issue. It takes 3 times to show the callout image. Loading all of the images that I want to use in the callouts before the map renders does not solve the issue. I have tried prefetching the images as the app loads as well as rendering all the images ahead of MapView in my map component. Has anyone found a work around for this?  I will keep experimenting and post if I find a solution.

**Comment by krishna-shilpakar** [comment]
+1

**Comment by damikdk** [comment]
+1

**Comment by Lowisoft** [comment]
+1

**Comment by damikdk** [comment]
According [this](https://github.com/airbnb/react-native-maps/issues/1280) answers, we should try to solve problems ourselves.

If you have any idea what to do or where to dig first, share it, please. I will try solve this on weekend

**Comment by MeganKurz** [comment]
+1

**Comment by cong196** [comment]
Same issue

**Comment by vuthanhtrung0504** [comment]
Does anyone get through this bug. I had find the solution for whole week and still cannot solve it

**Comment by vuthanhtrung0504** [comment]
I have found temporary solution. I used setInterval with 0 for showCallout when onPress the marker and clearInterval when the current calloutId change. I dont know is it the best solution but it works for me. Ex: setInterval(() => this[`marker + ${calloutId}`].showCallout(),0)

**Comment by vuthanhtrung0504** [comment]
I think i find the temporary solution by using setInterval to 0 when showCallout and clear the interval when the image show up. I dont know it is the best solution but it works for me now. You can use like this[calloutId] = setInterval(() => this[`marker + ${calloutId}`].showCallout(), 0)

**Comment by alvelig** [comment]
Merging to #1870

**Comment by DrJukka** [comment]
+1

**Comment by NYSamnang** [comment]
Same Issue but the problem has been solved after I added `resizeMode="cover"` to the `Image` props. I know that's weird, but it works 😀.

**Example**

```
<Image
  source={{ uri: this.state.profile }}
  style={{ width: 50, height: 50 }}
  resizeMode="cover"
/>
```

**Comment by Balasnest** [comment]
+1

**Comment by Prasadraaj** [comment]
I am also facing this issue. I have tried rendering image in 'text' component and in 'webview' also. Its not showing up image consistently. Some time working on tapping the callout. But my requirement is to auto render the image in call out on showing the screen.

**Comment by sasan-ebrahimi** [comment]
I tried this and it worked for me on Android. Just putting Image tag inside a Text tag

`<Text><Image .../></Text>`

**Comment by sriteja777** [comment]
It is still a problem, why this issue is closed?

**Comment by guoyiwang** [comment]
> I tried many things and finally I found a solution. Worked for me on Android. Just putting Image tag inside a Text tag
> 
> `<Text><Image .../></Text>`

It works for me. Unbelievable. Thanks!

**Comment by DorianNaaji** [comment]
> I think i find the temporary solution by using setInterval to 0 when showCallout and clear the interval when the image show up. I dont know it is the best solution but it works for me now. You can use like this[calloutId] = setInterval(() => this[`marker + ${calloutId}`].showCallout(), 0)

It works for me, even though I had to tweak the thing a little bit.
I had an OnPress function that I called within my Marker.onPress : 

onPress={(e) => simulatePress(e)}

Then, in my simulatePress function I did : 

```javascript
 const simulatePress = (e) =>
 {
         e.persist();
         let ref = markersRef;
         events[e.nativeEvent.id] = setInterval( () => ref[e.nativeEvent.id].showCallout(), 0);
         setTimeout( () =>
         {
            clearInterval(events[e.nativeEvent.id]);
         }, 800)
}
```

I'm doing the e.persist() cause the event can't be reused and that causes an error.

Then I made a timeOut in order to "wait" for the execution of the showCallout, so that the callout is redisplayed at least 3 times (btw i've seen many comments telling that after showing 2 to 3 times the callout, the image appears. the goal here is to do it programmatically).

const events = [];

events[] is just an array holding my events. each key is the marker id. (unique)

thanks for your suggestion.

btw this problem is here in the lib since many years now.

**Comment by OmegaNix** [comment]
> > I tried many things and finally I found a solution. Worked for me on Android. Just putting Image tag inside a Text tag
> > `<Text><Image .../></Text>`
> 
> It works for me. Unbelievable. Thanks!

I was about to kill everyone before I read this post.  Humanity thanks you.

**Comment by OmegaNix** [comment]
This issue should not be closed, there's no reason why Image components shouldn't render without all these workarounds.

**Comment by Navneetoo7** [comment]
just, try to add <Text><Image/></Text> it will work becasue it working for me give try

**Comment by Navneetoo7** [comment]
just add your image tag between text tag it will work because mine worked just try it

**Comment by abramsamir1** [comment]
I tried this code and it was working with me , I tried also using image inside text tags but it has some issues, tried using SVG and it has some issues too, Webview is working good with me until now 
      <View style={{ height: 100, width: 100}}>
                    <WebView
                      originWhitelist={['*']}
                      source={{ html: htmlImage }}
                    />
                  </View>

**Comment by brownieboy** [comment]
Still and issue for me on Android.

Putting the `<Image>` inside a `<Text>` did nothing for me.

**Comment by TalalNuman** [comment]
Putting the <Image> inside a <Text> solved the problem for me. 
 
Maybe we can only use <Text> inside a callout for Android.

**Comment by TalalNuman** [comment]
Putting the `<Image>` inside a `<Text>` solved the problem for me. 

Maybe we can only use `<Text>` inside a Callout on Android. But this issue should be resolved as putting the `<Image>` inside a `<Text>` doesn't make any sense.

**Comment by KristofaJosh** [comment]
@TalalNuman Idea worked for me but with a lot of tweaking, so I decided to try `Svg` instead. Works great.

**Comment by PaulLeymet** [comment]
Hi Guys,

As @KristofaJosh  suggested I tried with the Image component from react-native-svg and its working.

Here's an example if you are interested :

1. **Config :**

- BORDER_RADIUS : Radius of the image within the callout (you can remove a lot of code in unnecessary)
- IMAGE_SIZE : Width and height of the image (it as to be static).

2. **Code :**

          {/* This part is only if you need to set a BorderRadius to the image */}
          const path = `M${BORDER_RADIUS} 0 
            L${IMAGE_SIZE - BORDER_RADIUS} 0 
            Q${IMAGE_SIZE} 0 ${IMAGE_SIZE} ${BORDER_RADIUS} 
            L${IMAGE_SIZE} ${IMAGE_SIZE - BORDER_RADIUS} 
            Q${IMAGE_SIZE} ${IMAGE_SIZE} ${IMAGE_SIZE - BORDER_RADIUS} ${IMAGE_SIZE} 
            L${BORDER_RADIUS} ${IMAGE_SIZE} 
            Q0 ${IMAGE_SIZE} 0 ${IMAGE_SIZE - BORDER_RADIUS} 
            L0 ${BORDER_RADIUS} 
            Q0 0 ${BORDER_RADIUS} 0 
            Z`
    
     
          return (
            <View style={styles.callout}>
              <Svg width={IMAGE_SIZE} height={IMAGE_SIZE}>
                {/* This part is only if you need to set a BorderRadius to the image */}
                <Defs>
                  <ClipPath id="clipPath">
                    <Path d={path} />
                  </ClipPath>
                </Defs>
                {/* This is the image */}
                <Image
                  href={{ uri: uri }}
                  clipPath="url(#clipPath)" // Needed for borderRadius
                  preserveAspectRatio="xMidYMid slice" // Needed to set a 'cover' like image display
                  width={IMAGE_SIZE}
                  height={IMAGE_SIZE}
                />
              </Svg> 
            </View>
