### ISSUE TITLE
Keep marker centered and move map around it

### ISSUE THREAD

**Issue by alizahid** [react-community/react-native-maps#1542]
How do I keep the marker centered of the map, while dragging the map around the marker? Like how Uber does it, when a user is trying to choose a location. I tried updating the state in `onRegionChange`, but that's way too expensive, and slow. Any ideas?

**Comment by alizahid** [comment]
Another idea is to draw a fake marker overlay the map, which stays fixed in the center. And when the user presses save, get the latest location and save it.

Can I use a native `Marker` to do that instead of relying on a custom image?

**Comment by pellepersson** [comment]
@alizahid - we have solved this with the "fake marker" method you suggested in our application.

If you would solve it by having a real marker on the map that changes position to the center of the region that the map shows, there will be a lot more computing for the poor rendering mechanism to do. So if you want a smooth result, I really suggest going for the "faker marker".

If you use a custom marker, it should be fairly easy to recreate that marker with views for your "fake marker" in the overlay. I guess it might be a bit more tricky if you want the native markers from Apple MapKit and Google Maps.

**Comment by alizahid** [comment]
Yes, I went with a fake marker with a vertical margin to make sure the pointy end is on the correct position on the map.

It would've been nice to use the native marker image, but just using my own PNG for now.

**Comment by juergengunz** [comment]
What if need the "fake"-marker to be not in the center of the map? like a little bit closer to the top, because i have UI elements at the bottom. is this possible somehow?

**Comment by alizahid** [comment]
@juergengunz You can use `margin` to offset your _fake_ marker. But keep in mind, the map will always return the center coordinates.

**Comment by juergengunz** [comment]
@alizahid  yep thats my problem.. I have an uber style marker that shows the location for that point. if I would use margin the coordinates would not match the position of the fake marker...

**Comment by aylesm** [comment]
Hi @alizahid I'm running into the same problem.  I want to provide a crosshairs that always remains in the center of the map.  Plus add a circle that changes size based on a slider so that a user can easily select a location and set a radius to create a geofence.  I've tried using a marker and updating the coord and the performance isn't great.  You see lag in the marker updating when moving around the map.  So I'm thinking of a fake marker is the best solution.  How did you do that?  I've added a child item to my map which is a custom image.  The only problem with that is this can interfere with the panning around of the map.

**Comment by alizahid** [comment]
@aylesm For the panning issue, just set `pointer-events` to `none` in the style for the _fake_ marker. That'll make the marker unclickable and allow you to pan the map around with ease.

**Comment by kytwb** [comment]
@juergengunz I'm facing the same scenario, any luck?

**Comment by juergengunz** [comment]
@kytwb no unfortunately, I placed the marker in the center of the map for now

**Comment by alvelig** [comment]
You have to put it in the center and get coordinates onRegionChangeComplete.

**Comment by jassonha21** [comment]
@alvelig does on region change complete always return the centre of the map? 

how can i add the `fake` marker? 

just add some image and put it on the centre of the map?

**Comment by alvelig** [comment]
@jassonha21 region change complete returns coordinates of the region. I don't see any situations where it may not be the same as the center of the map with this current region.

If you need a marker, you put a marker, as it is bound to coordinates. If you need something in the center of your map, you put in the center of the screen

**Comment by hamidhadi** [comment]
Fake marker component is working on iOS but not on Android. Anybody know how can I fix it?

**Comment by alizahid** [comment]
I wrote a guide on how to do this. Check it out http://alizahid.net/post/172622558271/keep-marker-in-center-and-move-map-around-it

**Comment by hamidhadi** [comment]
@alizahid Thank you man. It works 👍

**Comment by jassonha21** [comment]
@alizahid where do you trigger to set the new coordinate? is it from onRegionChange? 

Where did you apply the event?

**Comment by alizahid** [comment]
@jassonha21 You should do it on `onRegionChangeComplete` for least updates and best performance.

**Comment by howg0924** [comment]
I also implemented this fake marker method but encountered the following problem:

[Region coordinates not centered on Google Maps] #2087 

which means the coordinate returned from onRegionChangeComplete is not at the center of the map. The error amount is depend on the map zoom level and the latitude. When zoom level is small (large latitudeDelta/longitudeDelta) or latitude is large, the error amount becomes large.

Did you guys notice this? How did you solve this problem?

**Comment by AhmedAliIbrahim** [comment]
How can i get Market lat,lng if i did that ?!

**Comment by rajaramanZencode** [comment]
> I wrote a guide on how to do this. Check it out http://alizahid.net/post/172622558271/keep-marker-in-center-and-move-map-around-it

can you show full source code

**Comment by Ahmed-Imam** [comment]
@AhmedAliIbrahim any updates on how to get the lat and lng ?

**Comment by seppemarotta** [comment]
Thank you @alizahid

**Comment by rAnAaRsl** [comment]
need help related to the circle with dynamic radius increasing through slider i want to have a still circle above the map which enables the map to move around but circle remains on its place with radius size increasing and decreasing through slider

**Comment by MorgadoKnivet** [comment]
Hey guys. I think this, but exist a problem. In uber/99 when you make zoom, It is directioned to point in center of screen. The normal, is to direction for point than you is selectioning. How resolve this fix?

**Comment by prav02** [comment]
> @rajaramanZencode Here you go https://github.com/alizahid/location-picker-demo

How to give the title to the fake marker?

**Comment by prav02** [comment]
@alizahid  how to give the title to the fake marker??

**Comment by alizahid** [comment]
You could create a `View` and add the fake `Image` and label `Text` to it and then position it carefully.

**Comment by prav02** [comment]
Yes I did exactly like that, but it gives me just some text on Image, But actually my requirement is exact styling as the title prop of the marker. From where I can get that. I have tried in the inbuild file of the react-native-maps but no luck?
Did anyone find it anywhere, I may have been missed?
Thank You

**Comment by alizahid** [comment]
Can you post a screenshot of what you want vs what you get?

**Comment by prav02** [comment]
@alizahid 
![image](https://user-images.githubusercontent.com/32065999/78976674-48e98200-7b34-11ea-8d6f-c5cf431238b4.png)
![image](https://user-images.githubusercontent.com/32065999/78976739-6dddf500-7b34-11ea-9db2-2b64da2130dd.png)

**Comment by prav02** [comment]
> @alizahid
> ![image](https://user-images.githubusercontent.com/32065999/78976674-48e98200-7b34-11ea-8d6f-c5cf431238b4.png)
> ![image](https://user-images.githubusercontent.com/32065999/78976739-6dddf500-7b34-11ea-9db2-2b64da2130dd.png)

First image is what I get and second one is what I Want?
Thank you

**Comment by nir099** [comment]
> I wrote a guide on how to do this. Check it out https://designplox.com/blog/keep-marker-in-center-and-move-map-around-it

Link is broken :/ @alizahid

**Comment by alizahid** [comment]
@nir099 Sorry. Updated the link: https://medium.com/@alizahid0/keep-marker-in-center-and-move-map-around-it-97f2320066b2

**Comment by alejandro4k** [comment]
how i can get the info window ussing a "Fake marker"?

**Comment by SaadBazaz** [comment]
The fake marker hack is interesting, but it'd be great if the native icons could be used. Because the iOS version and Android version of the marker is different (Google Maps vs Apple Maps)

**Comment by berkayakks** [comment]
i am still facing this problem. Has anyone found a new solution? This is very important for me

**Comment by nppull** [comment]
Is it possible to get the coordinates when I drag and drop the fake marker to another position?

**Comment by lsironic** [comment]
> 

The idea behind the fake marker is to have a fixed marked, and move the map below marker (see Facebook Marketplace map).

If you want to drag and drop map pin, use the react-native-maps Marker component instead of fake marker.

**Comment by Kuldeepkumhar-fs** [comment]
Not able to get any solution on it...can anyone help me with clarity plzz....

**Comment by Arjun0o** [comment]
Has anyone addressed the "Marker moves when we zoom in or zoom out" issue that arises after keeping the marker fixed?

**Comment by wilkinsonj** [comment]
It's very easy to do this:

`  const [region, setRegion] = useState<Region>(null)

  return (
    <>
      <MapView
        ref={mapRef}
        onRegionChange={setRegion}
      >
        <Marker 
          coordinate={{ latitude: region ? region.latitude : 0, longitude: region ? region.longitude : 0 }}
        />
      </MapView>
    </>
  )`

**Comment by Matt658041** [comment]
This is super important for Android users! I develop for both IOS and Android and the fake marker technique is great and works perfectly out of the box from @alizahid. But if you want this to work on Android you have to put the View with the Image outside of the Mapview like this  <View style={styles.viewSurroundingMapView}>
                    {location && (
                      <MapView
                        provider={undefined}
                        style={styles.mapView}
                        initialRegion={location}
                        onRegionChangeComplete={onLocationChange}
                      ></MapView>
                    )}
                    <View style={styles.markerContainer}>
                      <Image
                        source={schoolMarker}
                        style={styles.markerImageStyle}
                      />
                    </View>
                  </View>

**Comment by lnqminh3003** [comment]
![image](https://github.com/react-native-maps/react-native-maps/assets/101281380/324ada0a-671e-47fa-9f3f-243a94a5c0fb)
thank you for your advice

**Comment by Djotchuang** [comment]
> I wrote a guide on how to do this. Check it out https://alizahid.dev/blog/keep-marker-in-center-and-move-map-around-it

This helped me a lot!!! Thank you so very much!
