### ISSUE TITLE
blank map when use customMapStyle on iOS

### ISSUE THREAD

**Issue by michelson** [react-community/react-native-maps#1545]
I've the same issue as #1308, I've configured the pods correctly and I've set the api key in dev console, I've the key restricted to this identifier:  
![image](https://user-images.githubusercontent.com/11976/29204861-6368536e-7e47-11e7-8602-6d86b2a9cd3d.png)
as the app is not on app store, I've tried the api key without restriction on the first place, but the results was the same

the map looks like this
![image](https://user-images.githubusercontent.com/11976/29204835-37121854-7e47-11e7-88dc-4873218b57f6.png)

my deps are:
```
    "native-base": "2.1.0-rc.2",
    "react": "^15.4.2",
    "react-native": "^0.41.0",
    "react-native-maps": "^0.15.3",
```

what would be the problem ? 
best

**Comment by foyarash** [comment]
Did you provide your api key in your AppDelegate.m as described in the installation instructions?

**Comment by michelson** [comment]
Hi @foyarash , yes I did, 

it's something like this:

![image](https://user-images.githubusercontent.com/11976/29220088-092ea146-7e88-11e7-8ffe-f6d3b07928d8.png)

**Comment by ayberkanilatsiz** [comment]
+1 I have the same issue but I can render one time, other renders are failing.

**Comment by KalebPortillo** [comment]
+1

**Comment by alvelig** [comment]
Api key issue. Remove restriction and check your key.
