### ISSUE TITLE
Solved: React Native Maps - GPS Issue

### ISSUE THREAD

**Issue by arrayewhy** [react-community/react-native-maps#1551]
I want React Native Maps (RN0.46.1, RNMaps 0.16.0) to show my current location but am getting this error:
**Attempt to invoke interface method 'boolean abi19_0_0.com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference**

Here's my code:
```
import React from 'react';
import { StyleSheet, View, Text } from 'react-native';
import MapView from 'react-native-maps';

export default class MapScreen extends React.Component {

	state = {
		mapRegion: null,
		lastLat: null,
		lastLong: null,
	}

	componentDidMount() {
		this.watchID = navigator.geolocation.watchPosition((position) => {
		// Create the object to update this.state.mapRegion through the onRegionChange function
			let region = {
				latitude:       position.coords.latitude,
				longitude:      position.coords.longitude,
				latitudeDelta:  0.00922*1.5,
				longitudeDelta: 0.00421*1.5
			}
			this.onRegionChange(region, region.latitude, region.longitude);
		});
	}

	onRegionChange(region, lastLat, lastLong) {
		this.setState({
			mapRegion: region,
			// If there are no new values set the current ones
			lastLat: lastLat || this.state.lastLat,
			lastLong: lastLong || this.state.lastLong
		});
	}

	componentWillUnmount() {
		navigator.geolocation.clearWatch(this.watchID);
	}

	render () {
		return (
			<MapView
				style = { styles.mapContainer }
				region = { this.state.mapRegion }
			/>
		);
	}
}

const styles = StyleSheet.create ({
	mapContainer: {
		...StyleSheet.absoluteFillObject,
	}
})
```

**Comment by arrayewhy** [comment]
Managed to get this working in a new `react-native init` project (RN 0.47.1, RNMaps 0.16.0) with the following added to **./android/app/src/main/AndroidManifest.xml**:
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`
`<meta-data
android:name="com.google.android.geo.API_KEY"
android:value="WHATEVERYOURAPIKEYIS" />`

**Comment by Alexb32** [comment]
I'm having the same issue, and creating a new project didn't work. Any other ideas of what it could be?

**Comment by derren7532123** [comment]
@arrayewhy can you provided the soluction on it ? i also got this issue with
// Attempt to invoke interface method 'boolean abi27_0_0.com 'facebook.react.bridge.readablemap.getstring(java.lang.string) on a null object reference //
This is my file::
import React from 'react';
import { StyleSheet, Text, View, Dimensions } from 'react-native';
import MapView from 'react-native-maps';

const {width, height} = Dimensions.get('window')

const SCREEN_HEIGHT = height
const SCREEN_WIDTH = width
const ASPECT_RATIO = width / height
const LATTITUDE_DELTA =0.0922
const LONGTITUDE_DELTA =LATTITUDE_DELTA * ASPECT_RATIO

export default class map extends React.Component {
constructor(props) {
super(props)

  this.state = {
    initialPosition:{
    latitude: 0,
    longitude: 0,
    latitudeDelta: 0,
    longitudeDelta: 0
  },
  markerPosition: {
        latitude: 0,
        longitude: 0
      }
}
}
watchID: ?number = null
componentDidMount() {
navigator.geolocation.getCurrentPosition((position) => {
var lat =parseFloat(position.coords.latitude)
var long =parseFloat(position.coords.longitude)

   var initialRegion ={
       latitude: lat,
       longitude: long,
       latitudeDelta:LATTITUDE_DELTA,
       longitudeDelta: LONGTITUDE_DELTA
   }
   this.setState({initialPosition: initialRegion})
   this.setState({markerPosition: initialRegion})
 },
 (error) => alert(JSON.stringify(error)),
 {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000})

 this.watchIDd = navigator.geolocation.watchPosition((position) => {
   var lat = parseFloat(position.coords.latitude)
   var long =parseFloat(position.coords.longitude)

   var lastRegion ={
     latitude:lat,
     longitude:long,
     longitudeDelta: LONGTITUDE_DELTA,
     latitudeDelta:LATTITUDE_DELTA

   }
   this.setState({initialPosition : lastRegion})
   this.setState({markerPosition : lastRegion})
 })
}
componentWillUnmount(){
navigator.geolocation.clearWatch(this.watchID)
}
render() {
return (
        <MapView
            style={styles.map}
            region={this.state.initialPosition}>

                <MapView.Marker
                    coordinate={this.state.markerPosition}>


                        <View style={styles.radius}>
                            <View style={styles.marker}/>

                          </View>

                  </MapView.Marker>
        </MapView>

  </View>
);
}
}

**Comment by gbmahili** [comment]
This issue is only happening when using `create-react-native-app`. If you use `react-native init` and add what @arrayewhy suggested, then it works. Worked for me!

**Comment by derren7532123** [comment]
@gbmahili can help me changing my coding part ? coz im nit really understand it
