### ISSUE TITLE
Markers with custom images  not rendered on Android 7.1

### ISSUE THREAD

**Issue by sandropoluan** [react-community/react-native-maps#1552]
Not rendered on Android 7.1

Android 4.1
![4 1 1](https://user-images.githubusercontent.com/11922251/29246401-54a8407e-802b-11e7-9d90-a86c561a235e.PNG)

Android 4.3
![4 3](https://user-images.githubusercontent.com/11922251/29246404-6bf914ce-802b-11e7-8284-6adef12c9760.PNG)

Android 5,1
![5 1](https://user-images.githubusercontent.com/11922251/29246408-7819c546-802b-11e7-8a07-005d36b86717.PNG)

**Android 7.1**
![7 1](https://user-images.githubusercontent.com/11922251/29246411-828b68d6-802b-11e7-8b57-51e954697f5f.PNG)

**Comment by KarlosQ** [comment]
I have the same problem. The images are hidden in Android versions >= 7.0.

My code 
```
                   <MapView.Marker coordinate={{ latitude, longitude }} >
                        <View>
                           <Image style={styles.imageMarker} source={require('../../img/marcador_120px.png')} />
                        </View>
                  </MapView.Marker>
```

**Comment by grigored** [comment]
Have you tried the hacks from the issues referenced [here](https://github.com/airbnb/react-native-maps/issues/1518)  ?
In my case I had to do both: 
a) display the image using width=0, height=0 before the mapview is renderd. Otherwise images would be transparent on first load (I haven't seen this issue reported before)
b) Add a `<Text style={{width:0,height:0}}>{Math.random()}</Text>` in the image component, and forceUpdate the image on load. This way images are i) loaded on first pass, and ii) if i resize the image, it still looks good 

Right now, the render for my map component looks like this. 
```
render() {
    return (
      <View>

        <Image 
          style={{width:0,height:0}}
          source={{uri: imgSrc}}
        />

        <MapView
          style={styles.container}
          region={this.state.region}
          onRegionChangeComplete={region => {this.setState({region})}}
          showsUserLocation={true}
          // on Android the map is automatically recentered when you press on a marker
          // moveOnMarkerPress={false} disables this behaviour
          moveOnMarkerPress={false}
          ref={ref => { this.mapRef = ref; }}
        >
          {this.state.mapMarkers.map(marker => 
            <MapView.Marker
              key={marker.key}
              coordinate={{
                latitude: marker.latitude,
                longitude: marker.longitude,
              }}
            >
              <Image
                // we need the forceUpdate and the random text due to this
                // https://github.com/airbnb/react-native-maps/issues/924#issuecomment-280334935
                onLoad={() => this.forceUpdate()}
                onLayout={() => this.forceUpdate()}
                source={{uri: imgSrc}}
                style={styles.markerImg}
              >
                  <Text style={{width:0,height:0}}>{Math.random()}</Text>
              </Image>
            </MapView.Marker>
          )}

        </MapView>
      </View>
    );
  }
```

**Comment by jonathanmauer** [comment]
Hi @grigored i had the same issue, when i put `<Text style={{width:0,height:0}}>{Math.random()}</Text>` inside the markers it works fine, but it seems they lost the `borderRadius` property.

My marker code look like this:

`<MapView.Marker>
        <ImageBackground
          style={{ height: 50, width: 44 }} source={marker}
          onLoad={() => this.forceUpdate()}
          onLayout={() => this.forceUpdate()}
        >
          <Image
            style={{ width: 32.5, height: 32.5, marginLeft: 6.5, marginTop: 6.3, borderRadius: 16.25 }}
            source={{ uri: evento.venue.profilePicture }}
            onLoad={() => this.forceUpdate()}
            onLayout={() => this.forceUpdate()}
          >
            <Text style={{width:0,height:0}}>{Math.random()}</Text>
          </Image>
        </ImageBackground>
      </MapView.Marker>`

How can i work around this problem?

**Comment by grigored** [comment]
Not sure, for me using <Image> inside <Marker/> was a pain, so I'm using the image prop for the marker. Works much better for simple use cases, but won't allow any borders though.

**Comment by sami718** [comment]
```
<MapView
           provider={Platform.OS === 'ios' ? PROVIDER_DEFAULT :  PROVIDER_GOOGLE }
            style={{
              left: 0,
              right: 0,
              top: 0,
              bottom: 0,
              position: 'absolute'
            }}
          region={{
            latitude:18.569184,
            longitude: 73.765760,
            latitudeDelta: 0.00942,
            longitudeDelta: 0.0843
          }}
        >
          <MapView.Marker
            coordinate={{
              latitude: 18.568806,
              longitude: 73.765210
            }}
            title='ETHEL and Friends'
            centerOffset={{x:18.568806 , y:73.765210}}>
              <Image
              onLoad={() => this.forceUpdate()}
               onLayout={() => this.forceUpdate()}
                style={{
                  width: 25,
                  height: 25,
                  borderWidth:2,
                  borderRadius:25/2,
                  overflow:'hidden',
                  backgroundColor:'blue',
                }}
                source={{uri:"http://pokeapi.co/media/sprites/pokemon/1.png"}}
                ><Text style={{width:0,height:0}}>{Math.random()}</Text></Image>
            </MapView.Marker>
        </MapView>
```
marker is not visible on any device using `<Text style={{width:0,height:0}}>{Math.random()}</Text>` also it is not visible.Please give any idea

>

**Comment by klaszlo8207** [comment]
Marker image can not visible on the emulator to. Please help us

**Comment by tusharkhatiwada** [comment]
Hi @grigored , I tried your hack but is getting a different error.

**`Error: The <Image> component cannot contain children. If you want to render content on top of the image, consider using absolute positioning.`**

**Comment by grigored** [comment]
Not sure what the problem is. I couldn't make the image declaration as a child work, so I ended up using `<MapView.Marker image={getImageUrl(icon)} />`

**Comment by efkan** [comment]
@tusharkhatiwada problem regarding your react-native version. Try ImageBackground component instead of Image.

http://facebook.github.io/react-native/releases/0.49/docs/images.html#background-image-via-nesting

**Comment by alvelig** [comment]
Merging to #1870

**Comment by hugoh1995** [comment]
Having the same issue on different version of Android including 4.2, 7.0, 8.0

**Comment by vuphuctho** [comment]
Facing same issue in Android 8.0.1. End up using solution mentioned in https://github.com/react-community/react-native-maps/issues/1552#issuecomment-347527865, but really hope someone to figure out why it happens.

**Comment by WilliamAnputra** [comment]
@vuphuctho  which one ?

**Comment by vuphuctho** [comment]
> **grigored** commented on 28 Nov 2017
> Not sure what the problem is. I couldn't make the image declaration as a child work, so I ended up using <MapView.Marker image={getImageUrl(icon)} />

I used this, but have to create a complete new set of images for production build since image sizes in production build end up bigger than in debug mode.

**Comment by dopey2** [comment]
Having the same issue on Android 6.0 too

**Comment by ccoeder** [comment]
Android 8.0 has same issue.

**Comment by LightKnight3r** [comment]
using image props of marker works for me

**Comment by lunvjp** [comment]
@LightKnight3r I have the same problem with this thing now. Can you make it more clear, mate?
it will be good if you give us some source code about the thing you did well with it. 
Thanks a lot.

**Comment by krishanjangir** [comment]
@LightKnight3r  Could you please share the code, i have tried all ways but failed.
It's not working in android.

**Comment by LightKnight3r** [comment]
<MapView.Marker
              title= {''}
              image={} 
              coordinate={{
                latitude: ,
                longitude: 
              }}
              anchor={{x:,y:}}
              >
</MapView.Marker>
i tried local image, and it worked
