### ISSUE TITLE
onRegionChangeComplete fires multiple times while region decelerating (iOS)

### ISSUE THREAD

**Issue by EricPKerr** [react-community/react-native-maps#1557]
The `onRegionChangeComplete` event will fire multiple times if you drag the map and throw it to a new region while the native map region is decelerating to its new region.  The complete change event will fire at least twice, but up to a 3 or 4 times.

This is problematic if you call a Redux action to update the region when `onRegionChangeComplete` fires, which then updates the props (like `this.props.region`) that get passed back to the component, causing the component to re-render.

It's possible to "debounce" this event call, but that doesn't work well when you're passing in
`<MapView region={this.props.region} ...>` and the props region is expected to be up-to-date and synced.

```
Versions:
react-native: 0.47.1
react-native-maps: 0.16.1
```

**Comment by EricPKerr** [comment]
Dug into this a bit, here's some more notes. This will require some native changes:

http://www.b2cloud.com.au/tutorial/mkmapview-determining-whether-region-change-is-from-user-interaction/

> when the panning gesture ends the map’s region continues to decelerate.

**Comment by alvelig** [comment]
1. Don't manage region in state.
2. Watch for this enhancement #1620

**Comment by outaTiME** [comment]
Hi @EricPKerr, in need to intercept the user interaction to display "center" button like google maps on navigation, do you achieve that ?

Thanks !

**Comment by EricPKerr** [comment]
We did with mapbox - left this library awhile ago.

**Comment by j1mie** [comment]
@alvelig I don't manage region in state but I am seeing this issue on iOS. I do fetch data when `onRegionChangeComplete` event fires, and because it fires multiple times it's causing strange behaviour.

**Comment by riturajratan** [comment]
set   `followsUserLocation={false}` 
and on  ```onRegionChangeComplete={data => getAddress(data)}```
```
 const [latlong, setLatlong] = useState({
    latitude: 26.9124,  // set default Lat
    longitude: 75.7873, // set default Long
  });
 const getAddress = regionData => {
    if (
      regionData &&
      regionData.latitude !== latlong.latitude &&
      regionData.longitude !== latlong.longitude
    ) {
        ....
        your work 
      setLatlong(regionData);
 }
```
