### ISSUE TITLE
Map localization

### ISSUE THREAD

**Issue by AetherQuinque** [react-community/react-native-maps#1570]
I use this lib in Russia. On android and iOS device I got:
<img width="234" alt="2017-08-18 14 56 52" src="https://user-images.githubusercontent.com/20066332/29449792-5a383e96-8426-11e7-9f02-7e3c156f8c34.png">
Language of system - Russian. Can I fix that and take only Russian language for map?

**Comment by fahadbilal** [comment]
how do you upvote here! looking for same functionality...still searching right now.

**Comment by alvelig** [comment]
That's the limitation of GoogleMaps SDK. You can not :( 
@AetherQuinque If you know the way to make it in Android, tell me. But as far as I can see, there's no way to change it. Also we need contributors, please comment: #1807
