### ISSUE TITLE
animateToRegion didn't work in  v0.16.2

### ISSUE THREAD

**Issue by pigflymoon** [react-community/react-native-maps#1573]
animateToRegion didn't work in  v0.16.2.
When
onPress the marker, map animate toRegion:
  this.refs.MapView.animateToRegion(
            {
                latitude: coord.latitude,
                longitude: coord.longitude,
                latitudeDelta: 1.5,
                longitudeDelta: 1.2
            },
            1500);
first, it will animate to the region then it will animate back to original.

when I use version 0.15.2, it works.

**Comment by IjzerenHein** [comment]
I've had this problem as well. My workaround was to set the `initialRegion` prop to `undefined` after `onRegionChangeComplete` had been called:

```js
class MyMapView extends Component {
	constructor(props) {
		super(props);
		this.state = {
			regionChangeCompleted: false
		};
	}

	render() {
		const { regionChangeCompleted } = this.state;
		const region = ...;

		return (
			<MapView
				initialRegion={regionChangeCompleted ? undefined : region}
				onRegionChangeComplete={this.onRegionChangeComplete}>
			</MapView>
		);
	}

	onRegionChangeComplete = () => {
		if (!this.state.regionChangeCompleted) {
			this.setState({ regionChangeCompleted: true });
		}
	};
}
```

**Comment by alvelig** [comment]
It works in 0.18.3

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
