### ISSUE TITLE
After installing react-native-maps, RN does not recognize my directory as a RN project directory.

### ISSUE THREAD

**Issue by akashbdj** [react-community/react-native-maps#1574]
I'm creating a new project to use React Native Maps. After installing the module, RN doesn't recognize my project as a react native project.

Here's a set of commands I ran.
<img width="1241" alt="screen shot 2017-08-20 at 10 34 43 am" src="https://user-images.githubusercontent.com/7085282/29492286-866788d6-8594-11e7-8d15-f54368cb62b0.png">

I don't understand what happend.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
