### ISSUE TITLE
MapMarker

### ISSUE THREAD

**Issue by Clcll** [react-community/react-native-maps#1578]
Hi! how can I increase MapMarket hitSlop ?
Thx

**Comment by stajics** [comment]
@Clcll have you found a way to do it?

**Comment by stajics** [comment]
Nvm, Rendering a Marker with a custom view works good for this.

**Comment by otaviogaiao** [comment]
> Nvm, Rendering a Marker with a custom view works good for this.

How did you do it @stajics ? Can you post a sample of code? I've been trying to implement a CustomMarkerView with no success. The docs says very little about it.

**Comment by chrise86** [comment]
@otaviogaiao @stajics how did you achieve this?
