### ISSUE TITLE
onMapReady not called

### ISSUE THREAD

**Issue by kdong007** [react-community/react-native-maps#1580]
```
<MapView
                    style={styles.map}
                    initialRegion={{...}}
                    onMapReady = {this._mapReady.bind(this)}
                    onRegionChangeComplete={this._regionChanged.bind(this)}
                    showsUserLocation
                    //followsUserLocation
                    showsCompass
                    showsScale>

 _mapReady(){
        console.log("map ready");
    }
```

nothing happens

**Comment by dsc-cloyd** [comment]
try this.

onMapReady = { () => this._mapReady() }

mapReady = () => {
 console.log("map ready");
}

**Comment by kdong007** [comment]
@dsc-cloyd not working...

**Comment by cloyd** [comment]
Try adding reference to mapview?

<MapView
          ref={ref => { this.map = ref; }}

**Comment by ttlpta** [comment]
Have solution for this yet?

**Comment by kdong007** [comment]
i made a bare minimal test, 

`onMapReady = { () => console.log("xxxx") }`

not working....

**Comment by ttlpta** [comment]
I have updated the lastest version, It can fix this

**Comment by kytwb** [comment]
I somehow was subscribed to this thread. I confirm it's now working; might need to specify that `onMapReady` is called everytime new tiles of the map are loaded it seems.

**Comment by kdong007** [comment]
it worked since a update. It was not implemented before.

**Comment by resson-ntranquilla** [comment]
It does not work on v0.17, although it was marked as fixed on v0.16. I've run @kdong007 's simple test`onMapReady = { () => console.log("xxxx") }` and it confirms it is still not firing. I am on iOS.

**Comment by peterlau** [comment]
I find that mapReady is not consistently called on iOS when one navigates in and out of a page (I use `react-native-navigation`, but `react-navigation` has similar issues)

This is my current workaround
`
              onMapReady={Platform.OS === 'android' ? this.mapReadyResolve : null}
              onLayout={Platform.OS === 'ios' ? this.mapReadyResolve: null}
`
where `this.mapReadyResolve` resolves a promise in order to debounce onLayout, as it sometimes fire multiples times.

Note that I cannot use onLayout on both platforms either, as onLayout fires too soon on Android causing my panning command to be ignored.

**Comment by alvelig** [comment]
Does this example have the same issue? https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by carsonwah** [comment]
Same issue here. This is due to a flawed checking variable `didCallOnMapReady` introduced in `v0.18.x`.

This pull request https://github.com/react-community/react-native-maps/pull/1853 seems solving this issue. But it has not been included in any version yet. If you are not using services like `expo`, you can change the package version to master branch to try it out.

**Comment by rborn** [comment]
@carsonwah could you try to use the git version? The npm one is a little delayed (We're working on this issue now, it's an organisational issue)

**Comment by carsonwah** [comment]
@rborn My project is based on expo, which bundles `react-native-maps` into `expo` package. So I cannot change the version of this library. It is using 0.19.0 in its latest version v25.0.0. I may start an empty react native project to test it out later.

**Comment by darkmantle** [comment]
Any news on this? Getting the problem myself. Latest RN maps, with RN 0.55.4

**Comment by sallarahmed** [comment]
images of markers are not visable when i when i pass trackviewchanges props to false

**Comment by jafar-jabr** [comment]
moving on onMapReady out of the mapView solved the problem for me
const mapResolver = () => {
       console.log("xxxx");
}
........
..........
onMapReady = {mapResolver }

**Comment by burakkbilginn** [comment]
This problem still persists. No solution on IOS

**Comment by jackimatin** [comment]
This problem still persists, on IOS....

**Comment by Willham12** [comment]
On IOS Simulator do this:
````
- "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = i386;
+ "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64 i386";
```
