### ISSUE TITLE
Using Firebase to Generate Map Markers

### ISSUE THREAD

**Issue by TAM604** [react-community/react-native-maps#1581]
Hello everyone,

My apologies, but I am still fairly new to React Native and my terminology and vocabulary is still rather limited. I am currently trying to generate map markers by fetching data from Firebase. As of now, I am able to retrieve the information with the coordinates in the variable `finished`; but I am having trouble updating the array of `listingData`.

Also, I am not too sure about the second part of my code, which is suppose to hypothetically call upon the coordinates in `listingData` and then place the markers on the map.

If anyone has any suggestions that would be greatly appreciated.

Thank you very much,

Tam

```
export default class GetMarkers extends Component {  
    constructor(props) {
        super(props);
        this.state = {
            listingData: []
        }
    }
    
    componentWillMount(){
        let q = firebase.database().ref('profiles');
        q.on('value', (snap) => {
            var finished = []
            snap.forEach((data) => {
            let result = data.val();
            result["key"] = data.key;
            finished.push(result);
            })
            this.setState({
            listingData: finished
            })
        })
    }

    render() {
        return(
            <MapView>
                {this.state.listingData.map(x => (
                  <MapView.Marker
                    title={x.fName}
                    key={x.key}
                    description={'Test'}
                    coordinate={{
                      latitude: x.lat,
                      longitude: x.lon
                    }} />
              ))
            }
            </MapView>
        )
    }
}
```

**Comment by krishbhattacharyya** [comment]
Hi you can do like this, may be u can get better option from another member:

Step: 1

your view like this-
```

<MapView
	          provider={this.provider}
	          style={styles.map}
	          initialRegion={this.region}
	          onPress={this.onPress}
	          loadingEnabled
	          onRegionChange={this.onRegionChange}
	          ref={ref => { this.map = ref; }}
	          zoomEnabled={true}
	        >	
		{this.state.dynamicAddress.map(marker => (
	            <MapView.Marker
	              key={marker.key}
	              coordinate={marker.address}
	              image={flagImg}
	              identifier={ "Marker"+ marker.key}
	              onPress={() => this.getMyLocation(marker.address.latitude, marker.address.longitude)}
	            />
	        ))}
</MapView>
```


Step: 2

var dynamicAddress is an array use this in loop. For generate & set the markers position:

```
dynamicAddress.push({
		        	        'key' : i,
		      	            'address' : { 
						      	latitude: responseData.results[0].geometry.location.lat,
					        	longitude: responseData.results[0].geometry.location.lng,
		      				}
			  		});

self.setState({dynamicAddress:dynamicAddress}); //it will update the markers position
```

For generate the marker identifier name:

```
var markerIDs = [];
markerIDs.push("Marker"+ i);
```


Step: 3
pass the markerIDs here from above:

```
setTimeout(function(){
	self.focusMap(markerIDs, true); // delay sometime
},3200)
```


Step: 4

last & final step for placing the map into center
```

focusMap(markers, animated) {
   this.map.fitToSuppliedMarkers(markers, animated);
}
```

please go through this:
https://github.com/airbnb/react-native-maps/blob/master/example/examples/FitToSuppliedMarkers.js

**Comment by sandhysanjaya1206** [comment]
@TAM604 code from @krishbhattacharyya work with you?

or you have another source code to showing marker from firebase?

**Comment by krishbhattacharyya** [comment]
@sandhysanjaya1206 I think this is not related to firebase. If your lat long is correct then this should work properly. 


![screenshot_1503483523](https://user-images.githubusercontent.com/10433734/29705315-10ca7042-899b-11e7-9ec1-765430945887.png)

**Comment by sandhysanjaya1206** [comment]
can you trying my code @krishbhattacharyya  ? https://pastebin.com/bmzUuC47

thanks

**Comment by TAM604** [comment]
Thank you very much for the responses, but unfortunately, I am still experiencing issues with regards to populating `listingData`. I am able to fetch info from Firebase, but as you can see in my screenshot below, when I try to push the info into `listingData`, it tells me that is undefined.

Any suggestions to solve this issue?

Thank you very much again,

Tam

![image](https://user-images.githubusercontent.com/30561068/29738519-2305becc-89d9-11e7-9d8b-7f11bdeccc5f.png)

**Comment by krishbhattacharyya** [comment]
@sandhysanjaya1206 . 
1) First thing is that- this question should be in slack. 
2) this.state.dynamicAddress is return undefined please check.

**Comment by IjzerenHein** [comment]
Agreed, this issue has nothing to do with this module. Issue should be closed.

**Comment by rahibhagat** [comment]
> Hi you can do like this, may be u can get better option from another member:
> 
> Step: 1
> 
> your view like this-
> 
> ```
> 
> <MapView
> 	          provider={this.provider}
> 	          style={styles.map}
> 	          initialRegion={this.region}
> 	          onPress={this.onPress}
> 	          loadingEnabled
> 	          onRegionChange={this.onRegionChange}
> 	          ref={ref => { this.map = ref; }}
> 	          zoomEnabled={true}
> 	        >	
> 		{this.state.dynamicAddress.map(marker => (
> 	            <MapView.Marker
> 	              key={marker.key}
> 	              coordinate={marker.address}
> 	              image={flagImg}
> 	              identifier={ "Marker"+ marker.key}
> 	              onPress={() => this.getMyLocation(marker.address.latitude, marker.address.longitude)}
> 	            />
> 	        ))}
> </MapView>
> ```
> 
> Step: 2
> 
> var dynamicAddress is an array use this in loop. For generate & set the markers position:
> 
> ```
> dynamicAddress.push({
> 		        	        'key' : i,
> 		      	            'address' : { 
> 						      	latitude: responseData.results[0].geometry.location.lat,
> 					        	longitude: responseData.results[0].geometry.location.lng,
> 		      				}
> 			  		});
> 
> self.setState({dynamicAddress:dynamicAddress}); //it will update the markers position
> ```
> 
> For generate the marker identifier name:
> 
> ```
> var markerIDs = [];
> markerIDs.push("Marker"+ i);
> ```
> 
> Step: 3
> pass the markerIDs here from above:
> 
> ```
> setTimeout(function(){
> 	self.focusMap(markerIDs, true); // delay sometime
> },3200)
> ```
> 
> Step: 4
> 
> last & final step for placing the map into center
> 
> ```
> 
> focusMap(markers, animated) {
>    this.map.fitToSuppliedMarkers(markers, animated);
> }
> ```
> 
> please go through this:
> https://github.com/airbnb/react-native-maps/blob/master/example/examples/FitToSuppliedMarkers.js

self.focusMap() is not a function. i got runtime error.
