### ISSUE TITLE
[iOS] google maps stuttering / sticking issue when controlling region changes with component state / onRegionChange

### ISSUE THREAD

**Issue by LaurenceRolandJames** [react-community/react-native-maps#1592]
react-native version: 47.1
react-native-maps version: 0.16.2

Setting the region in the component state and using onRegionChange (and on RegionChangeComplete) to control the map region causes the map to stutter during touch events on iOS. Sometimes the map gets stuck completely.

This issue occurs when using Google Maps. It is not an issue when using Apple Maps. It also functions as expected on Android.

**Comment by emilefleming** [comment]
Did you resolve this? I'm experiencing the same thing.

**Comment by alvelig** [comment]
I suggest not controlling region, use animateTo...
See example: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by tmaly1980** [comment]
@alvelig Then perhaps the documentation should be updated to not offer a poor solution?

**Comment by rborn** [comment]
@tmaly1980 could you make a PR that would improve the docs? 🤗

**Comment by tmaly1980** [comment]
@rborn I unfortunately don't know what the solution is. I've switched to onRegionChangeComplete, but it only fires/refreshes once at the end after the drag is complete, so I'm not sure if that's a foolproof solution.

**Comment by alvelig** [comment]
@tmaly1980 controlling state is still a legitimate solution but unfortunately I don't know how to solve this problem with this approach. I recommend using animateToRegion. That is what my experience says.

**Comment by Rewieer** [comment]
Everything is working fine on RNM 0.17.0. Once I went to 0.20.1 it started to stutter.

**Comment by mobeenali12** [comment]
For the beginners who came here for the solution, [check this out](https://stackoverflow.com/a/54078573/10809746). :)
