### ISSUE TITLE
Custom tile is not working with MapMyIndia Map tile

### ISSUE THREAD

**Issue by anujsinghwd** [react-community/react-native-maps#1594]
If i am using mapmyindia map tile then it is not working , with google map it is working well . 
**MapMyIndia Tile Url**
[https://{s}.mapmyindia.com/advancedmaps/v1/ba61bb87d6e115d15324c61553686ec7/still_map/{z}/{x}/{y}.png](url)

**Comment by anujsinghwd** [comment]
**This is my code to load custom tile -** 
`import React from 'react';
import {
  StyleSheet,
  View,
  Text,
  Dimensions,
} from 'react-native';

import MapView, { MAP_TYPES, PROVIDER_DEFAULT } from 'react-native-maps';

class CustomTiles extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      region: {
        latitude: 27.78825,
        longitude: 77.4324,
        latitudeDelta: 1.0922,
        longitudeDelta: 1.0421,
      },
    };
  }

  get mapType() {
    // MapKit does not support 'none' as a base map
    return this.props.provider === null;
  }

  render() {
    const { region } = this.state;
    return (
      <View style={styles.container}>
        <MapView
          style={styles.map}
        >
          <MapView.UrlTile
            urlTemplate="https://{s}.mapmyindia.com/advancedmaps/v1/ba61bb87d6e115d15324c61553686ec7/still_map/{z}/{x}/{y}.png"
            zIndex={-1}
          />
        </MapView>
        <View style={styles.buttonContainer}>
          <View style={styles.bubble}>
            <Text>Custom Tiles</Text>
          </View>
        </View>
      </View>
    );
  }
}

CustomTiles.propTypes = {
  provider: MapView.ProviderPropType,
};

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: 300,
    width: 400
  },
  bubble: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
  },
  latlng: {
    width: 200,
    alignItems: 'stretch',
  },
  button: {
    width: 80,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginHorizontal: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
});

module.exports = CustomTiles;`

**I am not using meta tag in xml because i want to load MapMyIndia Map Tile**

**Comment by alvelig** [comment]
Duplicate #1595
