### ISSUE TITLE
[bug - ios] onRegionChangeComplete fires with wrong values

### ISSUE THREAD

**Issue by kesha-antonov** [react-community/react-native-maps#1596]
Hello!

```onRegionChangeComplete``` fires 2 times: first with correct values, second with some of old values. Because of this my map ```jumps```

RN: 0.47.1
RN-maps: 0.16.2

I've noticed it in ```0.16.2``` when upgraded from some ```0.14..``` I don't remember exact version

Any advice? Does anybody faced same issue?

**Comment by kesha-antonov** [comment]
Looks like this https://github.com/airbnb/react-native-maps/issues/1507

**Comment by kesha-antonov** [comment]
https://github.com/airbnb/react-native-maps/issues/1577

**Comment by alvelig** [comment]
I believe that's fixed in 0.18.3. Let me know if not.
