### ISSUE TITLE
Android Gradle documentation task failed

### ISSUE THREAD

**Issue by sytolk** [react-community/react-native-maps#1607]
Gradle documentation task failed here:
https://github.com/airbnb/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L116

I have run:
./gradlew build

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by sytolk** [comment]
@alvelig have you try to run in command line `gradle build` ?
```
cd /android 
./gradlew build
```
There is no problem with react-native build -> assembleDebug or assembleRelease
the problem is with Android Gradle documentation task.

**Comment by alvelig** [comment]
Yes, I have, it has some warnings but compiles ok.
