### ISSUE TITLE
Get Coordinates of Absolute Positioned Object on Map

### ISSUE THREAD

**Issue by thomasbaldwin** [react-community/react-native-maps#1610]
I've made a marker that I place position absolute on the map. This way, I can move the map around and the marker stays in place. I'm trying to make it so users set a location, kind of like Uber. However, the problem I'm facing is I'm not sure how to then get the coordinates of where the marker was positioned. Here is what the screen currently looks like with the absolute positioned marker:

![giphy](https://user-images.githubusercontent.com/5099084/29983762-507a1960-8f25-11e7-8e8b-a4f98d9ac9c1.gif)

I can attach a code sample if necessary

**Comment by juergengunz** [comment]
you could position the marker in the center of the map and use onRegionChange to get the map's center coordinate

**Comment by ejkkan** [comment]
@thomasbaldwin Would you mind sharing an code example of how you solved this? absolute position + retrieving cordinates

**Comment by alvelig** [comment]
Read onRegionChangeComplete event docs.

**Comment by AFMW** [comment]
Please share the Code @thomasbaldwin

**Comment by pmella16** [comment]
Please share the Code @thomasbaldwin
