### ISSUE TITLE
Map inside Tab View

### ISSUE THREAD

**Issue by wpram** [react-community/react-native-maps#1614]
I'm having trouble displaying my `<MapView />` inside a Tab. I'm using [react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view)

The `<MapView />` won't display in the map even after using : `...StyleSheet.absoluteFillObject`. I can display the map only if I put a fix height. For example: `height: 500`.

Here is what my sample tab screen looks like.

```
styles = StyleSheet.create({
  tabContent: {
    flex: 1,
  },

  map: {
    ...StyleSheet.absoluteFillObject,
  },
});

class HomeTemporary extends Component {
  render() {
    return (
      <ScrollableTabView
        renderTabBar={() => <ScrollableTabBar />}
      >
        <ScrollView tabLabel="List" style={styles.tabContent}>
          <Text>Content Tab One</Text>
        </ScrollView>
        <ScrollView tabLabel="Map" style={styles.tabContent}>
          <MapView
            scrollEnabled
            style={styles.map}
            provider={MapView.PROVIDER_GOOGLE}
            initialRegion={{
              latitude: 25.2048493,
              longitude: 55.2707828,
              latitudeDelta: LATITUDE_DELTA,
              longitudeDelta: LONGITUDE_DELTA,
            }}
          />
        </ScrollView>
      </ScrollableTabView>
    );
  }
}
```

**Comment by DevanB** [comment]
It appears that a `MapView` inside a vanilla `ScrollView` also required a fixed height. Is there a way to do this without specifying a fixed height, possibly by using `flex-basis` and/or `flex-shrink`?

**Comment by nonameolsson** [comment]
@devanb what is `vh`?

**Comment by DevanB** [comment]
`vh` is view height ([https://css-tricks.com/fun-viewport-units/](https://css-tricks.com/fun-viewport-units/)). You do have to do some odd things like pulling the main file from a package that has been updated in a while to get it working ([https://github.com/jmstout/react-native-viewport-units/blob/master/viewport-units.js](viewport-units.js)).
