### ISSUE TITLE
Can't interact with maps except zoom in

### ISSUE THREAD

**Issue by zeroseed** [react-community/react-native-maps#1616]
Hello , I have a problem with my maps
my maps can't be move except zoom in , the problem is appear when i try to use user current location on maps. when i don't use userlocation , i can't interact with maps 

here's my componentDidMount and componentWillMount function

```
componentDidMount() {
        var markerData = require('./../map_data/stores.json');
        let ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        this.setState({
            isLoading: false,
            dataSource: ds.cloneWithRows(markerData.features),
            data: markerData.features
        });

        navigator.geolocation.getCurrentPosition(
            position => {
              this.setState({
                region: {
                  latitude: position.coords.latitude,
                  longitude: position.coords.longitude,
                  latitudeDelta: LATITUDE_DELTA,
                  longitudeDelta: LONGITUDE_DELTA,
                }
              }
            );
            },
          (error) => console.log(error.message),
          { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },
          );
          this.watchID = navigator.geolocation.watchPosition(
            position => {
              this.setState({
                region: {
                  latitude: position.coords.latitude,
                  longitude: position.coords.longitude,
                  latitudeDelta: LATITUDE_DELTA,
                  longitudeDelta: LONGITUDE_DELTA,
                }
              });
            }
        );
  
      }

      
      componentWillUnmount() {
        navigator.geolocation.clearWatch(this.watchId);
      }
```

here's my render code

```
<MapView.Animated style={{
                height: window.height/2,
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
            }}
            showsMyLocationButton={true}
            provider={PROVIDER_GOOGLE}
            showsUserLocation={ true }
            region={ this.state.region }
            onRegionChange={ region => this.setState({region}) }
            onRegionChangeComplete={ region => this.setState({region}) }
    />
```

i'm using react-native version 0.47
thank you

**Comment by maluramichael** [comment]
You mean the map is really unresponsive? Got the same problem.

**Comment by zeroseed** [comment]
@maluramichael 
Found the fix ,
don't use 
region attribute on MapView
use initialRegion for set the region for the first time :)
honestly my problem now is after i swipe back from map view page , then i open map view page again ,
the map is blank , i don't know why , maybe i must reinitialize the map but how ?

**Comment by heysailor** [comment]
There's a few different types of 'blank map' problems - does the map have the legal insets, or is it just blue?

**Comment by zeroseed** [comment]
@heysailor
I'm using google maps 
And yes the map just show me blue screen with google logo
But when i tap showMyLocation button , then it back to normal

**Comment by heysailor** [comment]
Heya. It's a current bug - the blue is the sea, you're zoomed right in. See #1617 and #1559. The initialRegion prop was broken and has not yet been fixed up. Am having a look to see if I can figure it out.

**Comment by christopherdro** [comment]
Is this specific to iOS? Could you try remove Google as the provider and see if the problem still persists?

There's been quite a few issues around this in the latest releases. I think most have been resolved but now it appears that the recent changes are causing issues with Google maps on iOS.

**Comment by manideepcs024** [comment]
yes after removing google as provider, it works fine. but delta values are not working as expected when google is used nd it zooms out to whole world.

**Comment by alvelig** [comment]
See this example and forget about this problems https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

Delta values correspond to #616

**Comment by rahulpandey** [comment]
on ios map is unresponsive this is happening to my app also
