### ISSUE TITLE
Blank map when using StackNavigator (React navigation)

### ISSUE THREAD

**Issue by zeroseed** [react-community/react-native-maps#1618]
Why my google maps show blank screen (blue screen but dont show anything)
when i go to map page for the first time , it loaded normally , but when i go back to first page ,
then i go to map page, it show me blank screen
anyone facing the same problem ?

**Comment by heysailor** [comment]
Heya. It's a current bug - the blue is the sea, you're zoomed right in. See #1617 and #1559. The initialRegion prop was broken and has not yet been fixed up. Am having a look to see if I can figure it out.

**Comment by christopherdro** [comment]
@zeroseed What version of maps are you using?

**Comment by zeroseed** [comment]
@christopherdro 
i'm using 
**"react-native": "0.47.2",
"react-native-maps": "^0.16.2",**

**Comment by jeveloper** [comment]
I believe the initialregion was fixed(rolled back) in 0.16.3

**Comment by zeroseed** [comment]
@jeveloper i just updated into 0.16.3 but result still same
blue screen (sea view) 
fixed after tap showUserLocation button

:(

**Comment by luthfidc03** [comment]
@zeroseed, im using latest RN & react-native-maps & stackNavigator, working smoothly.

**Comment by juergengunz** [comment]
+1
same issue

**Comment by daominhsangvn** [comment]
any idea when this issue get fixed? i got same issue
"react-native": "0.48.4",
"react-native-maps": "^0.17.0",
"react-navigation": "^1.0.0-beta.13"
You can clone this repo to see the issue: https://github.com/daominhsangvn/testmap
clone the repo, yarn install, pod install then run ios, tap to link to goes to scene 3, scene 3 is place where the map display

**Comment by daominhsangvn** [comment]
@zeroseed Have you manage to fixed it yet ?

**Comment by daominhsangvn** [comment]
@luthfidc03 could you please send me the example of your working code?

**Comment by aaronbuchanan** [comment]
+1 with [my fork](https://github.com/aaronbuchanan/react-native-maps)

**Comment by daominhsangvn** [comment]
@aaronbuchanan It's not working, i'm still see the Sea View :(

**Comment by ruci06** [comment]
I had a same problem.
In my case, to change 'initialRegion' prop to 'region' fixed it.
Try to use 'region' property instead of 'initialRegion'

**Comment by sbkl** [comment]
When using initialRegion, I have the initial state not rendering properly but I can navigate smoothly.

When using region, the map rerender with the proper state but the navigation doesn't work properly.

Any idea?

**Comment by MinhNQ90** [comment]
Even i have set initialRegion but why it still zoom in Sea ?

**Comment by jordanmkoncz** [comment]
I'm having the same problem. I'm using `initialRegion`, and the first time the map is rendered it works perfectly, but the second time it's rendered the map is zoomed in at coordinates `0,0` (which is in the sea) so it looks like a blank blue map.

Here's my dependencies:

```
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-maps": "^0.18.3",
```

I also had this issue when I was using `"react-native-maps": "^0.17.1"`.

Just to be clear, it looks like this issue is not related to `react-navigation`, and is just a bug with `react-native-maps`.

I've found a workaround to get the map working correctly while the issue exists with `react-native-maps` by using `animateToRegion`. Here's a full example of the workaround.

```js
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

let styles;

class MapExample extends Component {
  constructor() {
    super();

    this.map = null;
  }

  componentDidMount() {
    requestAnimationFrame(() => {
      this.map.animateToRegion(
        {
          latitude: 24.4135615,
          longitude: 54.4592446,
          latitudeDelta: 0.1,
          longitudeDelta: 0.1,
        },
        1
      );
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <MapView
          ref={ref => {
            this.map = ref;
          }}
          initialRegion={{
            latitude: 24.4135615,
            longitude: 54.4592446,
            latitudeDelta: 0.1,
            longitudeDelta: 0.1,
          }}
          style={styles.map}
          provider={PROVIDER_GOOGLE}
        >
          <MapView.Marker
            coordinate={{
              latitude: 24.4135615,
              longitude: 54.4592446,
            }}
          />
        </MapView>
      </View>
    );
  }
}

styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});

export default MapExample;
```

This solution was based on the comment at https://github.com/airbnb/react-native-maps/issues/1577#issuecomment-329989550.

**Comment by alvelig** [comment]
I'm using similar approach to @jordanmkoncz's: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
