### ISSUE TITLE
maker moving animation

### ISSUE THREAD

**Issue by kdong007** [react-community/react-native-maps#1619]
I want to have a marker on the map and let it move to another location. I want to see the movement animation, not jumping. What is the best approach of doing this? 

`requestanimationframe` and update marker location on each frame?

**Comment by alvelig** [comment]
see #1765

**Comment by alvelig** [comment]
see #1765

**Comment by rushant11** [comment]
> I want to have a marker on the map and let it move to another location. I want to see the movement animation, not jumping. What is the best approach of doing this?
> 
> `requestanimationframe` and update marker location on each frame?

can you give me the code of requestanimationframe to disable the marker moving animation?
