### ISSUE TITLE
Get current viewport as polygon coordinates

### ISSUE THREAD

**Issue by IgorVanian** [react-community/react-native-maps#1621]
I want to check if a set of markers (points) are within current viewport to identify which marker am I zooming on. I guess I'll be using https://github.com/Turfjs/turf .

But to do that, I need a container as a polygon (which should be my current viewport obviously).

Is it possible to achieve, maybe with delta calculations?

(Please tell me there's a simpler way to do that...)

**Comment by EricPKerr** [comment]
You would take the lat,long coordinate and add/subtract the lat and long Deltas to get the 4 coordinates for the box.  This wouldn't account for any viewing angle modifications though, which is being worked on here: https://github.com/airbnb/react-native-maps/pull/1544

**Comment by joelbowen** [comment]
I'm doing something like this in the following manner (warning, Flow types ahead):
```
export const calculateBoundingBox = (
  region: MapRegion,
  halfLatDelta?: number = halfLatitudeDelta,
  halfLonDelta?: number = halfLongitutdeDelta
): Array<number> => [
  region.latitude + halfLatDelta,
  region.longitude - halfLonDelta,
  region.latitude - halfLatDelta,
  region.longitude + halfLonDelta,
];
```

This returns an array of [lat1, lon1, lat2, lon2] which is top-left and bottom-right coordinates.

**Comment by Tom29** [comment]
@joelbowen  what's `halfLatitudeDelta`?
i see `onRegionChangeComplete` returns `latitudeDelta`, so it's latitudeDelta/2?

**Comment by joelbowen** [comment]
Exactly that @Tom29!

**Comment by Tom29** [comment]
@joelbowen what's about `initialRegion` while there is no given `latitudeDelta` and `longitudeDelta`.
basically i don't understand how `latitudeDelta` and `longitudeDelta` are generated.

**Comment by joelbowen** [comment]
@Tom29 I identified a good "baseline" `latitudeDelta` for `initialRegion` and used that. You could `console.log` the values coming from `onRegionChange` to get a good `latitudeDelta` value to use, but fair warning it won't be exactly the same across different devices.

**Comment by alvelig** [comment]
Duplicate of #356

**Comment by alvelig** [comment]
Docs in #637
