### ISSUE TITLE
Unable to install (Mach-O Linker error or no files)

### ISSUE THREAD

**Issue by stjepangolemac** [react-community/react-native-maps#1623]
I am using wix react-native-navigation with airbnb react-native-maps.

Versions:
- react-native 0.47.2
- react-native-maps 0.16.3
- react-native-navigation 1.1.212

When trying to build an app in XCode I get this.
`linker command failed with exit code 1 (use -v to see invocation)`

I did everything as specified in the install guide, I even tried all three options but I could not fix this problem.

EDIT:
Now did everything again and got a different error.
`No such file or directory node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapUrlTile.m'`

EDIT2:
Now repeated everything again and it says that some files could not be found but they are present in their folders. Some of those files are RCTDevMenu.h, RCCManager.h,...
It's always just one of those files, but every time I try again they change.

This is my podfile:
```
# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'xxx' do
  rn_path = '../node_modules/react-native'

  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga/Yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # If you need GoogleMaps support on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

This is the Linker error.
![Screenshot](https://image.prntscr.com/image/-s7rFCJOS9ybgmitHjAUMA.png)

**Comment by victorbadila** [comment]
+1

**Comment by bacancy-suresh** [comment]
I also get this same issues

**Comment by tillg** [comment]
Same problem here

**Comment by RyanMitchellWilson** [comment]
If anyone is still having problems I followed this walkthrough and it worked perfectly. Very easy to follow and has step by step instructions. https://medium.com/@kswanie21/react-native-google-map-with-react-native-maps-572e3d3eee14

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
