### ISSUE TITLE
I want to get user's current location details like latitude and longitude

### ISSUE THREAD

**Issue by thayanithik** [react-community/react-native-maps#1624]
Using react native's geolocation component causes timeout on android many times.

So i want to get user's current location from mapitself.

Is there any functional callback to get user's current location from mapitself?

**Comment by milon87** [comment]
any response?

**Comment by victorbadila** [comment]
If it's not in the API it is probably not supported. I believe this issue should either be closed or renamed as a "Feature Request".

**Comment by alvelig** [comment]
Out of scope of the library. Look https://facebook.github.io/react-native/docs/geolocation.html

**Comment by edamazzio** [comment]
I know this is old, but the user location that shows this api is much faster than https://facebook.github.io/react-native/docs/geolocation.html.

**Comment by rborn** [comment]
@edamazzio use `onUserLocationChange`  https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#events
