### ISSUE TITLE
getOpenSourceSoftwareLicenseInfo is deprecated since GPS 11

### ISSUE THREAD

**Issue by markusguenther** [react-community/react-native-maps#1625]
Google deprecated getOpenSourceSoftwareLicenseInfo() that is used since the following commit.

[https://github.com/airbnb/react-native-maps/commit/75a38eab271b83d37a7f4089de806acac1a4865d](https://github.com/airbnb/react-native-maps/commit/75a38eab271b83d37a7f4089de806acac1a4865d
)
 
So if you are using play services in version 11 and more because you are maybe using also firebase services, you get a problem. I actually fixed it for by not using this constant.

And will discuss here maybe if this constant is relevant? Maybe we just check before using if this API call is available.

**Comment by rborn** [comment]
Should be solved by this https://github.com/react-community/react-native-maps/pull/1757
