### ISSUE TITLE
Build Error during run-ios

### ISSUE THREAD

**Issue by dniccum** [react-community/react-native-maps#1628]
I am consistently getting an error during my app builds. I can verify that the CocoaPods have been added to my project.

```
ld: file too small (length=0) file '/App/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture x86_64
```

I am using React Native `0.47.1` and Maps `0.16.3`. It appears that there is something wrong with the CocoaPods but I am not sure.

**Comment by kichiwa** [comment]
I can not run react-native run-ios. 
RS 0.48.3, Maps 0.16.3
:(

Installing build/Build/Products/Debug-iphonesimulator/helper.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/helper.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
