### ISSUE TITLE
Failed to open Map on Android 6 (real device)

### ISSUE THREAD

**Issue by zandzpider** [react-community/react-native-maps#163]
Specs: Sony Xperia Z5 Compact running latest android (6)
Google maps and play services are installed and working

What i have tested and confirmed that is working
- The genymotion android 6 and 5 simulator works
- Tested on several other real devices (samsung s4 with android 5.1) works

![2016-04-02 19 07 22](https://cloud.githubusercontent.com/assets/321691/14228542/7f6750e4-f917-11e5-96d6-f34e7f267102.png)

Here's is my package.json contents

"dependencies": {
    "babel-preset-es2015": "^6.6.0",
    "color": "^0.11.1",
    "react": "^0.14.8",
    "react-native": "^0.22.2",
    "react-native-android-statusbar": "^0.1.2",
    "react-native-drawer": "^2.0.0-alpha6",
    "react-native-maps": "^0.3.1",
    "react-native-navbar": "^1.2.2",
    "react-native-router-flux": "^2.3.1",
    "react-native-vector-icons": "^1.3.2",
    "react-redux": "^4.4.0",
    "react-timer-mixin": "^0.13.3",
    "redux": "^3.3.1",
    "redux-multi": "^0.1.12",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.0.1"
  }

**Comment by BigPun86** [comment]
+1

**Comment by zandzpider** [comment]
Tested on Samsung S7 curved with Android 6. worked. weird it's only on my phone. and BigPun86 too i guess

**Comment by jrichardlai** [comment]
What are the versions for google play services that you are using ? I think they should be 8.4.0

    compile 'com.google.android.gms:play-services-base:8.4.0'
    compile 'com.google.android.gms:play-services-location:8.4.0'
    compile 'com.google.android.gms:play-services-maps:8.4.0'

**Comment by BigPun86** [comment]
I am using 8.3 for all. Might be the reason why it breaks my app. But if i update it in react-native-maps build.gradle, then the build fails.

<img width="1384" alt="screen shot 2016-04-06 at 22 33 40" src="https://cloud.githubusercontent.com/assets/7880624/14331949/abf40b88-fc47-11e5-9049-24824faadfe4.png">

**Comment by zandzpider** [comment]
@jrichardlai are you thinking of phone version of google play services? if so, it is 8.3.03 (2645110-446)

**Comment by zandzpider** [comment]
@jrichardlai 

or this maybe? node_modules/react-native-maps/android/build.gradle

dependencies {
    compile 'com.facebook.react:react-native:0.19.+'
    compile "com.google.android.gms:play-services-base:8.4.0"
    compile 'com.google.android.gms:play-services-maps:8.4.0'
}

**Comment by BigPun86** [comment]
@jrichardlai No not the Phone Version. I meant the dependencies in node_modules/react-native-maps/android/build.gradle. If i use 8.4.0 for base and maps my app won´t build. I get the above error.

So i had to downgrade to:

    dependencies {
        compile 'com.facebook.react:react-native:0.19.+'
        compile "com.google.android.gms:play-services-base:8.3.0"
        compile 'com.google.android.gms:play-services-maps:8.3.0'
    }

With this dependency setup my app builds and i can use the map, except on the Sony Xperia Z5....

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
