### ISSUE TITLE
There are some differences between the user's location of react-native-map and the location from navigator.geolocation.

### ISSUE THREAD

**Issue by SleetShang** [react-community/react-native-maps#1630]
![img_1106](https://user-images.githubusercontent.com/20389595/30236710-3289c6f2-9552-11e7-9c73-667d62e0728e.PNG)

**Comment by alvelig** [comment]
Location is not accurate when you are placing your marker.

See example: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
