### ISSUE TITLE
Focus on <Marker/> so that the Google "directions" icon shows on the bottom right of screen

### ISSUE THREAD

**Issue by Progoogler** [react-community/react-native-maps#1632]
When I press on a `Marker`, it displays a set of Google icons on the bottom right of the screen to either get directions automatically to this Marker location from my location or open the Google Maps app. 

But how do I "select" or "focus" on the `Marker` without actually physically pressing on the `Marker` first?

**Comment by alvelig** [comment]
Merging to #1872
