### ISSUE TITLE
SyntheticEvent Error 

### ISSUE THREAD

**Issue by Kiozak** [react-community/react-native-maps#1633]
Hello , well i m trying to make a map app with react-native , so i used your Example guys and this what i got in compilation  :

![21585940_466710847045961_1144721829_o](https://user-images.githubusercontent.com/18468446/30266939-dd4b3de6-96d8-11e7-8e5f-ec410b51e11d.png)
 
i don't know why , i tried this #1394 as a solution but it didn't work :/ 

i m using  : "react-native": "0.48.1"
                  "react-native-maps": "^0.16.3"

Thanks

**Comment by alvelig** [comment]
Use this example and comment please. https://github.com/alvelig/react-native-maps-example
