### ISSUE TITLE
Unable to set max/min zoom on Android

### ISSUE THREAD

**Issue by joelbowen** [react-community/react-native-maps#1635]
I have been able to get expected results on iOS using `maxDelta` on MapView but am not able to get the same behavior on Android using `maxZoomLevel` or `minZoomLevel`. They don't seem to have any effect, is anyone else having this issue?

I am using CRNA, with expo 20 and react-native-maps 0.15.3

**Comment by foyarash** [comment]
minZoomLevel and maxZoomLevel have been implemented on 0.16
