### ISSUE TITLE
Provide Support for GPS Tracking

### ISSUE THREAD

**Issue by shukerullah** [react-community/react-native-maps#1637]
This library should provide GPS tracking too for both (Android iOS) platform. Also I would like to see this library to ask permission for GPS at run time.

**Comment by smolleyes** [comment]
hello

there's some libraries to do it already (https://github.com/mauron85/react-native-background-geolocation) or do it yourself with socket.io .... 

and permission is so easy to add... :)

**Comment by alvelig** [comment]
This is out of scope of the lib. You should implement it yourself.
