### ISSUE TITLE
Build failed when run "react-native run-ios"

### ISSUE THREAD

**Issue by kichiwa** [react-community/react-native-maps#1638]
Dear all, 
I have try to install react-native-maps@0.16.3 with react-native@0.48.3. 
I can not run react-native run-ios

** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/khoanguyen/Documents/rnmaps/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/khoanguyen/Documents/rnmaps/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/khoanguyen/Documents/rnmaps/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTTVRemoteHandler.o /Users/khoanguyen/Documents/rnmaps/node_modules/react-native/React/Base/RCTTVRemoteHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/rnmaps.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/rnmaps.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Thank you in advance

**Comment by kichiwa** [comment]
I have tried to use XCode to build. 
I found 1 error: 

Documents/rnmaps/node_modules/react-native/React/Base/RCTTVRemoteHandler.m:25:9: 'RCTDevMenu.h' file not found

**Comment by pierreis** [comment]
I got exactly the same problem, following all steps indicated here:

https://github.com/anhtuank7c/maps-example

**Comment by raihanrazi** [comment]
Having the same issue

**Comment by matthieupinte** [comment]
check if you have 'DevSupport' added, see
[#15775](https://github.com/facebook/react-native/issues/15775)

but after that I got a new error :
`Apple Mach-O Linker Error Group`

<img width="516" alt="screen shot 2017-09-15 at 11 53 48 am" src="https://user-images.githubusercontent.com/2217014/30477191-975fc914-9a0c-11e7-9c57-e4f376bcdc4b.png">

---

And this one is not really specific... can't find any useful help.

**Comment by matthieupinte** [comment]
In fact I just removed the `AirMaps` from my project and it's now building well.
Hope it can help ;)

**Comment by dobrysmak** [comment]
Same issue here
```
OS: MacOs High Sierra (10.13)
xCode: 9.0

deps:
react-native: 0.48.4
react-native-maps: 0.16.3
```

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by hill** [comment]
@alvelig I'm having issues running your version. Even just installing with `npm i` leads to:

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/react-community/react-native-maps.git
npm ERR!
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
```

I assume it's to do with permissions with the repo. Could you please suggest an alternative?

Thanks 😁

**Comment by alvelig** [comment]
It wasn't me :astonished: Sorta github issue XD
Change in `package.json`:
```
   "react-native-maps": "git+ssh://git@github.com/react-community/react-native-maps.git"
```
to
```
   "react-native-maps": "https://github.com/react-community/react-native-maps.git"
```

**Comment by heron2014** [comment]
I recently managed to upgrade existing react-native-maps from 0.17 to 0.21 with react-native 0.51 - these are the instructions: 

https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0#upgrade-existing-react-native-maps-from-017-to-021-with-react-native-0510

Hope that helps anyone.

**Comment by qodehub-nanadjei** [comment]
This solution might help you out. 
https://github.com/facebook/react-native/issues/24450#issuecomment-516760157
