### ISSUE TITLE
Error while updating 'coordinate' of a view manager by AIRMapMarker

### ISSUE THREAD

**Issue by mikhi** [react-community/react-native-maps#1639]
Hello,

i have the following issue: I don't know why on Android version of my app, for some latitude and longitude values the following error appears when i set a marker: "Error while updating 'coordinate' of a view manager by AIRMapMarker"

example of lat and lng that trigger this kind of error: 51.4152072, 0.0292294

In particular, I have noticed that the error appears only for positive values of longitude.

Package version:
"react": "16.0.0-alpha.6",
"react-native": "^0.44.3",
"react-native-maps": "^0.15.3",

Any idea what to do?

Thanks,
Mihai

**Comment by alvelig** [comment]
Please, update your issue to the new issue template to make a Minimum Reproducible Example.
From your post it's not clear if your variables are strings or float. Let me know, when you do and I'll see and reopen.
