### ISSUE TITLE
Memory Leak  of Mapview while using Navigator

### ISSUE THREAD

**Issue by pigflymoon** [react-community/react-native-maps#1641]
Hello,

I'm using  and when I'm switching between views on 
"react": "16.0.0-alpha.12",
"react-native": "^0.48.0", 
"react-native-maps": "^0.16.3",
iOS 10.12.3

memory keep rising up when I push a route / pop a route again and again. And using xcode leak to check leak found that as following:
![memory-leak](https://user-images.githubusercontent.com/22825982/30353003-888a8adc-9877-11e7-951f-d2ca89c6a5e3.png)

Any idears would be greatly appreciated!

Thanks.

**Comment by alvelig** [comment]
Please fill issue according to the new issue template. Comment and we will reopen. Looks like its not  related to the lib, but to navigator
