### ISSUE TITLE
Is there a way to specify the Google map api key from javascript as a prop to the MapView component?

### ISSUE THREAD

**Issue by balajivenkatesh** [react-community/react-native-maps#1648]

**Comment by sami718** [comment]
Add this to AndroidMainfest.xml file -
<application .......>
<meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="YOUR_API_KEY"/>
</application>

**Comment by sami718** [comment]
Add this to AndroidMainfest.xml file -
<application .......>meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="YOUR_API_KEY"/></application>

**Comment by jeveloper** [comment]
Short answer, NO

**Comment by alvelig** [comment]
Or, you may use react-native-config. But the key should be provided on build time.

**Comment by jsdevninja** [comment]
@alvelig 
How can I set key dynamically even on build time using react-native-config?

**Comment by alvelig** [comment]
@jsdevninja please refer to https://github.com/luggit/react-native-config#android

**Comment by jsdevninja** [comment]
I need to use the dynamic google api key in android project.
What I want exactly is to use Google api key as a props in Android project.
Is it possible?

**Comment by alvelig** [comment]
@jsdevninja no, it's not possible.

**Comment by alvelig** [comment]
@jsdevninja the link above is exactly how you can define your api key in `.env` file.
