### ISSUE TITLE
Perfomance of markers (600 points)

### ISSUE THREAD

**Issue by salbatore** [react-community/react-native-maps#1649]
I'm making an app with a Google map and 600 markers :round_pushpin:. The problem is that markers are custom with an image (small image without shadow). 

The map is very slow with many markers :turtle:

I have tried (in the last versión of React Native Maps):

-Marker with vector inside.
-Marker with an Image inside.
-Marker with an icon inside.
-Marker with mapview.circle inside.
-Marker width param image.

The map is always slow.

**However, if I use the default Google icon, everything works super good.**

Is there any way to edit (width image or svg or polygon) that marker outside React Native ?. My icon is always the same :round_pushpin: 

Thanks! ... great work this module.  :cupid:

**Comment by chintanparikh** [comment]
I had the same issue. I fixed it by clustering the points using supercluster.

**Comment by salbatore** [comment]
@chintanparikh Can you give me an example code? I have not found any that worked.

**Comment by danieljvdm** [comment]
He's referring to https://github.com/mapbox/supercluster

**Comment by salbatore** [comment]
thanks @danieljvdm 💃

**Comment by alvelig** [comment]
#213 see there. And #369 
Check that you are not re-rendering MapView or your Markers
