### ISSUE TITLE
java.lang.ClassCastException: com.google.maps.api.android.lib6.gmm6.api.am cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by sambit-112081** [react-community/react-native-maps#1652]
I am trying integrate map in android
While rendering map in android, it is giving below exception.

![image](https://user-images.githubusercontent.com/12734002/30510872-b0759de6-9aea-11e7-8874-36709148653f.png)

We are using : 
![image](https://user-images.githubusercontent.com/12734002/30510884-e8d48134-9aea-11e7-8340-9a49ec9420ed.png)

compileSdkVersion 25
    buildToolsVersion "26.0.1"

    defaultConfig {
        applicationId "com.facebookintegration"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

Please let me know, where i am going wrong. 
It's running fine in ios.

**Comment by jpapillon** [comment]
I'm having the same issue.

**Comment by shenlongdemon** [comment]
i have this problem.
any help ?

**Comment by shenlongdemon** [comment]
Hi @sambit-112081 
i fixed it and please try the way
 - If you render marker or control of maps, please using 
    ex: import MapView from 'react-native-maps';
  then in function which you render marker or whatever, please using <MapView.Marker />

- I got problem when using library what override react-native-maps (i used react-native-map-clustering) so i back to use react-native-maps and raised issue to owner

**Comment by rtman** [comment]
@sambit-112081 
If you are still having this issue, or anyone else. I was also encountering this, and it was because I was using both `<MapView>` and `<MapView.Animated>`. I at first thought they worked together but its one or the other, so I deleted the `<MapView>` and it works

**Comment by alvelig** [comment]
#1869 should fix that
