### ISSUE TITLE
Missing package.json from Example demo

### ISSUE THREAD

**Issue by dk0r** [react-community/react-native-maps#1659]
**Issue**: The demo example is broken due to a missing `package.json` from the [example directory](https://github.com/airbnb/react-native-maps/tree/master/example). 

**Cause**: The 'package.json' was removed on 26-March by @lelandrichardson's [6cd30ad](https://github.com/airbnb/react-native-maps/tree/6cd30add6b95ae69f0fbdc2a14adfbc394ed2a1e/example) commit.

**Solution**: Provide a new `package.json` that adhere's to `react-native-maps` current v0.16.4 dependencies.

**Comment by ahmetabdi** [comment]
Still a issue it seems

`react-native run-android` cannot run without a package.json why was it removed?

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Without pods: https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by alvelig** [comment]
Merged to #1785

**Comment by christopherdro** [comment]
The example uses the same package.json at the root level.
