### ISSUE TITLE
Map could not load after a long period of time

### ISSUE THREAD

**Issue by r0b0t3d** [react-community/react-native-maps#1663]
Hi,
I usually meet this problem.

![2017_09_09_17 31 56](https://user-images.githubusercontent.com/8109285/30769993-3a7f9608-a050-11e7-8447-c6750ac7a1b9.png)

As you can see, the map could not load as normal while I animating the marker. It kept this state until I touch the map, map working as normal. 
Did you all got this issue?

Thanks,

**Comment by alvelig** [comment]
Updated Google SDK. Please confirm that this appears on 0.19.0 and we'll reopen.
