### ISSUE TITLE
failed for task ':app:mergeDebugResources'

### ISSUE THREAD

**Issue by jantsch** [react-community/react-native-maps#1664]
I have installed the library and linked everything according to what is written in the README file. However when I try to compile I receive the following error.   I have already checked the setting.gradle, build.gradle and everything is linked. I have tried to change the build.gradle to play-services-base with the version specified in the error but it didn't work as well.  I am trying to run with an Android Device. 
Does anyone have a clue of what is happening?

Execution failed for task ':app:mergeDebugResources'.
> Error: Failed to crunch file C:\Users\---\---\---\---\---\GPS_FrontEnd\android\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png into C:\Users\---\---\---\---\---\GPS_FrontEnd\android\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

**Comment by AlvaroFalcon** [comment]
Hey, any fixes for it? I'm having the same issue...

**Comment by alvelig** [comment]
Try this project: https://github.com/alvelig/react-native-maps-example

But apparently is #1773 related

**Comment by VySellathurai** [comment]
I've face exactly the same issue and this work for me : 
1. I moved my projet in a different location to shorten the path (I put mine in the root of my D: for instance)
2. run the command `gradlew clean` from android directory of the project

As I understood, it's a OS path limit issu : 
https://stackoverflow.com/questions/33905687/error-file-path-too-long-on-windows-keep-below-240-characters/34680168#34680168

**Comment by pistou** [comment]
Moving the project folder is super _hacky_.
I used [this solution](https://stackoverflow.com/a/34680168/2099704) :

In build.gradle file
```
allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    repositories {
       ...
    }
}
```
