### ISSUE TITLE
Using Address Instead Of Longitude And Latitude With react-native-maps

### ISSUE THREAD

**Issue by sami718** [react-community/react-native-maps#1666]
I want to provide address to <Mapview /> component instead of latitude and longitude. Is it possible ?

**Comment by shepitchakpavlo** [comment]
@sami718  You can use Google Geocoding API to convert address string ->  coordinates

**Comment by alvelig** [comment]
Yep, this is out of scope of the library. Use https://github.com/devfd/react-native-geocoder
