### ISSUE TITLE
Move marker along the polyline with AnimatedRegion

### ISSUE THREAD

**Issue by jayminpanchal** [react-community/react-native-maps#1667]
I am currently working on the Car moving on the map with the Smooth animation from one location to another.

I have developed basic demo using AnimatedRegion by passing the LatLng and duration to animate them. But what I want is that animate marker along with the Polyline.

So is it possible to use AnimatedRegion with the Polyline because Polyline takes array of LatLng and AnimatedRegion takes only one LatLng?

Like, I want to do this way

https://developers.google.com/maps/documentation/javascript/examples/overlay-symbol-animate

Please help me.

**Comment by krunalpanchal** [comment]
Hi Jaymin,
Can you please help me with the Animation of Marker, I also want the same thing i.e. to move my car smoothly to the real time location which I am fetching. Can you please share me the code or snippet for the same?

Thanks
Krunal Panchal

**Comment by alvelig** [comment]
See #1765

**Comment by Yaweii** [comment]
@krunalpanchal Hi Krunal. I am working on a similar personal project i.e move marker smoothly with the real time location data I am fetching. I've been getting stuck on this for days. Would you mind share some thoughts? Much appreciated!
