### ISSUE TITLE
Rotate a marker when device is also rotating

### ISSUE THREAD

**Issue by SoldierCorp** [react-community/react-native-maps#1672]
Hi,

I'm wondering if you have a solution to get the degrees of the device when is rotating to set those degrees in the `rotation` parameter in the marker so for example if I have a marker of a car then see how the marker of a car is rotating when I'm rotating the device.

**Comment by alvelig** [comment]
Track rotation in your marker state and change it as it changes.

**Comment by hlbp** [comment]
@alvelig hi!!! do you know where can i get that device Rotation?

**Comment by alvelig** [comment]
@hlbp Google for something like that https://github.com/yamill/react-native-orientation

**Comment by hlbp** [comment]
@alvelig  thank you!! i made it with https://github.com/vnil/react-native-simple-compass it uses the native compass and return a value in degrees. so i can know where the device is pointing.

**Comment by breadadams** [comment]
We're also using `react-native-simple-compass` to get the angle at which the device is pointing. However if you rotate the map canvas (with a 2 finger _spin_) the marker is no longer pointing to the "correct" position on the map.

It _should_ just be a case of adding the maps current rotation to the the degrees returned from the above mentioned library.

That just leaves the question - is it actually possible to get the current **manual** rotation of the canvas (in degrees) from `react-native-maps`?
