### ISSUE TITLE
MapView onPress event fired multiple times for single tap on iOS

### ISSUE THREAD

**Issue by zolrath** [react-community/react-native-maps#1675]
I just added a console.log to `onPress` event on `MapView` and each time I tap the map on iOS it gets called 3 times.
On Android, the `onPress` event is only called once, as expected.

This might be related to #1353, perhaps multiple tap events are also getting sent during marker selection.

**Comment by alvelig** [comment]
Could you fill your issue according to the new issue template please, so we'll reopen and review

**Comment by ratkus91** [comment]
Does anyone have any idea how to fix this?

**Comment by vitriolix** [comment]
I'm seeing this issue as well, it is not caused by multiple overlapping markers for me though.

**Comment by vitriolix** [comment]
Looking deeper, it looks like the MapView.onPress is *also* being called right after the MapView.Marker.onPress, which seems like a different bug. I'll write up a new issue when I have a chance, disregard my comment here
