### ISSUE TITLE
MapView onPress triggered on double tap on iOS, not on Android

### ISSUE THREAD

**Issue by zolrath** [react-community/react-native-maps#1676]
The `onPress` event is fired on iOS (3 times, ala #1675) when the map is double tapped.
On Android, the onPress event is not fired on double tap.

I'd expect to have them behave the same way.
Either have an `onDoubleTap` prop or for it not to fire on double tap so we can rely on the zoom feature without activating our tap functions.

**Comment by alvelig** [comment]
Could you fill your issue according to the new issue template please, so we'll reopen and review
