### ISSUE TITLE
:react-native-maps:compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by Hormonot** [react-community/react-native-maps#1678]
Hi, have some problem in configuring map to android , it was easy to iOS. 

this is log when i try to start

:react-native-maps:preDebugUnitTestBuild UP-TO-DATE
:react-native-maps:preReleaseUnitTestBuild UP-TO-DATE
:react-native-maps:prepareComAndroidSupportAppcompatV72301Library
:react-native-maps:prepareComAndroidSupportSupportV42400Library
:react-native-maps:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:react-native-maps:prepareComFacebookFrescoDrawee101Library
:react-native-maps:prepareComFacebookFrescoFbcore101Library
:react-native-maps:prepareComFacebookFrescoFresco101Library
:react-native-maps:prepareComFacebookFrescoImagepipeline101Library
:react-native-maps:prepareComFacebookFrescoImagepipelineBase101Library
:react-native-maps:prepareComFacebookFrescoImagepipelineOkhttp3101Library
:react-native-maps:prepareComFacebookReactReactNative0472Library
:react-native-maps:prepareComFacebookSoloaderSoloader010Library
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBase1024Library
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBasement1024Library
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesMaps1024Library
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesTasks1024Library
:react-native-maps:prepareOrgWebkitAndroidJscR174650Library
:react-native-maps:prepareReleaseDependencies
:react-native-maps:compileReleaseAidl
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:compileLint
:react-native-maps:copyReleaseLint UP-TO-DATE
:react-native-maps:compileReleaseRenderscript
:react-native-maps:generateReleaseBuildConfig
:react-native-maps:generateReleaseResValues
:react-native-maps:generateReleaseResources
:react-native-maps:mergeReleaseResources
:react-native-maps:processReleaseManifest
:react-native-maps:processReleaseResources
:react-native-maps:generateReleaseSources
:react-native-maps:incrementalReleaseJavaCompilationSafeguard
:react-native-maps:compileReleaseJavaWithJavac
:react-native-maps:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/hrmnt/WebstormProjects/bloomapp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java:27: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-maps:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 28.262 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by gusilveiramp** [comment]
Same here.
Here the error began to happen with 0.49 of RN.
2 weeks ago I tried in version 0.47 and everything worked perfectly.

**Comment by dbarros** [comment]
I worked around it for a while by manually deleting the offending line with the `@override`.

**Comment by gusilveiramp** [comment]
Please, could you explain me better?

**Comment by gusilveiramp** [comment]
In my case, it not specify the line.
My error is:

java.io.IOException: Could not delete path 'C:\xampp\htdocs\rnReduxNavigation\node_modules\react-native-maps\lib\android\build\intermediates\classes\release\android'.

**Comment by Tanumay92** [comment]
Same Issue Here. Is there any solution regarding this??

**Comment by gusilveiramp** [comment]
@Tanumay92 this problem did not happen to me anymore. Everything works perfectly every time I try to install it now. I am using version 0.49 of RN.
But if it does, just try to remove the @override from the file in question. For example, remove the @override from the MapsPackage file on line 27.

**Comment by dann1609** [comment]
I have version 0.50.3 of RN, I have to this problem, but I can't find page that @dbarros and @gusilveiramp  talk about.

**Comment by hugoh1995** [comment]
@dann1609 you could share how and where you found the file for future people who encounter the same issue. Would be helpful!

**Comment by Luckygirlllll** [comment]
I got error "cannot find symbol method getOpenSourceSoftwareLicenseInfo(ReactApplicationContext). Error:Execution failed for task ':react-native-maps:compileReleaseJavaWithJavac'." in AirMapModule.java any ideas how to fix that?

**Comment by rborn** [comment]
@Luckygirlllll can you try with the git version?

**Comment by MSSPL-PiyaleeMaiti** [comment]
@grabblesaur  Is there any permanent solution except that remove override. Changes in package is temporary solution. When I run install then again this error is coming. I need to fix solution on other way except npm packages.

**Comment by Msspl-PrashenjeetRoy** [comment]
Do we have any solution yet?

**Comment by vendicto** [comment]
@MSSPL-PiyaleeMaiti  Try to find library version for your react-native version, eg. 
If you have react-native 0.47.x. you should update **react-native-svg** to 5.4.1 version
`npm i <name>@<version>`
![image](https://user-images.githubusercontent.com/17904693/44096988-5fc298b2-9fe5-11e8-8cce-cbc5eb54c744.png)

**Comment by Msspl-PrashenjeetRoy** [comment]
@vendicto You are showing us an example of react-native-svg but which version should we use for react-native-maps. We both @MSSPL-PiyaleeMaiti and me, using react-native-maps "^0.15.3" in react-native "0.54.4" and react "^16.3.0-alpha.1".
So which version should be for react-native-maps?
cc @MSSPL-PiyaleeMaiti

**Comment by Jeet007das** [comment]
> I have version 0.50.3 of RN, I have to this problem, but I can't find page that @dbarros and @gusilveiramp talk about.
> 
> I found it! I just remove the @override and it works!
> Thanks a lot!

when I removed @override then I got this error
> Task :app:compileDebugJavaWithJavac FAILED
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:6: error: cannot find symbol
import com.hypertrack.lib.HyperTrackMapFragment;
                         ^
  symbol:   class HyperTrackMapFragment
  location: package com.hypertrack.lib
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:17: error: cannot find symbol
    public boolean setMyLocationEnabled ( HyperTrackMapFragment hyperTrackMapFragment ) {
                                          ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:33: error: cannot find symbol
        public boolean showAddressInfoViewForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                                      ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:38: error: cannot find symbol
    public boolean showActionDetailForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                               ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:43: error: cannot find symbol
        public boolean showActionSummaryForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                                    ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:48: error: cannot find symbol
        public boolean showUserInfoForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                               ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:58: error: cannot find symbol
        public boolean showSourceMarkerForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                                   ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:63: error: cannot find symbol
        public int getHeroMarkerIconForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                                ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:68: error: cannot find symbol
        public int getExpectedPlaceMarkerIconForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                                         ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:73: error: cannot find symbol
        public boolean showCallButtonForActionID(HyperTrackMapFragment hyperTrackMapFragment, String actionID) {
                                                 ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:78: error: cannot find symbol
        public boolean showTrafficLayer(HyperTrackMapFragment hyperTrackMapFragment) {
                                        ^
  symbol:   class HyperTrackMapFragment
  location: class DriverAdapter
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:21: error: cannot find symbol
import com.hypertrack.lib.HyperTrackMapFragment;
                         ^
  symbol:   class HyperTrackMapFragment
  location: package com.hypertrack.lib
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:50: error: cannot find symbol
    private HyperTrackMapFragment mapFragment;
            ^
  symbol:   class HyperTrackMapFragment
  location: class TrackActivity
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\MainApplication.java:10: error: package com.wix.reactnativenotifications does not exist
import com.wix.reactnativenotifications.RNNotificationsPackage;
                                       ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\MainApplication.java:11: error: package com.evollu.react.fcm does not exist
import com.evollu.react.fcm.FIRMessagingPackage;
                           ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\MainApplication.java:12: error: cannot find symbol
import io.hypertrack.RNHyperTrackPackage;
                    ^
  symbol:   class RNHyperTrackPackage
  location: package io.hypertrack
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:32: error: method does not override or implement a method fro
        @Override
        ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:37: error: method does not override or implement a method fro
    @Override
    ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:42: error: method does not override or implement a method fro
        @Override
        ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:47: error: method does not override or implement a method fro
        @Override
        ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:57: error: method does not override or implement a method fro
        @Override
        ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:62: error: method does not override or implement a method fro
        @Override
        ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\adapter\DriverAdapter.java:77: error: method does not override or implement a method fro
        @Override
        ^
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:76: error: cannot find symbol
                public void onMapReadyCallback(HyperTrackMapFragment hyperTrackMapFragment, GoogleMap map) {
                                               ^
  symbol: class HyperTrackMapFragment
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:83: error: cannot find symbol
                public void onMapLoadedCallback(HyperTrackMapFragment hyperTrackMapFragment, GoogleMap map) {
                                                ^
  symbol: class HyperTrackMapFragment
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:93: error: cannot find symbol
                public void onMapCleared(HyperTrackMapFragment hyperTrackMapFragment, GoogleMap map) {
                                         ^
  symbol: class HyperTrackMapFragment
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:124: error: cannot find symbol
                    if(action.getETA() != null) {
                             ^
  symbol:   method getETA()
  location: variable action of type Action
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:125: error: cannot find symbol
                        Date etaDate = action.getETA();
                                             ^
  symbol:   method getETA()
  location: variable action of type Action
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:208: error: cannot access zzbgl
                    .position(new LatLng(wayChildPoint.get(1), wayChildPoint.get(0)))
                    ^
  class file for com.google.android.gms.internal.zzbgl not found
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:442: error: cannot find symbol
        mapFragment = (HyperTrackMapFragment) getSupportFragmentManager().findFragmentById(R.id.map_fragment);
                       ^
  symbol:   class HyperTrackMapFragment
  location: class TrackActivity
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\hypertracker\TrackActivity.java:677: error: cannot find symbol
            HyperTrack.stopTracking ();
                      ^
  symbol:   method stopTracking()
  location: class HyperTrack
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\MainApplication.java:46: error: cannot find symbol
            new RNNotificationsPackage(),
                ^
  symbol: class RNNotificationsPackage
E:\parenApp\beaconparent\android\app\src\main\java\in\greylabs\beacon\MainApplication.java:48: error: cannot find symbol
            new RNHyperTrackPackage(),
                ^
  symbol: class RNHyperTrackPackage
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
33 errors

**Comment by VenkateshSomu** [comment]
where can I found the file of @override to remove, Can you please tell the folder path. @dbarros @grabblesaur
