### ISSUE TITLE
Install Google Maps on IOS after "react-native link react-native-maps"

### ISSUE THREAD

**Issue by Nizarius** [react-community/react-native-maps#1681]
After 
```
npm install react-native-maps --save
react-native link react-native-maps
```
Core IOS maps work well. 
For activating Google Maps on Android it's enough to specify Google Maps API Key.

What is the right way to switch core ios maps to Google ones after "link" command? 

Is it "Option 1: CocoaPods - Same as the included AirMapsExplorer example"? But it looks like a lot of the duplicative actions in Podfile. And after several attempts I failed to switch to Google maps cause  of #1638 error.

In console i Got
```
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/petrpotapov/proil_app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTReconnectingWebSocket.o /Users/petrpotapov/proil_app/node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/proil_app.app
Launching org.reactjs.native.example.proil-app
org.reactjs.native.example.proil-app: 68166

```
XCode shows the issue `"/Users/petrpotapov/proil_app/node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m:14:9: 'fishhook/fishhook.h' file not found"`
But the app still runs and works with core IOS maps.

react-native-cli: 2.0.1
react-native: 0.49.0
react-native-maps: 0.16.4

**Comment by lucasbento** [comment]
@Nizarius: this is not related to react-native-maps at all, it was a small problem on react-native `0.49.0`, `0.49.1`+ fixes this issue with the PR https://github.com/facebook/react-native/pull/16192.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
