### ISSUE TITLE
Google Maps API Key security

### ISSUE THREAD

**Issue by zwiebelspaetzle** [react-community/react-native-maps#1682]
The installation instructions say to store the Google Maps API Key in `android\app\src\main\AndroidManifest.xml`.  Does that not create a security issue where users could extract the key from your app?  What is a secure way to handle this?

Sources:
https://rammic.github.io/2015/07/28/hiding-secrets-in-android-apps/
(related) https://developers.facebook.com/docs/facebook-login/security#appsecret

**Comment by jeveloper** [comment]
There is another way of protecting access to your API key , its called fingerprinting , essentially encryption so that only particular app is signed to connect to their APIs

**Comment by alvelig** [comment]
That's not related to the library. See GoogleMaps Android SDK docs, please
