### ISSUE TITLE
Could not read path ...

### ISSUE THREAD

**Issue by ahmedraza11** [react-community/react-native-maps#1683]
C:\Users\AhmedRazas\ReactNativeProjects\EventApp>react-native run-android
Scanning 603 folders for symlinks in C:\Users\AhmedRazas\ReactNativeProjects\Eve
ntApp\node_modules (144ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat install
Debug)...
To honour the JVM settings for this build a new JVM will be forked. Please consi
der using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.htm
l.
Observed package id 'build-tools;26.0.0-rc2' in inconsistent location 'C:\Progra
m Files (x86)\Android\android-sdk\build-tools\26.0.0-preview' (Expected 'C:\Prog
ram Files (x86)\Android\android-sdk\build-tools\26.0.0-rc2')
Observed package id 'build-tools;26.0.0-rc2' in inconsistent location 'C:\Progra
m Files (x86)\Android\android-sdk\build-tools\26.0.0-preview' (Expected 'C:\Prog
ram Files (x86)\Android\android-sdk\build-tools\26.0.0-rc2')
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-maps:preBuild UP-TO-DATE
:react-native-maps:preReleaseBuild UP-TO-DATE
:react-native-maps:checkReleaseManifest
:react-native-maps:preDebugAndroidTestBuild UP-TO-DATE
:react-native-maps:preDebugBuild UP-TO-DATE
:react-native-maps:preDebugUnitTestBuild UP-TO-DATE
:react-native-maps:preReleaseUnitTestBuild UP-TO-DATE
:react-native-maps:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportSupportV42400Library UP-TO-DATE
:react-native-maps:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Li
brary UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DAT
E
:react-native-maps:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-
DATE
:react-native-maps:prepareComFacebookReactReactNative0484Library UP-TO-DATE
:react-native-maps:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBase1024Library UP-TO-D
ATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBasement1024Library UP-
TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesMaps1024Library UP-TO-D
ATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesTasks1024Library UP-TO-
DATE
:react-native-maps:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-maps:prepareReleaseDependencies
:react-native-maps:compileReleaseAidl UP-TO-DATE
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:compileLint UP-TO-DATE
:react-native-maps:copyReleaseLint UP-TO-DATE
:react-native-maps:compileReleaseRenderscript UP-TO-DATE
:react-native-maps:generateReleaseBuildConfig

FAILURE: Build failed with an exception.

* What went wrong:
Could not read path 'C:\Users\AhmedRazas\ReactNativeProjects\EventApp\node_modul
es\react-native-maps\lib\android\build\generated\source\buildConfig\release\com\
airbnb\android\react\maps'.
> C:\Users\AhmedRazas\ReactNativeProjects\EventApp\node_modules\react-native-map
s\lib\android\build\generated\source\buildConfig\release\com\airbnb\android\reac
t\maps

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 36.649 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

I am using Windows Machine

**Comment by jeveloper** [comment]
Besides suggesting " Don't use windows " go for mac or linux  :)  

I see that you might be using Android Studio 3 beta ? I would not recommend using it.
The current build tools version is 26.0.2 so it could be an issue of your local dev tools installation

**Comment by Benzner** [comment]
Did't you solve this problem ? @ahmedraza11

**Comment by jeveloper** [comment]
Awesome :) 

Prepare to migrate to gradle 4.3 and you'll have to change gradle file too :)  

the nice thing is you'll then be able to remove build tools version
