### ISSUE TITLE
Edit existing polygons?

### ISSUE THREAD

**Issue by Bassonlinho** [react-community/react-native-maps#1685]
Hello I've been using your component for some time now and I'm very grateful for your work.
However I've got a question for you:
Is it possible to edit drawn polygons? Like drag the points of polygon to reshape it or something?
Thanks in advance!
Kind regards

**Comment by Bassonlinho** [comment]
If anyone wondering, I've did it with Draggable Markers.
 {this.state.editing && this.state.editing.coordinates &&
 (this.state.editing.coordinates.map((coordinate, index) => (
  <MapView.Marker draggable
   coordinate={coordinate}
   onDragEnd={(e) => this.changeCoordinate(e, index)}
   />
 )))}

and the function:
  changeCoordinate(e, index) {
    let newCoord = e.nativeEvent.coordinate;
    let newEditing = Object.assign({},this.state.editing);
    let newCoordinates = Object.assign({},newEditing.coordinates);
    newCoordinates[index] = newCoord;
    newEditing.coordinates = newCoordinates;   
    let transformedCoords = Object.keys(newEditing.coordinates).map(function (key) { return newEditing.coordinates[key]; }); 
    newEditing.coordinates = transformedCoords;
    this.setState({
      editing: newEditing
    })
  }

**Comment by pawan8525** [comment]
Mr. Nemanja Ristic  i tried but not success  i am confused at "this.state.editing"  from where it take value please  share full example.
Thank you for your kind cooperation.

**Comment by Bassonlinho** [comment]
Hey, my setup is the same like in the example of PolygonCreator(https://github.com/react-community/react-native-maps/blob/master/example/examples/PolygonCreator.js). In place where they do this(line 144-153):
         {this.state.editing && (
            <Polygon
              key={this.state.editing.id}
              coordinates={this.state.editing.coordinates}
              holes={this.state.editing.holes}
              strokeColor="#000"
              fillColor="rgba(255,0,0,0.5)"
              strokeWidth={1}
            />
)}
I added below it: 
{this.state.editing && (
            <MapView.Polygon
              key={this.state.editing.coordinates}
              coordinates={this.state.editing.coordinates}
              strokeColor="rgb(0,100,0)"
              fillColor="rgb(0,100,0)"
              strokeWidth={3}
            />
          )}
          {this.state.editing && this.state.editing.coordinates &&
            (this.state.editing.coordinates.map((coordinate, index) => (
              <MapView.Marker draggable
                key={index}
                coordinate={coordinate}
                anchor={{ x: 0.5, y: 0.5 }}
                onDragEnd={(e) => this.changeCoordinate(e, index)}>
                {dot}
              </MapView.Marker>
            )))}

And then the function : 
changeCoordinate(e, index) {
let newCoord = e.nativeEvent.coordinate;
let newEditing = Object.assign({},this.state.editing);
let newCoordinates = Object.assign({},newEditing.coordinates);
newCoordinates[index] = newCoord;
newEditing.coordinates = newCoordinates;
let transformedCoords = Object.keys(newEditing.coordinates).map(function (key) { return newEditing.coordinates[key]; });
newEditing.coordinates = transformedCoords;
this.setState({
editing: newEditing
})
}

Editing is from state which refers to coordinates as you draw points of your polygon. Hope I helped :)

**Comment by pawan8525** [comment]
Thanks you much Mr.Nemanja Ristic  ,problem resolved and  now i am moving ahead in my project and have one doubt
is It possible to overlay a map with another map  in react-native-map? 
I found image can overlay on  map (https://github.com/react-community/react-native-maps/blob/master/docs/overlay.md)
but my problem is  that i want to overlay react-native-map with third party map that will draw soil map on same map on toggle button. I also attached screen shot what i want, please help.
"Map with overlay"

![image](https://user-images.githubusercontent.com/38987561/39715019-751046f4-5249-11e8-9b67-18503ae17baa.png)

"Map without overlay"
![image](https://user-images.githubusercontent.com/38987561/39715097-c0f21caa-5249-11e8-906f-cff917d8e910.png)

once again thanks

**Comment by Bassonlinho** [comment]
Hey mate, that I would not know. You'd need to open a new issue for that. Haven't really tried overlays so for that you'd need someone experienced. But you could do conditional rendering with some boolean to toggle on/off the overlay if it fits the entire map.

**Comment by Bassonlinho** [comment]
I was looking for that too but no luck. I think you'd need to use some algorithm or 3rd party lib that would give you geometry of point in middle so that it can be dynamically added. Open new issue for that, I'm closing this down, cheers mate! :+1:

**Comment by claysol-pardeep** [comment]
Hi @Bassonlinho 

There has anyways to draw the polygon with fill colors like on the web we have this feature,

https://codepen.io/mdashikar/pen/gvMpXK?editors=1010
Circle,Rectangle, Polygon etc etc
