### ISSUE TITLE
Unique Key but , Warning each child in an array or iterator should have a unique "key" prop 

### ISSUE THREAD

**Issue by rainbowhat** [react-community/react-native-maps#1686]
```
{this.state.markerList.map(marker => (
				    <MapView.Marker
				      key={marker.id}
				      coordinate={{latitude:marker.latitude,longitude:marker.longitude}}>
				      <MapView.Callout>
		              <View>
		                <Text>ID : {marker.id}</Text>
		              </View>
		            </MapView.Callout>
				    </MapView.Marker>
				    
				  ))}
```

I've checked for duplicate Marker & the id by doing a call out but for some reason i'm still getting the error 
Warning each child in an array or iterator should have a unique "key" prop. 

BUT when i replace the unique key with latitude, the warning is gone.... uh????? whats going on ? Is this unique key interfering with my other screens or what?

**Comment by IjzerenHein** [comment]
The error comes from React and it should not be possible that it interferes with another screen. You most likely are indeed using a duplicate key, perhaps the key is `undefined`. I would double check that and even log it to the console to verify.

**Comment by lailaZayani** [comment]
for any looking for a solution: 
 <Marker
                            key={marker.key}
                            coordinate={marker.coordinates}
                            title={'hi'}
                            description={'hello'}
                        />

**Comment by LeviPhantom** [comment]
This doesn't work for me. it only render 1 marker. I use the same code as you lailaZayani
