### ISSUE TITLE
showing two tiles when i am using custom map tile ...

### ISSUE THREAD

**Issue by anujsinghwd** [react-community/react-native-maps#1688]
if i am using custom map tile url then it is showing two tiles one google map tile and one url tile ..
**i am using this code for cutom map tile**
`https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js`

<MapView 
  region={this.state.region}
  onRegionChange={this.onRegionChange}
>
  <MapView.UrlTile

    urlTemplate={this.state.urlTemplate}
  />
</MapView>

**Comment by davidroman0O** [comment]
I got the same problem on Android!

**Comment by alvelig** [comment]
Merging to #1880

**Comment by pawan8525** [comment]
hi i am using below url of soil map tile
<MapView.UrlTile
urlTemplate=" ....../api/soil/wms/?x=5458&y=12859&z=15 " />

in x,y i pass converted lat long and in z i pass zoom level.
But my map overlay tile repeat, why i don't know?
Please help
