### ISSUE TITLE
AirGoogleMapManager on RN 49.3

### ISSUE THREAD

**Issue by anhtuank7c** [react-community/react-native-maps#1690]
Warning message

```
RCTLog.js:48 Module AIRGoogleMapManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

OS: Mac 10.13 Sierra
Xcode: 9
Simulator: Iphone 8
RN: 0.49.3
Maps: 0.16.2

![screen shot 2017-10-10 at 1 34 40 am](https://user-images.githubusercontent.com/3163410/31353047-39c966f4-ad5b-11e7-8c4a-4b16924e115e.png)

**Comment by Palisand** [comment]
@christopherdro

Can this warning safely be ignored?

Will ignoring this lead to issues with `react-native-maps` and future RN releases?!

**Comment by rhysgoehring** [comment]
Im getting this same warning but on macOS High Sierra, xcode 9.2, rn 0.51.0, and react-native-maps 0.18.3. Any one have a fix for this?

**Comment by rborn** [comment]
This PR seems to be merged in master but somehow the code is missing https://github.com/react-community/react-native-maps/pull/1746

cc: @gpeal, @christopherdro , @alvelig   😊

**Comment by danielgindi** [comment]
Sorry guys I was in a short vacation...
Yes that was not deleted intentionally!

**Comment by alvelig** [comment]
No problem. Already fixed.
