### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-community/react-native-maps#1691]
I've followed the step 4 times now trying to get the google maps support into the ios side of my app and every single time I end up with error. 
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Has anyone been able to get passed this?

I'm following option 2 for ios at this link https://github.com/airbnb/react-native-maps/blob/1e71a21f39e7b88554852951f773c731c94680c9/docs/installation.md#ios

**Comment by codesinghanoop** [comment]
I think this will help you [issue 718](https://github.com/airbnb/react-native-maps/issues/718)

**Comment by RyanMitchellWilson** [comment]
I found an article that has step by step instructions that work really well and are easy to understand. https://medium.com/@kswanie21/react-native-google-map-with-react-native-maps-572e3d3eee14

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by cchamikara** [comment]
First of all, in “Project Navigator” choose project “YourProjectName”. After, open section “Link Binary With Libraries” under “Build Phases”. Delete “libAirMaps.a” in the list, and try to rebuild project again.
