### ISSUE TITLE
The example isn't working

### ISSUE THREAD

**Issue by jegumhon** [react-community/react-native-maps#1692]
I'm trying to run the example.
But running the example shows an error like this..
<img width="1142" alt="2017-10-10 6 27 01" src="https://user-images.githubusercontent.com/6110163/31379227-a7845680-ade8-11e7-8ee1-eaba4a55e478.png">

I followed the [example setup guide](https://github.com/airbnb/react-native-maps/blob/master/docs/examples-setup.md)

How can I fix or avoid this error case?

**Comment by kelset** [comment]
It looks like you haven't properly linked the library; moreover, that example is really really old, I suggest you try looking at the [installation guide](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md) instead.

**Comment by jegumhon** [comment]
@kelset Thank u!! I'll consider your suggestion!!

**Comment by compojoom** [comment]
@kelset - how are we supposed to link the library? Can we improve the docs?

In my case I have rn maps working in my project, but I stumbled on and I'm trying to reproduce it in the example. 

The example should be working... If it is not and we don't plan on supporting it, then we have to remove it.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
