### ISSUE TITLE
Put the google map API Key IOS ? 

### ISSUE THREAD

**Issue by BlackStef** [react-community/react-native-maps#1693]
Hi, I have a problem. 
Impossible for me to put my google map API key, when I try to import googleMap in appdelegate.m he don't reconise it. 

So I can't put my google map API key, but I've tried to build without the key and... It work ! 
I have the map displayed on my IOS simulator, but without any key... So it seem not very stable. 

In fact, in the tutorial at the IOS part (manual installation) there is no key setup information. Only with pods ! 

Does someone know the problem ? Maybe an update ?

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by BlackStef** [comment]
I don't use Pods, and I have a working google maps without any API key on IOS. 
That's strange

**Comment by alvelig** [comment]
@BlackStef share an image. I suppose your google maps are not google.
