### ISSUE TITLE
Map Marker onPress issues

### ISSUE THREAD

**Issue by jmhuret** [react-community/react-native-maps#1695]
I've noticed two issues reported where there are problems related to onPress events for map markers. 

First: There is a noticeable delay from the time a marker is touched to the time the action is taken. [833](https://github.com/airbnb/react-native-maps/issues/833)

Second: You can't seem to use touchable components as part of custom map marker code. [403](https://github.com/airbnb/react-native-maps/issues/403)
I've tried this a few different ways and can't seem to nail down a working solution.

I'd like to have actions taken from pressing the map markers to happen "immediately". Does anyone know of a way to make this happen?

**Comment by marano** [comment]
I've noticed theses issue when trying to use `TouchableHighlight` and `onPress` inside the marker, they won't work :(

I've also found that disabling zoom will make the actions to trigger immediately, it seems to be caused by the double tap to zoom capture as mentioned on the other thread.

**Comment by alvelig** [comment]
#833 will be tracked there (but it seems your performance issue)
#1556 for custom touchables
