### ISSUE TITLE
These options may not be necessary if you ran "react-native link" -- not helpful

### ISSUE THREAD

**Issue by PatNeedham** [react-community/react-native-maps#1703]
This not a technical issue but merely a suggestion on the wording. The first quote under the [iOS Installation section](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#ios) says:

> These options may not be necessary if you ran "react-native link"

Under what scenarios would the steps be necessary, and not necessary? The "may not be" phrase is irritating because to me it implies there is no certainty and that the answer depends on other factors as well (maybe operating system, react-native version, npm version, etc.).

Can it be changed to:

> These options are not necessary if you ran "react-native link"

**Comment by alvelig** [comment]
If you don't want to use GoogleMaps on iOS then 
```
npm i -S react-native-maps
react-native link 
```
Are enough to work.
