### ISSUE TITLE
[IOS] Map is changing region on load

### ISSUE THREAD

**Issue by apekatten** [react-community/react-native-maps#1704]
I have this really weird bug, almost everytime I start my app (the map is the first screen) it zoomes out and changes coordinates. If I'm very quick and accomplish to move the map before the markers are loaded the map wont move. All what I describe below is completely without touching the screen.

There is no issue on Android, that works perfectly as you can see in the attached logs. AppleMaps are also worse than GoogleMaps.

The logs are created with the following code, initial state is working like a charm, but for some reason the map moves by itself. In the code currently running I am just logging the `onRegionChange` thus the map will not move and the last coordinates logged are the initial ones from the reducer.

### MapScreen.js
```
onMapRegionChange(region) {
  console.log("Map region changed!")
  console.log(region)
  //this.props.mapRegionChanged(region)
}

componentDidMount() {
  console.log('Rendered and showed MapScreen')
}

render() {
  const {navigate} = this.props.navigation
  console.log("Rendering mapView")
  console.log(this.props.region)
  // Region is correct here
  return (
    <MapView
      provider={null} // or "google"
      region={this.props.region}
      style={styles.map}
      onRegionChange={this.onMapRegionChange.bind(this)}
      ref = {(ref)=>mapView=ref}
    >
      {
        this.state.venues.map(venue => (
          <MapView.Marker
            coordinate={venue.location}
            key={venue.id}
            onPress={() => navigate('VenueDetailsScreen', { id: venue.id, name: venue.name })}
          >
            <LocationMarker logo={venue.logo} display={venue.display} />
          </MapView.Marker>
        ))
      }
    </MapView>
  )
}
```

### MapReducer.js
```
export default (state = INITIAL_STATE, action) => {
  console.log("MapReducer starting")
  switch (action.type) {
    case MAP_REGION_CHANGED:
      return action.payload
    default:
      return state
  }
}
```

## Environment
I have tried updating to the newest version 1.17.0 and still have the same problem. I have been using react-native-maps-clustering, but not currently. Below are my dependencies:
 - react@16.0.0-alpha.12
 - react-native@0.48.4
 - react-native-maps@0.17.0
 - react-native-map-clustering@1.1.6 (attached logs are without clustering)
 - redux@3.7.2
 - react-redux@5.0.6
 - redux-logger@3.0.6
 - redux-thunk@2.2.0
 - react-navigation@1.0.0-beta.13

**Disclaimer:** I'm a n00b to React Native but have coded other stuff, there is a possibility that I have missed something. However I feel pretty comfortable this being a bug... All good ideas and solutions are welcome. Thanks!

## Logs
Android is working as expected
[android.txt](https://github.com/airbnb/react-native-maps/files/1385898/android.txt)
It even works on IOS with GoogleMaps 4 out of 20 times (just tried 20 times)
[ios-google_no-error.txt](https://github.com/airbnb/react-native-maps/files/1385901/ios-google_no-error.txt)
Here you can see the error on GoogleMaps on IOS (Line 21-29)
[ios-google.txt](https://github.com/airbnb/react-native-maps/files/1385900/ios-google.txt)
The worst is using AppleMaps (Line 21-56)
[ios-apple.txt](https://github.com/airbnb/react-native-maps/files/1385899/ios-apple.txt)

**Comment by kardolus** [comment]
Setting the initialRegion rather than the region in your MapView is what fixed this for me, you may also want to look at:

https://github.com/airbnb/react-native-maps/issues/846
https://github.com/airbnb/react-native-maps/issues/919

**Comment by apekatten** [comment]
Thanks for your reply @kardolus, setting initialRegion does not work when using clustering and/or react-redux.
Using onRegionChangeComplete is not possible as react-native-map-clustering overwrites it.

I find many issues for Adroid, but for me it's just IOS.

**Comment by kardolus** [comment]
@apekatten ah gotcha. Haven't tried react-native-maps with react-redux. Using plain redux instead.

**Comment by alvelig** [comment]
Let me know if this example does not help: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by Balasnest** [comment]
Facing this exact issue. Not working in iOS. But works in android. (#209 doesn't help)

@kardolus Did you get it to work?
