### ISSUE TITLE
Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

### ISSUE THREAD

**Issue by bevss** [react-community/react-native-maps#1708]
Installing react-native-maps and linking it to android dependency is successful. However, it throws an error.

```
$ react-native link react-native-maps
rnpm-install info Linking react-native-maps android dependency 
rnpm-install info Android module react-native-maps has been successfully linked 
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.
```

react-native-cli: 2.0.1
react-native: 0.41.2

Thank you.

**Comment by alvelig** [comment]
clean node_modules and update to latest version.

**Comment by percivalruiz-bibo** [comment]
Have you tried doing `react-native upgrade` before `react-native link`? That worked for me.

**Comment by hazeeb** [comment]
Please do manual link.

**Comment by 91ranjan** [comment]
Check your project.pbxproj file in my case there were merge conflicts which was showing "<<<<<<"

**Comment by AliRadmanesh** [comment]
As @91ranjan said check All of your files that has been changed since the last commit you have.
It's because of the merge conflicts that adds some "<<<<<" lines to your code.
resolving them would perfectly solve my problem!
