### ISSUE TITLE
longitudeDelta doesn't change it's value after onRegionChangeComplete

### ISSUE THREAD

**Issue by Tom29** [react-community/react-native-maps#1712]
I'm using Google Maps and i want to get viewport region after changing, latitudeDelta changes, but longtitudeDelta isn't.

react-native-maps: 0.16.4
react-native: 0.44.0

<img width="991" alt="screen shot 2017-10-18 at 4 29 45 pm" src="https://user-images.githubusercontent.com/5781080/31711909-cf9a2a78-b423-11e7-9fbd-9b18a2184b60.png">

**Comment by alvelig** [comment]
Please fill your issue according to the new issue template. We need a minimal reproducible example. We'll reopen then.
