### ISSUE TITLE
Image nested in MapView.Marker not rendering on Android

### ISSUE THREAD

**Issue by GregorioDiStefano** [react-community/react-native-maps#1723]
According to other issues, it should be straight forward to nest an ```Image``` into ```MapView.Marker```, and specify a style, however, it seems that doing so is rendering no image at all:

See the following snippet:

```
        <MapView.Marker coordinate={{latitude: 59.91491231, longitude: 10.77010}} title={"title"}>
            <Image source={require('./res/img/BIG_pin_yellow_map_ico.png')} style={{ width: 70, height: 90}}/>
         </MapView.Marker>
```

This is using the latest react-native and react-native-maps

**Comment by HsanBenJobrane** [comment]
+1

**Comment by socar-dorma** [comment]
I thing same issue...

In my case. 
I use custom marker icon + text.

```
<MapView.Marker
        identifier={_.toString(marker.id)}
        key={marker.id}
        title={marker.title}
        coordinate={marker.coords}
        description={marker.description}
        image={MarkerIcon}
        onPress={() => this.onMarkerPress(marker)}
        ref={ref => _.assign({}, marker, { ref })}
      >
        <View style={styles.markerContainer}>
          <Text style={styles.markerText}>{marker.ableCount}</Text>
        </View>
      </MapView.Marker>
```
The first render normally displays the text.
But. If the marker data is updated and render is called again, the image(`MarkerIcon`) is displayed but the text(`marker.ableCount`) is not displayed.

**Comment by susan-github** [comment]
@socar-dorma do you find any solutions?

**Comment by socar-dorma** [comment]
@susan-github 
I don't think this is the right way.... but it work.

re-render <MapView> when every time markers change.
But, react should be re-rendered only if the virtual-dom hierarchy has changed.


```

class MyMapView extends Component {
  constructor(props) {
    super(props);
    this.state = {
      toggle: 0,
    };
  }

  componentWillReceiveProps(nextProps) {
    const { toggle } = this.state;
    const prevMarkers = this.props.markers;
    const { markers } = nextProps;

    const prevHead = _.head(prevMarkers) || {};
    const head = _.head(markers) || {};
    if (_.size(prevMarkers) !== _.size(markers) // check marker changed..
    || (_.isEmpty(prevHead) !== _.isEmpty(head))
    || (prevHead.id !== head.id)) {
      this.setState(() => ({ toggle: (toggle === 1 ? 0 : 1) }));
    }
  }

  renderMarkers() {
    const { markers } = this.props;

    if (_.size(markers) === 0) return null;
    return _.map(markers, marker => (
      <MapView.Marker
        title={marker.title}
        coordinate={marker.coords}
        ....
      >
        <View style={styles.markerContainer}>
          <Text style={styles.markerText}>{...}</Text>
        </View>
      </MapView.Marker>
    ));
  }

  render() {
    const { toggle } = this.state;

    if (toggle === 0 && Device.isAndroid) {
      return (
        <MapView
          provider={MapView.PROVIDER_GOOGLE}
          ....
        >
          {this.renderMarkers()}
        </MapView>
      );
    }
    return (
      <View>
        <MapView
          provider={MapView.PROVIDER_GOOGLE}
          ....
        >
          {this.renderMarkers()}
        </MapView>
      </View>
    );
  }
}
```

**Comment by DiMaNacho** [comment]
Same problem here!

**Comment by alvelig** [comment]
Merging to #1870

**Comment by malik-sahab** [comment]
Same issue. Any solutions?

**Comment by AnjuBaby694** [comment]
same issues ,custom image markers are not showing on android 7+ versions :( frustrated.

**Comment by HKH515** [comment]
same

**Comment by rupalpatel0008** [comment]
I am also having same issue. Image component inside <Marker> does not render in android.

**Comment by fcabrera23** [comment]
Im having the same issue

<MapView.Marker
              coordinate={{
                latitude: marker.latitude,
                longitude: marker.longitude
              }}
              key={i}
              onPress={(e) => { e.stopPropagation(); this.onMarkerPress(marker); }}
            >
              <Image source={GetTractorIcon(marker.marker)} style={{width: 40, height: 40}} />
              <MapView.Callout style={{ flex: -1, position: 'absolute', width:220}}
                onSelect={() => this.goToDetailsTruck(marker)}
                onPress={() => this.goToDetailsTruck(marker)}
              >
                <CustomCallout marker={marker} />
              </MapView.Callout>
            </MapView.Marker>

**Comment by toyah** [comment]
same, custom image markers not showing on android > 7

**Comment by MusicianHub** [comment]
Very annoying, same problem

**Comment by toyah** [comment]
A solution for it
Use react-native-svg. Transform your icon (png, ...) to svg in first

**Comment by alvelig** [comment]
Guys, see #1870
