### ISSUE TITLE
The problem of calculating the distance between 2 points A to B (Lat, Long) too slow

### ISSUE THREAD

**Issue by Ollie-NTP** [react-community/react-native-maps#1738]
Hellow, 
I installed react-native-maps, I created a showMyLocation () method (A point) on a iOS device, if I choose a random point (B point) on the map then I want to defend my point of point, the coached coordinate is too slow, android runs very good, any suggestion? thank you beautifully, I expect a response.

**Comment by tonygentilcore** [comment]
Not sure I fully understand your question, but I've been using https://github.com/manuelbieh/Geolib in conjunction with this library to do various distance calculations. It has multiple levels of accuracy with different perf tradeoffs. For example: https://github.com/manuelbieh/Geolib#geolibgetdistancesimpleobject-start-object-end-int-accuracy

**Comment by alvelig** [comment]
Cmd + T (Slow animations). As far as I understood it refers to transitions.

**Comment by Manoj002** [comment]
@tonygentilcore, can you give a small example on this example: https://github.com/manuelbieh/Geolib#geolibgetdistancesimpleobject-start-object-end-int-accuracy.

I mean this is a react package and how do i use it in react native
