### ISSUE TITLE
Problems with google maps on iOS

### ISSUE THREAD

**Issue by rom1k** [react-community/react-native-maps#1739]
I have been stuck for days on this now. I'm using react-native **0.49.3** and react-native-maps **0.17.1**, the project is quite large but is freshly initialised at this version and not upgraded.

I have tried different ways of linking react-native-maps but there is always some problem on iOS. If I fix one problem by linking differently it will lead to another problem instead. I will try to summarise the problems below.

**(First method of linking)** 
Podfile looks like below and I drag the AirGoogleMaps dir manually to xcode and add the path to Header Search Path in build settings.

This is the closest I get to it working. Building the app for simulator works, the map component works as it should but when I try to archive (build for ad hoc/release) in xcode. I get 400+ duplicate symbol errors. I can build and run it in the simulator with react-native run-ios --configuration Release, but that's useless for production. I have searched specifically for the duplicate errors but none of the solutions posted seems to work. [This fix removed the duplicate errors but the app just launched with a blank white screen](https://github.com/airbnb/react-native-maps/issues/718#issuecomment-257476236)

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 
  pod 'React', path: '../node_modules/react-native', :subspecs => [    
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
    ]

    pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
    pod 'react-native-maps', path: '../node_modules/react-native-maps/'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'
    
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "react-native-google-maps"
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
  end
end


```

**(Second linking method)**
I linked in the same way as this guide
https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14
I can archive the app (build for release) in xcode with no errors but when I open it I get this error "AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on IOS".

This is a list of all the dependencies I'm using
```
"dependencies": {
    "axios": "^0.16.2",
    "deep-equal": "^1.0.1",
    "react": "16.0.0-beta.5",
    "react-moment-proptypes": "^1.5.0",
    "react-native": "0.49.3",
    "react-native-action-button": "^2.8.0",
    "react-native-animatable": "^1.2.4",
    "react-native-cached-image": "github:kfiroo/react-native-cached-image#pull/64/head",
    "react-native-chooser": "^1.6.3",
    "react-native-country-picker-modal": "git+https://github.com/xcarpentier/react-native-country-picker-modal.git#673c1e6e8abab0768785aec33c63aec86840c1a9",
    "react-native-datepicker": "^1.6.0",
    "react-native-elements": "^0.17.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-gifted-chat": "^0.2.9",
    "react-native-google-places": "^2.4.2",
    "react-native-i18n": "git+https://github.com/AlexanderZaytsev/react-native-i18n.git#5b1a37aef",
    "react-native-image-picker": "^0.26.7",
    "react-native-maps": "0.17.1",
    "react-native-modal-wrapper": "^3.0.0",
    "react-native-popup-dialog": "^0.9.36",
    "react-native-progress": "^3.4.0",
    "react-native-push-notification": "^3.0.1",
    "react-native-simple-toast": "0.0.7",
    "react-native-tag-input": "0.0.17",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.15",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-persist": "^4.10.1",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "tcomb-form-native": "^0.6.11"
  },
```

Of course I could try it on a blank project but that's irrelevant, I'm not working on a blank project. If this is an issue only in a non-blank project, does anyone have any idea what can cause this? Are there any old paths, flags or whatever in some hidden xcode files that messes it up and needs to be cleared? I have tried unlinking, linking again, unlinking, manually linking again. Nothing seems to work.

**Comment by davidhellsing** [comment]
Did you add `AirMaps.xcodeproj` to the `Libraries` folder in xcode?

<img width="172" alt="screen shot 2017-10-30 at 12 07 19" src="https://user-images.githubusercontent.com/329348/32167964-fa340ff6-bd6a-11e7-8157-89f2cbd8b080.png">

**Comment by mehdijjz** [comment]
@davidhellsing Resources ? where is that ?

**Comment by ghoshabhi** [comment]
@mehdijjz: Open the `{ProjectName}.xcworkspace` file in Xcode. There you should see the folders mentioned by @davidhellsing.

You need to do two things:
1) Add the `AirMaps.xcodeproj` directory to the `Libraries` directory in xcode. `AirMaps.xcodeproj` is located in `node_modules/react-native-maps/lib/ios/`.

2) Drag the `AirGoogleMaps directory from the same path mentioned above and drop it inside the root of your folder in xcode.

Hope this helps!

**Comment by SZanetti** [comment]
I have the exact same problem, react-native **0.48.2** and react-native-maps **0.16.0**.

I've ensured that `AirMaps.xcodeproj` in in the Libraries directory and that `AirGoogleMaps` is in the root of my xcode project, but the problem persists.

**Comment by kamrancode** [comment]
I have the same problem with RN 0.49.3 and map v0.17.1 here!
@davidhellsing  and @mehdijjz I tried your way but still I get AirGoogleMaps dir must be added to your project...

**Comment by rom1k** [comment]
I gave up and ended up using MapKit. Developing for iOS is already too time consuming and too expensive with provisioning profiles, certificates, weird xcode bugs and all that bullshit. :)

**Comment by kamrancode** [comment]
I make it work by following steps
1: I used @rom1k podfile
2: removed ```libAirMaps.a``` from build phase
3: add ```$(SRCROOT)/Pods``` (recursive) to framework search paths
4: add ```$(SRCROOT)/../node_modules/react-native-maps/lib/ios``` and  ```$(SRCROOT)/../node_modules/react-native-maps/ios/AirMaps``` to header search paths

and now its working even in production build without any duplicates

**Comment by SZanetti** [comment]
@kamrancode By "@rom1k podfile," you mean the Podfile including all the `RCT...` subspecs? Because that is what is causing the duplicate issue for me. It is NOT a duplicate symbol issue with AirMaps itself. 

The problem is that doing the Podfile this way includes the `RCT...` , but I also have them included in `Libraries`. I can't un-link the `Libraries`, though, because then none of the modules (`Image`, etc.) from react-native will load.

This is what I get:
`duplicate symbol _OBJC_CLASS_$_RCTLinkingManager in:
    [root]/libReact.a(RCTLinkingManager.o)
    [root]/libRCTLinking.a(RCTLinkingManager.o)
...
duplicate symbol _OBJC_CLASS_$_RCTSettingsManager in:
    [root]/libReact.a(RCTSettingsManager.o)
    [root]/libRCTSettings.a(RCTSettingsManager.o)
...
ld: 432 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by SZanetti** [comment]
Alright, there's two solutions (one for each of the original problems).

If you are using the first method of linking and are experiencing `duplicate symbol` errors, you need to add this to your Podfile (as described in the solution here https://stackoverflow.com/questions/42021796/react-native-xcode-project-product-archive-fails-with-duplicate-symbols-for-arch):
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end`

If you are using the second method of linking, likely what has happened is that even though you added GoogleMaps to your xcode project, none of the GoogleMaps files got included in `Compile Sources`. For this solution, open xcode, go to the `Build Phases` section, and look under `Compile Sources`. If any of the `.m` files from AirGoogleMaps are not here, add them.

Note that if you are on react-native version >=0.48, then you will also need to include `DevSupport` in your Podfile, as this is no longer included in xcode. This will cause a duplicate symbol error if you do not have the code from the first solution.

Hope this helps.

**Comment by kamrancode** [comment]
@SZanetti I met all your problems
at the end I decided unlink react-native maps and ```rm -rf /node_modules``` then using yarn again installed all those modules again using ```yarn``` 
which removed my duplicate symbols problems
then I used ```react-native link```
then I could build my project with ```AirGoogleMaps should be in dir...``` problem
so I put these in my podfile
```

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 
  pod 'React', path: '../node_modules/react-native', :subspecs => [    
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
    ]

    pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
    pod 'react-native-maps', path: '../node_modules/react-native-maps/'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "react-native-google-maps"
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
  end
end

```
then dragged AirGoogleMaps to my project root and fixed those 4 steps above and its worked!
I dont know how but it did!

**Comment by mtimofiiv** [comment]
I found that there are currently like half a dozen different sets of instructions to make this work. I wonder, is it possible to re-write the install instructions to have the latest updated version?

**Comment by smith64fx** [comment]
I also tried several instructions, but each causes other errors :( really frustrating.

I also wished if there would be install instructions for the current version.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
