### ISSUE TITLE
Unable to use "animateToBearing" nor "animateToViewingAngle"

### ISSUE THREAD

**Issue by echap** [react-community/react-native-maps#1743]
Hi everybody,

I'm trying to animate a map with the poperties  "animateToBearing" and "animateToViewingAngle",  but I have the following message in both cases : 

```
TypeError: undefined is not an object (evaluating 'this._mapManagerCommand(name).apply')
```

Here is my rendering :
```
<MapView
                            initialRegion={{
                                latitude: this.state.mapRequirements.mapBounds.center.lat,
                                longitude: this.state.mapRequirements.mapBounds.center.lng,
                                latitudeDelta: this.state.mapRequirements.mapBounds.deltaLat +  0.01,
                                longitudeDelta: this.state.mapRequirements.mapBounds.deltaLng + 0.01,
                            }}
                            onPress={e => this.onCoordinateTapped(e.nativeEvent)}
                            onMapReady={e => console.log("Map is ready")}
                            ref="map"
                            style={{width: '100%', height: '100%'}}
                        >

                            </MapView.Polyline>
                        </MapView>
```

And my attempts function : 

```

 devUpdatePosition(projectionEvent: ProjectionEvent) {
        this.refs.map.animateToBearing({ bearing : projectionEvent.heading, duration : 1000});

        // this.refs.map.animateToViewingAngle({ angle : 70, duration : 1000});
    }

```
I can enable one or another and the result is the same, I got the error above every time.

Using `"react-native-maps": "^0.17.1"` and expo sdk 21.`

Any clue on this ?.

**Comment by resson-ntranquilla** [comment]
I have seen the same issue, except I was handling the map `ref` differently than you are in an attempt to solve app crashing memory issue (serialising / deserialising to avoid circular references) . 

Out of curiosity, do you have the same issue if you implement your ref as:  `ref={ref=>this.map=ref}` ?

**Comment by echap** [comment]
@resson-ntranquilla I actually was going through the implementation of the PR that brought the animateToBearing, and I made this  implementation (`ref={ref=>this.map=ref}`), same issue :/

**Comment by resson-ntranquilla** [comment]
It could be that the map is not ready. Try accessing this ref inside `onMapReady`. Just a guess. I am having trouble with refs as well.

**Comment by echap** [comment]
Going deeper on my testings, with the *same basecode* on android, I got another straack trace `TypeError: expected dynamic type 'double' but had type 'null'`

**Comment by echap** [comment]
After more researches, I suspect that the reason of this failure is this one : Provided that the actual plugin works correctly (not tested yet) - the issue comes from the version of react-native-maps embedded in expo which is outdated.

Updating the version of react-native-maps with `npm i --save react-native-maps@^0.17.1` only updates the JS part of the plugin (which is totally normal). Thus, the native part is not correctly binded to the JS part of the plugin.

If anyone could confirm this to me // would be great ! :D

**Comment by echap** [comment]
AS mentionned [here](https://github.com/expo/expo/issues/890#issuecomment-341270938), I found out that the react native maps version embedded with expo is the *0.17.0* which means that animateToBearing and animateToViewingAngle should be working  within expo. (because those functions were released within 0.17.0, see [releases](https://github.com/airbnb/react-native-maps/releases). 

There's something that needs to be solved out ! Any input would be much welcomed on this !  @sandinosaso @christopherdro

**Comment by echap** [comment]
Still pending on this ! :)

**Comment by benvegel** [comment]
@echap running into the same issue here with expo and 0.17.1. 

I can get the demo code to work (for both animateToBearning and animateToViewingAngle) with the native iOS maps only, but I cannot use google maps. I get the same error as you:

 undefined is not and object (evaluating 'this._mapManagerCommand(name).apply') 

Any help is much appreciated!

**Comment by dlonli** [comment]
I read in one of thise issues a week ago (i can't remember the actually issue), and one of the devs reported that this will be fixed in the next sdk release, which will be 2 weeks from now, i think.

**Comment by dlonli** [comment]
Found it: https://github.com/expo/expo/issues/890#issuecomment-340898111

**Comment by echap** [comment]
@dlonli this is not what he’s saying, he says that expo will pull the last release of the react map sdk when they will release the expo sdk 23. Meaning that the issue is still present on this repo, it will be there in the next release.

**Comment by dlonli** [comment]
aaaah, my apologies, should have read more clearly.

**Comment by alvelig** [comment]
Likely you are not waiting for onMapReady. Comment if still experiencing that.
