### ISSUE TITLE
Image inside MapView.Callout not showing in Android

### ISSUE THREAD

**Issue by imanc** [react-community/react-native-maps#1751]
Image not visible in Android 7.1 but ok in iOS.
[http://terraautentica.whyabruzzo.com/images/android.png](http://terraautentica.whyabruzzo.com/images/android.png)

[http://terraautentica.whyabruzzo.com/images/ios.png](http://terraautentica.whyabruzzo.com/images/ios.png)

<MapView.Callout
    style={{flex: -1, position: 'absolute', minWidth:150, minHeight: 60}}
    onPress={ () => {
        this.props.navigation.navigate('Comuni', { comune: comune});
    }}
 >
   <View>
   { 'stemma' in comune.comune && 
    <Image source={ {uri: config.IMMAGINI + comune.comune.stemma.id }} 
        style={{ width: 40, height: 40, alignSelf:'center', margin: 5, backgroundColor: 'red'} }
         resizeMode='contain' />
   }
..................
 </MapView.Callout>

Someone knows what to do?
Thank you.

**Comment by MeganKurz** [comment]
+1

**Comment by alvelig** [comment]
You need to prefetch it.

**Comment by alvelig** [comment]
Set resizeMode="cover". I know that's weird, but it works.

**Comment by alvelig** [comment]
Merging to #1870

**Comment by malFuckingFurion** [comment]
Hello,
Use Image inside Text component
`<Text>
<Image style={{ height: 100, width:100 }} source={{ ... }} resizeMode="cover" />
</Text>`

**Comment by DaNiELChIoRo** [comment]
But what if I wannted the Image to be vertically center? Any solution?

**Comment by suhailkakar** [comment]
@alvelig, It is not working now
