### ISSUE TITLE
Default map is sometimes using google upon changing map tiles.

### ISSUE THREAD

**Issue by devlargs** [react-community/react-native-maps#1754]
Hi guys. I've tried changing the map tiles to openstreetmap. The initial map sometimes is using google.

Heres my code:
![image](https://user-images.githubusercontent.com/30046754/32358594-47800b92-c082-11e7-9891-b7671c5fc07e.png)

Expected result (works most of the time): 
![image](https://user-images.githubusercontent.com/30046754/32358641-c0037ba8-c082-11e7-8406-f3bad1c01101.png)

But sometimes it looks like this:
![image](https://user-images.githubusercontent.com/30046754/32358688-0c94eccc-c083-11e7-8d1b-68151747d9ae.png)

And why does the google logo is always showing on bottom (but this isnt the issue that i want to be resolved):
![image](https://user-images.githubusercontent.com/30046754/32358691-1b12c1b6-c083-11e7-9f75-8ca15d073927.png)
Suggested fix: https://github.com/airbnb/react-native-maps/issues/1239

**Comment by alvelig** [comment]
Merging to #1880

**Comment by pawan8525** [comment]
hi ,when i implement UrlTile  a white come between tile and google map so that google map not visible in react-native-map.
Please help

**Comment by software3daerospace** [comment]
How did this issue get fixed. I am facing same issue
