### ISSUE TITLE
[Bug][0.17.1] Map not moving

### ISSUE THREAD

**Issue by kesha-antonov** [react-community/react-native-maps#1756]
Hello!

After upgrade from [0.16.2] https://github.com/kesha-antonov/react-native-maps/tree/fix_fire_twice_onRegionChangeComplete

to [0.17.1] map does not respond to my tap gestures. Map not moving.

Has anyone experienced same or fixed it?

**Comment by mauron85** [comment]
Android version is fine, but having same problem in iOS Simulator iPhone 8 and iOS 11.0. Map is just static, doesn't respond to any touch or drag.

**Comment by kesha-antonov** [comment]
I've checked on oPhone real device. Map not responding

**Comment by kamrancode** [comment]
I had the same problem with iOS 11 so I had to install iOS 10.3 simulator which works fine and smooth
but I didn't try it on real device

**Comment by kesha-antonov** [comment]
We should target latest ios
I have 11 on device

**Comment by kamrancode** [comment]
@kesha-antonov It seems like it's just unusable on simulator
look at this issue https://github.com/airbnb/react-native-maps/issues/1665

**Comment by mauron85** [comment]
Can confirm. Replacing:

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/OpenGLES.framework
```

with

```
http://cl.ly/0q2k0r232o2h
```

solved issue with iOS simulator.

**Comment by alvelig** [comment]
In iOS simulator 11.2 should be fixed. Let me know if not.

**Comment by GarimaMathur07** [comment]
How can i fixed this issue on iOS 11 The map is freeze on real device and simulator. Can anyone tell the solution @alvelig @kesha-antonov

**Comment by Areeeb** [comment]
I am also facing similar kind of issue with weird behavior, when i run the project, the screen is blank, and when i navigate somewhere else and then come back, map shows up but it doesn't respond to any tap gesture. Need help....

**Comment by MaiconGilton** [comment]
Did anybody find the solution for the freezing issue on real device and simulator?
