### ISSUE TITLE
initialRegion starts zoomed out at country level and then transitions

### ISSUE THREAD

**Issue by jonching** [react-community/react-native-maps#1758]
When I open up a map view, I can see that it starts zoomed out to show the entire country and then transitions to my initialRegion immediately. It doesn't look good because you can see this flicker happening, especially when there are markers on the map that you can see moving around when the page opens.

There are times when the transition doesn't happen at all and I just see all of North America with my marker on the map. 

It seems that a lot of other people are having similar sorts of issues with initialRegion. It makes the library a bit unusable at the moment.

**Comment by xyzzyxyzzy0077** [comment]
#1338 This works as a good reference

**Comment by jsappme** [comment]
+1

**Comment by alvelig** [comment]
Try this https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
