### ISSUE TITLE
How can I use react-native-maps on android without google maps??

### ISSUE THREAD

**Issue by antontarasenko1** [react-community/react-native-maps#1764]
How can I use react-native-maps on android without google maps and without 
`<meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="test"/>`
Is it possible?
I want to use my custom openStreetMap server.

**Comment by fqborges** [comment]
I also want react-native-maps on android without google maps, but it is not possible right now.

I am working on a branch (https://github.com/fqborges/react-native-maps/tree/osmdroid), replacing google maps with osmdroid (https://github.com/osmdroid/osmdroid).

My goals are to get used to the codebase, and have a functional version using osmdroid. Then I will try to extract providers (gmaps, osmdroid) out of the main library. It seems a lot of work but I am slowly getting there.

Anyone else interested on this?

**Comment by fqborges** [comment]
related issue [https://github.com/airbnb/react-native-maps/issues/1098](url)

**Comment by fqborges** [comment]
related issue https://github.com/airbnb/react-native-maps/issues/1098

**Comment by alvelig** [comment]
Duplicate #773

**Comment by alvelig** [comment]
See #2348
