### ISSUE TITLE
duplicate symbols for architecture armv7 Error

### ISSUE THREAD

**Issue by wasa4587** [react-community/react-native-maps#1766]
I'm getting
ld: 301 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rborn** [comment]
@wasa4587 that's an installation issue, we're trying to put in place a better info for this - https://github.com/react-community/react-native-maps/issues/1862 
meanwhile you could try the instructions @alvelig put together here? https://github.com/react-community/react-native-maps/issues/1862#issuecomment-350421802 

Thanks

**Comment by alvelig** [comment]
@wasa4587 Try to build that project
https://github.com/alvelig/react-native-maps-pods-example
(or just from scratch), if it fails let me know. If it does not, rebuild your project around the working maps. (That's much easier than looking for the solution to your problem, trust me).
