### ISSUE TITLE
how can i load street view of a location inside a view ?

### ISSUE THREAD

**Issue by jpca999** [react-community/react-native-maps#1767]

**Comment by tonygentilcore** [comment]
I haven't actually done this, but I believe you'd have to wire up the Google Places API: https://developers.google.com/maps/documentation/streetview/intro

That'd let you, for example, grab the street view image for a given lat/long/heading during `MapView`'s `onPress()` event.

**Comment by alvelig** [comment]
Duplicate of #1217
