### ISSUE TITLE
Need helps, pls!

### ISSUE THREAD

**Issue by Vitkonv** [react-community/react-native-maps#1772]
Hey guys, I have a problem. When I run react-native run-android however, I get the following error:
![1](https://user-images.githubusercontent.com/33524851/32619417-8e3947b4-c59c-11e7-8203-d4ccf473e951.png)
AndriodStudio 3.0
gradle-4.3
jdk jdk1.8.0_151

**Comment by Stophface** [comment]
Why do you think this problem is related to `react-native-maps`?

Did you have an `emulator` running (a simulated Android device) when you run `react-native run-android`?

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
