### ISSUE TITLE
[Android] Out of Memory When Rendering Numerous Markers

### ISSUE THREAD

**Issue by xeoh** [react-community/react-native-maps#1775]
#### Problem
I need to render more than 100 markers with image at the same time.  Even all markers are using same image they consume N times of memory since each markers are generating icon's `Bitmap` and `BitmapDescriptor` themselves. This problem occurs both in Android and IOS.

#### Solution
I'm solving this problem only at Android for this moment([commits-WIP](https://github.com/xeoh/react-native-maps/commit/a7d7dbfee318522c641a177e99e6bca50330da06))

1. I've created static `LruCache` for storing icon's bitmap where key is there uri.
2. Moreover, It seams possible to cache Arbitrary view of Markers. So I cached child's view bitmap where key is hash of bitmap.

#### Result
Example `MultipleMarkers` is available on my commit.

- No Markers - memory usage 50.7MB
![](https://github.com/xeoh/react-native-maps/blob/raws/docs/screenshot_0_0.png?raw=true)
![](https://github.com/xeoh/react-native-maps/blob/raws/docs/screenshot_0_1.png?raw=true)

- 100 Markers - memory usage 53.14MB
![](https://github.com/xeoh/react-native-maps/blob/raws/docs/screenshot_1_0.png?raw=true)
![](https://github.com/xeoh/react-native-maps/blob/raws/docs/screenshot_1_1.png?raw=true)

### Questions
1. Is my idea reasonable?
2. How to decide LruCache size
3. `hashBitmap`(AirMapMarker.java:525) function is too slow, which makes delays on rendering markers. Any idea or solutions? (It would be perfect if we can know react component's outlook is same or not before rendering)

**Comment by alvelig** [comment]
android:largeHeap=true

**Comment by mrobidoux-pbsc** [comment]
Hello @xeoh,

Did you find a solution for optimizing the rendering of markers? I'm facing the same issues as you....

**Comment by mcmar** [comment]
@alvelig Why did you close this? `android:largeHeap=true` is a hack that causes slow performance due to longer garbage collection times. It's not acceptable to have a memory leak in your library.

@xeoh It looks like you deleted your repo fork from Github. Can you please re-introduce it or send me the commit? I'm facing the same issue and I'd be willing to fork this library and maintain it if that's needed to fix the issue.

**Comment by rborn** [comment]
@mcmar @xeoh any PR that solves this problem is more than welcome 😉
