### ISSUE TITLE
custom tiles is overlapping 

### ISSUE THREAD

**Issue by anujsinghwd** [react-community/react-native-maps#1784]
### I am using this script for adding custom tile but it is not working , it is overlapping with google maps tiles . 
```jsx
<View>
          <MapView
          style={styles.container}
            initialRegion={{
              latitude: 27.78825,
              longitude: 77.4324,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}
          >
          <MapView.UrlTile
            urlTemplate="https://mt1.mapmyindia.com/advancedmaps/v1/key/still_map/{z}/{x}/{y}.png"
            zIndex={-1}
          />
          </MapView>
      </View>
```

**Comment by davidroman0O** [comment]
I got the same problem on Android!

**Comment by alvelig** [comment]
Merging to #1880

**Comment by pawan8525** [comment]
hi i am using below url of soil map tile
<MapView.UrlTile
urlTemplate=" ....../api/soil/wms/?x=5458&y=12859&z=15 " />

in x,y i pass converted lat long and in z i pass zoom level.
But my map overlay tile repeat, why i don't know?
Please help
