### ISSUE TITLE
Needs new installation instructions

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-community/react-native-maps#1785]
I have followed the documented installation instructions multiple times now with 0 luck getting this to run. I have noticed that those docs are still talking about version 0.12 and 0.13 but the current version is 0.17.

The only way I have been able to get this to run is with this blog https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14 which is quite a bit different than what is documented.

Can this please be updated with proper instructions so it can be used?

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by alvelig** [comment]
We are working on that #1862
