### ISSUE TITLE
Can not render callout in full width

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [react-community/react-native-maps#1790]
Regarding iOS

I tried to use ```animateToCoordinate``` to centralize the map to the selected marker, but couldn't find the right way to render the callouts after the map movement is finished. This has caused the callouts to be really biased. 

Then I tried ```MapView.Animated``` and ```region.timing``` to do the same thing, but callouts are still biased of those markers near to the edge.

Is there a way out?

**Comment by alvelig** [comment]
Merge to #1872

**Comment by alvelig** [comment]
Or if I'm mistaken, can you please tell me your use case

**Comment by mafiusu** [comment]
@alvelig He has the same bug that I've wrote in this topic. https://github.com/react-community/react-native-maps/issues/1810#issuecomment-356000293

In near feature I will make a project that you can actually reproduce the problem.
