### ISSUE TITLE
Raw text cannot be used outside of a <Text> tag. Not rendering string: ''

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-community/react-native-maps#1791]
I can get the map working just fine in my app, but as soon as I try to mount a second screen with a map when one map is already mounted, I get this error. I've gone through my code multiple times and can confirm that it is not coming from my code.

Using:
react-native: 0.50.3
react-native-maps: 0.17.0

Screenshot of error:
<img width="400" alt="screen shot 2017-11-15 at 11 04 48 am" src="https://user-images.githubusercontent.com/11371200/32852349-db8a26d0-c9f4-11e7-8c71-748dcf5c34a2.png">

**Comment by alvelig** [comment]
Can you please make a project reproducing that behavior. 
https://github.com/alvelig/react-native-maps-example (No pods)
https://github.com/alvelig/react-native-maps-pods-example (Pods)
Fork any of these to reproduce please.

**Comment by alvelig** [comment]
Please fill your issue according to the new template or it will be closed. I've been waiting for 3 days for your reply.

**Comment by RyanMitchellWilson** [comment]
I currently don't have time to create a project reproducing it now. But the way to induce this is to mount a second screen with a map when you already have one mounted on the same stack. If I get some free time to create a project with this problem I will do so and post it here, but I currently just don't have time. I've gotten around this problem for now by just not letting my app have more than one map mounted at a time but it should be able to have multiple screens in the same stack each with their own map.

**Comment by kytwb** [comment]
@RyanMitchellWilson I have a project where we have multiple map mounted in the same screen, multiple map mounted in the the same navigation stack etc. and it all works just fine. We'll need to see some code or at least have additional information to be able to help you furthermore. You'd be surprised how many times "I've gone through my code multiple times and can confirm that it is not coming from my code" has been proven wrong 😅

**Comment by kytwb** [comment]
Look for this kind of things:

```
{variableWithStringValue && (
  <View/>
)}
```

And try the `!!` trick to make sure you only use booleans:

```
{!!variableWithStringValueAsBoolean && (
  <View/>
)}
```

**Comment by rborn** [comment]
@RyanMitchellWilson I'll close the issue, please comment if you have it again or feel I should have left it open. A code snippet to reproduce the issue would be really good though.

**Comment by bhavinpankanis** [comment]
Any solution to this. I am facing the same problem when i navigate to a new screen
My render code is as follows : 

render() {
        return (
            <View style={styles.container}>
                <MapView
                    style={styles.map}>

                    {this.state.mapMarkers && this.state.mapMarkers.map(marker => (
                        <MapView.Marker
                            key={marker.entity_id}
                            coordinate={marker.coordinates}>
                            <MapView.Callout onPress={() => {
                                const { navigate } = this.props.navigation;
                                navigate('formScreen')
                            }}>
                                <TouchableOpacity >
                                <Text>{marker.subject}</Text>
                                </TouchableOpacity>
                            </MapView.Callout>
                        </MapView.Marker>
                    ))}
                </MapView>
            </View>
        );
    }

**Comment by kytwb** [comment]
@bhavinpankanis your snippet is missing some code, can't find the opening `<MapView>`.  
Have you tried my suggestion above?
