### ISSUE TITLE
'MapMarker' has no propType for native prop 'AirMap.minZoomLevel' of native type 'String'

### ISSUE THREAD

**Issue by ZainaliSyed** [react-community/react-native-maps#1794]
![map error](https://user-images.githubusercontent.com/24393023/32877717-b49e102e-cac4-11e7-9a79-0a582c47a6d7.jpg)

I am Using "react-native": "0.48.3",	 "react-native-maps": "^0.15.3", 
@gpeal

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
