### ISSUE TITLE
Custom callouts not displaying on Android

### ISSUE THREAD

**Issue by jpmazza** [react-community/react-native-maps#1806]
`showCallout()` it is working on iOS but it is not working on Android. I am calling the following function inside the `onMapReady` callback:
```
    animateToRegion() {
        if (this.state.isMapReady && this.state.notificationDetailReceived) {
            const { alarmLat, alarmLng } = this.props.notificationDetail;
            const region = {
                latitude: alarmLat + 0.001209,
                longitude: alarmLng,
                latitudeDelta: 0.0041,
                longitudeDelta: 0.0021
            };
            const duration = 300;
            this.setState({ loading: false });        
            this.mapRef.animateToRegion(region, duration);
            this.marker.showCallout(); 
        }
    }
```
As you can see I am calling  `this.marker.showCallout();` in the last line of the function. The rest of the code is working nice.

iOS
<img width="268" alt="captura de pantalla 2017-11-20 a la s 23 15 55" src="https://user-images.githubusercontent.com/11351953/33052237-aa54fbba-ce4c-11e7-8756-14ef1b38d2ea.png">

Android
<img width="394" alt="captura de pantalla 2017-11-20 a la s 23 10 35" src="https://user-images.githubusercontent.com/11351953/33052241-ad224ef6-ce4c-11e7-84cb-38af8bd99d72.png">

**Comment by alvelig** [comment]
See #1872
