### ISSUE TITLE
Could not allocate java pixel ref.

### ISSUE THREAD

**Issue by matthieupinte** [react-community/react-native-maps#1811]
Hi,

I'm trying to use the last `v0.17.1` version with a lot of custom `Marker` (~1300)... but I'm experiencing an issue :

<img width="376" alt="screen shot 2017-11-21 at 4 36 33 pm" src="https://user-images.githubusercontent.com/2217014/33081874-9f3f9070-cedb-11e7-9eb9-a694c7510d91.png">

Only on Android...

Here my config :
```
Android 7.1.0 - API 25 :
    "react-native": "^0.49.3",
    "react-native-maps": "^0.17.1",
```

Thanks for your help ;)

**Comment by rborn** [comment]
@matthieupinte that's I think an `out of memory issue` - https://stackoverflow.com/a/36903036

1300 markers are **a lot**, you might wanna handle this on region change and show only the markers that should be in the screen or even cluster them for small zoom levels

**Comment by alvelig** [comment]
Yes, see #213
