### ISSUE TITLE
showsMyLocationButton not working

### ISSUE THREAD

**Issue by radiKal07** [react-community/react-native-maps#1812]
`<MapView
          style={styles.container}
          showsUserLocation={true}
          showsMyLocationButton={true}
          onRegionChange={region => this.setState({ region })}
          onRegionChangeComplete={region => this.setState({ region })}
        />`
`"react": "16.0.0",
"react-native": "0.50.0",`

Show my location button still not appearing.

**Comment by Stophface** [comment]
Did you solve this? Having the same problem.

**Comment by Germanaz0** [comment]
I discovered on android device that when you rotate the phone, the button appears, but not in the initial state.

**Comment by aubreywahl** [comment]
seeing the same here on iOS

**Comment by vhuytdt** [comment]
![image](https://user-images.githubusercontent.com/18238875/33699205-4f3e9e7a-db44-11e7-90f2-c1f12b667ac6.png)
you set Time out in componentWillMount.. and in 
`  <View style={{paddingTop: this.state.statusBarHeight }}>
        <MapView
           ............................
        </MapView>
        </View>`..
because  showMyLocation init after map paint... => not appear

**Comment by richardstephenz** [comment]
I also don't see the showsMyLocationButton on iOS:

            <MapView
               style={{flex:1}}
                      region={this.state.mapRegion}
                      showsUserLocation={true}
                      followUserLocation={true}
                      showsMyLocationButton={true}
                      onRegionChange={this.onRegionChange.bind(this)}>
            </MapView>

    "expo": "^22.0.0",
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3"

**Comment by vhuytdt** [comment]
@richardstephenz  you setTimeOut and style map.. it will show...

**Comment by alvelig** [comment]
Duplicate of #1315

**Comment by alvelig** [comment]
Duplicate of #1033
