### ISSUE TITLE
Could not delete path

### ISSUE THREAD

**Issue by Bubblex** [react-community/react-native-maps#1813]
Error:Execution failed for task ':react-native-maps:processReleaseResources'.
> java.io.IOException: Could not delete path 'C:\Users\**\node_modules\react-native-maps\lib\android\build\generated\source\r\release\android\support'.

![qq 20171122172324](https://user-images.githubusercontent.com/22041769/33119409-e19a5a80-cfa9-11e7-82e5-3201d26b49c2.png)

**Comment by dcu-sharepoint** [comment]
I got the same error after changing the react-native's load version from 0.5.4 to 0.4.9 to resolve an issue with a topTouch error, now nothing works, going back to 5.4 where at least I get a compiled version.

**Comment by LuisRizo** [comment]
Fixed it by running `npm start -- --reset-cache` (And following the [Android Installation guide ](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#android)

**Comment by alvelig** [comment]
@christopherdro can close

**Comment by alexsmartens** [comment]
I'm having similar error. Can the issue be reopened?

```
...
:lottie-react-native:generateReleaseBuildConfig FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lottie-react-native:generateReleaseBuildConfig'.
> java.io.IOException: Could not delete path 'D:\myPATH\myApp\node_modules\lottie-react-native\src\android\build\generated\source\buildConfig\release\com'.
```

**Comment by digrase008** [comment]
@LuisRizo  Instead of reset cache every time the best way is go to that particular folder and give it full access that one worked for me

**Comment by sunithakk** [comment]
npm watchman watch-del-all

its worked for me.
RN version-0.55.2

**Comment by AAKIBZ** [comment]
i was facing the same problem in my project what i did was i deleted the build project in the file explorer and then did 'rebuild' in the android studio and it worked perfectly for me

**Comment by digrase008** [comment]
@AAKIBZ  but it will work for one time next time you have to do same things I did back track on buildToolsVersion it was working but after some time again facing the same issue not getting exactly what happening If any one have better solution please provide .... Thanks in advance

**Comment by top-master** [comment]
If you want you can change gradle build directory using below script so you can delete all build files at once.
```
allprojects {
    buildDir = "${rootProject.rootDir}/.build/${project.name}"
}
```
