### ISSUE TITLE
issue at generateReleaseBuildConfig while running on android

### ISSUE THREAD

**Issue by sridamagit** [react-community/react-native-maps#1814]
Execution failed for task ':react-native-maps:generateReleaseBuildConfig'.
> java.io.IOException: Could not delete path

**Comment by zarnifoulette** [comment]
I think you have to go to ` ./android/app` and delete the `build` directory. Do the same thing for the `build` directory in `./android/`.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
