### ISSUE TITLE
The region change event does not always occur

### ISSUE THREAD

**Issue by khomyakov42** [react-community/react-native-maps#1819]
Marker should be 
I use expo-sdk@23.0.0 and react-native-maps@0.17.1

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/866005/33191760-4dd8bb60-d108-11e7-8728-6c3883b08e55.gif)

The marker indicates the center of the region. It is visible that at fast moving the event "onregion" is not caused and the marker is not in the center of the screen.

**Comment by IjzerenHein** [comment]
Should be fixed by 0.18.x

**Comment by khomyakov42** [comment]
Thanks
