### ISSUE TITLE
Android (RN): How to set lat/long of MapView before render? Getting region update error

### ISSUE THREAD

**Issue by pcampolina** [react-community/react-native-maps#182]
I'm a beginner in RN and i'm having some issues with MapView and geolocalizer. Some one can help? Its actually 2 issues in one: I want to know the mobile geolocation and render a map with its lat/long. So, here's what i'm trying: Using componentWillMount function to get the geolocation with the suggested code: (using this to try to set the state with the coords before render)

```

navigator.geolocation.getCurrentPosition(
(position) => {
var initialPosition = JSON.stringify(position);
this.setState({initialPosition});
},
(error) => alert(error.message),
{enableHighAccuracy: true, timeout: 20000, maximumAge: 1000} 
);
```

The state initialPosition sets right, but i need to set the latitude and longitude state as well beucase JSON.stringify(position) is a string with many other properties, so how can i do something x = position (of the function) or x = navigator.geolocation return, because when i try to put a var x = initialPosition after this.setState (to treat and get only lat/long from x after), it doesnt receive any value, like if the code didnt work until componentWillMOunt ends. IDK.

Why i'm trying this? Because when i try to rerender the Mapview with the new lat/long from the state initialized i get this error:

Android : Error while updating property 'region' of a view managed by : AIRMap : https://github.com/lelandrichardson/react-native-maps/issues/140

Note: i do have the lat/long Delta, as the post suggest(not my post) How can i do this? Idk if the way i want to do is possible too, any suggestion will be appreciated. Thanks!

**Comment by 724170381** [comment]
Facing the same issue !
Error WHILE UPDATING property 'region' of a view managed by: AIRMap
Someone please help...
Here's my MapView
` <MapView
                  style={styles.map}
                  region={{
                    longitude: this.state.initialCoords.longitude,
                    latitude: this.state.initialCoords.latitude,
                    latitudeDelta: 10,
                    longitudeDelta: 10,
                  }}
                />`

**Comment by AndreVicenteW** [comment]
Same error here. Did you find the solution? I'm using genymotion and everything works fine, but when I run into the real android device I recive the red screen with this alert. And sometimes when I open the application load the map and when I go to another page and return to the map appers this message. I do not know why

**Comment by alvelig** [comment]
See #209
