### ISSUE TITLE
cannot find symbol new MapsPackage() in MainApplication

### ISSUE THREAD

**Issue by joaoalbertocsjunior** [react-community/react-native-maps#1821]
Problem: 

> error: cannot find symbol
>             new MapsPackage()
>                 ^
>   symbol: class MapsPackage
> 2 errors
> :app:compileDebugJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.

import com.airbnb.android.react.maps.MapsPackage; already added on MainApplication.java

I did react-native link.

What could be the problem?

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by vikasgupta007** [comment]
I have this same error 
![image](https://user-images.githubusercontent.com/68554699/89819013-5d806a00-db68-11ea-92d1-953ff9d8492f.png)
