### ISSUE TITLE
Saving data after drawing completed

### ISSUE THREAD

**Issue by StevanCakic** [react-community/react-native-maps#1825]
Hi,

those anyone knows what is the simplest way to store geometry data in some geoJson file with all geometry data for the map (like points, polygons, and lines) after user draws some shapes and for example, clicks Save button? What about updating and deleting that shapes from the map? Thanks

**Comment by alvelig** [comment]
That's completely your business logic as you need to track your objects outside the library (you can manage it in state or in store (redux), or even vanilla js object.
