### ISSUE TITLE
'React/RCTView.h' file not found

### ISSUE THREAD

**Issue by darrindickey** [react-community/react-native-maps#1826]
I know this has come up in the past, but I cannot seem to resolve it. When I run "build" in XCode, I get this error: 'React/RCTView.h' file not found in AIRMapCallout.h. I tried upgrading RNMaps from 0.16.4 to 0.17.1, but it didn't solve the problem. I've gone through the setup instructions multiple times (I installed manually and used RN Link). I've even shut everything down and rebooted without success. Any suggestions?

React-Native 0.45.1
react-native-maps 0.17.1

**Comment by aubreywahl** [comment]
I was having the same problem. For some reason `react-native link react-native-maps` wasn't doing it's job. Eventually got it to following the 'manual' installation instructions.

github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually

Different versions tho. I used:

rn: 0.50.3
react-native-maps: 0.18.0

**Comment by darrindickey** [comment]
Thanks for the reply. Yeah, I've already done those steps multiple times. No love.  :-(

**Comment by JaredSartin** [comment]
I did a pod install and made sure that the only `.a` in the dependencies was the pod build. When RNM was in there too, thats when I had the same issue.

**Comment by christopherdro** [comment]
Likely a linking issue. Please follow the manual steps with special attention to step 3.

https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually

**Comment by darrindickey** [comment]
I've redone the manual steps at least half a dozen times. Yesterday, I even deleted the full node_module and reinstalled using the manual steps again. Still no luck. I restarted Xcode, did Clean, then Build and still get the error.

**Comment by aubreywahl** [comment]
maybe also try rm -rf ios/build

**Comment by christopherdro** [comment]
Also `rm -rf node_modules` and reinstall all dependencies again if you haven't already

**Comment by darrindickey** [comment]
Ugh! Got my hopes up trying something new with killing the iOS/build directory. I deleted that directory, deleted all of the node_modules and reinstalled fresh. I deleted the AirMaps stuff from Xcode, closed and reopened Xcode. I followed all of the manual install instructions exactly, ran Clean and then Build... and got "'React/RCTView.h' file not found".  And much sadness ensued.

**Comment by darrindickey** [comment]
Well, it seems now the maps are failing to run in Android as well after deleting my node_modules, clearing the build files and reinstalling manually. I get an error message in Android that the react-native-maps module is not found in node_modules, though I can see it there.

**Comment by alvelig** [comment]
Surely the problem on your side. Likely you are using Pods installation. Try to build that project 
https://github.com/alvelig/react-native-maps-pods-example
(or just from scratch), if it fails let me know. If it does not, rebuild your project around the working maps. (That's much easier than looking for the solution to your problem, trust me).

**Comment by AndreaStevanato** [comment]
I have the same problem after add `Alamofire` on the Podfile. I already tried to create the project from scratch using the example: https://github.com/react-community/react-native-maps/tree/master/example

**Comment by helixbass** [comment]
@alvelig @AndreaStevanato this looks like the same issue as #2013, where the common thread would seem to be that we're using `use_frameworks!` in our `Podfile`

So I don't think it's an option to "rebuild your project around the working maps"

**Comment by alvelig** [comment]
@helixbass I agree, but rebuilding your project around the working maps allows to localize the problem. The problem localized can be handled.
