### ISSUE TITLE
Error when using fitToCoordinates

### ISSUE THREAD

**Issue by QQizi** [react-community/react-native-maps#1827]
I tried different way of using this function and i always get an error : "owner.getName is not a function"

I reproduced exactly the exemple : https://github.com/airbnb/react-native-maps/blob/master/example/examples/FitToCoordinates.js

But still get an error.

```
this._map.fitToCoordinates([MARKERS[2], MARKERS[3]], {
         edgePadding: { top: 100, right: 100, bottom: 100, left: 100 },
         animated: true,
      });
```

With MARKERS[2] & MARKERS[3] an object with key latitude & longitude

**Comment by rborn** [comment]
@QQizi are you following the exact example in the `FitToCoordinates.js` file?

**Comment by hnliyuan** [comment]
I have the same problem with you.  "owner.getName is not a function" .

**Comment by QQizi** [comment]
@rborn I tried to clean all my code and use the exact same example, still got the error.
I feel like the function is expecting markers instead of simple coordinate.

**Comment by alvelig** [comment]
@QQizi I have checked the example in FitToCoordinates.js and it is working ok.
Try to fork the project run the examples and try to reproduce your error. If you succeed, let us know to reopen.
