### ISSUE TITLE
Property 'cameraTargetBounds' not found on object of type 'AIRGoogleMap *'

### ISSUE THREAD

**Issue by yatagan** [react-community/react-native-maps#1836]
.../node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapManager.m:310:15: Property 'cameraTargetBounds' not found on object of type 'AIRGoogleMap *'

react-native-google-maps.podspec uses GoogleMaps v2.1.1 but cameraTargetBounds comes with v2.2
Tried to switch to GoogleMaps v2.2 manually but it does not work.

**Comment by luco** [comment]
I was having this exactly issue today, as you can see in #1833 
Take a look in this link, it helped me a lot.

https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14

**Comment by yatagan** [comment]
@luco so you used old version react-native-maps @0.15.3 ?

**Comment by luco** [comment]
@yatagan Yes.

**Comment by yatagan** [comment]
@luco I see, but it looks like all last releases v0.18.* are broken because of invalid GoogleMaps dependency

**Comment by luco** [comment]
@yatagan I don't know. I'm using 0.15.3 here and it's working properly.

**Comment by christopherdro** [comment]
Yea you can specify GoogleMaps in your projects pod spec to override the one included with this library.

Still would be nice to open a PR updating to the latest. https://github.com/airbnb/react-native-maps/blob/master/react-native-google-maps.podspec#L20

**Comment by yatagan** [comment]
@christopherdro I tried, but it causes GoogleMaps versions conflict - react-native-google-maps wants strictly v2.1.1 and I want v2.2 or more. 

But I'm not really sure about correct version, right now I'm playing with GoogleMaps v2.5

**Comment by ismaserrano** [comment]
You have to upgrade to >2.2. Yes, react-native-maps searching for 2.1.1 strictly, then edit 'react-native-google-maps.podspec' from 'node_modules':
`s.dependency 'GoogleMaps', '2.1.1'`
to
`s.dependency 'GoogleMaps', '2.5.0'`

**Comment by dseipp** [comment]
PR created to resolve this: https://github.com/react-community/react-native-maps/pull/1854

**Comment by michelalbers** [comment]
Don't they even build it before releasing it ... ?  :/

**Comment by DogsForArms** [comment]
This is still an issue for me

**Comment by nico1510** [comment]
Did you run `pod update` ?

Am 07.12.2017 11:21 vorm. schrieb "Ethan Sherr" <notifications@github.com>:

**Comment by DogsForArms** [comment]
After running a `pod update` I can see it says `Using GoogleMaps (2.1.1)`.  

So I tried to go to my podfile ( which is based off of the ios setup instructions 1), where I copy AirMap's podfile) and I updated the line

`pod 'GoogleMaps'`
to 
`pod 'GoogleMaps', '~> 2.5.0'` 

The output from pod update then is:

`
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-google-maps` from `../node_modules/react-native-maps`
Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
[!] Unable to satisfy the following requirements:

- `GoogleMaps (~> 2.5.0)` required by `Podfile`
- `GoogleMaps (= 2.1.1)` required by `react-native-google-maps (0.18.3)`
`

**Comment by alvelig** [comment]
@DogsForArms You need to use master, as there it is not released yet. Or just change: node_modules/react-native-maps/react-native-google-maps.podspecs

**Comment by guidolodetti** [comment]
I am still experiencing the same problem with version 0.19 and Google Maps version 2.5. Any help please?
