### ISSUE TITLE
XCode Build Fails: Duplicate Symbols for Architecture x86_64

### ISSUE THREAD

**Issue by ProteanDev** [react-community/react-native-maps#1842]
Hi, I'm getting this error from your modules when building for iOS

ld: 186 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

This might have something to do with the $(inherited) Linker Flag from Cocoapods.
How do we fix this?

**Comment by noboddee** [comment]
Hi, if like me you use Cocoapods. 
For make it build I unlink with run "react-native unlink react-native-maps" and now everything works fine. 
I think pod + automatically link create this duplicate issue

**Comment by alvelig** [comment]
@christopherdro can be close. @noboddee's solution works

**Comment by ProteanDev** [comment]
Nope, still getting that Duplicate Symbols. 
Please Re-Open this Issue.

**Comment by rborn** [comment]
@ProteanDev wait for https://github.com/react-community/react-native-maps/issues/1862 (soon, waiting for a Testflight Apple review to complete the tests) where I'll set some better instructions on how to install it. If you're in a hurry ping me and I'll share it with you before making the PR

**Comment by alvelig** [comment]
@ProteanDev https://github.com/alvelig/react-native-maps-pods-example check this example project

**Comment by alvelig** [comment]
Right now experienced that on my own project example LOL unlink solved.

**Comment by cinder92** [comment]
same issue here, i just not make `react-native link` but getting this error

**Comment by rborn** [comment]
@abrajeethan have a look in Xcode if you have any map libs linked -  https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#on-ios
Also try to clean the project form Xcode
