### ISSUE TITLE
Markers not rendered after state change

### ISSUE THREAD

**Issue by theobouwman** [react-community/react-native-maps#1848]
Hello,

I am using Firebase to store my markers and I want to render them on the map.
But after the markers are fetched and `.setState()` is called the map wont render the markers.

What can I do to this?

**Comment by jnzw1986** [comment]
I met it too，why？

**Comment by alvelig** [comment]
Please fork this https://github.com/alvelig/react-native-maps-example to reproduce this behavior. And make sure you did not mess up the coordinates.
