### ISSUE TITLE
MapMarker's calloutOffset does not work on iOS GoogleMaps

### ISSUE THREAD

**Issue by satori-ytolstoguzov** [react-community/react-native-maps#1852]
subj

**What I tried:**

```js
<MapView.Marker coordinate={{...}} calloutOffset={{x: 100, y: 0}}>
  ...
  <MapView.Callout>
    ...
  </MapView.Callout>
</MapView.Marker>
```

**What I expected:**
The marker's callout is shifted right by 100 points as per [docs](https://github.com/airbnb/react-native-maps/blob/master/docs/marker.md)

**What I got:**
Any values in `calloutOffset` props does not affect callout position. It stays aligned to top center of marker.

Example project to reproduce issue: https://github.com/satori-ytolstoguzov/rn-maps-callout-offset
Here is a [direct link](https://github.com/satori-ytolstoguzov/rn-maps-callout-offset/blob/master/App.js) to the map configuration.

**Comment by alvelig** [comment]
Hi, tried calloutOffset in my project, and it works ok. (rn link, no pods, no google maps)

Could not assemble your project, your Podfile is not complete.

@christopherdro can close. Can not reproduce.

**Comment by alvelig** [comment]
@satori-ytolstoguzov try my repo https://github.com/alvelig/react-native-maps-example/tree/callout-offset (Branch matters). Проверено ;)

**Comment by alvelig** [comment]
Oh, ok. With google provider it does not.

**Comment by satori-ytolstoguzov** [comment]
@alvelig Sorry! I did not realize that my example project is not complete. I will update it as soon as I can. Спасибо!

**Comment by alvelig** [comment]
Не за что! 

But I confirm, it does not work as expected with "google" provider. So I will leave that open.

**Comment by alvelig** [comment]
May I sometimes ping you to check some bugs with my commits, please?

**Comment by satori-ytolstoguzov** [comment]
@alvelig Sure

**Comment by satori-ytolstoguzov** [comment]
Example project updated. I checked couple of times, it should build successfully now.

**Comment by HerbertLim** [comment]
This happens to me also.
I use Google map for both Android and iOS.
At Android, callout position changes well as I expected as I change the value of calloutAnchor props.
However, at iOS, callout position does not change even though I used calloutOffset props.

**Comment by zerefdragneel3007** [comment]
i am facing same issue with offset on android with google maps. can anyone help me ?

**Comment by antonioreyna** [comment]
same issue here, any news on this ?

**Comment by tristanheilman** [comment]
Same issue here, I get this error -> Warning: Failed prop type: Invalid prop `calloutOffset` of type `number` supplied to `MapMarker`, expected `object`.
