### ISSUE TITLE
Bug with Podfile Yoga

### ISSUE THREAD

**Issue by Alp4ga** [react-community/react-native-maps#1856]
Hi,

I follow this tuto : https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14
When i run pod install I have this error : 

> Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga/Yoga.podspec`
> [!] The name of the given podspec `yoga` doesn't match the expected one `Yoga`

I d'ont understand because I have the file Yoga.podspec

EDIT : Solution

Sorry for this post i found the solution 
in Podfile -> change pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
in -> pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'

**Comment by alvelig** [comment]
@Alp4ga please close the issue.

@christopherdro can close.

**Comment by jerrymarino** [comment]
@christopherdro - is the resolution to this to use the lowercased name? If that's the case, then all other pods with dependencies on Yoga would need to use that custom podspec as well.

Is there a reason that React needs to use a custom naming convention? If not it seems easier and less confusing to just use the name `Yoga` instead of `yoga` in React.

**Comment by aliu1212** [comment]
In case anyone else is following the tutorial mentioned above and still getting the error, try removing the "/Yoga.podspec" from the path in your Podfile

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

**Comment by x5engine** [comment]
nice @aliu1212 DOES solution work fine

easy fix.

just do 

`ls node_modules/react-native/ReactCommon/yoga/`
and see where is the yoga podspec, mine had a capital letter 

`Yoga.podspec`

so wise words: Yoga is bad, practise Kung Fu instead"
Master Shifu

**Comment by Frank-Developer** [comment]
I renamed Yoga.podspec to yoga.podspec AND changed line 18 inside podspec file from spec.name = 'Yoga' to spec.name = 'yoga'
