### ISSUE TITLE
How to center on user location?

### ISSUE THREAD

**Issue by xPiwkoPL** [react-community/react-native-maps#1858]
<MapView style={styles.map}
                showsUserLocation = {true}
            >
I am using this and it show user location but how to center on user location on application load?
Can i change icon of user? Will showsUserLocation = {true} ask for gps?

**Comment by AuroreM** [comment]
Hi @xPiwkoPL,
To center on the user location, we have to add code to the `componentDidMount` function. It should be something like this : 
```
export const getCurrentLocation = () => {
  return new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(position => resolve(position), e => reject(e));
  });
};

class MyMap extends Components {
  constructor(props) {
    super(props);
    this.state = {
      region: defaultRegion,
    };
  }
  componentDidMount() {
    return getCurrentLocation().then(position => {
      if (position) {
        this.setState({
          region: {
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
            latitudeDelta: 0.003,
            longitudeDelta: 0.003,
          },
        });
      }
    });
  }
}
```

**Comment by xPiwkoPL** [comment]
> AuroreM how to implement this to this code
`import React from 'react';
import { View, Text, Button, TouchableOpacity } from "react-native";
import MapView from 'react-native-maps';
import dataJson from './Markers';
import openMap from 'react-native-open-maps';
import Communications from 'react-native-communications';

export default class Map extends React.Component {
    przejdzDoMapy(coordinate){
        openMap(coordinate);
        console.log(coordinate);

    }
  render() {
    return (
        <View style={styles.view}>
            <View style={styles.details}>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.title}</Text>
                </View>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.address} </Text>
                </View>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.name} </Text>
                </View>
                <View style={styles.tile}>
                    <TouchableOpacity onPress={() => Communications.phonecall(this.props.posterunek.phone, true)}><Text style={styles.photo}>{this.props.posterunek.phone}</Text></TouchableOpacity>
                </View>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.name2} </Text>
                </View>
                <View style={styles.tile}>
                    <TouchableOpacity onPress={() => Communications.phonecall(this.props.posterunek.phone2, true)}><Text style={styles.photo}>{this.props.posterunek.phone2}</Text></TouchableOpacity>
                </View>
                <View style={styles.tile}>
                    <TouchableOpacity onPress={() => Communications.email(this.props.posterunek.phone2, null,null,'Wiadomość do komendy','Treść wiadomości')}><Text>{this.props.posterunek.email} </Text></TouchableOpacity>
                </View>
            </View>
                <View>
                    <Button
                    title = "Nawigacja"
                    onPress = {() => this.przejdzDoMapy(this.props.posterunek.latlng)}
                    />
                </View>

            <MapView style={styles.map}
                initialRegion={{
                    latitude: 50.772349,
                    longitude: 16.261400,
                    latitudeDelta: 0.0922,
                    longitudeDelta: 0.0421,
                }}
            >
            <MapView.Marker
                    coordinate={{ latitude: 50.772349,
                        longitude: 16.261400 }}
                    title={'Twoja pozycja'}
                    image={require('../../assets/usermarker.png')}
                    />

                    <MapView.Marker
                    coordinate={this.props.posterunek.latlng}
                    title={this.props.posterunek.title}
                    description={this.props.posterunek.address}
                    image={require('../../assets/policemarker.png')}
                    />

            </MapView>
        </View>
    );
  }
}

const styles = {
    view: {
        flex: 1
    },
    details: {
        flex: 1,
        paddingTop:60
    },
    map: {
        flex: 1
    },
    photo: {
        color: 'blue'
    },
    tile:{
        height:30,
        justifyContent:'center',
        marginHorizontal:15,
        fontSize:40,
        borderBottomColor: '#000',
        borderBottomWidth: 1 
    }
}
   
`

**Comment by AuroreM** [comment]
Hi @xPiwkoPL,
What is blocking you from implementing my advice ? I can help you understand if there something unclear but I don't have time to code for you :)

**Comment by xPiwkoPL** [comment]
i am beginner and dont know where to actually put componentdidmount in my code

**Comment by alvelig** [comment]
@xPiwkoPL In your map class. Read this: https://reactjs.org/docs/state-and-lifecycle.html

@christopherdro can close.

**Comment by xPiwkoPL** [comment]
Cant find variable defaultRegion



import React from 'react';
import { View, Text, Button, TouchableOpacity } from "react-native";
import MapView from 'react-native-maps';
import dataJson from './Markers';
import openMap from 'react-native-open-maps';
import Communications from 'react-native-communications';

export const getCurrentLocation = () => {
    return new Promise((resolve, reject) => {
      navigator.geolocation.getCurrentPosition(position => resolve(position), e => reject(e));
    });
  };
  
export default class Map extends React.Component {
    constructor(props) {
      super(props);
      this.state = {
        region: defaultRegion,
      };
    }
    componentDidMount() {
      return getCurrentLocation().then(position => {
        if (position) {
          this.setState({
            region: {
              latitude: position.coords.latitude,
              longitude: position.coords.longitude,
              latitudeDelta: 0.003,
              longitudeDelta: 0.003,
            },
          });
        }
      });
    }
  
  

// export default class Map extends React.Component {
//     przejdzDoMapy(coordinate){
//         openMap(coordinate);
//         console.log(coordinate);

//     }
  render() {
    return (
        <View style={styles.view}>
            <View style={styles.details}>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.title}</Text>
                </View>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.address} </Text>
                </View>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.name} </Text>
                </View>
                <View style={styles.tile}>
                    <TouchableOpacity onPress={() => Communications.phonecall(this.props.posterunek.phone, true)}><Text style={styles.photo}>{this.props.posterunek.phone}</Text></TouchableOpacity>
                </View>
                <View style={styles.tile}>
                    <Text>{this.props.posterunek.name2} </Text>
                </View>
                <View style={styles.tile}>
                    <TouchableOpacity onPress={() => Communications.phonecall(this.props.posterunek.phone2, true)}><Text style={styles.photo}>{this.props.posterunek.phone2}</Text></TouchableOpacity>
                </View>
                <View style={styles.tile}>
                    <TouchableOpacity onPress={() => Communications.email(this.props.posterunek.phone2, null,null,'Wiadomość do komendy','Treść wiadomości')}><Text>{this.props.posterunek.email} </Text></TouchableOpacity>
                </View>
            </View>
                <View>
                    <Button
                    title = "Nawigacja"
                    onPress = {() => this.przejdzDoMapy(this.props.posterunek.latlng)}
                    />
                </View>

            <MapView style={styles.map}
                showsUserLocation = {true}
                initialRegion = {{
                    latitude: position.coords.latitude,
                    longitude: position.coords.longitude,
                    latitudeDelta: 0.003,
                    longitudeDelta: 0.003,
                }}
            >

                    <MapView.Marker style={styles.map}
                    coordinate={this.props.posterunek.latlng}
                    title={this.props.posterunek.title}
                    description={this.props.posterunek.address}
                    image={require('../../assets/policemarker.png')}
                    />

            </MapView>
        </View>
    );
  }
  }

const styles = {
    view: {
        flex: 1
    },
    details: {
        flex: 1,
        paddingTop:60
    },
    map: {
        flex: 1
    },
    photo: {
        color: 'blue'
    },
    tile:{
        height:30,
        justifyContent:'center',
        marginHorizontal:15,
        fontSize:40,
        borderBottomColor: '#000',
        borderBottomWidth: 1 
    }
}

**Comment by AuroreM** [comment]
`defaultRegion` would be a const that you set in case you're user do not have the GPS.
I've added an exemple with the coordinate of the eiffel tower in your code share

**Comment by xPiwkoPL** [comment]
https://codeshare.io/aY7yKM
did something like this
cant find variable region
if i add region like this
cant find position

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
