### ISSUE TITLE
Enable default zoom buttons

### ISSUE THREAD

**Issue by KarthickRaja3018** [react-community/react-native-maps#1860]
How to enable default zoom button in react native maps 
I am able to bring default compass using  <MapView>showsCompass={true}</MapView>

**Comment by rborn** [comment]
@KarthickRaja3018 I'm afraid it's not possible at the moment, you might need to create your own.

**Comment by alvelig** [comment]
Yep, actually. You need to animateToRegion having the current region and changing deltas respectively.
