### ISSUE TITLE
'AIRmap' does not exists

### ISSUE THREAD

**Issue by lyz1991** [react-community/react-native-maps#1864]
Due to the wrong when happend yestday #1863 ,I clean all modules and install run again ,I get the wrong message：‘’Native components for AIRMap does not exits“
I track the code,and find this:
const AIRMap = getAirMapComponent(this.props.provider);
const nativeComponent = Component => requireNativeComponent(Component, MapView, {
  nativeOnly: {
    onChange: true,
    onMapReady: true,
    handlePanDrag: true,
  },
});
const airMaps = {
  default: nativeComponent('AIRMap'),
};
if (Platform.OS === 'android') {
  airMaps.google = airMaps.default;
} else {
  airMaps.google = googleMapIsInstalled ? nativeComponent('AIRGoogleMap') :
    createNotSupportedComponent('react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.'); // eslint-disable-line max-len
}
const getAirMapComponent = provider => airMaps[provider || 'default'];
If I run react-native link, I get the wrong compile message yesterday

How can I resolve the problem and why It happens?

**Comment by alvelig** [comment]
Delete `ios/build` folder and comment

**Comment by lyz1991** [comment]
@alvelig I delete and all the same if you have time ，you can init a project(the version of react-native is 0.51) and yarn the module， and run ，the wrong will appear

**Comment by alvelig** [comment]
Yep, I did.
The differences are:
npm instead of yarn (should not matter)
"react-native": "^0.49.5"
"react-native-maps": "git+ssh://git@github.com/react-community/react-native-maps.git"

And it works. Clone the project https://github.com/alvelig/react-native-maps-pods-example, `npm i` and `react-native run-ios`

Likely you are forgetting to `react-native link`.

**Comment by lyz1991** [comment]
@alvelig 
I have links ,and this time I open xCode to track the file, that I find when I compiled I get a wrong message that 'Use of undeclared identifier 'MKMapTypeMuteStandard'； I look the apple developer that says the  this supported by SDKs ：iOS 11.0+，macOS 10.13+,but my macOS 10.12,should I update my version? and the iphone what version less 11.0 can use?

**Comment by alvelig** [comment]
For iOS you are always forced to use the latest version.

**Comment by ShunYamada** [comment]
I have faced the same issue. And I spent so long time to fix it, finally I added `libAirMaps.a` on the Xcode. That worked!

**Comment by Juniper11** [comment]
@ShunYamada  how do you manually add libAirMaps.a?  Thanks!
