### ISSUE TITLE
Keeping markers visible whilst animating

### ISSUE THREAD

**Issue by jskidd3** [react-community/react-native-maps#1865]
I have a map with roughly 50 markers displayed within fairly close proximity. I have noticed a small (noticeable) issue when zooming out from a very zoomed-in state to fit a group of coordinates on the map.

Understandably, because I'm zoomed in very far the map hides other markers to save using memory unnecessarily. However, when I execute `fitToCoordinates`, the markers aren't shown until the animation has **completely** finished. This means suddenly at the end of the animation all other 50 markers are shown on the map again. It would look far better if I could show these markers again before I execute `fitToCoordinates` so that they can be seen throughout the animation and not just suddenly appear at the end.

Can anyone help me with a workaround for this issue?

```
this.map.fitToCoordinates(myCoordinates, {
  edgePadding: { top: 50, right: 50, bottom: Dimensions.get('window').height / 2, left: 50 },
  animated: true
});
```

**Comment by alvelig** [comment]
We recently changed issue template. Do you mind filling it up according to the new rules please?
