### ISSUE TITLE
Get markers on visible area of the map

### ISSUE THREAD

**Issue by choo737** [react-community/react-native-maps#1866]
"react-native": "0.45.1"
"react-native-maps": "^0.18.3"

Is there any way / method to get a list of visible markers on the screen? I tried to dive deep into the Marker component by ref={component => {this._marker = component;}} in the MapView.Marker but couldn't find any properties which indicates that the marker is visible..

**Comment by alvelig** [comment]
Do it the way around: 
https://github.com/mapbox/geo-viewport

Here's the full example with supercluster: https://github.com/novalabio/react-native-maps-super-cluster/blob/master/ClusteredMapView.js
