### ISSUE TITLE
ListView over MapView

### ISSUE THREAD

**Issue by hironarita** [react-community/react-native-maps#1871]
![ywrbb](https://user-images.githubusercontent.com/19714101/33864077-e7b2c7a4-deb8-11e7-8604-29473e4c5bc0.gif)

How can I achieve something similar to above? I want a ListView over a MapView. When the list is halfway down the screen, I'd like for the user to still be able to interact with the map.

Many thanks!

**Comment by alvelig** [comment]
Position your ListView (Use FlatList) absolutely above the map. Manage position of your list (use Animated for animation).

Sorry, will close. That's not related to the library.
