### ISSUE TITLE
Document using custom and offline tiles

### ISSUE THREAD

**Issue by alvelig** [react-community/react-native-maps#1880]
Merging all similar issues here.

MapView.UrlTile
MapView.LocalTile

**Comment by zavadpe** [comment]
@alvelig Updated documentation for LocalTile in main README file within PR #1876

**Comment by zavadpe** [comment]
@alvelig I guess we could close this one..

**Comment by pawan8525** [comment]
hi i am using below url of soil map tile
<MapView.UrlTile
urlTemplate=" ....../api/soil/wms/?x=5458&y=12859&z=15 " />

in x,y i pass converted lat long and in z i pass zoom level.
But my map overlay tile repeat, why i don't know?
Please help

**Comment by DanielBoening** [comment]
@pawan8525 
I am having the same issue with localTiles. Did you found a solution?

**Comment by aminmahrami** [comment]
@DanielBoening don't compute x, y, z for each tile. just pass `http://.../tile/{z}/{y}/{x}` and `UrlTile` will do the compute and replaces the values.

**Comment by hariDasu** [comment]
my tile set is generated from an indoor floor plan, and the width and height of my floor plan map is in pixels. when i use the`//.../tile/{z}/{y}/{x}` format i also see the upper left most tile repeating, and the zoom levels do not seem to change in the same way they did before when using leaflet in a web view. i am unsure how to calculate the proper bounds and zoom levels within react native maps. i have been trying to find info on GIS stack exchange, understanding mercator projections and working on formulas to derive a function to translate from  a world map to a pixelated floor plan map, if i can figure this out i will share here.

**Comment by DanielBoening** [comment]
@aminmahrami I did have a folder with that structure.
@hariDasu I kept having problems when working with my map that was not projected on the real world as this library tries to map it to real world coordinates.

I did end up building my own mechanics.

**Comment by hariDasu** [comment]
@DanielBoening i am still thinking there is no other way than using leaflet.js in a webview, such as this person did https://github.com/react-native-community/react-native-maps/issues/1460. were you able to successfully translate your non-world map to a  spherical coordinate system?

**Comment by DanielBoening** [comment]
@hariDasu 
I guess you are right. There even is a react-native library trying to implement leaflet.js but it did not seem good enough for our project. We show a map on browser with leaflet.js and on the phone with a self-made solution. It works quite similar and user experience is similar.
Translating your tiles to the x/y/z was quite easy. Handling touches and such was a bit complicated. I could create a library from that and publish it if you are interested. But I could do it only next week.

**Comment by AzranAzwer** [comment]
How can we create custom indoor tile to show on map ?
