### ISSUE TITLE
Invariant Violation: Native component  for "AIRMAP"does not exist. React Native 

### ISSUE THREAD

**Issue by LuckySambial** [react-community/react-native-maps#1881]
The following build commands failed:
	CompileC /Users/dineshkumar/Desktop/SpaApp/reactNativeMapsExample/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-google-maps.build/Objects-normal/x86_64/AIRGoogleMapManager.o /Users/dineshkumar/Desktop/SpaApp/reactNativeMapsExample/node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Steps already taken to fix that problem.**
- unlink react-native-maps and link again
- remove node modules and install again
- repeat whole installation process from https://github.com/react-community/react-native-maps/blob/master/example/ios/Podfile almost 10 times.

Please help!!!

**Comment by rborn** [comment]
@LuckySambial for the next issues you will open please follow the issue template we've put in place.

To answer your question: keep an eye on https://github.com/react-community/react-native-maps/issues/1862, we're working to improve the installation docs and we'll update them soon.
