### ISSUE TITLE
 <MapView.Marker/> Hits A Wrong Event   

### ISSUE THREAD

**Issue by BrianLeeGH** [react-community/react-native-maps#189]
I use MapView as a child node in TabBarIOS.Item , when pressing the MapView.Marker in MapView  it hits the TabBarIOS.Item's onPress event.

**Comment by christopherdro** [comment]
@BrianLeeGH Can you provide a code sample?

**Comment by joaovpmamede** [comment]
@BrianLeeGH check this: https://github.com/lelandrichardson/react-native-maps/issues/14
Although you probably already have found the solution.
