### ISSUE TITLE
React native maps callback functions

### ISSUE THREAD

**Issue by ankitbisht143** [react-community/react-native-maps#1890]
### Is this a bug report?

(No)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)
Yes
### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

React native callback functions are not working. Like onPanDrag, onDragEnd.

**Comment by rborn** [comment]
What platform?
Can you provide a small example code?

**Comment by ankitbisht143** [comment]
Its solved..

**Comment by ankitbisht143** [comment]
But i am using onRegionChange and onRegionChangeComplete to get coordinates.

**Comment by rborn** [comment]
`onPanDrag` requires `scrollEnabled:false`
`onDragEnd` doesn't exist.

But closing any way as you found the solution
