### ISSUE TITLE
Lock the scroll on the map

### ISSUE THREAD

**Issue by loic-lopez** [react-community/react-native-maps#1894]
Hi,

It is possible to lock the the map?

I would like to define my custom scrolls actions.

Thanks for reply

**Comment by alvelig** [comment]
Please describe your business case. Remember to prefer SO for questions.

**Comment by edo1493** [comment]
I think he means locking the map, so disabling all the touch gestures. I was looking for a similar solution. In this case, the map doesn't move, even if you try to pinch zoom or scrolling.

**Comment by alvelig** [comment]
@edo1493 that's easy, put a view over it.

**Comment by edo1493** [comment]
Perfect, I think this can be closed, not even an issue.

**Comment by slorber** [comment]
@alvelig if the map is part of a TabNavigator, I tried to put a view on top of it, but it prevents the navigation from swiping the tabs.

Any idea about what could cause parent view gestures to be prevented when a map is inside it?

The issue I describe can be tested with Expo:

![image](https://user-images.githubusercontent.com/749374/35157820-732e9c46-fd35-11e7-8ad0-281a7cb472a8.png)


The TabNav has nothing particular, and the map screen is:

```javascript
import React from "react";
import {View} from "glamorous-native";
import {MapView} from "expo";
import {StyleSheet} from "react-native";
import {BaseText} from "texts";
import * as Colors from "colors";


const CommandScreen = () => (
  <View
    flex={1}
    width="100%"
    position="relative"
    backgroundColor={Colors.white}
  >
    <View
      style={StyleSheet.absoluteFill}
      flex={1}
      padding={100}
      zIndex={-1000}
    >
      <MapView
        style={{flex: 1}}
        region={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />
    </View>

    <View
      flex={1}
      backgroundColor="rgba(0,0,0,0.3)"
      zIndex={10000}
      alignItems="center"
      justifyContent="center"
    >
      <BaseText xl white>
        hey
      </BaseText>
    </View>

  </View>
);

export default CommandScreen;
```

**Comment by slorber** [comment]
Hmmm it seems this issue disappear in liteMode on Android. For now it's ok for my usecase so let's see

**Comment by gwl002** [comment]
But i need to control it ,sometime it should locked and sometime it should be open.
