### ISSUE TITLE
Overlapping markers flicker

### ISSUE THREAD

**Issue by nikolas7892** [react-community/react-native-maps#1895]
I have two markers that share the same location. It seems that there is a confusion on which one should render, thus, they flicker. Is there a solution for this in the react-native-maps api? 

### Environment

    react-native: 0.51.0
    react: 16.0.0
react-native-maps: 0.18.3

I'm using Google Maps and this problem is both present on the simulator and device.

### Steps to Reproduce

Simply have a image as a marker overlap another marker (the same coordinate region)

### Expected Behavior
Can't necessarily say what would be the expected behavior. I would say just that one image would dominate the other? Or rather have a new image appear with a number if two markers share the same exact coordinate.

### Actual Behavior
The flicker back and forth.
![dec-17-2017 11-46-45](https://user-images.githubusercontent.com/11046180/34083138-215f37ce-e320-11e7-95f5-5c22527108c1.gif)

### Reproducible Demo

This code will reproduce exactly the same bug (considering that you have everything configured).

```javascript
import React, { Component } from "react";
import { View, Image } from "react-native";
import _ from "lodash";

import MapView, { PROVIDER_GOOGLE } from "react-native-maps";

const fakeData = {
  user1: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d2/Donald_Trump_August_19%2C_2015_%28cropped%29.jpg",

    latlng: {
      latitude: 37.785834,
      longitude: -122.406417,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.05183658170914543
    },
    key: "key1"
  },
  user2: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3e/Mark_Zuckerberg_-_South_by_Southwest_2008_-_5.jpg",
    latlng: {
      latitude: 37.785834,
      longitude: -122.406417,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.05183658170914543
    },
    key: "key2"
  }
};

class MapScreen extends Component {
  constructor() {
    super();
    this.state = {
      region: {
        latitude: 37.785834,
        longitude: -122.406417,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.05183658170914543
      }
    };
  }

  render() {
    return (
      <View>
        <MapView
          provider={PROVIDER_GOOGLE}
          style={{
            height: "100%",
            width: "100%"
          }}
          region={this.state.region}
          onRegionChange={region => this.setState({ region })}
          onRegionChangeComplete={region => this.setState({ region })}
        >
          {_.map(fakeData, marker => (
            <MapView.Marker coordinate={marker.latlng} key={marker.key}>
              <Image
                style={{
                  height: 60,
                  width: 60,
                  position: "absolute"
                }}
                source={{ uri: marker.image }}
              />
            </MapView.Marker>
          ))}
        </MapView>
      </View>
    );
  }
}

export default MapScreen;
```

**Comment by alvelig** [comment]
@nikolas7892 Please fill up the issue according to new template. I think, I know how to solve it, but need your assistance with a minimal reproducible example and environment to reproduce.

**Comment by nikolas7892** [comment]
@alvelig I went ahead a updated the issue with an exact code to reproduce the bug.

**Comment by alvelig** [comment]
Unfortunately my idea was about apple maps. Looked through the GoogleMaps code, there's not much to do about this. So here's my dirty hack (actually not only mine, people on native platform have the same problem with iOS SDK - https://stackoverflow.com/questions/39526942/blinking-custom-markers-in-google-maps-ios)

```javascript
render() {
let i = 0;
return (<MapView
          provider={PROVIDER_GOOGLE}
          style={{
            height: "100%",
            width: "100%"
          }}
          region={this.state.region}
          onRegionChange={region => this.setState({ region })}
          onRegionChangeComplete={region => this.setState({ region })}
        >
          {_.map(fakeData, marker => (
            <MapView.Marker coordinate={marker.latlng} key={marker.key}>
              <Image
                style={{
                  height: 60,
                  width: 60,
                  position: "absolute"
                }}
                zIndex={i++}
                source={{ uri: marker.image }}
              />
            </MapView.Marker>
          ))}
        </MapView>
```

P.S. That's dirty not because of the lib, but because of the way GM SDK works. I'll close. Comment if you disagree.

**Comment by alvelig** [comment]
Anyway we'll have to make a thorough refactor of how markers are added.

**Comment by nikolas7892** [comment]
@alvelig I tried your suggesting but The method doesn't work even the "dirty" way.  Is there any other way? If not, I had an idea of checking if two markers share a location, and if so. I just show a new image that would indicate the number of overlapping markers. That way, you can select a marker and present a list of users that are at that location. How legit does that sound? I don't like the idea of keeping all the rendered users in a state and simultaneously reading the current location of the user.

![dec-17-2017 22-31-33](https://user-images.githubusercontent.com/11046180/34092834-3b8cb22a-e37a-11e7-9a9b-a74b04734f34.gif)

**Comment by alvelig** [comment]
Oh, excuses, my bad. `zIndex` not on Image but on marker. I updated the dirty solution in my previous comment.
Also try to avoid custom image if you are planning to use Android and many markers.

**Comment by alvelig** [comment]
Use supercluster. That's what you are looking for. Like here: https://github.com/novalabio/react-native-maps-super-cluster
