### ISSUE TITLE
animateToRegion slow onRegionChangeComplete

### ISSUE THREAD

**Issue by vincegio** [react-community/react-native-maps#1896]
### Is this a bug report?
Maybe

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes, everything works fine except this animation.

### Environment
react-native: 0.49.1
react: 16.0.0
react-native-maps: 0.19.0

Targeted platform is Android 7. 
Same outcome on both my device and emulator.

### Steps to Reproduce
1. Mapview (Markers not needed, tried both).
2. buttons for coordinates or something.
3. mapView.animateToRegion(region);
4. Try with (region,1).

I also set up a console.log line when clicking and mapView onRegionChangecomplete. Delay could be noticed there. Can't go to the next coordinate until this has been triggered.

### Expected Behavior
Like with (region,1) snappy. onRegionChangeComplete when the region is in view?

### Actual Behavior

animateToRegion(region):
https://i.imgur.com/b4BaTcy.gifv

animateToRegion(region, 1):
https://i.imgur.com/ZOpFDGS.gifv

Note the timestamps.

### Reproducible Demo
If you really want something, I can cook a sample up for you.

**Comment by rborn** [comment]
@vincegio please edit your issue following the provided template.
it helps us sorting and managing the issues.

**Comment by vincegio** [comment]
@rborn Done.

**Comment by rborn** [comment]
@vincegio are you doing anything in the code after calling animateToRegion?

**Comment by vincegio** [comment]
@rborn I do not think so, no.
My onPress function is like:
```
let region = {
      latitude: rowData.latitude,
      longitude: rowData.longitude,
      latitudeDelta: 0.5,
      longitudeDelta: 0.5,
    }
    _this.mapView.animateToRegion(region);
(and the console.log output)
```

I just looked trough my events in mapView, and 
``          onRegionChange={region =>     this.setState({ region })}          
``
appears to be the issue. I excluded this in my code and it is working now.

I didn't think of this until now.. But why might this be interfering with animateToRegion...

**Comment by rborn** [comment]
`onRegionChange` triggers every time the map moves a pixel (or so to say), you might wanna use `onRegionChangeCompleted` so you update the region only at the end of the animation

**Comment by vincegio** [comment]
I had a small suspicion of this. 
Perfect, that solved this then.
I will adjust my code and continue on!

Thank you for the help, still learning 😃

**Comment by rborn** [comment]
keep in mind that the execution of the javascript is single threaded, so you execute setState A LOT for using `onRegionChange` and then every state change re-renders the components which only triggers more js code :) 

Makes sense?

**Comment by vincegio** [comment]
Yeah, it does now :) 
Didn't think of this at all.

I remember in v 16 that completed didn't work 100%. But seems to work nicely now.

**Comment by alvelig** [comment]
I recommend not using state for controlling region at all, actually. Avoid it and prefer animation methods.

**Comment by vincegio** [comment]
I removed it completely, didn't need it anymore. 
I changed my code a bit :)

**Comment by slorber** [comment]
@alvelig so you also recommend not using MapView.Animated? Because I had bad performances with it too (I don't do setState/log on region changes). Moving to the imperative api increased significantly the performances

**Comment by alvelig** [comment]
I don't use MapView.Animated for my projects. (I know it is slow on Android) What do you mean by `imperative api`?

**Comment by slorber** [comment]
I mean the API you get through component ref

**Comment by slorber** [comment]
@alvelig there"s nothing to understand: I just want to animate the map from one region to the other. 

There are currently 2 ways: using `MapView.Animated` and animating the region through the `AnimatedRegion` in state (slow in my experience) and using React refs and calling `this.mapRef.animateToRegion(region,1000)` (much faster in my experience).

**Comment by alvelig** [comment]
Ah, ok. For this case I recommend this.mapRef.animateToRegion(region,1000), as it uses native map camera and that's why it is looking natively smooth.
