### ISSUE TITLE
Error in rendering child view on map

### ISSUE THREAD

**Issue by ankitbisht143** [react-community/react-native-maps#1901]
### Is this a bug report?
Yes

(write your answer here)
I am using react-native-maps. My requirement is to render some text and images on the mapview, so i have taken these on <View> component inside MapView. This is working fine on ios but getting error in android "The specified child already has a parent. You must call removeView() on the child's parent first"

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

**Comment by alvelig** [comment]
It's not a bug. Take them outside and position absolutely:
```
<View style={StyleSheet.absoluteFillObject}>
  <MapView style={StyleSheet.absoluteFillObject} />
  <View style={{ position: 'absolute', top: 100, left: 50 }}/>
</View>
```

**Comment by rborn** [comment]
closing as per the new rules following the template

**Comment by Mahadev-Khatri** [comment]
not working

**Comment by codex-solutions2019** [comment]
same issue done everything not working
