### ISSUE TITLE
library not found for -lreact-native-google-maps

### ISSUE THREAD

**Issue by mounlion** [react-community/react-native-maps#1902]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

```
"dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-maps": "^0.19.0"
  },
  "devDependencies": {
    "babel-jest": "22.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.0.1",
    "react-test-renderer": "16.0.0"
  },
```

### Steps to Reproduce

(Write your steps here:)

1. Try run app with Xcode simulator

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

I create new project and setup react-native-maps use instructions. But when i want run on with xcode i have this error

```
ld: warning: directory not found for option '-L/Users/fonov/Library/Developer/Xcode/DerivedData/MapsExample-aqdkxyiidietuzfpqcdqzgaqrala/Build/Products/Debug-iphonesimulator/React'
ld: warning: directory not found for option '-L/Users/fonov/Library/Developer/Xcode/DerivedData/MapsExample-aqdkxyiidietuzfpqcdqzgaqrala/Build/Products/Debug-iphonesimulator/react-native-google-maps'
ld: warning: directory not found for option '-L/Users/fonov/Library/Developer/Xcode/DerivedData/MapsExample-aqdkxyiidietuzfpqcdqzgaqrala/Build/Products/Debug-iphonesimulator/react-native-maps'
ld: warning: directory not found for option '-L/Users/fonov/Library/Developer/Xcode/DerivedData/MapsExample-aqdkxyiidietuzfpqcdqzgaqrala/Build/Products/Debug-iphonesimulator/yoga'
ld: library not found for -lreact-native-google-maps
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
<img width="1396" alt="2017-12-19 14 13 23" src="https://user-images.githubusercontent.com/17071211/34154514-cd8ee74a-e4c6-11e7-9dd2-f1b90cc6a78f.png">

**Comment by alvelig** [comment]
@rborn I warned you yesterday LOL

@mounlion Please make sure you open .xcworkspace

**Comment by mounlion** [comment]
Ok. Thanks you. I solved problem

**Comment by rborn** [comment]
@alvelig I'll take care of it this week

**Comment by mrabedini** [comment]
I had the same issue and I was opening the .xcodproj file instead of .xcworkspace . Opening and building with .xcworkspace file has no problem.
I think emphasizing it in documentation would be useful.
Thanks

**Comment by rborn** [comment]
@mrabedini a PR with the emphasis is very welcomed 😁

**Comment by mrabedini** [comment]
@rborn just as you wish mrabedini/react-native-maps/5df1111f5aa09a5824cc66581c2358d8f5dbfc32

**Comment by mrabedini** [comment]
@rborn just as you wish mrabedini/react-native-maps@5df1111f5aa09a5824cc66581c2358d8f5dbfc32

**Comment by mrabedini** [comment]
pull request #1931

**Comment by jeffreymendez1993** [comment]
Still occurs for me and I have the right project open..

**Comment by alvelig** [comment]
@jeffreymendez1993 can you try to checkout https://github.com/alvelig/react-native-maps-pods-example and see if it happens? can you provide logs of your issue?

**Comment by zaguini** [comment]
@jeffreymendez1993 solved it?
