### ISSUE TITLE
Error:Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by malashkevich** [react-community/react-native-maps#1908]
### Is this a bug report?
yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Steps to Reproduce

(Write your steps here:)

1. Install lib like described in manual
2. during build I get `Error:Execution failed for task ':app:processDebugResources':

```
AGPBI: {"kind":"error","text":"Attribute \"buttonSize\" already defined with incompatible format.","sources":[{"file":.../android/app/build/intermediates/res/merged/debug/values/values.xml","position":{"startLine":526}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Original attribute defined here.","sources":[{"file":".../android/app/build/intermediates/res/merged/debug/values/values.xml","position":{"startLine":412}}],"original":"","tool":"AAPT"}
.../android/app/build/intermediates/res/merged/debug/values/values.xml:527: error: Attribute "buttonSize" already defined with incompatible format.
.../android/app/build/intermediates/res/merged/debug/values/values.xml:413: Original attribute defined here.
```
In values.xml:
```
Line 527:
<declare-styleable name="SignInButton"><attr format="reference" name="buttonSize">
<enum name="standard" value="0"/>

<enum name="wide" value="1"/>

<enum name="icon_only" value="2"/>

</attr><attr format="reference" name="colorScheme">
<enum name="dark" value="0"/>

<enum name="light" value="1"/>

<enum name="auto" value="2"/>

</attr><attr format="reference|string" name="scopeUris"/></declare-styleable>
```
```
Line 413:
<declare-styleable name="EditFieldKeyboardView"><attr format="dimension" name="minButtonHorizontalDistance"/><attr format="dimension" name="buttonRowsDistance"/><attr format="dimension" name="buttonsPageMargin"/><attr format="dimension" name="buttonTextSize"/><attr format="dimension" name="buttonSize"/><attr format="dimension" name="pageIndicatorMargin"/><attr format="boolean" name="showButtonsPageIndicator"/><attr format="boolean" name="showButtonsInSingleRow"/><attr format="color" name="buttonTextColor"/><attr format="integer" name="buttonBackgroundDrawable"/><attr format="color" name="selectedButtonTextColor"/><attr format="integer" name="selectedButtonBackgroundDrawable"/><attr format="color" name="pagerIndicatorColor"/><attr format="color" name="selectedPagerIndicatorColor"/><attr format="string" name="buttonTextFontFamily"/></declare-styleable>
```

**Comment by alvelig** [comment]
Clean. Start from scratch. Clone this and tell me if it persists: 
https://github.com/alvelig/react-native-maps-example

**Comment by alvelig** [comment]
Did you manage to solve?

**Comment by malashkevich** [comment]
Actually, the issue is not with a new project but I'm trying to integrate maps into existing app. Seems like there are some library conflicts. Often this is due to different Google Play versions but seems like react-native-maps is the only lib that requires it. 
I need to dig into a bit.

**Comment by alvelig** [comment]
Might be related to #1773. Try `google-play-services:11.+` in gradle.

**Comment by malashkevich** [comment]
Thanks @alvelig, I saw that issue but still get the same problem.
What I did found - if I  in `app/build.gradle` will exclude `play-services-base` module - app start to build. Of course, it fails in runtime but seems like I localized a bit the issue.

I exclude module in this way:
```
compile(project(':react-native-maps')) {
    exclude group: 'com.google.android.gms', module: 'play-services-base'
}
```

**Comment by alvelig** [comment]
That's exactly the installation case: 
https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#android

Try this:
```
compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:11.+'
    compile 'com.google.android.gms:play-services-maps:11.+'
```

**Comment by malashkevich** [comment]
No I still had same issue: 
![image](https://user-images.githubusercontent.com/1452064/34361807-c8e33422-ea7e-11e7-8182-3681a109493f.png)

**Comment by alvelig** [comment]
Have you looked at that? 
https://github.com/playgameservices/play-games-plugin-for-unity/issues/947#issuecomment-178831950

Maybe there's a duplicate... But really I'm out of ideas.

**Comment by malashkevich** [comment]
@alvelig thanks, I'll take a look.
Also I can try to create reproducible demo if you need.

**Comment by alvelig** [comment]
That would be very welcome. I'll definitely help to find a way out of the problem if I can checkout and see it.

**Comment by malashkevich** [comment]
@alvelig Here is repository https://github.com/malashkevich/react-native-maps-test
Hopefully, you will be able to reproduce this too.

**Comment by alvelig** [comment]
Just remove your excludes.
```
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 7e698ef..f507654 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -141,12 +141,6 @@ dependencies {
     compile fileTree(dir: "libs", include: ["*.jar"])
     compile "com.android.support:appcompat-v7:23.0.1"
     compile "com.facebook.react:react-native:+"  // From node_modules
-    compile(project(':react-native-maps')){
-        exclude group: 'com.google.android.gms', module: 'play-services-base'
-        exclude group: 'com.google.android.gms', module: 'play-services-maps'
-    }
-    compile 'com.google.android.gms:play-services-base:10.0.1'
-    compile 'com.google.android.gms:play-services-maps:10.0.1'
 }
 
 // Run this once to be able to run the application with BUCK

```

**Comment by alvelig** [comment]
It's exactly `blinkid-verify-react-native` mess. 
I suppose that the libs included in that library (.aar) conflict with `compile "com.google.android.gms:play-services-base:+"`.
Feel free to ask them why it does not compile with google-services :) 

Despite all my willingness to help, I can't :( I'll close. That's not react-native-maps issue.

**Comment by alvelig** [comment]
Just try to compile this (without react-native-maps):

```
compile project(':blinkid-verify-react-native')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-base:+"
```

**Comment by malashkevich** [comment]
@alvelig but if I not include maps - they won’t work. Or I’m missing something?

**Comment by alvelig** [comment]
play-services-base gives the same error without react-native-maps

**Comment by alvelig** [comment]
@malashkevich I saw they replied quickly 👍 Let me know if it resolves, so we can have a happy New Year 😄

**Comment by malashkevich** [comment]
Sorry @alvelig, I completely forgot to close this one. Big thanks for help!!! Merry Christmas and Happy New Year!
