### ISSUE TITLE
Add a way to convert between coordinates and screen point

### ISSUE THREAD

**Issue by thatsmydoing** [react-community/react-native-maps#191]
Example use case: We can get screen points from some events like onPress to position views on a certain coordinate, but we cannot make the view move when the map is panned because we don't have a way to recalculate the new screen point for the panned map.

**Comment by rops** [comment]
+1 👍

**Comment by lixiaolihua** [comment]
+1

**Comment by wbattel4607** [comment]
This issue is stale, but +1

**Comment by wbattel4607** [comment]
Actually, though a built-in method would be awesome, I was able to do it without one.

The region's `latitudeDelta` and `longitudeDelta` show the distance, in coordinates, between the top and bottom and the left and right side of the map respectively. You can calculate the corresponding coordinate from any point on the screen by getting the distance between the center of the screen and the point, and converting it to the equivalent distance from the region's `latitude, longitude` pair to the coordinates at the edge of the screen using the deltas.

**Comment by alvelig** [comment]
see #1737

**Comment by rborn** [comment]
Closing, should be implemented/fixed by https://github.com/react-community/react-native-maps/pull/2039
