### ISSUE TITLE
can i set fixed marker in draggable map ?

### ISSUE THREAD

**Issue by hasanal1995** [react-community/react-native-maps#1912]
plaese! help me!!
any way to set fixed marker in mapView and Icon when click it, then get current location of fixed marker?
i was used fake image as a marker, but cannot use native events outside Mapview!!
any one can help please ?

**Comment by alvelig** [comment]
You need to show your 'marker' over your map in the center and then get region coordinates.

**Comment by hasanal1995** [comment]
how to get region coordinates of center map ? please help me @alvelig

**Comment by alvelig** [comment]
@hasanal1995 `onRegionChange` and `onRegionChangeComplete` here https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#events
