### ISSUE TITLE
Error when downloading the library with npm

### ISSUE THREAD

**Issue by chen4393** [react-community/react-native-maps#1913]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native-cli: 2.0.1
react-native: 0.51.0

### Steps to Reproduce

npm install react-native-maps --save

### Expected Behavior

build success

### Actual Behavior

> MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 

> 1) install the .NET Framework 2.0 SDK, 
> 2) install Microsoft Visual Studio 2005 or 
> 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\ccr13\Documents\ReactNativeProjects\MapDemo\node_modules\weak\build\binding.sln]

> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\ccr13\Documents\ReactNativeProjects\MapDemo\node_modules\weak
> gyp ERR! node -v v6.11.2
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok

**Comment by alvelig** [comment]
> install the .NET Framework 2.0 SDK
> add the location of the component to the system path if it is installed elsewhere. 

That's not related to the lib. See https://github.com/nodejs/node-gyp/issues/307

**Comment by alvelig** [comment]
https://github.com/nodejs/node-gyp#on-windows
