### ISSUE TITLE
how to zoom the map in center ?

### ISSUE THREAD

**Issue by wangliguang** [react-community/react-native-maps#1915]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment

 "react": "16.0.0-alpha.12",
  "react-native": "0.46.4",
  "react-native-maps": "^0.17.0",

### Expected Behavior

I want to zoom the map in center.

### Actual Behavior

How to  zoom the map in center?  thank you

**Comment by alvelig** [comment]
Your question is not clear. 
But as far as I understand you want to zoom programatically. Change region, maintain the same coordinates but change latitudeDelta and longitudeDelta.

**Comment by code-by** [comment]
@alvelig could you provide small example?
