### ISSUE TITLE
onPress not working on custom marker image?

### ISSUE THREAD

**Issue by ankitbisht143** [react-community/react-native-maps#1916]
When i am using default MapView.Marker, onPress is working but when I am using custom marker image(Inside TouchableOpacity), onPress is not working.

<MapView.Marker draggable coordinate={{latitude: this.state.region.latitude, longitude: this.state.region.longitude}}>
        <TouchableOpacity onPress={(e) => {e.stopPropagation(); this.onMarkerPress()}}>
           ..........Image.........
          </TouchableOpacity>
      </MapView.Marker>

**Comment by alvelig** [comment]
On Android it won't ever work. Not guaranteed to work on iOS.
Use MapView.Marker onPress. Don't use TouchableOpacity
