### ISSUE TITLE
Markers in radius of circle?

### ISSUE THREAD

**Issue by nikolas7892** [react-community/react-native-maps#1919]
I'm trying to know if a MapView.marker is inside of the radius of a MapView.Circle. I don't see any documentation explaining how to do this. Please give me something to try to figure out how to implement this feature.

![simulator screen shot - iphone 6 - 2017-12-22 at 16 38 57](https://user-images.githubusercontent.com/11046180/34315914-8b5ca8de-e73d-11e7-9dfb-6e8647c0d937.png)

**Comment by alvelig** [comment]
Share a snippet :)

**Comment by rborn** [comment]
@nikolas7892 https://www.movable-type.co.uk/scripts/latlong.html

**Comment by vuadenthuj1** [comment]
Do you have any example, bro?

**Comment by alprde** [comment]
i used isPointInCircle function of react native geolib.

https://github.com/manuelbieh/Geolib/blob/master/README.md

**Comment by funkyyy** [comment]
did u solve it? iam trying the same but i dont have a clue how to do it :/

**Comment by Priya-2016** [comment]
Do you have sample code? I need it urgently, unable to do it. Please help me

**Comment by sagar-deliverabhi** [comment]
This can be achieved using [Circle](https://github.com/react-native-maps/react-native-maps/blob/master/docs/circle.md) component of maps

Here is an example 

```
import MapView, {Marker, Circle} from 'react-native-maps';

<MapView
  initialRegion={{
    latitude: 21.239724,
    longitude: 72.9382757,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }}
  >
  <Marker coordinate={{latitude: 21.239724, longitude: 72.9382757}} />
  <Circle
    center={{
      latitude: 21.239724,
      longitude: 72.9382757,
    }}
    radius={5000}
    fillColor="#5A66CD1A"
    strokeWidth={0}
  />
</MapView>
```
