### ISSUE TITLE
Replace small 'y' with capital 'Y' in yoga pod install 

### ISSUE THREAD

**Issue by rishiankush** [react-community/react-native-maps#1933]
Please replace small 'y' with capital one in the documentation. I was really upset why my pod is not installing.
The error was just a capital letter.

**Comment by alvelig** [comment]
Do you mind making a PR?

**Comment by rborn** [comment]
@rishiankush you need to update your react-native. https://github.com/react-community/react-native-maps/pull/1816

Please try and let us know.

**Comment by rborn** [comment]
Closing, no issue template.
@rishiankush if the suggested fix doesn't work for you, please update the issue following the template and once it's done, ping me and I'll reopen the issue.
