### ISSUE TITLE
Scrollable callout using ScrollView not scrollable? 

### ISSUE THREAD

**Issue by Jun711** [react-community/react-native-maps#1938]
### Is this a bug report?
No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
```
"react": "16.0.0",
"react-native": "^0.50.4",
"react-native-maps": "^0.18.1",
target: Android
```

### Steps to Reproduce

(Write your steps here:)
```
<MapView
      scrollEnabled={false}
      rotateEnabled={false}
      moveOnMarkerPress={false}
      provider={MapView.PROVIDER_GOOGLE}
      style={{...StyleSheet.absoluteFillObject}}
      region={this.props.region}
    >
       <MapView.Marker
         coordinate={this.props.coord}
         pinColor='blue'>
           <MapView.Callout
                  tooltip={true}
                  style={{height: 100, width: 50, flex: 1}}
                >
                  <View style={{flex: 1}}>
                    <ScrollView contentContainerStyle={{flexGrow:1}}>
                      <Text style={{flex: 1, borderWidth: 1, borderColor: '#000'}}>{longText}</Text>
                    </ScrollView>
                  </View>
                </MapView.Callout>
          </MapView.Marker>
</MapView>
```
### Expected Behavior

to have scrollable callout content

### Actual Behavior

Callout text is contained within the MapView.Callout height. The callout is not scrollable no matter if MapView scrollEnabled is set to true or false.

### Attempt 
Have also read issues regarding having a MapView within a ScrollView

Have checked this [issue](https://github.com/facebook/react-native/issues/3422) and was able to create a regular scrollable view.

**Comment by alvelig** [comment]
Unfortunately callouts don't allow any interaction by Google Maps design see 
https://developers.google.com/maps/documentation/android-api/infowindows

<img width="873" alt="screen shot 2018-01-05 at 12 06 24 am" src="https://user-images.githubusercontent.com/4231544/34593882-69aaa73a-f1ac-11e7-9b54-217e9701413d.png">

You should make your view appear outside of the callout to make scrollview or touchable work.
