### ISSUE TITLE
After install maps other modules "Module does not exist"

### ISSUE THREAD

**Issue by abaddonGIT** [react-community/react-native-maps#1941]
in ios
react-native: 0.51.0
react: 16.0.0
react-native-maps: 0.19.0

After install react-native-maps from pods by instruction, different modules cant find in project then i run in device, 'ListView', 'React-Native', 'View' and other (different for each launch). After delete maps and reinstall all modules all work fine.

**Comment by rborn** [comment]
Closing, no issue template, no code to reproduce the issue.
