### ISSUE TITLE
Local MBTILES or GeoPackage support? Raster or Vector Tiles

### ISSUE THREAD

**Issue by geospatialmapmashup** [react-community/react-native-maps#1946]
Need offline disconnected mapping application. I have MBTILES that I create. Does this library support viewing local mbtiles SQLite3 Databases (raster tiles png or jpg and vector tiles GZipped PBF)
or Support OGC GeoPackage SQLite3 databases with Vector Features or Raster Tiles or Terrain Tiles or Vector Tiles?

**Comment by alvelig** [comment]
See #1876

**Comment by rborn** [comment]
Closing, missing issue template.

**Comment by Stophface** [comment]
This PR adds MbTiles support: https://github.com/react-community/react-native-maps/pull/2208

**Comment by systemlevel** [comment]
> This PR adds MbTiles support: #2208

Hi @Stophface was this added support for MbTiles reverted and taken out or is this still included in the latest react-native-maps?  Reading through some of the PR request history made me wonder if was fully included right now or there were additional items needing attention?

**Comment by Stophface** [comment]
@systemlevel No. `2208` got reverted. I corrected the errors and opened a new PR (https://github.com/react-native-community/react-native-maps/pull/2388) but noone ever got back to this. The code to include `MBTiles` on iOS and Android works. Not sure why it never got merged. Now there are most likely a lot of merge conflicts. I wont put any effort/time in it anymore though.

**Comment by madhums** [comment]
@Stophface would you be able to revisit the PR by any chance? I think it needs rebasing and then hopefully we can merge after 1.5y

**Comment by P0oOOOo0YA** [comment]
@madhums any news on this feature? I'm new to mapping and all terminologies around it. Kind of lost so apologies if i'm not technically right. This is what i'm trying to do:
I wish to host my own vector tile server with `openstreetmap` data and want `react-native-maps` to draw these tiles on the client which i guess this lib is capable of. Does this setup work? and if not would you please give me some hints on how should i approach my goal. I'm targeting only android right now.

**Comment by cklinx** [comment]
Any news??

**Comment by rxng8** [comment]
any news ?????? I really need this feature!
