### ISSUE TITLE
NSLocationWhenInUseUsageDescription ios

### ISSUE THREAD

**Issue by DanGDroid** [react-community/react-native-maps#1947]
### Is this a bug report?

no, it is incomplete important info documentation.

`<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>`

if description is left empty Apple review will reject.
you must fill a description

**Comment by alvelig** [comment]
Make a PR instead.

**Comment by Billy-** [comment]
This is still an issue, can this be re-opened please @alvelig

**Comment by alvelig** [comment]
@Billy- @ma96o @DanGDroid what would be the solution for this issue? Can anyone make a PR for it?
