### ISSUE TITLE
App crash without rendering in react-native@0.51.0, 

### ISSUE THREAD

**Issue by sathishu37** [react-community/react-native-maps#1949]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.51.0
    react: 16.0.0
    react-native-maps: 0.19.0
   Target Platform: eg: Android 6.0.1

### Expected Behavior

MapView Rendering Normally

### Actual Behavior

when i am open the app  It crashes frequently with the error alert. Unfortunately, app has stopped

  

I followed all the necessary steps in (https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)
  
![screenshot from 2018-01-08 20-15-32](https://user-images.githubusercontent.com/30067630/34675824-c70dc0e0-f4b0-11e7-8be9-b029644df4c3.png)

**Comment by rborn** [comment]
We need more info to be able to help. Try to get some logs from the device.

**Comment by sathishu37** [comment]
@rborn I have added screenshot for error log

**Comment by rborn** [comment]
@sathishu37 do you have google services installed? you need to run on device that has google play installed or an emulator with google apis.

**Comment by sathishu37** [comment]
finally, I solved this problem to update the versions.
```
dependencies {
    ...
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:11.+'
    compile 'com.google.android.gms:play-services-maps:11.+'
}
```

**Comment by rishiankush** [comment]
my app crashes on release build after rendering default splash screen.
This is my package.json file:
```
"dependencies": {
    "ajv": "^5.5.1",
    "ajv-keywords": "^2.1.1",
    "axios": "^0.17.1",
    "clamp": "^1.0.1",
    "faker": "^4.1.0",
    "https": "^1.0.0",
    "moment": "^2.19.3",
    "native-base": "^2.3.5",
    "react": "^16.2.0",
    "react-native": "^0.51.0",
    "react-native-button": "^2.3.0",
    "react-native-datepicker": "^1.6.0",
    "react-native-drawer": "^2.5.0",
    "react-native-fbsdk": "^0.7.0",
    "react-native-fcm": "^14.1.1",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-google-places": "^2.4.2",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-google-signin": "^0.12.0",
    "react-native-image-crop-picker": "^0.19.0",
    "react-native-image-picker": "^0.26.7",
    "react-native-infinite-scroll-view": "^0.4.3",
    "react-native-keyboard-aware-scroll-view": "^0.4.4",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-modal-datetime-picker": "^4.13.0",
    "react-native-router-flux": "^4.0.0-beta.27",
    "react-native-text-input-reset": "^1.0.2",
    "react-native-vector-icons": "^4.4.2",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "socket.io-client": "^2.0.4",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.3.11",
    "@storybook/addon-links": "^3.3.11",
    "@storybook/addons": "^3.3.11",
    "@storybook/react-native": "^3.3.11",
    "babel-core": "^6.26.0",
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "prop-types": "^15.6.1",
    "react-dom": "16.0.0",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
```
I tried many solutions provided on github and stackoverflow bu nothing worked for me.

**Comment by rishiankush** [comment]
@rborn How can I create logs in release build, Can you please help

**Comment by rborn** [comment]
what os ?

**Comment by rishiankush** [comment]
MacOS Sierra version 10.12.6

**Comment by rborn** [comment]
No, ios or android?

**Comment by rishiankush** [comment]
IOS

**Comment by rborn** [comment]
https://docs.buddybuild.com/troubleshooting/getting_device_logs_from_xcode.html

get only the ones related to your app

**Comment by rishiankush** [comment]
ohh yes! let me try this. Thanks
