### ISSUE TITLE
Map component loads an empty blue background

### ISSUE THREAD

**Issue by lucasharada** [react-community/react-native-maps#1951]
### Is this a bug report?

Yes. I followed all steps described on Installation and General Usage fields to load the Map component to place one single Marker (did not try yet).

The Map component seems to load, but all I get is a full light blue screen with Google logo on the Bottom. No other element is loaded (check image below).

<img width="431" alt="captura de tela 2018-01-08 as 17 31 48" src="https://user-images.githubusercontent.com/18669473/34691037-1980814e-f49a-11e7-96f7-53329c927ffa.png">

### Environment

react: 16.0.0
react-native: 0.51.0
react-native-maps: 0.19.0

**Comment by markmssd** [comment]
I think you're fully zoomed on the ocean :P Can you pinch out as much as you can, see of you discover something. Then you can try putting a flag, I mean a marker**, on it!

**Comment by lucasharada** [comment]
@markmssd That's it! The problem was that the Map component was not changing the location on state change. Got to fix that.
