### ISSUE TITLE
MapView onPress not triggered

### ISSUE THREAD

**Issue by theobouwman** [react-community/react-native-maps#1955]
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"expo": "^23.0.0",

### Issue

I just created a `MapView` with this code:

```
<MapView 
  onPress={(e) => this._onMapPress(e)}
  style={{flex: 1}}
  showsUserLocation={true}
  showsPointsOfInterest={false}
/>
...
_onMapPress = (e) => {
  console.log(e)
}
```
But nothing happens when I press the Map.

**Comment by rborn** [comment]
Expo uses an older version of the map https://github.com/expo/expo-sdk/blob/master/package.json#L59

**Comment by theobouwman** [comment]
@rborn do you know if that is the problem?

**Comment by rborn** [comment]
sadly no :(

**Comment by Manoj002** [comment]
same but not exactly same issue here as i click on map, the map collapses back 

im actually returning a mapview as a component between cardSection and view and as i click on map, the mapview goes back to its previous state of invisibility.
