### ISSUE TITLE
[ANDROID] #1851 build error

### ISSUE THREAD

**Issue by pedrolopes10** [react-community/react-native-maps#1956]
After updating for commit #1851 throws an error when building:

AirMapModule.java:205: error: cannot find symbol
        WritableMap coordJson = new WritableNativeMap();
        ^
  symbol: class WritableMap

### Environment
react-native: 0.52.0
react: 16.2.0
react-native-maps: "git+ssh://git@github.com/react-community/react-native-maps.git"

### Steps to Reproduce
npm update
react-native run-android 

@danielgindi & @rborn 

Thanks

**Comment by rborn** [comment]
@pedrolopes10 please update the issue following the template and I'll reopen it.

**Comment by rborn** [comment]
@danielgindi can you have a look at this one? Thnx

**Comment by vendramini** [comment]
Same here. Adding `import com.facebook.react.bridge.WritableMap;` on `AirMapModule.java` and problem solved.

**Comment by rborn** [comment]
@vendramini mind a PR?

**Comment by vendramini** [comment]
https://github.com/react-community/react-native-maps/pull/1958

**Comment by rborn** [comment]
#1958 merged, closing
