### ISSUE TITLE
How do hide the markers on the map?

### ISSUE THREAD

**Issue by itarodrigo** [react-community/react-native-maps#1963]
The google map is load with many places marker on the map. How do I can hide the markers on map?

**Comment by alvelig** [comment]
See #213

**Comment by itarodrigo** [comment]
See this image:

![1](https://user-images.githubusercontent.com/35380512/34892685-5a07b7bc-f7c1-11e7-8775-444f5fb131aa.png)

How do hide the items red on the map?
