### ISSUE TITLE
current location button in IOS App

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-community/react-native-maps#1971]
How can I show current location button in react native IOS App like this : 

![image](https://user-images.githubusercontent.com/3944526/35036839-99605bd4-fb9b-11e7-89b2-4c32d58a499d.png)

**Comment by abhitheawesomecoder** [comment]
and yes I don't ant to use Google Maps

**Comment by jskidd3** [comment]
@abhitheawesomecoder Apple's MapKit doesn't contain a 'my location' button out of the box. You'll need to create your own one and add it to the map.

**Comment by abhitheawesomecoder** [comment]
Then is this prop for in react-native-maps showsmylocationbutton={true}

**Comment by rborn** [comment]
Closing, no issue template.

**Comment by abhitheawesomecoder** [comment]
Then what is this prop for, in react-native-maps
showsmylocationbutton={true}

**Comment by alvelig** [comment]
Implement your own, can be like this:
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
