### ISSUE TITLE
Invariant Violation: Native Component for "AIRMap" does not exist in iOS

### ISSUE THREAD

**Issue by chen4393** [react-community/react-native-maps#1972]
npm: 5.4.2
node: 8.8.1
react-native: 0.52.0
react-native-maps: 0.19.0

**Comment by alvelig** [comment]
Not linked. Use pods or make `react-native link`

**Comment by aqwert** [comment]
The docs says not to use `react-native link`:

!! DO NOT USE !! react-native link

**Comment by alvelig** [comment]
@rborn There's an error there... This should be said below PODS installation, not general. @aqwert thank's for spotting it!

**Comment by aniiskywalker** [comment]
same issue, i can't do anything

**Comment by noumanDev** [comment]
@aniiskywalker  anyluck?

**Comment by aniiskywalker** [comment]
@noumanDev yeah, I opened an issue if you want to take a look [https://github.com/react-community/react-native-maps/issues/2064#issuecomment-376429299](#2064) i hope it helps

**Comment by thecraftykraut** [comment]
@alvelig so when should I link? It has to be linked at some point right?

**Comment by pawarvijay** [comment]
i followed all below steps and it worked
https://github.com/react-community/react-native-maps/issues/2188#issuecomment-395977497
