### ISSUE TITLE
0.19.0 cameraTargetBounds

### ISSUE THREAD

**Issue by CityLifeCorp** [react-community/react-native-maps#1974]
Getting this Error  on POD INSTALL

[!] Unable to satisfy the following requirements:

- `GoogleMaps` required by `Podfile`
- `GoogleMaps (= 2.5.0)` required by `react-native-google-maps (0.19.0)`

Specs satisfying the `GoogleMaps, GoogleMaps (= 2.5.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by alvelig** [comment]
Provide your podfile

**Comment by alvelig** [comment]
NO ISSUE TEMPLATE

**Comment by MacKentoch** [comment]
Same exact issue, here is my Podile:

```ruby
# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target '_I_JUST_REPLACED_THIS_FOR_THIS_ISSUE' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'react-native-maps', path: rn_maps_path

  pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by rborn** [comment]
@CityLifeCorp  @MacKentoch  uncomment and set this to 8.0 or higher `platform :ios, '8.0'`

https://developers.google.com/maps/documentation/ios-sdk/releases - `Note: Support for Xcode 7.3 has been dropped. The new minimum is Xcode 8.0.`

**Comment by MacKentoch** [comment]
Thank you @rborn for blazing fast answer.


**NOTE / FEEDBACK:** If someone has the same issue **after running**:
```bash
pod install
```

Then modifying Podfile to specify ios platform as @raubas told will fix it. 
But, maybe because I messed up before, I had to `update pod` rather than install again (*it kept keep throwing the issue until I update*):
```bash
pod update
```
