### ISSUE TITLE
Markers count on current view

### ISSUE THREAD

**Issue by rodrigoic23** [react-community/react-native-maps#1975]
Hi, i need some help. I need to count the current markers on the map view.
This is how i rendering:

```
<MapView
          style={styles.map}
          region={{
            ...this.props.location
          }}
          loadingEnabled
          followsUserLocation
          showsMyLocationButton={false}
          showsPointsOfInterest={false}
          showsCompass={false}
          showsScale={false}
          showsBuildings={false}
          showsTraffic={false}
          showsIndoors={false}
          pitchEnabled={false}
          zoomEnabled={false}
          rotateEnabled={false}
          moveOnMarkerPress={false}
          scrollEnabled={false}
          onPress={this.props.onPress}
          showsUserLocation
        >
          {this.props.pois.map(this._renderMarker)}
        </MapView>
```

I have an array with all my pois, but my maps is fixed, so, I won't show necessary al pois in array, that's why i can't use pois.length to get that count.. 

If i can't count the showing markers, I can only validate that there is unless 1 marker rendered, or show a little message if not. 

Thank you.

**Comment by alvelig** [comment]
https://github.com/mapbox/geo-viewport

**Comment by aMarCruz** [comment]
@rodrigoic23 ...why not `this.props.pois.length` ?
