### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by ankitbisht143** [react-community/react-native-maps#1978]
### Is this a bug report?
  If you answered "Yes":

I am using react-native-maps which is working fine. I have one marker in my map, but when I am dragging my map screen, marker is moving very slowly. So if I drag the screen 4-5 times left to tight, then it will slowly go to left then right...

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
YES

  Please specify the react, react-native, react-native-maps versions, eg:

    react-native: 0.51.0
    react: 16.0.0
	react-native-maps: ^0.18.3

  Target Platform: Both platforms

**Comment by alvelig** [comment]
Uncheck slow animations (Cmd + T)

**Comment by ankitbisht143** [comment]
@alvelig What does that mean?

**Comment by alvelig** [comment]
1. Your issue is not full according to the template.
2. I suppose you are using iOS simulator. Press Cmd + T (Debug -> Slow Animations)

**Comment by ankitbisht143** [comment]
@alvelig I m using in real device

**Comment by alvelig** [comment]
Then it in your code.
