### ISSUE TITLE
MapView.Marker causes project to crash

### ISSUE THREAD

**Issue by jongirard** [react-community/react-native-maps#1984]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
"expo": "25.0.0",
"react": "16.2.0",
 "react-native": "expo/react-native#sdk-25",
 "react-native-maps": "0.19.0",

### Steps to Reproduce

Add <MapView.Marker /> as directed in instructions with Coordinate prop and attempt to build app in expo. Causes client to crash fatally without logs.

### Expected Behavior

App should build and launch normally.

### Actual Behavior

Expo crashes fatally on latest SDK. Please see interactive snack to see reproducible error. https://snack.expo.io/@jongirard/map-crash

### Reproducible Demo

https://snack.expo.io/@jongirard/map-crash

Comment out or remove the MapView.Marker code on line 82-84 to see the map properly working in expo.

**Comment by rborn** [comment]
I think that's more an Expo issue. If you can reproduce the issue with a "normal" project I will re-open it. 🤗
