### ISSUE TITLE
Remove all markers

### ISSUE THREAD

**Issue by ankitbisht143** [react-community/react-native-maps#1985]
Is there a way to clear or remove all markers in onPress action?

**Comment by rborn** [comment]
no issue template, closing

**Comment by alvelig** [comment]
MapView's children is the only way to control markers.

**Comment by prashant9912** [comment]
what I did is to wrap marker 

```
{this.state.clearMap?null:(
<MapView.Marker
....
/>
)}
```

then call ` this.setState({clearMap:true})` whenever want to clear the map and `false` when I want to show (after updating the positions of the markers) 

Kinda one of the solution :)
