### ISSUE TITLE
How to fix google map not show?

### ISSUE THREAD

**Issue by chaipipatP** [react-community/react-native-maps#1986]
# How to fix google map not show?
![bfbda4a398a6478b7c78d85cfff7a2c5.png](https://www.img.in.th/images/bfbda4a398a6478b7c78d85cfff7a2c5.png)
![d6f9c25f08de76e66a24f99022550a95.png](https://www.img.in.th/images/d6f9c25f08de76e66a24f99022550a95.png)

**Comment by rborn** [comment]
Be sure you have the api key correct and not limited in the google console.

No issue template. Closing.
