### ISSUE TITLE
Where's this example? 

### ISSUE THREAD

**Issue by sofiane-soufi** [react-community/react-native-maps#1988]
Hi!

I'd like to know if anyone has the link of the source code to this example in the doc:

https://camo.githubusercontent.com/9b5fcde0cb8146672f54d39fc3c34bd2e1f7891f/687474703a2f2f692e67697068792e636f6d2f336f365542644751644d31476d566f4964712e676966

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedViews.js
