### ISSUE TITLE
How to disable drag or any other touch event on the MapView

### ISSUE THREAD

**Issue by jack2684** [react-community/react-native-maps#1989]
I want to simply display the map, but do not want any user interaction on it. 

Is there a way to do it?

**Comment by rborn** [comment]
No issue template, closing

**Comment by alvelig** [comment]
Duplicate of #1961

**Comment by morksinaanab** [comment]
This is not a duplicate. #1961 mentions not being able to move the map, but only to move the marker.
This issue mentions not to have any user interaction at all.

My comment on 1961 has a solution: wrap it in view with pointerEvents="none"

https://github.com/react-community/react-native-maps/issues/1961#issuecomment-393525742

hope it helps. It solved my problem

**Comment by edmondalimehmeti1** [comment]
use `scrollEnabled={false}`

**Comment by whoiscarlo** [comment]
scrollEnabled={false} is not working on:
`"expo": "~52.0.32",`
`"@rnmapbox/maps": "^10.1.33"`

**Comment by dbaonguis** [comment]
> use `scrollEnabled={false}`

For me, this worked.  Mainly because I wanted to disable the dragging/panning of the map, but I still want to be able to press  Markers.  Thanks!
