### ISSUE TITLE
iOS Satellite Map type is not supported

### ISSUE THREAD

**Issue by manotnemanja** [react-community/react-native-maps#1993]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

Set satellite as mapType on iOS. 
### Expected Behavior

It should set map type as satellite.
### Actual Behavior

It will report that is invalid GMSMapViewType and it should be one of the following: hybrid, none, standard, terrain.
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

![screen shot 2018-01-25 at 9 31 09 pm](https://user-images.githubusercontent.com/29597393/35410892-1da65278-0217-11e8-8ec5-f95f3a7149b7.png)

**Comment by rborn** [comment]
@manotnemanja can't reproduce, works for me with both apple and google maps.
set this as property to the MapView and it should work.

If not we need some code to reproduce it.

```
mapType="satellite"
```

**Comment by rborn** [comment]
@manotnemanja closing for  lack of activity, comment and ping me if you still experience this.

**Comment by simon4321** [comment]
Still experience this bug. Pls help. Using Expo version 24. React version 16. React-native version 0.51 and react-native-maps version 0.20.1.
