### ISSUE TITLE
white screen in Release mode

### ISSUE THREAD

**Issue by krionoah69** [react-community/react-native-maps#1994]
"react-native": "0.50.3",
"react-native-maps": "^0.18.3",
2.5.0
I have a problem, my app just launched with a blank white screen when change Release mode, but in debug mode works perfectly.
when I change to released, the app crashes and I get an error.

`Thread 11: signal SIGABRT`
```
  @catch (NSException *exception) {
    // Pass on JS exceptions
    if ([exception.name hasPrefix:RCTFatalExceptionName]) {
      @throw exception;
    }

    NSString *message = [NSString stringWithFormat:
                         @"Exception '%@' was thrown while invoking %s on target %@ with params %@\ncallstack: %@",
                         exception, method.JSMethodName, moduleData.name, objcParams, exception.callStackSymbols];
    RCTFatal(RCTErrorWithMessage(message));
  }
```
![screen shot 2018-01-25 at 20 31 25](https://user-images.githubusercontent.com/16009215/35422569-ff539e64-020e-11e8-905c-e63accb17c15.png)

Due to this I can not get the file from my final app.
**It only fails in released, in debug mode it works perfectly.**
NOTE: I am running from xcworkspace

**Comment by alvelig** [comment]
Unfortunately, there's not much information provided in your issue.  
Maybe you should `archive` your app for production? 
What steps do we need to follow to see the same problem as you see?

**Comment by krionoah69** [comment]
solved the problem by installing the most current version of React-native

**Comment by Mimicx** [comment]
i have the same issue, but it was after the "Codesign wants to access key “access” in your keychain"  ALERT, when i was bulinding my app in realease mode.

**Comment by rborn** [comment]
@Mimicx that's normal, you need to sign the app and the certificates are stored in your keychain, allow it or you won't be able to release.
