### ISSUE TITLE
Pressing on Marker also triggers MapView's onPress.

### ISSUE THREAD

**Issue by vuphuctho** [react-community/react-native-maps#2004]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.51.0
react: 16.0.0
react-native-maps: 0.19.0

platform: iOS
map provider: Google

### Steps to Reproduce

1. Add a Marker into MapView.
2. Assign custom `onPress` behaviours to both MapView and its Marker (e.g. onMapPressed & onMarkerPressed)
3. Press on Marker

### Expected Behavior

- Only onMarkerPressed should be triggerred

### Actual Behavior

- Both onMapPressed and onMarkerPressed are fired
- Issue only happens in iOS (tested in iOS 10 and iOS 11). On Android so far I don't observe same issue happened.

### Reproducible Demo

Expo: [link here](https://snack.expo.io/rJqs1-lLG)

**Comment by gunsym** [comment]
hi @vuphuctho, I noticed that this could be the same issue as noted in #758 

I believed they were able to have a workaround by stopping the propagation of the event.

**Comment by vuphuctho** [comment]
Thanks a lot. The workaround works.
