### ISSUE TITLE
AIRMap does not exist

### ISSUE THREAD

**Issue by danchokobo** [react-community/react-native-maps#2005]
Please help me. I have Xcode 9.0
React-native 0.52

I did everything by instruction Instalation.
Also, I cannot build in xworkspace, because of error: 
"/Applications/Q4C/app/node_modules/react-native/ReactCommon/yoga/yoga/YGNodePrint.cpp:208:46: Implicit conversion loses integer precision: 'size_type' (aka 'unsigned long') to 'const uint32_t' (aka 'const unsigned int')"
const uint32_t childCount = node->children.size();
![simulator screen shot - iphone 6 - 2018-02-01 at 12 55 40](https://user-images.githubusercontent.com/16972272/35665214-4dd81de0-074f-11e8-8b2c-92f0ba11ea40.png)

**Comment by Seventhly** [comment]
Hi,I have exactly the same issue.
My React : 16.2.0 ,React-Native : 0.52.0  
so when I install maps,the result
[
![380e074a-7d22-46a4-a577-7c67058ad5d0](https://user-images.githubusercontent.com/13692743/35714981-ca6ed824-080a-11e8-8764-b5eae41c676b.png)
](url)
Pleas keep your React : 16.0.0 and React-Native:0.51.0  to resolve warning.

And link the react-native-maps.
`react-native link react-native-maps`

The result :
[
![66cd39ec-4c44-426b-8a29-ac36b45926b9](https://user-images.githubusercontent.com/13692743/35715017-03dbe8b8-080b-11e8-9b3d-97d5d4a5febb.png)
](url)

Your Xcode Build Phases --> Link Binary  will have the libAirMaps.a.
[
![989a9eee-d8d2-4ac0-8d6c-a5bce072cf1c](https://user-images.githubusercontent.com/13692743/35714782-ac988878-0809-11e8-931e-9eb4c787e208.png)
](url)

Please clean your project and run again.

**Comment by thomashermine** [comment]
I think this is actually related to a bug in RN 0.52 : https://github.com/facebook/react-native/issues/17274

**Comment by inanbayram** [comment]
Tried everything but didn't found a solution. Someone know how to fix the problem?

**Comment by inanbayram** [comment]
I created now a new project and installed at first the react-native-maps package. Everything works fine now. The strange thing is, that I'm currently using the same version as before (react-native, react-native-maps etc...) and also the modules which I installed are the same as before :/

If you have enough time, try to create a fresh project with react-native-maps. Later you can include the other components/modules

**Comment by aniiskywalker** [comment]
Same issue, I follow the instructions and the same screen appears 
![captura de pantalla 2018-03-05 a la s 23 16 10](https://user-images.githubusercontent.com/37088363/37015310-bdd56dc4-20cb-11e8-8260-ba95ab45eeb1.png)

**Comment by floraSy** [comment]
1. Use **Xcode** to open project
2. Find **Libraries** in Project Navigator and click right to choose **Add Files to "[Your Project]" ...**
3. Find **AirMaps.xcodeproj** in **node_modules/react-native-maps/lib/ios** and add it
4. Find **Link Binary With Libraries** in **Build Phases** and add **libAirMaps.a**
