### ISSUE TITLE
iOS map callout is pixelated

### ISSUE THREAD

**Issue by janroures** [react-community/react-native-maps#201]
Anyone else seen this? The callouts/annotations on my map are pixelated on iOS. Not on Android.

**Comment by jrichardlai** [comment]
Hello, I'm not sure I understand the issue, can you put a screenshot of what you see? Thanks!

**Comment by janroures** [comment]
Hope you can see this:

![leland](https://cloud.githubusercontent.com/assets/8616333/15108262/3ca105fe-15d5-11e6-9e1c-6a40de3c4d0c.png)

**Comment by yonahforst** [comment]
is this screenshot from the simulator? do you experience the same problem on the device?

**Comment by janroures** [comment]
this is a screenshot from the device (iPhone 6 latest OS). Same on the simulator.

**Comment by Marswang92** [comment]
@janroures @jrichardlai  having same issue, any work around?

**Comment by Marswang92** [comment]
Temporary solved by not using built-in callout, but to use a flag to make selected marker render a tooltip with position: 'absolute', will look into the source code to find a better solution.

**Comment by alvelig** [comment]
Can't reproduce. Please provide your code/sample project to reproduce that problem
