### ISSUE TITLE
Zooming is not working

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-community/react-native-maps#2014]
Hello everyone,

I'm currently facing one issue in react-native-maps. When I'm tapping, the maps is zooming to its end value, so I'm unable to see side locations or point. So, I've set max zoom level for the lat-long coordinates using maxZoomLevel={15} prop. Now, I'm able to see the side locations also but it is not zooming in if I want to zoom more.
I've used     `maxZoomLevel={8} zoomEnabled={true}` props is MapView. How can achieve the above one ?

**Comment by ShaikhKabeer** [comment]
@rborn , any solution for this ?

**Comment by hedaktibo** [comment]
If you added the 'region' property to the MapView element, for every render() call, the map will update it's region.
if whenever you interact with the map the map refreshes, that kind of behaviour can be caused.

**Comment by rborn** [comment]
Closing as we start to enforce the issue template. Sorry.

**Comment by ShaikhKabeer** [comment]
Any solution for this one ?

**Comment by hegelstad** [comment]
I would also like a fix for this.

fitToMarkers, fitToCoordinates, animateToMarker etc..  are all zooming all the way in without any possibility to adjust how zoomed in the animation should be. If you adjust with maxZoomLevel you aren't able to zoom in manually to read street names or navigate.
