### ISSUE TITLE
How to see all the plotted markers in map?

### ISSUE THREAD

**Issue by nicoaureliovillanueva** [react-community/react-native-maps#2018]
Nice work on this! But i have a one question?

I have a dynamic markers. i want to see all the markers in the map? Is this possible to this project? I want to see it with a perfect zoom level. Thanks Alot more powers!

**Comment by rborn** [comment]
Please update the issue with the template, and also give more details on what you need. I'm not sure I understand.

**Comment by alvelig** [comment]
@nicoaureliovillanueva I think if you expressed in Spanish we could understand you better XD
There's a #175 (fitToElements)
