### ISSUE TITLE
Empty (gray) map after installing react-native-onesignal on Android

### ISSUE THREAD

**Issue by lucasharada** [react-community/react-native-maps#2020]
### Is this a bug report?

Yes. I've installed `react-native-maps`, had some issues with the version of the `play-services` (had to set to `11.+`), but got it to work properly. When installing `react-native-onesignal`, the FAQ recommends setting the `app.gradle` as [follows](https://github.com/geektimecoil/react-native-onesignal#issue-4---make-react-native-onesignal-work-with-react-native-maps).

I tried to use the recommended version on `react-native-onesignal` and the version that was working previously, but none got to work. Both of them just loads a gray map with Google logo on the bottom left corner.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

"react": "16.0.0",
"react-native": "0.51.0",
"react-native-maps": "0.19.0",
"react-native-onesignal": "3.0.9"

Target platform: Android 6.0

### Steps to Reproduce

(Write your steps here:)

1. Start a new project
2. Include `react-native-maps`
3. Include `react-native-onesignal`

### Expected Behavior

Both libs to work properly.

(Write what you thought would happen.)

### Actual Behavior

Only the `react-native-onesignal` lib worked properly. `react-native-maps` doesn't load the map, leaving a gray background with Google logo on the bottom left corner.

<img width="345" alt="captura de tela 2018-02-08 as 13 17 09" src="https://user-images.githubusercontent.com/18669473/35984096-6f19302e-0cd2-11e8-81dd-96973bf57fde.png">

### Reproducible Demo

Cannot share the project.

**Comment by rborn** [comment]
That's a google api key problem.

**Comment by lucasharada** [comment]
@rborn Anything related to versions or Google Console-only problem?

**Comment by rborn** [comment]
When the map renders the grey background and you can see the google logo it's a bad key. So yes, console only (you need to add the correct key in the app)

**Comment by lucasharada** [comment]
That was it.

**Comment by alvelig** [comment]
Duplicate of #118 and numerous more XD

**Comment by rohithramachandran** [comment]
Same issue Here.The key is correct.But still loads the blank map after the installation of react-native-onesignal
Here is my build.gradle

```  
    compile project(':react-native-onesignal')
    compile "com.facebook.react:react-native:+" 
    compile project(':react-native-maps')
    compile 'com.google.android.gms:play-services-location:+'
```

**Comment by ngocphat-fsdev** [comment]
get a Google Cloud API key at https://developers.google.com/maps/documentation/ios-sdk/get-api-key.
Follow the instruction to solve the problem. God bless you.
