### ISSUE TITLE
Use a local image as map

### ISSUE THREAD

**Issue by hanselsen** [react-community/react-native-maps#2033]
I want to use `react-native-maps` for showing a map of a building or zoo or something.  
The map will also show custom (clustered) markers.  
I tried to load a `LocalTile` but that's showing the same image over and over again ofcourse.  
  
Is there someone with insights on how to make this work? Maybe a local tile generator?

**Comment by alvelig** [comment]
#2022 ?

**Comment by hanselsen** [comment]
This is not a question for showing an image above a Google Maps for example. I don't need an actual map provider. Only my own map.

**Comment by g3r4n** [comment]
@hanselsen can you give us a snippet of your code to understand your issue ?

**Comment by hanselsen** [comment]
I can tell you how I got this working.  
I downloaded picture which is rectangular. Then I used my native module to add whitespace around the image so that it becomes square and from this point, I created the tiles to store locally and use `LocalTile` to show the image in my map.

**Comment by AdamGerthel** [comment]
@hanselsen could you elaborate on you accomplished this? Did you use react-native-maps along with a custom map (i.e image)?
