### ISSUE TITLE
Can't npm install, unexpected token.

### ISSUE THREAD

**Issue by Goblaz** [react-community/react-native-maps#2040]
I'm currently attempting to install this package and I run across the following error when executing npm install react-native-maps --save:

Unexpected token < in JSON at position 6708.

Has anyone else seen this that has tried to install this recently?

**Comment by alvelig** [comment]
As far as I see you managed to overcome this.

**Comment by Goblaz** [comment]
I overcame it with yarn. Using NPM still results in this error.
