### ISSUE TITLE
Android app crashing as soon as MapView is rendered.

### ISSUE THREAD

**Issue by Goblaz** [react-community/react-native-maps#2041]
I'm currently testing on an emulator with android 5.1. Everything seems to be linked correctly as I'm able to build and run the app just fine. However, when I get to a component that renders MapView the app crashes with no error. Just says it had to stop. I have no error and nothing to go on, has anyone else run into this?

**Comment by wkoutre** [comment]
@Goblaz There's always an error :)

Run the Android debugger before launching your app -- either in Android Studio or via terminal with the `adb logcat` command.

Clear logs right before you're about to render a component with `MapView`, enter the component and let your app crash, immediately copy/paste the logs, and report back.

**Comment by Goblaz** [comment]
ADB Logs:


--------- beginning of main
W/unknown:ViewManagerPropertyUpdater( 3356): Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
D/AndroidRuntime( 3356): Shutting down VM
--------- beginning of crash
E/AndroidRuntime( 3356): FATAL EXCEPTION: main
E/AndroidRuntime( 3356): Process: com.myapp, PID: 3356
E/AndroidRuntime( 3356): java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zzo
)"
E/AndroidRuntime( 3356):        at com.google.android.gms.dynamic.zza.zza(Unknown Source)
E/AndroidRuntime( 3356):        at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
E/AndroidRuntime( 3356):        at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
E/AndroidRuntime( 3356):        at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:128)
E/AndroidRuntime( 3356):        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:64)
E/AndroidRuntime( 3356):        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
E/AndroidRuntime( 3356):        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
E/AndroidRuntime( 3356):        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224)
E/AndroidRuntime( 3356):        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
E/AndroidRuntime( 3356):        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIView
OperationQueue.java:1010)
E/AndroidRuntime( 3356):        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:9
81)
E/AndroidRuntime( 3356):        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
E/AndroidRuntime( 3356):        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)

E/AndroidRuntime( 3356):        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
E/AndroidRuntime( 3356):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
E/AndroidRuntime( 3356):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime( 3356):        at android.view.Choreographer.doFrame(Choreographer.java:549)
E/AndroidRuntime( 3356):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime( 3356):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 3356):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 3356):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3356):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 3356):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3356):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3356):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 3356):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
--------- beginning of system
W/ActivityManager( 1526):   Force finishing activity 1 com.myapp/.MainActivity
D/gralloc_ranchu( 1167): gralloc_alloc: Creating ashmem region of size 331776
D/        ( 1526): HostConnection::get() New Host Connection established 0xa057f650, tid 1735
W/        ( 1526): Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1
E/EGL_emulation( 1167): tid 1167: eglCreateSyncKHR(1865): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/OpenGLRenderer( 1526): Initialized EGL, version 1.4
D/EGL_emulation( 1526): eglCreateContext: 0xa2424580: maj 2 min 0 rcv 2
D/EGL_emulation( 1526): eglMakeCurrent: 0xa2424580: ver 2 0
D/EGL_emulation( 1526): eglMakeCurrent: 0xa2424580: ver 2 0
W/ActivityManager( 1526): Activity pause timeout for ActivityRecord{2617b93e u0 com.myapp/.MainActivity t71 f}
D/EGL_emulation( 1865): eglMakeCurrent: 0xae834fa0: ver 2 0
D/EGL_emulation( 1865): eglMakeCurrent: 0xae834fa0: ver 2 0
D/EGL_emulation( 1865): eglMakeCurrent: 0xae834fa0: ver 2 0
D/EGL_emulation( 1865): eglMakeCurrent: 0xae834fa0: ver 2 0
W/OpenGLRenderer( 1865): Incorrectly called buildLayer on View: aep, destroying layer...
D/EGL_emulation( 1865): eglMakeCurrent: 0xae834fa0: ver 2 0
W/ResourceType( 1636): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1636): Failure retrieving resources for com.myapp: Resource ID #0x0
W/AudioTrack( 1526): AUDIO_OUTPUT_FLAG_FAST denied by client
I/Process ( 3356): Sending signal. PID: 3356 SIG: 9
W/InputDispatcher( 1526): channel '17112fb4 com.myapp/com.myapp.MainActivity (server)' ~ Consumer closed input channel or an error occurred.
 events=0x9
E/InputDispatcher( 1526): channel '17112fb4 com.myapp/com.myapp.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed
!
I/WindowState( 1526): WIN DEATH: Window{17112fb4 u0 com.myapp/com.myapp.MainActivity}
W/libprocessgroup( 1526): failed to open /acct/uid_10071/pid_3356/cgroup.procs: No such file or directory
W/InputDispatcher( 1526): Attempted to unregister already unregistered input channel '17112fb4 com.myapp/com.myapp.MainActivity (server)'
I/ActivityManager( 1526): Process com.myapp (pid 3356) has died
D/EGL_emulation( 1526): eglMakeCurrent: 0xa2424580: ver 2 0
D/OpenGLRenderer( 1526): endAllStagingAnimators on 0xb3d93f80 (RippleDrawable) with handle 0xa058f5f0
W/InputMethodManagerService( 1526): Got RemoteException sending setActive(false) notification to pid 3356 uid 10071
I/MicrophoneInputStream( 1996): mic_starting gzi@2efe6e03
E/audio_hw_generic( 1176): Error opening input stream format 1, channel_mask 0010, sample_rate 16000
I/HotwordRecognitionRnr( 1996): Starting hotword detection.
I/AudioFlinger( 1176): AudioFlinger's thread 0xb593a000 ready to run
I/Icing   ( 2132): IndexChimeraService.getServiceInterface callingPackage=com.google.android.googlequicksearchbox componentName=null serviceId=21
I/MicrophoneInputStream( 1996): mic_started gzi@2efe6e03
I/HotwordWorker( 1996): onReady
I/Icing   ( 2132): Usage reports ok 2, Failed Usage reports 0, indexed 0, rejected 0, imm upload true

**Comment by Goblaz** [comment]
I think this is to due with google play services.

**Comment by Goblaz** [comment]
It was do to Google Play Services, a quick:
compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-location:+'
    compile 'com.google.android.gms:play-services-maps:+'

in the build.gradle solved it.

**Comment by minhphung210** [comment]
@Goblaz  how do you solve it

**Comment by taqwaaziz95** [comment]
> @Goblaz how do you solve it

simply edit your yourapp/android/app/build.gradle
