### ISSUE TITLE
Issues while rendering Google Maps on iOS

### ISSUE THREAD

**Issue by iosfitness** [react-community/react-native-maps#2042]
Please review the mechanism for rendering Google Maps on iOS and recommend corrections to improve/revise the approach.

Issue: The UI gets stuck if I quickly click the back button while the reverse geocode is still fetching. However, the performance is way better for Apple Maps for the same use-case. Also, I keep receiving memory warning while rendering Google Maps.

Library used for reverse geocode : https://github.com/devfd/react-native-geocoder

Code Snippet : 

import React, { Component } from 'react';
import {
    Platform,
    StyleSheet,
    Text,
    View,
    TouchableHighlight,
    TouchableOpacity
} from 'react-native';
import MapView, { PROVIDER_GOOGLE , Callout } from 'react-native-maps'
import Geocoder from 'react-native-geocoder';
import { Header } from 'react-native-elements';

let self;
export default class MapScreen extends Component {

    static navigationOptions = ({ navigation }) => {
        return {
            header: <Header
                leftComponent={{ icon: 'arrow-back', color: '#000', onPress: () => { navigation.goBack() } }}
                centerComponent={{ text: 'Inspection Maps', style: { color: '#000', fontSize: 18 } }}
                outerContainerStyles={{ backgroundColor: '#ffffff' }}
            />
        };
    };

    constructor(props) {
        super(props);
        this.mapRef = null;
        this.state = {
            mapMarkers: null,
            initialized: false,
            identifiers: []
        }
        self = this;
    }

    componentWillMount() {
        this.getMapsMarker().done();
    }

    onMapReady = () => {
        this.setState({ initialized: true });
      };

    componentDidUpdate() {
        setTimeout(() => {
            this.state.mapMarkers ? this.focus() : null;
        }, 1000);
    }

    focus() {
        this.mapRef.fitToSuppliedMarkers(
            this.state.identifiers,
            true, // not animated
        );
    }

    async getMapsMarker() {
        let incidenceData = this.props.navigation.state.params;
        let identifiers = []
        for (var i = 0; i < incidenceData.length; i++) {
            let incidenceObject = incidenceData[i];
            let address = '';
            if (incidenceObject.street) {
                address = address + incidenceObject.street + ',';
            }
            if (incidenceObject.city) {
                address = address + incidenceObject.city + ',';
            }
            if (incidenceObject.country) {
                address = address + incidenceObject.country + ',';
            }
            if (incidenceObject.postalCode) {
                address = address + incidenceObject.postalCode;
            }
            console.log(address)
            let latitude = 0;
            let longitude = 0;
            try {
                const res = await Geocoder.geocodeAddress(address)
                console.log('pos', i)
                console.log('geocode', res.length > 0 ? res[0].position : '')
                latitude = res.length > 0 ? res[0].position.lat : 0;
                longitude = res.length > 0 ? res[0].position.lng : 0
            } catch (err) {
                console.log(err)
            }
            let coordinates = {
                latitude,
                longitude,
            }
            incidenceData[i].coordinates = coordinates;

        }
        this.setState({
            mapMarkers: incidenceData,
            identifiers
        })
    }

    render() {
        return (
            <View style={styles.container}>
                <MapView
                    style={styles.map}
                    onMapReady={this.onMapReady}
                    provider={PROVIDER_GOOGLE}
                    ref={(ref) => { this.mapRef = ref }}
                    style={styles.map}>
                    {this.state.mapMarkers && this.state.mapMarkers.map((marker, i) => {
                        return (
                            <MapView.Marker.Animated
                                identifier={marker.subject}
                                key={marker.entity_id}
                                coordinate={marker.coordinates}
                                tracksViewChanges={!this.state.initialized}
                                >
                                <MapView.Callout onPress={() => {
                                    this.navigateToForms();
                                }}>
                                    <TouchableOpacity >
                                        <Text>{marker.subject}</Text>
                                    </TouchableOpacity>
                                </MapView.Callout>
                            </MapView.Marker.Animated>
                        )
                    })}
                </MapView>
            </View>
        );
    }

    navigateToForms() {
        const { navigate } = this.props.navigation;
        navigate('formScreen')
    }

}
const styles = StyleSheet.create({
    container: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'flex-end',
        alignItems: 'center',

    },
    map: {
        ...StyleSheet.absoluteFillObject,
    }
});

Thanks in advance

**Comment by alvelig** [comment]
This might happen because you are trying to render when it's already unmounted.

Try something like that (not tested, just an idea)
```
componentWillUnmount() {
  this.unmounted = true
}

async getMapsMarker() {
...
if(!this.unmounted) {
 this.setState({
        mapMarkers: incidenceData,
        identifiers
    })
}
}
```

Could you please make a project to be able to clone and describe steps to reproduce.

**Comment by iosfitness** [comment]
@alvelig I will surely try this. I have also referred to https://github.com/Rudolph-Miller/RNGoogleMapExample but I'm unable to see the markers. 
If possible, please try this sample and share your feedback. 
Thanks..

**Comment by rborn** [comment]
Closing, old issue.
