### ISSUE TITLE
Show title on marker

### ISSUE THREAD

**Issue by sofiane-soufi** [react-community/react-native-maps#2044]
Hello.

I would like to know if anyone knows how to show the title of a marker without having to press on it.

Example:

![kxz6nr5gq2_ynzfuncugkw](https://user-images.githubusercontent.com/14898088/36746714-02a7dda2-1bc1-11e8-9d67-ee15fa26663c.png)

Thank you!

**Comment by alvelig** [comment]
You need to make the title a part of the marker.

```
<Marker><Text>{text}</Text><Image ... /></Marker>
```
Marker's image prop also can do instead of <Image />

**Comment by sofiane-soufi** [comment]
Thank you!

**Comment by hegelstad** [comment]
@alvelig Is it possible to keep the native marker and add a react component beneath or above the marker (much like a always on callout for each marker)? Ideally moving itself to avoid borders?

**Comment by alvelig** [comment]
@hegelstad didn't get your idea. Place native marker and another one with offset?

**Comment by hegelstad** [comment]
@alvelig yes. https://github.com/react-community/react-native-maps/issues/2166

**Comment by NithinKulal** [comment]
What if the marker rotated..?

**Comment by rosnaib11** [comment]
Same problem what if marker is rotated? I tried the text rotated too.

**Comment by Pajimo** [comment]
What worked for me: 

Give the particular marker a ref of lets say 'originMarker', on Component mount, do this. originMarker?.current?.showCallout();
