### ISSUE TITLE
react-native-maps@0.19.0 requires a peer of react@16.0.0 and react-native@0.51.0

### ISSUE THREAD

**Issue by iegik** [react-community/react-native-maps#2045]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.53.3
    react: 16.2.0

### Steps to Reproduce

```
npm install expo@latest # expo@25.0.0
```

### Actual Behavior

```
npm WARN react-native-maps@0.19.0 requires a peer of react@16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-maps@0.19.0 requires a peer of react-native@0.51.0 but none is installed. You must install peer dependencies yourself.
```

https://github.com/react-community/react-native-maps/blob/v0.19.0/package.json#L36

**Comment by ecarrera** [comment]
├── UNMET PEER DEPENDENCY react@16.2.0
├── UNMET PEER DEPENDENCY react-native@0.53.3
└─┬ react-native-maps@0.20.1
  ├─┬ babel-plugin-module-resolver@2.7.1
  │ ├─┬ find-babel-config@1.1.0
  │ │ └── path-exists@3.0.0
  │ └── resolve@1.5.0
  └─┬ babel-preset-react-native@1.9.0
    └── babel-plugin-react-transform@2.0.2

npm WARN react-native-maps@0.20.1 requires a peer of react@16.0.0 but none was installed.
npm WARN react-native-maps@0.20.1 requires a peer of react-native@0.51.0 but none was installed.

**Comment by AzarouAmine** [comment]
Had the same problem as yours, solver it by changing dependencies in package.json manually:
Was:
```
"dependencies": {
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.0",
    "react-native-maps": "0.20.1"
  },
```

Changed to

```
"dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-maps": "0.20.1"
  },
```

Then ran npm install.

**Comment by guhungry** [comment]
Fixed was landed in master branch (https://github.com/react-community/react-native-maps/commit/53b374b189599590fc5a5c20c0468f22c1e80598). Waiting for next release.

**Comment by rborn** [comment]
Yes, please use the master for now, we are a little slow in publishing on npm.
