### ISSUE TITLE
Requiring unknown module "undefined".

### ISSUE THREAD

**Issue by AzarouAmine** [react-community/react-native-maps#2051]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, repeated the steps 3 times with different projects. Same result.

### Environment

    react-native: 0.54
    react: 16.3.0-alpha.1 react-native-maps: 0.20.1
   

### Actual Behavior

The MapView import doesn't recognize "react-native-maps" as a module.
[Screenshot](https://i.imgur.com/kJK7SvN.png)

**Comment by AzarouAmine** [comment]
Solved the issue by changing dependencies in package.json manually:
Was:
```
"dependencies": {
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.0",
    "react-native-maps": "0.20.1"
  },
```

Changed to

```
"dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-maps": "0.20.1"
  },
```

Then ran npm install.

**Comment by hrl7** [comment]
I have same issue.
I changed react-native to `0.54.0-rc.3`, and then it works.
[this commit](https://github.com/facebook/react-native/commit/f4fde9d84a5d12051173ee8e13754144b1f08903) may cause this problem.

https://github.com/react-community/react-native-maps/blob/master/index.js#L12
those module cannot be imported.

**Comment by VinceBT** [comment]
Your fix worked for me

**Comment by andersonaddo** [comment]
I got the same error, upgrading to 0.54.0-rc.3 worked.

**Comment by hrl7** [comment]
I sent PR to solve this and it was merged.
https://github.com/react-community/react-native-maps/pull/2053
this PR enables to import modules in react-native@0.54.0

**Comment by VinceBT** [comment]
@altissave1 The aim of this issue is to make RNMaps@0.20.1 compatible with RN@0.54.0

**Comment by Tamiyadd** [comment]
waiting for release too

**Comment by rborn** [comment]
@Tamiyadd try to install the master from git and let us know if it works

**Comment by Tamiyadd** [comment]
@rborn it works!

**Comment by jamesDZ** [comment]
@AzarouAmine I used the given steps but same error every time. 
If it is possible please send the steps to solve.

**Comment by rishabhmathur1693** [comment]
I'm facing the same issue for past few days as @jamesDZ . It would be really helpful if someone can provide insight on what could be happening on either react native side or react native maps side.

**Comment by VinceBT** [comment]
@jamesDZ @rishabhmathur1693 The only fix for the moment is [this](https://github.com/react-community/react-native-maps/issues/2051#issuecomment-370119631)

Make sure of [this point ](https://github.com/react-community/react-native-maps/issues/2051#issuecomment-370179379) too

Now you can only wait for the next release like everyone

**Comment by rishabhmathur1693** [comment]
@VinceBT Thanks for your response, but I didn't helped me much. 

After changing react-native to 0.54.0-rc.3, NPM gave me this error -

![screen shot 2018-03-08 at 9 19 12 pm](https://user-images.githubusercontent.com/6391138/37160512-6a02f57a-2316-11e8-8b61-d5e924e8ad4c.png)

Then, I looked up for this issue and I found its resolution on this link - 

[https://github.com/facebook/react-native/issues/18010](url)

After changing react-native version to 0.54.0-rc.4, my package.json looks like this - 

`{
  "name": "GoogleMapDemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0-rc.3",
    "react-native-maps": "^0.20.1"
  },
  "devDependencies": {
    "babel-jest": "22.4.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "^16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  }
}`

Then, I executed the command `npm install` and it completed successfully. After that I stopped the `react-native start` command and restarted it with clear cache option.

When the service is started, I ran `react-native run-ios` & it again gave me the same error like before - 

![screen shot 2018-03-08 at 9 23 35 pm](https://user-images.githubusercontent.com/6391138/37160793-0b6f35c2-2317-11e8-93fe-2a44d4ee58e2.png)


Please point out if I had done something wrong or should've done something else.

**Comment by rborn** [comment]
@rishabhmathur1693  use

```
 "react-native-maps": "https://github.com/react-community/react-native-maps.git",
```

**Comment by hrl7** [comment]
FYI: I wrote the document to solve this issue until it will be released.
I recommend to use [patch-package](https://www.npmjs.com/package/patch-package) in the aspect of maintainability.
https://gist.github.com/hrl7/916ce48ba3e2d62dcaee9540f304a504#file-use-rn-maps0-20-1-in-rn0-54-0-md

**Comment by VinceBT** [comment]
@rishabhmathur1693 You wont have the babylon error if you install it with yarn

**Comment by sydneywu** [comment]
I faced this issue too and this is my experience and eventual temp solution.

Before i start, i would like to point out that before I even reached this error of 'unknown module "undefined"', i was following the documentation and realized i need to  need to comment out "BatchedBridge" from the Podfile to do pod install.

After pod install and following further into the document, i encounter 'unknown module "undefined"' when trying to run it on IOS. So following the suggested solution on this page, i encountered the following:

1. When i try to use "react-native": "0.54.0-rc.3" and npm install, i encounter the issue of "EUNSUPPORTED ISSUE protocol". The way to fix this is to use yarn to install. But after that i still faces issue with 'unknown module "undefined"'.

2 Using "react-native": "0.54.0-rc.4" can overcome the "EUNSUPPORTED ISSUE protocol" but still result in 'unknown module "undefined"'.

3. Using master branch of react-native-maps by "react-native-maps": "https://github.com/react-community/react-native-maps.git" seems to not throw error. But for some reason i keep getting the react-native error of 'DeltaPatcher should receive a fresh Delta when being initialized'. I think this error is a bug from react-native. But before using master branch of react-native-maps, i was able to avoid this error 50% of the time when i refresh my app. But after using master branch, this error appears 100%.

So the temporarily fix for me is to use version "react-native": "^0.52.3". Specifically i did the following:
npm uninstall react-native
npm install react-native@0.52.3
pod install (in ios folder. Also don't have to comment out BatchedBridge)
reopen xcode (and product clean. Not sure if this is neccessary)
run on IOS and the map should work.

**Comment by rishabhmathur1693** [comment]
@sydneywu Thanks for your solution. I did everything that you mentioned, but still I got this error while building - 
![screen shot 2018-03-09 at 12 28 18 pm](https://user-images.githubusercontent.com/6391138/37195055-455ec6f0-2397-11e8-8615-eef7c546a29b.png)

So, I added `DevSupport` in pod file and ran `pod install`

After doing all that my package. json looks like this - 

`
{
  "name": "GoogleMapDemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "^16.3.0-alpha.1",
    "react-native": "^0.52.3",
    "react-native-maps": "https://github.com/react-community/react-native-maps.git"
  },
  "devDependencies": {
    "babel-jest": "22.4.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "^16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
I ran `react-native run-ios` and this time it build successfully. Only one thing Map was not getting displayed in the app. It's just a white screen 

![screen shot 2018-03-09 at 12 45 19 pm](https://user-images.githubusercontent.com/6391138/37195187-c7ef2dd0-2397-11e8-96e8-23afaf17e59f.png)

I looked up a solution and added style to MapView - 

`
mapStyle: {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0
  },
`

Still nothing. Could it be due to the reduced version of react that we are using?

**Comment by VinceBT** [comment]
@rishabhmathur1693 @sydneywu As said in https://github.com/react-community/react-native-maps/issues/2051#issuecomment-371578887 you wont have the unsupported protocol error if you install 0.54.0-rc.3 with yarn.
```sh
npm i -g yarn
yarn add react-native@0.54.0-rc.3
```

**Comment by rishabhmathur1693** [comment]
@VinceBT @sydneywu 
Using yarn resolved the issue for installing react-native 0.54.0-rc.3. Google Map is finallly displayed on screen.

![screen shot 2018-03-09 at 4 26 07 pm](https://user-images.githubusercontent.com/6391138/37204362-9b6ca7dc-23b6-11e8-8551-9abc4f6de256.png)

Thanks everyone for all the assistance.

**Comment by VinceBT** [comment]
@christopherdro Could there be a release after this PR ?

**Comment by jamesDZ** [comment]
Thanks @VinceBT @sydneywu and @rishabhmathur1693  with your effort issue resolved.

**Comment by esutton** [comment]
Work-around to use master results in iOS ** BUILD FAILED **.  

Rolling back to **0.53** ....

````
"react": "^16.2.0",
"react-native": "^0.54.1",
"react-native-maps": "https://github.com/react-community/react-native-maps.git",
````

** BUILD FAILED **
````
The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm
	Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /react-native/my-app/source/ios/build/Build/Intermediates.noindex/
AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/
AIRGoogleMapPolygonManager.o AirGoogleMaps/AIRGoogleMapPolygonManager.m 
normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
````

**Comment by sydneywu** [comment]
@VinceBT I tried yarn add react-native@0.54.0-rc.3. I am still getting the same 'unknown module "undefined" error'. For those of you who did it. May i asked whether you:

1) comment out "BatchedBridge" in podFile
2) run pod update yoga
3) run pod update React/Core

**Comment by esutton** [comment]
Yet another silent metro side effect.

[Requiring unknown module "undefined" #152](https://github.com/facebook/metro/issues/152)

> The problem is happening when there are 2 requires to the same file but with different forms in the same module, for example:
> ````
> const a = require('./a');
> const a1 = require('./a.js');
> This is what happened to react-native-maps (although they've just fixed it in react-community/react-native-maps@0e201a9).
> ````
>
> This is what happened to react-native-maps (although they've just fixed it in react-community/react-native-maps@0e201a9).

**Comment by maikenmadsen92** [comment]
I just set this in the package.json:

  "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-maps": "https://github.com/react-community/react-native-maps.git"

Now it works.

**Comment by Arshiamidos** [comment]
i upgrade RN for this bug #18359
and now :|

**Comment by Arshiamidos** [comment]
"native-base": "^2.3.10",
"react": "^16.3.0-alpha.1",
"react-native": "0.54.0-rc.3",
"react-native-maps": "^0.20.1"

with this package i solved my solution 
it relate to react-native-maps

**Comment by Arshiamidos** [comment]
i fixed this issue with react-native-maps 

```
"dependencies": {
    "native-base": "^2.3.10",
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-maps": "^0.20.1"
  },
```

**Comment by arapocket** [comment]
The code here fixed this for me

https://github.com/react-community/react-native-maps/commit/0e201a9a2ca833728b20526049c172e7240e4d7c

**Comment by sibelius** [comment]
can we plan a new release?

**Comment by magichim** [comment]
My package

    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-maps": "https://github.com/react-community/react-native-maps.git"

When I use Mapview, nothing is showing in emulator.

What should I do? :( Help [`me...`](url)

<img width="362" alt="2018-03-15 3 55 00" src="https://user-images.githubusercontent.com/5843652/37448386-82b540ac-2869-11e8-8abf-5ee06405e608.png">

**Comment by wbattel4607** [comment]
@hrl7 @rborn can we please have a new release?

**Comment by danZheng1993** [comment]
@hrl7 's solution works for our project too.
When are you guys going to release the new build which changes?
Really appreciate it.

**Comment by xxstefanoxx** [comment]
hi, i get red error undifined, this is my configuration:
"dependencies": {
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-maps": "^0.20.1"
  }
i get the error in ios simulator and real device. 
I've install with pod.
https://github.com/react-community/react-native-maps/blob/master/docs/installation.md
please help :)

**Comment by wbattel4607** [comment]
@xxstefanoxx change `"react-native-maps": "^0.20.1"` to `"react-native-maps": "https://github.com/react-community/react-native-maps.git"`

**Comment by xxstefanoxx** [comment]
I have to give back the command npm install?

**Comment by wbattel4607** [comment]
@xxstefanoxx after changing the version in `package.json` you will need to re-install the package with the command `npm install`

**Comment by xxstefanoxx** [comment]
now works with emulatore but xcode give this error:
'GMUKMLParser.h' file not found AIRGoogleMap.m

**Comment by wbattel4607** [comment]
@xxstefanoxx see proposed solutions in this issue https://github.com/react-community/react-native-maps/issues/2066

**Comment by wbattel4607** [comment]
This is still holding us up. We've tried using the fix on master but #2066 is preventing us from doing so. @rborn @hrl7 when will a new version be released? There are a ton of changes on master but the last version was released 40 days ago.

We're stuck into a corner right now. React Native 0.53 has a debugging issue that prevents us from using it and we can't get react-native-maps working on 0.54 at all.

**Comment by rborn** [comment]
@wbattel4607 I don't control the releases sadly :(
@christopherdro does but I think he's overloaded atm as he's not responding.

**Comment by christopherdro** [comment]
Hey there. Right now I am pretty backed up with work so what is mainly limiting me from doing a release is putting the release notes together.

If someone from the community can create the release commit as a PR I'll be more than happy to merge and do a release. Here is a reference commit to what needs to be changed for a new release.

https://github.com/react-community/react-native-maps/commit/0d376464a3b75edb8004cce0cfc9285fcd4a0816

**Comment by jerolimov** [comment]
The master version works fine (for me). Whats holding back a new release?

**Comment by rborn** [comment]
@jerolimov this:  https://github.com/react-community/react-native-maps/issues/2051#issuecomment-376191505

**Comment by wbattel4607** [comment]
I guess I'll make a PR then... ¯\_(ツ)_/¯

**Comment by Ukiand1** [comment]
So there was an update for react, react-native and react-native-maps, the configuration that is **currently working** for me is: 

```
package.json {
    "dependencies": {
        "react": "16.3.0",
        "react-native": "0.55.0",
        "react-native-maps": "^0.21.0"
  }
}
```
**Also I added additional things to make project work**

_your-project/android/build.gradle_

```
buildscript {
    repositories {
        jcenter()
        google() // add this
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0' // change gradle to this version

    }
}
```

I used the old way of implementation (not the recommended project-wide properties)

_your-project/android/app/build.gradle_

```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-maps')
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:11.0.1' // these both to version 11.0.1
    compile 'com.google.android.gms:play-services-maps:11.0.1'
}

```

and the last thing I changed is 

_your-project/android/gradle/wrapper/gradle-wrapper.properties_

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip // update to this version

```

Hope this helps, cheers! 👍

**Comment by herarya** [comment]
@Arshiamidos thanks bro, now works  💃

**Comment by mcandrak** [comment]
how to change the package.json ?

**Comment by Arshiamidos** [comment]
@herarya  u r welcome bro🤗.

**Comment by mcandrak** [comment]
i try this, but not working, 
i got this

Error type 3
Error: Activity class {com.awesomeproject/com.awesomeproject.MainActivity} does not exist.

**Comment by mcandrak** [comment]
the error is fixed, but after that this ih just showing a white blank screen , somebody know how to fix it ?

**Comment by RishavKumar-3796** [comment]
> the error is fixed, but after that this ih just showing a white blank screen , somebody know how to fix it ?

@mcandrak you have to give style to map.. give it absolute position of top, bottom, left and right to 0

**Comment by CyrilChen** [comment]
I got the same error ,but finally I fix it by changed a path of a required image
I hope this can help some one else
