### ISSUE TITLE
Cannot use animateToBearing and animateToViewingAngle function

### ISSUE THREAD

**Issue by toanhosss** [react-community/react-native-maps#2052]
I implement google maps on Expo latest version SDK 25.0.0,

I get this error when call animateToBearing or animateToViewingAngle:

this.mapRef.animateToBearing(45, 1000);
Error:
undefined is not an object (evaluating 'this._mapManagerCommand(name).apply')

**Comment by rborn** [comment]
@toanhosss this might be an issue with expo as it uses an older map module (0.19).

Closing as we start to enforce the issue template. Sorry.
