### ISSUE TITLE
Map options showsBuildings, showsCompass not working (Expo MapView))

### ISSUE THREAD

**Issue by iamlasse** [react-community/react-native-maps#2054]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

Expo 25.0.0
React Native 0.52.0
React 16.2.0

IOS Simulator 11.2

### Steps to Reproduce
Imported MapView from Expo, Added MapView component and added 
showsBuildings={true}
showsMyLocationButton={true}
        showsCompass={true}
        onPanDrag={updateRegion}
        showsBuildings={true}
        minZoomLevel={12}
        maxZoomLevel={0}
        fitToElements={true}

None of these properties/options show on the map.

1. 2. 3.

### Expected Behavior
Expected to see buildings, compass on Map.

### Actual Behavior

Don't see any of these on the map. See screenshot

![screen shot 2018-03-03 at 1 39 56 pm](https://user-images.githubusercontent.com/556886/36939603-6acc8d72-1ee8-11e8-8b3d-92912ae4af9d.png)

**Comment by rborn** [comment]
@iamlasse expo uses react-native-maps[ 0.19 ](https://github.com/expo/expo-sdk/blob/master/package.json#L60) and usually it takes a little for them to update to the last version.

You could try to update the module manually and see if it solves your issues.
Also on npm we don't always have the very last version, so you might wanna use the github one.

I'll close the issue now, but please comment and ping me if you manage to update the module and is not fixing the problem.
