### ISSUE TITLE
Show callout without marker press

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-community/react-native-maps#2056]
Is it possible to show callouts on marker without marker press ? I mean I should not need to press the marker for viewing callout.

**Comment by rborn** [comment]
Closing as we start to enforce the issue template. Sorry.

**Comment by minhchienwikipedia** [comment]
Any update with this issue?

**Comment by Shiva207892** [comment]
Any update with this issue? I want to show callout on my markerData as user selects from search suggestion not by tapping marker
