### ISSUE TITLE
Android doesn't compile with current master as dependency

### ISSUE THREAD

**Issue by bramus** [react-community/react-native-maps#2058]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native 0.54.0
react 16.3.0-alpha.1
Android compileSDKVersion 23
Android buildToolsVersion "23.0.1"

### Steps to Reproduce

1. Create a new RN project
2. Add the master of `react-native-maps` as a dependency
3. `react-native run-android`

### Expected Behavior

Get the app compiled and run it

### Actual Behavior

App doesn't compile. Getting back this:

````
:react-native-maps:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/bramus/repos/evpoint/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:186: error: cannot find symbol
    map.setOnUserLocationChangeListener(new GoogleMap.OnUserLocationChangeListener() {
                                                     ^
  symbol:   class OnUserLocationChangeListener
  location: class GoogleMap
Note: /Users/bramus/repos/evpoint/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-maps:compileReleaseJavaWithJavac FAILED
````

### Going down the Rabbit Hole

A last minute change in PR https://github.com/react-community/react-native-maps/pull/2032 renamed `onMyLocationChange` to `onUserLocationChange`. Unfortunately this was rushed, and some function that shouldn't have been renamed got renamed after all.

E.g. The error above complains about `GoogleMap.OnUserLocationChangeListener()` which doesn't exist. Checking out the Android docs, [it should be `GoogleMap.OnMyLocationChangeListener()`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMyLocationChangeListener) _(which is depreated, but that's another story)_.

Even though I'm no Android Developer I've prepared some changes on a forked version over at https://github.com/bramus/react-native-maps/tree/android-locationchange-compile-hotfix, yet it's still not 100% working:
- Compilation here still stumbles over `location.getVerticalAccuracyMeters()`, even though there's a conditional around it.
- Not too sure about putting floats into `putDouble`, most likely they will need to be converted … the compiler doesn't complain though.

Perhaps a proper Android Dev, or the original author @dabit1, can pick this up further?

**Comment by zerazeru** [comment]
Indeed seems rushed, the ios build fails too, thanks to a syntax error.

**Comment by rborn** [comment]
@zerazeru could you work with @bramus for a common PR please? 🤗

**Comment by alvelig** [comment]
Applied hotfix.

**Comment by rborn** [comment]
@alvelig is this still an issue? I saw you applied a hotfix.

**Comment by alvelig** [comment]
@rborn @zerazeru @bramus could you please confirm that's this is not an issue anymore?

**Comment by bramus** [comment]
Just checked:
- Android: OK (`yarn run:android`)
- iOS: OK (`yarn build:ios && yarn run:ios`)

Closing.

**Comment by zerazeru** [comment]
Yes, ios builds now 👍

**Comment by arapocket** [comment]
....so what's the hotfix? I have this same issue.

**Comment by bramus** [comment]
@arapocket The hotfix is already on master: https://github.com/react-community/react-native-maps/commit/8f7bd9edbf2145f21664d282d73310457543a4e1
