### ISSUE TITLE
Show button on Map

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-community/react-native-maps#2060]
Guys, I have used 'MapView' and I need to use button on Map to implement some functionality. So how can I place button on Map ? Help needed

**Comment by alvelig** [comment]
Have Marker onPress if the button is location specific or place a button over the map as if it was another view (absolute positioning)

**Comment by ShaikhKabeer** [comment]
I tried by placing button on Map but it's giving me errors. Can post the example if you have.

**Comment by SirPhemmiey** [comment]
Any one to help?

**Comment by amsimoes** [comment]
@SirPhemmiey @ShaikhKabeer this does the trick: [SO answer](https://stackoverflow.com/a/51302355/6245942)

```javascript
<View style={{ flex: 1 }}>
    <MapView
      style={{ flex: 1 }}
    />
    <View
        style={{
            position: 'absolute',//use absolute position to show button on top of the map
            top: '50%', //for center align
            alignSelf: 'flex-end' //for align to right
        }}
    >
        <Button />
    </View>
</View>
```

**Comment by wecoon** [comment]
> 
> 
> @SirPhemmiey @ShaikhKabeer this does the trick: [SO answer](https://stackoverflow.com/a/51302355/6245942)
> 
> ```js
> <View style={{ flex: 1 }}>
>     <MapView
>       style={{ flex: 1 }}
>     />
>     <View
>         style={{
>             position: 'absolute',//use absolute position to show button on top of the map
>             top: '50%', //for center align
>             alignSelf: 'flex-end' //for align to right
>         }}
>     >
>         <Button />
>     </View>
> </View>
> ```

Thanks, I managed to get the button on top of the map, but it is not clickable. What could be the issue?
