### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "React/BatchedBridge

### ISSUE THREAD

**Issue by vinicius5581** [react-community/react-native-maps#2063]
### Is this a bug report?

Yes. 

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0",
    "react-native-maps": "^0.20.1"

  ***iOS , using AppleMaps or GoogleMaps

### Steps to Reproduce

**Steps**
```
$ npm install -g react-cli
$ react-cli init myProject
$ cd myProject
$ npm install
$ npm install react-native-maps --save 
$ cd ios/
$ vim Podfile
```

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myProject' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'react-native-maps', path: rn_maps_path

  pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
```
$ pod install
```

### Expected Behavior

I would expect the pod installation to succeed 

### Actual Behavior

```
pod install
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-google-maps` from `../node_modules/react-native-maps`
Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
[!] CocoaPods could not find compatible versions for pod "React/BatchedBridge":
  In Podfile:
    React/BatchedBridge (from `../node_modules/react-native`)

None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

[!] Automatically assigning platform `ios` with version `8.0` on target `maps` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

### Reproducible Demo

N/A

**Comment by vinicius5581** [comment]
at `myProject/node_modules`

<img width="266" alt="screenshot 2018-03-05 21 55 00" src="https://user-images.githubusercontent.com/1258955/37016210-ff768a6c-20bf-11e8-8a7c-075d52d865e0.png">

**Comment by rborn** [comment]
@vinicius5581 can you try a `pod update`?

**Comment by cryser29** [comment]
`BatchedBridge` was deleted in the latest release. It's mentioned in the [release notes](https://github.com/facebook/react-native/releases/tag/v0.54.0). So it looks like that it should be removed from `Pods` file.

**Comment by rborn** [comment]
@cryser29 @vinicius5581 can you run a test and confirm this? maybe even make a PR? 🤗

**Comment by ujwal-setlur** [comment]
Running into this too. Will remove BatchedBridge and test

**Comment by vinicius5581** [comment]
I did the same @ujwal-setlur  and now I got this:
<img width="399" alt="screenshot 2018-03-06 21 53 16" src="https://user-images.githubusercontent.com/1258955/37075882-cbe8cfb0-2188-11e8-8e55-91cf9cbcee78.png">

**Comment by ujwal-setlur** [comment]
It worked for me. Are your sure your packager is running?

**Comment by vinicius5581** [comment]
Ok @ujwal-setlur . I've created a fresh project and used the following Podfile, I successfully ran `pod install`.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myProject' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'react-native-maps', path: rn_maps_path

  pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

I don't know if that belongs to this thread anymore but after running `react-native run-ios` with the following `App.js` I got an error (attached below). I wonder if you can successfully run the `App.js` above or spot anything wrong with it. 

```
import React, { Component } from 'react';
import { View } from 'react-native';
import MapView from 'react-native-maps';

export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <MapView
            initialRegion={{
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}
        />
      </View>
    );
  }
}
```

Error:

<img width="401" alt="screenshot 2018-03-06 22 28 23" src="https://user-images.githubusercontent.com/1258955/37076987-b6481dbe-218d-11e8-84b3-7e47958374a9.png">

**Comment by ujwal-setlur** [comment]
This looks like you are pulling react-native-maps from a published release in npm. 

Please use the latest code from git. 

In package.json:

"react-native-maps": "github:react-community/react-native-maps"

**Comment by vinicius5581** [comment]
@ujwal-setlur , you are right. I've applied the change on package.json as you suggested and I got it up and running now. Thanks.

**Comment by ujwal-setlur** [comment]
Great! Hopefully, a new release will be pushed out soon so that we don't have to pull from git.

**Comment by vinicius5581** [comment]
Just for the sake of completeness here is a working sample `App.js`:

```
import React, { Component } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import MapView from 'react-native-maps';

export default class App extends Component {
  render() {
    const { region } = this.props;
    console.log(region);

    return (
      <View style ={styles.container}>
        <MapView
          style={styles.map}
          region={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121,
          }}
        >
        </MapView>
      </View>
    );
  }
}


const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    height: 400,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});
```

**Comment by vinicius5581** [comment]
Ops! I closed the issue but I'm not sure if I should do that before or after the PR been accepted. Please advise for future reference and I'll be happy to reopen if that is the case.

**Comment by rborn** [comment]
@vinicius5581 the issue has the solution in the comments, so it's ok to be closed 😀

**Comment by itinance** [comment]
FYI

In order to avoid this linker issue https://github.com/facebook/react-native/issues/15049:

> Undefined symbols for architecture arm64:
> "facebook::react::customJSCWrapper()", referenced from:
> 

 i had to Add 
"**CxxBridge**" to Podfile after removing **BatchBridge**.

**Comment by pavjacko** [comment]
If you still having issues I've created example project which runs with latest (at the point of writing) RN 0.56.0 and works with 'CxxBridge'
both iOS and tvOS project
https://www.npmjs.com/package/react-native-vanilla

**Comment by bramski** [comment]
Using 'CxxBridge' resolved my issue. It should really be aded to the changelog for React 0.54 where the removal of BatchedBridge was listed.  This would avoid others having to do a massive google search.

**Comment by itinance** [comment]
I can confirm (at least for RN 0.57):

```
- BatchedBridge
+ CxxBridge
```

Many thanks to @pavjacko & @bramski

**Comment by rborn** [comment]
I wonder why is this a problem 🤨
BatchedBridge isn't mentioned in the pod file install instructions

**Comment by itinance** [comment]
@rborn in former Versions of RN it was required. 

See also https://github.com/facebook/react-native/issues?page=5&q=BatchedBridge&utf8=%E2%9C%93

**Comment by rborn** [comment]
Maybe we could do a PR to the docs mentioning this for the cases where you upgrade? 😊

**Comment by itinance** [comment]
@rborn 

This was my PR adding batchedBridge in those Days, and it ended up that CxxBridge was added then instead for newer projects:

https://github.com/facebook/react-native-website/pull/131

(in my current issue i have just forgotten the change between both while upgrading an older project)
