### ISSUE TITLE
'GMUKMLParser.h' file not found AIRGoogleMap.m while building myProject on my Iphone with XCode

### ISSUE THREAD

**Issue by vinicius5581** [react-community/react-native-maps#2066]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

```
"react": "^16.3.0-alpha.1",
"react-native": "0.54.0",
"react-native-maps": "github:react-community/react-native-maps"
```

### Steps to Reproduce
```
$ npm install -g react-cli
$ react-cli init myProject
$ cd myProject
$ npm install
$ npm install react-native-maps --save 
$ cd ios/
$ vim Podfile // Podfile from docs/installation.md
$ pod install
$ vim App.js 
$ react-native run-ios
```

```
// App.js

import React, { Component } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import MapView from 'react-native-maps';

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      latitude: null,
      longitude: null,
      error: null,
    };
  }

  componentDidMount() {
    navigator.geolocation.getCurrentPosition(
      (position) => {
        console.log(position);
        const { accuracy, altitude, altitudeAccuracy, heading, latitude, longitude, speed } = position.coords;
        this.setState({
          accuracy,
          altitude,
          altitudeAccuracy,
          heading,
          latitude,
          longitude,
          speed,
          error: null,
        });
      },
      (error) => this.setState({ error: error.message }),
      { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },
    );
  }

  render() {
    const { region } = this.props;
    const { latitude, longitude } = this.state;
    console.log('region', region);
    return (
      <View style ={styles.container}>
        <MapView
          style={styles.map}
          region={{
            latitude: latitude || 37.78825,
            longitude: longitude || -122.4324,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121,
          }}
        >
        </MapView>
      </View>
    );
  }
}


const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});

```
$ `react-native run-ios`. // The app builds correctly on the simulator

- Using XCode to build it on my Iphone.

### Expected Behavior

Expected the app to successfully build on my phone. 

### Actual Behavior

XCode build fails with the following error:

<img width="265" alt="screenshot 2018-03-07 02 08 01" src="https://user-images.githubusercontent.com/1258955/37086429-647b1d28-21ac-11e8-847d-6308c1e27931.png">

### Reproducible Demo
N/A

**Comment by rborn** [comment]
@rafaellincoln could you have a look at this? I think it's related to your PR #2011

I suspect it requires google maps, but in the @vinicius5581 code the provider is apple so maybe your  code is missing a conditional? 🤗

**Comment by EsdrasEtrenne** [comment]
I got this exact same issue, causing my builds to fail when I use the `react-native-maps` library by pulling directly from master.

If I do not pull directly from master then I get issue #2051

**Comment by rafaellincoln** [comment]
@vinicius5581 remove the `BatchedBridge` from `Podfile` and run `pod install` again.

Example using
----
```
"react": "^16.3.0-alpha.1",
"react-native": "0.54.0",
"react-native-maps": "github:react-community/react-native-maps"
```
https://github.com/rafaellincoln/test-rn-maps

@rborn `BatchedBridge` was removed from the version 0.54.0 of the react-native. #2072

**Comment by breadadams** [comment]
Downgrading as suggested by @EsdrasEtrenne is the only thing that fixes this for me. So the following dependencies:
```
"react": "^16.3.0",
"react-native": "0.54.2",
"react-native-maps": "^0.19.0"
```

However it's been a rollercoaster to finally get to _this_ issue, I've been through at least half-a-dozen bugs/issues prior to meeting ye `'GMUKMLParser.h'` 😅

**Comment by wassgha** [comment]
I solved this issue without downgrading by adding
`
    pod 'Google-Maps-iOS-Utils'
`
(in addition to `pod 'GoogleMaps'`) to my Podfile then running `pod update` followed by `pod install`

**Comment by eladgel** [comment]
@wassgha this what happens to me now
![image](https://user-images.githubusercontent.com/412137/37520871-61cabc28-2927-11e8-8187-c76daa8a0f57.png)

**Comment by breadadams** [comment]
I ran into that one too @eladgel. Try removing the lib files from `node_modules/...` in Xcode & dragging in again again after downgrading. Then restart Xcode and clean the project. I'm pretty sure that's what cleared it up for me.

**Comment by wbattel4607** [comment]
I've been wrestling with this one for a while. Unfortunately nothing in this thread has resolved it for me.

This only happens when pulling from master, which I have to do to get around https://github.com/react-community/react-native-maps/issues/2051

**Comment by wbattel4607** [comment]
@benseitz I uninstalled the library and reinstalled it. This fixed it for me because I was using an older integration method from an older version. They updated the recommended installation method and I used that to reinstall using Coacoapods and it worked just fine after that.

**Comment by benseitz** [comment]
@wbattel4607  Thanks! unfortunately, I don't really remember what kind of files I had to edit to install it, so uninstalling is going to be a challenge.

**Comment by wbattel4607** [comment]
@benseitz how is it installed currently? Did you manually add the AirMaps and AirGoogleMaps directories to the Xcode project? Or is it installed by some other method?

**Comment by benseitz** [comment]
@wbattel4607  I installed it with cocoapods, but had some issues, I resolved by adding lines to some files (e.g. 'AppDelegate.m`). I just looked for the commit and am reversing every step now.

**Comment by rborn** [comment]
#2396  was merged, please test with the latest git version. 
Please keep in mind that you might have to setup the module again as now it works with `react-native link`
Read the install manual carefully

**Comment by pisacode** [comment]
I am still facing the same issue at v0.24.2 do you guys have any idea how to fix it? I am using v0.19.0 to make it work but would like to use the latest release.

**Comment by minhphung210** [comment]
@pisacode  same issues :(

**Comment by jacquesdev** [comment]
Same - I have logged issue #2876 to investigate this, for me it was working until 2 days ago

**Comment by joohimks** [comment]
@pisacode & @minhphung210 Is there any update at your end?

Still stuck with this error here and its driving me crazy :(

**Comment by pisacode** [comment]
> @pisacode & @minhphung210 Is there any update at your end?
> 
> Still stuck with this error here and its driving me crazy :(

I am just using `react-native-maps v0.19.0` to get around this problem and it is ok for my needs.

**Comment by mwcm** [comment]
seeing the same issue as @jacquesdev and @pisacode

**Comment by stevenheffner** [comment]
Same issue

**Comment by joohimks** [comment]
Check this [comment](https://github.com/react-native-community/react-native-maps/issues/2876#issuecomment-494977693) out. I had the exact problem and I fixed it.
