### ISSUE TITLE
Is RN 0.54 supported?

### ISSUE THREAD

**Issue by hegelstad** [react-community/react-native-maps#2067]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.54.0
    react: 16.3.0-alpha.1 (peerDep of RN 0.54)
    react-native-maps: 0.20.1

### Steps to Reproduce

1. npm install
2. `npm WARN react-native-maps@0.20.1 requires a peer of react-native@0.51.0 but none is installed. You must install peer dependencies yourself.`

### Expected Behavior

No warning.

### Actual Behavior

Warning.

---

Does react-native-maps support RN 0.54.0?

Bonus question: Could we create a discord channel for this project?

**Comment by rborn** [comment]
@hegelstad try yo use the git version, it should work with 0.54

about the discord channel, I don't know 😊

**Comment by hegelstad** [comment]
It's supported. It worked even with 0.20.1, I just needed to remove BatchedBridge from React deps in Podfile.

**Comment by rborn** [comment]
@hegelstad we have this almost ready: https://github.com/react-community/react-native-maps/pull/2065
