### ISSUE TITLE
Build failed on iOS, library not found for Google-Maps-iOS-Utils

### ISSUE THREAD

**Issue by zaguini** [react-community/react-native-maps#2074]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment
OS: macOS High Sierra 10.13.3
  Node: 9.6.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

### Steps to Reproduce

The mentioned in installation... As usual.

### Expected Behavior

To build.

### Actual Behavior

Build failed.

```
ld: warning: directory not found for option '-L/Users/toodo/Library/Developer/Xcode/DerivedData/toodo-diaxclcoysjytfgoqmwkdloeawbf/Build/Products/Release-iphonesimulator'
ld: warning: directory not found for option '-F/Users/toodo/Library/Developer/Xcode/DerivedData/toodo-diaxclcoysjytfgoqmwkdloeawbf/Build/Products/Release-iphonesimulator'
ld: library not found for -lGoogle-Maps-iOS-Utils
```

Yes, I opened `.xcworkspace` file. Instaled from Git Repo instead of npm.
Yes, I tried to add the `.a` file manually.
Yes, I tried to build for release. Nothing works.

Podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'toodo' do
  rn_path = '../node_modules/react-native'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for toodo
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'

  target 'toodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'toodo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for toodo-tvOS

  target 'toodo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by rishabhmathur1693** [comment]
@zaguini Try to remove this from Podfile and the run command `pod install` - 

`if target.name == "React"`
`      target.remove_from_project`
`    end`

**Comment by zaguini** [comment]
@rishabhmathur1693 I can't see how this resolves the issue. I tried it anyway, still no results...

**Comment by zaguini** [comment]
Solved! The problems was the libraries were not properly being found at `Library Search Paths`. I changed it from `$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)` to `$(BUILD_DIR)/${CONFIGURATION}$(EFFECTIVE_PLATFORM_NAME)` and it worked. Perhaps it was not my fault, who knows... Whatever, if someone has this issue as well, that is the solution.

**Comment by jeremyfrancis** [comment]
No success for me. I can see the Google-Maps-iOS-Utils folder inside the Pods folder but there is no group for it in the XCode project. Not sure if that matters but I don't know how else it's suppose to find it. I installed it as a Pod normally with no luck. Not sure what plan of action to take next.

**Comment by shimatai** [comment]
No success for me too. I'm building for React Native 0.63.2 and react-native-maps 0.27.1.

I'm getting the following error:

`ld: warning: directory not found for option '-L-L/Users/shimatai/Library/Developer/Xcode/DerivedData/walible-futipljqkogzvygbjfbbrzcgirra/Build/Products/Debug-iphonesimulator/Google-Maps-iOS-Utils'
ld: library not found for -lGoogle-Maps-iOS-Utils
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by uplamartya** [comment]
Any fix available yet? I am also facing the same issue in IOS
<img width="546" alt="Screenshot 2021-01-14 at 11 42 48 AM" src="https://user-images.githubusercontent.com/47631015/104551894-bc896400-565d-11eb-81f4-6e7a068a96f2.png">

**Comment by skantus** [comment]
> Any fix available yet? I am also facing the same issue in IOS
> 
> <img alt="Screenshot 2021-01-14 at 11 42 48 AM" width="546" src="https://user-images.githubusercontent.com/47631015/104551894-bc896400-565d-11eb-81f4-6e7a068a96f2.png">

@uplamartya probably there is some problem linking the pod, you can execute directly from you console

```
npx react-native run-ios
```

This should open the simulator
