### ISSUE TITLE
Blank map on android

### ISSUE THREAD

**Issue by Puetz** [react-community/react-native-maps#2075]
Hi,
I'm trying to use react-native-maps on android but the map is always blank. I also checked out the other issues regarding this topic but none of them helped me fixing it. The map renders the Google icon in the bottom left corner. 
I compared my app/build.gradle to the one in the  react-native-maps/example/android/app/ folder and I'm using the same sdk versions:

- compileSdkVersion 25
- buildToolsVersion "25.0.3"
- minSdkVersion 16
- targetSdkVersion 23

I ran the app on virtual devices with android api 25 and 26 and on an Galaxy S7 but the map is always blank. I'm using
    `compile "com.google.android.gms:play-services-base:11.8.0"`
    `compile 'com.google.android.gms:play-services-maps:11.8.0'`
in my app dependencies and I'm using the latest version of react-native. 

Does anybody have any suggestions how to fix this?
Thanks a lot for your help!

**Comment by zaguini** [comment]
+1

**Comment by zaguini** [comment]
Fixed it by enabling `Google Maps Android API` on Google Developers Console. It takes around 5 minutes to update the changes, so don't rush.

**Comment by Puetz** [comment]
I tried everything mentioned in the installation.md and readme.md, including the suggested style from istallation.md. Google Maps API is enabled and I generated a new API Key but the map is still blank. 

This is the [link](https://github.com/Puetz/Phodl) to our repository in case someone would like to check our files. The map works on IOS but not on android. It's also our first time developing an app, so please excuse any stupid mistakes and feel free to point them out.

Thanks again your help.

**Comment by zaguini** [comment]
It's not Maps API, it's Maps ANDROID API. Check?

**Comment by Puetz** [comment]
That's what i meant, sorry. Google Maps Android API is enabled.

**Comment by zaguini** [comment]
Right. Did you check the logs? `adb logcat`. Check if there is some meaningful information

**Comment by Puetz** [comment]
```
03-09 16:38:30.597  6915  7066 I ReactNativeJS: Running application "phoodl" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
03-09 16:38:30.623  6915  7067 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
03-09 16:38:30.636  6915  6915 I Google Maps Android API: Google Play services package version: 11947480
03-09 16:38:30.744  6915  7073 D         : HostConnection::get() New Host Connection established 0xcc1a6400, tid 7073
03-09 16:38:30.753  6915  7073 D EGL_emulation: eglCreateContext: 0xca904140: maj 1 min 0 rcv 1
03-09 16:38:30.756  1401  1401 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4411392
03-09 16:38:31.015  6915  7073 D EGL_emulation: eglMakeCurrent: 0xca904140: ver 1 0 (tinfo 0xcc1e9790)
03-09 16:38:31.092  1401  1401 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4411392
03-09 16:38:31.215  1401  1401 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4411392
03-09 16:38:31.224  6915  6968 E GLConsumer: [SurfaceTexture-0-6915-1] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
03-09 16:38:32.102  6915  6968 I chatty  : uid=10085(u0_a85) RenderThread identical 36 lines
03-09 16:38:32.122  6915  6968 E GLConsumer: [SurfaceTexture-0-6915-1] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
03-09 16:38:35.064  6915  7062 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["websocketFailed",{"message":"failed to connect to /10.0.2.2 (port 8097) from /... after 10000ms","id":4}])
```
That's the end of the log. The information up to this point does not seem meaningful.

**Comment by Puetz** [comment]
I just tried it again on my S7 and now it's working fine. I have no idea what fixed it though. I guess I made a mistake during my initial setup and redoing everything over and over again fixed that. But since it's not working properly on my virtual device, I didn't realize that the app itself works fine.

So I will just use my phone for debugging from now on, since that works. 
I used one virtual device with x86 Image, API 26 and Android 8.0 (Google APIs) and one with x86 Image, API 25 and Android 7.1.1 (Google APIs). I also downloaded the SDK Platforms that are necessary for React Native. If someone knows why it doesn't work, I still would be interested in an answer but for now I'll just use my real phone.

Thanks zaguini for your help.

**Comment by zaguini** [comment]
Cheers.

**Comment by djalmaaraujo** [comment]
I am facing the same issue, simply is not working. Can't find a solution. Which react-native version you guys are using?

**Comment by rborn** [comment]
Closing, no issue template, not closed by the author even after it was working.

@djalmaaraujo make a search for similar issue, if you have the logo of the map rendered is a apikey issue and/or a simulator that does't have google services installed.

**Comment by djalmaaraujo** [comment]
Info for whom is getting the same error. I BELIEVE the error is related to the API KEY. Do not use the same key for IOS and android, generate one in the android SDK page. That's the only thing I changed, and it worked.

**Comment by adirzoari** [comment]
I have same issue. any solution?
