### ISSUE TITLE
Dynamically removing & adding markers depending on region

### ISSUE THREAD

**Issue by minotaurrr** [react-community/react-native-maps#2078]
Hey guys,

I have lots of markers on the map but I only want to display the ones within user's screen.

So as the user moves the map to a different area (`onRegionChangeComplete`), new markers in that area would show up (as long as they are within the screen) and the old ones would disappear.

I tried a couple things myself and searched this repo but haven't figured it out yet.

Can anyone help please?

**Comment by rborn** [comment]
No issue template 😔, closing.
