### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleMaps"

### ISSUE THREAD

**Issue by joshuamataaraya** [react-community/react-native-maps#2080]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
    react-native: ^0.51.0
    react: ^16.2.0
    react-native-maps: ^0.20.1

  Target Platform: eg: iOS - 10.2 Simulator

### Steps to Reproduce

I followed the steps for installation in the [link](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#on-ios). When I reach the part to execute the command pod install I get the following error:

    [!] CocoaPods could not find compatible versions for pod "GoogleMaps":
    In Podfile:
    GoogleMaps

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.20.1, which depends on
      GoogleMaps (= 2.5.0)
    Specs satisfying the `GoogleMaps, GoogleMaps (= 2.5.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by rborn** [comment]
`Note: Support for Xcode 7.3 has been dropped. The new minimum is Xcode 8.0.` -> https://developers.google.com/maps/documentation/ios-sdk/releases

In other words your xcode project needs to have the target >=8.0

You might wanna try to uncomment this podfile line
`# platform :ios, '9.0'`

**Comment by piloulac** [comment]
Same here,

using XCode `9.02`and when uncommenting `platform :ios, '9.0'` it gives the same result :/

**Comment by ujwal-setlur** [comment]
Try using the latest code from github. In you package.json:
```
"react-native-maps": "github:react-community/react-native-maps"
```

**Comment by piloulac** [comment]
still the same issue

**Comment by biancaFarcas** [comment]
i had the same issue but running pod update fixed the problem.

**Comment by rborn** [comment]
Closing,  see https://github.com/react-community/react-native-maps/issues/2080#issuecomment-374192549

**Comment by tierfour** [comment]
I also had to define a global platform constant (uncomment platform line)

`# platform :ios, '9.0'`

**Comment by tyjing** [comment]
> github:react-community/react-native-maps

is there any issue if i using github:react-community/react-native-maps for react-native-maps versioning? issue like once the code is updated, my current running app will not working/functioning well?

**Comment by rborn** [comment]
@tyjing yes, if you point to master any change done to the repo will reflect in your code if you run `npm install`
An idea would be to point to a specific commit 

~~~
"dependencies": {
  "package": "git://github.com/username/package.git#commit"
}
~~~

or  fork the repo and point to your fork (of course keeping in in sync with the master only when you are sure you can update safely)

**Comment by icemancast** [comment]
Confirmed @biancaFarcas solution to `pod update` worked for me as well.

**Comment by AliRawash** [comment]
pod update still not worked for me. 
cocoaPods couldn't find compitable versions for pod "GoogleMaps":
in podfile: GoogleMaps
