### ISSUE TITLE
Dynamically rendering markers

### ISSUE THREAD

**Issue by minotaurrr** [react-community/react-native-maps#2081]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
```
  "dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz"
```

### Expected Behavior

I'm trying to dynamically display/hide markers only within users screen. I have a function that returns true if a coordinate is within users screen, false if not.

For every marker I run it through this function to check whether it should be displayed or not.

Ideally, as user moves the map around, they should be seeing markers appearing/disappearing in realtime.

### Actual Behavior

The markers will disappear once they are out of screen (e.g. if I zoom in) however they won't reappear once they should be back in the screen.

I tried using the key props trick as mentioned in another issue like `<Marker key={${`marker_id`}${Date.now()}} />` but that made it worse.. markers just didn't appear at all

My suspicion is that the code kind of works but it's very very slow when it's trying to get the markers to render back on the screen for some reason.

There's about 1000 markers in total.

### Reproducible Demo
Here's the code.
```
import React from 'react';
import { Text, View, Dimensions } from 'react-native';
import { MapView } from 'expo';
import markerImage from './assets/marker-128.png';

const { width, height } = Dimensions.get('window');
const ASPECT_RATIO = width / height;
const LATITUDE = -37.812365;
const LONGITUDE = 144.962338;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

export default class App extends React.Component {
  constructor() {
    super();
    this.state = {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA
      },
      data: [],
      isLoaded: false,
      boundingBox: {
        westLng: 0,
        southLat: 0,
        eastLng: 0,
        northLat: 0
      }
    }
  }

  componentDidMount() {
    this.getData();
  }

  getData = async () => {
    this.setState({isLoaded: false});
    let data = await (await fetch(someURL)).json();
    this.setState({data: data, isLoaded: true});
  }

  onRegionChangeComplete = (region) => {
    let boundingBox = this.getBoundingBox(region);
    this.setState({region, boundingBox});
  }

  getBoundingBox = (region) => {
    let boundingBox = {
      westLng: region.longitude - region.longitudeDelta/2, // westLng - min lng
      southLat: region.latitude - region.latitudeDelta/2, // southLat - min lat
      eastLng: region.longitude + region.longitudeDelta/2, // eastLng - max lng
      northLat: region.latitude + region.latitudeDelta/2 // northLat - max lat
    }

    return boundingBox;
  }

  isInBoudingBox(coordinate) {
    if (coordinate.latitude > this.state.boundingBox.southLat && coordinate.latitude < this.state.boundingBox.northLat &&
        coordinate.longitude > this.state.boundingBox.westLng && coordinate.longitude < this.state.boundingBox.eastLng)
    {
      return true;
    }
    
    return false;
  }

  render() {
    return (
      <MapView style={ { flex: 1 } } initialRegion={ this.state.region } onRegionChangeComplete={this.onRegionChangeComplete}>
        <MapView.Marker coordinate={ { latitude: this.state.region.latitude, longitude: this.state.boundingBox.westLng } } image={ markerImage }>
            <MapView.Callout>
              <View>
                <Text>This is a west lng</Text>
              </View>
            </MapView.Callout>
        </MapView.Marker>
        <MapView.Marker coordinate={ { latitude: this.state.region.latitude, longitude: this.state.boundingBox.eastLng } } image={ markerImage } />

        {this.state.isLoaded ? this.state.data.map(p =>
          this.isInBoudingBox({ latitude: parseFloat(p.lat), longitude: parseFloat(p.lon) }) ? 
          <MapView.Marker coordinate={ { latitude: parseFloat(p.lat), longitude: parseFloat(p.lon) } } image={ markerImage }>
            <MapView.Callout>
              <View>
                <Text>This is a test callout</Text>
              </View>
            </MapView.Callout>
          </MapView.Marker>
          : null)
        : console.log('data does not exist yet')}
      </MapView>
      );
  }
}
```

Can anyone help?

**Comment by rborn** [comment]
``` 
onRegionChangeComplete = (region) => {
    let boundingBox = this.getBoundingBox(region);
    this.setState({region, boundingBox});
  }
```
you set the `state.region` but then in `isInBoudingBox` you look for  `state.boundingBox`.

Another idea would be to try to use supercluster, because is really fast but I'm not sure you can set a cluster of 1 marker only.

**Comment by minotaurrr** [comment]
@rborn Is that what's causing the slow performance? Should I be getting the bounding box coords within the `isInBoundingBox` function rather than looking for `state.boundingBox`?

**Comment by rborn** [comment]
Is not slow performance what's making your markers not to show (even if the code slow). It's the fact that `onRegionChangeComplete` you are setting the `state.region` as being the area where to look for, while `isInBoudingBox` searches in `state.boundingBox` which you never change.

**Comment by minotaurrr** [comment]
@rborn but I am setting `state.boundingBox`? 

```
onRegionChangeComplete = (region) => {
    let boundingBox = this.getBoundingBox(region);
    this.setState({region, boundingBox}); // <- setting bounding box
  }
```

**Comment by rborn** [comment]
I'm blind, sorry.
Managing the region in the state is not ok, there are few issues related to this (you can search). Try to set only the  `state.boundingBox` and see if it improves anything.

**Comment by minotaurrr** [comment]
@rborn getting rid of `setState({region})` didn't help unfortunately :(

I noticed the markers do show up but they take a long time to show up. And the rendering seems really slow even when they show up, like maybe 4-5 would show up every second or so (out of like 100).

**Comment by minotaurrr** [comment]
@rborn I noticed it's the custom image causing the slow performance. I'll open a new issue.
