### ISSUE TITLE
React Native 0.54 remove batchbridge

### ISSUE THREAD

**Issue by taojoe** [react-community/react-native-maps#2084]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
    react-native: 0.54.0
    react: 16.3.0-alpha.1
    react-native-maps: 0.20.1

### Steps to Reproduce

1.  upgrade react native to 0.54

### Expected Behavior

react-native-maps works

(Write what you thought would happen.)

### Actual Behavior

red screen failed, require faild, 
![image](https://user-images.githubusercontent.com/545656/37261084-9eb63190-25d4-11e8-9464-ea1f85dd0a6f.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by alvelig** [comment]
That's your environment. Follow what the red screen says.

**Comment by rborn** [comment]
@taojoe try with the git version please and let us know.

**Comment by alvelig** [comment]
Sure, is it duplicate of #2053 ?

**Comment by taojoe** [comment]
@rborn 

git version works. 

now the map is not loaded well,  I don't know what the problem is.  I'm in China, so the default map of ios is "GAODE"? 

![image](https://user-images.githubusercontent.com/545656/37318927-d5a62fec-26a7-11e8-98f6-95d7d123379d.png)

**Comment by taojoe** [comment]
@alvelig , yes it's duplicate

**Comment by longpq18** [comment]
@taojoe same issue on android, i rerun "react-native run-android" and it working, you try rerun "react-native run-ios"

**Comment by rborn** [comment]
@taojoe @longpq18 if the map renders the logo is usually an api key issue.
