### ISSUE TITLE
Dynamic style change on Callouts not working properly

### ISSUE THREAD

**Issue by minotaurrr** [react-community/react-native-maps#2085]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
```
  "dependencies": {
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-maps": "^0.20.1"
  }
```
### Steps to Reproduce

I'm trying to change `width` of my marker callout when state changes, using react native animation. However when the state changes, callout style still remains the same.

Workaround I found was to set `tooltip={true}` however this will break the callout image (Instead of the default text bubble shape, it'll just be transparent).

### Expected Behavior

Style on callout will change as state changes.

### Actual Behavior

<img width="67" alt="screen shot 2018-03-12 at 2 09 06 pm" src="https://user-images.githubusercontent.com/28755951/37263963-f515017c-25fe-11e8-9715-aade6d0a4146.png">

The width will remain the same like above screenshot even though the code is set to dynamically change width.

<img width="211" alt="screen shot 2018-03-12 at 2 07 35 pm" src="https://user-images.githubusercontent.com/28755951/37263944-c826f198-25fe-11e8-91b3-ecb06e6a334f.png">

This is the callout when `tooltip={true}` is applied, it is showing the width I want however the background text bubble image is gone.

### Reproducible Demo

```
    render() {
        return (
            <MapView.Marker image={markerImage} onPress={e => {e.stopPropagation(); this.onMarkerPress(this.props.bayID)}} coordinate={ this.props.coordinate } tracksViewChanges={this.state.tracksViewChanges}>
                <MapView.Callout style={[{ flex: -1, position: 'absolute' }, this.state.isLoaded && { flex: -1, position: 'absolute', width: 220 }]}> //<- CHANGING WIDTH DOESN'T WORK
                    {this.state.isLoaded ? 
                    <View>
                        <Text>{this.state.descriptions.description1}</Text>
                        <Text>{this.state.descriptions.description2}</Text>
                        {this.state.descriptions.description3 ? <Text>{this.state.descriptions.description3}</Text> : null}
                    </View>
                    : 
                    <ActivityIndicator size="large" />
                    }
                    
                </MapView.Callout>
            </MapView.Marker>
        )
    }
```

**Comment by rborn** [comment]
Closing as tracksViewChanges works fine now. Please open a new issue if you still find this

**Comment by ismaelbarry** [comment]
Hi minotaurrr! I hope you were able to fix your issue. I was wondering how you were able to remove the padded borders from the call out from your image in the "actual behavior." What styling did you use?

Thanks!
