### ISSUE TITLE
Android "App has stopped"

### ISSUE THREAD

**Issue by GH974** [react-community/react-native-maps#2086]
Hi, App crash after launched

Extract error in cmd adb logcat
`Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
03-12 04:56:21.743 12676 12695 I zygote  :   at void com.airbnb.android.react.maps.AirMapManager.<init>(com.facebook.react.bridge.ReactApplicationContext) (AirMapManager.java:54)
03-12 04:56:21.743 12676 12695 I zygote  :   at java.util.List com.airbnb.android.react.maps.MapsPackage.createViewManagers(com.facebook.react.bridge.ReactApplicationContext) (MapsPackage.java:39)
03-12 04:56:21.743 12676 12695 I zygote  :   at java.util.List com.facebook.react.ReactInstanceManager.createAllViewManagers(com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:768)
03-12 04:56:21.743 12676 12695 I zygote  :   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.createUIManager(com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:175)
03-12 04:56:21.743 12676 12695 I zygote  :   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.access$200(com.facebook.react.CoreModulesPackage, com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:55)
03-12 04:56:21.743 12676 12695 I zygote  :   at com.facebook.react.bridge.NativeModule com.facebook.react.CoreModulesPackage$7.get() (CoreModulesPackage.java:132)
03-12 04:56:21.743 12676 12695 I zygote  :   at java.lang.Object com.facebook.react.CoreModulesPackage$7.get() (CoreModulesPackage.java:129)
03-12 04:56:21.743 12676 12695 I zygote  :   at java.util.List com.facebook.react.LazyReactPackage.createNativeModules(com.facebook.react.bridge.ReactApplicationContext) (LazyReactPackage.java:81)
03-12 04:56:21.743 12676 12695 I zygote  :   at void com.facebook.react.NativeModuleRegistryBuilder.processPackage(com.facebook.react.ReactPackage) (NativeModuleRegistryBuilder.java:106)
03-12 04:56:21.743 12676 12695 I zygote  :   at void com.facebook.react.ReactInstanceManager.processPackage(com.facebook.react.ReactPackage, com.facebook.react.NativeModuleRegistryBuilder) (ReactInstanceManager.java:1171)
03-12 04:56:21.743 12676 12695 I zygote  :   at com.facebook.react.bridge.NativeModuleRegistry com.facebook.react.ReactInstanceManager.processPackages(com.facebook.react.bridge.ReactApplicationContext, java.util.List, boolean) (ReactInstanceManager.java:1141)
03-12 04:56:21.743 12676 12695 I zygote  :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.createReactContext(com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:1083)
03-12 04:56:21.743 12676 12695 I zygote  :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.access$900(com.facebook.react.ReactInstanceManager, com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:113)
`

### Is this a bug report?

(write your answer here)
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)
Yes
### Environment
react-native 0.53.3
react 16.2.0
react-native-maps : 0.20.1

Android simulator API 27

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
@GH974 try with the git version please and let us know

**Comment by Metroninja** [comment]
Was facing the same issue, can confirm running from the current repo version solves this issue.

**Comment by rborn** [comment]
Closing as fixed ( @Metroninja comment).
