### ISSUE TITLE
not able to zoom map view to the current location when loading map

### ISSUE THREAD

**Issue by sasikg** [react-community/react-native-maps#209]
i am not able to show my current location closely when loading map without using showUserLocation, as you can see in the below pic.
![simulator screen shot 5 may 2016 11 31 06 am](https://cloud.githubusercontent.com/assets/13790938/15035474/e2b79f94-12b4-11e6-83b2-67ed77ce7b2e.png)

**Comment by christopherdro** [comment]
@sasikg Do you have `latitudeDelta` and `longitudeDelta` set?

**Comment by sasikg** [comment]
@christopherdro yes i have set the region as follows
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.033,

**Comment by cinder92** [comment]
BTW, how can i get `latitudeDelta` and `longitudeDelta` from any location?

**Comment by tsuz** [comment]
@cinder92  What about `onRegionChangeComplete`?

**Comment by avdept** [comment]
@cinder92 Deltas - are the values that responsible for zoom level

**Comment by pacozaa** [comment]
I have the same problem too. Can anyone give a few examples? How `Region` works?

**Comment by alvelig** [comment]
```
import React from 'react';
import {
  Alert,
  Platform,
  StyleSheet
} from 'react-native';
import MapView from 'react-native-maps'

const LATITUDE_DELTA = 0.01;
const LONGITUDE_DELTA = 0.01;

const initialRegion = {
  latitude: -37.78825,
  longitude: -122.4324,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421,
}

class MyMapView extends React.Component {

  map = null;

  state = {
    region: {
      latitude: -37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    },
    ready: true,
    filteredMarkers: []
  };

  setRegion(region) {
    if(this.state.ready) {
      setTimeout(() => this.map.mapview.animateToRegion(region), 10);
    }
    //this.setState({ region });
  }

  componentDidMount() {
    console.log('Component did mount');
    this.getCurrentPosition();
  }

  getCurrentPosition() {
    try {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const region = {
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
            latitudeDelta: LATITUDE_DELTA,
            longitudeDelta: LONGITUDE_DELTA,
          };
          this.setRegion(region);
        },
        (error) => {
          //TODO: better design
          switch (error.code) {
            case 1:
              if (Platform.OS === "ios") {
                Alert.alert("", "Para ubicar tu locación habilita permiso para la aplicación en Ajustes - Privacidad - Localización");
              } else {
                Alert.alert("", "Para ubicar tu locación habilita permiso para la aplicación en Ajustes - Apps - AppWash - Localización");
              }
              break;
            default:
              Alert.alert("", "Error al detectar tu locación");
          }
        }
      );
    } catch(e) {
      alert(e.message || "");
    }
  };

  onMapReady = (e) => {
    if(this.state.ready) {
      this.setState({ready: true});
    }
  };

  onRegionChange = (region) => {
    console.log('onRegionChange', region);
  };

  onRegionChangeComplete = (region) => {
    console.log('onRegionChangeComplete', region);
  };

  render() {

    const { region } = this.state;
    const { children, renderMarker, markers } = this.props;

    return (
      <MapView
        showsUserLocation
        ref={ map => { this.map = map }}
        data={markers}
        initialRegion={initialRegion}
        renderMarker={renderMarker}
        onMapReady={this.onMapReady}
        showsMyLocationButton={false}
        onRegionChange={this.onRegionChange}
        onRegionChangeComplete={this.onRegionChangeComplete}
        style={StyleSheet.absoluteFill}
        textStyle={{ color: '#bc8b00' }}
        containerStyle={{backgroundColor: 'white', borderColor: '#BC8B00'}}>

        {/*markers.map(renderMarker)*/}

        {children && children || null}

      </ClusteredMapView>
    );
  }
}

export default MyMapView;
```

**Comment by rafaelmaeuer** [comment]
@alvelig your example isn't working for me, can you please review your snippet? I get the Exception 'TypeError: undefined is not an object (evaluating 'markers.map')' and is the closing tag </ClusteredMapView> correct for the opening <MapView ...> tag?

**Comment by alvelig** [comment]
@rafaelmaeuer 

replace 
```
{markers.map(renderMarker)}

        {children && children || null}
```
with your markers

**Comment by tmaly1980** [comment]
@alvelig I don't understand this code:

```
  onMapReady = (e) => {
    if(this.state.ready) {
      this.setState({ready: true});
    }
  };
```

How is this ever false?

**Comment by alvelig** [comment]
@tmaly1980 Sorry, that's my typo. But generally the code represents the idea.

**Comment by tmaly1980** [comment]
@alvelig I don't quite understand what you're doing, can you fix your typos and maybe add some comments? For now I'm just using onRegionChangeC implement instead of onRegionChange, seems to work so far.

**Comment by alvelig** [comment]
The main idea is that you need to wait for the map to be ready to animateToRegion. Controlling region in state has more drawbacks, that are not obvious until you start using it in production.

**Comment by AgNm** [comment]
@tmaly1980 you said replace 

`{markers.map(renderMarker)}

        {children && children || null}`

with your marker. What do you mean by "your marker". I am new to react-native, can you please be more specific?

**Comment by tmaly1980** [comment]
@AgNm I didn't say that, it was @alvelig that said that. I'm still trying to figure all this out just like you.

**Comment by alvelig** [comment]
Guys, maybe read the docs before you ask :) The code is not to copy and paste. It is to understand and make your own business logic.

@AgNm you need to provide `<MapView.Marker .../>` to show markers on map. See docs.

@tmaly1980 feel free to ask a specific question.

**Comment by valeriashpiner** [comment]
@alvelig I try to implement geolocation and use your code as an example, but get the error "Cannot read property "animateToRegion" of undefined.

**Comment by rborn** [comment]
@valeriashpiner I think there is a mistake in the example code, it should be `this.map.animateToRegion(region), 10);` instead of `this.map.mapview.animateToRegion(region), 10);` (extra `mapview`)

Let us know :)

**Comment by breadadams** [comment]
I was seeing the same as @valeriashpiner, none of the methods were _available_ on my `MapView`'s ref node, trying with `animateToRegion` & `animateToCoordinate`.

Just as I was typing this, I figured out what was going on, thanks to your comment @rborn.

I'm working with a `Map` component which is basically a wrap of the `MapView` component from react-native-maps. So accessing `ref` on _our_ map component was the main node for that component, even though we're explicitly passing all `...props` to `MapView`.

So, the fix, first we changed our `Map` from a stateless component to a class extended from react's `Component` (so we can access it's `ref`, we'll call that **REF1**).
Then, within that component we assigned `ref` to an internal `this.mapView` (we'll call that **REF2**). And finally, where we were trying to access `this.REF1.animateToCoordinate`, changed it to `this.REF1.REF2.animateToCoordinate`. And works fine 😄

**Comment by vinhthieugia** [comment]
> @valeriashpiner I think there is a mistake in the example code, it should be `this.map.animateToRegion(region), 10);` instead of `this.map.mapview.animateToRegion(region), 10);` (extra `mapview`)
> 
> Let us know :)



> Here's the example of how I manage to show user location.
> 
> I use a button calling `getUserPosition` to animate to user's current coordinates. (Demonstration code, programmer discretion is advised XD )
> 
> ```
> import React from 'react';
> import {
>   Alert,
>   Platform,
>   StyleSheet
> } from 'react-native';
> import MapView from 'react-native-maps'
> 
> const LATITUDE_DELTA = 0.01;
> const LONGITUDE_DELTA = 0.01;
> 
> const initialRegion = {
>   latitude: -37.78825,
>   longitude: -122.4324,
>   latitudeDelta: 0.0922,
>   longitudeDelta: 0.0421,
> }
> 
> class MyMapView extends React.Component {
> 
>   map = null;
> 
>   state = {
>     region: {
>       latitude: -37.78825,
>       longitude: -122.4324,
>       latitudeDelta: 0.0922,
>       longitudeDelta: 0.0421,
>     },
>     ready: true,
>     filteredMarkers: []
>   };
> 
>   setRegion(region) {
>     if(this.state.ready) {
>       setTimeout(() => this.map.mapview.animateToRegion(region), 10);
>     }
>     //this.setState({ region });
>   }
> 
>   componentDidMount() {
>     console.log('Component did mount');
>     this.getCurrentPosition();
>   }
> 
>   getCurrentPosition() {
>     try {
>       navigator.geolocation.getCurrentPosition(
>         (position) => {
>           const region = {
>             latitude: position.coords.latitude,
>             longitude: position.coords.longitude,
>             latitudeDelta: LATITUDE_DELTA,
>             longitudeDelta: LONGITUDE_DELTA,
>           };
>           this.setRegion(region);
>         },
>         (error) => {
>           //TODO: better design
>           switch (error.code) {
>             case 1:
>               if (Platform.OS === "ios") {
>                 Alert.alert("", "Para ubicar tu locación habilita permiso para la aplicación en Ajustes - Privacidad - Localización");
>               } else {
>                 Alert.alert("", "Para ubicar tu locación habilita permiso para la aplicación en Ajustes - Apps - ExampleApp - Localización");
>               }
>               break;
>             default:
>               Alert.alert("", "Error al detectar tu locación");
>           }
>         }
>       );
>     } catch(e) {
>       alert(e.message || "");
>     }
>   };
> 
>   onMapReady = (e) => {
>     if(!this.state.ready) {
>       this.setState({ready: true});
>     }
>   };
> 
>   onRegionChange = (region) => {
>     console.log('onRegionChange', region);
>   };
> 
>   onRegionChangeComplete = (region) => {
>     console.log('onRegionChangeComplete', region);
>   };
> 
>   render() {
> 
>     const { region } = this.state;
>     const { children, renderMarker, markers } = this.props;
> 
>     return (
>       <MapView
>         showsUserLocation
>         ref={ map => { this.map = map }}
>         data={markers}
>         initialRegion={initialRegion}
>         renderMarker={renderMarker}
>         onMapReady={this.onMapReady}
>         showsMyLocationButton={false}
>         onRegionChange={this.onRegionChange}
>         onRegionChangeComplete={this.onRegionChangeComplete}
>         style={StyleSheet.absoluteFill}
>         textStyle={{ color: '#bc8b00' }}
>         containerStyle={{backgroundColor: 'white', borderColor: '#BC8B00'}}>
> 
>         {markers.map(renderMarker)}
> 
>         {children && children || null}
> 
>       </ClusteredMapView>
>     );
>   }
> }
> 
> export default MyMapView;
> ```

Thank u so much. You saved my life, bro. :D

**Comment by saudkhan1391** [comment]
onRegionChangeComplete did the work. It is not getting stuck now. :-)

**Comment by abdi4** [comment]
Just a quick question to anyone who got this working. Do you have to set a marker for user's current location or does that come with `showsUserLocation` out of the box?

**Comment by cybercoder** [comment]
> Just a quick question to anyone who got this working. Do you have to set a marker for user's current location or does that come with `showsUserLocation` out of the box?

It will shown but there's two prequsits: 1- cache not enabled 2- the container which the MapView is inside it, has a dynamic flex property in style, and the flex get 1 in ```componentDidMount``` using a setTimeout like this:

```javascript
let [flex, setFlex] = useState(0);

  useEffect(() => {
    setTimeout(() => {
      setFlex(1);
    }, 100);
  }, []);

...
<MapView style={{flex}} .../>
```

**Comment by cybercoder** [comment]
Is there a native event to force MapView to animate to GPS region ?
e.g. press map's current location using ref?

**Comment by henriquebarrosx** [comment]
> BTW, how can i get `latitudeDelta` and `longitudeDelta` from any location?

We can work if different kinds of value to `latitudeDelta` and `longitudeDeilta`, but there are some trade off to be considered. I noticed that using `latitudeDelta: 0.0922` and `longitudeDelta: 0.0421` was the best values finded to be more precised. Including the Geolocation configuration, like

```javascript
const geoLocationOptions: GeolocationOptions = {
  timeout: 15000, 
  maximumAge: 10000, 
  distanceFilter: 0,
  enableHighAccuracy: true,
};

```
