### ISSUE TITLE
Why are render images different with original render images?

### ISSUE THREAD

**Issue by magichim** [react-community/react-native-maps#2099]
### Is this a bug report?

(No)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Yes)

### Environment
"react": "^16.3.0-alpha.1",
"react-native": "0.54.2",
"react-native-maps": "https://github.com/react-community/react-native-maps.git"

### Steps to Reproduce

(Write your steps here:)

1. just put in code in root.
```
        <MapView
          style={...StyleSheet.absoluteFillObject}
          initialRegion={{
            latitude: 37.486,
            longitude: 127.044,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
        />
```
2. compare render image.
### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
<img width="680" alt="2018-03-15 11 48 49" src="https://user-images.githubusercontent.com/5843652/37471116-60ab3dd4-28ac-11e8-83f0-b578c7060e7d.png">

<Left: made by only swift,   Right: made by RN, react-native-map>

Google map still have raster tile image rendering in Korean because of legal problem.
But When I use react-native-map in RN, App is showing vector rendering image like other country.
I also made same page with swift only. however the app made by swift is same with web page.
Is it ip detect problem? I am so wondering.

**Comment by rborn** [comment]
@magichim on the right it's Apple map, not Google, you need to set the `provider` of the map first

**Comment by magichim** [comment]
@rborn oh really thanks! but I have a question. When I not use provider, automatically render apple map. however when this event like zoom and move by touching in simulator is triggering, it is very slow unlike google map. What's reason?

**Comment by rborn** [comment]
The simulator is slow, you might wanna try on a real device, and in release mode.
