### ISSUE TITLE
Relocate the 'Powered by Google' logo in MapView to a different part of the MapView

### ISSUE THREAD

**Issue by AliSarraf** [react-community/react-native-maps#2108]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Steps to Reproduce

The 'Powered By Google' logo appears in the bottom left of the MapView, but I have a component that floats at the bottom of the MapView. So this 'Powered by Google' logo is hidden, how do I position this logo to a different part of the MapView in order to comply with Google Maps' policy?

### Expected Behavior

I thought there would be a prop in MapView which would allow us to select a position for this logo to appear in the MapView

### Actual Behavior

A screenshot: https://prnt.sc/it0xsg
As you can see, the 'Powered by Google' logo at the bottom left isn't appearing because a component is covering it

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
Not sure this will work for Google maps, but please try: `legalLabelInsets`

**Comment by julienR2** [comment]
@AliSarraf You can set padding to the map. It will change the place of the Google logo to the corner of the padded map, and as an bonus, the center of the map will be adjusting accurately to the visible part of the map !
See the PR here for more detail https://github.com/react-community/react-native-maps/pull/1750 (We could probably add some docs on this one @rborn, the mapPadding property is actually missing from the MapView Docs https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md I'll try find some time to update it)

**Comment by rborn** [comment]
@julienR2 at the moment I have some busy time, I'll try to add the docs. 
Would be interesting to see if we can somehow normalise this between apple and google maps - if needed.
Any thoughts?

**Comment by julienR2** [comment]
I think @codypearce already offered a PR 👍(https://github.com/react-community/react-native-maps/pull/2121)
Good question about Apple logo.. I'll try to investigate a bit to see if it's needed (to be honest I don't even know if the apple logo has to appear on the map to respect the TOC). I'll check it out !

**Comment by rborn** [comment]
@julienR2  merged #2121 🎉  
Can we close this issue or should I wait for you to see the Apple stuff? 🤗

@AliSarraf  see #2121

**Comment by julienR2** [comment]
@rborn Nice ! Thanks 👍 
I checked and it is also necessary to let the "legal" label visible on IOS.. But good new is it act as GM, so the label moves with the paddings. So it should be all good already !

**Comment by AngelVenchev** [comment]
I don't think the mapPadding solved the problem of the issue. I'd like to reopen it. It only hides the google logo.
![screenshot_20190212-215335_electriceyemobile](https://user-images.githubusercontent.com/2339840/52664056-bf7af780-2f10-11e9-84b8-7aae53f8f73c.jpg)

This is the bottomPadding set to 15

**Comment by LukePenkava** [comment]
Being able to relocate the Google logo would solve literally all the issues. Or just let us hide it and put it there ourselves. That would be super simple to do and we would be able to position it anywhere on the screen with absolute position.
 I am totaly stuck on this Google logo thing for a month, because it gets removed when i use bottom padding on Android.

**Comment by rborn** [comment]
@LukePenkava we cannot touch that, the only way to move it is to use the padding (which seems not to work ?)

**Comment by LukePenkava** [comment]
@rborn I have to re-render the map to make the Google logo reappear, otherwise it does not show up on Android. If we cant position the Google as we need with absolute position and we cant hide it to show it ourselves, it would be good if it would not require re-render to get it working. Or it should be at least clarified that it needs re-render i think. 
 Padding is not ideal to move the logo tho, it has limitations. ( Ex. have map centred at top half of the screen and show logo at the bottom of the screen is not possible now )

```
style={[styles.map, { width: this.state.width }]}
onMapReady={() => this.setState({ width: this.state.width - 1 })}
```

**Comment by rborn** [comment]
@LukePenkava my understanding is that the logo cannot be altered in any way other than Google decides. So for now a padding can be set but all the controls will be pushed away from the edge basd on that control

As for the re-rendering I don't know, I didn't have to move that in any of my projects.

**Comment by grobelDev** [comment]
I fixed this issue by putting the `MapView` in a parent `View` for Android.

Something like this:
```
<View style={{ ...StyleSheet.absoluteFillObject }}>
  <MapView
    style={{
      ...StyleSheet.absoluteFillObject,
    }}
    mapPadding={{
      top: 0,
      left: 0,
      right: 0,
      bottom: 500,
    }}
  />
</View>
```

End Result:
<img width="401" alt="Screen Shot 2020-06-25 at 4 14 22 PM" src="https://user-images.githubusercontent.com/56764278/85804629-f6fdd480-b6fe-11ea-9375-eb79232a9fc4.png">

**Comment by rp-nova** [comment]
@LukePenkava thanks for that trick!
