### ISSUE TITLE
Overlay component not working - `Invariant Violation: Native component for "AIRGoogleMapOverlay" does not exist`

### ISSUE THREAD

**Issue by swese44** [react-community/react-native-maps#2109]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
    react-native: 0.54.0-rc.3
    react: 16.2.0
    react-native-maps: 0.20.1

  Target Platform: eg: iOS - 11.2 Simulator/iPhone 6

  Google Maps

### Steps to Reproduce
I'm new to iOS and React Native so maybe I've missed some configuration others would generally know about. The react-native-maps installation docs are missing instructions for installing the Podfile after creating it, maybe there are other missing instructions.

I'm trying to nest `<Overlay>` in a `<MapView>`:
```
<MapView ...>
    <Overlay bounds={overlayBounds} image={overlayImage} />
</MapView>
```

### Expected Behavior
Render an image overlay without error

### Actual Behavior
I get the error `Invariant Violation: Native component for "AIRGoogleMapOverlay" does not exist`.

<img width="374" alt="screen shot 2018-03-19 at 1 02 54 am" src="https://user-images.githubusercontent.com/471731/37584098-5769e2f4-2b11-11e8-8517-940cf76e17eb.png">

**Comment by rborn** [comment]
Try to use the git version of the module. Also did you see the `# REMOVE THIS if you use RN 0.54+` part in Podfile ?. 

What are the instructions you think are missing?

**Comment by swese44** [comment]
thanks @rborn

Regarding missing instructions, I had initially missed the `pod install` step but it's in the readme so nevermind 😳

My Podfile was correct, but things must have gotten borked while upgrading different versions of react-native, react-native-maps, etc. I started over with a fresh RN install and things are good now.

**Comment by sfm2222** [comment]
can you share the podfile
