### ISSUE TITLE
setState infinity loop in onRegionChange

### ISSUE THREAD

**Issue by moh3n9595** [react-community/react-native-maps#2110]
Hi, when I use `this.setState` inside of onRegionChange function, program stuck on an infinity loop. 

Code :  
 ```
  onRegionChange(region) {
    this.setState({myVar : 2 });
  }
render() {
 return (
          <MapView region={this.state.region} onRegionChange={(region) =>this.onRegionChange(region)} >
            {this.state.markerLevel1} // some marker is here!
          </MapView> 
)
}
```
Is this a bug? what I do this for?

**Comment by rborn** [comment]
No template, I'll close this.

Don't make the region state dependent, make a search among the issues and you'll find more info about.

**Comment by moh3n9595** [comment]
But in main doc I see something like this : `Using a MapView while controlling the region as state`.
what is other way for that? please give me a link or code to find that.

**Comment by rborn** [comment]
I think this will need to be changed.

**Comment by borgogelli** [comment]
So does the documentation is wrong about it ?
