### ISSUE TITLE
Is there any option to render map with default zoom ?

### ISSUE THREAD

**Issue by Anandks1993** [react-community/react-native-maps#2129]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.54.2
    react: 16.0.016.3.0-alpha.1
    react-native-maps: https://github.com/react-community/react-native-maps.git

Is there an option to render the map with default zoom option ? I checked props of MapView but I didn't find any about that.

**Comment by rborn** [comment]
@Anandks1993  The zoom is controlled by longitudeDelta and latituteDelta.

**Comment by Anandks1993** [comment]
@rborn Thank you 🤝

**Comment by sturmenta** [comment]
```
import { Dimensions } from 'react-native';
const { height, width } = Dimensions.get( 'window' );
const LATITUDE = 40.74333; // Korea Town, New York, NY 10001
const LONGITUDE = -73.99033; // Korea Town, New York, NY 10001
const LATITUDE_DELTA = 0.28;
const LONGITUDE_DELTA = LATITUDE_DELTA * (width / height);

<MapView
	initialRegion={{
		latitude: LATITUDE,
		longitude: LONGITUDE,
		latitudeDelta: LATITUDE_DELTA,
		longitudeDelta: LONGITUDE_DELTA
	}}
	...
>

**Comment by abbasmoosavi** [comment]
> ```
> import { Dimensions } from 'react-native';
> const { height, width } = Dimensions.get( 'window' );
> const LATITUDE = 40.74333; // Korea Town, New York, NY 10001
> const LONGITUDE = -73.99033; // Korea Town, New York, NY 10001
> const LATITUDE_DELTA = 0.28;
> const LONGITUDE_DELTA = LATITUDE_DELTA * (width / height);
> 
> <MapView
> 	initialRegion={{
> 		latitude: LATITUDE,
> 		longitude: LONGITUDE,
> 		latitudeDelta: LATITUDE_DELTA,
> 		longitudeDelta: LONGITUDE_DELTA
> 	}}
> 	...
> >
> ```
> 
> LATITUDE_DELTA = zoom level

Thanks bro

**Comment by suhailkakar** [comment]
@sturmenta , Thanks It is working perfectly
