### ISSUE TITLE
Clustering map

### ISSUE THREAD

**Issue by thiagoterleski** [react-community/react-native-maps#213]
There are clustering support?

**Comment by raphaelsaunier** [comment]
There's an open PR which adds marker clustering on iOS here: https://github.com/lelandrichardson/react-native-maps/pull/137

**Comment by bcalik** [comment]
This feature is a must.

**Comment by lucaboieru** [comment]
Any idea when will this be available? 👍

**Comment by nazywamsiepawel** [comment]
+1, important feature!

**Comment by zverev** [comment]
+1

**Comment by imperat0r** [comment]
+1

**Comment by Exilz** [comment]
+1

**Comment by java99** [comment]
+1

**Comment by esutton** [comment]
+1

**Comment by klaste** [comment]
We use https://github.com/mapbox/supercluster in combination with https://github.com/mapbox/geo-viewport to cluster 2000 locations. It works like a charm on iOS and Android.

**Comment by bcalik** [comment]
@klaste Could you please make a simple example?

**Comment by m-tbox** [comment]
I want to add clustering feature in my app I am using "react-native-maps" but I don’t have “clusterMarkers” prop in my library which I have installed using "npm install react-native-maps --save” how can I use "react-native-maps" library to add clustering feature to my markers ?

**Comment by m-tbox** [comment]
I want to add clustering feature in my app I am using "react-native-maps" but I don’t have “clusterMarkers” prop in my library which I have installed using "npm install react-native-maps” how can I use this library to add clustering feature to my markers.

**Comment by shafy** [comment]
+1

**Comment by jomaint** [comment]
+1

**Comment by gilbox** [comment]
If you want this feature, I'd suggest try taking over the PR 
https://github.com/airbnb/react-native-maps/pull/137

**Comment by herlon214** [comment]
+1

**Comment by MatthiasDebaere** [comment]
+1

**Comment by almirfilho** [comment]
+1

**Comment by sahir** [comment]
did you find any solution for clustering in Android :  @thiagoterleski  @raphaelsaunier

**Comment by Clcll** [comment]
@klaste how can we it in react native ?

**Comment by Exilz** [comment]
@sahir @Clcll I managed to add clusters to android & ios with supercluster and @i-tu 's gist. Here it is : https://gist.github.com/i-tu/05e79737adfe36935ec869125a686f82

It is easy to do if you wrap your mind around it. The major issue is performance, if you need to display hundreds or thousands of markers you're gonna have to optimize the hell out of it, and this is where it gets really hard.

This is a decent solution, but I think we still need a native implementation.

**Comment by iiitmahesh** [comment]
:+1:

**Comment by warka0** [comment]
If someone come here and want something working right now, i made an example :  
https://github.com/warka0/react-native-cluster-example

**Comment by rigobcastro** [comment]
+1 native feature

**Comment by anupkale1984** [comment]
+1 for clustering feature

**Comment by wilbyang** [comment]
+1 for clustering feature

**Comment by nehvaleem** [comment]
+1 for clustering. it is a really must-have!

**Comment by Jazz747** [comment]
looks like PR about that just came in #1344

**Comment by nehvaleem** [comment]
@Jazz747 - it looks promising! I hope we can manage to implement both PR for complete clustering solution!

**Comment by Clowning** [comment]
Any news ?

**Comment by luco** [comment]
+1 on this

**Comment by oskaryil** [comment]
+1

**Comment by nschurmann** [comment]
+1

**Comment by nschurmann** [comment]
Please!!!

**Comment by slane2016** [comment]
Pretty please!!

**Comment by gilra2000** [comment]
+1 please!!

**Comment by beornborn** [comment]
+1

**Comment by karimkazoo** [comment]
+1

**Comment by venits** [comment]
You can try this. It works for me :) https://github.com/venits/react-native-map-clustering
It is the simplest solution right now.

**Comment by GetSource1234** [comment]
+1

**Comment by clarktank** [comment]
+1

**Comment by 39otrebla** [comment]
We are working on a supercluster-based version as well, it is performing (and behaving) correctly. It'll be mounted on a production application in late Dec 2017. Try it out: https://github.com/novalabio/react-native-maps-super-cluster

**Comment by timsaval** [comment]
👾 Much love from team Plural if this would be added 👏

**Comment by alvelig** [comment]
Seeing many issues in implementing clustering natively. https://github.com/novalabio/react-native-maps-super-cluster is the best alternative actually.

**Comment by dbyilmaz** [comment]
+1 for clustering feature

**Comment by krystianpach** [comment]
+1

**Comment by terrathe2** [comment]
+1

**Comment by andr3a88** [comment]
+1

**Comment by tugorez** [comment]
+1

**Comment by cinder92** [comment]
+1

**Comment by jonathanmauer** [comment]
+1

**Comment by andr3a88** [comment]
+1

**Comment by dbyilmaz** [comment]
+1

**Comment by markozelenbaba** [comment]
+1

**Comment by rborn** [comment]
Going to close and lock the issue because there is a "good enough" solution mentioned in the comments and the discussion only goes "+1" which doesn't bring value.

If anybody has a better solution please open a PR.
