### ISSUE TITLE
Object.assign not behaving as before when updating the library

### ISSUE THREAD

**Issue by ou2s** [react-community/react-native-maps#2130]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

   react-native: 0.52.1
   react: 16.2.0
   react-native-maps: 0.20.1

### Steps to Reproduce

- Install the react-native-maps@0.20.1 via npm/yarn
- Use Object.assign with a prototype object like below
`Object.assign(new Example(), {test : "test"}`

### Expected Behavior

No React Native error as it was with version 0.17.1

### Actual Behavior

It is causing the  error below:
`TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.`

I also had to deal with issues like when I was using spread operator with StyleSheet: 
`TypeError: In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.`

I don't understand why I was not having this issue before updating the react-native-maps. I suspect it's because of the addition of `babel-preset-react-native` and its `babel-plugin-transform-object-assign`.

This may be related to this RN issue : https://github.com/facebook/react-native/issues/16814

**Comment by rborn** [comment]
@ou2s What does this have to do with `react-native-maps`?

**Comment by ou2s** [comment]
@rborn I don't know but I don't have this issue with 0.17.1 and I have it with 0.20.1 so there is a link with the changes in the dependencies in the latest version of `react-native-maps`.

**Comment by rborn** [comment]
Without some code to see  what you are doing there we can't really help.

**Comment by ou2s** [comment]
Snippets are explicit and I cannot add code, but let's close this issue as I seem I'm the only complaining about it.
