### ISSUE TITLE
How to render a list of MapView with different coordinates in one page using FlatList Component 

### ISSUE THREAD

**Issue by aminvb12** [react-community/react-native-maps#2138]
I'm using below code but list of map not rendering:
/////////////////////////////////////////////////////////////////////////////

import React, { Component } from 'react';
import {
    Platform,
    StyleSheet,
    Text,
    View,
    ScrollView,
    Image,Dimensions,TextInput,FlatList
} from 'react-native';
import MapView from 'react-native-maps';
import Modal from "react-native-modal";
import Images from './location.png'
import { Button } from 'react-native-elements'

var width=Dimensions.get('window').width;
var height=Dimensions.get('window').height;

export default class App extends Component {
    constructor(props){
        super(props);
        this.state={
            region: {
                latitude: 37.78825,
                longitude: -122.4324,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
            },
            isModalVisible:false,
            test:[{a:1,"b":2},{a:2,"b":3}]
        }
    }

    onUserPinDragEnd = (e) =>{
        console.log(e.nativeEvent)

    };

    _toggleModal = ()=>{
        this.setState({
            isModalVisible:!this.state.isModalVisible
        })
    };

    render() {
        return (

<FlatList
    data={this.state.test}
    renderItem={({ item,index}) => (
                    <View style={{ flex:.5,alignItems:'center',justifyContent:'center',backgroundColor:'#F5FCFF',marginTop:50}}>
                        <MapView
                            style={{ left:0, right: 0, top:0, bottom: 0, position: 'absolute' }}
                            initialRegion={{
                                latitude: 29.607987,
                                longitude: 52.508046,
                                latitudeDelta:  0.00922*1.5,
                                longitudeDelta: 0.00421*1.5
                            }}
                            showsUserLocation={true}
                            mapType={'hybrid'}
                            loadingEnabled={true}
                            followUserLocation={true}
                            zoomEnabled={true}
                        >

                            <MapView.Marker
                                draggable
                                onDragEnd={this.onUserPinDragEnd.bind(this)}
                                onPress={()=>{
                                    this._toggleModal()
                                }}
                                coordinate={{
                                    latitude: 29.607987,
                                    longitude: 52.508046}}
                            >
                                <View style={styles.radius}>
                                    <View style={styles.marker}/>
                                </View>
                            </MapView.Marker>
                        </MapView>
                    </View>

                )}

                keyExtractor={(item, index) => item.b}
                />

        );
    }

}

const styles = StyleSheet.create({

    radius:{
        width:50,
        height:50,
        borderRadius:50/2,
        backgroundColor:'rgba(0,112,255,0.3)',
        borderColor:'rgba(0,112,255,0.3)',
        borderWidth:1,

        alignItems:'center',
        justifyContent:'center'
    },
    marker:{
        height:20,
        width:20,
        borderWidth:3,
        borderColor:'white',
        borderRadius:20/2,
        overflow:'hidden',
        backgroundColor:'#007AFF'

    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
    },
    viewInnerModal:{
        flex: .6,
        borderWidth:1,borderColor:'white',backgroundColor:'white',borderRadius:20,  shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.8,
        shadowRadius: 2,
        alignItems:'center',
        justifyContent:'center',

    },
    locationLogo:{
        flex:.25,
        alignItems:'center',
        justifyContent:'center'

    },
    st:{
        width:150
    },

    viewButton:{

        flexDirection:'row',
        alignItems:'flex-end',
        justifyContent:'center',
        marginBottom:height/5
    }

});

**Comment by rborn** [comment]
No template on any type of information, closing

**Comment by aminvb12** [comment]
@rborn can you please help me about this issue?

**Comment by rborn** [comment]
@aminvb12 how can I help if you didn't even try to respect the simple requirement of filling the issue template. We are giving our free time to the community but you expect to be helped without putting any little effort into it. Sorry.
