### ISSUE TITLE
Map zoom is different with provider="google" in iOS

### ISSUE THREAD

**Issue by danielhq** [react-community/react-native-maps#2140]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.52.0
    react: 16.2.0
    expo: 25.0.0
    react-native-maps: 0.19.0 or "git+ssh://git@github.com/react-community/react-native-maps.git"

### Steps to Reproduce
Add a Map to a View
`<MapView
    style={{ height: 400, width: ‘100%’ }}
    provider="google"
    initialRegion={{
        latitude: 45.463908,
        longitude: 9.19788,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421
    }}
/>`

### Expected Behavior
I'd expect the same map zoom in both iOS and Android.
#### Screenshot in iOs 11.2.6
![img_604054e5af00-1](https://user-images.githubusercontent.com/1651415/38129641-2803ecce-3400-11e8-90d6-aab65a578186.jpeg)
#### Screenshot in Android 8
![screenshot_1522396331](https://user-images.githubusercontent.com/1651415/38129689-5329e2be-3400-11e8-85d9-cfea94073339.png)

### Actual Behavior
iOS ignores the longitudeDelta and latituteDelta when using provider="google" values and map is zoomed out.

### Reproducible Demo

[snack.io](https://snack.expo.io/@evoluzione/map-zoom)

**Comment by halzahrani79** [comment]
I spent hours and hours trying to solve the longitudeDelta to discover minutes ago that there is a bug on ios when using google as provider , thank you for opening this issue

**Comment by rborn** [comment]
We merged #2131 two days ago, can you try with the last master (so the git version).

**Comment by danielhq** [comment]
@rborn I tried the last version (sdk 26) and it's working now.

**Comment by amerazzam** [comment]
> We merged #2131 two days ago, can you try with the last master (so the git version).

how did you solve this issue please because I am using google maps in my app and the zoom level differs between the IOS and the android
