### ISSUE TITLE
Prevent Polygon intersecting?

### ISSUE THREAD

**Issue by Bassonlinho** [react-community/react-native-maps#2143]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.45.1
    react: 16.0.0
   react-native-maps: 0.16.2

### Steps to Reproduce

/

### Expected Behavior

Prevent Polygon from being line intersected while drawing.

### Actual Behavior

It's possible to intersect at the moment.

### Reproducible Demo

Is it possible to, while drawing Polygon, prevent user from intersecting Polygon lines?
If not by the component itself, then by some other service. I'd like to prevent users from intersecting Polygon lines and provide them with some error if they try to do so, so when they finish with drawing Polygon gets it fill color?

**Comment by rborn** [comment]
This is outside the scope of this module. Closing.
