### ISSUE TITLE
[ADVICE NEEDED] How to additional Java Library

### ISSUE THREAD

**Issue by Stophface** [react-community/react-native-maps#2145]
I want to bring more functionality to react-native-maps. In order to do that, I have to add an [additional Java library][1]. No I wonder where exactly am I supposed to add the Java library that it works with react-native-maps. Do I add here (in a newly created `lib` folder)
https://github.com/react-community/react-native-maps/tree/master/lib/android or somewhere else? How do I make it "known" to Java?

  [1]: https://de.wikipedia.org/wiki/Java_Database_Connectivity

**Comment by rborn** [comment]
@Stophface no template, I'll close the issue till you update it.
