### ISSUE TITLE
estimated arrival time (question)

### ISSUE THREAD

**Issue by starba3** [react-community/react-native-maps#2151]
does mapview provide function to calculate estimated arrival time between 2 latlng objects?
if not is there any other to get the function.

**Comment by markmssd** [comment]
You will probably need to use Google's Directions service for this.

**Comment by markmssd** [comment]
https://github.com/bramus/react-native-maps-directions might also be useful to you.

**Comment by starba3** [comment]
will try, if it didn't work well i will just use 
Distance Matrix through fetch api.
thanks for quick response

**Comment by rborn** [comment]
Closing, no template, not a real issue.

**Comment by DevAelius** [comment]
after the googles map api is fetched

var EstimateTime = respJson.routes[0].legs[0].duration.text
console.log("Estimate Time=>",EstimateTime)
