### ISSUE TITLE
Building Crashes With Error

### ISSUE THREAD

**Issue by rpicking** [react-community/react-native-maps#2152]
### Is this a bug report?

Yes

### Environment

"react": "16.3.0-alpha.1",
"react-native": "0.54.4",
"react-native-maps": "^0.21.0"

Target Platform: android

### Steps to Reproduce

1. Create new project with react-native init
2. npm install --save react-native-maps
3. Follow installation steps
4. react-native run-android
5. Build crashes

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method implementation() for arguments [project ':react-native-maps'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by wbattel4607** [comment]
I'm guessing https://github.com/react-community/react-native-maps/pull/2096 is what's causing it.

See what happens if you revert those changes yourself. You can do this by navigating to node_modules/react-native-maps/lib/android/build.gradle and changing

these lines
```
  compileOnly "com.facebook.react:react-native:+"
  implementation "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
  implementation "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
  implementation "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
```
to
```
  provided "com.facebook.react:react-native:+"
  compile "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
  compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
  compile "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
```
and see if the project builds.

**Comment by rborn** [comment]
@rpicking did you update your gradle ? https://github.com/react-community/react-native-maps/pull/2096#issuecomment-376877553

**Comment by havinhthai** [comment]
Same problem

**Comment by havinhthai** [comment]
Fixed, thanks @wasa4587

**Comment by havinhthai** [comment]
Fixed, thanks @wbattel4607

**Comment by wbattel4607** [comment]
Everyone upgrading to version 0.21.0 will need to upgrade their gradle to 3.0.0+ as described [here](https://github.com/react-community/react-native-maps/pull/2096#issuecomment-376860933).
---
@havinhthai no problem

**Comment by rpicking** [comment]
Sorry for delay upgrading gradle fixed the issue

**Comment by rborn** [comment]
Closing as fixed

**Comment by seftrick** [comment]
I found solution here: 
https://itnext.io/install-react-native-maps-with-gradle-3-on-android-44f91a70a395

**Comment by lastpeony** [comment]
tried all same problem.

**Comment by rborn** [comment]
@lastpeony please don't comment on multiple issues if you don't come with a solution.
