### ISSUE TITLE
The app crashes after reinstalling the react-native-maps 0.21.0

### ISSUE THREAD

**Issue by xempie** [react-community/react-native-maps#2155]
### Environment

    react-native: 0.54.0
    react: 16.0.0
    react-native-maps: 0.21.0 
   Target Platform:  Android 7.0 Galaxy S6

### Expected Behavior

I'm using the react-native-maps for about a year and I never had such an issue but I recently reinstalled it but my app crashes when I use <MapView> component. 
There is no change in my code but just I reinstalled the library and did all the steps in installation to make changes in build.gradle files and others as advised. 

I used gradle 2.2.3 (I guess) but seems in this version I need to use gradle 3.0.1 or higher which I updated it as well. 

I followed the steps in #2152 so I could build but when run it it crashes again.

### Actual Behavior

The application crashes

**Comment by havinhthai** [comment]
Did you update your gradle to 3?

**Comment by rborn** [comment]
- If it crashes it should have some logs, try to get some
- gradle neeeds to be updated to 3 (there are 2 places you need to be sure things are changed - https://github.com/react-community/react-native-maps/pull/2096#issuecomment-376877553)
- run a `gradle clean` (in your android folder)

**Comment by xempie** [comment]
I found the issue
needed to use google play services base v11.0.4 instead of 10.0.1
also complile sdk version 27.0.3

```
implementation(project(':react-native-maps')){
            exclude group: 'com.google.android.gms', module: 'play-services-base'
            exclude group: 'com.google.android.gms', module: 'play-services-maps'
        }
        implementation 'com.google.android.gms:play-services-base:11.0.4'
        implementation 'com.google.android.gms:play-services-maps:11.0.4'
}
```

**Comment by Xaus** [comment]
i have the same problem when turning on   showsUserLocation={true} above solutions didn't work :-(

**Comment by umairalii** [comment]
<uses-library
        android:name="org.apache.http.legacy"
        android:required='false' />

in androidmenifest.xml

**Comment by umairalii** [comment]
`<uses-library
        android:name="org.apache.http.legacy"
        android:required='false' />`

in androidMenefest
