### ISSUE TITLE
Unknown error when add Callout

### ISSUE THREAD

**Issue by pnthach95** [react-community/react-native-maps#2156]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.48.4
react: 16.0.0-alpha.12
react-native-maps: 0.21.0

### Steps to Reproduce
I try to add Callout

```
<MapView
...>
            {this.state.data
              ? this.state.data.map((gara, index) => (
                <MapView.Marker
                  key={index}
                  image={require('../../../assets/images/marker-65x87.png')}
                  coordinate={{
                    latitude: Number(gara.lat),
                    longitude: Number(gara.long)
                  }}
                  onPress={this._loadInitialState}
                >
                  <MapView.Callout>
                    <Text>{gara.name}</Text>
                    <Text>{`Available: ${gara.current_bike}`}</Text>
                  </MapView.Callout>

                  <View style={{
                    flex: 1,
                    justifyContent: 'center',
                    alignItems: 'center',
                    width: 35, height: 35,
                  }}>
                    <Text>
                      {gara.current_bike}
                    </Text>
                  </View>

                </MapView.Marker>
              ))
              : null}
</MapView>
```

### Expected Behavior

Show Callout when press marker

### Actual Behavior

I get this error every time open app and markers disappear:
![screenshot_20180403-102352](https://user-images.githubusercontent.com/31266357/38227745-eedb668e-3729-11e8-83cf-171511ef9f4c.png)

**Comment by rborn** [comment]
Your Callout has 2 Texts inside, try to add a single child ( or a wrapper View around the texts)

**Comment by pnthach95** [comment]
No luck with that. Still get the same error.

**Comment by pnthach95** [comment]
I just moved Callout below View, problem solved.
