### ISSUE TITLE
Markers from KML-File not showing

### ISSUE THREAD

**Issue by stereu** [react-community/react-native-maps#2164]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment

    react-native: 0.54.4
    react: 16.3.1
    react-native-maps: 0.21.0 / Google Maps

### Steps to Reproduce

Started the Example (AirMapsExplorer), selected GoogleMaps mode and clicked "Load Map with KML".

### Expected Behavior

Multiple Markers will be placed like defined in the KML on pastebin.

### Actual Behavior

No markers were shown except of the "Test" marker.

**Comment by pncosta** [comment]
Hi
in the end were you able to get the markers from the kml to work?

even with the same code as in the example I only get the "test" marker, but no marker from the kml file is shown.
