### ISSUE TITLE
Use of "showsUserLocation" rejected by Apple because message not specific enough

### ISSUE THREAD

**Issue by sfyfe31** [react-community/react-native-maps#2170]
### Is this a bug report?

Half a bug, half a feature request

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react: 16.3.0-alpha.1
react-native: 0.54.0
react-native-maps: ^0.21.0

### Steps to Reproduce

iOS App Store build was rejected because the request user's location message was not specific enough. The generic "would like to use your location" message is too vague for their approval rules now.

This is when using the `showsUserLocation` attribute in a `<MapView />`.

### Expected Behaviour

Ideally it would be possible to add a custom message. e.g. `<MapView showsUserLocation={'We would like to use your location, to show where you are on our map'}></ MapView>`

### Actual Behavior

The binary was rejected in iTunes Connect

### Reproducible Demo

N/A as this is a functionality issue, rather than a bug in the code

**Comment by rborn** [comment]
This is outside the scope of the module. 

You need to provide a meaningful and specific to your app text in the `info.plist` file in the ios project for the key `NSLocationWhenInUseUsageDescription` (the text you specified in your example)

The module cannot and should not do this, as there are cases when you'd need more control, like multi language for example.

Closing, ping me if you still have issues 🤗

**Comment by sfyfe31** [comment]
Thanks for that explanation. I've submitted a pull request to add it to the readme
