### ISSUE TITLE
Buillding crash 

### ISSUE THREAD

**Issue by rdy23x** [react-community/react-native-maps#2175]
* What went wrong:
A problem occurred evaluating project ':react-native-maps'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by rborn** [comment]
No issue template, closing

**Comment by hungdev** [comment]
i get same issue

**Comment by mmontone** [comment]
I'm having this problem too. Why is this closed?

**Comment by muzammil-triffort** [comment]
@hungdev Did you find any solution? I am also facing issue with "react-native-camera".

**Comment by rborn** [comment]
@mmontone it's pretty clear to me, the author didn't care to respect the issue template we've set in place.

**Comment by hungdev** [comment]
@muzammil-triffort  and @mmontone  
this my solution. hope this will help guys.
look at readme
https://github.com/hungdev/IntegrateMapAndCamera
