### ISSUE TITLE
Many polygons will make the map performance slowly

### ISSUE THREAD

**Issue by nc3816** [react-community/react-native-maps#2176]
### Is this a bug report?
Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes.

### Environment
    react-native: 0.50.1
    react: 16.0.0
    react-native-maps: 0.19.0 

### Steps to Reproduce

1. npm install react-native-geojson from [https://www.npmjs.com/package/react-native-geojson](react-native-geojson)
2. fetch the geojson data and render the polygons (321 polygons)
My code is similar like below:

`import React from 'react';`
`import MapView from 'react-native-maps';`
`import Geojson from 'react-native-geojson';`

`export default class HomeScene extends React.Component {`
   ` constructor(props) {`
      `  super(props);`
        `// default value for the states`
        `this.state =`
      `  {`
       `   data:[]`
       `  }`
`}`

 `getData = (region) => {   `
      `  var URL = 'http://URL.COM';`
       ` return fetch(URL, {`
          `  method: 'GET',`
         `   headers: headers`
       ` })`
    `    .then((response) => response.json())`
       ` .then((response) => {`
           ` this.setState({`
               ` data: geojonsdata,`
        `    },function(){`
          `  });`
      `  })`
      `  .catch((error) =>{`
          `  console.error(error);`
   `     });`
   ` })   `
`} `
`render(){`
  `<MapView`
        `onRegionChangeComplete={this.getData}`
 ` >`
   ` <Geojson geojson={this.state.data} />`
  `</MapView>`
`};`

### Expected Behavior
After rendering the polygons, should drag, zoom in or zoom out the map smoothly.

### Actual Behavior
When I try to render 321 polygons, it will makes the map performance slowly and delay in 5-7 seconds.

Any suggestion on how to optimize the performance? Thank you!

**Comment by rborn** [comment]
321 polygons is a lot, if they are not all visible you should remove them when they are not in the view.
You could also cluster them when the map it's zoomed out

**Comment by nc3816** [comment]
@rborn Thank you for the reply. I know markers could cluster, but how the polygons are clustered?

**Comment by rborn** [comment]
@nc3816 I think you will need to find a way to "unify" some of them in a bigger polygon depending on the zoom. Not sure how to do this though :(

**Comment by ManUtd27** [comment]
I'm having the same issue. Making and RESTfull API call to GeoServer that returns a Geojson feature collections.  Also having the issue of encountering two children with the same key. 

"Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and:could change in a future version."

 https://www.npmjs.com/package/react-native-geojson

**Comment by nc3816** [comment]
Follow the idea of @rborn, I solved this problem. Thank you @rborn !
The method is looping the coordinates, remove the points which are not in the view of the current map view. And generate a new Geojson object to render, works well.
Close this issue, thank you.

**Comment by Diwei-Chen** [comment]
Can you please provide more information of how to do this? @rborn @nc3816

**Comment by akhromets** [comment]
Hi @Diwei-Chen,
you can use a library like [turf](http://turfjs.org/docs/) to find intersections. Below is an example of how to use it.
Hope this helps other guys when looking for this issue.

```javascript
import * as turf from '@turf/turf';

const getConvertedRegionToPolygon = (region) => {
  const leftTopLongitude  = region.longitude - (region.longitudeDelta / 2);
  const rightTopLongitude = region.longitude + (region.longitudeDelta / 2);
  const leftTopLatitude   = region.latitude  + (region.latitudeDelta / 2);
  const rightTopLatitude  = region.latitude  + (region.latitudeDelta / 2);

  const leftBottomLongitude  = region.longitude - (region.longitudeDelta / 2);
  const rightBottomLongitude = region.longitude + (region.longitudeDelta / 2);
  const leftBottomLatitude   = region.latitude  - (region.latitudeDelta / 2);
  const rightBottomLatitude  = region.latitude  - (region.latitudeDelta / 2);

  const coordinates = [[
    [leftTopLongitude, leftTopLatitude],
    [leftBottomLongitude, leftBottomLatitude],
    [rightBottomLongitude, rightBottomLatitude],
    [rightTopLongitude, rightTopLatitude],
    [leftTopLongitude, leftTopLatitude]
  ]];

  return turf.polygon(coordinates);
};

const onRegionChange = (region) => {
  // put your geoJSONData from state etc.
  if (!geoJSONData) {
    return;
  }
  const polygon = getConvertedRegionToPolygon(region);
  const filteredPolygons = geoJSONData.features.filter(feature => turf.intersect(polygon, feature));
  const geoData = turf.featureCollection(filteredPolygons);
  
  // put your result into Geojson component
  setFilteredGeoJSONData(geoData);
};

return <Geojson geojson={filteredGeoJSONData}/>;
```
