### ISSUE TITLE
Change mapType after mounted.

### ISSUE THREAD

**Issue by JoseVf** [react-community/react-native-maps#2178]
### Is this a bug report?

No.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

react-native: 0.47.1
react: 16.0.0-alpha.12
react-native-maps: 0.15.3

### Expected Behavior

Is there a way to change the mapType when the user tap on a button? I tried to make it setting the mapType on the state and when the user tap other mapType change with setState but doesn't works.

**Comment by rborn** [comment]
@JoseVf did you try with a newer version of the module? `0.15.3` is pretty old

**Comment by JoseVf** [comment]
@rborn Nope, I've not tried with a newer version 😕. I'm gonna try it and then come back here 😅

**Comment by JoseVf** [comment]
Okay, in the latest version (0.21.0) it works just changing the state.
