### ISSUE TITLE
showsMyLocationButton

### ISSUE THREAD

**Issue by sofiane-soufi** [react-community/react-native-maps#2190]
Hello,

I'd like to know if there's anyway to add an offset to the showsMyLocationButton.. I want to change its position and I couldn't find how.

Thank you!

**Comment by sofiane-soufi** [comment]
Solved!

Add the attribute mapPadding to your Mapview and set the positions with top, left, bottom, right!

**Comment by udaysai27** [comment]
@sofiane-soufi Can we change the icon too?

**Comment by julienR2** [comment]
@udaysai27 From what I know, GM doesn't let you customize the icon. However you can disable `showMyLocationButton` and implement your own button to trigger [`getCurrentLocation`](https://facebook.github.io/react-native/docs/geolocation.html#getcurrentposition).

**Comment by rborn** [comment]
Closing, no issue template and solved as per https://github.com/react-community/react-native-maps/issues/2190#issuecomment-380934643

**Comment by TaraSinghDanu** [comment]
> Solved!
> 
> Add the attribute mapPadding to your Mapview and set the positions with top, left, bottom, right!

By using mapPadding, current location marker not coming in center
