### ISSUE TITLE
AnimatedViews..js

### ISSUE THREAD

**Issue by sofiane-soufi** [react-community/react-native-maps#2192]
Hi!

I've been trying to integrate this https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedViews.js to my existing map but since it looks like everything's in the constructor, it seems harder to integrate to my code since I load the markers dynamically.

Does anyone have a tutorial of how to do something similar for dynamic loaded markers?

[Image](https://camo.githubusercontent.com/9b5fcde0cb8146672f54d39fc3c34bd2e1f7891f/687474703a2f2f692e67697068792e636f6d2f336f365542644751644d31476d566f4964712e676966)

Thank you.

**Comment by rborn** [comment]
closing, no issue template

**Comment by sofiane-soufi** [comment]
Actually, the Animated View is not working. I tried to copy paste the example and it's not.
