### ISSUE TITLE
[GOOGLE MAPS][IOS] onPress event not fired for polyline

### ISSUE THREAD

**Issue by VladCherniavsky** [react-community/react-native-maps#2194]
Hi to all.

Could you tell about support of onPress for polyline on google maps for ios ?

It seems to me that it isn't  implemented. For android works fine

Thank you

**Comment by rborn** [comment]
closing, no  issue template

**Comment by VladCherniavsky** [comment]
@doomsower  thanks for the answer

but it didn't help. onPress still not fired on ios
```
<MapView.Polyline
        tappable={true}
        lineCap={'butt'}
        onPress={(this.onPressPolyline(route, index))}
        key={index}
        coordinates={route.polyline}
        strokeWidth={ polylineStyles[index].strokeWidth}
        strokeColor={ polylineStyles[index].color} />
```

**Comment by weisssean** [comment]
I got stuck on this for a while, onPress was working on Android and iOS but not with GoogleMaps on iOS. Found out I needed the tappable={true} attribute. now my question is, why do you need such an attribute? Isn't it obvious that I want it to be tappable if I have an onPress event?
Can you not just check whether onPress does not equal null?

**Comment by danloiterton** [comment]
Same issue for me. Adding `tappable={true}` to the `Polyline` props fixed it (thanks @weisssean). This doesn't seem to be documented anywhere.
