### ISSUE TITLE
ios do not connect to internet

### ISSUE THREAD

**Issue by ariya94** [react-community/react-native-maps#2198]
hi
i am in trouble
in android we use the `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>` for connecting to internet.
what is the permission in ios? how can i add it

**Comment by julienR2** [comment]
I think you're mistaking with `<uses-permission android:name="android.permission.INTERNET" />` on Android.
Not an expert on IOS, but I'd have a first look here https://github.com/codepath/ios_guides/wiki/Internet-Permissions

**Comment by rborn** [comment]
closing,  no issue template
