### ISSUE TITLE
Location timestamp is missing in onUserLocationChange

### ISSUE THREAD

**Issue by sytolk** [react-community/react-native-maps#2203]
https://github.com/react-community/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L188
can you add:
```
coordinate.putDouble("timestamp", location.getTime());
```
https://developer.android.com/reference/android/location/Location.html#getTime()

I needs to have timestamp to check if this is location is not expired. I suppose that on Android initial location is received from mFusedLocationClient.getLastLocation()

**Comment by rborn** [comment]
@sytolk mind a PR?
