### ISSUE TITLE
Zooming on map is showing different position of Marker and Polyline

### ISSUE THREAD

**Issue by ravirupareliya** [react-community/react-native-maps#2205]
I have implement react-native-maps with Marker and Polylines. Actualy i want to show specific region with some center point on it. So i have just created polyline by attaching those points and then a center marker in it. But when i zoom out the map, it is showing different position for both Map and Polyline. Take a look at GIF.

![giphy](https://user-images.githubusercontent.com/17959204/38916500-3d5083a8-4305-11e8-8878-7836efb0c468.gif)

**Comment by rborn** [comment]
Please update your issue following the template. If you don't do it in a timely manner I'll close the issue.
