### ISSUE TITLE
Could not find method implementation() for arguments [project ':react-native-maps', build_czs7godsj0vcwov8vklieva36$_run_closure2$_closure12@204d9edf] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by nahidmbstu** [react-community/react-native-maps#2211]
i have followed the installation rules. it is showing me this error in this file.

android/app/build.gradle...

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-base:10.0.1'
    implementation 'com.google.android.gms:play-services-maps:10.0.1'
}

i have seen this issue
https://github.com/react-community/react-native-maps/issues/2152

and updated my node module file 

dependencies {
  def googlePlayServicesVersion = rootProject.hasProperty('googlePlayServicesVersion')  ? rootProject.googlePlayServicesVersion : DEFAULT_GOOGLE_PLAY_SERVICES_VERSION
  def androidMapsUtilsVersion   = rootProject.hasProperty('androidMapsUtilsVersion')    ? rootProject.androidMapsUtilsVersion   : DEFAULT_ANDROID_MAPS_UTILS_VERSION

 provided "com.facebook.react:react-native:+"
  compile "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
  compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
  compile "com.google.maps.android:android-maps-utils:$androidMapsUtilsVersion"
}

but still showing me the same error.

**Comment by moseslucas** [comment]
I’ve encountered that same issue. The latest version will break your app because it’s only compatible with gradle 3. I made a tutorial how to solve this issue herehttps://itnext.io/install-react-native-maps-with-gradle-3-on-android-44f91a70a395

**Comment by rborn** [comment]
Closing, missing template and solution offered in comments.

**Comment by rishiankush** [comment]
this article solved my problem: https://medium.com/bam-tech/boost-compilation-time-of-your-react-native-or-android-app-with-the-latest-build-tools-a3d5d398ed33

**Comment by deehuey** [comment]
Why wouldn't this be part of the set-up instructions? I'm trying to install the latest version of react-native-maps in the latest version of react-native, and this issue seems it would happen by default.

**Comment by moseslucas** [comment]
Maybe because airbnb is now moving from react native to native and doesn’t have time to update `react-native-maps`

**Comment by rborn** [comment]
This is a community project now, so PRs are welcomed for the documentation

**Comment by KirankumarDafda** [comment]
Is there any proper solution for this yet ?

**Comment by MonAiss** [comment]
i also have this problem when i install react-native-maps, i get this error:
`could not find method implementation() for arguments [{group=com.google.android.gms, module:=play-services-base}] on project ':react-native-maps' of type org.gradle.api.Project
`
any ideas how to solve this !?

**Comment by andrewhartwig** [comment]
@MonAiss Is your project still using `compile()` instead of `implementation()` in `android/app/build.gradle` ?

```gradle

dependencies {
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-location')
    implementation project(':react-native-device-info')
    implementation project(':react-native-camera')
    implementation project(':react-native-video')
    implementation project(':react-native-image-crop-picker')
...
```

**Comment by andrewhartwig** [comment]
@MonAiss if yours looks like `compile project....` then you might need to change it, but that also means you're on an old version which may not work with what you're  doing. Worth a shot though.

**Comment by MonAiss** [comment]
> @MonAiss if yours looks like `compile project....` then you might need to change it, but that also means you're on an old version which may not work with what you're doing. Worth a shot though.

no it's `implementation()`

**Comment by MonAiss** [comment]
@andrewharting please if you could share any other ideas, i need to fix this now.

**Comment by DimoNline** [comment]
> Make sure your project is using Gradle 3.
> 
> I had this same issue and this fixed it. In your root build.gradle file-
> 
> ```
> buildscript {
>     repositories {
>         jcenter()
>         google()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.0.1'  
>     }
> }
> ```
> 
> see here for more #2096

ERROR: Gradle DSL method not found: 'classpath()'

**Comment by shubhamRai12** [comment]
> Make sure your project is using Gradle 3.
> 
> I had this same issue and this fixed it. In your root build.gradle file-
> 
> ```
> buildscript {
>     repositories {
>         jcenter()
>         google()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.0.1'  
>     }
> }
> ```
> 
> see here for more #2096

but i am using 4.0.1 version of gradle

**Comment by Chris-the-Intern** [comment]
> > Make sure your project is using Gradle 3.
> > I had this same issue and this fixed it. In your root build.gradle file-
> > ```
> > buildscript {
> >     repositories {
> >         jcenter()
> >         google()
> >     }
> >     dependencies {
> >         classpath 'com.android.tools.build:gradle:3.0.1'  
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > see here for more #2096
> 
> but i am using 4.0.1 version of gradle still it is not working

Same here, any alternative solution?

**Comment by rayyan808** [comment]
Couldn't find a similar issue anywhere else, maybe it's not a react issue. I'm facing a similar issue in Android Studio attempting to import `androidx.appcompat:appcompat:1.3.0` using `Kotlin 1.5.20` & `Gradle `4.2.1`
