### ISSUE TITLE
Clicking on marker on maps should display a toast message and then redirect to google maps

### ISSUE THREAD

**Issue by DurgaManickam** [react-community/react-native-maps#2212]
Clicking on the marker on the map should display a Toast message and then, it should redirect to google maps(two actions on onPress). 

  <MapView
          ref={map => this.map = map}
          style={[styles.map, this.props.mapStyle]}
          region={region}
          loadingEnabled={true}>
          {markers.map(marker => (
            <MapView.Marker
              coordinate={marker.latlng}
              key={marker.title}
              title={marker.title}
              image={marker.image}
             **onPress={() => Linking.openURL("google.navigation:q=" + marker.latlng.latitude + "," + marker.latlng.longitude)}**>
            </MapView.Marker>
          ))}
        </MapView>

Please help me in displaying a toast message when clicked on the marker before opening the google maps

**Comment by rborn** [comment]
Closing for missing issue template
