### ISSUE TITLE
MapView not being displayed/instantiated

### ISSUE THREAD

**Issue by danielteles** [react-community/react-native-maps#2216]
### Is this a bug report?

I'm not sure, but I guess it's not

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.55.1
    react: 16.3.1
	react-native-maps: 0.21.0

### Steps to Reproduce

The app has to display a MapView to inform the user he's current location. Instantiate a MapView with some base coordinates and that's I've done to get this problem.

### Expected Behavior

I expected to see a MapView on my screen

### Actual Behavior

There is no MapView on screen
![img_1811](https://user-images.githubusercontent.com/5444753/39266783-62258fec-48a1-11e8-8faa-e7f51f7541e3.JPG)
I should see a Map where the screen is gray.

**Comment by jackcbrown89** [comment]
Same issue
`"react-native": "0.55.3"`
`"react": "16.3.1"`
`"react-native-maps": "^0.21.0"`

Please share the code where you render your `<MapView />`

**Comment by jackcbrown89** [comment]
Just fixed mine now by using this style:
```
map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
```

**Comment by danielteles** [comment]
@jackcbrown89 this solved the problem here too, thanks a lot man

**Comment by rborn** [comment]
closing, fixed
@danielgindi please close the issue once you find a solution.

**Comment by Shubham1993** [comment]
I am getting the issue with react native 0.55.3 
"Native component for 'AIRMap' does not exist". Did anyone get this issue?

**Comment by danielgindi** [comment]
@rborn you mean @danielteles :-)

**Comment by rborn** [comment]
@danielgindi omg, I'm so sorry 🤗
