### ISSUE TITLE
Problem with same size of circle while zooming in/out

### ISSUE THREAD

**Issue by DanielWalendzewicz** [react-community/react-native-maps#2220]
I'm trying to get same size of my circle while zooming in/out. I was trying to do that with settings "scale" but it also doesnt work. How can i do that? Could someone show me how can do that, maybe with any example ?

               <MapView.Circle
                    key = { (this.state.longitude + this.state.latitude).toString() }
                    center = {{latitude: this.state.latitude,
                        longitude: this.state.longitude} }
                    radius = { 100 }
                    strokeWidth = { 1 }
                    strokeColor = { '#1a66ff' }
                    fillColor = { '#1a66ff' }

                />
Best regards

**Comment by rborn** [comment]
@DanielWalendzewicz please update the issue respecting the  template. If you don't do it in a timely manner I'll close the issue

**Comment by rborn** [comment]
No reply, closing

**Comment by lfkwtz** [comment]
There may be a better way, but this is how I handled adjusting the circle size based on zoom level:

```js
    onRegionChangeComplete({ longitudeDelta, latitudeDelta }) {
        this.setState({
            radius: _.round(((longitudeDelta + latitudeDelta) / 2) * 3000),
        });
    }
```
