### ISSUE TITLE
Realtime map and traffic on react native map

### ISSUE THREAD

**Issue by Manoj002** [react-community/react-native-maps#2233]
Hello,

im trying to build a interactive and info providing map, so i need to show thing like various possible routes to a single destination,  even predict the traffic in way, if present.

im aware about the react-native-maps-direction but it shows only 1 best solution, how about if i wanna all possible routes to the same destination and provide the user even the details of each route like how much distance, time, traffic... like uper app do...?

Any help will be appreciated guyss...

**Comment by rborn** [comment]
No template, closing
