### ISSUE TITLE
peer dep missing: react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0

### ISSUE THREAD

**Issue by Buwaneka1993** [react-community/react-native-maps#2234]
peer dep missing: react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0

React-native version -     "react-native": "^0.55.3",

**Comment by rborn** [comment]
No issue template, closing

**Comment by michalladon** [comment]
Why is their no issues or why does the command prompt throw out an issue here? I run into the same problem @rborn
