### ISSUE TITLE
GoogleMaps/GoogleMaps.h file not found

### ISSUE THREAD

**Issue by navneetsharma1988** [react-community/react-native-maps#2236]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Steps to Reproduce

Manually install react native maps using Xcode and then execute npm run ios

### Expected Behavior

Build should be passed. I changed the react native maps version to 0.17.1 and it worked.

### Actual Behavior

iOS build failed and the error is GoogleMaps.h file doesn't exist
![screen shot 2018-05-04 at 3 01 53 pm](https://user-images.githubusercontent.com/5161329/39621520-abcc5d3a-4fac-11e8-9569-633125eef90d.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rafaellincoln** [comment]
Duplicate #2159

**Comment by RohitRajpal** [comment]
Upgrading to latest react-native-maps(0.23.0) resolved my problem 

npm i react-native-maps@0.23.0
react-native link
