### ISSUE TITLE
 blank black page on rendering

### ISSUE THREAD

**Issue by obiwankenoobi** [react-community/react-native-maps#2237]
the bug was reported? 

    yes  #118 #176

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

    yes

### Environment

    react-native: 0.55.3
    react: 16.3.1

### Steps to Reproduce

1. installing react-native-maps using [this](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md) tutorial.
2. creating component for the map: 
```
import React, { Component } from 'react';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'


class Map extends Component {
    constructor(props) {
        super(props);
        this.state = {  };
    }
    render() {       
        return (
                <MapView 
                provider={PROVIDER_GOOGLE}
                initialRegion={{
                    latitude: 37.78825,
                    longitude: -122.4324,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
                }}
            />
        );
    }
}


const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});


export default Map;

```
3.trying to render the component in a method inside my App component:
```
  renderImage() {

      return (
        <View style={styles.container}>
          <Map/>
        </View>
    )

  }
```
4. blank black page returned on my iPhone device

### Expected Behavior

expect to see the map rendered to the view

### Actual Behavior

black screen in my device
with error in the console: 
```
Failed to load optimized model at path '/var/containers/Bundle/Application/XXXXXXXXX-XXXXXXX-XXX/ProgramName.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
```

NOTE** when 
```
provider={null}
```
error is: 
```
2018-05-05 17:58:06.043030+0300 ProgramName[5406:3660428] Could not inset compass from edges 9
2018-05-05 17:58:06.043274+0300 ProgramName[5406:3660428] Could not inset scale from edge 9
2018-05-05 17:58:06.077742+0300 ProgramName[5406:3660428] Could not inset legal attribution from corner 4
```
[Here](https://github.com/obiwankenoobi/React-Map-Bug) is the repo of the program with the bug recreated. (with  ```provider={null}``` so no need for google api to clone and run)

**Comment by obiwankenoobi** [comment]
for real? not even one answer?

**Comment by rborn** [comment]
@obiwankenoobi you posted a duplicate issue **in a weekend**.  You realise everybody participating in the project does this in his/hers free time, right? Nobody owes you anything 😔

This is an api key problem, you either used a wrong key or your map api is not well configured in the google console.

Closing as duplicate to #118 #176

**Comment by obiwankenoobi** [comment]
sorry man! didnt meant to offend no one I really appreciate this community and thankful for it! (clearly I forgot its weekend in in US as it isnt where I am.) thanks anyway for the hint even though I tried it without google API but with the native ios map and it wasnt working as well. anyway, sorry and thank you.! (:

**Comment by slorber** [comment]
@obiwankenoobi did you find a solution? I have the same error on my iOS app and pretty sure my api keys are correctly setup.

**Comment by slorber** [comment]
@rborn are you sure it's related to the api keys?

I actually get a grey map with the markers and polylines on top of it. I'm pretty sure my api keys are correctly setup (I've done this before correctly).

Also there's an existing issue with the same error message on `google-maps-ios-utils` which is a dependency of this project:

https://github.com/googlemaps/google-maps-ios-utils/issues/180

**Comment by rborn** [comment]
@slorber for me every time the map was working but no tiles were loaded it was an api key issue.
You might have to do some stuff on the google console to whitelist the app or try to allow anything for a start

**Comment by slorber** [comment]
@rborn you are right it was an API key issue. Actually I didn't change anything. I'm pretty sure the newly created keys or restriction updates are not immediately applied by google, leading to developers being annoyed...

I still have the errors above on XCode but now my map tiles are displayed. It was not the case 10 minutes ago and I can promise there is no git diff at all.

**Comment by slorber** [comment]
Not sure exactly why (unsure) but I think moving this at the top of AppDelegate method does help:

`[GMSServices provideAPIKey:@"xxxx"];`

I put it as last statement, under Expo/RN stuff, and it does not seem to help maps to be displayed. Will not investigate further as my problem is solved but just reporting what my intuition is.

**Comment by rborn** [comment]
well, docs say this: https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#if-you-want-to-use-google-maps -  the api key is set the first think in `didFinishLaunchingWithOptions`

**Comment by slorber** [comment]
that's true ;) maybe it should be highlighted

**Comment by rborn** [comment]
@slorber fancy a PR ? 🤗

**Comment by slorber** [comment]
sure

**Comment by BravenxX** [comment]
I had the same problem. But I solved doing this: [comment](https://github.com/react-native-community/react-native-maps/issues/2766#issuecomment-484778579)

And enabling all maps services.
