### ISSUE TITLE
On iOS+Google Maps, onPoiClick doesn't work.

### ISSUE THREAD

**Issue by sargunv** [react-community/react-native-maps#2240]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-navigation": "1.5.11"

That version of expo comes with react-native-maps 0.21.0

Platform: Google Maps on iOS

### Steps to Reproduce

Create a MapView (Google Maps) with an `onPoiClick` property and run it on Android and iOS.

### Expected Behavior

On both Android and iOS, the event should fire when tapping a POI like a restaurant, etc.

### Actual Behavior

The event fires fine on Android, but doesn't on iOS. The docs state it's Google Maps only, but don't say it's Android only.

### Reproducible Demo

https://snack.expo.io/B1KBGrp6G

```jsx
<MapView
  style={{ flex: 1 }}
  provider={MapView.PROVIDER_GOOGLE}
  initialRegion={{
    latitude: 47.6062,
    longitude: -122.3321,
    latitudeDelta: 0.0922,
    longitudeDelta: 0.0421,
  }}
  onPress={() => Alert.alert('onPress')}
  onLongPress={() => Alert.alert('longPress')}
  onPoiClick={() => Alert.alert('onPoiClick')}
/>
```

**Comment by MorganDream** [comment]
Same problem.

**Comment by eduardovillasenor** [comment]
I'm seeing the same issue as sargunv.  

The map provider is Google and everything loads fine, simply that the onPoiClick handler doesn't fire when a poi is clicked on iOS (phone or simulator), while it does on the Android simulator.
![image](https://user-images.githubusercontent.com/10862655/39881833-ee00ecfa-5436-11e8-8cb5-616e042f565f.png)

**Comment by janajri** [comment]
I've had some similar issues with the onMarkerSelect method. Setting provider to "google". Things seem to work when I change this ```onPoiClick={(a) => console.log(a)}``` to ```				onPoiClick={({ nativeEvent }: any) => console.log(nativeEvent)}
```

**Comment by vuthanhtrung0504** [comment]
same issue in my case too

**Comment by mlop113** [comment]
Why this issue is closed, Are there any solution ?
