### ISSUE TITLE
Tile sizes for UrlTile on High DPI iOS devices

### ISSUE THREAD

**Issue by funkyfourier** [react-community/react-native-maps#2242]
### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

Any react-native, react-native maps version on iOS running on a high dpi "retina" device.

### Steps to Reproduce

1. Use UrlTile with standard 256x256 OSM tiles on any map.

2. Test on any iOS device with `PixelRatio.get()` higher than 1.

### Expected Behavior

I would expect the same thing that happens on Android, that the tiles are stretched in accordance to the device pixel ratio. If they are not, they end up being displayed very small, so that the text on the tiles (street names, etc) are unreadable.

### Actual Behavior

The tiles are displayed 1:1 pixel sized on iOS, making street names and other text on the tiles very hard to read.

On Android the tiles are scaled, as IMHO they should be:

![map-android](https://user-images.githubusercontent.com/272493/39693293-d409f5c6-51e3-11e8-86fb-5f260ce681f4.png)

On iOS the tiles are displayed 1:1, which makes text very hard to read. Here in the simulator for the iPhone X:

<img width="356" alt="map-iphonex" src="https://user-images.githubusercontent.com/272493/39693164-6586e7d0-51e3-11e8-9643-2871f9620839.png">

### Reproducible Demo

https://snack.expo.io/@jmr/urltile-ios-tile-size

**Comment by rborn** [comment]
@funkyfourier did you try to provide @2x and @3x assets?

**Comment by funkyfourier** [comment]
@rborn For different reasons it would be best for us to avoid using high resolution tiles, file size being the most important one. Also I think in any case it should behave the same on iOS and Android.

**Comment by rborn** [comment]
Can you at least try to see if it works with the correct assets ?

**Comment by funkyfourier** [comment]
@rborn  I tried using a tile provider which serves 512x512 tiles on an iPhone 6 (simulator) and a physical iPhone 5S which both have a device pixel ratio of 2. These should be the corresponding tiles if the map engine displays the tiles 1:1 per pixel.

Weirdly, the maps are still too small. It seems like they are in fact truncated. I have verified that the tiles are indeed 512x512. Unfortunately I can't hand out the url template for the 512x512 tiles, since it contains an API key.

In case someone has an API key for HERE maps the url is something like:

https://2.base.maps.api.here.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/512/jpg?app_id=[APP_ID]&app_code=[APP_CODE]&lg=eng

Here is a screenshot of it from the iPhone 6 simulator using the 512x512 tiles. For sure there is something wrong about the scaling?

![simulator screen shot - iphone 6 - 2018-05-07 at 14 38 09](https://user-images.githubusercontent.com/272493/39702669-e0eecf1a-5205-11e8-9762-a8dc3446c2e0.png)

**Comment by funkyfourier** [comment]
Just a quick update: Setting `_tileLayer.tileSize = 512` in AIRGoogleMapUrlTile.m setUrlTemplate function, while using 256 sized tiles, seems to fix the problem on iOS devices with pixel ratio 2. I will investigate more and report back tomorrow.

**Comment by funkyfourier** [comment]
Ok, so I have researched this a bit more:

On an iPhone X, which has pixel ratio of 3, the tiles will be shown very tiny by default. If I set _tileLayer.tileSize to 512, they are stretched and rendered twice as big. If I set _tileLayer.tileSize to 768, or any number more than that, they are stretched and rendered three times as big, and at the physical size I would expect with 256px tiles on a 160dpi'ish screen.

On iPhones with pixel ratio 2, like the 5S and the 6, it renders the tiles tiny by default. If i set _tileLayer.tileSize to 512 they are stretched and rendered twice as big. If I set _tileLayer.tileSize to anything more than 512 they are also stretched and rendered twice as big.

So in other words, if I set _tileLayer.tileSize to equal or more than 256 times pixel ratio, they are rendered in a manner which makes them roughly the same size as on a 160dpi'ish screen. This is the same behaviour as on Android. If I use 512px tiles in that configuration they are rendered at the same physical size but crisper.

So, to achieve the same behaviour as on Android there are two alternatives:

1) Set _tileLayer.tileSize to some arbitrary high number.
2) Expose the parameter to Javascript and let users set it. 

I am unsure on wether or not that setting would mean the same on Android or iOS.

I can attempt to make a pull request on one of these approaches. What do you think would be the best one?

Also, see documentation from Google regarding this:

https://developers.google.com/maps/documentation/ios-sdk/tiles#high_dpi_tiles_for_retina_devices

https://developers.google.com/maps/documentation/android-sdk/tileoverlay#coordinates

**Comment by funkyfourier** [comment]
Another update: I implemented a `tileSize` property for UrlTile (Google Maps) in my fork:

https://github.com/funkyfourier/react-native-maps

So if one sets `tileSize={256 * PixelRatio.get()}` the tiles will be stretched so they are physically as big as they would be on a 160dpi screen. This is regardless of the size of the tiles themselves, so if you use 512px tiles on a device with pixel ratio of 2 they will be displayed 1:1, and if you use 256px tiles on a device with pixel ratio of 2 they will be stretched 1:2.

Now for Android, it is written in the documentation:

_Google Maps targets 256 dp (device-independent pixels) when displaying tiles._

So whatever tiles you give it on Android, they will be stretched/shrinked to fit 256 times the device pixel ratio. That is exactly what happens on iOS if one uses the `tileSize={256 * PixelRatio.get()}` property which I implemented.

So to me it seems sensible to _not_ have this property, since it would only apply to iOS, and since there does not seem to be an equivalent property on Android. The solution as I see it, is to set `_tileLayer.tileSize` in AIRGoogleMapUrlTile.m to 256 times device pixel ratio. Then it will behave the same way on both platforms, and users would be able to read the text on the tiles in all cases.

Does that sound good? In that case I can put up a PR on friday.

**Comment by funkyfourier** [comment]
@rborn Yes, that is what I am suggesting. In that case it will display any tile, wether it be 256px, 512px, or more, at 256 density independant pixels (256 * device pixel ratio). The physical size will then be the same on any device.

Will put up the PR on friday when I am back at work.

**Comment by rborn** [comment]
Merged #2248
