### ISSUE TITLE
Showing "Invariant violation:native component for "AirMap" does not exist"

### ISSUE THREAD

**Issue by aneena-thomas** [react-community/react-native-maps#2247]
Installed react-native maps by running "npm install react-native-maps --save"
and linked the react-native-maps
But showing the below error

![simulator screen shot - iphone 6 - 2018-05-11 at 14 48 14](https://user-images.githubusercontent.com/13118654/39917292-b3d6b0c4-552a-11e8-8318-c416dc56b4f0.png)

**Comment by JorgeLoaiza12** [comment]
Same problem! 👍

**Comment by rborn** [comment]
Duplicate of many other issues, also no template. Closing

**Comment by aneena-thomas** [comment]
@rborn  tried all solutions but still its shows "Invariant violation:native component for "AirMap" does not exist"

**Comment by gabrielbuzziv** [comment]
@rborn duplicated of may other issues that you guys didnt solved

**Comment by Yaweii** [comment]
@gabrielbuzziv agree!
