### ISSUE TITLE
'Google play services are updating' error

### ISSUE THREAD

**Issue by louisallain** [react-community/react-native-maps#2258]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.55.3
    react: 16.3.2
    react-native-maps: 0.21.0
 
     Android: 7.0

### Expected Behavior

A Google Map view should appear.

### Actual Behavior

Instead of the map the message 'Google play services are updating' is printed.

![screenshot_20180515-110758 1](https://user-images.githubusercontent.com/32368870/40068805-d8820352-583f-11e8-8e68-6db6dca24363.png)

###

**Comment by rborn** [comment]
https://stackoverflow.com/a/50327544/8018651

**Comment by louisallain** [comment]
Thank you!
