### ISSUE TITLE
doesn't work with react-native@0.55

### ISSUE THREAD

**Issue by rss81** [react-community/react-native-maps#2259]
doesn't work with react-native@0.55

    npm ERR! peer dep missing: react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0

**Comment by rborn** [comment]
no issue template

**Comment by bedakb** [comment]
@rborn maybe explicitly adding `^0.55` version as peer dependency to package.json should fix the problem ? It that's case, maybe I could create pull request.

**Comment by rss81** [comment]
adding either of those to the json file does nothing

**Comment by tavriaforever** [comment]
Use `yarn add react-native-maps`
