### ISSUE TITLE
Dependency Resolution different versions for compile 10.0.2 and runtime 10.2.4

### ISSUE THREAD

**Issue by heisty** [react-community/react-native-maps#2267]
D:\Nat\ChatApp>react-native run-android
Scanning folders for symlinks in D:\Nat\ChatApp\node_modules (350ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

> Configure project :app
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-maps
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-maps' has different version for the compile (10.0.1) and runtime (10.2.4) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
3 actionable tasks: 1 executed, 2 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by sopdock** [comment]
I have this issue too, is there any resolution?

**Comment by tadeumx1** [comment]
When you run react-native link after the installation of react-native-maps this line is added` compile project(':react-native-maps')` in dependencies in `android/app/build.gradle` only remove this line and react-native-maps and it is going to work again

**Comment by subooom** [comment]
I removed `compile project(':react-native-maps')` but now I'm getting 'Native module AirMapModule tried to override AirMapModule for module name AirMapModule'

**Comment by Shhzdmrz** [comment]
It worked. Thanks @tadeumx1  and @Stalder but my question is how this solution is even working?

**Comment by Burgeon8interactive** [comment]
@Shhzdmrz getting the same error.. Did you get to solve it?

**Comment by muhlishp33** [comment]
> I removed `compile project(':react-native-maps')` but now I'm getting 'Native module AirMapModule tried to override AirMapModule for module name AirMapModule'

It looks like the RealmReactPackage was somehow included twice. Can you check that it only appears once in the getPackages() method inside MainActivity.java?

**Comment by MaxZubko** [comment]
**Help fix the error**

![image](https://user-images.githubusercontent.com/45923184/52646576-aca1fc00-2eeb-11e9-9f55-ec55e8129f00.png)
