### ISSUE TITLE
Android: onDeselect / onSelect are not triggered

### ISSUE THREAD

**Issue by mvaivre** [react-community/react-native-maps#227]
It seems that the Marker's event callbacks `onDeselect`, `onSelect` and the equivalent on MapView `onMarkerSelect`, `onMarkerDeselect` are never triggered.

Version: 0.4.0

**Comment by mvaivre** [comment]
Kind of duplicates https://github.com/lelandrichardson/react-native-maps/issues/114

**Comment by DennisMG** [comment]
This is because they are not implemented on android.

**Comment by mvaivre** [comment]
@DennisMG : yep, that's why I referenced #114. But it would be a more-than-useful feature :).
In the meantime, we could try to specify more clearly in the doc what's available for Android and what is not!

**Comment by KGALLET** [comment]
+1

**Comment by magrinj** [comment]
@KGALLET Any news on this ? :)

**Comment by KGALLET** [comment]
@magrinj Sorry, but i'm not working on react native project anymore for the moment..

**Comment by magrinj** [comment]
@KGALLET Ok no problem, thanks!

**Comment by alvelig** [comment]
Duplicate of 114
