### ISSUE TITLE
'GoogleMaps/GoogleMaps.h' file not found in AIRGoogleMapPolygon.h

### ISSUE THREAD

**Issue by himaanshi** [react-community/react-native-maps#2270]
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(YES)

### Environment

"react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-maps": "^0.21.0"
	
When i am running app from  xCode error  'GoogleMaps/GoogleMaps.h' file not found is showing.
Full path : GoogleMapProject/node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapPolygon.h

**Comment by damathryx** [comment]
getting the same problem after updating to 0.21

**Comment by Webdev55486** [comment]
same here.
"react": "16.3.1",
"react-native": "0.55.4",

**Comment by dreallday** [comment]
same here.

```
"react": "^16.3.2",
"react-native": "^0.55.3",
"react-native-maps": "^0.21.0",
```

**Comment by JoseVf** [comment]
Same here, but I don't want to use GoogleMaps...

`"react": "16.3.1",
"react-native": "0.55.4",
"react-native-maps": "^0.21.0",`

**Comment by dreallday** [comment]
Are you guys using Cocoapods? or manual install?

**Comment by Webdev55486** [comment]
I am using pod

**Comment by Webdev55486** [comment]
by the way how can you install manually ?

**Comment by Webdev55486** [comment]
@dreallday

**Comment by dreallday** [comment]
@Webdev55486 Let me test it with Pods.

Installing it manually is very, very painful. You have to follow the instructions on google maps sdk for ios. I wouldn't do it again.

**Comment by Webdev55486** [comment]
thanks @dreallday .
then in my side that working well with simulator and xcode.
but after build the ipa and uploaded to the diawi.
when install that to my device , App crashed.

**Comment by himaanshi** [comment]
@dreallday  i am using cocoapods i have installed  it with command "sudo  gem install cocoapods" .

**Comment by mikemorris** [comment]
I'm using _without_ CocoaPods and started seeing this build error when upgrading from
```
"react": "^16.2.0",
"react-native": "^0.53.0",
"react-native-maps": "^0.20.1",
```
to
```
"react": "^16.3.1",
"react-native": "^0.55.4",
"react-native-maps": "^0.21.0",
```

Cloned down this repo, used `npm link` into my project with
```
git bisect start
git bisect good 106f0ca5774ec3dc1107c70458343a1dcd9c5989 (v0.20.1)
git bisect bad c53ff0ad2632a049b6e6a25b7b304005e4f9791e (v0.21.0)
```
Cleaning and building in Xcode on each commit, it landed on d22f96f9115f10b50085206463143c421f8d948d as the first bad commit, at a quick glance I'd guess this may be related to adding all the AirGoogleMap files to `lib/ios/AirMaps.xcodeproj/project.pbxproj`.

**Comment by zolar** [comment]
Changed the Deploy Target to 9.0 and did a `pod install` and all is well.

**Comment by M47h13u** [comment]
I have the same problem with:
```
"react": "16.0.0-alpha.6",
"react-native": "0.43.3",
"react-native-maps": "^0.21.0",
```

**Comment by mikemorris** [comment]
Please check out my proposed fix in #2310 and give feedback if it fixes this issue for y'all!

**Comment by tunm1228** [comment]
$(SRCROOT)/../node_modules/react-native-maps/lib/ios/AirMaps

**Comment by mikemorris** [comment]
Fix for this was merged in https://github.com/react-community/react-native-maps/pull/2396 and released in

**Comment by Kottidev** [comment]
![image](https://user-images.githubusercontent.com/12915009/46729562-98b86600-cc7d-11e8-86b8-fde3aabd7d22.png)

@rborn  Please let me know how to fix this issue !

**Comment by rborn** [comment]
@Kottidev use the git version

**Comment by Kottidev** [comment]
![image](https://user-images.githubusercontent.com/12915009/46729706-0b294600-cc7e-11e8-87bc-b40b572e3f7b.png)
@rborn

**Comment by rborn** [comment]
I have this:
`"react-native-maps": "https://github.com/react-community/react-native-maps.git",`

clean your `node_modules`, `npm install` and try again, if it's still not working make a backup and try `react-native link react-native-maps`

**Comment by nolan12345** [comment]
Add pod 'GoogleMaps', '~> 2.7.0' and then pod install solves the problem

**Comment by g33ktony** [comment]
In Podfile:
    GoogleMaps (~> 2.7.0)

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.22.1, which depends on
      Google-Maps-iOS-Utils (= 2.1.0) was resolved to 2.1.0, which depends on
        GoogleMaps

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.22.1, which depends on
      GoogleMaps (= 2.5.0)

**Comment by RohitRajpal** [comment]
Upgrading to latest react-native-maps(0.23.0) resolved my problem

npm i react-native-maps@0.23.0
react-native link

**Comment by shakogele** [comment]
```
npm i react-native-maps@0.23.0
react-native link
```
 this was the solution for me. I am not using cocoa-pods just followed the [manual installation](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md)
and [this](https://developers.google.com/maps/documentation/ios-sdk/start) .
