### ISSUE TITLE
Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.interna l.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by yzonglun** [react-community/react-native-maps#2275]
C:\APP\chaowei>react-native run-android
Scanning folders for symlinks in C:\APP\chaowei\node_modules (37ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\APP\chaowei\node_modules\react-native-camera\android\build.gradle' line: 56

* What went wrong:
A problem occurred evaluating project ':react-native-camera'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.interna
l.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by yzonglun** [comment]
![1](https://user-images.githubusercontent.com/19408097/40313789-2993d3d4-5d49-11e8-8e12-eaabf9cca628.jpg)

**Comment by himaanshi** [comment]
Replace "compileOnly" with "provided" in  node_modules\react-native-camera\android\build.gradle'.

**Comment by kholiavko-roman** [comment]
Hi guys. But maybe anybody know better solution ? I cant update gradle in my project, because I have a lot of dependencies, but every time change `"compileOnly" with "provided"` when I install my modules this is not good.
