### ISSUE TITLE
Custom marker size Android

### ISSUE THREAD

**Issue by Thetortuga** [react-community/react-native-maps#228]
Hello,

Is there a way to change the size of a custom marker ?
I explain : I have a custom marker, here a simple red box of 64px :
![screenshot_2016-05-13-16-04-34 1](https://cloud.githubusercontent.com/assets/11147922/15250300/6ba651e0-1924-11e6-896e-c14ed9bdc31b.jpg)

The callout appears to be centered on a 32x32 inside marker. There is the same problem with the anchor.

Here is my code :

```
render() {
        return (
            <View style={styles.container}>
            </View>
        )
    };
...
container: {
        flex: 1,
        height: 64,
        width: 64,
        backgroundColor: 'red',
    }
})
```

If I add "position: 'absolute'" to my style, the size is totally ignored and appear to be 32, but the center is good.

I work on an actual device, an Asus Zenfone 2 ZE551ML, 1080x1920px , 400dpi.

**Comment by alvelig** [comment]
As described in #230 PR #258 fixes this
