### ISSUE TITLE
App crash on IOS after switching between screens which contains mapView for several times

### ISSUE THREAD

**Issue by temraz** [react-community/react-native-maps#2281]
I am using react-native v~0.55.2 and react-native-maps v^0.21.0,
I noticed the memory usage exceeded 1GB !! after switching between screens which contain mapView for more than 7 times on a real device Iphone 7 plus !!
this is serious issue here I stoped developing on my app and started digging for a solution but I couldn't found out any solution, please I need your help..

**Comment by koswarabilly** [comment]
it happens in android too
