### ISSUE TITLE
initialRegion should be my location 

### ISSUE THREAD

**Issue by adhavalboy** [react-community/react-native-maps#2298]
My code is as below 
    
      import React, { Component } from "react";
      import { AppRegistry, StyleSheet, Dimensions, Image, View, StatusBar, TouchableOpacity } from "react-native";
      import { Container, Text } from "native-base";
      
      import MapView from 'react-native-maps';
      import Polyline from '@mapbox/polyline';
      import { StackNavigator } from 'react-navigation';

        const util=require('util');
      
      class LocationA extends Component {
        static navigationOptions ={
          title:'Map',
        };
        constructor(props) {
          super(props);
      
          this.state = {
            latitude: null,
            longitude: null,
            error: null,
            concat: null,
            latitudeDelta: null,
            longitudeDelta: null,
            coords:[],
            
          };
      
        }
      
        componentDidMount() {
          navigator.geolocation.getCurrentPosition(
             (position) => {
               this.setState({
                 latitude: position.coords.latitude,
                 longitude: position.coords.longitude,
                 error: null,
               });
        
             },
             (error) => this.setState({ error: error.message }),
             { enableHighAccuracy: false, timeout: 200000, maximumAge: 1000 },
           );
      
         }
      
 
        render() {
       
          return (
          
            <MapView style={styles.map} initialRegion={{
            latitude:20.5937,
            longitude:78.9629,
            latitudeDelta: 0.00522,
              longitudeDelta:Dimensions.get("window").width / Dimensions.get("window").height * 0.00522
            }}>
      
            {!!this.state.latitude && !!this.state.longitude && <MapView.Marker
               coordinate={{"latitude":this.state.latitude,"longitude":this.state.longitude}}
               title={"Your Location"}
             />}
      
            </MapView>
          );
        }
      }
      
      const styles = StyleSheet.create({
        map: {
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        },
      });
      
      export default LocationA;`

`
i want intial region as my current location.

**Comment by rborn** [comment]
@adhavalboy update your issue to follow the template or I'll close it.

**Comment by adhavalboy** [comment]
k

**Comment by kkureli** [comment]
hi, can u solve?

**Comment by jackimatin** [comment]
hi
any solution
?
