### ISSUE TITLE
[BUG] [Android] native component for AIRMap does not exist

### ISSUE THREAD

**Issue by diablourbano** [react-community/react-native-maps#2301]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
The whole document at least 10 times, plus all reported issues here and in stackoverflow and several posts I've found.

### Environment
react-native: 0.55.3
react: 16.3.1
react-native-navigation: 1.1.452
react-native-maps: 0.21.0

```
*I also tried it with:*
react-native: 0.54.4
react: 16.3.2
but I got to the same error
```

_note:_ The project has graddle updated as several gh issues and post have stated, which is the expected route considering react-native-maps uses `implementation` instead of `compile` command which is part of graddle 3.

### Steps to Reproduce

(Write your steps here:)
0. check README for requirements, anyway, the important thing is to have node v 8.11.1

1. open an android emulator (I've tried with several including Nexus 5 with OREO OS. It's the one I'm using right now)

2. in a console execute
```
$> yarn install
$> yarn start // this will execute metro server
```

3. in a different console execute
```
$> yarn run android
```

4. Wait and watch it explode :(

### Expected Behavior
The map should render properly.
*_note:_ in iOS this project runs smoothly, so please this ticket is to focus on android error*

### Actual Behavior
What I'm getting right now is a big red screen on the android simulator and on the device saying.

```
Native component for "AIRMap" does not exist
```

The demo app I'm linking has changed the navigation route setting the map screen (currently called dashboard) as the root.

![image](https://user-images.githubusercontent.com/316812/40890763-83d408ac-6751-11e8-970d-eb045601ec14.png)

### Reproducible Demo
The instructions are the ones describe above.

[Github repo rn-maps-error](https://github.com/diablourbano/rn-maps-error)

*Note: I've just left the code regarding to android, what I did was to trim everything from the original project including the ios part and the new implementations (so you won't find the linking on iOS). As said before iOS works just fine, the problem is exclusively with android and that's why you won't find in the shared code anything related to iOS. Please check `index.android.js` that's the root point of the app*

*Note 2: Please I need some help with this, I've been moving normally with iOS adding more libraries and implementing more features but I can't do anything on the android side and this side is as important as iOS side*

**Comment by diablourbano** [comment]
Can someone help me with this? please!

**Comment by cdra0624** [comment]
@diablourbano 
Hi, I forked your repo and fixed it.
I'm not sure this is correct way, but it worked in my AVD now.
Not checked iOS.

Here is my PR.
https://github.com/diablourbano/rn-maps-error/pull/1

**Comment by diablourbano** [comment]
Thanks @cdra0624 I didn't saw those details.

For those arriving here with something similar I'm copying @cdra0624 PR comment (I have to delete the repo)

------

```
I'm just trying to use react-native-maps and react-native-navigation too.

### Your problem is in `MainApplication.java`

## 1st step
```code:MainApplication.java
public class MainApplication extends NavigationApplication {
```
to
```code:MainApplication.java
import com.facebook.react.ReactApplication;
...
...
public class MainApplication extends NavigationApplication implements ReactApplication {
```

## 2nd step
```code:MainApplication.java
 @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return null;
  }
```
to
```code:MainApplication.java
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.<ReactPackage>asList(
     new MainReactPackage(),
     new MapsPackage()
   );
  }
```

### Before
![screen shot 2018-06-09 at 21 04 47](https://user-images.githubusercontent.com/7720795/41191329-c497cd3e-6c28-11e8-989c-9f0fcdf71820.png)

### After
![screen shot 2018-06-09 at 21 02 38](https://user-images.githubusercontent.com/7720795/41191318-a7484524-6c28-11e8-87f4-f3c4cd2ce18a.png)

### I can not understand why this code worked, and I think this is not correct way, but just worked for me. I'm, now learning `react-native-navigation` .
```
