### ISSUE TITLE
Permissions on Android are weird (more info inside)

### ISSUE THREAD

**Issue by iremlopsum** [react-community/react-native-maps#2303]
Hey,

Let me first describe the issue at hand. Before rendering the map I want to ask the user for permissions for the location. Depending on that I will either show data based on the user's location or if the user does not agree to share the location I will just show a region. The product only works within a certain city, so that all good and dandy.

Now, I can't actually ask for permissions in runtime, because if I do, the answer is always `never_ask_again`. I assume it's due to the fact that `react-native-maps` has the following permissions in it's manifest file `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`. This does not allow me to specify the users needs.

Any solution to that?

### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

"react-native": "0.55.4",
"react-native-maps": "^0.21.0",

### Steps to Reproduce

run `react-native init testMapApp` and install `react-native-maps`.  Root file looks like

```
import React, { PureComponent } from 'react';
import { View, StyleSheet, PermissionsAndroid, Platform } from 'react-native';
import MapView from 'react-native-maps';

class App extends PureComponent {
  componentDidMount() {
    this._askForLocationServices();
  }
  _askForLocationServices() {
    PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, {
      'title': 'question',
      'message': 'gimme that location',
    }).then((granted) => {
      console.log('granted', granted);
      // always returns never_ask_again
    })
  }
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: 'white' }}>
        <MapView
          style={{ ...StyleSheet.absoluteFillObject }}
          provider="google"
        />
      </View>
    );
  }
}

export default App;
```

### Expected Behavior

I would expect I could ask for the permissions in the runtime from the user to be able to make a decision based on that

### Actual Behavior

Does not display a modal to ask the user for location permissions

### Reproducible Demo

Snack: https://snack.expo.io/B1svm6fgm

**Comment by fqborges** [comment]
The way permissions are handled in Android has changed on Android 6.0 (API level 23). From API level 23 and upper, permissions behaviour like you expect: you can (and should) ask for the permissions on runtime. The current behaviour (install time permissions) is API level 22 or lower.

You can solve it by changing you `targetSdkVersion` on your app `build.gradle` from 22 (crna default) to 23.

**Comment by iremlopsum** [comment]
Hey, @fqborges thanks for the help, I tried it out but I get the same result. Here's mu `build.gradle` file

```
android {
    compileSdkVersion 23
    buildToolsVersion "25.0.1"

    defaultConfig {
        applicationId "com.appName"
        minSdkVersion 16
        multiDexEnabled true
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile (project(':react-native-maps')){
        exclude group: 'com.google.android.gms'
    }
    compile ("com.google.android.gms:play-services-base:12.0.1") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-maps:12.0.1") {
        force = true;
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

Any ideas?

**Comment by fqborges** [comment]
@iremlopsum did you remove/reinstall the app? When on API 23+ it should ask on runtime, except when the permission was already granted.

**Comment by fqborges** [comment]
@iremlopsum now I see. You are asking for ACCESS_FINE_LOCATION. Did you include this permission (ACCESS_FINE_LOCATION) on your manifest?

The lib only uses permission ACCESS_COARSE_LOCATION.

**Comment by iremlopsum** [comment]
@fqborges this worked, thanks :)

**Comment by anastely** [comment]
@fqborges Hello, I'm tired of this issue, and it adds the Tow permission in the AndroidManifest.xml but it tells me please Add the Location permission!!!

**Comment by fqborges** [comment]
@anastely I didn't understand your problem or how can I help you. I recommend you to open a new issue in this repository.

**Comment by sudeeps-r** [comment]
am also facing the same issue, always getting never_ask_again error
