### ISSUE TITLE
[FEATURE REQUEST] Use the pacakge without API Key (bypass Google)

### ISSUE THREAD

**Issue by Stophface** [react-community/react-native-maps#2304]
### Is this a bug report?

No.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

    "react-native": "0.48.3",
    "react": "16.0.0-alpha.12",
    "react-native-maps": "^0.20.1",

### Steps to Reproduce

1. Set up a minimal react-native project, follow the installation instruction but skip adding a Google Maps API Key in the `android/app/src/main/AndroidManifest.xml`

```
<application>
    <meta-data
    android:name="com.google.android.geo.API_KEY"
    android:value="Your Google maps API Key Here"/>
</application>
```

2. Use this https://github.com/react-community/react-native-maps/blob/master/example/examples/CustomTilesLocal.js

or

3. this code https://github.com/react-community/react-native-maps/blob/master/example/examples/CustomTiles.js

### Expected Behavior

When I use `<LocalTile />` or `<UrlTile />` it should work without supplying a Google Maps API Key because I am not using a Google Maps WMS.

### Actual Behavior

The app crashes on start up ans asks for a Google Maps API Key. 

### Reproducible Demo

Simply remove your Google Maps API Key in any react-native Project and use this code https://github.com/react-community/react-native-maps/blob/master/example/examples/CustomTilesLocal.js instead of your `<MapView />`.

### Feature Request
I am wondering why I need an GoogleMaps API Key on Android, eventhough I am not using Google as a provider, but `<LocalTile />` or `<UrlTile />`?!

That just does not make a lot of sense to me... Why would I need a Google Maps API key when using tiles that are stored locally on the device (`<LocalTile>`)? Why would I need a Google Maps API key when I am using i.e. MapBox tiles (`<UrlTile>`)? That limits what can be done with `react-native-maps` because it puts restrictions on the App that are linked to what can be done for free/paid with the Google Maps API Key.

Can anyone explain why that is? That should not be. It would be better to leave the API Key optional and allow developers to bypass Google.

**Comment by rborn** [comment]
@Stophface would have been nice if you could respect the issue template, even if it's a question :(

**Comment by Stophface** [comment]
@rborn I added the issue template

**Comment by fqborges** [comment]
Unfortunately it is not possible using GooglePlay libs.

I am working on this on a fork, implementing a (still experimental) new provider using osmdroid (https://github.com/osmdroid/osmdroid). You can check this out on https://github.com/fqborges/react-native-maps.

Caution! It is still a work in progress, some things are not implemented and bugs are expected.

**Comment by rborn** [comment]
Going to close this, @fqborges thnx for replying

**Comment by Peretz30** [comment]
@fqborges hey! How is your fork? Did you succeed with extracting provider?

**Comment by fqborges** [comment]
@Peretz30 I am using it on production and it is working as expected. You can find more info and instructions here: https://github.com/react-community/react-native-maps/pull/2348

**Comment by Vahradrim** [comment]
Any possibility to use this with expo ?
