### ISSUE TITLE
Android sometimes crashes on production with: undefined is not an object (evaluating 'this.map.setNativeProps')

### ISSUE THREAD

**Issue by macrozone** [react-community/react-native-maps#2305]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

  Please specify the react, react-native, react-native-maps versions, eg:

    react-native: 0.55.4
    react: 16.3.1
    react-native-maps: 0.21.0

 

### Steps to Reproduce

I got this map component:

```

const Map = class extends React.Component<Props, State> {
  state = {
    animatedRegion: new AnimatedRegion({
      ...DEFAULT_REGION,
    }),
  }

  componentDidMount() {
    this.animateToRegion(this.props.region || DEFAULT_REGION)
  }

  animateToRegion(region) {
    this.state.animatedRegion
      .timing({
        duration: 1000,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
        ...region,
      })
      .start()
  }

  componentDidUpdate(oldProps) {
    const newRegion = this.props.region || DEFAULT_REGION
    if (oldProps.region !== newRegion) {
      this.animateToRegion(newRegion)
    }
  }
  onRegionChange = region => {
    this.state.animatedRegion.setValue(region)
  }

  render() {
    const {
      style,
      coordinates,
      theme,
      strokeColor,
      strokeWidth = STROKE_WIDTH,
    } = this.props
    return (
      <Container style={style}>
        <StyledMap
          onRegionChange={this.onRegionChange}
          region={this.state.animatedRegion}
        >
          {coordinates &&
            coordinates.length > 0 && (
              <Polyline
                coordinates={coordinates}
                strokeColor={strokeColor || theme.colors.primary}
                strokeWidth={strokeWidth}
              />
            )}
          {coordinates && coordinates.length > 0 ? (
            <Marker coordinate={first(coordinates)}>
              <StartPoint />
            </Marker>
          ) : null}
          {coordinates && coordinates.length > 1 ? (
            <Marker coordinate={last(coordinates)}>
              <StartPoint />
            </Marker>
          ) : null}
        </StyledMap>
      </Container>
    )
  }
}
```

### Expected Behavior

should not crash

### Actual Behavior

works on both android and ios, but sometimes i get 

`undefined is not an object (evaluating 'this.map.setNativeProps')` and the app crashes.

It looks like the `this.map` is not set, which would contain the ref, but i am not sure when this can happend and how i can guard it

**Comment by pedrolopes10** [comment]
Hi there! I was coming to report the same issue. I've an app in production and this crash happens for a small percentage of users: multiple android versions (6,7,8 and 8.1) and multiple devices (Pixel XL, Samsung's, LG's, Huwaei). If I can help with something just say. I've the same environment.

**Comment by pedrolopes10** [comment]
@macrozone did you manage to fix this?

**Comment by rborn** [comment]
What's `StyledMap` ? I think there is the problem as I don't see in your code anything related to the code it crashes on.

**Comment by macrozone** [comment]
@rborn ah sorry, that's just a styled map via styled components:

```
import { Animated } from 'react-native-maps'
import styled from 'styled-components'

// 

const StyledMap = styled(Animated)`
  flex: 1;
`

```

**Comment by macrozone** [comment]
@pedrolopes10 actually yes:

The problem may happen in 

```
 componentDidMount() {
    this.animateToRegion(this.props.region || DEFAULT_REGION)
  }
```

you can change this with:

```
 onMapReady = () => {
    this.animateToRegion(this.props.region || DEFAULT_REGION)
  }

// in render:

 <Map
          onMapReady={this.onMapReady}
     
        >
```

**Comment by rborn** [comment]
@macrozone @pedrolopes10  oh, I'm blind - yes, you can call map methods ONLY after is ready, not after it mounted as the map has to do more stuff.

**Comment by vanydeasy** [comment]
@rborn Can you point out what kind of props that should not be passed to the map before it is ready? I'm having a hard time figuring out which props I define that cause the error.

**Comment by rborn** [comment]
@vanydeasy you can pass any prop to the map before is ready, you cannot act on them though until is ready. The most sensitive are the ones that make the map change the region/zoom etc as these are not available yet.

**Comment by khanh21011999** [comment]
Guyssss, i'm still having problem, anyone still active on that issue 🥲
