### ISSUE TITLE
Update Installation README!

### ISSUE THREAD

**Issue by kevinzhangftw** [react-community/react-native-maps#2321]
### Is this a bug report?

NO

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

I might be dumb, but i was looking how to install for whole week before figuring how to do this.
If you use CRNA, you will not have ios nor android folder, do not npm eject!

expo already has maps installed. just use it like this:

```
import React from 'react';
import { MapView } from 'expo';

export default class App extends React.Component {
  render() {
    return (
      <MapView
        style={{ flex: 1 }}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />
    );
  }
}
```

This took me forever to figure out because all the documentation and youtube videos are outdated. Finally, i dug up this github issue and figure it outhttps://github.com/react-community/react-native-maps/issues/1981.  

as a new user, i shouldnt have to go through all of issue just to see the demo. Thanks very much listening to my rant. 

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by fqborges** [comment]
I do agree the installation.md should be updated, but for crna you should follow the crna docs. People maintaining this repo does not necessarily maintains crna (or Expo SDK).

On the crna faqs you can read:
 > Apps made with Create React Native App also support most of the JavaScript-to-Native APIs provided by the Expo SDK, since they are loaded by the Expo app.

Going to Explo SDK docs you can find the doc for MapView at https://docs.expo.io/versions/v27.0.0/sdk/map-view. In this doc you can see that API key config for your standalone app is specific for Expo apps.

A line stating that when using crna the MapView is already included would be a good thing, but instructions on how to build latest version on android using Gradle 3.x or how to fix android dependencies version mismatch is much more important in the current state of things.

I will try to make a pull with this when I find some time.

**Comment by kevinzhangftw** [comment]
Thanks for the your reply, rn has changed so quickly that anyone that is new to rn is using CRNA. that is what the official website is telling us to do. 

May be just have a CRNA section will help out alot of developers. let me know how i can help
