### ISSUE TITLE
Select a marker, go back and try to select it again fails

### ISSUE THREAD

**Issue by nschurmann** [react-community/react-native-maps#233]
Hello!, first of all amazing plugin!

I'm experiencing a strange behaviour, not sure if it is a bug.

I have maps with **Markers**, this markers have **custom views** (small red boxes), just like the image below
<img width="223" alt="screen shot 2016-05-14 at 9 15 15 pm" src="https://cloud.githubusercontent.com/assets/5099344/15271311/fb704142-1a18-11e6-9c41-57a6b02df2c0.png">

after i select one (let's say **5**) i will push the navigator state to another route (the details of the Marker selected), if i go back (with `navigator.pop()`) i won't be able to select the same box (**5**) again. I will only be able to select it again if i tap outside the box (anywhere in the map) and then tap again the box with **5**.

Is this behaviour expected?, i'm dispatching the event with this line of code:
`onSelect={e => dispatch(selectBox(box.id, navigator))`

**Comment by jrichardlai** [comment]
is this only happening for iOS ?

**Comment by nschurmann** [comment]
@jrichardlai haven't tested on android.

**Comment by laeckerv** [comment]
Maybe this helps?

https://github.com/facebook/react-native/issues/6242#issuecomment-219873431

**Comment by rborn** [comment]
Please let us know if this is still the case. Thank you.
Closing as it's an old issue.
