### ISSUE TITLE
MapView methods appear to be undefined on master branch

### ISSUE THREAD

**Issue by emilefleming** [react-community/react-native-maps#2333]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.55.3
    react: 16.3.1
    react-native-maps: "git+ssh://git@github.com/react-community/react-native-maps.git" (master branch)

### Steps to Reproduce

All MapView methods seem to be undefined in the MapView ref.

```
class MyComponent extends Component {
  pointForCoordinate (coordinate) {
    this.map.pointForCoordinate(coordinate, callback)
    // error this.map.pointForCoordinate not a function
  }

  render () {
    return (
      <MapView ref={map => this.map = map} />
    )
  }
}
```

### Expected Behavior

Method is called

### Actual Behavior

Error is thrown, method is not a function.

None of the methods seem to appear in the ref. Maybe I am missing something?

**Comment by j1mie** [comment]
@emilefleming Wondering if you found a solution to this? Experiencing the same issue

**Comment by emilefleming** [comment]
Bit embarrassing in my case, I had the wrong URL in my package.json for this lib (pointed at my fork instead) and so I was using an old version of the lib. I didn't notice until i opened the MapView source file in node_modules and noticed it was much shorter than the one on github. Correcting the URL and reinstalling fixed it for me.

**Comment by emilefleming** [comment]
@j1mie

**Comment by gabrielroriz** [comment]
I have this problem too... Some functions I can call using `this.maps._component`, but, it's not for all.
