### ISSUE TITLE
Text component inside Marker make marker not show

### ISSUE THREAD

**Issue by kidmysoul** [react-community/react-native-maps#2335]
### Is this a bug report?

no

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment
    react-native: 0.55.4
    react: 16.3.1
    react-native-map: 0.21.0

### Steps to Reproduce

I wraped text in marker but only the text show(marker not show )

### Expected Behavior

marker  and text both showing

### Actual Behavior

only text showing

this code is like 

`            {this.markers.map((marker, index) => (
                <Marker
                    key={index} coordinate={marker.latlng} title={marker.name}
                    pinColor={'red'}
                >
                  <Text>123</Text>
                </Marker>
            ))}`

<img width="369" alt="2018-06-18 13 41 05" src="https://user-images.githubusercontent.com/15664045/41518413-4e0680d0-72fd-11e8-962a-cd8ab22a0917.png">

**Comment by rborn** [comment]
You can't, it either shows the default using the pinColor or your own component, never both

```If NO custom marker view or custom image is provided, the platform default pin will be used, which can be customized by this color. Ignored if a custom marker is being used.``` https://github.com/react-community/react-native-maps/blob/master/docs/marker.md
