### ISSUE TITLE
Property 'style' does not exist on type '{}'.

### ISSUE THREAD

**Issue by the-joat** [react-community/react-native-maps#2338]
### Is this a bug report?
Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes.

### Environment
Example package.json here: https://gist.github.com/the-joat/43b1c371424ef5d2195f4ec52e99c5ea

### Steps to Reproduce
1. Initialize React Native
2. Install Typescript
3. Install react-native-maps
4. Import MapView then give MapView a style prop

### Expected Behavior
Type error thrown

### Actual Behavior
Type error not thrown

Screenshots included in SO question
![img](https://i.stack.imgur.com/j4J2u.png)
![img](https://i.stack.imgur.com/v2XZz.png)
![img](https://i.stack.imgur.com/yJqEC.png)

### Reproducible Demo
package.json, tslint.json, and tsconfig.json included https://gist.github.com/the-joat/43b1c371424ef5d2195f4ec52e99c5ea

**Comment by qventura** [comment]
This need to be reopened, it's still a valid issue.

By doing this, we can 
```
<MapView
   ...
   { ...{ style: styles.map } }
/>
```

**Comment by rborn** [comment]
@qventura fancy a PR ? 😊
