### ISSUE TITLE
Dynamically Rendering Marker Images

### ISSUE THREAD

**Issue by ZHamburglar** [react-community/react-native-maps#2343]
I'm working on dynamically rendering images in my list of markers. I have a separate .json file that contains information regarding what I'm trying to rendering. Each of the items has a different image that I'm trying to render as they correspond to different types of things. If I hard code it to something like "../assets/icons/beer-jar.png" then they will all render correctly, but whenever I try to replace it with something dynamic like {MapMarker.icon} then the application will crash. If there an issue with syntax or does there need to be a work around to render the different icons?

import React, { Component } from 'react';
import { View, Platform, Image, Text, Button, Dimensions } from 'react-native';
import MapView, { PROVIDER_GOOGLE, Marker } from 'react-native-maps';
import { Divider } from 'react-native-elements';
import { connect } from 'react-redux';

import Expo from 'expo';

// import MarkerComponent from '../components/MapMarkers'

import { STATUS_BAR_HEIGHT, SCREEN_WIDTH } from '../constants';

const window = Dimensions.get('window');

class MapScreen extends Component {

  render() {
    const { container, mapView } = styles;
    const { MapMarkers } = this.props.mapMarkers.locations
    console.log("props for markers", this.props.mapMarkers.locations)

    return (
      <View>
        <View style={container}>
          <MapView
            provider={PROVIDER_GOOGLE}
            style={mapView}
            initialRegion={{
                latitude: 30.26722,
                longitude: -97.7619,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
              }}
          >
          {this.props.mapMarkers.locations.map(MapMarker => 
          <Marker 
          key={MapMarker.id}
          coordinate={{ latitude: MapMarker.latitude, longitude: MapMarker.longitude }}
          title={MapMarker.name}
          description={MapMarker.description}
          image={require('{MapMarker.icon}')}
          />)} 
          
        </MapView>
        </View>
      </View>
    );
  }
}

const mapStateToProps = state => {
  return { mapMarkers: state.mapMarkers };
};

export default connect(mapStateToProps) (MapScreen);`

**Comment by stianjensen** [comment]
`require` in react-native needs a static path to an asset in order to work:
https://facebook.github.io/react-native/docs/images.html

So you will have to create a mapping in your app between different strings and calls to require for each image.

For instance an object like this:
```
const markerImages = {
    iconOne: require('icon-one.png'),
    iconTwo: require('icon-two.png'),
};
...
<Marker image={markerImages[MapMarker.icon]} />
```

**Comment by giusousa** [comment]
Thanks!!!

**Comment by z00m1n** [comment]
> `require` in react-native needs a static path to an asset in order to work:
> https://facebook.github.io/react-native/docs/images.html
> 
> So you will have to create a mapping in your app between different strings and calls to require for each image.
> 
> For instance an object like this:
> 
> ```
> const markerImages = {
>     iconOne: require('icon-one.png'),
>     iconTwo: require('icon-two.png'),
> };
> ...
> <Marker image={markerImages[MapMarker.icon]} />
> ```

great approach, thanks for that! 👍 
however, what if `MapMarker.icon` is only know at runtime, e.g. because I get an image URL from a REST API ?

**Comment by stianjensen** [comment]
> > `require` in react-native needs a static path to an asset in order to work:
> 
> > https://facebook.github.io/react-native/docs/images.html
> 
> > 
> 
> > So you will have to create a mapping in your app between different strings and calls to require for each image.
> 
> > 
> 
> > For instance an object like this:
> 
> > 
> 
> > ```
> 
> > const markerImages = {
> 
> >     iconOne: require('icon-one.png'),
> 
> >     iconTwo: require('icon-two.png'),
> 
> > };
> 
> > ...
> 
> > <Marker image={markerImages[MapMarker.icon]} />
> 
> > ```
> 
> 
> 
> great approach, thanks for that! 👍 
> 
> however, what if `MapMarker.icon` is only know at runtime, e.g. because I get an image URL from a REST API ?


The docs say that only local images may be used with the `image` prop:

> | `image` | `ImageSource` |  | A custom image to be used as the marker's icon. Only local image resources are allowed to be used.

However, you can render a custom child view with your own standard react native Image component that does handle remote urls. I assume that will have a performance hit over embedding marker images in your app and referencing them with some sort of enum though. But if you need it, that is mentioned at the bottom of the doc for Marker:

https://github.com/react-native-community/react-native-maps/blob/master/docs/marker.md

**Comment by z00m1n** [comment]
Thank you very much for your super-quick response - you would not believe how much you've helped me with that! 👍👍👍 
They've really tucked the child image info nicely away down there on that page, gotta admit I stopped reading after `Only local image resources are allowed to be used.`
Found some other code samples in the mean time that make a lot more sense now:
- <https://www.reddit.com/r/reactnative/comments/auy3hj/reactnativemaps_marker_icon_doesnt_change_to>
- <https://lifesaver.codes/answer/images-inside-marker-views-are-not-always-rendered-on-android>
