### ISSUE TITLE
Many markers results in large memory consumption.

### ISSUE THREAD

**Issue by CarstenHoyer** [react-community/react-native-maps#2346]
### Is this a bug report?
Yes I believe it is a bug or at least a question about optimization.

We have a map, where we are currently loading 258 markers (this is too many, and it is another issue, we should fix eventually). Some markers have one image, some markers use another image. So we are setting the image dynamically on the markers.

I have noticed that it looks like each marker creates its own bitmap, so the memory usage goes way up. I am not sure if this is just the way the devices work. But it would seem more resource friendly to me, if all the markers referenced the same image in memory. Is this possible?

Examples from Android Device monitor and Memory Analyzer with 2000 markers.
<img width="390" alt="skaermbillede 2018-06-20 kl 14 05 42" src="https://user-images.githubusercontent.com/1811751/41657633-4de638be-7494-11e8-98ec-b7bd2cc3a003.png">
![skaermbillede 2018-06-20 kl 14 07 22](https://user-images.githubusercontent.com/1811751/41657634-4e0d1966-7494-11e8-92b8-6945603c5c30.png)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment
react-native: 0.53.3
react: 16.2.0
react-native-maps: 0.20.1

Target platform: Android 7.0

### Steps to Reproduce
Use the below code in App.js in a react-native project. And use the attached markers. Then just run the app.

### Expected Behavior
Less memory would be used.

### Actual Behavior
A lot of memory was used. 141.2Mb for 2000 markers.

### Reproducible Demo

```Javascript
import React from 'react'
import { StyleSheet } from 'react-native'
import MapView, { Marker } from 'react-native-maps'

export default class extends React.Component {
  constructor (props) {
    super(props)
    this.guideMarker = require('../src/modules/assets/guideMark.png')
    this.caseMarker = require('../src/modules/assets/caseMark.png')
    this.state = {
      region: {
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421
      }
    }
  }

  render () {
    return (
      <MapView
        region={this.state.region}
        style={{...StyleSheet.absoluteFillObject}}>
        {[...Array(2000).keys()].map((m, i) => (
          <Marker
            key={i}
            coordinate={{ latitude: 37.78825, longitude: -122.4324 }}
            image={i % 2 === 0
              ? this.guideMarker
              : this.caseMarker}
          />
        ))}
      </MapView>
    )
  }
}
```

![casemark 2x](https://user-images.githubusercontent.com/1811751/41657409-985d3b96-7493-11e8-8b56-c00f601e624c.png)
![guidemark 2x](https://user-images.githubusercontent.com/1811751/41657410-987c676e-7493-11e8-9190-b4fd63794c37.png)

**Comment by rborn** [comment]
@CarstenHoyer Try the github version, the #2320 might fix this. Let us know.

**Comment by CarstenHoyer** [comment]
@rborn I tried out the github version. I only had an emulator available, but it looks like it fixes this issue. I am closing the issue, and will reopen if it turns out the issue is still on a real device.
