### ISSUE TITLE
showCompass does not work on AppleMaps

### ISSUE THREAD

**Issue by gvlekke** [react-community/react-native-maps#2350]
### Is this a bug report?
yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment
 react-native: 0.53.3
 react: 16.3.1
 react-native-maps: 0.21.0 

Target Platform:: iOS - 11.4 Simulator/iPhone SE
Maps type: Apple maps

* It is working on Google maps on iOS. We don't want Google maps because of performance issues with the markers.

### Steps to Reproduce

1. Add the option `showsCompas={false}` to the mapview
2. Show a screen with the map. 
3. Then turn the map so north is not at the top direction.

### Expected Behavior
The compass shouldn't be shown because the showCompass is set to false

### Actual Behavior
The compass is shown.

### Reproducible Demo
https://snack.expo.io/ByaE7CcZQ

1. run on preview
2. click on option/alt and while holding alt turn the map to a other orientation (north not at the top)
3. the compass is shown :(

**Comment by gvlekke** [comment]
my mistake missed a s in the showcompass

**Comment by diogoviannaaraujo** [comment]
I think this is broke again
