### ISSUE TITLE
fresh install from npm, version 0.21.0 does not include react-native 0.55 in peer deps, even though the package.json here in github says it does

### ISSUE THREAD

**Issue by paolord** [react-community/react-native-maps#2352]
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.55.4
    react: 16.3.1
    react-native-maps: 0.21.0
 

### Steps to Reproduce

1. Included react-native 0.55.4, react 16.3.1 and expo 28.0.0
2. used npm install, triggered a warning: 
`react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52 || ^0.53 || ^0.54 but none was installed.`
3. Checked this github repo and found out react-native ^0.55 was included in peer deps in package.json with same exact version 0.21.0
4. Checked http://registry.npmjs.org/react-native-maps, exact same version 0.21.0, react-native ^0.55 is not included in peer deps for that version.

### Expected Behavior

Expected react-native ^0.55 to be in peer deps of react-native-maps version 0.21.0

### Actual Behavior

Throws the warning:
`react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52 || ^0.53 || ^0.54 but none was installed.`

I think someone just needs either republish 0.21.0 again or bump up the version and publish.

Thanks

**Comment by rborn** [comment]
please use the github version, it's not published yet on npm
