### ISSUE TITLE
animateToNavigation is not a function

### ISSUE THREAD

**Issue by njnest** [react-community/react-native-maps#2355]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.55.3
react: 16.3.1
react-native-maps: 0.21.0

### Steps to Reproduce

Just start up this example https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedNavigation.js

### Expected Behavior

Just working example

(Write what you thought would happen.)

### Actual Behavior

I try to call `animateToNavigation` from this example https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedNavigation.js but I get "this.map.animateToNavigation is not a function"

![image](https://user-images.githubusercontent.com/15174668/42138119-8b5d78c8-7d78-11e8-84b2-96948e53ac07.png)

### Reproducible Demo

Just try to use your example. 

### P.S.
I saw that is the new feature, Perhaps you added it to the documentation but not yet added to the package.

**Comment by rborn** [comment]
@njnest please use the git version, not the npm one, sadly we didn't have the time to publish to npm

**Comment by njnest** [comment]
@rborn it seems everything works with the git version. 
So, I hope in the next version for npm you will publish animateToNavigation.

Have a nice day
