### ISSUE TITLE
Map returns to center when setState is called within onRegionChange

### ISSUE THREAD

**Issue by mitajunior** [react-community/react-native-maps#2356]
Need help with this.

When never you drag the map and hook onRegionChange 

i.e
`
state = { region: latLngDelta }

 onRegionChange = (region) => { 
     this.setState({blah: 'blah'}) 
}`

Doesn't matter what context is changed in state, the map always recenters

Any workarounds?

**Comment by mitajunior** [comment]
@brownbl1 realized I am supposed to use initialRegion instead of region if you intend on changing the region

**Comment by EskelCz** [comment]
@mitajunior In readme it says the exact opposite:
`Use initialRegion instead of region only if you don't want to control the viewport of the map besides the initial region.`
The issue still exists, can you please reopen this?
