### ISSUE TITLE
can't show google maps on iOS

### ISSUE THREAD

**Issue by shoki2shoki** [react-community/react-native-maps#2362]
I couldn't display google maps on iOS, only can show apple map even though I add some codes to ios/YOUR_PROJECT_NAME/AppDelegate.m according to installation guide below.
```
+ @import GoogleMaps; //add this line if you want to use Google Maps

@implementation AppDelegate
...

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
+  [GMSServices provideAPIKey:@"_YOUR_API_KEY_"]; // add this line using the api key obtained from Google Console
...
```
↑I put my google api key instead of "_YOUR_API_KEY_"

https://github.com/react-community/react-native-maps/blob/master/docs/installation.md

Did someone have same problem?

**Comment by declandowling** [comment]
You probably haven't specified Google maps as the provider. 

`import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'`
`<MapView provider={PROVIDER_GOOGLE}>`

The docs aren't very clear on this, I had trouble with it myself until I read down to **[Customizing the map style](https://github.com/react-community/react-native-maps#customizing-the-map-style)**

**Comment by shoki2shoki** [comment]
Thank you for your comment. I resolved it.

**Comment by shoki2shoki** [comment]
I'm closing this issue because I found out the way to display google maps.

**Comment by SiSa68** [comment]
Please add @declandowling 's comment to [Enabling Google Maps](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps) section of the documentation!
It took me a few hours to find this!!
