### ISSUE TITLE
React native área polygon calculation

### ISSUE THREAD

**Issue by joaopaulorefatti** [react-community/react-native-maps#2365]
How can I calculate a polygon area in react native?

**Comment by PatrickCavalcanti** [comment]
I need too.

**Comment by prashantvv** [comment]
Hello, did you find any workaround for calculating the area so far.

**Comment by PatrickCavalcanti** [comment]
it works...


  function calcArea(locations) {   

    if (!locations.length) {    
      return 0;
    }
    if (locations.length < 3) {
      return 0;
    }
    let radius = 6371000;

    const diameter = radius * 2;
    const circumference = diameter * Math.PI;
    const listY = [];
    const listX = [];
    const listArea = [];
    // calculate segment x and y in degrees for each point

    const latitudeRef = locations[0].latitude;
    const longitudeRef = locations[0].longitude;
    for (let i = 1; i < locations.length; i++) {
      let latitude = locations[i].latitude;
      let longitude = locations[i].longitude;
      listY.push(this.calculateYSegment(latitudeRef, latitude, circumference));

      listX.push(this.calculateXSegment(longitudeRef, longitude, latitude, circumference));

    }

    // calculate areas for each triangle segment
    for (let i = 1; i < listX.length; i++) {
      let x1 = listX[i - 1];
      let y1 = listY[i - 1];
      let x2 = listX[i];
      let y2 = listY[i];
      listArea.push(this.calculateAreaInSquareMeters(x1, x2, y1, y2));

    }

    // sum areas of all triangle segments
    let areasSum = 0;
    listArea.forEach(area => areasSum = areasSum + area)


    // get abolute value of area, it can't be negative
    let areaCalc = Math.abs(areasSum);// Math.sqrt(areasSum * areasSum);  
    return areaCalc;

  }

  function calculateAreaInSquareMeters(x1, x2, y1, y2) {
    return (y1 * x2 - x1 * y2) / 2;
  }

  function calculateYSegment(latitudeRef, latitude, circumference) {
    return (latitude - latitudeRef) * circumference / 360.0;
  }

  function calculateXSegment(longitudeRef, longitude, latitude, circumference) {
    return (longitude - longitudeRef) * circumference * Math.cos((latitude * (Math.PI / 180))) / 360.0;
  }

**Comment by prav02** [comment]
@PatrickCavalcanti I have seen the code you share and I want to implement this in the below code, how can the following code can be implemented in the following code. Thanks in advance.
export default class PolyLines extends Component{
    constructor(){
        super();
        this.state={
              coords:[
                { latitude: 37.8025259, longitude: -122.4351431 },
                { latitude: 37.7896386, longitude: -122.421646 },
                { latitude: 37.7665248, longitude: -122.4161628 },
                { latitude: 37.7948605, longitude: -122.4596065 },
                { latitude: 37.8025259, longitude: -122.4351431 }
            ]
        }
    }

    render(){
        const {initialRegion} = this.state
        return(
            <View style={styles.mapContainer}>
                <MapView
                initialRegion={initialRegion}
                style={styles.map}>
	<Polygon
		coordinates={this.state.coords}
		strokeColor='#B24112' 
		// strokeColors={[
		// 	'#7F0000',
		// 	'#00000000',
		// 	'#B24112',
		// 	'#E5845C',
		// 	'#238C23',
		// 	'#7F0000'
		// ]}
		strokeWidth={3}
	/>
</MapView>
            </View>
        )}}
const styles = StyleSheet.create({
    mapContainer:{
      flex:1,
        height: 200,
        width:'100%',
        margin:20,
    },
    map:{
        width:'100%',
        height:'100%'
    }
  });
