### ISSUE TITLE
Invariant Violation requireNativeComponent AirMap was not found i UiManager

### ISSUE THREAD

**Issue by sananddev** [react-community/react-native-maps#2369]
![screenshot from 2018-07-09 15-39-13](https://user-images.githubusercontent.com/35886764/42445873-35ae7e46-8394-11e8-90ac-bf5a7738469e.png)
#  my build.gradle file is 
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
            

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

ext {
    compileSdkVersion   = 26
    targetSdkVersion    = 26
    buildToolsVersion   = "26.0.2"
    supportLibVersion   = "26.1.0"
    googlePlayServicesVersion = "11.8.0"
    androidMapsUtilsVersion = "0.5+"
}

# my package.json file is 
{
  "name": "MapView",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0"
  },
  "devDependencies": {
    "babel-jest": "23.2.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.3.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

# my Maping.js file
import React, {Component} from 'react';
import {View,StyleSheet,Text} from 'react-native';
import MapView from 'react-native-maps';
export default class Mapss extends Component{
    render(){
        return(
            <View style={styles.container}>
                <MapView style={styles.map}
    initialRegion={{
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    }}
  />  
            </View>
        );
    }
}
 const styles=StyleSheet.create({
    container: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: "flex-end",
        alignItems: "center"
        },
        map: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0
        }
 });

# my index.js 

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import Mapss from './Maping';
AppRegistry.registerComponent(appName, () => Mapss);
  

## if anybody knew the solution please kindly inform me and i guess that i am having this issue is because i am using gradle 3.1 and react-native 5.6 or may be i have some problem in build.gradle file so sincearly  see the problem

**Comment by Mhossni94** [comment]
Same issue here

**Comment by pabloga265** [comment]
having the same issue in IOS

    "react-native-maps": "^0.21.0",
    "react-native": "0.56.0",

**Comment by mks1948** [comment]
And I have this same issue

**Comment by tdurand** [comment]
Same here, on iOS, will try tomorrow with another version of react native map

**Comment by aozisik** [comment]
I had the same issue in iOS. Fixed this by doing the following:

Open the following folder:

    node_modules/react-native-maps/lib/ios

Drag & drop the AirMaps folder (and not the AirMaps.xcodeproj !) into Xcode.
Uncheck `copy items ...`, and check your app under `add to targets`

**Comment by tdurand** [comment]
@aozisik Interesting, it didn't worked for me yet, where do you drag & drop it ? Anywhere in the project ?

**Comment by aozisik** [comment]
@tdurand Under Libraries but it shouldn't matter I guess.

**Comment by tdurand** [comment]
that is what I think also, didn't worked, I'm now trying to set up the project from scratch again... did you enabled google map or only native ios map in the Podfile ?

**Comment by aozisik** [comment]
I am not using Cocoapods. And also not google maps.

**Comment by tdurand** [comment]
Thanks, I solved this by reinstalling react-native-map from this commit: https://github.com/react-community/react-native-maps/pull/2310#issuecomment-404883935 , and then react-native link instead of cocoa pods, no need to drop the AirMap folder in this case.

**Comment by sananddev** [comment]
hey i got the solution , actually  what i did mistake is that i did not put any implementation method in app build.gradle file. and i think that was the problem. so i fixed it.

**Comment by Koshukey** [comment]
And alo, when i restart app, my app crashed

**Comment by mks1948** [comment]
I have this issue on Android

**Comment by sananddev** [comment]
its simple just check some of you build.gradle file and on dependencies use implementation  (but not compile) this  is a new syntax

**Comment by mks1948** [comment]
`Task :react-native-maps:compileDebugJavaWithJavac FAILED
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:18: error: cannot find symbol
import com.facebook.react.uimanager.UIBlock;
                                   ^
  symbol:   class UIBlock
  location: package com.facebook.react.uimanager
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/RegionChangeEvent.java:15: error: no suitable constructor found for Event(int)
    super(id);
    ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int,long) is not applicable
      (actual and formal argument lists differ in length)
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java:121: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java:124: error: cannot find symbol
    super.setZIndex(view, zIndex);
         ^
  symbol: method setZIndex(AirMapMarker,float)
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:119: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package
    if (!contextHasBug(appContext.getCurrentActivity())) {
                                 ^
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:120: error: getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package
      superContext = appContext.getCurrentActivity();
                               ^
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:123: error: cannot find symbol
      if (!contextHasBug(reactContext.getCurrentActivity())) {
                                     ^
  symbol:   method getCurrentActivity()
  location: variable reactContext of type ThemedReactContext
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:124: error: cannot find symbol
        superContext = reactContext.getCurrentActivity();
                                   ^
  symbol:   method getCurrentActivity()
  location: variable reactContext of type ThemedReactContext
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:89: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock() {
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:152: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock()
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
/home/jakub/Desktop/JakubKowalski/mobileapp/GoogleApp/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java:187: error: cannot find symbol
    uiManager.addUIBlock(new UIBlock()
                             ^
  symbol:   class UIBlock
  location: class AirMapModule
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`

I have a problem for 3 days, what should I do?

**Comment by mks1948** [comment]
Now, I have this problem 
`Task 'installDebug' not found in root project 'GoogleApp'.`

**Comment by mks1948** [comment]
@sananddev  I did everything I updated the gradle but still does not work and the same error

**Comment by sananddev** [comment]
@mks1948 can you paste all your build.gradle file here

**Comment by erenakbltt** [comment]
I have same issue on android and ios. 
Tried this installation too.
https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14

**Comment by sananddev** [comment]
i am going to open this issue until we find the solution

**Comment by janioxavier** [comment]
Solution for this problem can be found here:

[](https://itnext.io/install-react-native-maps-with-gradle-3-on-android-44f91a70a395)

**Comment by rfdc** [comment]
It is not working on IOS for me. Android is fine:
"react": "16.4.1",
"react-native": "0.56.0",
"react-native-maps": "^0.21.0",

**Comment by pulkitsapra** [comment]
It doesn't work with 
"react-native": "0.56.0",
"react-native-maps": "^0.21.0"

**Comment by bavachaucp0002** [comment]
@pulkitsapra  same :((

**Comment by pulkitsapra** [comment]
You can try this solution, it worked for me!
```
add pod Google-Maps-iOS-Utils in the podfile
Add AirMaps folder to your project
remove AirMaps.xcodeproj from Libraries
remove libAirMap.a from Link Binary with Libraries
```

This is the solution suggested by https://stackoverflow.com/a/50931023/2713214

**Comment by herkyl** [comment]
For me the issue resolved after rerunning `pod install` while in the `ios` folder.

**Comment by icemancast** [comment]
@herkyl what versions are you running? I am getting the same error and have not been able to resolve.

**Comment by herkyl** [comment]
@icemancast 
```json
"dependencies": {
     "react": "16.4.1",
     "react-native": "0.56.0",
     "react-native-maps": "^0.21.0"
   },
```

**Comment by icemancast** [comment]
@herky Thanks I ended finding a work around another way. Mine are similar versions.

**Comment by tomoyuki28jp** [comment]
@icemancast What was your way to fix this issue?

**Comment by icemancast** [comment]
@tomoyuki28jp I used this PR for my library https://github.com/react-community/react-native-maps/pull/2310#issuecomment-417823504

After doing that I installed the maps manually here: https://developers.google.com/maps/documentation/ios-sdk/start

Now seeing it was closed with another solution as that issue above was closed but I have not tried the new solution.

**Comment by wresniwahyu** [comment]
@aozisik i have some problem and i use "react-native-maps": "^0.21.0" & "react-native": "^0.56.0"
 i am not use google map too, i want to show map using openstreetmap

can anyone help me how to use openstreetmap with react-native-maps without google map api key

**Comment by rborn** [comment]
#2396  was merged, please test with the latest git version. 
Please keep in mind that you might have to setup the module again as now it works with `react-native link`
Read the install manual carefully

**Comment by mgcrea** [comment]
@rborn any chance you could cut a release soon with these changes?

**Comment by rborn** [comment]
@mgcrea I can't make the releases, maybe @christopherdro can help but we could use somebody's help to prepare the changelog 🤪

**Comment by mgcrea** [comment]
Would this [nice compare view](https://github.com/react-community/react-native-maps/compare/v0.21.0...master) be good enough 😜?

**Comment by rborn** [comment]
@mgcrea something more like this: https://github.com/react-community/react-native-maps/releases :)

**Comment by abhinavpadala** [comment]
I had the same issue in android. It was working well the previous day and when I checked it today I got this error. I uninstalled and reinstalled the app. Surprisingly, this solved the issue for now.

**Comment by lakkakularajesh** [comment]
This error got resolved after `pod install` inside `ios` folder

**Comment by madhums** [comment]
Can anyone explain why this error occurs? May be good to also document this in the troubleshooting section.

**Comment by kevinsalcedoUab** [comment]
(Android) I solve that with a rebuild app. `react-native run-android`

**Comment by seanflyyy** [comment]
I used this website. https://www.freecodecamp.org/news/how-to-integrate-maps-in-react-native-using-react-native-maps-5745490fe055/

Namely, after creating a react native file using 
- react-native init ReactNativeMaps
- cd ReactNativeMaps
- react-native run-ios 
- npm install --save react-native-maps  
- react-native link react-native-maps
