### ISSUE TITLE
Overlay - bounds

### ISSUE THREAD

**Issue by jantemel** [react-community/react-native-maps#2371]
Hello, 

why do Overlay component wants bounds: [NW, SE] when Google uses [NE, SW]?

https://developers.google.com/maps/documentation/javascript/reference/3/coordinates#LatLngBounds

Its annoying to convert from one coordinate system to another? Can you use Google method?

**Comment by markmssd** [comment]
I totally agree with you @jantemel. I believe to change it now would be a breaking change to anyone using it, so not sure what's the best way to approach it.

**Comment by matifriaz** [comment]
> Hello,
> 
> why do Overlay component wants bounds: [NW, SE] when Google uses [NE, SW]?
> 
> https://developers.google.com/maps/documentation/javascript/reference/3/coordinates#LatLngBounds
> 
> Its annoying to convert from one coordinate system to another? Can you use Google method?

Can You please how to get the right bounds everything is working fine on IOS but on android I only see a line on right side of the polygon
