### ISSUE TITLE
directory not found for option

### ISSUE THREAD

**Issue by yooouuri** [react-community/react-native-maps#2377]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
react-native: 0.56.0
react: 16.4.1
react-native-maps: 0.21.0

### Steps to Reproduce

1. create empty react native
2. `yarn add react-native-maps`
3. create Podfile file in the ios folder
4. `pod install`
5. open .xcworkspace
6. changed Build Configuration to release (Product > Scheme > Edit Scheme ...)

<img width="559" alt="image" src="https://user-images.githubusercontent.com/12934957/42657295-18b33350-8622-11e8-9dff-f1f6c6418774.png">

### Expected Behavior
Build should succeed.

### Actual Behavior
Clean works, building crashes.

**In debug, it builds...**

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
ld: warning: directory not found for option '-L/Users/yooouuri/Library/Developer/Xcode/DerivedData/parkingapp-gsyhlbpnneouzmgazfpqdrhtbzay/Build/Products/Release-iphonesimulator/DoubleConversion'
ld: warning: directory not found for option '-L/Users/yooouuri/Library/Developer/Xcode/DerivedData/parkingapp-gsyhlbpnneouzmgazfpqdrhtbzay/Build/Products/Release-iphonesimulator/Folly'
ld: warning: directory not found for option '-L/Users/yooouuri/Library/Developer/Xcode/DerivedData/parkingapp-gsyhlbpnneouzmgazfpqdrhtbzay/Build/Products/Release-iphonesimulator/React'
ld: warning: directory not found for option '-L/Users/yooouuri/Library/Developer/Xcode/DerivedData/parkingapp-gsyhlbpnneouzmgazfpqdrhtbzay/Build/Products/Release-iphonesimulator/glog'
ld: warning: directory not found for option '-L/Users/yooouuri/Library/Developer/Xcode/DerivedData/parkingapp-gsyhlbpnneouzmgazfpqdrhtbzay/Build/Products/Release-iphonesimulator/react-native-maps'
ld: warning: directory not found for option '-L/Users/yooouuri/Library/Developer/Xcode/DerivedData/parkingapp-gsyhlbpnneouzmgazfpqdrhtbzay/Build/Products/Release-iphonesimulator/yoga'
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

<img width="881" alt="image" src="https://user-images.githubusercontent.com/12934957/42657253-f9f718f0-8621-11e8-9b78-574b53ca19ef.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/12934957/42657264-02693bf8-8622-11e8-9fd3-b90840091e2c.png">

### Reproducible Demo

Please follow the steps, I tried it with a new project and it still occurs.

**Comment by lww** [comment]
I had the same issue. Turned out I opened .xcodeproj instead of .xcworkspace file.

**Comment by monkibraum** [comment]
+1 ; opening .xcworkspace file didn't fix this problem either

**Comment by tushgup** [comment]
> +1 opening .xcworkspace file didn't fix this problem either. And the same environment!
> 
> react-native: 0.56.0
> react: 16.4.1
> react-native-maps: 0.21.0

Hey @monkibraum - did you end up fixing this? I'm stuck at this too.

**Comment by rborn** [comment]
You need to use the podfile in the intallation instructions

**Comment by onusgit** [comment]
send code

**Comment by riyastk** [comment]
any solutions for this issue..?

**Comment by jetobe95** [comment]
I have same error ,resolved changing Podfile  https://sandstorm.de/de/blog/post/react-native-managing-native-dependencies-using-xcode-and-cocoapods.html
And Try changing workspaceSetting in Xcode
 https://www.youtube.com/watch?v=aSPg3UUrMco

**Comment by ibanezzaro** [comment]
Same issue here, any updates?

**Comment by ziyoshams** [comment]
Here is my working version, just in case someone needs this: 
`react-native-maps: ^0.23.0`
`react-native: 0.59.1`

// Podfile
```
platform :ios, '9.0'

target 'SOME_PROJECT' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by sayem314** [comment]
While I don't have react-native-maps, I found this issue via google and just want to say that I had a similar issue with Cocoapods and open .xcworkspace solved it for me.

**Comment by Jaroswaldo** [comment]
@sayem314 there already are this suggestions and still there are people that could not resolve it with this "little trick". Any other suggestions?

**Comment by sayem314** [comment]
> @sayem314 there already are this suggestions and still there are people that could not resolve it with this "little trick". Any other suggestions?

Not sure, lately `react-native` is working pretty good for me. Maybe start a fresh project and move sources! I usually keep writing everything inside `src` folder so if there is an issue with `react-native` I can start fresh very quickly :smile: However if there is something wrong with a plugin then try to find the cause, probably install few earlier version and see if that works because latest is not always the answer!
