### ISSUE TITLE
How to animate to region but not center map around main coordinate

### ISSUE THREAD

**Issue by vvusts** [react-community/react-native-maps#2378]
As you can see from image bellow I have something similar to one of [gif examples](https://camo.githubusercontent.com/9b5fcde0cb8146672f54d39fc3c34bd2e1f7891f/687474703a2f2f692e67697068792e636f6d2f336f365542644751644d31476d566f4964712e676966) but still not clear how to implement this.
One list item is one marker coordinate. So when I scroll list for current item I call:
`this.map.getMapRef().animateToRegion(createRegion(...));`
And this region I am getting like:
```
createRegion(lat, lon, distance, moveCoordinatesUp) {
    if (moveCoordinatesUp) {
      var R = 6378137;
      var _lat = lat;
      var _lng = lon;

      var dLat = moveCoordinatesUp / R;
      var dLng = moveCoordinatesUp / (R * Math.cos(Math.PI * _lat / 180));

      lat = _lat + dLat * 180 / Math.PI;
      lng = _lng + dLng * 180 / Math.PI;
    }
    
    // Make a region
    distance = distance / 2;
    const circumference = 40075;
    const oneDegreeOfLatitudeInMeters = 111.32 * 1000;
    const angularDistance = distance / circumference;

    const latitudeDelta = distance / oneDegreeOfLatitudeInMeters;
    const longitudeDelta = Math.abs(
      Math.atan2(
        Math.sin(angularDistance) * Math.cos(lat),
        Math.cos(angularDistance) - Math.sin(lat) * Math.sin(lat)
      )
    );

    return (result = {
      latitude: lat,
      longitude: lon,
      latitudeDelta,
      longitudeDelta
    });
  }
```
Problem is that you can see that I when create region move region up for number of meters.
So I am trying to `animateToRegion` where `marker` is but to make **center in a visible area to avoid that list cover marker**.
I think that this might be solved with edgePadding but it's not clear to me what it does.
Any help on this?

I tried to set `mapPadding` but this do nothing marker is always at the map center.

**Comment by shiftrtech** [comment]
Hi @vvusts, have you finish thisor can you help me with some directions, thanks.
