### ISSUE TITLE
Google map on Android not visible, but logo Is

### ISSUE THREAD

**Issue by goinnovative** [react-community/react-native-maps#2379]
The Google Map package of Airbnb already ran on my android device. Now I made several updates and installed new packages and now I don't see the Google Map anymore. I only see the Google Logo in the left bottom corner. I am using react-native 0.54.2 and react-native-maps 0.21.0.

**android/app/build.gradle**

    dependencies {
        implementation fileTree(dir: "libs", include: ["*.jar"])
        implementation "com.android.support:appcompat-v7:27.0.0"
        implementation "com.facebook.react:react-native:+"  // From node_modules
    
        implementation project(':react-native-onesignal')
        implementation project(':react-native-i18n')
        implementation project(':react-native-splash-screen')
        implementation project(':react-native-linear-gradient')
        implementation project(':react-native-fetch-blob')
        implementation project(':react-native-image-picker')
    
        implementation(project(':react-native-maps')){
            exclude group: 'com.google.android.gms', module: 'play-services-base'
            exclude group: 'com.google.android.gms', module: 'play-services-maps'
        }
    
        implementation project(':react-native-firebase')
    
        // Firebase dependencies
        implementation "com.google.android.gms:play-services-base:15.0.0"
        implementation "com.google.android.gms:play-services-maps:15.0.0"
        implementation "com.google.firebase:firebase-core:15.0.2"
        implementation "com.google.firebase:firebase-analytics:15.0.2"
    
    }

**AndroidManifest.xml inside of <application>**

    <meta-data
                android:name="com.google.android.geo.API_KEY"
                android:value="xxx"/>

MainApplication.java

    import com.airbnb.android.react.maps.MapsPackage;

and 

    @Override
        protected List<ReactPackage> getPackages() {
          return Arrays.<ReactPackage>asList(
              new MainReactPackage(),
                new RNFirebasePackage(),
                new RNFirebaseCrashPackage(),
                new RNFirebaseAnalyticsPackage(),
                new ImagePickerPackage(),
                new MapsPackage(),
                new ReactNativeOneSignalPackage(),
                new RNI18nPackage(),
                new SplashScreenReactPackage(),
                new LinearGradientPackage(),
                new RNFetchBlobPackage()
          );
        }

**Comment by JerryAWalker** [comment]
sounds like  API key issue.

**Comment by goinnovative** [comment]
I am using exactly the same API key in iOS.

**Comment by batuhansahan** [comment]
same here

**Comment by goinnovative** [comment]
I solved it by activating **Maps SDK for Android** in my Google Maps Platform.
