### ISSUE TITLE
Zoom very large when call fitToCoordinates - how to manipulate it

### ISSUE THREAD

**Issue by vvusts** [react-community/react-native-maps#2383]
This is not a bug report and I need kind of fast information about this please.
To set map view I use:
```
this.map.fitToCoordinates([{latitude: obj.latitude, longitude: obj.longitude}], {
    edgePadding: { top: 50, right: 50, bottom: 120, left: 50 },
    animated: true
  });
```
But after this code zoom is very close for example I see only part of the street and I want to make it to see more streets around.
Can this be achieved?
I am using maps: 0.20.1

**Comment by rborn** [comment]
Try with `animateToRegion`

Also closing the issue for not respecting the template

**Comment by vvusts** [comment]
@rborn I can't use `animateToRegion` as I need to set edgePadding. I have overlay items over the map `fitToCoordinates` is only method that allow me to set map view to are of map I need.

**Comment by vvusts** [comment]
@rborn can you please reopen issue I update to template?

**Comment by vvusts** [comment]
@rborn should I open new qustion or this can be reopened?

**Comment by rborn** [comment]
I see you opened a new one https://github.com/react-community/react-native-maps/issues/2384 so well keep that closed, right?

**Comment by vvusts** [comment]
Yes i created new. Sorry there was no feedback and I am still trying to make this work. So I need some help. And sorry for template.

**Comment by vvscode** [comment]
I faced the same issue on 0.30.2
