### ISSUE TITLE
Snapshot in satellite mode for IOS snap it in default instead of satellite view, - this works fine in android

### ISSUE THREAD

**Issue by MXLI88** [react-community/react-native-maps#2404]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment

react-native: 0.55.4
react: 16.4.0
react-native-maps: 0.21.0
target : IOS 
Map: ???

### Steps to Reproduce

1. take a snapshot for satellite mode. 
2. expected the image in same snapshot mode, but the image is in standard maptype mode instead of satellite.
this works fine in android
![img_20180731_094017](https://user-images.githubusercontent.com/41943279/43445231-27e76354-94a6-11e8-9d2e-9758c9b49e41.jpg)
![img_20180731_094032](https://user-images.githubusercontent.com/41943279/43445232-2800619c-94a6-11e8-8600-bd4c5e982565.jpg)
### Expected Behavior

take a snapshot in the mapview(satellite), expected in same view in the snapped image. (IOS)

### Reproducible Demo

the project example.

**Comment by brunsy** [comment]
@MXLI88 Just came across this myself.  
Did you find a fix for it before closing the ticket?

**Comment by brandtnewww** [comment]
I have the same issue right now.

**Comment by MXLI88** [comment]
sorry for my outstanding.. 
solved this, by using view-shot instead.
