### ISSUE TITLE
Multiple markers with custom callout result in huge memory usage iOS

### ISSUE THREAD

**Issue by Sangrene** [react-community/react-native-maps#2412]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes
### Environment

"react": "16.3.1"
"react-native": "0.55.4"
"react-native-maps": "0.21.0"

Target Platform: iOS -- 10.3.3, iPhone 5S

### Steps to Reproduce

Render hundreds of markers with custom callouts on an iOS Google Maps.

### Expected Behavior

The map should render smoothly without any memory leak, just like on Android.

### Actual Behavior

When I add multiple `View` inside my callouts, the memory usage is starting to grow up until the out of memory error. The JS thread seems to be blocked as well.

### Reproducible Demo

```
renderCallout(name, food, price, distance){
  return(
    <Callout
    onPress={this.onPressShop}
    >
      <View>
        <View style={mapStyle.calloutView}>
          <View style={{marginRight: 10, maxWidth: 200}}>
            <Text
            numberOfLines={1}
            ellipsizeMode={"tail"}
            style={[globalStyle.style.h1, {fontFamily: globalStyle.fonts.AvertaBold, }]}>{name}</Text>
            <Text style={globalStyle.style.p}>{food+" - "+price}</Text>
          </View>
          <Text style={globalStyle.style.p}>{distance}</Text>
          <MaterialCommunityIcon name={'map-marker-radius'} size={20} color={globalStyle.colors.darkGray} />
          <Ionicon style={{marginLeft: 10}} name={"ios-arrow-forward"} size={18} color={globalStyle.colors.gray} />

        </View>
      </View>
    </Callout>
  );
}

renderMarker(shop, index){
  const markerImg = shop.state === 0 ? greenPoint : (shop.state === 1 ? orangePoint : redPoint);
  const markerZIndex = shop.state === 0 ? 3 : (shop.state === 1 ? 2 : 1);
  const lat = shop.LATITUDE;
  const lng = shop.LONGITUDE;
  const key = shop.ID.toString();
  const distance = formatDistance(shop.distance);
  const price = formatPriceRange(shop.PRICE_RANGE);
  const name = shop.NAME;
  const food = shop.FOOD;

  return (
    <Marker
    ref={(ref) => {
      this.markerRefs[index] = ref;
    }}
    zIndex={markerZIndex}
    key={key}
    anchor={{x: 0.5, y: 0.5}}
    coordinate={{latitude: lat, longitude: lng}}
    title={name}
    onPress={() => {
      this.onMarkerPress(shop, index);
    }}
    image={markerImg}
    >
      {this.renderCallout(name, food, price, distance)}

    </Marker>
  );
}
```

When I remove the first or second view of my callout, the issue does not happen.

Would appreciate any help on how to fix this, thanks :)

**Comment by Sangrene** [comment]
Workaround I found for this :
Don't render callout unless a marker is pressed (with a selected props for example).
When marker is pressed, call showCallout method with a small delay so the callout is updated.
When marker is not pressed I return an empty callout which height and width are calculated according to the width and height the callout would take when showed, otherwise it is shrinked.

Ugly workaround but it works without destroying the memory...

**Comment by rborn** [comment]
@Sangrene could you provide a small example and maybe close the issue? 
Tbh I found the "workaround" not so much a "workaround", hundreds of views are really a lot and we should avoid doing this 🤗

**Comment by Sangrene** [comment]
I'm on holidays atm, I'll add a small code snippet and close this issue in a few days ! 

I thought it was a workaround because of the delay I have to use to update the marker and callout, but it is related to other issues here.

**Comment by Sangrene** [comment]
Kinda late but here is my workaround.
You can use https://github.com/airamrguez/react-native-measure-text to measure text if you really need accuracy.

I have a function to render my callout and in it : 
```
if(this.props.selected){
  return(
    <Callout
    onPress={()=>this.onCalloutPress()}
    >
      <View>
        <View style={{flexDirection: "row",
        alignItems: "center",
        backgroundColor: "transparent"}}>
          <View style={{marginRight: 10, maxWidth: 200}}>
            <Text
            numberOfLines={1}
            ellipsizeMode={"tail"}
            style={[globalStyle.style.h1]}>{name}</Text>
            <Text style={globalStyle.style.p}>{food+" - "+price}</Text>
          </View>
          <Text style={globalStyle.style.p}>{distance}</Text>
          <MaterialCommunityIcon name={"map-marker-radius"} size={20} color={globalStyle.colors.darkGray} />
          <Ionicon style={{marginLeft: 10}} name={"ios-arrow-forward"} size={18} color={globalStyle.colors.gray} />

        </View>
      </View>
    </Callout>
  );
}else{
  return(
    <Callout
    tooltip
    >
      <View style={{height: 40}}>
        <Text style={[globalStyle.style.h1, {opacity: 0, marginRight: 90, maxWidth: 200}]}>{name}</Text>
      </View>
    </Callout>
  );
}
```
If not selected, my callout is only a small transparent view (setting height is important!) with a text and a margin to get the approx size of the selected callout. 

On my map, I have this prop
```
onMarkerPress={(e) => {
  const index = parseInt(e.nativeEvent.id, 10);
  this.onMarkerPress(index, {latitude: this.props.shops[index].LATITUDE, longitude: this.props.shops[index].LONGITUDE});
}}
```
Which call this function : 
```
onMarkerPress(index, coordinate){
  if(coordinate){
    this.map.animateToCoordinate(coordinate, 200);
    this.setState({selectedOfferIdx: 0, selectedShopIdx: index}, () => {
      if(this.markerRefs[index] !== null)
        this.markerRefs[index].showCallout();
    });
  }
}
```
You can see that I call the showCallout method on my marker, and here is the trick : 
```
showCallout(){
  if(this.props.selected){
    setTimeout(() => {
      if(this.marker !== null)
        this.marker.showCallout()
    }, 0);
  }
}
```
Without the small delay induced by setTimeout it won't work.

Note that I have a `selected` prop passed to my marker which make the marker to re-render as so `selected={index === this.state.selectedShopIdx}`.

This is overly complex but the only way I found to render as much marker as I want.
