### ISSUE TITLE
Xcode 9.4.1: Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by FlonTaut** [react-community/react-native-maps#2421]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.56.0
react: 16.4.1
react-native-maps: 0.21.0
Target Platform: iOS - 11.4 Simulator/iPhone 6

### Steps to Reproduce

Follow the Installation instructions.
When finished run: `react-native run-ios`

### Expected Behavior

App should start

### Actual Behavior

Im getting the following output
`Print: Entry, ":CFBundleIdentifier", Does Not Exist`

As I have read the installation instructions, this appears if Xcode below 9 is installed.
But im running Xcode 9.4.1
I need to say that im running the latest public beta of Mojave

Hopefully somebody can help me with this issue.

Thank you

**Comment by FlonTaut** [comment]
Sorry guys,
a missed an error which was written when running `pod install` fixed now.

**Comment by giovanicascaes** [comment]
Which was the error?

**Comment by jacek213** [comment]
I get no error when running `pod install` but get the same error as OP reported
