### ISSUE TITLE
There was an error React Native.(React-Native-Maps)

### ISSUE THREAD

**Issue by Yokoi-K** [react-community/react-native-maps#2447]
### I would like to draw a map using react-native-maps with react native. I succeeded at ios. However, Android gives an error.

The error contents are 「**The specified child already has a parent.You must call removeView() on the parent first.**」

I tried it a lot, but it will not work.

Does anyone fall into the same situation as I am?

Please let me know the solution.

**Comment by ChristopheHochP** [comment]
Hi @Yokoi-K, I am running into the same issue as you described. Did you found a solution to your problem?

**Comment by alvelig** [comment]
@ShrutiGarg019 remove all your in-marker components and try. Then go adding one by one and find which element. Let me know when found.
