### ISSUE TITLE
Invariant Violation requireNativeComponent "AirMap" was not found in the UIManager

### ISSUE THREAD

**Issue by 91debug** [react-community/react-native-maps#2449]
## Is this a bu g report?
Yes

## Have you read the Installation Instructions?
Yes

## Environment
- iOS 11.4
- react: 16.4.1
- react-native: ^0.56.0
- react-native-maps: ^0.21.0

This issue only occurs when running with the `react-native run-ios` command in IOS.
But it works well when running with Xcode `Product > Run`.

**Comment by Kennytian** [comment]
same here +1

**Comment by miteOrhan** [comment]
Could you fix that?

**Comment by rborn** [comment]
#2396  was merged, please test with the latest git version. 
Please keep in mind that you might have to setup the module again as now it works with `react-native link`
Read the install manual carefully

**Comment by amirkheirabadi** [comment]
I still have this problem.
`  "react-native-maps": "^0.21.0",`

**Comment by askielboe** [comment]
Managed to solve this by:

1) Adding newest commit to package.json: `"react-native-maps": "https://github.com/react-community/react-native-maps.git#1aee143302129f3811f1753155600bd041b5214d",` and then `yarn install`ing
2) Relinking the library using `react-native unlink react-native-maps && react-native link react-native-maps`
