### ISSUE TITLE
Module not found 

### ISSUE THREAD

**Issue by markib** [react-community/react-native-maps#2454]
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --mode development --watch --progress --hide-modules --config=./webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "web": "webpack --mode development  --config ./webpack.config.js  --inline --hot --colors --content-base public/index.php --history-api-fallback",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@babel/plugin-proposal-object-rest-spread": "^7.0.0-rc.1",
        "axios": "^0.18.0",
        "babel-loader": "^7.1.5",
        "babel-plugin-react-native-web": "^0.8.9",
        "babel-plugin-transform-decorators-legacy": "^1.3.5",
        "babel-plugin-transform-imports": "^1.5.0",
        "babel-plugin-transform-react-jsx-source": "^6.22.0",
        "babel-plugin-transform-runtime": "^6.23.0",
        "babel-preset-env": "^1.7.0",
        "babel-preset-react": "^6.24.1",
        "babel-preset-react-native": "^4.0.0",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1",
        "css-loader": "^1.0.0",
        "file-loader": "^1.1.11",
        "jquery": "^3.2",
        "laravel-mix": "^2.1.11",
        "lodash": "^4.17.4",
        "react": "^16.4.1",
        "react-dom": "^16.4.1",
        "redux-logger": "^3.0.6",
        "style-loader": "^0.22.1",
        "webpack": "^4.16.5",
        "webpack-cli": "^3.0.8",
        "webpack-dev-server": "^3.1.4",
        "webpack-dev-middleware": "^3.1.3"
    },
    "dependencies": {
        "babel-core": "^6.26.3",
        "babel-runtime": "^6.26.0",
        "prop-types": "^15.6.2",
        "react-art": "^16.4.2",
        "react-native": "^0.55.4",
        "react-native-collapsible": "^0.13.0",
        "react-native-i18n": "^2.0.15",
        "react-native-maps": "^0.21.0",
        "react-native-router-flux": "^4.0.1",
        "react-native-tab-view": "^1.0.2",
        "react-native-vector-icons": "^5.0.0",
        "react-native-web": "^0.8.9",
        "react-navigation": "^2.11.2",
        "react-redux": "^5.0.7",
        "redux": "^4.0.0",
        "redux-saga": "^0.16.0"
    }
}

### Steps to Reproduce

while compile
(Write your steps here:)

1. 2. 3.

### Expected Behavior

import type { ResolvedAssetSource } from 'AssetSourceResolver';
(Write what you thought would happen.)

### Actual Behavior

Module not found: Error: Can't resolve 'react-native/Libraries/Image/resolveAssetSource'
(Write what happened. Add screenshots!)

### Reproducible Demo

ERROR in ./node_modules/react-native-maps/lib/components/MapOverlay.js
Module not found: Error: Can't resolve 'react-native/Libraries/Image/resolveAssetSource'
(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment]
@markib  it's a react-native project? or react-native-web?

**Comment by markib** [comment]
react-native-web

**Comment by rborn** [comment]
This module doesn't support react-native-web as far as I know, see  https://github.com/react-community/react-native-maps/issues/2106
Closing
