### ISSUE TITLE
Android compiling error. minSDK property should be removed from manifest.

### ISSUE THREAD

**Issue by dkfl1995** [react-community/react-native-maps#2471]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react": "16.4.2"
"react-native": "0.56.0"
"react-native-maps": "0.21.0"

### Steps to Reproduce

(Write your steps here:)

Android only!
When upgrading to newer gradle wrapper package versions that works with buildtools version 28+, error comes up if uses-sdk tag has "minSDK" property defined inside AndroidMainfest.xml file. Default SDK properties should stand only inside build.gradle files.

My steps to reproduce is to try to compile react-native in Android Studio with: 
1. gradle-wrapper package version in gradle-wrapper.properties:
  ` distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-all.zip`
2. App`s build.gradle file buildToolsVersion 28.0.2.
3. Gradle plugin version I used (the newest at that time): 
`dependencies { 
           classpath 'com.android.tools.build:gradle:3.3.0-alpha08'
   }`

You will receive an gradle sync error: 

> Error:The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by tigranbalayan** [comment]
Have the same issue

**Comment by dkfl1995** [comment]
@tigranbalayan  you can use tempopary solution fixed on forked repo.
`    "react-native-maps": "github:dkfl1995/react-native-maps#master",
`

**Comment by tigranbalayan** [comment]
@dkfl1995  thanks bro, but I need solution from here and I believe that your PR would be merged.

**Comment by rborn** [comment]
https://github.com/react-community/react-native-maps/pull/2472 merged, closing

**Comment by rendomnet** [comment]
@rborn I have 0.21 version and this error exist
