### ISSUE TITLE
How to set fontFamily for custom Marker Text ?

### ISSUE THREAD

**Issue by bashirpour** [react-community/react-native-maps#2474]
### How to set fontFamily for custom Marker Text ??

    <Marker
        coordinate={{ 
            ...
         }}
        onPress={...} 
    >

        <ImageBackground
            ...
        >

            <Text style={{fontFamily: "SansMobile"}}>   // <---- this line
                this.props.pointCount
            </Text>

        </ImageBackground>
    </Marker>

**Comment by rborn** [comment]
No issue template, closing
