### ISSUE TITLE
customMapStyle doesn't work Android

### ISSUE THREAD

**Issue by Luckygirlllll** [react-community/react-native-maps#2475]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)
YES

### Environment
react-native: 0.55.1
 react-native-maps: "^0.21.0"

### Steps to Reproduce

(Write your steps here:)

```
mapStyle = [
    {
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#041826"
        }
      ]
    },

 <MapView
          customMapStyle={[this.mapStyle]}
          provider={PROVIDER_GOOGLE}
         region={{
           latitude: 37.78825,
           longitude: -122.4324,
           latitudeDelta: 0.015,
           longitudeDelta: 0.0121,
         }}
       >
       </MapView>
```

### Expected Behavior

(Write what you thought would happen.)
See map with the custom style 

### Actual Behavior

I see blank white screen 

(Write what happened. Add screenshots!)

If I'm using style={styles.map} 
map: {
    ...StyleSheet.absoluteFillObject,
  }  I see the map with default style, so maybe I need add to the custom style ...StyleSheet.absoluteFillObject? But how to do that? Is that possible to convert  ..StyleSheet.absoluteFillObject to json object and add it to the custom style?

**Comment by KacperKurek** [comment]
mapStyle and styles for component are different objects. You pass array mapStyle in array
`customMapStyle={[this.mapStyle]}` convert to `customMapStyle={this.mapStyle}`.
Here is my working solution for your problem https://snack.expo.io/Sydc97-dX

**Comment by rborn** [comment]
Closing as per https://github.com/react-community/react-native-maps/issues/2475#issuecomment-419633237. Please fell free to open anew one if you still have issues
