### ISSUE TITLE
Sporadic Polylines

### ISSUE THREAD

**Issue by ecjs** [react-community/react-native-maps#248]
![khqhl9sfqz](https://cloud.githubusercontent.com/assets/8406471/15488427/fa9c2602-210a-11e6-806d-8fad004380e7.gif)

Has anyone else noticed this issue with polylines... where at certain zooms they draw funny?  I am generating them via Google APIs, and I have seen it on quite a few polylines I have generated over the past few months.

**Comment by jrichardlai** [comment]
@ecjs I noticed this sometimes too, not sure what's the issue. Could not find something about this on google, the implementation of the Polyline is really basic.

**Comment by muzix** [comment]
I got this issue yesterday, change lineCap and lineJoin to 'round' will fix it.

**Comment by Roconda** [comment]
I've encountered this issue as well
<img width="318" alt="screenshot 2016-06-22 14 17 29" src="https://cloud.githubusercontent.com/assets/1711132/16266242/1b1c2054-3884-11e6-98d1-a07e8c9fda8d.png">

**Comment by jrichardlai** [comment]
@Roconda did changing lineCap and lineJoin helped ?

**Comment by Roconda** [comment]
@jrichardlai I'll try to reproduce and let you know. The bug doesn't show up most of the time.

**Comment by agrass** [comment]
I'm with the same problem.  @muzix , 'round' it's not supposed to be the default value of lineCap?

**Comment by nbiocani** [comment]
What do you mean by 'round'?
This is my problem:
<img width="346" alt="screen shot 2017-05-04 at 2 55 10 pm" src="https://cloud.githubusercontent.com/assets/20321363/25704454/cac8ce78-30d9-11e7-8246-0414c7a5ea97.png">

**Comment by mattijsf** [comment]
Confirmed. Had the same visual artifact and adding
```swift
<MapView.Polyline ... lineCap="round" lineJoin="round" />
```
Fixes it. 

`round` should be the default `lineCap` / `lineJoin` value if you ask me.

**Comment by Nualiian** [comment]
well in the [docs](https://github.com/airbnb/react-native-maps/blob/master/docs/polyline.md), `lineCap` is specified to be `round` by default indeed and `lineJoin` is supposed to be an `Array<LatLng>`

**Comment by jerome-chen** [comment]
@mattijsf, you saved my day!
