### ISSUE TITLE
API Level 26 - Runtime Permissions

### ISSUE THREAD

**Issue by imzeeshan** [react-community/react-native-maps#2482]
The new google app publishing guidelines state that the location permissions needs to be handled at the UI side - https://developer.android.com/distribute/best-practices/develop/target-sdk 

Also see https://facebook.github.io/react-native/docs/permissionsandroid.html

Is this going to be supported or WIP already ?

**Comment by rborn** [comment]
Permissions are handled outside the lib as far as I know: https://github.com/react-community/react-native-maps/blob/72b0f77e31d18959e91acb036d5f91ab46e11ef2/example/examples/MyLocationMapMarker.js#L55
Anyway, I'll close the issue as it doesn't respect the template.
