### ISSUE TITLE
API key not found, although using custom tiles (OSM)

### ISSUE THREAD

**Issue by seco35** [react-community/react-native-maps#2486]
### Is this a bug report?

No (I guess)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.55.4
react: 16.3.1
react-native-maps: 16.3.1

Android 28 (Emulator)

### Steps to Reproduce

Installing with the steps in the instructions with react-native-link.

### Expected Behavior

Using custom tiles (OSM) and seeing the map instead of an error for missing Google API Key.

EDIT: Copy+pasted following lines without an actual API Key. No Error messages seems to appear. I have a gray map with google's label at the left bottom corner. It tries to get the tiles from google I guess (hmm). 

### Actual Behavior

Error: 

API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml

**EDIT: ON iOS I'm getting following error message:
Invariant Violation: Native component for "AIRMapUrlTile" does not exist**

### Reproducible Demo

```
      ...
       this.state= {
            urlTemplate: 'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png'
        }
       ....
     <MapView
                region={{latitude: 48.117949,longitude: 7.853377,latitudeDelta: 0.0922,longitudeDelta: 0.0421,}}
                provider={null}
                rotateEnabled={false}
                style={{flex: 1}}
                mapType={"none"}
                showsUserLocation >
                    <MapView.UrlTile urlTemplate={this.state.urlTemplate} />
               </MapView>

```

**Comment by rborn** [comment]
@seco35  Custom tiles will still load google lib in the background so you need an api key to work.

**Comment by seco35** [comment]
> 
> 
> @seco35 Custom tiles will still load google lib in the background so you need an api key to work.
Will add an API Key later, thank you. What is the problem with iOS though? Getting an error message for a missing native component of "AIRMapUrlTile"?
