### ISSUE TITLE
Invariant violation: Native component for 'AirMapr' does not exist

### ISSUE THREAD

**Issue by Uzairrrr** [react-community/react-native-maps#2489]
my version details...
![screen shot 2018-09-14 at 5 08 33 pm](https://user-images.githubusercontent.com/23259529/45549344-ed182380-b840-11e8-9954-2f7020defec9.png)
i followed this link
https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14
and my error is
![screen shot 2018-09-14 at 5 10 03 pm](https://user-images.githubusercontent.com/23259529/45549380-0caf4c00-b841-11e8-8410-ac2917161014.png)
Help me for IOS

**Comment by Uzairrrr** [comment]
@MingyuJeon thanks for reply but i succedded 
by following this link
https://github.com/rborn/react-native-maps-pods-example
react-native version :0.50.4
react-native-maps: 0.20.1

**Comment by Uzairrrr** [comment]
I am closing this issue as i resolved react-native-maps in ios

**Comment by leugimmai** [comment]
@MingyuJeon Finally got this working on iOS. Thank You so much!
