### ISSUE TITLE
App crashes when using Firebase and react-native-maps

### ISSUE THREAD

**Issue by SrihariThalla** [react-community/react-native-maps#249]
Here is the stacktrace:

```
FATAL EXCEPTION: main
  Process: com.example, PID: 9308
  java.lang.NoSuchMethodError: No virtual method zztU()Lcom/google/android/gms/dynamic/LifecycleDelegate; in class Lcom/google/android/gms/maps/MapView$zzb; or its super classes (declaration of 'com.google.android.gms.maps.MapView$zzb' appears in /data/app/com.example-2/base.apk)
    at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
    at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
    at com.google.android.gms.dynamic.zza.zza(Unknown Source)
    at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
    at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
    at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:70)
    at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:67)
    at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:26)
    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:205)
    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
    at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:760)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:830)
    at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
    at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:549)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5264)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

P.S. I used manual installation, a.k.a. the `com.airbnb.android.react.maps.MapsPackage` and not via `com.AirMaps.AirPackage`. I've tried v0.4.2 and v0.5.0

**Comment by SrihariThalla** [comment]
BTW, these are the things I needed to add to Gradle files: https://firebase.google.com/docs/android/setup

I've added `core` and `messaging` libraries.

**Comment by jrichardlai** [comment]
Which version of `com.google.android.gms:play-services-maps` and `com.google.android.gms:play-services-base` are you using ?

**Comment by BigPun86** [comment]
+1

**Comment by SrihariThalla** [comment]
@jrichardlai I've installed Google Play Services version 30. But I didn't include them in any of my Gradle files.

**Comment by mikelambert** [comment]
@jrichardlai This exact same error happens to me too. Except I am using the NPM, `rnpm link` and so therefor am pulling in the react-native-maps' gradle file with these versions:
```
    compile "com.google.android.gms:play-services-base:8.4.0"
    compile 'com.google.android.gms:play-services-maps:8.4.0'
```

The only additional lines added were:
```
compile 'com.google.firebase:firebase-core:9.0.0'
```

alongside this additional magical plugin:
```
apply plugin: 'com.google.gms.google-services'
```
(which I assume comes from `classpath 'com.google.gms:google-services:3.0.0'`, and I believe does some magic around parsing google-services.json and making that data available downstream)

Unfortunately, it's not entirely clear to me what these dependencies and versions are doing under the hood.

**Comment by bendellarocco** [comment]
+1
I am not seeing this on debug but I am seeing this on release.

**Comment by kitolog** [comment]
+1 Firebase + RNM crashes android

**Comment by mikelambert** [comment]
Okay, figured it out. This in an incompatibility between Google Play Services 8.4 and Firebase 9.0 (ideally, they should probably be kept on the same version). The trick is to stop including version 8.4 and instead include your desired version 9.0)

My gradle ended up looking like this, though you will most likely need to understand what is going on in the below snippet to adapt it for your purposes.

```
dependencies {
    compile (project(':react-native-admob')) {
        // exclude version 8.+
        exclude group: 'com.google.android.gms', module: 'play-services-ads'
    }

    compile (project(':react-native-maps')) {
        // exclude version 8.4
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

    // include whatever firebase packages we want:
    compile 'com.google.firebase:firebase-core:9.0.0'

    // Now re-include an up-to-date version of the packages we excluded above.
    // I believe these basically need to match what we do with firebase, to make things work again
    compile 'com.google.android.gms:play-services-base:9.+'
    compile 'com.google.android.gms:play-services-maps:9.+'
    compile 'com.google.android.gms:play-services-ads:9.+'
}

// Note we must specify an exact version above for firebase, so that the below will work.
// If we specify a '9.+' or '9.0.+' version above, this will error:
apply plugin: 'com.google.gms.google-services'

**Comment by mikelambert** [comment]
A proper "fix" to work with Firebase, would be to upgrade react-native-maps' dependencies to version 9.0.2 (or whatever the latest version of firebase is).

But I only use a tiny bit of maps functionality (basically a static map), and so cannot verify that such a major revision change doesn't break any of the react-native-maps functionality/apis, and am not comfortable submitting such a pull request.

**Comment by bendellarocco** [comment]
I required 9.2+ of play-services-maps and still receive this crash.

**Comment by mikelambert** [comment]
@bendellarocco , have you guaranteed that the version of firebase and play-services-XXX you include are all consistent? Can you share a link to your gradle?

**Comment by bendellarocco** [comment]
@mikelambert So Debugged a bit more and it's not firebase related. All our firebase and geofire calculations and requests are done on our sever. The front end is only getting the reply. I removed all of that code and I get that error just loading a standard map with a hard coded latitude and longitude.

**Comment by mikelambert** [comment]
I continue to believe it's an incompatibility when loading different versions of the google-play libraries. (due to firebase, or perhaps something else you depend on). You haven't shared your gradle file, so there's not really much more I can suggest.

**Comment by bendellarocco** [comment]
My last comment was sent from a mobile device.
``android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.masstuning"
        minSdkVersion 21
        targetSdkVersion 23
        versionCode 16
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                                onesignal_app_id: "fdf3e6f0-8620-4db5-8ad4-099c0e649506",
                                onesignal_google_project_number: "976220226607"]
    }
    
    signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            //minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    packagingOptions {
        exclude 'META-INF/license.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/DEPENDENCIES'
    }
}

configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-ads:9.2.0+'
    force "com.google.android.gms:play-services:9.2.0+"
    force "com.google.android.gms:play-services-location:9.2.0+"
    force "com.google.android.gms:play-services-maps:9.2.0+"
  }
}

dependencies {
    compile project(':react-native-admob')
    compile project(':react-native-lock')
    compile project(':react-native-vector-icons')
    compile project(':react-native-maps')
    compile project(':react-native-mail')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-image-picker')
    compile project(':react-native-onesignal')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
  into 'libs'
}

**Comment by mikelambert** [comment]
Ahh I haven't seen resolutionStrategy { ... } before, sounds like you're sure this does the same thing as my exclude group rules?

Regardless, you seem to have forgotten play-services's gcm and analytics, which appear to pull the latest version when you use https://github.com/geektimecoil/react-native-onesignal/blob/master/android/build.gradle , and might end up in conflict with the 9.2.0+ version choice you force elsewhere?

**Comment by bendellarocco** [comment]
I was able to get the map running.  This was my final gradle dependencies 
```
configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-ads:9.2.0+'
    force "com.google.android.gms:play-services:9.2.0+"
    force "com.google.android.gms:play-services-location:9.2.0+"
    force "com.google.android.gms:play-services-maps:9.2.0+"
    force "com.google.android.gms:play-services-gcm:9.2.0+"
    force "com.google.android.gms:play-services-analytics:9.2.0+"
  }
}

dependencies {
    compile project(':react-native-admob')
    compile project(':react-native-lock')
    compile project(':react-native-vector-icons')
    compile project(':react-native-maps')
    compile project(':react-native-mail')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-image-picker')
    compile project(':react-native-onesignal')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules

}
```

**Comment by simlmx** [comment]
I had a similar issue (react-native-maps + firebase apparently clashing) and this thread helped me fix it, so I thought I'd share.
So basically when I added firebase, my app would crash with "Unfortunately, MyApp has stopped.".
I simple added
`compile 'com.google.android.gms:play-services-maps:9.2.1'`
to my
`android/app/build.gradle`
and it magically fixed it.

**Comment by KGALLET** [comment]
thx @simlmx

**Comment by julien-rodrigues** [comment]
@bendellarocco suggestion worked perfectly for me 👍

**Comment by diogopalhais** [comment]
This config is working for me

`configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-ads:9.2.0+'
    force "com.google.android.gms:play-services:9.2.0+"
    force "com.google.android.gms:play-services-location:9.2.0+"
    force "com.google.android.gms:play-services-maps:9.2.0+"
    force "com.google.android.gms:play-services-gcm:9.2.0+"
    force "com.google.android.gms:play-services-analytics:9.2.0+"
  }
}

dependencies {
    compile project(':react-native-admob')
    compile project(':react-native-vector-icons')
    compile project(':react-native-share')
    compile project(':react-native-maps')
    compile project(':react-native-extra-dimensions-android')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}`

**Comment by shivekkhurana** [comment]
I tried everything, didn't work.

Then I came across this PR : https://github.com/airbnb/react-native-maps/pull/731/commits

I moved react-native-maps out of node_modules, put it in src folder, made the changes as in above PR, changed settings.gradle and now it works.

**Comment by highlabs** [comment]
Little update:

I'm was using the old version of react-native-maps (0.11.0) with Firestack (https://github.com/fullstackreact/react-native-firestack).

I updated to new version (0.12.4) and it's works. :)

**Comment by sreejithraman** [comment]
@simlmx thanks, that seems like it did the trick. any idea why this works?

**Comment by tonyhb** [comment]
This is an exception with play services; adb logcat shows:

```
--------- beginning of crash
05-04 17:26:04.156  3201  3201 E AndroidRuntime: FATAL EXCEPTION: main
05-04 17:26:04.156  3201  3201 E AndroidRuntime: Process: co.cvstom.pearl, PID: 3201
05-04 17:26:04.156  3201  3201 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method zzBM()Lcom/google/android/gms/dynamic/LifecycleDelegate; in class Lcom/google/android/gms/maps/MapView$zzb; or its super classes (declaration of 'com.google.android.gms.maps.Ma
pView$zzb' appears in /data/app/co.cvstom.pearl-1/base.apk)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.google.android.gms.maps.MapView$zzb.zzJy(Unknown Source)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.google.android.gms.dynamic.zza.zza(Unknown Source)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:126)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:62)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
05-04 17:26:04.156  3201  3201 E AndroidRuntime:        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
```

This project now uses Google Play Services 0.10.2, so the following in your `android/app/build.gradle` should work:

```
configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-ads:10.2.0+'
    force "com.google.android.gms:play-services:10.2.0+"
    force "com.google.android.gms:play-services-location:10.2.0+"
    force "com.google.android.gms:play-services-maps:10.2.0+"
    force "com.google.android.gms:play-services-gcm:10.2.0+"
    force "com.google.android.gms:play-services-analytics:10.2.0+"
  }
}

dependencies {
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile "com.google.android.gms:play-services-base:10.2.0"
    compile "com.google.android.gms:play-services-maps:10.2.0"
    // other deps
}
```

**Comment by sergiofraile** [comment]
None of this has worked for me, but finally this did the trick.

On your android/app/build.gradle, just place above your dependencies:

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'com.google.android.gms' 
            && ( (details.requested.name == 'play-services-base') || (details.requested.name == 'play-services-maps') ) ) {            
            details.useVersion '11.0.2'
        }
    }
}
```

**Comment by redwind** [comment]
For anyone still get this error when using react-native-maps & react-native-firebase together.This is my build.gradle:
`dependencies {
    compile project(':react-native-fast-image')
    compile project(':react-native-text-input-reset')
    compile project(':react-native-google-place-picker')
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    
    compile (project(':react-native-device-info')){
        exclude group: "com.google.android.gms" 
    }
   
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    
    compile ('com.google.android.gms:play-services-location:11.+'){
        force = true;
    }
    
    // Firebase dependencies
    compile ("com.google.firebase:firebase-core:11.+")
    // RNFirebase optional dependencies
    
    compile ("com.google.firebase:firebase-crash:11.+"){
        force = true;
    }
    compile ("com.google.android.gms:play-services-base:11.+")
    compile ('com.google.android.gms:play-services-maps:11.+')
    compile project(':react-native-onesignal')
    compile project(':react-native-push-notification')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-facebook-account-kit')
    compile project(':react-native-splash-screen')
    compile project(':react-native-fs')
    compile project(':react-native-sound')
    compile project(':react-native-audio')
    compile project(':react-native-image-resizer')
    compile project(':bugsnag-react-native')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-share')
    compile project(':react-native-contacts')
    compile 'com.facebook.android:facebook-android-sdk:4.22.1'
    compile project(':react-native-vector-icons')
    compile project(':react-native-config')
    compile project(':react-native-code-push')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
}`

**Comment by esutton** [comment]
@redwind Thank you for posting.  Changing to **11.+** prevented the crash.  When app launched  user was prompted to update Google Play services when app launched.

I was using **11.4.2** and app crashed at start due to a firebase gms dependency.

I see current version is [11.7.44](https://google-play-services.en.uptodown.com/android).  
No sure if  **11.+** is going to cause user Google Play update anxiety or not?

/android/app/build.gradle
````
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    // Firebase dependencies
    // https://rnfirebase.io/docs/v3.0.*/installation/android
    compile "com.google.android.gms:play-services-base:11.+"
    compile 'com.google.android.gms:play-services-maps:11.+'

    compile "com.google.firebase:firebase-core:11.+"
    compile "com.google.firebase:firebase-analytics:11.+"
    compile "com.google.firebase:firebase-messaging:11.+"    
````

My crash when using **11.4.2** : Lcom/google/android/gms/common/internal/zzbp
````
11-08 10:12:36.650  2431  2431 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-08 10:12:36.651  2431  2431 E AndroidRuntime: FATAL EXCEPTION: main
11-08 10:12:36.651  2431  2431 E AndroidRuntime: Process: com.ditchwitch.fieldscout, PID: 2431
11-08 10:12:36.651  2431  2431 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbp; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbp' appears in /data/app/com.ditchwitch.fieldscout-2/base.apk)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-08 10:12:36.651  2431  2431 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-08 10:12:36.652   569   581 W ActivityManager:   Force finishing activity com.ditchwitch.fieldscout/.MainActivity
11-08 10:12:36.811  1194  1534 I Icing   : Indexing A3DEDC2945BD6907C295655A2388D7A2702EF393 from com.google.android.gms
````

**Comment by redwind** [comment]
@esutton : what's device you test ? i run on my samsung gallaxy J7 and it doesn't promt for update GooglePlay service :)

**Comment by esutton** [comment]
@redwind I was using a Genymotion x86 simulator of a Google nexus 5, 6.00, API23

Maybe the update had something to do with the x86 "GApps" versions that Genymotion installs?

**Comment by redwind** [comment]
@esutton as i known, Genymotion doesn't include google play service by default, so maybe that cause your issue. Try to install into real device :)

**Comment by pisangGoreng** [comment]
Hi.. im using react-native-maps & react-native-firebase. When im running react-native run-android. my app is success to build, but the app has stopped
![whatsapp image 2017-11-26 at 11 25 43 pm](https://user-images.githubusercontent.com/23170091/33242055-48f99236-d301-11e7-8fc9-78efd77a58be.jpeg)

this is my gradle 
`dependencies {
    compile project(':react-native-device-info')
    compile (project(':react-native-notifications')) {
        exclude group: 'com.google.android.gms'
    }
    compile project(':react-native-maps')
    compile project(':react-native-google-places')
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-facebook-login')
    compile project(':react-native-picker')
    compile (project(':react-native-maps')) {
        exclude group: 'com.google.android.gms'
    }
    compile (project(':react-native-google-places')) {
        exclude group: 'com.google.android.gms'
    }
    compile project(':react-native-config')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    // compile 'com.google.android.gms:play-services:11.4.2'

    compile (project(':react-native-facebook-login')) {
        exclude group: 'com.facebook.android'
    }
    compile "com.google.android.gms:play-services-base:11.6.0"
    compile "com.google.firebase:firebase-core:11.6.0"
    compile "com.google.firebase:firebase-messaging:11.6.0"
    compile "com.google.firebase:firebase-analytics:11.6.0"
    compile ("com.google.android.gms:play-services-gcm:11.6.0") {
        force = true
    }
    compile ("com.google.android.gms:play-services-maps:11.6.0") {
        force = true
    }
    compile ("com.google.android.gms:play-services-location:11.6.0") {
        force = true
    }
    compile ("com.google.android.gms:play-services-places:11.6.0") {
        force = true
    }
    compile 'com.facebook.android:facebook-android-sdk:4.20.0'
}`

im using "react-native": "^0.47.2", "react-native-maps": "^0.16.4", "react-native-firebase": "^3.1.0".

Anyone have idea to solve this? thanks

**Comment by kesha-antonov** [comment]
+1

**Comment by alvelig** [comment]
See https://github.com/react-community/react-native-maps/issues/1773#issuecomment-351122033

**Comment by nkov** [comment]
I got this error when adding `firebase-ads:11.6.0`. Only solution was to upgrade all firebase components to `11.8.0`

**Comment by 95deepan** [comment]
I am getting this issue in iOS since react-native-firebase does not support !user_frameworks! and react-native-maps require !use_frameworks!

Can anyone help me?

**Comment by rborn** [comment]
@95deepan  Where do you see in the https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#ios---cocoapods  ` !use_frameworks!` ?
