### ISSUE TITLE
Map is setting to initial region after we drag.

### ISSUE THREAD

**Issue by Mahaswami** [react-community/react-native-maps#2494]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES
### Environment
IOS

### Steps to Reproduce

 1. I have followed the installation instructions and using Mapview as shown below.
 2.   <MapView style={this._mapHeight()}
                             provider={PROVIDER_GOOGLE}
                             region={this.state.mapRegion}
                             onRegionChange={this._handleMapRegionChange}
                             showsUserLocation = {true}
                             showsCompass={false}
                             showsMyLocationButton = {false}
                    > 

3. When ever I drag the map UI to different region it is setting back to old region which shown initially.

4. Even though I change region map to new lat and long map fixes to old region which appeared as soon as loaded.
### Expected Behavior

Since I am using a region if change the state variable of region to new region map should update to the new updated region
### Actual Behavior

Even though I am changing the state of region map is not updating it stays in initial region.

**Comment by Mahaswami** [comment]
Sorry this is some other issue.

**Comment by edoantonioco** [comment]
How did you fix it? I can change the marker to some other place but I cant change the initialRegion to the same place where the marker was moved.
