### ISSUE TITLE
Feature: liteMode support on iOS via MKMapSnapshotter?

### ISSUE THREAD

**Issue by mgcrea** [react-community/react-native-maps#2497]
Have you considered using [MKMapSnapshotter](https://developer.apple.com/documentation/mapkit/mkmapsnapshotter) as a `liteMode` for iOS ? I've seen that there is a [AIRMapSnapshot.h](https://github.com/react-community/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapSnapshot.h) file in the project?

Thanks for the great lib!

**Comment by mgcrea** [comment]
@rborn Does feature request really need an issue template? Only relevant lines I could find were:

```
### Is this a bug report?
NO
```

Is it what is required?

**Comment by rborn** [comment]
@mgcrea feel free to open a template that included feature requests 😉
