### ISSUE TITLE
Maps doesnt render in release mode

### ISSUE THREAD

**Issue by isaaclem** [react-community/react-native-maps#2499]
### Is this a bug report?
Nope I believe

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment

    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-maps": "^0.21.0",

  Target Platform: Android

### Issues
I've been using Google Maps API in debug mode and working fine all along until it's in Release mode. Correct me if I'm wrong, we need a separated API key for Google Maps if we wished to release our app.

![screen shot 2018-09-20 at 6 24 49 pm](https://user-images.githubusercontent.com/32945572/45813242-a628a300-bd04-11e8-93f5-e3c6b274ddb1.png)

I've done the following:

- Created new API key
- enabled billing account in my project at GCP

In order to extract the `SHA-1` key, I've navigated to `project/android/app` where I can see `myapp.keystore` and run the command `keytool -list -v -keystore mypp.keystore`.

After created the API_KEY, I've navigated to `project/android/app/src/main/AndroidManifest.xml` and modify the key
```
  <meta-data
    android:name="com.google.android.geo.API_KEY"
    android:value="xxxxxx"/>
```
What else could've been missing? Thanks in advance

**Comment by geekazoid-at** [comment]
I could only get mine to work without setting an application restriction, i.e. not limiting it to a package name + fingerprint tuple. Would be interested in a solution too, but at least it works in release mode now.

**Comment by isaaclem** [comment]
@geekazoid-at Let's say we don't set any Application Restrictions, logically speaking this API-KEY should be working in both release and debug mode right? Reason is we can't specify in what mode the API-KEY is for

**Comment by geekazoid-at** [comment]
Yes, it works for me like this. I have no restriction set and I am using it for both debug and release, as it seems.
