### ISSUE TITLE
Error on Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

### ISSUE THREAD

**Issue by adispartadev** [react-community/react-native-maps#2502]
I have want to showing a map, and this error always showing.. I tried to delete my node_modules and run `yarn install` and it's didn't work
![image](https://user-images.githubusercontent.com/16744864/45866441-6a004b80-bdb3-11e8-90d0-9e92bb40e155.png)

How to fix this? 

"react": "16.5.0",
"react-native": "0.56.0",
"react-native-maps": "^0.21.0",

**Comment by shivhg** [comment]
adding this in build.gradle worked for me

```
 implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-base:12.0.0'
    implementation 'com.google.android.gms:play-services-maps:12.0.0'
```

**Comment by sujaygchand** [comment]
> adding this in build.gradle worked for me
> 
> ```
>  implementation(project(':react-native-maps')){
>         exclude group: 'com.google.android.gms', module: 'play-services-base'
>         exclude group: 'com.google.android.gms', module: 'play-services-maps'
>     }
>     implementation 'com.google.android.gms:play-services-base:12.0.0'
>     implementation 'com.google.android.gms:play-services-maps:12.0.0'
> ```

Dude, you are a life saver 

Add that to the build.gradle in the app folder.

**Comment by haffjjj** [comment]
> adding this in build.gradle worked for me
> 
> ```
>  implementation(project(':react-native-maps')){
>         exclude group: 'com.google.android.gms', module: 'play-services-base'
>         exclude group: 'com.google.android.gms', module: 'play-services-maps'
>     }
>     implementation 'com.google.android.gms:play-services-base:12.0.0'
>     implementation 'com.google.android.gms:play-services-maps:12.0.0'
> ```

thanks dude :)

**Comment by lordmaul** [comment]
What a life saver. Thanks

**Comment by jrwpatterson** [comment]
awesome cheers

**Comment by mauricio-msp** [comment]
>  adding this in build.gradle worked for me
> 
>      implementation(project(':react-native-maps')){
>             exclude group: 'com.google.android.gms', module: 'play-services-base'
>             exclude group: 'com.google.android.gms', module: 'play-services-maps'
>         }
>         implementation 'com.google.android.gms:play-services-base:12.0.0'
>         implementation 'com.google.android.gms:play-services-maps:12.0.0'

I put this inside dependencies in the app / build.gradle directory?

**Comment by tinymobile** [comment]
Where in the build.gradle file does this go?

I get this error:

Could not find method implementation() for arguments [project ':react-native-maps', build_9w9nrzhnzmham0vilfwjnmvgy$_run_closure1$_closure8@4fc27b76] on object of type com.android.build.gradle.AppExtension.

**Comment by areeb111** [comment]
Update your react-native-maps (build.gradle) file to the following versions:
`
def DEFAULT_COMPILE_SDK_VERSION             = 27
def DEFAULT_BUILD_TOOLS_VERSION             = "27.0.3"
def DEFAULT_TARGET_SDK_VERSION              = 27
def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION    = "16.0.0"
def DEFAULT_ANDROID_MAPS_UTILS_VERSION      = "0.5+"
`

After changing your project Compile SDK and Build Tools version to 27 too.

**Comment by marcojr** [comment]
After applied this fix, I receive an API KEY NOT FOUND. Do I really need API key for react-native-maps ?

Running on IOS I don't need such key ! and it's works nice. I just want to display a map on the screen.

**Comment by bhaveshrao96** [comment]
![bg 1](https://user-images.githubusercontent.com/48318303/53967059-82beac80-411a-11e9-9890-d34be9f6c5a0.PNG)
![bg 2](https://user-images.githubusercontent.com/48318303/53967070-83efd980-411a-11e9-899a-3221919e6a3b.PNG)


these are the error and the place where i think error is so plz help

**Comment by KarinGarciaZ** [comment]
@shivhg Thanks!
I just had to vhange the version of this:
`implementation 'com.google.android.gms:play-services-base:12.0.0'`
`implementation 'com.google.android.gms:play-services-maps:12.0.0'`
