### ISSUE TITLE
Invisible button with "back" behavior

### ISSUE THREAD

**Issue by Cyberuben** [react-community/react-native-maps#2504]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

`react-native: "0.55.4"`
`react: "16.4.1"`
`react-native-maps: "0.21.0"`
`react-navigation: "2.13.0"`

### Steps to Reproduce

1. Create a regular stack navigator using `react-navigation`
2. Create a `MaterialTopBar` navigator within another screen
3. Include a `MapView` within a random tab
4. Click on the left top of the map, you'll be moved back

### Expected Behavior

Render a very basic map, nothing else.

### Actual Behavior

It seems to place an invisible button, that when pressed, moves back to the previous activity. I'm using react-navigation, but it doesn't show up when rendering another view instead of the map. Switching around the tabs doesn't work either, as it just makes the button show up on the map on another tab.

![image](https://user-images.githubusercontent.com/1823121/45896766-65e52580-bdd5-11e8-8dbe-0b4b3484b2ae.png)

### Reproducible Demo

I'm unable to properly get this running on https://snack.expo.io (getting errors and the device is very unresponsive), so I'm pasting the part of the code I'm having issues with here. I stripped all my own logic, that is further not needed to reproduce the steps.

```
import React, { Component } from "react";
import { View, StyleSheet } from "react-native";
import PropTypes from "prop-types";
import MapView from "react-native-maps";

class MapScreen extends Component {
	constructor(props) {
		super(props);
	}

	calculateDelta(latitude, longitude, zoom) {
		const oneDegreeOfLatitudeInMeters = 111.32 * 1000;
		const latitudeDelta = zoom / oneDegreeOfLatitudeInMeters;
		const longitudeDelta = zoom / (oneDegreeOfLatitudeInMeters * Math.cos(latitude * (Math.PI / 180)));

		return {
			latitude,
			longitude,
			latitudeDelta,
			longitudeDelta
		};
	}

	render() {
		return (
			<View style={{ ...StyleSheet.absoluteFillObject, justifyContent: "flex-end", alignItems: "center" }}>
				<MapView
					style={{ ...StyleSheet.absoluteFillObject }}
					ref={ref => { this.map = ref; }}
					initialRegion={this.calculateDelta(51.43581846832452, 5.475311279296875, 4000)} />
			</View>
		);
	}
}

export default MapScreen;
```

**Comment by rborn** [comment]
Try a lower version of the navigator, like `2.12.1`

**Comment by vbhv19** [comment]
Resolved it by removing react-native-elements and react-native-vector-icons package which is used in the header.

**Comment by Cyberuben** [comment]
@vbhv19 I have neither of these modules installed. I can't see them anywhere in my node_modules folder either.
