### ISSUE TITLE
When can we expect the next release?

### ISSUE THREAD

**Issue by ravirajn22** [react-community/react-native-maps#2510]
### Is this a bug report?
NO

Guys, there has been a lot of fixes and changes since the last release v0.21.0 dated APR 1. Now that react-native 0.57.0 has been released with Gradle updates and other changes, can we also have a release for this lib?. I feel its long time due.
Thanks.

**Comment by JumalDB** [comment]
+1

**Comment by todorone** [comment]
@alvelig Is any help needed for release?

**Comment by rborn** [comment]
@todorone if you could make a changelog for the release would be good. Then we can ask @christopherdro to make one 😊

Take a look at how the changelog looks like https://github.com/react-community/react-native-maps/releases and I believe the last commit was `c53ff0a`

🤗

**Comment by todorone** [comment]
@rborn Great. Will try to assemble it across next week.

**Comment by ferrannp** [comment]
Any news on this @todorone ? This package does not build anymore in Android Studio and makes CI(s) to break just for this tiny commit https://github.com/react-community/react-native-maps/commit/680debed50e0c492eadc19e172ff8ccaa0271907. Maybe we could even cherry-pick that one for a `0.21.1`...

**Comment by todorone** [comment]
@ferrannp I hope I'll do it tomorrow. But I have no clue when @christopherdro can do release though...

**Comment by todorone** [comment]
@rborn @alvelig  Please take a look at #2535. If I didn't confuse links/descriptions, we are theoretically ready to go with the release.

PS: Wow, I must say it's not an easy task... 😌

**Comment by ravirajn22** [comment]
A new version is released v0.22.0. Hence closing.
