### ISSUE TITLE
[iOS] - No visible @interface for 'AIRMap'

### ISSUE THREAD

**Issue by vendramini** [react-community/react-native-maps#2513]
### Is this a bug report?

I don't know, probably yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

```javascript
"react": "^16.3.1",
"react-native": "^0.55.4",
"react-native-maps": "git+https://git@github.com/react-community/react-native-maps.git",
```

### Steps to Reproduce

I just updated node_modules and the problem started. My last build was successfully before.

### Expected Behavior

Compile.

### Actual Behavior

`No visible @interface for 'AIRMap' declares the selector 'showAnnotations:edgePadding:animated:'`
![screen shot 2018-09-26 at 21 54 40](https://user-images.githubusercontent.com/510878/46118000-c6f86900-c1da-11e8-8877-6c5513fecae4.png)

I tried some things that people said here #2396 but nothing seems to work.

Android is fine.
iOS is not compiling. I'm **not** using Google Maps.

**Comment by gitpushdev** [comment]
Same here I started receiving this issue two days ago, updated node modules and problem started. 
I even tried replacing "github:react-community/react-native-maps" with "^0.21.0" 
still the same issue

**Comment by vendramini** [comment]
I changed for 0.21.0 and the issue was solved.

@gitpushdev try removing node_modules, npm install, remove ios/Pods then pod install. Worked here.

But we probably have a bug on last git version here.

xcode 9.4.1 here.

**Comment by gitpushdev** [comment]
@vendramini thank you, I will try your steps

**Comment by wanderSX** [comment]
I don't use cocoapods, but i also have this issue with git version

**Comment by bmkopp10** [comment]
I'm experiencing the same problem.  This just started a few days ago.  It was working perfectly fine.  I've tried removing node, reinstalling, removing pods and reinstalling.  

Any other solutions?

**Comment by todorone** [comment]
@marcelkalveram Could You please check, iOS project can't be built using latest `master` branch and this problem is possibly introduced in this commit - https://github.com/react-community/react-native-maps/commit/c928c717afe5bc17046cfc04512d9843572ee081

**Comment by marcelkalveram** [comment]
@todorone thanks for the heads-up. There's indeed an issue with the function I modified.

Here's a patch

```
patch-package
--- a/node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
+++ b/node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
@@ -204,7 +204,7 @@ RCT_EXPORT_METHOD(fitToSuppliedMarkers:(nonnull NSNumber *)reactTag
       CGFloat bottom = [RCTConvert CGFloat:edgePadding[@"bottom"]];
       CGFloat left = [RCTConvert CGFloat:edgePadding[@"left"]];
 
-      [mapView animateWithCameraUpdate:[GMSCameraUpdate fitBounds:bounds withPadding:55.0f withEdgeInsets:UIEdgeInsetsMake(top, left, bottom, right)]];
+      [mapView animateWithCameraUpdate:[GMSCameraUpdate fitBounds:bounds withEdgeInsets:UIEdgeInsetsMake(top, left, bottom, right)]];
     }
   }];
 }
--- a/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapManager.m
+++ b/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapManager.m
@@ -245,12 +245,7 @@ RCT_EXPORT_METHOD(fitToSuppliedMarkers:(nonnull NSNumber *)reactTag
 
             NSArray *filteredMarkers = [mapView.annotations filteredArrayUsingPredicate:filterMarkers];
 
-            CGFloat top = [RCTConvert CGFloat:edgePadding[@"top"]];
-            CGFloat right = [RCTConvert CGFloat:edgePadding[@"right"]];
-            CGFloat bottom = [RCTConvert CGFloat:edgePadding[@"bottom"]];
-            CGFloat left = [RCTConvert CGFloat:edgePadding[@"left"]];
-
-            [mapView showAnnotations:filteredMarkers edgePadding:UIEdgeInsetsMake(top, left, bottom, right) animated:animated];
+            [mapView showAnnotations:filteredMarkers animated:animated];
             
         }
     }];
```

I'll now submit a PR based on this fix: https://github.com/marcelkalveram/react-native-maps/commit/cd285cfc43b13b73c6ec395004de0d5f86cdb3f6. 

You can use this instead of the original repo, but npm also seems to work as it didn't include the bug yet.

**Comment by todorone** [comment]
@marcelkalveram Amazing, thanks a lot for the quick fix!

**Comment by marcelkalveram** [comment]
No problem. Again, apologies. This should never have gone into master. 

It looks like I didn't properly rebuild when testing this, but instead was just testing the bundle changes.

Maybe failing builds should be caught by CI? @rborn @alvelig

**Comment by vendramini** [comment]
Thank you for the quick fix! Awesome =)
