### ISSUE TITLE
No known class method for selector 'fitBounds:withPadding:withEdgeInsets:'

### ISSUE THREAD

**Issue by IgorVanian** [react-community/react-native-maps#2517]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Steps to Reproduce

While building with the latest RNMaps from the repo, Xcode 10 throws a build error  `/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapManager.m:239:57: No known class method for selector 'fitBounds:withPadding:withEdgeInsets:'``

I checked AIRGoogleMapManager.m history here: https://github.com/react-community/react-native-maps/commit/c928c717afe5bc17046cfc04512d9843572ee081#diff-d59125d4a8890a4d22b6026d3612becd

`withEdgeInsets:UIEdgeInsetsMake(top, left, bottom, right)` seems to be the problem. It also repeats 

When I reverted it back to the older version, it worked fine.

It also repeats here:

![image](https://user-images.githubusercontent.com/16898357/46138479-43776000-c24c-11e8-95bd-9d95b426b4a1.png)

### Expected Behavior

Should normally build.

### Actual Behavior

Throws error trying to build.

**Comment by rborn** [comment]
#2524 merged and tested.
