### ISSUE TITLE
Callout on Polyline?

### ISSUE THREAD

**Issue by isaaclem** [react-community/react-native-maps#2527]
### Is this a bug report?
Maybe yes maybe no.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Steps to Reproduce
Does Polyline support callout the way it does like marker? or Polyline doesnt support callout at all?
I've tried below but callout doesnt seems to appear

              <Polyline
                coordinates={gotoPolyCoord}
                lineCap='round'
                lineJoin='round'
                strokeColor='purple' // fallback for when `strokeColors` is not supported by the map-provider
                strokeWidth={4}
              >
                <Callout style={mapCalloutStyles.calloutContainer} tooltip>
                  <MapCallout 
                    title={'hihi'}
                    description={`yo!`}
                  />
                </Callout>
              </Polyline>

**Comment by rborn** [comment]
Polylines don't have callouts.

**Comment by isaaclem** [comment]
@rborn: wondering will there be any plan to include a callout for polyline as it's already supported a onPress event?

**Comment by rborn** [comment]
@isaaclem we're a community so features are added based on what people add in their PRs. 
Besides this it has to be supported by the native sdk - which I'm not sure it is.

**Comment by danikane** [comment]
Take one of the polyline points (the middle one or the one pressed) and construct a marker and a callout based on it.
