### ISSUE TITLE
Centered map after rotate that 

### ISSUE THREAD

**Issue by bashirpour** [react-community/react-native-maps#2530]
### Environment

    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-map-clustering": "^1.3.0",
    "react-native-maps": "*",
    "react-native-svg": "^7.0.3",
    "react-navigation": "^2.0.2",

### Expected Behavior

Fixed maps after rotate 

### Actual Behavior

When i rotate the map and update region it automatically centered

### Real Code
    import React, { Component } from 'react';
    import {
        StyleSheet,
        Dimensions,
    } from 'react-native';
    import MapView from "react-native-maps";
    
    const {width, height} = Dimensions.get('window');
    const ASPECT_RATIO = width / height;
    const LATITUDE_DELTA = 0.5;
    const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
    
    
    type Props = {};
    export default class App extends Component<Props> {
    
    
        onRegionChange(region) {
            this.setState({ region });
        }
    
        constructor(props){
            super(props);
    
            this.coordinate = {
                latitude: 35.688442,
                longitude: 51.403753,
                latitudeDelta: LATITUDE_DELTA,
                longitudeDelta: LONGITUDE_DELTA,
            };
    
    
            this.state = {
                region : this.coordinate
            }
        }
    
        render() {
            return (
                <MapView
                    region={this.state.region}
                    onRegionChangeComplete={this.onRegionChange.bind(this)}
                    style={{...StyleSheet.absoluteFillObject}}
                />
                
            );
        }
    }

### Reproducible Demo

![keth4-fxccc](https://user-images.githubusercontent.com/29279799/46407956-71ade180-c71d-11e8-8e4e-41405f864b0f.gif)

**Comment by rborn** [comment]
Please update your issue following the template or I'll close it

**Comment by bashirpour** [comment]
I've updated my issue

**Comment by rborn** [comment]
When you rotate the map is re-rendered so region will be reset. Try to use
` initialRegion={this.state.region}`

**Comment by bashirpour** [comment]
@rborn Thanks a lot

**Comment by FanchenBao** [comment]
My solution for this issue is to use `initialRegion` for `MapView`, and use `animateToRegion` when the map view needs to be centered on a point of interest a user has just pressed.
