### ISSUE TITLE
Can't update react-native-maps

### ISSUE THREAD

**Issue by rendomnet** [react-community/react-native-maps#2537]
### Is this a bug report?
NO.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

    react-native: 0.59.0
    react-native-maps: 0.21.0

### Expected Behavior

yarn add react-native-maps updates react native maps.

### Actual Behavior

When i use "yarn add react-native-maps" the version I get is different from the version I see on the repo. For example in my version inside AndroidMainifest there is minSdk property but in the version on gitlab there is no such property. As I understand my version is like 6 month old.

**Comment by rborn** [comment]
The git version is not yet published to npm. Use this one for now.

**Comment by rendomnet** [comment]
@rborn 
So using 
`"react-native-maps": "https://github.com/react-community/react-native-maps.git",`

in package.json will do the job?

**Comment by rborn** [comment]
yes
