### ISSUE TITLE
problems installing react-native-maps 0.21.0 and react-native

### ISSUE THREAD

**Issue by dmorilha** [react-community/react-native-maps#2539]
## Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
```
{
    react-native: 0.57.2.
    react: 16.0.0,
    react-native-maps: 0.21.0
}
```
Targeting both platforms with Google Maps.

### Steps to Reproduce

Install the package and run the application. All advised steps were followed at: https://github.com/react-community/react-native-maps

### Expected Behavior

Application runs with no bugs.

### Actual Behavior

Application becomes flaky and presents undefined behavior.

![image](https://user-images.githubusercontent.com/723098/46687890-dd2a0000-cbb0-11e8-85b4-312e1c3d48d2.png)

### Reproducible Demo

n/a

**Comment by rborn** [comment]
Use the git version.

**Comment by atmeanas** [comment]
I have the exactly the same issue even importing from git.

This is my dependency line from react-native-maps:

"react-native-maps": "github:react-community/react-native-maps"
