### ISSUE TITLE
Moving Google Maps Elements

### ISSUE THREAD

**Issue by adam-jakiela** [react-community/react-native-maps#254]
Is it possible to move the default Google maps elements within the map? Specifically, I am trying to move the "Google" logo from the bottom left corner and the user location button from the top right corner.

Thanks

**Comment by jeveloper** [comment]
That's odd, mine is showing on the right bottom side

**Comment by xvalentino** [comment]
Any progress on this?

**Comment by kaanlcaglar** [comment]
Did you guys figure this out already?

**Comment by xvalentino** [comment]
I moved over to Mapbox.

**Comment by kaanlcaglar** [comment]
We've been considering that. How did it take you to set up mapbox? Cheers!

**Comment by xvalentino** [comment]
Overall a little better than I thought, I think I was running into some weird problems with changing what the map markers looked like, but I believe that's resolved. It's a little better to customize, so I'd reccommned looking into it.

**Comment by kaanlcaglar** [comment]
Thanks for the quick response. Overall, the designs are way better than Google Maps. I think we'll switch to that in one of the next releases of our app.

**Comment by xvalentino** [comment]
Yeah, I also think that there is a dependency on the Google apps being installed on the device running it, so users of custom ROMS may run into problems. Haven't looked into it much though.

**Comment by alvelig** [comment]
That's a GoogleMaps SDK limitation. Wontfix :(
