### ISSUE TITLE
Problems setting up maps - node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapPolygonManager.h:7:9: fatal error: 'React/RCTViewManager.h' file not found #import <React/RCTViewManager.h>

### ISSUE THREAD

**Issue by manujbahl** [react-community/react-native-maps#2540]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
    react - 16.3.1
    react-native - 0.55.4
    react-native-maps: 0.21.0
    iOS - 11.2 Simulator/iPhone 6

### Steps to Reproduce

Followed the steps for cocoa pods install from the installation.md document.

### Expected Behavior

react-native-maps with google maps gets installed.  

### Actual Behavior

build fails with the following error.
node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapPolygonManager.h:7:9: fatal error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>

### Reproducible Demo

The issue happens with just trying to build

**Comment by rborn** [comment]
use the git version
