### ISSUE TITLE
Problem using react-native-maps

### ISSUE THREAD

**Issue by atmeanas** [react-community/react-native-maps#2542]
### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react-native-maps": "github:react-community/react-native-maps"
"react": "16.5.0"
"react-native": "0.57.0"

### Steps to Reproduce

Just try to run the application after installing react-native-maps

### Expected Behavior

It should be able to use without any problems.

### Actual Behavior

I've got this screen:
![erro rnm](https://user-images.githubusercontent.com/44002017/46750943-95c67100-cc8f-11e8-9c0e-577641cd9b99.png)

@Edit
Something I've just remembered. I've seen some answers saying to link using 'react-native link react-native-maps' but when I do it, I got an even worse problem.

this is what happens when I use react-native link react-native-maps

[build fail rn rnm.txt](https://github.com/react-community/react-native-maps/files/2465564/build.fail.rn.rnm.txt)

I put it into a txt file because it is too long to paste here.

### Reproducible Demo

n/a

**Comment by rborn** [comment]
duplicate https://github.com/react-community/react-native-maps/issues/2495
