### ISSUE TITLE
'React/RCTConvert.h' file not found

### ISSUE THREAD

**Issue by simonstyleur** [react-community/react-native-maps#2554]
<img width="896" alt="screen shot 2018-10-18 at 5 21 04 pm" src="https://user-images.githubusercontent.com/25347779/47169330-17a34380-d2fb-11e8-9fc1-887f85cbf7db.png">

after installing react-native-maps and using Pods to link it with on IOS i got error 
'React/RCTConvert.h' file not found

what should i do please ?

**Comment by Mamdouh-Symbyo** [comment]
how you solve it @rborn?

**Comment by TxusBlack** [comment]
I have the same issue

**Comment by sleepserenade** [comment]
how to fix it ?

**Comment by syedamirali14** [comment]
any solution?

**Comment by simonstyleur** [comment]
> any solution?

try :
cd ios 
pod install
and in Xcode : File -> workspace settings : Build system to Legacy build system
