### ISSUE TITLE
Android Map cannot be displayed

### ISSUE THREAD

**Issue by showtan001** [react-community/react-native-maps#2558]
### Is this a bug report?
    Yes
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
    YES
### Environment
    react-native: 0.51.0
    react: 16.0.0
    react-native-maps: 0.20.1
    phone: xiaomi 5s（Real machine Android7.0）、Google Nexus 5X（Simulator Android7.0）
### Steps to Reproduce
    react-native run-android
### Expected Behavior
    Map display
### Actual Behavior
    Map not shown
### Reproducible Demo
    [https://github.com/react-community/react-native-maps/tree/master/example/examples]
    build.gradle
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        multiDexEnabled true
        applicationId "com.xxxx"
        minSdkVersion 16
        targetSdkVersion 27
   }
   
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    
![xiaomi 5s](https://user-images.githubusercontent.com/32892347/47203813-09652e00-d3b4-11e8-9de8-ed9991ec87dd.png)
![google nexus 5x](https://user-images.githubusercontent.com/32892347/47204578-43cfca80-d3b6-11e8-8ac6-f335208e5994.png)

**Comment by rborn** [comment]
That's an  api key problem

**Comment by showtan001** [comment]
@rborn 
AndroidManifest.xml file I have configured.
![7 w_7fk1ihm6l86w9 ijys0](https://user-images.githubusercontent.com/32892347/47209527-26552d80-d3c3-11e8-9f57-7df9cf672139.png)

![dfc043d8-86f6-7b82-c721-fc4b14f5f89a](https://user-images.githubusercontent.com/32892347/47209409-dd9d7480-d3c2-11e8-9988-d14e53fcda91.jpg)

**Comment by rborn** [comment]
Try to make an unrestricted key in google console, you have a restricted one for android only now (I think, I cannot read your language 😅)

**Comment by showtan001** [comment]
@rborn ok! Is the SHA-1 value obtained from the .android debug.keystore or is it obtained in my project my-release-key.keystore?

**Comment by showtan001** [comment]
@rborn ok! Is the SHA-1 value obtained from the .android debug.keystore or is it obtained in my project my-release-key.keystore?
