### ISSUE TITLE
[iOS] no such file or directory AirGoogleMaps DummyView.m

### ISSUE THREAD

**Issue by leanstartlab** [react-community/react-native-maps#2601]
I have the update from 0.21.0 to 0.22.1 but I have a problem as:

`clang: error: no such file or directory: node_modules/react-native-maps/lib/ios/AirGoogleMaps/DummyView.m
clang: error: no input files`

how to resolve this issue.
many thanks.

**Comment by leanstartlab** [comment]
I replaced all `DummyView.m` to `AIRDummyView.m` on `ios/Pops/Pops.xodeprj` 💃

**Comment by arled** [comment]
What in the world is Pops?

**Comment by pakkibokati2012** [comment]
@lachenmayer @arled How did you solve the issue? I did not find any Pops folder inside ios.

**Comment by indiorlei** [comment]
I searched for DummyView.m in VSCode and found this entry in the project.pbxproj file, I switched all entries to AIRDummyView.m
It worked for me!

**Comment by amsdamsgram** [comment]
I fixed it by updating my pods: `pod update react-native-maps`

**Comment by pakkibokati2012** [comment]
Actually I took a different route instead. I manually installed react-native-maps. That was quite painful but is worth putting an effort.

**Comment by Jobel91** [comment]
I did what @amsdamsgram  said and it works, thanks.

**Comment by NemanjaManot** [comment]
I have same problem
