### ISSUE TITLE
is it possible to create an 'undraggable' DraggableMarker component

### ISSUE THREAD

**Issue by gerard0315** [react-community/react-native-maps#274]
This is not really a issue, just doing a project, might need such component just like the Uber pick up point marker. 
Marker is located in the middle of the view and user drags map to change the location

**Comment by jrichardlai** [comment]
Hello, I'm not sure I understand, there is a `draggable` prop that can be set on the Marker, will set `draggable=false` enough?

**Comment by dozoisch** [comment]
@gerard0315 if you control the region, then on regionChange you should be able to recenter the marker at the same time.

**Comment by SteffenC** [comment]
Any conclusion to this ?

**Comment by alvelig** [comment]
@dozoisch's solution would be the recommended. If not please post your business logic to see alternatives
