### ISSUE TITLE
Get distance to fetch markers.

### ISSUE THREAD

**Issue by kinhbang89** [react-community/react-native-maps#278]
Hi I just would like to ask for example I get the latitude and longitude point in the  MapView so how can I get radius distance from that point to the border of my MapView?

**Comment by jrichardlai** [comment]
you can use the onRegionChange and get the latitude, longitude, latitudeDelta and longitudeDelta

**Comment by kinhbang89** [comment]
Hi,

I can get the distance from this formula?    

`  let distance = Math.abs(deltaLongitude / 360 *  (Math.cos(latitude) * 2 * (Math.PI) * radiusEarth));`

**Comment by texas697** [comment]
can you post your working code kinhbang89

**Comment by jrichardlai** [comment]
Not sure about the formulas @kinhbang89, where did you found this one?

**Comment by laoqiu** [comment]
@kinhbang89 Do you have solution now?  
I have the same problem.

**Comment by esutton** [comment]
https://github.com/niix/haversine

**Comment by alvelig** [comment]
Or reverse Mercator Projection https://github.com/react-community/react-native-maps/issues/356

**Comment by timorss** [comment]
in that
let distance = Math.abs(deltaLongitude / 360 * (Math.cos(latitude) * 2 * (Math.PI) * radiusEarth));

what do i need to put in the radiusEarth?

**Comment by rborn** [comment]
@timorss one of these depending what you want (km, miles, m, nautical miles): https://github.com/brandon93s/haversine-js/blob/master/index.js#L5
