### ISSUE TITLE
Pod install errors

### ISSUE THREAD

**Issue by igorclark** [react-community/react-native-maps#279]
Hi there - this is possibly related to #184 and #250 but they've both been closed and the suggestions don't seem to make a difference.

I'm trying to install using the [instructions](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md). I get the following catch-22:

```
It seems like you've changed the constraints of dependency `react-native-maps` inside your development pod `react-native-maps`.
You should run `pod update react-native-maps` to apply changes you've made.
$ pod update react-native-maps
[!] The `react-native-maps` Pod is not installed and cannot be updated
```

(Full output log below.)

I don't know enough about Pods to say for sure but it looks like the version in NPM is still out of date. Thing is when I try `npm install lelandrichardson/react-native-maps` as suggested in #250  I get the same problem, and I don't know which commit to use in `package.json` as the `podspec` in `master` still seems to point to [0.3.1](https://github.com/lelandrichardson/react-native-maps/blob/master/react-native-maps.podspec). (I could be getting the wrong end of the stick due to lack of knowledge about `npm`/`pod`/ interaction between the two.)

Is this broken, or am I just missing something? Any ideas on what to do? 

Thanks!

```
$ node --version
v6.2.1
$ npm --version
3.9.3
$ uname -a
Darwin igors-mbp.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
$ npm install lelandrichardson/react-native-maps --save # tried "npm install react-native-maps --save", same result
$ npm install
$ rnpm link
$ cd ios
$ vi Podfile # add line: pod 'react-native-maps', :path => '../node_modules/react-native-maps'
$ cat Podfile
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MyApp' do
        pod 'react-native-maps', :path => '../node_modules/react-native-maps'
end

$ grep s.version ../node_modules/react-native-maps/react-native-maps.podspec
  s.version      = "0.3.1"
$ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
[!] Unable to satisfy the following requirements:

- `react-native-maps (from `../node_modules/react-native-maps`)` required by `Podfile`

It seems like you've changed the constraints of dependency `react-native-maps` inside your development pod `react-native-maps`.
You should run `pod update react-native-maps` to apply changes you've made.
$ pod update react-native-maps
[!] The `react-native-maps` Pod is not installed and cannot be updated
$ cat Pods/Local\ Podspecs/react-native-maps.podspec.json
{
  "name": "react-native-maps",
  "version": "0.3.1",
  "summary": "React Native Mapview component for iOS + Android",
  "authors": {
    "intelligibabble": "leland.m.richardson@gmail.com"
  },
  "homepage": "https://github.com/lelandrichardson/react-native-maps#readme",
  "license": "MIT",
  "platforms": {
    "ios": "8.0"
  },
  "source": {
    "git": "https://github.com/lelandrichardson/react-native-maps.git"
  },
  "source_files": "ios/AirMaps/**/*.{h,m}",
  "dependencies": {
    "React": [

    ]
  }
}
$ cat ../package.json
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.0.2",
    "react-mixin": "^3.0.5",
    "react-native": "0.26.2",
    "react-native-maps": "github:lelandrichardson/react-native-maps",
    "react-redux": "^4.4.5",
    "react-timer-mixin": "^0.13.3",
    "redux": "^3.0.0",
    "redux-actions": "^0.9.1"
  },
  "devDependencies": {
    "rnpm-plugin-upgrade": "^0.26.0"
  }
}
```

**Comment by erickreutz** [comment]
Running into this very thing. Were you able to find a solution?

**Comment by igorclark** [comment]
Hey @erickreutz, no, I gave up in the end. I found the same problem trying to use [another React Native module](https://github.com/yamill/react-native-orientation) that linked native code via a Pod.

However, I did manage to get the [Mapbox native component](https://www.mapbox.com/ios-sdk/) installed via CocoaPods and successfully exposed the basics of that to React as [Native UI Component](https://facebook.github.io/react-native/docs/native-components-ios.html). So I'm left wondering if it's a problem with [i] these projects; [ii] my Mac/setup; [iii] `rnpm`; [iv] `pod`. My guess is [iii]. (Or of course [ii] ;-)).

Would love to know if you work out how to get around this!

**Comment by brianjd** [comment]
Encountering this as well.  https://github.com/lelandrichardson/react-native-maps/pull/308 appears to be related.

**Comment by charliesbox** [comment]
having the same issue. anyone already found a workaround?

**Comment by PotterDai** [comment]
uncommenting "platform :ios, '9.0'" at second line of generated Podfile will solve the problem :)

**Comment by masterkrang** [comment]
having the same issue:

```
$ pod install
Analyzing dependencies
Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
[!] Unable to satisfy the following requirements:

- `react-native-maps (from `../node_modules/react-native-maps`)` required by `Podfile`

It seems like you've changed the constraints of dependency `react-native-maps` inside your development pod `react-native-maps`.
You should run `pod update react-native-maps` to apply changes you've made.
```

reproduce:

1. react-native init newproject
2. Follow instructions exactly as they are are on react-native-maps README
3. arrive at the part where I `pod install` and run `pod install`
4. above error occurs

**Comment by benmarten** [comment]
Using `platform :ios, '9.0'` fixed this for me...

**Comment by nsarafa** [comment]
Ran into a similar issue. After installing cocoapods (`sudo gem install cocoapods`) generating a Podfile (`cd ios && touch Podfile`) and by adding the following to Podfile swapping `NAME_OF_PROJECT` with the project name
```
platform :ios, '9.0'
workspace './NAME_OF_PROJECT.xcodeproj/project.xcworkspace'

target 'NAME_OF_PROJECT' do
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
end
```
.. Then run `pod install` inside the `ios` directory and you should be good to go

**Comment by ios122** [comment]
```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
```
It seems that platform must be declared in Podfile,and the Value must be greater than or equal to 8.0

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
