### ISSUE TITLE
Error in real device

### ISSUE THREAD

**Issue by KarlosQ** [react-community/react-native-maps#284]
I have this error:

![screenshot_2016-06-09-14-45-29_com maptest](https://cloud.githubusercontent.com/assets/15233913/15930033/f7ba5000-2e50-11e6-914c-330a8b53c848.png)

I'm using react-native 0.27, react-native-maps 0.42 and Android 5.1.1 in a Xiaomi Redmi Note 3 Pro

**Comment by pramodkumardamam73** [comment]
+1 need a fix

**Comment by henrikra** [comment]
We have the same problem on newer version Xiaomi Redmi Note 4

**Comment by benyliantriana** [comment]
error on some devices xiaomi and sony.. need help

**Comment by rborn** [comment]
Trying to clean the repo, please comment or mention me to re-open the issue if is still the case. Thanks.
