### ISSUE TITLE
AnimatedViews Strucks half-way

### ISSUE THREAD

**Issue by symmetriccurve** [react-community/react-native-maps#287]
I'm using animatedViews but when I only slide up halfway and release the touch and click again to drag it up more it does not work.

**Comment by italobrasiil** [comment]
I have the same issue

**Comment by douglaswissett** [comment]
Any progress on this issue? I can drag the red view up and down but when I release the click it no longer drags up or down.

![screenshot 2017-06-23 11 43 06](https://user-images.githubusercontent.com/15790783/27478811-2871a576-5809-11e7-8570-bdd0c252ec2d.png)

**Comment by rborn** [comment]
Seems to be resolved. Closing.
