### ISSUE TITLE
Marker onDrag takes too long to fire

### ISSUE THREAD

**Issue by deoqc** [react-community/react-native-maps#292]
I would like to know if is there a way to reduce `onDrag` time lapse between press/holding the marker and the event fire?

I think it takes too long (maybe to better distinguish it from `onPress`), feeling unresponsive.

**Comment by jrichardlai** [comment]
Hello, are you testing on Android or iOS?

**Comment by deoqc** [comment]
I'm using iOS, both in simulator and real device.

**Comment by rborn** [comment]
Trying to clean the repo, please comment or mention me to re-open the issue if is still the case. Thanks.
