### ISSUE TITLE
running rnpm link for an unrelated module breaks android installation.

### ISSUE THREAD

**Issue by allthetime** [react-community/react-native-maps#303]
I just ran `rnpm link` for an unrelated module and it added an extra/unnecessary line to `build.gradle` that broke my react-native-maps installation.

The line added is in `dependencies` and is 

```
compile project(':react-native-maps')
```

It leads to this error:

```
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.
```

This line should not be added. I'm not sure how rnpm works or how much control you/this project has over its behaviour, just thought you should know!

**Comment by jrichardlai** [comment]
Thanks for pointing out the issue, not sure either how this works.

**Comment by joelcloralt** [comment]
Oh man thank you!

I just upgraded to `0.6.0` and got this issue and removed that line from build.gradle and it passed that step. After that, I got another error, which seems related.

`error: package com.AirMaps does not exist` which points to `MainActivity.java`, so I removed this line from there too `import com.AirMaps.AirPackage;` 

After that, it compiled correctly.

**Comment by jdeniau** [comment]
Manage to fix this by changing this after `rnpm link`:

in `android/app/build.gradle`
```diff
- compile project(':react-native-maps')
+ compile "com.airbnb.android:react-native-maps:0.6.0"
```

I tried replacing `0.6.0` by  `+` and it seems to work

in `MainActivity.java`:
```diff
- new MapsPackage()
+ new MapsPackage(this)
```

It is as it's said in the manual installation. @lelandrichardson can you do something to make rnpm working ?

**Comment by christopherdro** [comment]
We should remove instructions for rnpm since it's not going to add the maven lib and should default to manual setup. It's only a few lines of code and we have it documented.

**Comment by alvelig** [comment]
Closing in favor of #1862
