### ISSUE TITLE
 'RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by ryudice** [react-community/react-native-maps#318]
I'm getting compilation error: 
 'RCTViewManager.h' file not found

after installing using "pod 'react-native-maps', :path => '../node_modules/react-native-maps'".

The iOS target is 9.3, wonder if that has something to do?

**Comment by sheldongoldberg** [comment]
Quite possibly for the same reason,  I keep getting the error RCTView.h not found, although I do see it in node_modules

**Comment by christopherdro** [comment]
@ryudice If you are going to use the library with cocoapods you'll need to make sure you do the same with React Native.

https://facebook.github.io/react-native/docs/embedded-app-ios.html#install-react-native-using-cocoapods

Can you give that a shot and report back?

**Comment by MasterA** [comment]
Have the same issue. I deleted the node modules and reinstalled them but still nothing.

**Comment by ryudice** [comment]
I used `rnpm link` instead of adding the pod and that worked for me

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
