### ISSUE TITLE
Markers are "overloading" the component (?)

### ISSUE THREAD

**Issue by kelset** [react-community/react-native-maps#319]
Hi guys.
I'm using the component to show, around the user current location, some elements (a-la-TripAdvisor). But it seems that, when I move to another screen in my app, that the component is not "flushed" nor the markers are deleted. (even if in the component unmount I free the array with the markers positions)

This basically causes the whole app to get slower each time I go back to the screen where the MapView is.

Is there any way to have some sort of
`MapView.flush`
that resets the markers and such?

**Comment by jrichardlai** [comment]
Interesting I would think the native map would handle off screen data, I don't think there is a flush method, it could be a nice add to the lib, PR welcome. Also one way to achieve it in JS would be to listen to onRegionChange and update the markers to only the ones that should be visible.

**Comment by Kristiansen** [comment]
Im having the same issue. Using RN 0.25.1 and react-native-maps 0.5.0. I am using the same component for the map i did in a previous project, using RN 0.21 and react-native-maps 0.3 and then everything worked very well. I havent really looked into this problem jet more than identifying that when i add markers to the map the app becomes very slow in general..

**Comment by luco** [comment]
Same issue here. Removing markers makes the app more smooth, but not the ideal.

**Comment by alvelig** [comment]
The map is not unmounted (at least in react-navigation). You control your markers as you wish. Unfortunately, there's not much to do with this. Just make sure your markers are performant and you don't change the state or props from outside.
