### ISSUE TITLE
'Constructor' has no propType for native prop 'AIRMap.loadingEnabled' of nativetype 'boolean'

### ISSUE THREAD

**Issue by sagarsuryawanshi** [react-community/react-native-maps#320]
i am trying to show simple map view with below code and getting this "Constructor has no PropType" error. Please help.

```
import React, { Component } from 'react';
import MapView from 'react-native-maps';
//var MapView = require('react-native-maps');

import {
  AppRegistry,
  StyleSheet,
  PropTypes,
  Text,
  TextInput,
  Platform,
  Navigator,
  ScrollView,
  Image,
  ListView,
  TouchableHighlight,
  TouchableNativeFeedback,
  View,
  DrawerLayoutAndroid,

} from 'react-native';

var styles = StyleSheet.create({
    map: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
});

var ShowMap = React.createClass({

    getInitialState() {
        return {
            region: {
                latitude: 37.78825,
                longitude: -122.4324,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
            },
        };
    },

    onRegionChange(region) {
        this.setState({ region });
    },

    render() {


        return (<View style ={styles.container}>
                <MapView 
                          style = {styles.map} 
                            initialRegion={this.state.region}
                    />

                </View>
        );
    }
});


AppRegistry.registerComponent('AwesomeProject', () => ShowMap);
```

**Comment by jrichardlai** [comment]
Hello, Can you restart your packager? is there a full stacktrace you can put?

**Comment by sagarsuryawanshi** [comment]
@jrichardlai There is no error while running the below commands, but here is what i get.
`
======================================================
E:\AwesomeProject>react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat install Debug...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-maps:compileLint
:react-native-maps:copyReleaseLint UP-TO-DATE
:react-native-maps:preBuild UP-TO-DATE
:react-native-maps:preReleaseBuild UP-TO-DATE
:react-native-maps:checkReleaseManifest
:react-native-maps:preDebugAndroidTestBuild UP-TO-DATE
:react-native-maps:preDebugBuild UP-TO-DATE
:react-native-maps:preDebugUnitTestBuild UP-TO-DATE
:react-native-maps:preReleaseUnitTestBuild UP-TO-DATE
:react-native-maps:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-maps:prepareComFacebookReactReactNative0191Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:react-native-maps:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-maps:prepareReleaseDependencies
:react-native-maps:compileReleaseAidl UP-TO-DATE
:react-native-maps:compileReleaseRenderscript UP-TO-DATE
:react-native-maps:generateReleaseBuildConfig UP-TO-DATE
:react-native-maps:generateReleaseAssets UP-TO-DATE
:react-native-maps:mergeReleaseAssets UP-TO-DATE
:react-native-maps:generateReleaseResValues UP-TO-DATE
:react-native-maps:generateReleaseResources UP-TO-DATE
:react-native-maps:mergeReleaseResources UP-TO-DATE
:react-native-maps:processReleaseManifest UP-TO-DATE
:react-native-maps:processReleaseResources UP-TO-DATE
:react-native-maps:generateReleaseSources UP-TO-DATE
:react-native-maps:processReleaseJavaRes UP-TO-DATE
:react-native-maps:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-maps:extractReleaseAnnotations UP-TO-DATE
:react-native-maps:mergeReleaseProguardFiles UP-TO-DATE
:react-native-maps:packageReleaseJar UP-TO-DATE
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:packageReleaseJniLibs UP-TO-DATE
:react-native-maps:packageReleaseLocalJar UP-TO-DATE
:react-native-maps:packageReleaseRenderscript UP-TO-DATE
:react-native-maps:packageReleaseResources UP-TO-DATE
:react-native-maps:bundleRelease UP-TO-DATE
:app:prepareAwesomeProjectReactNativeMapsUnspecifiedLibrary UP-TO-DATE
:app:prepareComAirbnbAndroidReactNativeMaps060Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0100Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0100Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30100Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0272Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'HP 7 Plus - 4.2.2'
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 3 mins 59.102 secs
Starting the app on 51384d4385423710508 (E:\hybrid\adt-bundle-windows-x86-201310
30\sdk/platform-tools/adb -s 51384d4385423710508 shell am start -n com.awesomepr
oject/.MainActivity)...
Starting: Intent { cmp=com.awesomeproject/.MainActivity }

======================================================
Looking for JS files in
   E:\AwesomeProject

[10:09:00 AM] <START> Building Dependency Graph
[10:09:00 AM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[10:09:00 AM] <START> Building Dependency Graph
[10:09:00 AM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[10:15:24 AM] <END>   Crawling File System (383872ms)
[10:15:25 AM] <START> Building in-memory fs for JavaScript
[10:15:26 AM] <END>   Building in-memory fs for JavaScript (1136ms)
[10:15:26 AM] <START> Building in-memory fs for Assets
[10:15:27 AM] <END>   Building in-memory fs for Assets (969ms)
[10:15:27 AM] <START> Building Haste Map
[10:15:27 AM] <START> Building (deprecated) Asset Map
[10:15:28 AM] <END>   Building (deprecated) Asset Map (397ms)
[10:15:28 AM] <END>   Building Haste Map (1497ms)
[10:15:28 AM] <END>   Building Dependency Graph (388385ms)

======================================================
E:\AwesomeProject>react-native bundle -dev false --platform android --entry
-file index.android.js --bundle-output ./android/app/build/intermediates/assets/
debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/m
erged/debug
[10:30:10 AM] <START> Building Dependency Graph
[10:30:10 AM] <START> Crawling File System
[10:30:11 AM] <START> find dependencies
[10:30:58 AM] <END>   Crawling File System (48180ms)
[10:30:58 AM] <START> Building in-memory fs for JavaScript
[10:30:59 AM] <END>   Building in-memory fs for JavaScript (589ms)
[10:30:59 AM] <START> Building in-memory fs for Assets
[10:31:00 AM] <END>   Building in-memory fs for Assets (462ms)
[10:31:00 AM] <START> Building Haste Map
[10:31:00 AM] <START> Building (deprecated) Asset Map
[10:31:00 AM] <END>   Building (deprecated) Asset Map (183ms)
[10:31:00 AM] <END>   Building Haste Map (402ms)
[10:31:00 AM] <END>   Building Dependency Graph (50112ms)
transformed 613/613 (100%)
[10:31:02 AM] <END>   find dependencies (50823ms)
bundle: start
bundle: finish
bundle: Writing bundle output to: ./android/app/build/intermediates/assets/debug
/index.android.bundle
bundle: Done writing bundle output
bundle: Copying 5 asset files
bundle: Done copying assets

======================================================
E:\AwesomeProject\android>gradlew assembleDebug
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-maps:compileLint
:react-native-maps:copyReleaseLint UP-TO-DATE
:react-native-maps:preBuild UP-TO-DATE
:react-native-maps:preReleaseBuild UP-TO-DATE
:react-native-maps:checkReleaseManifest
:react-native-maps:preDebugAndroidTestBuild UP-TO-DATE
:react-native-maps:preDebugBuild UP-TO-DATE
:react-native-maps:preDebugUnitTestBuild UP-TO-DATE
:react-native-maps:preReleaseUnitTestBuild UP-TO-DATE
:react-native-maps:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-maps:prepareComFacebookReactReactNative0191Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:react-native-maps:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-maps:prepareReleaseDependencies
:react-native-maps:compileReleaseAidl UP-TO-DATE
:react-native-maps:compileReleaseRenderscript UP-TO-DATE
:react-native-maps:generateReleaseBuildConfig UP-TO-DATE
:react-native-maps:generateReleaseAssets UP-TO-DATE
:react-native-maps:mergeReleaseAssets UP-TO-DATE
:react-native-maps:generateReleaseResValues UP-TO-DATE
:react-native-maps:generateReleaseResources UP-TO-DATE
:react-native-maps:mergeReleaseResources UP-TO-DATE
:react-native-maps:processReleaseManifest UP-TO-DATE
:react-native-maps:processReleaseResources UP-TO-DATE
:react-native-maps:generateReleaseSources UP-TO-DATE
:react-native-maps:processReleaseJavaRes UP-TO-DATE
:react-native-maps:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-maps:extractReleaseAnnotations UP-TO-DATE
:react-native-maps:mergeReleaseProguardFiles UP-TO-DATE
:react-native-maps:packageReleaseJar UP-TO-DATE
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:packageReleaseJniLibs UP-TO-DATE
:react-native-maps:packageReleaseLocalJar UP-TO-DATE
:react-native-maps:packageReleaseRenderscript UP-TO-DATE
:react-native-maps:packageReleaseResources UP-TO-DATE
:react-native-maps:bundleRelease UP-TO-DATE
:app:prepareAwesomeProjectReactNativeMapsUnspecifiedLibrary UP-TO-DATE
:app:prepareComAirbnbAndroidReactNativeMaps060Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0100Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0100Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0100Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30100Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0272Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:react-native-maps:copyDebugLint UP-TO-DATE
:react-native-maps:checkDebugManifest
:react-native-maps:prepareDebugDependencies
:react-native-maps:compileDebugAidl UP-TO-DATE
:react-native-maps:compileDebugRenderscript UP-TO-DATE
:react-native-maps:generateDebugBuildConfig UP-TO-DATE
:react-native-maps:generateDebugAssets UP-TO-DATE
:react-native-maps:mergeDebugAssets UP-TO-DATE
:react-native-maps:generateDebugResValues UP-TO-DATE
:react-native-maps:generateDebugResources UP-TO-DATE
:react-native-maps:mergeDebugResources UP-TO-DATE
:react-native-maps:processDebugManifest UP-TO-DATE
:react-native-maps:processDebugResources UP-TO-DATE
:react-native-maps:generateDebugSources UP-TO-DATE
:react-native-maps:processDebugJavaRes UP-TO-DATE
:react-native-maps:compileDebugJavaWithJavac UP-TO-DATE
:react-native-maps:extractDebugAnnotations UP-TO-DATE
:react-native-maps:mergeDebugProguardFiles UP-TO-DATE
:react-native-maps:packageDebugJar UP-TO-DATE
:react-native-maps:compileDebugNdk UP-TO-DATE
:react-native-maps:packageDebugJniLibs UP-TO-DATE
:react-native-maps:packageDebugLocalJar UP-TO-DATE
:react-native-maps:packageDebugRenderscript UP-TO-DATE
:react-native-maps:packageDebugResources UP-TO-DATE
:react-native-maps:bundleDebug UP-TO-DATE
:react-native-maps:compileDebugSources UP-TO-DATE
:react-native-maps:assembleDebug UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1 mins 2.795 secs
======================================================`
[stacktrace.txt](https://github.com/lelandrichardson/react-native-maps/files/331242/stacktrace.txt)

![screenshot_2016-06-24-10-40-08](https://cloud.githubusercontent.com/assets/8817995/16328651/e28b047c-39f9-11e6-8fd7-a6908d0170bf.png)

**Comment by npomfret** [comment]
I have a similar issue but on android:

`E/ReactNativeJS: `Constructor` has no propType for native prop `AIRMap.cacheEnabled` of native type `boolean`
                                                         If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.`

Using rn 0.28 and maps 0.6.0

**Comment by sagarsuryawanshi** [comment]
This is the logcat for the error:"Could not find generated setter for class " what does it mean ?

`
06-24 18:45:48.704 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
06-24 18:45:48.706 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
06-24 18:45:48.712 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
06-24 18:45:48.725 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
06-24 18:45:48.728 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
06-24 18:45:48.739 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
06-24 18:45:48.739 20039-20071/com.awesomeproject I/OpenGLRenderer: Initialized EGL, version 1.4
06-24 18:45:48.748 20039-20071/com.awesomeproject D/OpenGLRenderer: Enabling debug mode 0
06-24 18:45:48.752 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
06-24 18:45:48.759 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
06-24 18:45:48.760 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
06-24 18:45:48.768 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
06-24 18:45:48.769 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
06-24 18:45:48.774 20039-20039/com.awesomeproject W/unknown:React: Unable to dispatch keyboard events in JS as the react instance has not been attached
06-24 18:45:48.782 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
06-24 18:45:48.792 461-486/? I/ActivityManager: Displayed com.awesomeproject/.MainActivity: +746ms
06-24 18:45:48.800 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
06-24 18:45:48.804 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
06-24 18:45:48.805 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
06-24 18:45:48.811 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
06-24 18:45:48.813 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
06-24 18:45:48.817 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
06-24 18:45:48.823 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
06-24 18:45:48.829 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
06-24 18:45:48.833 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
06-24 18:45:48.835 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
06-24 18:45:48.839 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
06-24 18:45:48.843 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageViewManager
06-24 18:45:48.846 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageShadowNode
06-24 18:45:48.851 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
06-24 18:45:48.863 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
06-24 18:45:48.865 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
06-24 18:45:48.866 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
06-24 18:45:48.873 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
06-24 18:45:48.884 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
06-24 18:45:48.897 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
06-24 18:45:48.899 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
06-24 18:45:48.906 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
06-24 18:45:48.915 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
06-24 18:45:48.921 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapCalloutManager
06-24 18:45:48.924 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapMarkerManager
06-24 18:45:48.933 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapPolylineManager
06-24 18:45:48.936 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapPolygonManager
06-24 18:45:48.946 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapCircleManager
06-24 18:45:48.953 20039-20072/com.awesomeproject W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapManager`

**Comment by kulicuu** [comment]
I got the same error just now.  

I had this working last week, ran into some warnings earlier which only prevented the map from rendering, fixed those, now it red-screen crashes and need to restart with `react-native run-android` which red-screens and throws again.

**Comment by RoelWKramer** [comment]
We experience the same problem, on android.

initialRegion and region:
```
06-30 16:35:29.436  7141  7170 I ReactNativeJS: { speed: 0,
06-30 16:35:29.436  7141  7170 I ReactNativeJS:   heading: 0,
06-30 16:35:29.436  7141  7170 I ReactNativeJS:   accuracy: 20,
06-30 16:35:29.436  7141  7170 I ReactNativeJS:   longitude: 5.09096,
06-30 16:35:29.436  7141  7170 I ReactNativeJS:   altitude: 0,
06-30 16:35:29.436  7141  7170 I ReactNativeJS:   latitude: 52.09358666666667,
06-30 16:35:29.436  7141  7170 I ReactNativeJS:   latitudeDelta: 0.0025,
06-30 16:35:29.436  7141  7170 I ReactNativeJS:   longitudeDelta: 0.0025 }
```

The java error
```
06-30 16:35:29.469  7141  7171 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.AirMaps.SizeReportingShadowNode
06-30 16:35:29.477  7141  7141 D AndroidRuntime: Shutting down VM
06-30 16:35:29.498  7141  7141 E AndroidRuntime: FATAL EXCEPTION: main
06-30 16:35:29.498  7141  7141 E AndroidRuntime: Process: com.confy.delivery.debug, PID: 7141
06-30 16:35:29.498  7141  7141 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method zztU()Lcom/google/android/gms/dynamic/LifecycleDelegate; in class Lcom/google/android/gms/maps/MapView$zzb; or its super classes (declaration of 'com.google.android.gms.maps.MapView$zzb' appears in /data/app/com.confy.delivery.debug-1/base.apk)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.AirMaps.AirMapView.<init>(AirMapView.java:71)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.AirMaps.AirMapManager.createViewInstance(AirMapManager.java:70)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.AirMaps.AirMapManager.createViewInstance(AirMapManager.java:27)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:205)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:855)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:823)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-30 16:35:29.498  7141  7141 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-30 16:35:29.499  1518  1698 W ActivityManager:   Force finishing activity com.confy.delivery.debug/com.confy.delivery.MainActivity
06-30 16:35:29.522  1185  1185 E EGL_emulation: tid 1185: eglCreateSyncKHR(1315): error 0x3004 (EGL_BAD_ATTRIBUTE)
```

**Comment by RoelWKramer** [comment]
it probably has to do with not having google services installed on my emulator. Additionally it looks like i had to follow directions in this post.

https://github.com/lelandrichardson/react-native-maps/issues/249

**Comment by alvelig** [comment]
I recently made a fresh example build with pods.
https://github.com/alvelig/react-native-maps.
Try to check it out or build through the README.MD. If it does not help, let me know.
