### ISSUE TITLE
Callout does not update after markers prop change

### ISSUE THREAD

**Issue by VinceBT** [react-community/react-native-maps#324]
My markers change colors when depending on if the users specifies a certain option. When the option is called and all the markers are rebuilt with the same key prop, the callout remains  the same.

**Comment by yonahforst** [comment]
you can try setting the key attribute on <Marker/> to include the color (or some attribute that drives the color). That way when the color changes, the marker is redrawn with a new key

**Comment by alvelig** [comment]
Duplicate of #486

**Comment by nguyenanhthai** [comment]
Please check this 
https://github.com/react-native-community/react-native-maps/issues/486#issuecomment-515340764
