### ISSUE TITLE
How to search for an address and update the map view?

### ISSUE THREAD

**Issue by nschurmann** [react-community/react-native-maps#347]
I need to search for an address by the user input, and after that return a lat-lon object so i can show him that spot in the maps. Any pointers with this?

**Comment by symmetriccurve** [comment]
Use GoogleMapAPI:
"https://maps.googleapis.com/maps/api/geocode/json?&address=<Location>"
parse the JSON and use animateToRegion method to take to the location.

ProTip: use the responseData.results[0].types[0] to set the Zoom Level of the Map.
More here: 
https://developers.google.com/places/supported_types

**Comment by alvinthen** [comment]
@symmetriccurve how does type of the place decide the zoom level?

**Comment by alvelig** [comment]
https://github.com/devfd/react-native-geocoder
Example: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
