### ISSUE TITLE
Two markers in same position, one hides the other

### ISSUE THREAD

**Issue by aforty** [react-community/react-native-maps#350]
I have some edge cases where I end up having two markers in the same position (but showing distinctly different data points, so they are necessary). I'm changing the selected marker's color with `onSelect` and it works nicely, except for the cases where I have two markers, where one hides the other. Is there anyway to deal with this, forcing a marker to be "on top" at render? Only other thing I can think of would be to only render the first marker at a specific position, unless a the selected marker is in the same position. Kind of a dirty hack that I'd rather not implement.

Any thoughts?

**Comment by KGALLET** [comment]
I got the same problem, in my app, sometimes there were markers at the same positions,
I wrote a little function which move markers a bit, here is what I did, maybe you can use it in your app or get inspired by to implements your own function.

In my map component : (simplified version)
```
  constructor(props) {
    super(props)
    const self: any = this
    self.onRegionChange = this.onRegionChange.bind(this)
    self.onLoadMoreContents = this.onLoadMoreContents.bind(this)
    self.mapContainerStyle = this.mapContainerStyle.bind(this)
    this.rebuildMarkers = true
}

componentWillReceiveProps(nextProps) {
    if (this.props.events !== nextProps.events) {
      this.rebuildMarkers = true
    }
}


render() {
   return (
     <MapView
            style={ this.mapContainerStyle() }
            region={ this.state.region }
            onRegionChange={ this.onRegionChange }
            showsUserLocation
      >
          { this.getMarkers() }
     </MapView>
  )
}
```

and the function : (there are probably things useless for you in the function)

```
  getMarkers() {
    const { onEventPress, events } = this.props
    if (!this.rebuildMarkers) {
      return this.markers
    }
    this.rebuildMarkers = false
    const markers = {}
    this.markers = []
    events.forEach(event => {
      const venuesSeen = new Set()
      event.schedules.edges.forEach((edge, idx) => {
        const schedule = edge.node
        if (schedule.isExpired || schedule.nextDate === null) {
          return
        }
        let coordinate = getCoordinatesFromSchedule(schedule) // this return me the coordinates of my event
        if (coordinate === null) {
          return
        }
        const currentVenueId = schedule.venue.edges[0].node.id
        if (venuesSeen.has(currentVenueId)) {
          return
        }
        venuesSeen.add(currentVenueId)

// i think the most interesting part of the function for you is there :

        const markerStr = coordinate.latitude + '_' + coordinate.longitude
        if (markerStr in markers) {
          let newLat = markers[markerStr].coordinates.latitude
          let newLng = markers[markerStr].coordinates.longitude
          if (markers[markerStr].nb % 6 === 0) {
            newLat = coordinate.latitude
          } else {
            newLng = newLng + (0.1 / 3000)
          }
          newLat = newLat + (0.1 / 3000)
          coordinate = { latitude: newLat, longitude: newLng }
          markers[markerStr] = {
            'coordinates': coordinate,
            'nb': markers[markerStr].nb + 1
          }
        } else {
          markers[markerStr] = {
            'coordinates': coordinate,
            'nb': 1
          }
        }

        this.markers.push(
          <MapView.Marker
            key={ this.props.after + event.id + idx }
            coordinate={ { latitude: coordinate.latitude, longitude: coordinate.longitude } }
            event={ event }
            eventId={ event.id }
            onSelect={ () => this.setState({ eventSelected: event }) } // not possible yet on Android see. (https://github.com/lelandrichardson/react-native-maps/issues/227)
            onEventPress={ onEventPress }
          />
        )
      })
    })
    return this.markers
  }

```

The function is maybe hard to understand but it does what I needed :)

Enjoy 👍

**Comment by aforty** [comment]
Hey that's great, thank you for posting that! Yeah I was thinking about something like that but at the end of the day decided it wasn't worth the hassle. I may lift some of your code though, and will certainly post if I come up with a better solution.

**Comment by nathanwaters** [comment]
Some compact code for anyone else who comes across this issue. Adjust for your own circumstances :)

```
const filteredLocations = arr => {
  const hash = Object.create(null);
  const result = arr.map(x => {
    const { lat, lng } = x.location;
    const latLng = `${lat}_${lng}`;
    if (hash[latLng]) {
      return {
        ...x,
        location: {
          lat: lat - 0.0001,
          lng,
        },
      };
    }
    hash[latLng] = true;
    return x;
  });
  return result;
};
```

**Comment by junaid7898** [comment]
> Some compact code for anyone else who comes across this issue. Adjust for your own circumstances :)
> 
> ```
> const filteredLocations = arr => {
>   const hash = Object.create(null);
>   const result = arr.map(x => {
>     const { lat, lng } = x.location;
>     const latLng = `${lat}_${lng}`;
>     if (hash[latLng]) {
>       return {
>         ...x,
>         location: {
>           lat: lat - 0.0001,
>           lng,
>         },
>       };
>     }
>     hash[latLng] = true;
>     return x;
>   });
>   return result;
> };
> ```

slight adjustments if you have more then 2 markers at the same point
  const filteredLocations = (arr) => {
    const hash = Object.create(null);

    const processedLocations = arr.map((x) => {
      const { latitude: lat, longitude: lng } = x.coordinates;
      const latLng = `${lat}_${lng}`;

      // Check if this combination of latitude and longitude has been encountered before
      if (hash[latLng]) {
        // If it has, increment the offset based on the number of occurrences
        const offset = hash[latLng];
        hash[latLng] += 1;

        return {
          ...x,
          coordinates: {
            latitude: lat - offset * 0.00001,
            longitude: lng,
          },
        };
      }

      // If it hasn't been encountered before, mark it as seen in the hash table with an offset of 1
      hash[latLng] = 1;

      // Return the original location if it's the first time encountering this combination
      return x;
    });

    return processedLocations;
  };

**Comment by LockeandDropit** [comment]
> `>` Some compact code for anyone else who comes across this issue. Adjust for your own circumstances :)
> 
> > ```
> > const filteredLocations = arr => {
> >   const hash = Object.create(null);
> >   const result = arr.map(x => {
> >     const { lat, lng } = x.location;
> >     const latLng = `${lat}_${lng}`;
> >     if (hash[latLng]) {
> >       return {
> >         ...x,
> >         location: {
> >           lat: lat - 0.0001,
> >           lng,
> >         },
> >       };
> >     }
> >     hash[latLng] = true;
> >     return x;
> >   });
> >   return result;
> > };
> > ```
> 
> slight adjustments if you have more then 2 markers at the same point
> 
> ```
>   const filteredLocations = (arr) => {
>     const hash = Object.create(null);
>     const processedLocations = arr.map((x) => {
>       const { latitude: lat, longitude: lng } = x.coordinates;
>       const latLng = `${lat}_${lng}`;
>       // Check if this combination of latitude and longitude has been encountered before
>       if (hash[latLng]) {
>         // If it has, increment the offset based on the number of occurrences
>         const offset = hash[latLng];
>         hash[latLng] += 1;
>         return {
>           ...x,
>           coordinates: {
>             latitude: lat - offset * 0.00001,
>             longitude: lng,
>           },
>         };
>       }
>       // If it hasn't been encountered before, mark it as seen in the hash table with an offset of 1
>       hash[latLng] = 1;
>       // Return the original location if it's the first time encountering this combination
>       return x;
>     });
>     return processedLocations;
>   };
> ```

Hot dang man thank you. I could find nothing even close to a solution. This is fantastic.
