### ISSUE TITLE
blank map on android

### ISSUE THREAD

**Issue by samuelcalegari** [react-community/react-native-maps#354]
Hello
I have a blank map when I start emulation in Genymotion : 
![snap01](https://cloud.githubusercontent.com/assets/15143054/16564095/fbf4e2c0-4205-11e6-8787-26a9f2a013a0.jpg)

here's my android sdk manager : 
![snap04](https://cloud.githubusercontent.com/assets/15143054/16564119/11d1fad8-4206-11e6-9e1f-b67b16e85344.jpg)

I use a browser key in google API

![snap02](https://cloud.githubusercontent.com/assets/15143054/16564134/235d011c-4206-11e6-9700-0e68bd63dec6.jpg)

![snap03](https://cloud.githubusercontent.com/assets/15143054/16564137/2629bfa2-4206-11e6-88b6-616d043aa414.jpg)

here's my code : 

**index.android.js**

```
import React, { Component } from 'react';
import {
  AppRegistry,
} from 'react-native';

import Home from './Home';

class GMapDemo extends Component {
  render() {
    return (
      <Home></Home>
    );
  }
}

AppRegistry.registerComponent('GMapDemo', () => GMapDemo);
```

**Home.js**

```
import MapView from 'react-native-maps';

import React, { Component } from 'react';
import {
  StyleSheet,
  View,
} from 'react-native';

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: 400,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});

class Home extends Component {

  constructor() {
    super();
  }

  render() {

    return (
    <View style ={styles.container}>
      <MapView
        style={ styles.map }
        initialRegion={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        }}
      />
    </View>
    );
  }

}

export default Home;
```

AndroidManifest.xml

![snap05](https://cloud.githubusercontent.com/assets/15143054/16564297/fe2b8c14-4206-11e6-8e2e-df16f0805420.jpg)

only logo google appears :(

Thanks a lot !

**Comment by dhdo** [comment]
Hi @samuelcalegari, have you tried using a Android Key instead? You can find the steps in the [Installation Guide](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md)

**Comment by samuelcalegari** [comment]
thanks for your repply, I'm going to try !

**Comment by kfiroo** [comment]
@samuelcalegari Any luck? I'm having a similar issue.

All seems to be configured correctly and the Map shows fine on iOS, blank on Android :(

**Comment by robmoorman** [comment]
Try installing Google Play Services (or uses the Google API's in you emulator)

**Comment by kfiroo** [comment]
@robmoorman Thanks, setting the **Target** in the emulator device settings to **Google APIs...** resolved it.

**Comment by samuelcalegari** [comment]
@robmoorman i m in formation i Will t'y this as soon as possible

**Comment by krokofant** [comment]
I have the same problem running an a stock Nexus 5 device and I've tried both a browser key and Android key.

**Comment by samuelcalegari** [comment]
@kfiroo how do you setting the Target in the emulator device settings to Google APIs ? thanks

**Comment by KGALLET** [comment]
@samuelcalegari Quand tu ouvres ton gestionnaire d'émulateur, dans les paramètres : (when you set settings of the emulator) [](http://4.bp.blogspot.com/-opYcbxEVwQ4/UOKgbx7-iTI/AAAAAAAAAIY/9Ed6Z9lf_0E/s1600/011+AVD+Manager.png)

**Comment by kfiroo** [comment]
This is the current setup I got it to work with:

* note the CPU/API: Google APIs..

![image](https://cloud.githubusercontent.com/assets/284636/16900333/f73f0a74-4c2a-11e6-9ed2-dae41c986a55.png)

**Comment by samuelcalegari** [comment]
@kfiroo @KGALLET 
Thanks for your replies, but I use for the moment Genymotion, should I use AVD instead ?
Merci pour vos réponses, actuellement j'utilise Genymotion, dois-je utiliser AVD à la place ?

**Comment by KGALLET** [comment]
@samuelcalegari I don't know how to use Genymotion, I always works with AVD, maybe someone here an help you more than me.

**Comment by uriklar** [comment]
Anyone resolve this issue? 
I'm using genymotion with google play services and google apps installed. Andriod v6 API v23
I've tried everything in the installation guide but i'm still getting an empty map (only the google logo appears...)

Thanks!
Uri

**Comment by uriklar** [comment]
Might be a newb thing to mention, but your api key should be written without the enclosing {{ }}. 
Took me some time to find that out :-) 
Also make sure there are no referrer restrictions

**Comment by samuelcalegari** [comment]
@uriklar thanks to your reply, I'm going to try this ;)

**Comment by benderlidze** [comment]
@uriklar You saved my day! that should be in the installation guide!

**Comment by bfarrgaynor** [comment]
Confirmed you need to do two things:

In your AndroidManifest.xml put in your key like this: (fake key in example)
```
     <meta-data
     android:name="com.google.android.geo.API_KEY"
     android:value="AIzaSyC_J20BIuzKvk234238298FtlYR423w18"/>
```

And in your Google API settings go into both the ...

Google Maps Android API
Google Maps JavaScript API

... and enable them at the top. This got my maps working.

<img width="1194" alt="screenshot 2016-12-15 08 31 33" src="https://cloud.githubusercontent.com/assets/1213836/21225914/391556fa-c2a1-11e6-8646-477c2648e902.png">

**Comment by arasKruh** [comment]
I figured out the only reason my map was "blank" was that the size was too big for the emulator - hours and hours and hours to figure out that the airbnb tutorial mentioned 400x400 and mine needed 200x400.  Oy!

**Comment by mshameer** [comment]
Here is a complete configured sample application for android just clone it and do npm install the application will show you the map

https://github.com/mshameer/react-native-maps-sample

**Comment by bochen2014** [comment]
1. make sure when you create AVD, target set to 'google api'
2. make sure your API has 'google maps Android API' enabled

they both have been mentioned in above discuession

**Comment by alvelig** [comment]
That's google api_key problem. Verify your log on Android. It will tell you that key is not found and will have links to configure it

**Comment by apamphilon** [comment]
I managed to fix this by registering my API key for android use. 

Section 5 of the troubleshooting section here:

https://github.com/react-community/react-native-maps/blob/5f7bb26d2878b59ff3a66a05bb0238c8b47be177/docs/installation.md

**Comment by rborn** [comment]
@apamphilon finally somebody that reads the docs 🤗

**Comment by donmesserli** [comment]
Anytime I get to the Google API page, it shows that I have no projects. My company has dozens of projects.
