### ISSUE TITLE
Get the position fetched from showsUserLocation

### ISSUE THREAD

**Issue by VinceBT** [react-community/react-native-maps#360]
When showsUserLocation is used, the blue dot coordinates are not the same than what I get from the RN Geolocation API. Is there a way to get those coordinates ?

**Comment by Elyx0** [comment]
Are they more accurate than the RN Geolocation ? I'm not sure which one to use in my project :/

**Comment by VinceBT** [comment]
They are. Most of the time the blue dot is closer to the real coordinates. Problem is that the two geolocations are different.

**Comment by lixiaolihua** [comment]
+1

**Comment by VinceBT** [comment]
+1

**Comment by ababba15** [comment]
These  values are different and `showsUserLocation` is updating better^ faster and more close to real position. Please provide us some api to get coordinates from that awesome blue dot : )

**Comment by rborn** [comment]
Closing, should be implemented by https://github.com/react-community/react-native-maps/pull/2032
