### ISSUE TITLE
Custom View Marker broken on iOS with react-native 0.29

### ISSUE THREAD

**Issue by rops** [react-community/react-native-maps#364]
The custom view marker seems to be broken on iOS with react-native 0.29. It shows up as a regular red pin marker. Also tested with the sample app, same problem there.

**Comment by rops** [comment]
"Arbitrary Views as Markers"

![screen shot 2016-07-07 at 16 21 42](https://cloud.githubusercontent.com/assets/693182/16658643/01f71bba-445f-11e6-9baa-59c82569a1e9.png)

**Comment by rops** [comment]
I've done some digging around. 
It seems like `[self shouldUsePinView]` always returns false.

```
- (BOOL)shouldUsePinView
{
    return self.subviews.count == 0 && !self.imageSrc;
}
```
Shouldn't it be querying `reactSubviews` instead? With that change, it works as expected.
It it not using `reactSubviews` on purpose? Shall I open a PR?

**Comment by aforty** [comment]
This fixed it for me as well. Did you create a PR for your fix?

**Comment by trajedy** [comment]
Can also confirm that the above fixed my issue
