### ISSUE TITLE
'Configuration with name 'default' not found' by rnpm

### ISSUE THREAD

**Issue by limulidae** [react-community/react-native-maps#372]
still fail in v0.7.1

we have many libs to upgrade, so it would be big help if rnpm is able to handle this.

**Comment by dstnation** [comment]
Fix, temporary

$ rnpm link react-native-maps
Then
Edit "android/settings.gradle" file 

----------
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android**/lib**') <-- just add **/lib**

----------
After Clean project then 
$ react-native run-android

**Comment by alexHlebnikov** [comment]
'/lib' solved the issue. 
I think this needs some addition mentioning on Installation page.

**Comment by dstnation** [comment]
Thx @alexHlebnikov

**Comment by yanikproulx** [comment]
Hi @alexHlebnikov I have tried this and still get the error. Maybe I haven't cleaned the project (as you mentioned) properly? What are the exact steps you syggest (iOS and Android)? Thank you.

**Comment by VinceBT** [comment]
What works for me in react-native@0.30.0 : 

- Use ```react-native upgrade``` to remove all modifications made by rnpm. Type 'y' each time it asks to replace something (make a copy in case ou made some custom mods).
- Type ```rnpm link```
- Make the modifications for installation which are listed ![https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md](here)
- Type ```react-native run-android``` and eveything works again !

**Comment by pocesar** [comment]
for me I was missing the compiler 25.0.2, but was giving this cryptic error
