### ISSUE TITLE
Still encountering "Native component for "AIRMap" does not exist"

### ISSUE THREAD

**Issue by Ac2zoom** [react-community/react-native-maps#375]
I've attempted all the solutions proposed in issue responses, including the most recent, but am still receiving the error mentioned in the title (as well as the associated ones with regards to the different aspects of AIRMap).  All current code on the feature-MapView branch of https://github.com/ZacBlanco/Repo-10/tree/front-end

**Comment by Daniellt1** [comment]
Hi,
I have exactly the same issue. I have almost the same code as **Ac2zoom**, the only one difference in android/settings.gradle:

`include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android/**lib**')`

Can someone help with it, please?

Kind regards,
Daniel

**Comment by nilsonivano** [comment]
@Daniellt1 Can you explain me better where to put the new MapsPackage() on MainApplication.java?

**Comment by eangfmbs** [comment]
that a good point Daniellt1. but why wen i browse and cannot find lib in the /node_modules/react-native-maps/android folder. still stuck :(

**Comment by stereodenis** [comment]
I got it on iOS
what am I doing wrong?

**Comment by stereodenis** [comment]
@spikebrehm

**Comment by gilbox** [comment]
If you get this error then most likely the native dependencies are not properly linked in your native project.

**Comment by jayhuang75** [comment]
@stereodenis Did you fix your issues for iOS? Please advices! Thanks

**Comment by eScribMac** [comment]
@jayhuang75 did you follow the instructions [here](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md)?

**Comment by jayhuang75** [comment]
@eScribMac! I have fixed the issues by https://github.com/airbnb/react-native-maps/issues/969

**Comment by duhaime** [comment]
I came here with the same issue on ios, and resolved it by simply running `react-native link`.

**Comment by abhishekpandey747** [comment]
@Daniellt1 it's too late to answer  hope it will help someone else in future , but i think you have installed the react-native-maps-google , which will lead you to the `project(':pptmapview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps-google/android/library')`
insted of 
`project(':pptmapview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps-google/android/')`.
This is what I found while installing.

**Comment by vnhnhm** [comment]
`react-native unlink react-native-maps && react-native link react-native-maps` might help.

**Comment by idan-ratzabi** [comment]
On Android don't forget to add "MapsPackage" to getPackages inside your ReactApplication instance.

**Comment by SiyabongaNzulwana** [comment]
Guys Im facing the same issue, on iOS, tried your solutions, none work for me

**Comment by carlosacabrera** [comment]
Don' forget to kill the build and rerun `react-native run-ios` after you link react-native-maps

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by anandbabud1987** [comment]
The below worked for me. I used both google maps and react maps. hence faced same issue.

react-native unlink react-native-maps && react-native link react-native-maps
npm uninstall react-native-google-maps
kill the build and rerun react-native run-ios

**Comment by mymai91** [comment]
@anandbabud1987 Work for me, Thanks

**Comment by alliuca** [comment]
this https://github.com/react-community/react-native-maps/issues/1391#issuecomment-330961899 helped me after attempting all of the above without luck. I am on RN 0.52

**Comment by noumanDev** [comment]
Tried all the solution, but i am still facing 
`Native component for "AIRMap" does not exist`

Followed the installation docs
1. npm install react-native-maps --save
2. use the same code in podfile and then run pod install
3. Then use the following code in my component 
```
import MapView from 'react-native-maps';
...
 <MapView
    initialRegion={{
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    }}
  />
....
```

but still got the  "airmap" does not exist error

**And please someone explain me without react-native link react-native-maps, how can it mapped? please explain someone as its my first react-native ios project.
and help me out, spend 2 days on this error**

**Comment by danielptm** [comment]
@noumanDev Im having the same issue after trying much of the above advice

**Comment by noumanDev** [comment]
@danielptm yup its working for me now, 8 days ago they have upadated react-native-maps on npm. 
after their latest release, i created the project from scratch, with latest react-native version 0.54.4 and latest react-native-maps 0.21.0 everything works fine, just followed the instruction, this time no error shown.

**Comment by vctqs1** [comment]
@noumanDev  I have latest react-native-maps 0.21.0 and have same error.

**Comment by pawarvijay** [comment]
@noumanDev 
If you guyz are still getting "AIRMap" error Or if you have run `react-native link`
please follow this answer 
https://stackoverflow.com/a/50777873/1390678

**Comment by jdonald** [comment]
Ironic that a bunch of answers here say they solved it by running `react-native link react-native-maps` yet [the instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md) still say:
**!! DO NOT USE !!** `react-native link`

Not sure what to believe, but I use link command. I also had to apply mikemorris's solution in #2159 for iOS, although that probably isn't the same issue that people were hitting in 2016 and 2017.

**Comment by Khsed4** [comment]
The same issue in August 2018 with React-Native 56

**Comment by Luckygirlllll** [comment]
@Khsed4 I have the same error, did you find the solution?

**Comment by Khsed4** [comment]
@Luckygirlllll yes I solved my problem with not using _react-native link_ , since it miss up all the project , so u need to link the library with your project manually.
