### ISSUE TITLE
Some image markers fail to render when lots of image markers are rendered

### ISSUE THREAD

**Issue by christianversloot** [react-community/react-native-maps#385]
In my app, I have to render a lot of image-based markers based on the conditions specified in a source file that I use. When few positions are in the file, everything goes well. On a larger amount, I sometimes see that image markers fail to render with an image, but instead render with the standard marker icon. See screenshot. I have no root of this issue.

![image](https://cloud.githubusercontent.com/assets/6450612/16763844/1e0aacca-482b-11e6-849e-af2b106d571f.png)

**Comment by ramirogm** [comment]
Can you share your code?
