### ISSUE TITLE
I want to change the content of `showsUserLocation` marker callout.

### ISSUE THREAD

**Issue by jacklam718** [react-community/react-native-maps#391]
I want to change the content of showsUserLocation marker callout, does anyone knows how to do it? Does this library expose any of API can let me do that?

**Comment by VinceBT** [comment]
I don't think there is any right now. The marker is managed by the Google package itself. Maybe try fetching user location and display your custom marker by hand. If you wanna track the movement just add a listener with watchPosition and update the marker position [Docs here](https://facebook.github.io/react-native/docs/geolocation.html)
