### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by maheshiv** [react-community/react-native-maps#392]
Hi @lelandrichardson,
I am using React V15.2.0, ReactNative V0.29, react-native-maps V0.7.1
When i run `react-native run-ios`, it shows 

```
../node_modules/react-native-maps/ios/AirMaps/AIRMap.h:12:9: fatal error: 
      'React/RCTComponent.h' file not found
#import <React/RCTComponent.h>
        ^
1 error generated.

** BUILD FAILED ** 
```

What will be the work around for this?

**Comment by arthurnn** [comment]
@maheshiv I was having the same issue. https://github.com/lelandrichardson/react-native-maps/issues/371#issuecomment-231585153 fixed for me.

**Comment by asafratzon** [comment]
Hi,
I encountered the same issue but the suggested fixes (in all other issues) didn't solve the problem for me.
This is my first project in React Native and the first time I work with xCode (new to mac), so if everyone else got their builds going I probably miss something basic.

I'm using react 15.2.1, react-native 0.29 and react-native-maps 0.7.1.

Reading other people's comments I felt that some stuff were left vague in the installation process, but I followed the instructions to get it working for iOS simulator only (to begin with), step by step.

This is what I did:

**Step 1**. Installed react-native-maps 0.7.1 .
**Step 2**. ran 'rnpm link'. a little note about this step - in one of my many attempts to solve the problem I wanted to re-link the binaries, but no matter how many times I cleaned the build, re-installed the pods, or tried to unlink - the output always remained:
```
rnpm-link info Android module react-native-maps is already linked 
rnpm-link info iOS module react-native-maps is already linked 
```
Can anyone explain why?

**Step 3**. Installed Cocoapods according to [this](https://shift.infinite.red/beginner-s-guide-to-using-cocoapods-with-react-native-46cb4d372995#.o4ys0ecww) article.
This is how my Podfile looks like:
```
platform :ios, '8.0'
use_frameworks!
workspace 'appName.xcworkspace'
project 'appName.xcodeproj'

target 'appName' do
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
end
```
And this is my Podfile.lock:
```
PODS:
  - React (0.11.0):
    - React/Core (= 0.11.0)
  - react-native-maps (0.7.1):
    - React
  - React/Core (0.11.0)

DEPENDENCIES:
  - react-native-maps (from `../node_modules/react-native-maps`)

EXTERNAL SOURCES:
  react-native-maps:
    :path: ../node_modules/react-native-maps

SPEC CHECKSUMS:
  React: ab1a2e21deb34965c38328d5ec40cc7d12c6050a
  react-native-maps: 15971c9c1822446d98724df9f49399a6b0d73f03

PODFILE CHECKSUM: 8f1c7ee120c139535c2cb6279c9acc3a9570750d

COCOAPODS: 1.0.1
```
I ran 'pod install'.

**Step 4**. Then, when I try to build (react-native run-ios) this is the output:
```
In file included from /Users/asafratzon/projects/triotaxi/triotaxi_customer_client/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m:10:
In file included from /Users/asafratzon/projects/triotaxi/triotaxi_customer_client/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.h:11:
/Users/asafratzon/projects/triotaxi/triotaxi_customer_client/node_modules/react-native-maps/ios/AirMaps/AIRMapCallout.h:13:29: error: unknown
      type name 'RCTBubblingEventBlock'
@property (nonatomic, copy) RCTBubblingEventBlock onPress;
                            ^
/Users/asafratzon/projects/triotaxi/triotaxi_customer_client/node_modules/react-native-maps/ios/AirMaps/AIRMapCallout.h:13:1: error: property
      with 'copy' attribute must be of object type
@property (nonatomic, copy) RCTBubblingEventBlock onPress;
^
```

If I try to build in xCode I see the `Framework not found React` error during the linking process, although when I select my app's workspace it seems like React is linked:
![image](https://cloud.githubusercontent.com/assets/2094413/16894676/4d09ded6-4b66-11e6-86a6-f918efa0a3af.png)

Any help is much appreciated.
Thanks.
Asaf.

**Comment by willks** [comment]
@maheshiv I got it working after making the import changes mentioned in the same ticket - but found it thanks to your post.(#371)

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by MaheshNandam** [comment]
react - 16.0.0
react-native - 0.54

'React/RCTNetworking.h' file not found, did anyone resolve this?
