### ISSUE TITLE
How to make Uber like map? The map which is getting rendered through google API is not so catchy. how can i make it look attractive?

### ISSUE THREAD

**Issue by sayedatif** [react-community/react-native-maps#396]
what i see right now.
![img_20160716_115529](https://cloud.githubusercontent.com/assets/6937774/16893139/a2120f76-4b4c-11e6-83a7-e43f2e1afc92.JPG)

can i make it catchy or attractive by using camera angles or any similar thing? can anybody guide me on this?

**Comment by zelll** [comment]
There are so many issues here. I don't think the devs will be happy when they see your "how to" questions. Please try Google/Stackoverflow and keep the devs focusing on other issues.
