### ISSUE TITLE
Image Overlay?

### ISSUE THREAD

**Issue by dtruel** [react-community/react-native-maps#400]
Hi,

I have a gif I want to overlay.  It is US weather radar:

http://radar.weather.gov/ridge/Conus/RadarImg/latest_radaronly.gif

Is there a way I can do this with this plugin?  I saw there are polygon overlays, but I did not see an image overlay.

**Comment by Nodonisko** [comment]
+1

**Comment by sunglee** [comment]
@lelandrichardson Any plan to support image overlay yet? Thanks.

**Comment by anupkale1984** [comment]
+1

**Comment by zolrath** [comment]
:+1: I would love to be able to show something as simple as a logo on the top center of the map but still have Callouts appear above it when Markers are pressed.

**Comment by kanekotic** [comment]
+1

**Comment by danielreuterwall** [comment]
I got an image overlay to the map like this.

`<MapView></MapView>
<View pointerEvents="none" style={{position: 'absolute', top: x, left: y}}>
  <Image source={{uri: 'zzz'}} />
</View>`

The pointerEvents="none" makes sure the map gets all touch events. Hope this helps.

**Comment by Nodonisko** [comment]
But we want overlay, not something like watermark :) Overlay should reflect zoom, tilt etc.

**Comment by danielreuterwall** [comment]
Ah, misunderstood :)

**Comment by fmelp** [comment]
+1 on image overlay responsive to zoom and rotation

**Comment by alvelig** [comment]
Duplicate of #103
