### ISSUE TITLE
rnpm link problem when using react native 0.29.1

### ISSUE THREAD

**Issue by lcustodio** [react-community/react-native-maps#401]
The last version throws the following problem:

```
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.
```

**The fix is** to change `build.gradle`:

```
--wrong--
compile project(':react-native-maps')
--right--
compile 'com.airbnb.android:react-native-maps:0.7.1'
```

After this, including `new MapsPackage()` on the MainApplication.java throws compilation error because a library is missing:

**The fix is** to include a library in the `MainApplication.java`:

There is a confusion problem between MainActivity.java and MainApplication.java.

There reference to the library `com.airbnb.android.react.maps.MapsPackage` is made at Activity instead of Application.

**Comment by skellock** [comment]
Part of the issue here was that React Native 0.29 was broken for linking Android binaries.  0.29.2 has since been released which now supports MainActivity vs MainApplication.

**Comment by DVassilev** [comment]
I had to replace the line the build.gradle file as well.

**Comment by VinceBT** [comment]
Is it possible to make a PR to change what rnpm does for the package and applies the installation process ?

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
