### ISSUE TITLE
[android] fitToElements does not account for the anchor of <Markers/>

### ISSUE THREAD

**Issue by erickreutz** [react-community/react-native-maps#404]
When trying to fitToElements it seems to be fitting to the coordinates of the elements rather then the bounding box of the elements themselves. Is this a known issue?

**Comment by pablood85** [comment]
Hi @erickreutz, do you have this problem? 
![fit](https://cloud.githubusercontent.com/assets/1504797/16953385/3245dc6e-4da3-11e6-9166-a34e62198fcd.jpg)

**Comment by erickreutz** [comment]
What problem are you referring to? My problem is it's fitting to the coordinates not to the elements.

**Comment by pablood85** [comment]
My Custom Callout does not fit the width of the inner markup, when it opens, it is truncated at the width of the marker. However, it does not seems related to your issue.

**Comment by rborn** [comment]
closing, very old
