### ISSUE TITLE
Issues with my rendered Markers/Pins only on Android

### ISSUE THREAD

**Issue by BigPun86** [react-community/react-native-maps#407]
I am using RN 24.1 and react-native-maps v0.4.2

If i render multiple pins on my Map View, than on ANdroid the first time it is rendered, not all pin images are rendered. The second time it always works great. I have problems to locate this and find the certain source code for this implementation. 

First Search:

![screenshot_20160720-144326](https://cloud.githubusercontent.com/assets/7880624/16989357/37337ba4-4e94-11e6-9f50-871eb8f9bcb0.png)

Second Search:

![screenshot_20160720-144845](https://cloud.githubusercontent.com/assets/7880624/16989374/468bf02c-4e94-11e6-9e36-eaf9bbe0ed03.png)

In the first screen you can see that at the bottom, the first pin has no pin image, only the text i am rendering in the pin itself. On the second screenshot u can see the correct pin image 

Any ideas what to do? Updating react-native-maps forces me to update the whole project, and the project is at a point where it might be to big and risky to update RN and its dependencies....

**Comment by bcalik** [comment]
Same issue here. Please fix this.

**Comment by MatiMil** [comment]
Yep, got the exact same one. Nice Documentation btw

**Comment by jeveloper** [comment]
Brings good memories, i drove this route with my family :)

**Comment by BigPun86** [comment]
hahah :P

**Comment by sayedatif** [comment]
Do anybody has idea how to render markers within specfic radius near user location?

**Comment by JohnyDays** [comment]
@sayedatif track the user's region and then remove from your markers any ones outside the radius

**Comment by carbureted** [comment]
I'm getting this on the latest version of react-native and react-native-maps with a basically fresh project. What code are people using to work around this?

**Comment by sayedatif** [comment]
hey can any one help me with how to calculate distance between user location and the marker so to check whether it fits inside the radius or not?

**Comment by saberking** [comment]
use haversine

**Comment by seppemarotta** [comment]
Do any body know the fix ?
I'm having the same issue.

**Comment by jeveloper** [comment]
I believe its fixed, please use RN 42+ and this lib 0.13 
i suggest looking into creating groups of pins

**Comment by alvelig** [comment]
Merging to #1870
