### ISSUE TITLE
Force redraw

### ISSUE THREAD

**Issue by BigPun86** [react-community/react-native-maps#408]
Is there any way to force a redraw with this module?

My problem is, that my pin images are not always rendered when i intially open the map.So i thought as a workaround i could just use a way to force a redraw....

**Comment by VinceBT** [comment]
What do you mean by redraw ? Try using this.forceUpdate() after your markers have been built

**Comment by efkan** [comment]
When changing custom MapMarkers `backgroundColor` (maybe an image source) current markers aren't been affected. Reloading makes markers refreshed with the latest changes.

**Comment by efkan** [comment]
I guess that when [this issue](https://github.com/airbnb/react-native-maps/issues/924) is resolved, then this issue would be resolved :)

**Comment by alvelig** [comment]
Merge to #1870
