### ISSUE TITLE
Expose userLocation on MapView?

### ISSUE THREAD

**Issue by Jarred-Sumner** [react-community/react-native-maps#430]
Right now, to get the user's current location on the map, I'm doing:

``` javascript
navigator.geolocation.getCurrentPosition(
      (position) => {
        const region = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta: 0.15,
          longitudeDelta: 0.15
        }
      },
      null,
      {enableHighAccuracy: true, timeout: 20000, distanceFilter: 20}
    );
```

However, this call is very slow on real devices (~700ms-10000ms) and I know that [`MKMapView` provides a `userLocation` property](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapView_Class/#//apple_ref/occ/instp/MKMapView/userLocation) that is very quick. This makes for a bad user experience.

Is there any way this can be exposed to the `MapView` component? It makes using this library a not-so-good user experience for my particular use case (showing crowdsourced Pokemon sightings on a map).

**Comment by raubas** [comment]
If you intend to zoom to the user, doesn't this work #313 ? 

getCurrentPosition gets triggered time the GPS updates location I think.!
