### ISSUE TITLE
Image in callout

### ISSUE THREAD

**Issue by arashbi** [react-community/react-native-maps#431]
Is it possible to reander an image in the callout?

**Comment by jeveloper** [comment]
Yes but its buggy as hell on android, it becomes a clickable area and acts as pressed/depressed.

they should just copy paste what they did for marker (image property) to callout
Do you think its possible @lelandrichardson 
thanks

**Comment by arashbi** [comment]
I tried an Image tag on CustomCallout, but it didn't work on ios simulator

**Comment by esutton** [comment]
I have custom callout with a TextInput and a camera button. This works fine on iOS.

On Android, any touch anywhere in the callout, highlights the *entire* callout.  

I cannot activate either the TextInput or the button?

```
  "dependencies": {
    "react": "15.0.2",
    "react-native": "0.26.2",
    "react-native-image-picker": "^0.21.4",
    "react-native-maps": "^0.4.2",
  }
```

**Comment by esutton** [comment]
Still an issue after upgrading RN and maps on Android.  Anyone find a solution?
```
    "react-native": "^0.32.0",
    "react-native-maps": "^0.8.0",
```

Actually 0.80 is worse since now my custom callout maximum width is constricted on both Android and iOS.

<img width="163" alt="screen shot 2016-08-31 at 10 59 02 am" src="https://cloud.githubusercontent.com/assets/6115047/18136171/fbca27c4-6f69-11e6-8015-70c06120c875.png">

**Comment by jeveloper** [comment]
Ouch  @esutton 
Is this on RN 32

Are you using absolute dimensions for callout, checkout commits , there were changes on callouts

**Comment by esutton** [comment]
@jeveloper Yes
```
    "react-native": "^0.32.0",
    "react-native-maps": "^0.8.0",
```

**Comment by jeveloper** [comment]
Sorry but did you try explicitly setting width in pixels , you can use Dimensions of your current window and scale based on that.

**Comment by esutton** [comment]
@jeveloper Thank you so much for taking your time to suggest a fix!

This works! 

I will research a more screen display independent solution.
```
            <MapView.Callout
            style={{ flex: -1, position: 'absolute', width:400}}
```

Bigger snippet:
```
          {this.state.markers.list.map(marker => (
            <MapView.Marker
            ref={marker.label}
            key={marker.key}
            coordinate={marker.coordinate}
            pinColor={marker.color}
            onPress={() => this.onMarkerPress(marker)}
            onSelect={() => this.onMarkerSelect(marker)}
            onCalloutPress={() => this.onCalloutPress(marker)}
            >

            <MapMarkerWaypoint marker={marker} />
            <MapView.Callout
            style={{ flex: -1, position: 'absolute', width:400}}
            tooltip={false} >
            <MapCalloutWaypoint marker={marker} unitType={this.props.state.unitType}/>
            </MapView.Callout>
            </MapView.Marker>
          ))}
```

**Comment by jeveloper** [comment]
Happy to help @esutton , now you've got to visit Toronto , coffee and treats on me :)

By the way, you'll find this super useful: 

```
import RN from 'react-native'
const {
  Dimensions
} = RN

let { width, height } = Dimensions.get('window')

```

**Comment by esutton** [comment]
@jeveloper Thanks again for the tip.  I'd love to visit Toronto as I never have.

I bet Toronto could be a cool city to schedule some training next year.  I started diving into react native development this February after coming to conclusion that my cross-platform desktop & mobile development with Qt was not delivering a good mobile UI experience ( desktop UI not so bad ).

Coming from C++ I could ***really*** use some training in JavaScript, react, or react native.   This is a strange new world.  A 4-day break to focus on learning stuff from experts would be welcome.

Thanks again for your help!

**Comment by jeveloper** [comment]
Im happy to help! A company i consult for (Surgeforward) supports me in OSS.

Yeah id love to show you around ! With Canadian dollar you'll be getting eveyrthing for about 20-30% off.

Reach out to me via email or let me know how to find you.

**Comment by esutton** [comment]
Problem still exists on latest everything:
		"react": "16.0.0",
		"react-native": "^0.50.3",
		"react-native-maps": "^0.17.1",

Image displays as gray rectangle.

<img width="420" alt="screen shot 2017-11-08 at 3 01 40 pm" src="https://user-images.githubusercontent.com/6115047/32574098-ca377e1e-c495-11e7-9c4c-2e95ddbac0df.png">

Sadly I also had to hide my camera button, as I understand buttons are not supported in react-native-maps marker on Android.

[How to insert button in custom marker](https://github.com/airbnb/react-native-maps/issues/211#issuecomment-342449160)

> "this is a limitation of the Google Maps library on Android and react-native-maps"

Has anyone had success displaying images on Android inside a callout?

**Comment by jeveloper** [comment]
Thanks for providing an update on this , wow , last time i worked on this issue was over a year ago and its still a problem . Works great on IOS (love apple's platform)

**Comment by alvelig** [comment]
Merging to #1870

**Comment by zauribrahimkhalilov** [comment]
This solution worked for me

`<Callout
                                    style={{ flex: 1, position: 'absolute', minWidth: 200, minHeight: 60 }}
                                >
                                    <Card>
                                        <CardItem cardBody>
                                            <ImageBackground source={{ uri: 'YOUR_URL' }}
                                                style={{ height: 120, width: null, flex: 1 }}
                                                resizeMode='cover'></ImageBackground>
                                        </CardItem>
                                        <CardItem>
                                            <Text>{i.title}</Text>
                                        </CardItem>
                                    </Card>
                                </Callout>`

**Comment by AnthonyDugarte** [comment]
I found this while looking for a solution to this problem. Fully working on Android.

> If you use Image Component inside Text component image will be rendered.

[source](https://stackoverflow.com/questions/54703716/custom-callout-image-not-rendering-in-android-api-level-26-react-native-maps)

**Comment by malFuckingFurion** [comment]
> I found this while looking for a solution to this problem. It worked for me.
> 
> > If you use Image Component inside Text component image will be rendered.
> 
> [source](https://stackoverflow.com/questions/54703716/custom-callout-image-not-rendering-in-android-api-level-26-react-native-maps)

It work for me
Use Image inside Text component

<Text>
<Image style={{ height: 100, width:100 }} source={{ ... }} resizeMode="cover" /></Text>``

**Comment by mbrucher** [comment]
Using react-native-paper Card inside a Callout, and trying to display an Avatar.Image inside the left element doesn't work and cannot wrap it inside a Text element.
Is there a standard way of doing this or is it a Google bug that they don't care enough to solve?
I have other issues with their Badge that also doesn't display properly on Android maps.

**Comment by osvald0** [comment]
Have you any update about this issue? The workaround using the Text component don't work for me. Thanks!

**Comment by thanhluantl2304** [comment]
> Have you any update about this issue? The workaround using the Text component don't work for me. Thanks!

Ya. Me not working too. I don't know why this issue still there! Anyone can help me?

**Comment by osvald0** [comment]
@thanhluantl2304 My workaround was display the content in a modal. I've added to the maker onPress event a function to set a modal visible and also set the needed information.

**Comment by thanhluantl2304** [comment]
> @thanhluantl2304 My workaround was display the content in a modal. I've added to the maker onPress event a function to set a modal visible and also set the needed information.
So the modal will show inside the callout element or somewhere?

**Comment by osvald0** [comment]
No, I'm not using callout in this solution.
Here an example:

```
  <>
                <MapEventModal
                    modalVisible={this.state.modalVisible}
                    setModalVisible={this.setModalVisible}
                    title={title}
                    score={score}
                    description={description}
                    siteUrl={siteUrl}
                    images={images}
                    locale={locale}
                />
                <MapView
                    loadingEnabled={true}
                    style={styles.map}
                    initialRegion={{
                        latitude,
                        longitude,
                        latitudeDelta: 0.0043 / 2,
                        longitudeDelta: 0.0034 / 2,
                    }}
                >
                    {events && events.map(e =>
                        <Marker
                            key={e.id}
                            coordinate={{ latitude: Number(e.latitude), longitude: Number(e.longitude) }}
                            identifier={e.title}
                            tracksViewChanges={true}
                            tracksInfoWindowChanges={true}
                            ref={ref => { this.marker2 = ref; }}
                            onPress={() => this.setModalVisible(!this.state.modalVisible, e)}
                        >
                            <View>
                                <View style={styles.makerContainer}>
                                    <Text style={styles.makerText}>
                                        {e.name}
                                    </Text>
                                </View>
                                <Icon
                                    name={'map-marker'}
                                    type='font-awesome'
                                    size={30}
                                    color={randomColor()}
                                    containerStyle={{ marginLeft: 5 }}
                                />
                            </View>
                        </Marker>
                    )}
                </MapView>
            </>
```

**Comment by ninareunes** [comment]
> > I found this while looking for a solution to this problem. It worked for me.
> > > If you use Image Component inside Text component image will be rendered.
> > 
> > 
> > [source](https://stackoverflow.com/questions/54703716/custom-callout-image-not-rendering-in-android-api-level-26-react-native-maps)
> 
> It work for me
> Use Image inside Text component
> 
> ```
> <Text>
> <Image style={{ height: 100, width:100 }} source={{ ... }} resizeMode="cover" />
> </Text>
> ```

I tried this approach and it worked! Thanks a lot. Only problem I have now is that there appears to be "a border" around my Text Component (see picture). I tried setting borderWidth to 0 but nothing changes.

I use "react-native-maps": "~0.25.0". 
And my code is: 
`<Text style={styles.calloutViewImage}>
                            <Image
                              style={styles.calloutImage}
                              source={{ uri: `${coordinate.img}` }}
                            />
                          </Text>`

![image](https://user-images.githubusercontent.com/44461009/70856107-66844300-1ed6-11ea-8b22-53af0311359b.png)

Is there anyway to hide this?

**Comment by sasan-ebrahimi** [comment]
I tried many things and finally I found a solution. Worked for me on Android. Just putting Image tag inside a Text tag

<Text><Image .../></Text>

**Comment by MustaphaGhlissi** [comment]
Actually, rendered **Image** inside a **Text** doesn't work properly,
Same for **WebView** use case, it's not possible to control **Image** display such as ResizeMode inside it while **WebView** source is the image link  !

**_Solution:_**
An alternative solution is to use **[react-native-svg Image](https://github.com/react-native-svg/react-native-svg#image)** 


Code example: 
   ```
 Import {Svg, Image as ImageSvg} from 'react-native-svg';

                <Svg width={240} height={120}>
                        <ImageSvg
                            width={'100%'} 
                            height={'100%'}
                            preserveAspectRatio="xMidYMid slice"
                            href={{ uri: 'http://lorempixel.com/400/200/'}}
                        />
                    </Svg>
```

**Comment by auggustus6** [comment]
Cool, but when I add an image to the callout it often takes a long time to load or sometimes it doesn't, can you tell me why?

**Comment by Dekartmc** [comment]
> En realidad, la **imagen** renderizada dentro de un **texto** no funciona correctamente, lo
> mismo para el caso de uso de **WebView** , no es posible controlar la visualización de la **imagen** como ResizeMode dentro de ella mientras que la fuente de **WebView** es el enlace de la imagen.
> 
> **_Solución:_**
> una solución alternativa es utilizar**[ react-native-svg Image](https://github.com/react-native-svg/react-native-svg#image)**
> 
> Ejemplo de código:
> 
> ```
> Import {Svg, Image as ImageSvg} from 'react-native-svg';
> 
>              <Svg width={240} height={120}>
>                      <ImageSvg
>                          width={'100%'} 
>                          height={'100%'}
>                          preserveAspectRatio="xMidYMid slice"
>                          href={{ uri: 'http://lorempixel.com/400/200/'}}
>                      />
>                  </Svg>
> ```

The best solution!
