### ISSUE TITLE
Breaks on 0.30

### ISSUE THREAD

**Issue by yeegr** [react-community/react-native-maps#432]
Was working fine under 0.28, but had to update to 0.30 due to other packages. Now build fails

The following build commands failed:
    CompileC /Users/yeegr/Desktop/trails/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCallout.o AirMaps/AIRMapCallout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by olegdizus** [comment]
Same problem

**Comment by sarovin** [comment]
#411

**Comment by esutton** [comment]
@sarovin On iOS should applying #411 resolve issue with 0.30 ?

I modified the package.json 
`  "react-native": ">=0.30.0"`

and the two iOS header file imports as een in #411.

I am getting issue with AIRMapPolygonManager

** BUILD FAILED **

```
The following build commands failed:
	CompileC /Users/edward3/Documents/projects/react-native/field-planner-mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/
AIRMapPolygonManager.o AirMaps/AIRMapPolygonManager.m normal 
x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/edward3/Documents/projects/react-native/field-planner-mobile/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: xcodebuild process exited with code 65
    at ChildProcess.<anonymous> (runIOS.js:102:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by sarovin** [comment]
@esutton  see this #426

**Comment by abuammar** [comment]
i am getting the same issue

**Comment by abuammar** [comment]
following build commands failed:
	CompileC /Users/ws1/Code/mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCircle.o AirMaps/AIRMapCircle.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by raphaelboukara** [comment]
Not working for me 😞
my config:
```
os: sierra
ruby: 2.2.0
node: 8.6.0
react-native-cli: 2.0.1
react-native: 0.51.0
react-native-maps: 0.19.0
```
I think I am doing the same of the @alvelig example, but I receive:
```
Installing build/Build/Products/Debug-iphonesimulator/ReactNativeMapsPodsExample.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ReactNativeMapsPodsExample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```
Any idea?

**Comment by alvelig** [comment]
@raphaelboukara Which XCode version?

**Comment by raphaelboukara** [comment]
@alvelig sorry, XCode: 8.1

**Comment by alvelig** [comment]
@raphaelboukara mind updating? The error should be gone after update.

**Comment by alvelig** [comment]
@raphaelboukara please let us know if it's ok after update or not, for our knowledge and to be able to help others if they are experiencing the same.

**Comment by raphaelboukara** [comment]
@alvelig working with XCode 9.2
![image](https://user-images.githubusercontent.com/6442236/34256103-65d708de-e65c-11e7-870a-080ad0c26d85.png)
