### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by samcambridge** [react-community/react-native-maps#435]
Hi,

Couldn't see this anywhere so hoping someone can help. I've followed the install instructions for android and my app works until I introduce the MapView. I'm calling it like:

`import { MapView } from 'react-native-maps';` and my render method looks like: 

```
render() {
    return (
      <View style={styles.container}>
        <Text>Hi</Text>
        <MapView />
      </View>
    );
  }
```

The error I get when loading into an emulator is:

![genymotion_for_personal_use_-_google_nexus_6_-_6_0_0_-_api_23_-_1440x2560__1440x2560__560dpi__-_192_168_56_101](https://cloud.githubusercontent.com/assets/884310/17213057/8c55e20c-54ca-11e6-8225-f09058d2b010.png)

If I remove the `<MapView />` it renders. I'm super new to react native so if it's something obvious I'm sorry!

**Comment by dozoisch** [comment]
@samcambridge There is an issue with your import. It's supposed to be 

```
import MapView from 'react-native-maps';
```

without the curly braces around MapView.

**Comment by nomoreboredom** [comment]
import * as MapView from 'react-native-maps'; solved this for me
