### ISSUE TITLE
Markers buggy on 0.30.0

### ISSUE THREAD

**Issue by yonahforst** [react-community/react-native-maps#436]
Custom markers became buggy on iOS and Android when upgrading from 0.28.0 to 0.30.0,
### iOS
- marker sometimes stay in the same screen position
- custom marker onSelect only called when marker pressed just outside the view. It looks like onPress is consuming the click and not letting the callout show.
  ![srrgzinqgv](https://cloud.githubusercontent.com/assets/1440796/17217605/3579c10e-54e5-11e6-8794-aa85204bc5fc.gif)

![ezgif com-gif-maker 1](https://cloud.githubusercontent.com/assets/1440796/17217937/5ebcd8d4-54e6-11e6-92ff-1cadb4a6f656.gif)
### Android
- custom marker drawn slightly above coordinate
- custom callout clipped halfway
  ![pnso6eusy2](https://cloud.githubusercontent.com/assets/1440796/17218816/7935d474-54e9-11e6-90d8-2940dcdcec9c.gif)

**Comment by LeBlaaanc** [comment]
I'm having a similar issue on 0.29.2.

**Comment by carleryd** [comment]
I am also experiencing this with react-native@0.30.0 and react-native-maps@0.7.1 using <MapView.Marker> with <Image> inside on both iPad, iPhone and simulator. Works great on Android though!

**Comment by monotv** [comment]
Markers with a custom images are broken too. Also on react-native@0.30.0 and react-native-maps@0.7.1

**Comment by yonahforst** [comment]
has anyone tested this on 0.31.0?

**Comment by nazywamsiepawel** [comment]
@yonahforst I'm using it with 0.31 now - callouts are cut off, markers' onSelect is giving some random clicks.

**Comment by pellepersson** [comment]
Any luck with this? I am experiencing a similar issue in iOS with react-native@0.31 and react-native-maps@0.7.1.

Everything works as expected using the standard marker, but when using anything else (just a view with a height, width and background color set as a simple example), the "onSelect" event is triggered (or "showCallout" method is called) randomly. The "onPress" event is triggered at every click on the marker though, but it is just not passing the event to whatever should happend next...

**Comment by alexHlebnikov** [comment]
I'm having slightly different issue with markers on Android. 
My markers have a custom image inside and a label. But they renders everytime in different way. 
For example, one time 3 of 5 markes renders without image, only with label. Another time they renders without images at all. On a third time markers renders with images, but some of images are unexpectedly becames semitransparent... And so on. And this happens each time I reload my map. 

I think there is something wrong with markers rendering and updating logic in Android code.

**Comment by pellepersson** [comment]
After looking into it a bit more, I believe that my problems has to do with memory issues. So probably not that related to this issue... Sorry for disturbing. :)

**Comment by kevinvangelder** [comment]
I'm having the same iOS issues on RN0.31. The custom image markers are not clickable until you zoom in. Once you've zoomed in you can zoom out again and all the markers are clickable.

**Comment by esutton** [comment]
On RN 0.32 and react-native-maps 0.8.0

Custom callouts on both Android and iOS render with what appears to be a constricted maximum width?

@nazywamsiepawel is that what you mean by  callouts are cut off ?

Before:
<img width="267" alt="dff6e5a0-5aec-11e6-985a-9e82fd57e6a0" src="https://cloud.githubusercontent.com/assets/6115047/18136704/44668a1c-6f6b-11e6-8406-b55d6879b443.png">

On RN 0.32 and react-native-maps 0.8.0 cuts off width of callout.
<img width="163" alt="screen shot 2016-08-31 at 10 59 02 am" src="https://cloud.githubusercontent.com/assets/6115047/18136653/267f30e4-6f6b-11e6-812e-cfeab74078da.png">

**Comment by nazywamsiepawel** [comment]
@esutton I'm having the same issue. 0.32.0 and 0.8.0 too. 

<img width="132" alt="screen shot 2016-09-08 at 10 08 48" src="https://cloud.githubusercontent.com/assets/334875/18343679/46472494-75ac-11e6-9b50-ec923b1045e7.png">

**Comment by esutton** [comment]
@nazywamsiepawel  A work-around was solution was given to me by @jeveloper in issue https://github.com/lelandrichardson/react-native-maps/issues/431

This works for me:
```
            <MapView.Callout
            style={{ flex: -1, position: 'absolute', width:400}}
```
@jeveloper recommended a screen dependent approach
```
import RN from 'react-native'
const {
  Dimensions
} = RN

let { width, height } = Dimensions.get('window')

```

**Comment by nazywamsiepawel** [comment]
@esutton - thanks, I tried that and it helped with the sizing. My remaining issues are custom markers that are positioned over the custom callouts and seemingly random callout appearances (sometimes they don't appear after clicking on the custom marker). Have you experienced any similar issues? I'm compiling an issue now.

Thanks!

**Comment by esutton** [comment]
@nazywamsiepawel No.  That description does not sound familiar.

My custom callout appears over the custom marker only when user touches the associated custom marker.

**Comment by ewindso** [comment]
@yonahforst re: 'marker sometimes stay in the same screen position'

were you able to figure out a solution for this one?  i'm on 0.33 and 0.8.2 and just noticed.

**Comment by yonahforst** [comment]
After migrating to 40.0, I no longer have an issue with the callout sizes, but I'm still having on issue with onSelect

**Comment by alvelig** [comment]
Should be already fixed. If no let us know.
