### ISSUE TITLE
How to push view down on marker press?

### ISSUE THREAD

**Issue by Dudyboy** [react-community/react-native-maps#437]
Hi everybody,

could you please help me how to pull down view on Marker press? Now, when I press on Marker, the map is centered, so Marker is in center of screen, but I need pull down all MapView with marker to have more place for CalloutView above. I hope I explained well.

Thanks for answers.

**Comment by VinceBT** [comment]
You cannot place a marker below the center of its coordinates. If you use some margins to force it you will see the marker is cut.
