### ISSUE TITLE
How does the extension of the Animated API work?

### ISSUE THREAD

**Issue by perkola** [react-community/react-native-maps#438]
As it is right now, animating markers result in smooth animations when zommed out and very jumpy when zoomed in. I suspect this is because the animation of the marker is done by "stepping" towards the new latitude/longitude, however I can't find it [here](https://gist.githubusercontent.com/lelandrichardson/c0d938e02301f9294465/raw/5053cebc66989d27697bbb08450f360555309b0c/AnimatedImplementation.js). When zoomed in the steps are more notable since they cover more of the screen and thus the result becomes very jumpy as opposed to when zoomed out the steps in the animation are very small and look more smooth.

Would it be possible to instead animate to the relative position of the marker on the screen? That way the animation would be smooth regardless of zoom.

Any ideas on how this would be achieved?

**Comment by erickreutz** [comment]
I'm also interested to hear how the region is animated in Objc and Java land.

**Comment by rborn** [comment]
I will close this for now as it's an old issue. Please comment if you want it re-opened but first have a look at the latest code, maybe you can find what you want to know.
