### ISSUE TITLE
calling a React.PropTypes validation function WARNING

### ISSUE THREAD

**Issue by L3V147H4N** [react-community/react-native-maps#441]
React 15.3.0 Warnings about this are going crazy, any idea when this usage of PropTypes is going to be refactor?

for ex:

![image](https://cloud.githubusercontent.com/assets/5846479/17280238/90bb4852-5761-11e6-8b92-bd0f53c8aae1.png)

**Comment by bingle87** [comment]
Any luck with solving this issue?

**Comment by L3V147H4N** [comment]
I'm resuming my project in React Native this weekend so I'll let you know

**Comment by rborn** [comment]
PropTypes moved to it's own module: https://reactjs.org/docs/typechecking-with-proptypes.html - read the starting note.
