### ISSUE TITLE
First init freeze; Blackbox when animated (Android)

### ISSUE THREAD

**Issue by akoshman** [react-community/react-native-maps#444]
Hi there,

I've added `react-native-maps` inside to a one tab managed by [react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view) component. With that component you can navigate between tabs like you do in Youtube or Periscope apps.

But when I navigate from one tab to another one which contains map component, it freezes for a moment (can be seen on the video below). Then, if I tap and scroll between the tabs (the both tabs are visible), the black container behind the map is visible (this container isn't mine, it belongs to the map).

[Here is the link to the video where both of issues can be clearly seen. ](https://www.youtube.com/watch?v=KaKc8trRRe4)

Is there any way to solve these issues or any work around?

Thank you for your afford.

**Comment by VinceBT** [comment]
The freeze comes from the fact that the View was not created before you scrolled. This is surely because your tab manager creates it only when it needs to be rendered.
For the blackbox, avoid putting a MapView in a swipable container for the moment.

**Comment by akoshman** [comment]
@VinceBT Thank you for your reply.
The freeze I kinda solved with setting property `loadingEnabled=true` for `<MapView />` component.

As for blackbox, I can't avoid putting MapView in a swipable container because I want to get a Periscope similar behavior for the map. It would be cool to swipe horizontal tabs with one contained a map. Can you point where can be a problem with blackbox? Is it because of native map can't re-render fast enough when moving? Or is it because of JS<->Native bridge or React Native is slow? Is there any tricks or hacks that would help here?

And I have one more question.
Now the all area of the MapView is draggable. Is it possible to make it all draggable but except 10-15 pixels on the border to make it possible to kinda bubble up user events? Like we can drag over the map but swipe it's tab on the borders -> http://i.imgur.com/R59QJCh.png

**Comment by VinceBT** [comment]
I think the problem comes from the bridge between Native and JS.
I know that when you put a View on top of the MapView it lets touch events pass if it has no backgroundColor or if there is nothing to be rendered inside.
Try adding after your MapView :
```jsx
<View style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 100, backgroundColor: 'transparent' }} />
```
The ```backgroundColor: 'transparent'``` is a quick trick to render an invisible View that can receive touch events.

**Comment by akoshman** [comment]
I've tried this hack but it didn't help... `ViewPagerAndroid ` is used as a container for tabs and it consumes a bunch of `View`s but doesn't react to nested components like a `View` on top of `MapView`

**Comment by VinceBT** [comment]
Even if your page view is designed like this ? :
```jsx
<View style={{ flex: 1, position: 'relative' }}>
  <MapView
    style={{ flex: 1 }}
    ...otherProps />
  <View style={{
    position: 'absolute',
    bottom: 0, left: 0, right: 0,
    height: 100, backgroundColor: 'transparent' }} />
</View>
```

**Comment by akoshman** [comment]
If I make a page like this, the drag events from visible are propagated to underlying view only it it's not overlapped by MapView. I mean, if there's a free space between MapView and underlying View, it is draggable via transparent top View. But drag events made over the MapView neither makes page is being swiped nor changes the map's position

**Comment by alvelig** [comment]
On latest (0.19.0) does not happen
