### ISSUE TITLE
Update Android installation documentation

### ISSUE THREAD

**Issue by nsarafa** [react-community/react-native-maps#448]
Opened a [pull request](https://github.com/lelandrichardson/react-native-maps/pull/465) proposing an amendment [the Android installation documentation](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md#android) from setting `android:name="com.google.android.geo.API_KEY"` to `android:name="com.google.android.maps.v2.API_KEY"` for the meta-tag. This change got the maps view loading for me on Android. Still working through a fix for iOS

**Comment by kakbeya** [comment]
android:name="com.google.android.geo.API_KEY"  works for me with a browser key
android:name="com.google.android.maps.v2.API_KEY" works for me with an android key

**Comment by nsarafa** [comment]
@kakbeya interesting. I'll have to A/B test and see if it works within our project. Would be nice to leverage the same key across Android/iOS.

**Comment by JonoH** [comment]
For some reason both of the above meta-tags are working for me regardless of whether I use a browser or android key.  Both work with both.

**Comment by nsarafa** [comment]
@JonoH can think of two reasons as to why this might be happening.. 
1. You're using an `.env` module
2. Your Google dev console having both the Android and Browser keys set to `enabled`

Do you know which key is loaded when the gradle file compiles? Presumably, if you're using react-native, your aim is to build for both native clients simultaneously. Thus, it might be wise to go with the browser key, in the event the browser key is already taking precedence.
