### ISSUE TITLE
OnCameraChangeListener() is deprecated

### ISSUE THREAD

**Issue by alexHlebnikov** [react-community/react-native-maps#459]
[In 0.9.4 version of the API](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap), Google replaced _GoogleMap.OnCameraChangeListener()_ with three camera listeners :

GoogleMap.OnCameraMoveStartedListener
GoogleMap.OnCameraMoveListener
GoogleMap.OnCameraIdleListener

**Comment by IjzerenHein** [comment]
Fixed in PR #1710
