### ISSUE TITLE
GPS Detection

### ISSUE THREAD

**Issue by chansila** [react-community/react-native-maps#466]
Is their a way to always detected the app if GPS location was enable or disable ?

**Comment by scerelli** [comment]
I figured out how to do it on android, but not on ios. 
Check this package  `react-native-android-location-services-dialog-box`

**Comment by hkxicor** [comment]
react-native-android-location-services-dialog-box not working

**Comment by alvelig** [comment]
https://facebook.github.io/react-native/docs/geolocation.html
