### ISSUE TITLE
Build error testing on Emulator 

### ISSUE THREAD

**Issue by kcfgl** [react-community/react-native-maps#469]
Hey there - 

iOS is working great. But I'm hitting issues building successfully.  I've followed the troubleshooting guide, but seems I'm missing something.

Here is the error:

```
Execution failed for task ':react-native-maps:processReleaseResources'.
:react-native-maps:processReleaseResources[path to project]/node_modules/react-native-maps/android/lib/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/drawable-v23/abc_control_background_material.xml:18:24-59 : No resource found that matches the given name (at 'color' with value '@color/abc_color_highlight_material')

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/kanecochran/Library/Android/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1
```

I've confirmed I have the SDKs installed, cleaned cache, but still here.

RN 0.30 and RN Maps 0.7.1 developing on Mac.

Thanks!

**Comment by spikebrehm** [comment]
Can you see if this still is a problem with [0.8.0](https://github.com/lelandrichardson/react-native-maps/releases/tag/v0.8.0)?

**Comment by kcfgl** [comment]
Works great for me.  Thanks guys!!
