### ISSUE TITLE
showsUserLocation options?

### ISSUE THREAD

**Issue by lindsay-ablonczy** [react-community/react-native-maps#473]
For the app we're making we're using a bluetooth GPS device, but want to default to using the android GPS if the bluetooth somehow disconnects, so we'd like to not have the blue dot icon and the "zoom to self" button in the top right because we might be using location from another device. The problem is it seems like when we set showsUserLocation to false, it makes it so we can't get coordinates from the android GPS at all, and when it's set to true, we get that icon and button that we don't want. Is there any way for us to still be able to get the coordinates from the android GPS and not have to have the icon and button with it?

**Comment by alvelig** [comment]
showsMyLocationButton={false}
