### ISSUE TITLE
Transparent 'hud' like overlay

### ISSUE THREAD

**Issue by GustavoGramajo** [react-community/react-native-maps#476]
Hi, is possible to add an overlay view to a **MapView**, just a decorative view, that does not responds to any touch event? I tried the following:

```
<MapView
          style={styles.map}
          initialRegion={this.state.region}
          onPress={this.onMapPress}
          {...mapOptions}
        >

        <View style={styles.radar} onStartShouldSetResponderCapture={(e) => {

               return false;
          }} onMoveShouldSetResponder={(e) => {

               return false;
          }}

          >

</MapView>

```

I can get the **onMapPress** event fired, but the map loses the ability to scroll/pan, zoom in/out.

Any help would be appreciated,

Thanks.

**Comment by danielreuterwall** [comment]
If you still got this issue, I got an image overlay to the map like this.

```
<MapView></MapView>
<View
  pointerEvents="none"
  style={{position: 'absolute', top: x, left: y}}>
  <Image source={{uri: 'zzz'}} />
</View>
```

The pointerEvents="none" makes sure the map gets all touch events. Hope this helps.

**Comment by rborn** [comment]
This seems to be resolved. Closing.
