### ISSUE TITLE
showsPointsOfInterest has no effect

### ISSUE THREAD

**Issue by veedeo** [react-community/react-native-maps#480]
When I pass showsPointsOfInterest={false} I still see POIs like "Medical Center" or "Museum of Art"
how do I remove them completly?
Tested in android emulator

Thanks

**Comment by IgorVanian** [comment]
It seems that showsPointsOfInterest does nothing (on Android at least). I had the same issue and I solved it by using "customMapStyle" prop

Example to remove business and park POIs:

```javascript
customMapStyle={[
    {
	"featureType": "poi.business",
	"stylers": [
		 {
			 "visibility": "off"
                 }
	 ]
     },
     {
	"featureType": "poi.park",
	"elementType": "labels.text",
	"stylers": [
		{
			"visibility": "off"
		}
	 ]
    }
]}
```

Use [https://mapstyle.withgoogle.com/](url) to style your map then put the JSON object into the prop.

**Comment by luco** [comment]
@IgorVanian 's solutions didn't work for me. This worked:

```
var myStyles =[
		    {
		        featureType: "poi",
		        elementType: "labels",
		        stylers: [
		              { visibility: "off" }
		        ]
		    }
		];
```
