### ISSUE TITLE
Is it possible to disable showing callout on marker select

### ISSUE THREAD

**Issue by ronyv89** [react-community/react-native-maps#482]

**Comment by jaderYang** [comment]
any solusion?

**Comment by jaderYang** [comment]
+1

**Comment by Exilz** [comment]
Have you tried rendering a custom callout without children with the prop that disables the bubble style ?
It seems to be working for me (0.11 and react-native 0.36) :

```javascript
...
                <MapView.Marker
                  key={`marker-${index}`}
                  title={title}
                  coordinate={{ latitude, longitude }}
                >
                    <MapView.Callout tooltip={true} />
                </MapView.Marker>
```

**Comment by alvelig** [comment]
If @Exilz solution does not suit, provide a business logic example (why would you need it).

**Comment by Ibeihl** [comment]
hey there, this would be awesome, since there is a known bug for rendering images in a custom callout on android, it would be great to disable the google callouts on a marker press so you could fully implement your own custom callout. 

#https://github.com/react-native-community/react-native-maps/issues/1870

**Comment by mbrucher** [comment]
What's the status of this? As Google Maps is broken for displaying images and for buttons, a callout is the last thing I want to display.

**Comment by ReallyLiri** [comment]
The solution proposed works for me in iOS, but not in Android

**Comment by Eli-Nathan** [comment]
Also working on iOS but not Android 😔

**Comment by haeniya** [comment]
Does anyone have a working solution to completely disable / hide the callouts? The solution above is not working for me.

**Comment by dlombardi** [comment]
We need this in order to prevent callouts from showing if the end user is clicking around the markers too fast.  A way to debounce/throttle the callout interactions, if you will.

**Comment by vytautasvargonas** [comment]
workaround that works on Android:

```
<Callout tooltip={true}>
  <View style={{ width: 1, height: 1, backgroundColor: "transparent" }} />
</Callout>
```
