### ISSUE TITLE
Document steps for contributing

### ISSUE THREAD

**Issue by athaeryn** [react-community/react-native-maps#496]
I spent about an hour last night trying to get the example app running in Xcode so I could work on contributing a feature. It'd be awesome to document the steps needed to get things running (`npm run dev` in `example/`, which .xcodeproj to open, etc.). Relatedly, I still haven't figured out how to get things running in Android Studio...

Maybe there should be a [`CONTRIBUTING.md`](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)?

**Comment by alvelig** [comment]
@athaeryn That's the crucial moment. You can help. Please comment here: #1807.
