### ISSUE TITLE
Image markers error in iOS

### ISSUE THREAD

**Issue by sirgalleto** [react-community/react-native-maps#499]
When I load marks in a location out of the map region, the map render the images in one corner. 
![simulator screen shot aug 25 2016 2 24 57 pm](https://cloud.githubusercontent.com/assets/5873627/17983023/2048289c-6ad0-11e6-9506-72eb54720d76.png)

**Comment by villetou** [comment]
+1 Having the same issue

**Comment by sirgalleto** [comment]
So in the last version the images has bit sizes.

**Comment by Exilz** [comment]
This is still happening on 0.11, I guess it's a major issue for those experiencing it.

**Comment by hiaw** [comment]
I managed to solve it by wrapping the image in another component. Similar to this https://github.com/airbnb/react-native-maps/blob/master/example/examples/ViewsAsMarkers.js

**Comment by hiaw** [comment]
import React from 'react';
      import {Image} from 'react-native';

      const selectedMarkerImage = require('src/images/selected_marker.png')
      const markerImage = require('src/images/marker.png')

      export default class PriceMarker extends React.Component {
        render() {
          return (
            <Image source={this.props.selected ? selectedMarkerImage : markerImage} />
          );
        }
      }

**Comment by sirgalleto** [comment]
@hiaw mm nice, sounds like a good solution.

**Comment by alvelig** [comment]
Duplicate of #678
