### ISSUE TITLE
Combine markers

### ISSUE THREAD

**Issue by kitolog** [react-community/react-native-maps#510]
Hi all, I need to combine nearest markers to one marker with counter in it.
Maybe someone has an idea how to do this?

**Comment by java99** [comment]
+1

**Comment by alexHlebnikov** [comment]
If you need markers generalisation, take a look at this library: https://github.com/mourner/rbush

**Comment by nazywamsiepawel** [comment]
#213

**Comment by alvelig** [comment]
duplicate #213
