### ISSUE TITLE
Android: Cannot use measure function inside of Marker

### ISSUE THREAD

**Issue by carleryd** [react-community/react-native-maps#516]
I want to be able to tell where on the screen a marker is placed so that I can perform an animation at that position(creating a new image on top of the marker because animating marker size won't work on Android).
To solve this I tried to use the measure function on the child of the marker

```
componentDidMount() {
    setTimeout(this.measureStuff.bind(this));
}
measureStuff() {
    this.refs.markerview.measure((ox, oy, width, height) => {
        console.log("ox", ox, oy, width, height);
    });
}
...
<MapView.Marker>
    <View ref="markerview" collapsable={false} onLayout={() => {}}>
        <Image/>
    </View>
</MapView.Marker>
```

But everything logged in `measureStuff()` returns undefined. I tried this outside of the MapView and it worked, using this same technique.

So for some reason I cannot get the info of a View inside of the MapView(works on iOS). Does anyone have a clue how to solve this? The measure function is problematic on Android which is why I had to use tricks like `collapsable={false}` to make it work outside of the MapView.

**Comment by alexHlebnikov** [comment]
Are sure there is `measure` exists in `this.refs.markerview`? 
Btw, markers on Android are bitmaps and the they can't be animated.

**Comment by carleryd** [comment]
@alexHlebnikov The reason I want to use measure is to get the position on screen of a marker so that I can create a new image there which animates on create/remove of the marker, because it cannot be done with Android markers due to them being bitmaps.
How do you mean? I assume all View's have access to the measure function?

**Comment by alexHlebnikov** [comment]
You could be right about measure in markers, I honestly have no experience wtih it. But I thought on Android it could not work because of markers bitmap nature.

**Comment by alvelig** [comment]
@alexHlebnikov comment is right. IMHO WONTFIX
Maybe change Marker view? Let me know if it's still actual.

**Comment by vitto-moz** [comment]
it would be very useful to measure views inside marker within the map (get marker position relative to the screen) - with this data we can create/use markers/callouts outside the map and place them with absolute position over the map, this will bring a lot of cool stuff like animations and so on.

**Comment by vitto-moz** [comment]
@carleryd , have you found a solution? Please, share, if yes =)

**Comment by sevicbb** [comment]
@vitto-moz Have you found any solution for this? Currently, I'm using .measure() on View inside Marker, and I'm getting good values for width and height, but for x/y positions on screen, I'm getting some random large values, like 38095240, 36363636 etc

**Comment by vitto-moz** [comment]
Yes! now we have it! Thanks a lot for creators and maintainers - guys you are awesome! :) 
For those who are interested, please check the updated doc for `<MapView />` there is new method  called `pointForCoordinate` that cover the requirement I've mentioned above!
