### ISSUE TITLE
onCalloutPress-event doesn't work

### ISSUE THREAD

**Issue by ippa** [react-community/react-native-maps#521]
Have anyone gotten onCalloutPress-event to work? I've tried it both on MapView  and MapView.Marker and it won't trigger. I've tried it on the default callout-bubble but also on my own custom-made callout, silent in both cases.

On iOS, RN 0.33.0-rc0 and RN Maps master as of this writing.

**Comment by ippa** [comment]
I've confirmed this by adding `onCalloutPress={ e => console.log("calloutPress") }` to the Marker-components in the bundled Callouts.js example. No matter how i press/tap the default and custom callouts, that event wont be called. Still on iOS.

**Comment by esutton** [comment]
On RN 0.32 with RN Maps 0.8.0,  onCalloutPress is working for both iOS and Android. 

    "react": "^15.3.1",
    "react-native": "^0.32.0",
    "react-native-maps": "^0.8.0",

**Comment by ippa** [comment]
Hi @esutton thanks for replying.

So... I clone react-native-maps, edit package.json:

`   "dependencies": {
-    "react": "15.2.0",
-    "react-native": "^0.29.2",
+    "react": "15.3.1",
+    "react-native": "^0.32.0",
     "react-native-maps": "../"`

`npm install`

add some console.log's to exampl/exampels/Callouts.js  like this `<MapView.Marker ref="m2" coordinate={markers[1].coordinate} onCalloutPress={ e => console.log("calloutPress") }>`

The Callouts.js-example has 3 Markers, I add onCalloutPress-logging to all of them.

I compile the project with latest xcode and run it on my iphone 6.

The example-explorer comes up, pick "Custom Callouts"-example. I trigger the callouts by touching each marker one by one and then clicking on the callout itself. Nothing in the debug-window. I tried adding some other logging just to make sure the debug was live, and it is.

What do I miss here? What exactly does work for you?

What I did manage to get with that combination of versions was this new warning: `ExceptionsManager.js:78 Warning: ReactClass: You're attempting to include a mixin that is either null or not an object. Check the mixins included by the component, as well as any mixins they include themselves. Expected object but got undefined.`

**Comment by esutton** [comment]
I think MapView.Marker onCalloutPress is called only when you touch an open callout.

- I use onCalloutPress to hide the callout when user touches callout a second time.

**Comment by ippa** [comment]
That's what I do, I touch the open callouts. Are you testing this from within examples/Callouts.js?

**Comment by esutton** [comment]
I am not using **examples/Callouts.js**

Last time I tried I could not get it to run.  I should try again with latest release

**Comment by esutton** [comment]
@ippa  I could not get the example to work either.  

I never saw onCalloutPress in the debugger using iOS simulator when I added a console.log to display "'onCalloutPress" ?
 
```
  render() {
    const { region, markers } = this.state;
    return (
      <View style={styles.container}>
        <MapView
          style={styles.map}
          initialRegion={region}
        >
          <MapView.Marker
            ref={ref => { this.marker1 = ref; }}
            coordinate={markers[0].coordinate}
            title="This is a title"
            description="This is a description"
            onCalloutPress={() => console.log('onCalloutPress')}
      />
```

**Comment by crisu83** [comment]
@esutton I stumbled on the exact same issue when I wanted to navigate when you press the callout. Here is how I solved the issue:

```
<Marker key={index} coordinate={coordinates}>
  <Callout>
    <TouchableHighlight onPress={() => onMarkerPress({ id })} underlayColor="transparent">
      <Text>{title}</Text>
    </TouchableHighlight>
  </Callout>
</Marker>
```

It's not the most elegant solution, but at least it works.

**Comment by oksas** [comment]
@crisu83 thanks for the fix, and @ippa thanks for reporting this issue; I was _really_ confused why this wasn't working so I'm glad to see I'm not the only one. In order to make @crisu83's fix work, I had to provide a `width` and `height` prop to the `<Callout>`, otherwise a small, blank callout was showing up no matter what else I seemed to do. My final code then looks like:


```
<MapView.Marker
  key={marker._id}
  coordinate={tempLoc}
  pinColor="purple"
>
  <MapView.Callout width={40} height={40} >
    <TouchableHighlight
      underlayColor="transparent"
      onPress={() => console.log('callout was clicked')}
    >
      <Text>{marker.name}</Text>
    </TouchableHighlight>
  </MapView.Callout>
</MapView.Marker>
```

... where `marker` and `tempLoc` are other variables I have in my application, non-essential to this particular issue.

**Comment by lappalj4** [comment]
You can work around this issue by using the MapView.Callout onPress prop, which works on iOS as well. The only drawback is that since the onCalloutPress prop works as intended on android, you have to make sure you aren't firing click listeners twice.

**Comment by OmgDef** [comment]
I came up with this
```javascript
<MapView.Callout tooltip={true} width={210} onPress={() => console.log(123)}>
````

**Comment by pcooney10** [comment]
The `onCallOutPress` prop for `MapView.Marker` is still not working for me on iOS.
````json
    "expo": "^21.0.0"
    "graphql-tag": "^2.4.2",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
   "react-native-maps": "^0.16.4",
````
The current workaround is something janky like this:
````jsx
        <MapView.Marker
              key={marker.key}
              coordinate={marker.coordinates}              
              onPress={(Platform.OS === 'ios') ? () => console.log("callout was clicked") : null }
              onCalloutPress={(Platform.OS === 'android') ? () => console.log("callout was clicked") : null }
            />
````
Or the approach suggested by @oksas above: 
````jsx
            <MapView.Marker
              key={marker.key}
              coordinate={marker.coordinates}
            >
              <MapView.Callout
                onPress={() => console.log('callout was clicked')}
              >
                <Text style={s.calloutText}>{marker.title}</Text>
              </MapView.Callout>
            </MapView.Marker>
````

**Comment by alvelig** [comment]
Can't reproduce. The following works perfectly on 0.18.3:

```
onCalloutPress() {
    const { associated, dispatch, navigation, ...store } = this.props;
    if(associated) {
      dispatch(goTo({ routeName: "Store", params: store }));
    }
  }

  render(){

    const { id, name, address, associated, contacts = [], hours = [], location: { lat, lng }} = this.props;

    //image={markerIco}
    return (
      <Marker
        key={id}
        ref={(ref) => { this.ref = ref; } }
        title={name}
        description={address}
        onCalloutPress={this.onCalloutPress.bind(this)}
        coordinate={{ latitude: lat, longitude: lng }}>
        <BottleMarker associated={associated} />
        <Callout><StoreCallout {...this.props} /></Callout>
      </Marker>
    );
  }
```

**Comment by chrise86** [comment]
This is still an issue, but only when using Google maps.

**Comment by yareyaredesuyo** [comment]
↑ above PR Fixed iOS google maps callout problem?

**Comment by doongsilee** [comment]
I believe It's still not fixed.



```Javascript, JSX
{places.map(place => (
              <Marker
                store={place}
                identifier={place.name}
                coordinate={{
                  latitude: Number(place.y),
                  longitude: Number(place.x)
                }}
                onCalloutPress={() => console.log("onCalloutPressed")}
                title={place.name}
                description={place.category}
                image={require("../../assets/images/pin-normal.png")}
              />
            ))}
```

**Comment by izilla** [comment]
Not working for me either @doongsilee issue is reproducible for me too

**Comment by flashman2** [comment]
Still not working. Since 2016

**Comment by danieldanielecki** [comment]
> Still not working. Since 2016

the same thing in 2022, it doesn't work on `iOS`.

**Comment by jagthedrummer** [comment]
> > Still not working. Since 2016
> 
> the same thing in 2022, it doesn't work on `iOS`.

Still doesn't work in 2023.
