### ISSUE TITLE
iOS exception when double tap

### ISSUE THREAD

**Issue by sirgalleto** [react-community/react-native-maps#524]
In diferent iPhone models like 4s or 5c when I use a double tap to zoom in the app crash and throw a exception `libc++abi.dylib: terminating with uncaught exception of type NSException`

![screen shot 2016-09-01 at 10 16 23 am](https://cloud.githubusercontent.com/assets/5873627/18172988/6e7a4312-702d-11e6-8682-bf3f0d02820e.png)

**Comment by alvelig** [comment]
Let us know if experience that with latest version please.
