### ISSUE TITLE
Can't customize Map's Styles

### ISSUE THREAD

**Issue by rlkelly** [react-community/react-native-maps#537]
Google Maps typically allows for customization of mapviews, as in http://output.jsbin.com/fodapo/.  It would be nice to have this feature incorporated on the react-native api.

**Comment by damathryx** [comment]
+1

**Comment by damathryx** [comment]
+1

**Comment by nschurmann** [comment]
+1

**Comment by RWOverdijk** [comment]
👍

**Comment by alvelig** [comment]
As far as I know latest versions don't have this problem. Let me know if not
