### ISSUE TITLE
Question: how to make initial region to fit minimum dimension of map container?

### ISSUE THREAD

**Issue by alsh76** [react-community/react-native-maps#569]
at the moment a map fits to maximum dimension of its container and rest of the map is cut off. it looks like this (for ios platform)

![screen shot 2016-09-12 at 1 20 06 pm](https://cloud.githubusercontent.com/assets/8568628/18445959/019181c4-78ee-11e6-8b9d-d5f9b9fe7879.png)

is it possible to fit the map to minimum dimension of the container? like this

![screen shot 2016-09-12 at 1 17 55 pm](https://cloud.githubusercontent.com/assets/8568628/18446115/ce16081e-78ee-11e6-961f-8074e6e70133.png)

**Comment by rborn** [comment]
Not sure it's possible.

Closing as it's an old question
