### ISSUE TITLE
showUsersLocation not working as expected

### ISSUE THREAD

**Issue by raysmithdev** [react-community/react-native-maps#579]
`
<MapView
        style={styles.map}
        region={this.state.region}
        showsUserLocation={true}
        onRegionChange={this.onRegionChange}
      />
`

"If true the app will ask for the user's location. NOTE: You need to add NSLocationWhenInUseUsageDescription key in Info.plist to enable geolocation, otherwise it is going to fail silently!" - I have done this also but the Map does not ask for the users location ? Any thoughts of what I am missing here.

**Comment by christianversloot** [comment]
Do you have GPS enabled?

**Comment by raubas** [comment]
Are you running on simulator or real device? On simulator you need to Select: 'Debug -> Location -> Set some location' to get it to work, and maybe restart a couple of times..

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
