### ISSUE TITLE
App crash on ios after opening map several times

### ISSUE THREAD

**Issue by jernejrus** [react-community/react-native-maps#581]
I am using react 15.3.0, RN 0.32.1, and react-native-maps 0.8.2.
If I open a page containing map several times (5-10 times) on iPad, the app crashes. No such problems on Android or in simulator.
Anyone has any idea how to solve this?

**Comment by DennisSnijder** [comment]
This is because a memory leak, if you check on xcode debugging you see the Map is not getting cleaned from your RAM.

I opened an issue for this.
#795

**Comment by alvelig** [comment]
Duplicate #795
