### ISSUE TITLE
Android Custom Mark Issue.

### ISSUE THREAD

**Issue by YoonJaePark** [react-community/react-native-maps#583]
Ios is good. But Android in the mapView Custom Marker issue Maybe the image before it is loaded loaded. and marker imae style not working android.  What should I do? 

this code 

```
    <MapView.Marker coordinate={{
          latitude: 37.78825,
          longitude: -122.4324}}>
          <Image 
              style={{height:100, width: 100, borderWidth:2}} 
             source=  {require('../img/icons/001.png')} 
           />
    </MapView.Marker>       
```

 or 

```
<MapView.Marker coordinate={{
          latitude: 37.78825,
          longitude: -122.4324}}
          image=require('../img/icons/001.png')
         style={{height:100, width: 100, borderWidth:2}} 
>  
```

**Comment by gilbox** [comment]
This is a bug, currenlty Android markers cannot support `<Image />` as child/descendent of marker.  The workaround is to use the `<MapView.Marker />`'s `image` prop. I'd love to get this fixed but I have no idea why it doesn't work atm.

**Comment by alvelig** [comment]
Merging to #1870
