### ISSUE TITLE
MapView.Maker Press Events Not Working

### ISSUE THREAD

**Issue by robertmylne** [react-community/react-native-maps#593]
Marker click events are not working for marker press or callout press.

Not working: onPress + onCalloutPress

```
<MapView.Marker
    ref={ref => {
        this.selectedMarker = ref
    }}
    coordinate={{
        latitude: venue.latitude,
        longitude: venue.longitude,
    }}
    title={venue.name}
    pinColor={'blue'}
    onPress={
        () => console.log('onPress')
    }
    onCalloutPress={
        () => console.log('onCalloutPress')
    }
/>
```

Package.json

```
  "dependencies": {
    "react": "15.3.1",
    "react-native": "0.33.0",
    "react-native-maps": "^0.8.2"
  }
```

**Comment by comountainclimber** [comment]
Can you supply the full mark up for the way you are rendering `<MapView.Marker/>`I have had no issues with either marker press or callout press in my project...

**Comment by ippa** [comment]
I had the same problem, there's a workaround if you create do custom callout  content that contains a <Touchable*> and detect clicks on that.

**Comment by Wallace121980** [comment]
I had the same problem also. With <Touchable*> it works on iOS, but not on Android?

**Comment by mozillo** [comment]
+1，"onPress" event is not working in my custom callout, when touch custom callout, it just disappeared without calling my "onPress" event.

**Comment by tpisto** [comment]
It seems that in iOS with default pin (no custom marker view) the onPress event is not detected. As far as my test goes, in Android the onPress IS detected with default markers.

**Comment by richardhuang09** [comment]
I'm having the same issue as described by tpisto.  The onPress event is not detected on iOS with default pin.

**Comment by jojonarte** [comment]
I am also having issues with not detecting presses on default pin. 
IOS
RN 0.31
maps 0.11

**Comment by skylarmb** [comment]
+1
IOS
RN 0.36
maps 0.11

**Comment by muhgumus** [comment]
+1
IOS
RN 0.40
maps 0.13

**Comment by esutton** [comment]
+1
IOS ( default pin onPress does not work )
RN 0.38.1
maps 0.12.1

**Comment by parkerdan** [comment]
`onCalloutPress` works with custom pins on iOS...but the callouts sometimes render underneath other pins....so this is not a solution.

Default pins callout do not render under other pins....but the `onCalloutPress` doesn't get fired.

It's nice to have this package...be a lot nicer if it worked properly.

**Comment by edencakir** [comment]
+1

**Comment by alvelig** [comment]
In 0.18.3 can't rreproduce
