### ISSUE TITLE
How do I use the Polygon lineJoin prop?

### ISSUE THREAD

**Issue by jameshfisher** [react-community/react-native-maps#603]
According to [the documentation](https://github.com/airbnb/react-native-maps/blob/master/docs/polygon.md), I have to pass an `Array<LatLng>` to set the lineJoin style. This seems weird - what latitudes and longitudes should I be passing?

**Comment by Cygnus2112** [comment]
I too am puzzled by this. Anyone have any insight?

**Comment by chinloong91** [comment]
from 
https://github.com/airbnb/react-native-maps/blob/master/lib/components/MapPolygon.js#L88

```
lineJoin: PropTypes.oneOf([
    'miter',
    'round',
    'bevel',
  ]),
```
only for ios map.

**Comment by AlexChaseJones** [comment]
Can we get more info on this please?

**Comment by rborn** [comment]
closing, very old
