### ISSUE TITLE
fitToCoordinates cannot call apply on undefined

### ISSUE THREAD

**Issue by rgabrielsson** [react-community/react-native-maps#604]
Trying to use this._map.fitToCoordinates(markersLatLngToFit, { "edgePadding": DEFAULT_PADDING, animated: true } ); exactly as in examples, but does not work.

**Comment by olemikkel** [comment]
Seems like this was added a few days ago, what version are you running? Make sure you have the version including https://github.com/airbnb/react-native-maps/commit/7a5083cbb820faec0bb684c010e15c222ce7e533

**Comment by rgabrielsson** [comment]
Thanks! I'll take a look!

**Comment by rgabrielsson** [comment]
It works on Android but not on iOS--anyone know when this could be fixed? Thanks :)

**Comment by amirrezamahyari** [comment]
same problem on ios , didnt work 
but in android works fine

**Comment by kanekotic** [comment]
Is this still open? i have used it lately and it works for me
