### ISSUE TITLE
Fixed tilt 45 degree

### ISSUE THREAD

**Issue by maituanmte** [react-community/react-native-maps#605]
Hi all, 
I would like to set tilt 45 degree like image below. Can I do that with this lib?
![template12](https://cloud.githubusercontent.com/assets/2890277/18810226/c3acd56c-82ba-11e6-91b7-e4545fde3b1f.png)

**Comment by alexHlebnikov** [comment]
Try it this way:
```
style: {
    transform: [
        { rotateY: '45deg'},
    ]
```
