### ISSUE TITLE
Toolbar doesn't appear when open app but if i turn to landscape appears

### ISSUE THREAD

**Issue by diogopalhais** [react-community/react-native-maps#610]
Hey,

The toolbar have a strange behaviour on startup. It appears after a long time navigating the app or if i turn the device to landscape. But when i open the app the toolbar doesn't appear. There is a event or some property that i missed?

![screenshot_20160912-220141](https://cloud.githubusercontent.com/assets/1840393/18818216/b1f6fdb4-836b-11e6-88d2-6ed305b35f52.png)

**Comment by comountainclimber** [comment]
I had a bunch of issues related to this exact issue and ultimately had to use a super hacky solution in order to get the android toolbar to appear on marker press... +1

**Comment by rborn** [comment]
Trying to clean the repo, please comment or mention me to re-open the issue if is still the case. Thanks.

**Comment by victorhsb** [comment]
@rborn the issue still remains, it appears that only when something refreshes the size of the map that the toolbar shows up, when it should appear when a marker is selected. :( airbnb#549 only gives a hint about miraculous hacks, the problem appears to be more "native"
