### ISSUE TITLE
latitudeDelta does not corresponding to current view bounds on iOS

### ISSUE THREAD

**Issue by rgabrielsson** [react-community/react-native-maps#616]
On a very out-zoomed level region.latitudeDelta does not correspond to the current bounds that are displayed. For example, putting a marker at (lat: center.lat + latitudeDelta / 2, lng: center.lng) does not always put it in the upper bound of the screen. Near the north pole it is outside the screen and near the south pole it is lower within the screen (i.e. within the current bounds being displayed).

**Comment by rgabrielsson** [comment]
Actually, it does not correspond even on a moderately zoomed level close the the poles of the earth.

**Comment by alvelig** [comment]
They are from MapKit :( Nothing to do with this
