### ISSUE TITLE
Document purpose of latitudeDelta and longitudeDelta

### ISSUE THREAD

**Issue by bbodenmiller** [react-community/react-native-maps#637]
Would be nice if https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md or similar documented the purpose of `latitudeDelta` and `longitudeDelta`.

**Comment by peacechen** [comment]
I had to look this up too.  It allows you to control how much of the map to display.  In effect, the amount of "zoom". 

> **latitudeDelta**
> The amount of north-to-south distance (measured in degrees) to display on the map. Unlike longitudinal distances, which vary based on the latitude, one degree of latitude is always approximately 111 kilometers (69 miles).
> 

From
https://developer.apple.com/reference/mapkit/mkcoordinatespan/1452417-latitudedelta

**Comment by tak2siva** [comment]
I found this easier to understand https://stackoverflow.com/a/36688156/2309704

**Comment by KangYoosam** [comment]
👍

**Comment by EnKrypt** [comment]
Why was this closed? I do not see the properties reflected on the documentation still.

Do you expect every user to google and come to this issue to look it up?

**Comment by christopherdro** [comment]
https://github.com/react-native-community/react-native-maps/blob/master/docs/overlay.md

**Comment by EnKrypt** [comment]
... what?

There is no mention of `latitudeDelta` or `longitudeDelta` in whatever you linked.

At this point I am very confused and convinced that this issue should be re-opened.

**Comment by EnKrypt** [comment]
Got it.

I supposed you meant to link this instead :

https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#types
