### ISSUE TITLE
Vertical scroll not working when included in "ScrollView" - Android

### ISSUE THREAD

**Issue by dchdimitrov** [react-community/react-native-maps#64]
MapView for iOS is with greater priority than ScrollView. When you try to scroll, you scroll the map. If the content of the ScrollView should be scrolled, the user has to touch something outside the map. I think that the case should be the same here.

**Comment by ericmuyser** [comment]
It doesn't seem to be working in iOS either. I'd like to wrap it in a ScrollView so that I can scroll below the map. I think the map is absolutely positioned so that's why. I think a workaround would be to use an interaction to manipulate the map properties manually.

**Comment by loox-** [comment]
I met the same problem on Android: it is nearly impossible to scroll map in the same direction of scrollview (either vertical or horizontal)
Did anyone solve this?

**Comment by ericmuyser** [comment]
I'm trying to grok the issue but I believe I solved this by wrapping everything inside the ScrollView with a View, including the MapView.

```js
<ScrollView>
  <View>
    <MapView></MapView>
  </View>
  <View>
    <MyComponentHere></MyComponentHere>
  </View>
</ScrollView>
```

**Comment by AndroidMatrixnmedia** [comment]
good# 

> [`_****_`](url)

**Comment by mohamedpsx** [comment]
On ios everything works perfectly but this issue still persists on android ? any progress on this or any ideas that might help ?

**Comment by rborn** [comment]
We're trying to cleanup the repo, so please comment/mention me if this is still an issue. Thank you.

**Comment by jpls93** [comment]
I'm still experiencing this issue. Only on Android. Works perfectly fine in iOS.

```
"react-native": "0.49.3",
```

**Comment by diksha-valuecoders** [comment]
I'm still experiencing the this issue. I am using ScrollView vertical within the viewTransformer and the ScrollView horizontal. The parent scroll works properly as expected but the vertical scroll which is inside the view transformer is not working properly. 
Is there any solution for a table of large no. of data which scroll horizontal as well as vertical with zooming.
