### ISSUE TITLE
Auto-zoom to user location on Android

### ISSUE THREAD

**Issue by richardhuang09** [react-community/react-native-maps#645]
"followsUserLocation" is iOS only.  Has anyone implemented or found a way to get this behavior working on Android?

**Comment by i8wu** [comment]
+1

**Comment by kanekotic** [comment]
+1

**Comment by petrovakd** [comment]
+1

**Comment by zhaohany** [comment]
+1

**Comment by raihanrazi** [comment]
+1

**Comment by freeman1995** [comment]
listen to user's location, and update the mapView's region every time the user location changes
(it's better to set a debounce or add some logic to avoid updating the map's region too fast)

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
