### ISSUE TITLE
Zoom in on User Location and specified marker

### ISSUE THREAD

**Issue by matsossah** [react-community/react-native-maps#646]
Hello,

I am trying to get the map to zoom in on the user's location and a default marker but can't seem to get the desired result.  The map is showing both the user location and the marker correctly but focuses on the marker (that is what I supplied in the region state prop.  For the user location I used
showsUserLocation={true}

Thanks for the help!

**Comment by DylanRichardPearson** [comment]
I'm wondering this same thing. Any luck?

**Comment by matsossah** [comment]
Unfortunately not...Anyone?

**Comment by i8wu** [comment]
If it matters to anyone searching, I used map.fitToCoordinates with my desired marker and psuedo-marker using current location to create this effect.

**Comment by rborn** [comment]
Seems to be resolved. Closing.
