### ISSUE TITLE
Set map width & height set via flexbox?

### ISSUE THREAD

**Issue by joncursi** [react-community/react-native-maps#655]
Right now, it seems the only way to view the map is to hard-code it's dimensions with pixel values. Otherwise, they are 0,0 and the map is not shown. However, I would like the map's width and height to be dynamic, i.e. with `flex: 1`.

The use-case for this is for when the map is initially rendered, then the user rotates the device and the screen orientation changes. This is the result:

<img width="769" alt="screen shot 2016-10-06 at 5 06 32 am" src="https://cloud.githubusercontent.com/assets/4974609/19146705/ad20922c-8b82-11e6-8111-a11f1a04724f.png">

Going from portrait -> landscape, the map width is still based on the original calculation. The only possible workaround I can see right now is to store device width on state, and re-render the map in its entirety when the device width changes (i.e. orientation changes). Is there a better way?

Thanks!

**Comment by qimingfang** [comment]
+1 this would be useful for me as well

**Comment by baba43** [comment]
This is still not working when any tools are shown right?

**Comment by pesterhazy** [comment]
```{:style {:flex 1}}` works for me

Actually this should arguably be in the first example in the readme. I spent some time trying to figure out why the map didn't show - it didn't have a width or height.

**Comment by gokulkulkarni1987** [comment]
@pesterhazy adding height and width worked for me. 
But isn't it weird to hard code the values? there is no way out for this?

**Comment by pesterhazy** [comment]
If you use flexbox, the container (and each ancestor) needs to do the screen as well I think

**Comment by pesterhazy** [comment]
Needs to fill the screen is what I meant

**Comment by gokulkulkarni1987** [comment]
@pesterhazy u mean the container which has maps?

**Comment by pesterhazy** [comment]
Right

**Comment by alvelig** [comment]
<MapView style={StyleSheet.absoluteFillObject} /> ? Let me know if it does not
