### ISSUE TITLE
Rotating user location marker as per bearing angle

### ISSUE THREAD

**Issue by gourav-singhal** [react-community/react-native-maps#689]
I have calculated the bearing angle between two lat longs. How can I provide bearing to the marker image on the map ? Any help will be appreciated.

**Comment by jojonarte** [comment]
Bump, also interested in this.

**Comment by jojonarte** [comment]
up

**Comment by jojonarte** [comment]
This is somewhat the same with Google map app on IOS I wonder if we could do this with this library. Have you had any success with this man?

**Comment by gourav-singhal** [comment]
Yes, I have resolved this. Actually Mapview.Marker provides a rotation prop(not provided in documentation) which can be used as follows :-  
`<MapView.Marker
              coordinate={cordinate
              image= {marker}
              rotation={degree}
              flat={false}
              />`
It will automatically rotate the marker image at the given angle. You can calculate the bearing angle between two lat longs and pass it to the rotation prop.

**Comment by jojonarte** [comment]
It would be great if they could implement #765

**Comment by sandinosaso** [comment]
There is a PR that add support for this https://github.com/airbnb/react-native-maps/pull/1544
When that get merged we can close this issue.
