### ISSUE TITLE
showsMyLocationButton,showsScale property not working

### ISSUE THREAD

**Issue by Rashhh** [react-community/react-native-maps#691]
```
   <MapView
     style={styles.map}
    onPress={(e) => this.onMapPress(e)}
   provider="google"
     zoomEnabled={true}
      scrollEnabled={true}
      showsScale={true}
      mapType='satellite'
      showsMyLocationButton={true}
      showsScale={true}
      showsCompass={true}
      loadingIndicatorColor="#228B22"
     onRegionChange={()=>this.onRegionChange()}
     region={this.state.region}
   >
   </MapView>
```

**Comment by barrilocho** [comment]
Same :( 
Any solution?

**Comment by voidale** [comment]
same case `showsMyLocationButton` has no effect, should it put something on the map?

**Comment by JonoH** [comment]
Yeah none of the toolBar control properties seem to work my side either.

**Comment by pewh** [comment]
+1 Same issue

**Comment by lucianomlima** [comment]
+1

**Comment by gilbox** [comment]
`showsMyLocationButton` is not implemented for google provider on iOS. You're welcome to make a PR to add the feature.

**Comment by JonoH** [comment]
@gilbox they aren't working on Android either.

**Comment by win45** [comment]
**on Android:** This is a stretch, but make sure the `showsMyLocationButton` isn't caught behind an overlaying element i.e. navigationBar. Also, the event wasn't working on my emulator for whatever reason, but worked on a device.

**Comment by psam44** [comment]
For the button to be visible you must set `showsUserLocation={true}` because the default is `false`.
Afterwards, please follow the issue on #1033.

**Comment by alvelig** [comment]
Duplicate of #1033
