### ISSUE TITLE
animateToRegion not working in some circumstance.

### ISSUE THREAD

**Issue by BJChen990** [react-community/react-native-maps#698]
I just start using RN and I found that in some cases animateToRegion will not work when was initialRegion set.

This doesn't work:

```
//MainApp.js
componentWillReceiveProps(nextProps) {
      if (nextProps.newCoords) {
            this.refs.map.animateToRegion({newRegion});
      }
}

_getCustomOverlay() {
     return (someComparison) ? null : <CustomOverlay />;
}

render() {
     const customOverlay = this._getCustomOverlay();

     return (
          <MapView
               ref="map"
               initialRegion={initialRegion}
          >
               {customOverlay}
          </MapView>
     )
}


//CustomOverlay.js
render() {
    return (
        <View>
            {this.state.markers.map((marker) => <MapView.Marker {...someProps} />)}
        </View>
    )
}
```

I've check that the newRegion did pass to animateToRegion but it seems to be a problem in AIRMap. I'm not familiar with Android so I didn't check further in AIRMap, but I did solve this by working around:

First approuch, wrapped with setTimeout:

```
setTimeout(() => {
    this.refs.map.animateToRegion({newRegion});
}, 1)
```

setTimeout with 0 doesn't work, so I use 1. But it will take about 3~5 sec to actually trigger the animation.
Finally I found a better solution:

```
//MainApp.js
render() {
     return (
          <MapView
               ref="map"
               initialRegion={initialRegion}
          >
               <CustomOverlayContainer />
          </MapView>
     )
}
```

This move the overlay logic into a container component, and it works fine. But this makes code much uglier.

I think MapView should support `<MapView>{child operations}</MapView>` without side effects, please help fix this.

**Comment by Roconda** [comment]
Does this only affect Android @BJChen990 ?

**Comment by BJChen990** [comment]
@Roconda
 Sorry for the late reply.
I didn't check on iOS for I didn't setup the environment for iOS

**Comment by Moumene** [comment]
I run to the same issue, so if i understand your solution, you put the `animateToRegion` inside `componentWillReceiveProps` of **CustomOverlayContainer**  right? @BJChen990

**Comment by alvelig** [comment]
Use latest version and comment please

**Comment by Toutai** [comment]
@BJChen990 I LOVE YOU !!!

**Comment by beyond-root-dev** [comment]
Great job.
