### ISSUE TITLE
getting error after installing react-native-maps. IOS and android

### ISSUE THREAD

**Issue by adnanmayo** [react-community/react-native-maps#703]
Hi i am trying to install this in my project i am getting build failed even on Fresh installation  for android and ios on andoird

`FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:dexDebug'.
  
  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

also getting error on ios after linking the assets

`Users/adnan/Radar2App/node_modules/react-native-maps/ios/AirMaps/Callout/SMCalloutView.h:43:36: error: 
cannot find protocol declaration for 'CAAnimationDelegate'; did you mean
'UIApplicationDelegate'?
@interface SMCalloutView : UIView 
^~~~~~~~~~~~~~~~~~~
UIApplicationDelegate
In module 'UIKit' imported from ../../react-native/React/Base/RCTBridge.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:258:11: note: 
'UIApplicationDelegate' declared here
@protocol UIApplicationDelegate
^
1 error generated.

=== BUILD TARGET RCTText OF PROJECT RCTText WITH CONFIGURATION Debug ===

Check dependencies

*\* BUILD FAILED **

The following build commands failed:
CompileC /Users/adnan/Radar2App/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCircle.o AirMaps/AIRMapCircle.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
CompileC /Users/adnan/Radar2App/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapUrlTileManager.o AirMaps/AIRMapUrlTileManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Installing build/Build/Products/Debug-iphonesimulator/Radar2App.app
Launching org.reactjs.native.example.Radar2App
org.reactjs.native.example.Radar2App: 3086`

**Comment by adnanmayo** [comment]
also getting error on ios after linking the assets 

`Users/adnan/Radar2App/node_modules/react-native-maps/ios/AirMaps/Callout/SMCalloutView.h:43:36: error: 
      cannot find protocol declaration for 'CAAnimationDelegate'; did you mean
      'UIApplicationDelegate'?
@interface SMCalloutView : UIView <CAAnimationDelegate>
                                   ^~~~~~~~~~~~~~~~~~~
                                   UIApplicationDelegate
In module 'UIKit' imported from ../../react-native/React/Base/RCTBridge.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:258:11: note: 
      'UIApplicationDelegate' declared here
@protocol UIApplicationDelegate<NSObject>
          ^
1 error generated.

=== BUILD TARGET RCTText OF PROJECT RCTText WITH CONFIGURATION Debug ===

Check dependencies

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/adnan/Radar2App/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCircle.o AirMaps/AIRMapCircle.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/adnan/Radar2App/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapUrlTileManager.o AirMaps/AIRMapUrlTileManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Installing build/Build/Products/Debug-iphonesimulator/Radar2App.app
Launching org.reactjs.native.example.Radar2App
org.reactjs.native.example.Radar2App: 3086`

**Comment by ArnaudBarre** [comment]
Hi, you can see the answer of eangfmbs in issue #118, I think it will solve your problem :
cd android && gradlew clean

**Comment by adnanmayo** [comment]
@ArnaudBarre Hi i have fixed this error for Android is there a solution for IOS also?

**Comment by Clcll** [comment]
@ArnaudBarre try to run via Xcode  
Xcode will offer you change 'CAAnimationDelegate' to 'UIApplicationDelegate'

**Comment by ArnaudBarre** [comment]
Sorry, for the moment I develop for android only on windows, so I don't know how to solve the problem for iOS

**Comment by jeveloper** [comment]
Folks, @spikebrehm  the project is only for ios10 , which is challenging

need to add macro to check for older versions.

**Comment by efkan** [comment]
@adnanmayo  I has encountered with the same issue and I overcome it.

The issue for me was writing dependencies with different versions of Google Play Services.

For example, this is a portion of the `build.gradle` file of `react-native-maps` package:

```
dependencies {
  compile 'com.facebook.react:react-native:+'
  compile "com.google.android.gms:play-services-base:9.4.0"
  compile 'com.google.android.gms:play-services-maps:9.4.0'
}
```

And I had another module which has the following dependencies:

```
dependencies {
    compile 'com.facebook.react:react-native:0.20.+'
		compile 'com.google.android.gms:play-services-location:8.4.0'
}
```

Finally I changed google play services version from **`8.4.0`** to **`9.4.0`** and it works!

I guess gradle would try to add Google Play Services two times. Both of versions.

**Comment by adnanmayo** [comment]
@efkan Thanks buddy i have solved the issue with this

 compile "com.google.android.gms:play-services-base:+"
 compile 'com.google.android.gms:play-services-maps:+'

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
