### ISSUE TITLE
Is it possible to expose google.maps.geometry?

### ISSUE THREAD

**Issue by GuelorEmanuel** [react-community/react-native-maps#704]
I want to be able to use google.maps.geometry.spherical.computeDistanceBetween(latlng1,latlng2), thanks.

**Comment by Kastamarov** [comment]
+1
or how do this google.maps.geometry.encoding.decodePath() ?

**Comment by weihanchen** [comment]
+1

**Comment by Kastamarov** [comment]
I did it by next method:

buildRoute() {
        let pointA = this.state.region;
        let pointB = this.state.regionDestination;
        fetch("https://maps.googleapis.com/maps/api/directions/json?origin=" + pointA.latitude + "," + pointA.longitude + "&destination=" + pointB.latitude + "," + pointB.longitude + "&key=YOUR_KEY", {method: "GET"})
            .then((response) => response.json())
            .then((responseData) => {
                if (responseData.status == "OK") {
                    let pol = responseData.routes[0].overview_polyline.points;
                    let distance = responseData.routes[0].legs[0].distance.text;
                    this.decodePolyline(pol, distance);
                } else {
                    this.setState({
                        destinationCheck: false,
                        allPoints: [],
                        regionDestination: 0,
                        searchString: '',
                        distance: null,
                    });
                    alert('Incorrect destination')
                }
            })
            .done();
    }

decodePolyline(encoded, distance) {
        if (!encoded) {
            return [];
        }
        var poly = [];
        var index = 0, len = encoded.length;
        var lat = 0, lng = 0;

        while (index < len) {
            var b, shift = 0, result = 0;

            do {
                b = encoded.charCodeAt(index++) - 63;
                result = result | ((b & 0x1f) << shift);
                shift += 5;
            } while (b >= 0x20);

            var dlat = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
            lat += dlat;

            shift = 0;
            result = 0;

            do {
                b = encoded.charCodeAt(index++) - 63;
                result = result | ((b & 0x1f) << shift);
                shift += 5;
            } while (b >= 0x20);

            var dlng = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
            lng += dlng;

            var p = {
                latitude: lat / 1e5,
                longitude: lng / 1e5,
            };
            poly.push(p);
        }

        this.setState({allPoints: poly, distance: distance, showDistance: true});
        return poly;
    }

**Comment by weihanchen** [comment]
Thank you for reply.
Algorithm reference from [here](https://developers.google.com/maps/documentation/utilities/polylinealgorithm?hl=zh-tw)?

**Comment by Kastamarov** [comment]
Probably yes. 
I found it on some forum, one guy has transformed it from Java to JavaScript.

**Comment by Kastamarov** [comment]
And it working brilliant.

**Comment by weihanchen** [comment]
This solution also working for me, thanks.

**Comment by FredericBriolet** [comment]
Hey, I found a simple way to get the distance as the crow flies between two coordinates (without using Google), it seems to work nicely. Here's the function : 
```javascript
calculateDistance(pointA, pointB) {

  // http://www.movable-type.co.uk/scripts/latlong.html
  const lat1 = pointA.coordinate.latitude;
  const lon1 = pointA.coordinate.longitude;

  const lat2 = pointB.coordinate.latitude;
  const lon2 = pointB.coordinate.longitude;

  const R = 6371e3; // earth radius in meters
  const φ1 = lat1 * (Math.PI / 180);
  const φ2 = lat2 * (Math.PI / 180);
  const Δφ = (lat2 - lat1) * (Math.PI / 180);
  const Δλ = (lon2 - lon1) * (Math.PI / 180);

  let a = Math.sin(Δφ/2) * Math.sin(Δφ/2) +
          Math.cos(φ1) * Math.cos(φ2) *
          Math.sin(Δλ/2) * Math.sin(Δλ/2);
  
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  const distance = R * c;
  return distance; // in meters
}
```

**Comment by Kastamarov** [comment]
looks good.

**Comment by rborn** [comment]
Seems to be resolved. Closing.

**Comment by thexyman** [comment]
@Kastamarov you saved my life, thank you :)

**Comment by Kastamarov** [comment]
> @Kastamarov you saved my life, thank you :)

glad to know it ;)

**Comment by RodolfoSilva** [comment]
https://www.movable-type.co.uk/scripts/latlong.html

**Comment by RodolfoSilva** [comment]
> Hey, I found a simple way to get the distance as the crow flies between two coordinates (without using Google), it seems to work nicely. Here's the function :
> 
> ```js
> calculateDistance(pointA, pointB) {
> 
>   // http://www.movable-type.co.uk/scripts/latlong.html
>   const lat1 = pointA.coordinate.latitude;
>   const lon1 = pointA.coordinate.longitude;
> 
>   const lat2 = pointB.coordinate.latitude;
>   const lon2 = pointB.coordinate.longitude;
> 
>   const R = 6371e3; // earth radius in meters
>   const φ1 = lat1 * (Math.PI / 180);
>   const φ2 = lat2 * (Math.PI / 180);
>   const Δφ = (lat2 - lat1) * (Math.PI / 180);
>   const Δλ = (lon2 - lon1) * (Math.PI / 180);
> 
>   const a = (Math.sin(Δφ / 2) * Math.sin(Δφ / 2)) +
>             ((Math.cos(φ1) * Math.cos(φ2)) * (Math.sin(Δλ / 2) * Math.sin(Δλ / 2)));
>   
>   const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
> 
>   const distance = R * c;
>   return distance; // in meters
> }
> ```

Complete source: https://www.movable-type.co.uk/scripts/latlong.html
