### ISSUE TITLE
Running GoogleMap on IOS 

### ISSUE THREAD

**Issue by Clcll** [react-community/react-native-maps#706]
Hi! 

I am trying set up google map on IOS. Which option should I use when dragging AirMap and AirGoogleMap in my xCode project? 

I selected this one 

![2016-10-19_12-09-04](https://cloud.githubusercontent.com/assets/22677040/19513090/60af4490-95f7-11e6-89c7-3d27591f88f6.png)

**Comment by christopherdro** [comment]
AirMapsExplorer is the sample app. You'll need to select AirMaps.xcodeproj.

**Comment by Clcll** [comment]
@christopherdro Thank you for response 
Please, can you explain step by step how can I running GoogleMap on IOS.

I was trying do  like it was shown in instruction  .... 
I have already had project and just want to change the map
- Copy the Podfile from example project and change   TARGET name to my project name

-  I call  "pod install" command 

- open my project in xCode and dragging AirMaps and  AirGoogleMaps into project

- Running my project and get still getting this error --- react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.

-  I didn't find AirGoogleMaps there "NativeModules.UIManager" 


Thank you before hand.

**Comment by warmwater** [comment]
@Clcll l I thought you suppose to put Podfile into project_dir/ios folder?

btw I have followed the [instruction ](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md), my project also can not find AirGoogleMaps....

**Comment by Clcll** [comment]
@warmwater yes I put it myProjectct/ios

**Comment by Clcll** [comment]
@christopherdro How must I modified podfile ? Thx

**Comment by christopherdro** [comment]
all you have to do is add that line to your podfile and make sure you run `pod install` inside the ios directory the the podfile is located.

**Comment by Clcll** [comment]
@christopherdro with  pod 'GoogleMaps', path: 'ios/AirGoogleMaps' path or just  pod 'GoogleMaps?

**Comment by skylarmb** [comment]
@Clcll choose the `Create groups` option instead of `Create folder references` option when dragging the folders in. I had this same issue.

**Comment by Clcll** [comment]
@skylarmb Thank you, and what about podfile ? Did you do like in example ?
--> pod 'GoogleMaps', path: 'ios/AirGoogleMaps' path or just pod 'GoogleMaps?

**Comment by btoueg** [comment]
Just `  pod 'GoogleMaps'` is enough

**Comment by Clcll** [comment]
@btoueg thank you but still can't find AirGoogleMaps....

**Comment by jojonarte** [comment]
#713

**Comment by mersay** [comment]
i have the same problem, dragged the folder, installed the pods, but still cannot find AirGoogleMaps

**Comment by skylarmb** [comment]
@mersay @btoueg you sure you chose the `Create groups` option instead of `Create folder references` option when dragging it in? Also clean and rebuild the project `cmd + shift + k` and `react-native run-ios`

**Comment by pascalc** [comment]
If it helps, I've written how I got it to work here: https://github.com/airbnb/react-native-maps/issues/693#issuecomment-259804156

**Comment by starcraft0429** [comment]
Hi @Clcll !
Did you fix your issue?
I recommend to check "copy items if needed"

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
