### ISSUE TITLE
Marker views overlap the loading indicator.

### ISSUE THREAD

**Issue by saadibrahim** [react-community/react-native-maps#709]
I am showing custom views as marker and also have loading indicator on as I think its just better that way but this is whats happening:

![screen shot 2016-10-19 at 11 20 29 pm](https://cloud.githubusercontent.com/assets/4365774/19534009/1e010e74-9653-11e6-950f-0d01c5910f62.jpg)

React Native version: 0.34.1
react native maps version: 0.10.1

**Comment by alvelig** [comment]
Let us know if it's still actual. Might be related to #483
