### ISSUE TITLE
how to get coord on map

### ISSUE THREAD

**Issue by yuda1124** [react-community/react-native-maps#710]
I want to know lat, lng, delta value on map what i'm seeing!
can i get the coord when map center is changed?
plz help me!

**Comment by jeveloper** [comment]
@yuda1124 Short answer is NO
There is no event that can give you even remote information about zoom level with this lib
https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md

You'll be a hero if you add binding to native code.

**Comment by ochanje210** [comment]
https://github.com/airbnb/react-native-maps/issues/122
it does not have solution tho

**Comment by avspeed** [comment]
Huge road block for me to start using this..damn ..

**Comment by ochanje210** [comment]
Well, you can get lat, long, and delta values by using region props like this for example...
``` javascript
<MapView
          region ={this.currentLocation}
          onRegionChange={(region) => {
                     this.setState({region: region})
          }}
/>
```

but the thing is I do not know how the delta values are calculated.

**Comment by gilbox** [comment]
Donno if it helps, but here is how we convert from *zoom and center* to *center and delta*:

https://github.com/airbnb/react-native-maps/blob/master/ios/AirGoogleMaps/AIRGoogleMap.m#L27

**Comment by avspeed** [comment]
Actually @gaguirre's solution worked well for me which includes geo-viewport
https://github.com/airbnb/react-native-maps/issues/122

**Comment by Stophface** [comment]
Use what @ochanje210 wrote, combined with `geo-viewport`, as @avspeed suggested.
