### ISSUE TITLE
Performance regression on Android

### ISSUE THREAD

**Issue by rops** [react-community/react-native-maps#716]
Did anyone notice a performance regression on Android after #548? Any interaction with the maps gets the screen very sluggish. 

I'll try to investigate more.

**Comment by kkgelu** [comment]
Could it be this? https://github.com/airbnb/react-native-maps/pull/728

**Comment by rops** [comment]
I've been seeing that too. Could be related. I'll test the patch and see if it get better

**Comment by alvelig** [comment]
That's general performance as I see. Dupe of #741
