### ISSUE TITLE
Ability to limit zooming

### ISSUE THREAD

**Issue by timford2015** [react-community/react-native-maps#72]
Implement the following params:
minDelta={0.05}
maxDelta={2}
as outlined in https://facebook.github.io/react-native/docs/mapview.html

**Comment by ahmed1490** [comment]
maximum for sure !

**Comment by lelandrichardson** [comment]
Agreed. This should be implemented. Unfortunately it might have to be for ios only though :/

**Comment by ahmed1490** [comment]
Do we really need a native implementation for this?

How about maintaining the maxDelta in as props and as soon as user changes the delta more than that.. the map animates and snap backs to the maximum its allowed to.

**Comment by lelandrichardson** [comment]
@ahmed1490 the problem is the native side is often the side that is responding to zoom changes, which is required to stay that way in order to keep the map performant.

**Comment by bbk1985** [comment]
will android be supported?

**Comment by rborn** [comment]
`maxZoomLevel/minZoomLevel` exist now https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md

We're trying to cleanup the repo, so please comment/mention me if this is still an issue. Thank you.
