### ISSUE TITLE
0.11.0 Warning: Native component for "AIRMapUrlTile" does not exist

### ISSUE THREAD

**Issue by valinaga** [react-community/react-native-maps#732]
after upgrading to 0.11.0 I got this warning:
Warning: Native component for "AIRMapUrlTile" does not exist
Any idea how to get rid of it?
Thanks.

**Comment by fakhrishahab** [comment]
I have same problem, I have try to downgrade react-native-maps but still got this issue

**Comment by lakhman** [comment]
bump, me to, really need to use this.

```
react-native-cli: 1.0.0
react-native: 0.34.1
```

Any ideas, I've also tried master. Looks like a setup/config issue, but everything looks good when I follow the manual install instructions.

**Comment by fakhrishahab** [comment]
I fix my problem by downgrade this package 

`react-native : 0.30.0
react-native-maps : 0.7.1`

**Comment by Arman92** [comment]
What's the status of this issue? I have the same problem : 
library versions in ./package.json
"react": "15.3.2",
"react-native": "0.35.0",
"react-native-maps": "^0.10.2",

**Comment by jverhoeven** [comment]
Probably a stupid remark, but did you try 'react-native link'. I got the exact same error when I forgot that step.

**Comment by pewh** [comment]
@jverhoeven still got same issue after react-native link. Do you use react-native-maps latest version?

**Comment by jverhoeven** [comment]
I have react-native-maps@0.11.0 and no issues so far.

**Comment by bunnrf** [comment]
@fakhrishahab This worked for me, thanks.

My app was crashing unless the MapView was given a width and/or height of 0. Map is working fine after downgrading to react-native@0.30.0.
