### ISSUE TITLE
image marker size 

### ISSUE THREAD

**Issue by yellowbang** [react-community/react-native-maps#733]
I am using a customize image as a marker. However my image size is 400 x 400. How to make it smaller so that it fits the map?

**Comment by Arturszott** [comment]
I would try the following:

```
<Image
    source={require('./marker.png')}
    style={{ width: 40, height: 40 }}
 />
```

**Comment by OtacilioN** [comment]
I am trying to use: 
<MapView.Marker>
            <Image source={require('src/assets/marker.png')} style={{ width: 40, height: 40 }} />
            coordinate={{
              latitude: this.state.latitude,
              longitude: this.state.longitude
            }}
          </MapView.Marker>
And got this error:

<img width="375" alt="screen shot 2018-01-15 at 10 57 34" src="https://user-images.githubusercontent.com/10578275/34945706-f110fd44-f9e2-11e7-8a3c-838bd9cae667.png">

**Comment by rborn** [comment]
@OtacilioN you are uisng `coordinate` as child of the marker instead of a prop.

**Comment by OtacilioN** [comment]
Thanks @rborn solved now, follow the example to make it clear:

<MapView.Marker
            coordinate={{
              latitude: this.state.latitude,
              longitude: this.state.longitude
            }}>
            <Image source={require('src/assets/marker.png')} style={{ width: 40, height: 40 }} />
          </MapView.Marker>

**Comment by OtacilioN** [comment]
Now is working in the simulator but is showing in the build version =/ 

1.

**Comment by rborn** [comment]
What's wrong? without a description of what's going on we can't help :|

**Comment by OtacilioN** [comment]
Okay was build problems, working perfect now, thank you so much for your patience @rborn

**Comment by rborn** [comment]
@OtacilioN 🤗

**Comment by douglasjunior** [comment]
Dont work for Android?

**Comment by douglasjunior** [comment]
For Android only works with `Marker.Animated`:

```xml
      <Marker.Animated
                identifier={`VagaMarker:${vaga.id}`}
                key={vaga.id}
                coordinate={new AnimatedRegion({
                    latitude: coord[0],
                    longitude: coord[1],
                })}
            >
                <Image
                    source={imageSource}
                    style={{ height: 50, width: 50 }}
                    resizeMode="contain"
                />
            </Marker.Animated>
```

But now work with normal `Marker`:

```xml
      <Marker
                identifier={`VagaMarker:${vaga.id}`}
                key={vaga.id}
                coordinate={{
                    latitude: coord[0],
                    longitude: coord[1],
                }}
            >
                <Image
                    source={imageSource}
                    style={{ height: 50, width: 50 }}
                    resizeMode="contain"
                />
            </Marker>
```

No errors, just marker does not appear.

**Comment by nahidmbstu** [comment]
Dont Work in Android   OtacilioN
