### ISSUE TITLE
[Android] Can I use amap in Android devices？

### ISSUE THREAD

**Issue by ColdJuzi** [react-community/react-native-maps#736]
My Android device can not connect to Google services, can i use other maps do? For example amap。

**Comment by Roconda** [comment]
You could use custom tiles, please see https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js

**Comment by sartrey** [comment]
How about using an abstract layer in airbnb rn mapview to adapt custom map service provider?
Just like Draft.js.

React native deprecated original MapView, and push us to airbnb/react-native-maps.
So any plan to make airbnb rn mapview more extensible?

**Comment by alvelig** [comment]
Stick to #773
