### ISSUE TITLE
map markers extensively slow down performance

### ISSUE THREAD

**Issue by percyteng** [react-community/react-native-maps#741]
Hey, I realized that when I have a lot of markers on the map, say 50. It slows down the app's performance extensively. Tapping a button would have effect 5 seconds later. Swiping the map works as smooth as before tho. I wonder if there are any way to enhance performances with a lot of markers on the map. For example, Yelp's performance doesn't get affected by the amount of markers they have on the map.

**Comment by kkgelu** [comment]
https://github.com/airbnb/react-native-maps/issues/716

**Comment by fancypig** [comment]
I have created my own math calculation to only render the markers within my screen as in markers out of my screen don't get displayed. Still if there are more than 10 markers rendered. The performance becomes really bad

**Comment by cyprusglobe** [comment]
@fancypig mind sharing the calculations?

**Comment by fancypig** [comment]
I figured out that it's not the markers that are causing this problem, but the marker callouts. That's a lot easier for me since I can just make my custom callouts when the markers gets pressed

**Comment by fancypig** [comment]
@cyprusglobe  Sure. It's really simple. To find the current border let's say the north(up) one, you do 
After my iterative tests, I figured out that the distance between upper border and ur current location is simply currentRegion.longtitudeDelta*0.5. So the North east position on the border is

latitude: currentRegion.latitude + currentRegion.latitudeDelta*0.5
longitude: currentRegion.longitude + currentRegion.longitudeDelta*0.5

**Comment by 7daysofrain** [comment]
@fancypig Can you tell us how do you create the callout on press? Im here in the same situation. Thanks

**Comment by fancypig** [comment]
@7daysofrain  I just created my own modal when user presses on the marker. But if you want callouts, you can try this one. https://www.npmjs.com/package/react-native-callout

**Comment by jackychow** [comment]
So in my case I didn't even have *a lot* of markers. I just started playing around with this package and maybe @fancypig you can shed some light on what I saw? I just have a super simple piece for testing:

`
          <MapView region={region}
                   onRegionChange={region=>{this.setState({region});}}
                   style={styles.map}
          >
              <MapView.Marker
                  coordinate={location}/>
          </MapView>
`

both location and region were initialized in componentwillmount with a geolocation call. "region" is updated by the MapView and location is never changed since the initial load. 
Having vs. Not Having the marker makes a very noticeable difference when I drag and pan the mapview. The movements are smooth withou the marker and everything gets choppy once I put just this one marker in. 

I figure that the marker keeps rerendering itself as I drag the map as it's (again noticeably) flashing. I believe this kind of code is as simple as it can get? Any idea from your experiences what could have caused this sluggishness?

**Comment by Ulydev** [comment]
^
I had the same flashing marker issue, which caused my app to be very laggy. I made a CustomMarker component that simply renders a marker, and made shouldComponentUpdate always return false.

**Comment by saberking** [comment]
@jackychow the map does not work properly with managed region, just remove the region prop and it should work fine.

**Comment by eard7** [comment]
I've managed to solve this problem in a similar way like Ulydev says, i made a custom component wrapping the marker, the difference with my solution is that instead of always return false in shouldComponentUpdate, in constructor i'm saving the coordinate into the state

```
constructor(props) {
	super(props);
	this.state = {...props};
}
```
Then in shouldComponentUpdate just validate the coordinate again
```
shouldComponentUpdate(nextProps, nextState) {
	return nextProps.coordinate.latitude != this.state.coordinate.latitude && nextProps.coordinate.longitude != this.state.coordinate.longitude;
}
```

The map is configured in such way to request locations when onRegionChangeCompleted is fired to fetch only the markers in the boundaries of the map.

Hope it helps!

**Comment by markmssd** [comment]
Thanks a lot for sharing your solution @eard7 🥇

**Comment by nehvaleem** [comment]
I am having same issue. Using google maps on ios with custom markers slows app a lot. Event with one custom marker it feels slower.

**Comment by grundmanise** [comment]
@nehvaleem Same issue for me! Even with a super 'light' custom marker that contains empty `View`. iOS FPS drastically drops and other native UI elements (ScrollView) are lagging. It's a super issue for me... because I need custom map styling.

**Comment by afxal** [comment]
Try using componentDidMount and set a timeout of around 1000ms before mounting the map component. Will give you 60fps speed.

**Comment by grundmanise** [comment]
@afxal does not help... CPU jumps from 9% to 60%+ as soon as I add one marker with a custom image.

**Comment by andfk** [comment]
Anyone had luck fixing this?
Thanks

**Comment by heysailor** [comment]
+1 It's making it difficult to use maps effectively.

**Comment by OrDuan** [comment]
+1 can't really use the library with this bug

**Comment by maxfysho** [comment]
Also found the CPU jumps as soon as you use a custom marker with simple <View/> component. It seems that similar issues where had on Android, could there be a fix similar? 

https://github.com/airbnb/react-native-maps/pull/264

**Comment by GitDima0122** [comment]
123456

**Comment by davidhellsing** [comment]
I solved it (temporary) using: https://github.com/airbnb/react-native-maps/issues/369#issuecomment-340334468

You could also adjust things like `componentShouldUpdate` to further increase performance, but for me it was the `tracksViewChanges` property that made all the difference.

**Comment by Lomaas** [comment]
Have the same problem. Massive performance issues when using markers. Even if only one marker. My markers does not re-render more than once so this issue seems to be in the native code. It really makes iOS and google maps unusable

**Comment by alvelig** [comment]
@Lomaas could you please open a new issue and fill it according to the new template. I will definitely help with that.

This will be closed. See also #369 for some insights.

**Comment by vanskins** [comment]
Hi guys should try removing prop 'provider' in MapView.

**Comment by AngelVenchev** [comment]
Hey, I solved my problem and this could help somebody else too. I ended up using the image prop on the marker component to display whatever custom component I need. In my usecase I was implementing clustering using supercluster, I wanted to display a number of clusterized pins. I generated my images from here: https://dummyimage.com - about a hundred. Then a designer converted them to circles with a transparent background automatically with a Photoshop action and I loaded them in my application. 100 images were as small as 60kB so it's not a big hit that I have them all in the app.

**Comment by hwesol13** [comment]
Hey, performance in my app was improved a lot after I've set `tracksViewChanges` to `false` for `<Marker />` component. You need to think about it if you can do it in your app but it was possible in my case.

**Comment by EnclaveAnthony** [comment]
I set ```tracksViewChanges``` to ```false``` and it works very well. But the event is delayed so much. Any solution for it?

**Comment by spanwair** [comment]
the main problem in this case that you load `<Markers />` which are also out of the screen. To take of the initial memory usage of unused markers, you will have to make sure not to show it unused one. In this case come very handy to get screen size from lat, lon, latDelta, lonDelta. So one take in use on every `onRegionChangeComplete((e) => ....your_function(e))` and inside use your locally saved marker from initated call (useEffect) or (didmounted) and find only point on screen const ```
makeMarkersInscreen = (allMarkers: SearchDoc[], r: MapCoor) => {
    let markers: SearchDoc[] = [];
    markers = allMarkers.filter(m => 
      (r.latitude - (r.latitudeDelta / 2)) < m.lat
      && ((r.latitude - (r.latitudeDelta / 2)) + r.latitudeDelta) > m.lat
      && (r.longitude - (r.longitudeDelta / 2)) < m.lon
      && ((r.longitude - (r.longitudeDelta / 2)) + r.longitudeDelta) > m.lon
    )
    return markers;
  }
```

have a hapy coding :)

**Comment by Yaolegol** [comment]
In my case solution was
1. as said Ulydev wrap Marker from react-native-maps in component with shouldComponentUpdate (in my case I use functional component so I use React.memo(functionalComponentDeclaration) - more details https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-shouldcomponentupdate)
2. add for Marker from react-native-maps prop tracksViewChanges={false}

**Comment by Arvi128** [comment]
> ```
> Hi guys you should try removing prop 'provider' in MapView.
> " previous code "
> <MapView initialRegion={} provider={PROVIDE_GOOGLE}>
>    <MapView.Marker>....</MapView.Marker>
> </MapView>
> " working code "
> <MapView initialRegion={}>
>    <MapView.Marker>....</MapView.Marker>
> </MapView>
> ```

This , with tracksViewChanges=false improved my map performance drastically.

**Comment by joaoschaab** [comment]
why is this closed?

**Comment by Revolt9k** [comment]
Problem still here

**Comment by joudsul** [comment]
> @jackychow the map does not work properly with managed region, just remove the region prop and it should work fine.

can i ask you i want the region view to change without using region prop because it make propbems?

**Comment by DanielDanaee** [comment]
> Hey, performance in my app was improved a lot after I've set `tracksViewChanges` to `false` for `<Marker />` component. You need to think about it if you can do it in your app but it was possible in my case.

You are amazing man. My FPS went from 19 to 85!

**Comment by arpitBhalla** [comment]
Facing same issue

**Comment by alperenkarip** [comment]
> the main problem in this case that you load `<Markers />` which are also out of the screen. To take of the initial memory usage of unused markers, you will have to make sure not to show it unused one. In this case come very handy to get screen size from lat, lon, latDelta, lonDelta. So one take in use on every `onRegionChangeComplete((e) => ....your_function(e))` and inside use your locally saved marker from initated call (useEffect) or (didmounted) and find only point on screen const
> 
> ```
> makeMarkersInscreen = (allMarkers: SearchDoc[], r: MapCoor) => {
>     let markers: SearchDoc[] = [];
>     markers = allMarkers.filter(m => 
>       (r.latitude - (r.latitudeDelta / 2)) < m.lat
>       && ((r.latitude - (r.latitudeDelta / 2)) + r.latitudeDelta) > m.lat
>       && (r.longitude - (r.longitudeDelta / 2)) < m.lon
>       && ((r.longitude - (r.longitudeDelta / 2)) + r.longitudeDelta) > m.lon
>     )
>     return markers;
>   }
> ```
> 
> have a hapy coding :)

When I enter the pitch value it works fine, but when I enter the pitch value as 100 it shows more pointers than it should. How do I add the pitch value to this formula?
