### ISSUE TITLE
Night/Dark mode?

### ISSUE THREAD

**Issue by divye01** [react-community/react-native-maps#745]
I am just curious to know if the library supports dark/night mode of Apple maps.

**Comment by RWOverdijk** [comment]
👍

**Comment by toaa-media** [comment]
I am curious about too.
Anyone can answer the question above?

**Comment by IjzerenHein** [comment]
Apparently this is not supported by Apple maps, as it is a private API..
https://stackoverflow.com/questions/23327985/mkmapview-night-mode-like-in-ios7-apple-maps
