### ISSUE TITLE
pod install fails if not opened first

### ISSUE THREAD

**Issue by RWOverdijk** [react-community/react-native-maps#748]
https://github.com/CocoaPods/CocoaPods/issues/6107

On a fresh install of react native, the steps provided in the install guide don't work. I had to open up the project in xcode once, and only then did the install work.

**Comment by rborn** [comment]
@RWOverdijk @alvelig as we're working to improve the install instructions and this issue is pretty old, maybe it can be closed? 
Thnx

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
