### ISSUE TITLE
onCalloutPress not triggered in iOS 

### ISSUE THREAD

**Issue by nbastoWM** [react-community/react-native-maps#75]
I just copied the events example and the `onCalloutPress` is not being triggered in iOS (Either on MapView or Marker). 
In Android it fires OK, but in iOS it catches always the Map::onPress even though the callout doesn't hide until I click outside of it.

(I'm on RN 0.19)

**Comment by nbastoWM** [comment]
I tried to overcome this bug by catching a ```onPress``` (map) between a ```onMarkerSelect``` and a ```onMarkerDeselect``` but the onPress triggers before the onMarkerDeselect. 

Anyway, I don't know how to get marker info in the onMarkerSelect.
I did:  ```onMarkerSelect={(m) => this.setState({markerSelected: m})}``` but the m doesn't get the markers' info.

**Comment by lelandrichardson** [comment]
Will try to take a look at this when I get a chance.

**Comment by Ouadie** [comment]
same issue for me too

**Comment by ruqqq** [comment]
onCalloutPress does not work on iOS. Is there a workaround for this?

**Comment by damienadermann** [comment]
Still seeing this issue

**Comment by damienadermann** [comment]
Seems to work if using a custom marker view

**Comment by KGALLET** [comment]
I got the same issue, works on Android but not on iOS.

**Comment by TUNER88** [comment]
any updates?

**Comment by deanmcpherson** [comment]
For those needing a workaround, if you use a custom view for the callout, you can just wrap it in a `TouchableHighlight` and pass through an onPress callback. For me this fires on iOS and not on Android, which means between the two you can get something working. Using react-native-maps@0.3.2

e.g.

```javascript
<MapView.Callout tooltip={true} onPress={() => this.goToPlace(place.place_id)}>
    <Callout {...this.props} place={place} onPress={() => this.goToPlace(place.place_id)}  />
</MapView.Callout>

...

var Callout = React.createClass({
  render: function() {
    let {place} = this.props;
    return <TouchableHighlight underlayColor="transparent" {...this.props}>
      <View style={styles.marker}>
        <View style={styles.markerPointer} />
        <View style={styles.markerContent}>
          <Text style={styles.markerTitle}>{place.name}</Text>
        </View>
    </View>
    </TouchableHighlight>
  }
})
```

**Comment by jlebensold** [comment]
@deanmcpherson any chance you could share your styles for marker markerPointer and markerContent? I'm struggling with the same bug presently

**Comment by thundenilla** [comment]
By anychance anyone solve this bug or any way to click the info window? its working on Android but not on IOS.

**Comment by cinder92** [comment]
+1 not working on android :c

**Comment by jmruiza** [comment]
Any update?? I have same issue. The onCalloutPress event don't works in IOS

**Comment by dually8** [comment]
I'm having a similar issue. onCalloutPress doesn't work when the map view is inside a modal. It works on a regular view though. The only event that is registered is onSelect and onDeselect.

**Comment by dually8** [comment]
I was able to make the callout press thing look similar enough to native, I think. Hope this helps someone. https://gist.github.com/dually8/9e056d8a678982539338529ebc2e2d42

**Comment by alvelig** [comment]
Just tested in the simulator ios 11, with 0.18.3. onCalloutPress is fired. Let me know if persists for anybody, and show your code/environment to reproduce.
