### ISSUE TITLE
how to draw from a to b

### ISSUE THREAD

**Issue by 2ducanhpham** [react-community/react-native-maps#755]
![simulator screen shot nov 1 2016 6 46 18 pm](https://cloud.githubusercontent.com/assets/14899775/19888800/8cbeda02-a063-11e6-9745-1ec16f80d026.png)

**Comment by symmetriccurve** [comment]
use a polyline and onPress prop.

**Comment by 2ducanhpham** [comment]
polyline run ok Apple maps, but google maps for IOS not showing

**Comment by rborn** [comment]
Trying to clean the repo, please comment or mention me to re-open the issue if is still the case. Thanks.
