### ISSUE TITLE
Anatomy of region object

### ISSUE THREAD

**Issue by heysailor** [react-community/react-native-maps#757]
Super simple question - to where do the latitude and longitude parameters of the map region refer? The center, or a corner?

**Comment by symmetriccurve** [comment]
The Region Object is.

region : {
          latitude: 44.883681,
          longitude:  -0.171728,
          latitudeDelta:150,
          longitudeDelta: 150,
         }

The latitude and longitude go as center of the Map and delta sets the zoom level to this location(still maintaining the center of the map as center of the screen.) super cool right. !
