### ISSUE TITLE
Run Polyline with GoogleMaps IOS not showing,but Apple map is working

### ISSUE THREAD

**Issue by 2ducanhpham** [react-community/react-native-maps#762]
please help me!

**Comment by symmetriccurve** [comment]
I have the same Issue.

**Comment by unboundfire** [comment]
@2ducanhpham can you post an example of what you're trying to do?

**Comment by 2ducanhpham** [comment]
I used example PolylineCreator.js ( https://github.com/airbnb/react-native-maps/blob/master/example/examples/PolylineCreator.js ) and change  provider={MapView. PROVIDER_GOOGLE}

**Comment by unboundfire** [comment]
Looks like onPanDrag isn't implemented for iOS google maps...switch the onPanDrag event listener to onPress and you'll be able to draw.

**Comment by 2ducanhpham** [comment]
thanks @unboundfire . I hope you create PR

**Comment by AnmolJLL** [comment]
This works well. Why can't we submit this PR and merge it into `react-native-maps`?
