### ISSUE TITLE
IOS GOOGLE MAPS : Support for animateToViewingAngle and animateToBearing?

### ISSUE THREAD

**Issue by jojonarte** [react-community/react-native-maps#765]
https://developers.google.com/maps/documentation/ios-sdk/views
I have tried looking into the source code but i find it confusing as I am not yet 100% expert on objective C, so this would come up as a suggestion if anyone could do this, it would greatly help for this map's functionality.

**Comment by jojonarte** [comment]
👍

**Comment by gourav-singhal** [comment]
:+1:

**Comment by jojonarte** [comment]
up

**Comment by dorthwein** [comment]
+1

**Comment by jojonarte** [comment]
this still seems to be not part of any recent update, sadly.

**Comment by jojonarte** [comment]
So I figured out that animateToBearing is actually part of the GMSMapView that is used by this library. We could put a react handler function in there to pass around a bearing degrees.

**Comment by sandinosaso** [comment]
Hi I added both functions on this PR: https://github.com/airbnb/react-native-maps/pull/1544
(only IOS for now) any help supporting this for Android is appreciated

**Comment by dlonli** [comment]
doesn't work

**Comment by alvelig** [comment]
It works only on GoogleMaps on IOS. Original issue is closed with #1544
