### ISSUE TITLE
iOS Build Failed (RN0.35 + R-N-maps 0.11.0)

### ISSUE THREAD

**Issue by edolfuchs** [react-community/react-native-maps#767]
Buil not work on IOS. The following build commands failed:

![captura de tela 2016-11-04 as 16 18 16](https://cloud.githubusercontent.com/assets/12100777/20017362/6aa43716-a2aa-11e6-84b0-e117d7484d77.png)

...

![captura de tela 2016-11-04 as 16 18 53](https://cloud.githubusercontent.com/assets/12100777/20017368/702752c2-a2aa-11e6-858e-32a85be26ac8.png)

dependencies:

  "react": "15.3.2",
  "react-native": "^0.35.0",
  "react-native-maps": "^0.11.0",

Anyone can help?

**Comment by abr54** [comment]
I've been having the same issue as this, seems to be a protocol(?) found in the iOS 10 SDK.

There's a PR that fixed this issue here: https://github.com/airbnb/react-native-maps/pull/708 but a new release hasn't been made with it yet. (It'd be extremely helpful if that appears soon!)

**Comment by edolfuchs** [comment]
I changed to **UIApplicationDelegate** and is working so far. I do not know if it's the best solution, but it worked for me.

**Comment by itinance** [comment]
@edolfuchs  just remove the delegate if you're working on maximum iOS SDK Version < 10 as shown in #708. Anyhow, your local fix will only work as long as you don't update the node modules (or reinstall them completely, e.g. on another machine) [just for the sake of completness]

**Comment by edolfuchs** [comment]
@itinance Thanks.

**Comment by alvelig** [comment]
See latest doc. On iOS stick to the latest please.
