### ISSUE TITLE
[iOS] showsPointsOfInterest does nothing when set to false.

### ISSUE THREAD

**Issue by ErkanSensei** [react-community/react-native-maps#768]
Hello, 

When making a MapView and setting showsPointsofInterest to {false}, all POI still show.

`<MapView
         showsPointsOfInterest = {false}
   />`

What I'm trying to do is remove all the default markers that show hospitals, schools, restaurants, etc.

**Comment by Bjvanminnen** [comment]
What I'm seeing is that `showsPointsOfInterest` disables a bunch of things, but not everything.

Here's a view with showsPointsOfInterest=false
![image](https://cloud.githubusercontent.com/assets/1767466/21692011/cdf9233e-d32f-11e6-8cc0-38b6dc88f9e9.png)

Here's a view with showsPointsOfInterest=true
![image](https://cloud.githubusercontent.com/assets/1767466/21692052/f969d91e-d32f-11e6-8166-4419fb2821ef.png)

My suspicion is that for some reason the underlying MKMapView has some of theses things (like Barneys New York) tagged differently, and there may unfortunately be nothing that react-native-maps can do about this.

**Comment by Bjvanminnen** [comment]
More evidence that this issue is an external one https://openradar.appspot.com/28980142

**Comment by IgorVanian** [comment]
It seems that showsPointsOfInterest does nothing (on Android at least). I had the same issue and I solved it by using "customMapStyle" prop

```javascript
customMapStyle={[
    {
	"featureType": "poi.business",
	"stylers": [
		 {
			 "visibility": "off"
                 }
	 ]
     },
     {
	"featureType": "poi.park",
	"elementType": "labels.text",
	"stylers": [
		{
			"visibility": "off"
		}
	 ]
    }
]}
```

Use [https://mapstyle.withgoogle.com/](url) to style your map then put the JSON object into the prop.

**Comment by koxelez** [comment]
Thank you! POIs wouldn't let me get location via the ```onPress()``` method. I managed to hide all POIs by using:
``` 
customMapStyle={[
              {
                "featureType": "poi",
                "stylers": [
                  {
                    "visibility": "off"
                  }
                ]
              },
            ]}
```
It's just a workaround but hey, works for me!
