### ISSUE TITLE
How to get radius from the center point to the corner in meters?

### ISSUE THREAD

**Issue by toaa-media** [react-community/react-native-maps#771]
I want to get radius from center point to the corner point (top-left for ex) on the map in meters but I don't know how.
Can anyone give me the answer?
Thank you, everyone, for your support in this difficult time

**Comment by toaa-media** [comment]
Anyone knows the correct answer?
Please let me know.

**Comment by symmetriccurve** [comment]
Please can you be more elucidate on this, is there any particular use case are you trying to achieve.

**Comment by alvelig** [comment]
get current bounding box #356 and then convert the difference to meters using GIS formulas.
