### ISSUE TITLE
Custom map (tiles) without Google Maps API (Android)

### ISSUE THREAD

**Issue by lpikora** [react-community/react-native-maps#773]
Is possible to use custom tiles without accessing Google Maps API on Android? When i setup custom tiles (https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js) app still requesting Google Maps API according to API Console. And MapView does not render custom tiles when i remove Google Maps API_KEY from AndroidMainfest.xml.

**Comment by mbmelgo** [comment]
do you know how to use custome tiles for the google map?

**Comment by djtango** [comment]
is anyone able to answer this?

**Comment by michael-laoyu** [comment]
TMS or the WMTS, is supported?

**Comment by bcalik** [comment]
I'm also looking for an answer to this.

**Comment by eduatletico** [comment]
Anyone have an answer?

**Comment by eduatletico** [comment]
Does anyone have an answer?

**Comment by wregis** [comment]
Me too. I want to use OpenStreet Map and Here as provider, not Google.

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by anujsinghwd** [comment]
I also want to use mapmyindia as provider not google .

**Comment by alvelig** [comment]
#1631 is a good workaround example of how to achieve

**Comment by bcalik** [comment]
@alvelig No it doesn't, because it still counts as Api requests. Google reached us to stop using Google Maps because we used it for asset tracking and Google doesn't allow asset tracking applications, despite that we used custom tiles.

**Comment by alvelig** [comment]
Closing in favor of #712

**Comment by alvelig** [comment]
See #2348

**Comment by luisbraganca** [comment]
I'm extremely confused here.
I'm using custom tiles on my `MapView` component and it actually works, however I noticed that on Google Cloud Platform, my app is still making requests to Google Maps Android SDK.
Why? Since I'm using my own tile server, this shouldn't be happening at all. Do I have to pay in order to simply use the Maps SDK?
Main render:
```javascript
<MapView
  provider={null}
  mapType={"none"}
  style={styles.map}
  region={this._fetchRegion()}
  showsUserLocation={this._isFollowing.call(this)}
  cacheEnabled={true}
  showsCompass={true}
  zoomControlEnabled={true}
  rotateEnabled={true}
  scrollEnabled={true}
  minZoomLevel={this.props.minZoom || Config.minZoom}
  maxZoomLevel={this.props.maxZoom || Config.maxZoom}
  pitchEnabled={false}
  loadingEnabled={true}
  moveOnMarkerPress={false}
>
  <UrlTile urlTemplate={this._fetchRandomTileURL.call(this)} zIndex={-1} />
  {this._fetchPolylines.call(this)}
  {this._fetchMarkers.call(this)}
</MapView>
```
`this._fetchRandomTileURL.call(this)}` simply gets one of the `4` tile servers I own, used for load balancing.

**Comment by luisbraganca** [comment]
I'm extremely confused here.
I'm using custom tiles on my `MapView` component and it actually works, however I noticed that on Google Cloud Platform, my app is still making requests to Google Maps Android SDK.
Why? Since I'm using my own tile server, this shouldn't be happening at all.

So, do I have to pay in order to simply use the Maps SDK? I don't think that makes sense at all...

Main render:
```javascript
<MapView
  provider={null}
  mapType={"none"}
  style={styles.map}
  region={this._fetchRegion()}
  showsUserLocation={this._isFollowing.call(this)}
  cacheEnabled={true}
  showsCompass={true}
  zoomControlEnabled={true}
  rotateEnabled={true}
  scrollEnabled={true}
  minZoomLevel={this.props.minZoom || Config.minZoom}
  maxZoomLevel={this.props.maxZoom || Config.maxZoom}
  pitchEnabled={false}
  loadingEnabled={true}
  moveOnMarkerPress={false}
>
  <UrlTile urlTemplate={this._fetchRandomTileURL.call(this)} zIndex={-1} />
  {this._fetchPolylines.call(this)}
  {this._fetchMarkers.call(this)}
</MapView>
```
`this._fetchRandomTileURL.call(this)}` simply gets one of the `4` tile servers I own, used for load balancing.

**Comment by wregis** [comment]
@luisbraganca That's the thing here, even if you will not use Google as tile provider you still need a valid API key.

**Comment by luisbraganca** [comment]
@wregis Yea I realized that, and I managed to get a Key. However, even though I'm not using their tiles my APP is still doing some requests to Google Maps API...
Do this requests have any kind of pricing?

**Comment by wregis** [comment]
@luisbraganca I'm not really sure about that.

**Comment by pawan8525** [comment]
hi i am using below url of soil map tile
<MapView.UrlTile
urlTemplate=" ....../api/soil/wms/?x=5458&y=12859&z=15 " />

in x,y i pass converted lat long and in z i pass zoom level.
But my map overlay tile repeat, why i don't know?
Please help

**Comment by bharath-doijode** [comment]
Hi @pawan8525 ,
Did you get the solution for overlay tile repeat? Please share the solution if you got it.

**Comment by yogeshjugwan** [comment]
hi @bharath-doijode 
Did you get the solution for overlay tile repeat? Please share the solution if you got it
