### ISSUE TITLE
Something is wrong when updating the marker data. (IOS)

### ISSUE THREAD

**Issue by osungjin** [react-community/react-native-maps#774]
When I use 0.7.1 version, it worked well.
However, after raising the version, it became odd when the marker data was updated.
The marker data is updated in onRegionChangeComplete.

![markers](https://cloud.githubusercontent.com/assets/1883718/20045071/7274eb0a-a4e1-11e6-9bd9-8b45b1b84c32.gif)

![markers2](https://cloud.githubusercontent.com/assets/1883718/20045045/46773904-a4e1-11e6-8c98-8a9c89493e6d.gif)

react-native-maps: 0.11.0
react-antive: 0.35.0

**Comment by EricPKerr** [comment]
I am experiencing a similar issue. Are you using a custom view inside the `<MapView.Marker>` component?

Can you paste the code for the marker rendering and any other views that are being used?

**Comment by osungjin** [comment]
@EricPKerr 
`<MapView.Marker
        coordinate={{latitude:marker.lat,longitude:marker.lon}}
        key={this.state.iconLoaded ? 'markerLoaded' : 'marker'}
        onPress={e => this.props.pressMarker(marker)}
        >
        <View style={{'backgroundColor':'#FFFFFF','padding':3,'borderRadius':10}}>
          <View style={{'padding':7,'borderRadius':7,'backgroundColor':'#4c82e5'}}>
          </View>
        </View>
      </MapView.Marker>`

How did you solve this problem?

**Comment by mhoffman** [comment]
Has anyone found a workaround for a custom view like this in react-native 0.35+ ?

**Comment by macnube** [comment]
See my latest comment in #1103 as I think I may have found a workaround to the issue.

**Comment by alvelig** [comment]
Might be related to #483
