### ISSUE TITLE
[Android] Markers not appearing...?

### ISSUE THREAD

**Issue by ChrisCates** [react-community/react-native-maps#775]
I am able to update coordinates, lat lng of the map... But for some weird reason I can't set markers...

Here is my code:

```
onMapPress(e) {
    this.setState({
      markers: [
        ...this.state.markers,
        {
          coordinate: e.nativeEvent.coordinate,
          key: `foo${this.state.markers.length + 1}`,
        },
      ],
    });
    console.log(e.nativeEvent);
    console.log(this.state.markers)
  }

  render() {
    return(
      <View style={mapStyles.map}>
        <MapView
          region={{
            latitude: this.state.lat,
            longitude: this.state.lng,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
          zoom={20}
          style={mapStyles.map}
          onPress={this.onMapPress.bind(this)}
        >
        {
          this.state.markers.map((marker, i) => {
            <MapView.Marker
              coordinate={marker.coordinate}
              title={marker.title}
              key={i}
            />
          })
        }
        </MapView>
      </View>
    )
  }
```

Any clues as to why it won't work? Everything seems correct...

**Comment by stephanemaillard** [comment]
Try to return the "MapView.Marker"
 ```
this.state.markers.map((marker, i) => {
  return <MapView.Marker
                coordinate={marker.coordinate}
                title={marker.title}
                key={i}
            />
})
```

**Comment by ChrisCates** [comment]
OMG @stephanemaillard thank you so much for catching that.

One other issue though... I am using `react-native-fetch-blob` module to fetch images for markers... But for some weird reason only the regular marker shows up!

**Comment by seppemarotta** [comment]
@ChrisCates  Add this to your marker 
`        onLoad={() => this.forceUpdate()}
`
I'd also like to add that there is also a bug when you load your image sometimes the marker is not rendering on Android. A temporal workaround for that issue is to add 
` <Image
        style={{opacity: 0}}
        source={$YOURSOURCE}
        />`
 </MapView>
> 
at the end of your map view.

**Comment by neo125874** [comment]
@seppemarotta hi, i found that even iOS need this force method, right?

**Comment by alvelig** [comment]
Merging to #1870
