### ISSUE TITLE
Marker with custom image don't show callout on press 

### ISSUE THREAD

**Issue by adamivancza** [react-community/react-native-maps#777]
When I set a custom image to a marker then the callout won't be presented on press. Although if I use the default markers then it shows the callout on press. I've checked what happens on Xcode and I've found that: 
- when I set a custom image to the Marker then AIRMapMarkerManager's _handleTap method gets invoked.
- when I use the built in Markers then AIRMapManager's didSelectAnnotationView method gets invoked.

Here is the code I'm using:
https://gist.github.com/adamivancza/3a074003496420fa1be2922cfc1df443

**Comment by magrinj** [comment]
It looks like the touchable zone fit to the native component for the callout, but not the zone of the custom marker :/
A temporary fix for me was to add a ref to the `MapView.Marker` and in the `onPress` function of the marker I call the `showCallout` function

**Comment by simonstewart** [comment]
@magrinj have the same issue, but when using onPress on the Marker, the app no longer receives input (i.e. can't click on Navbar items, etc...), although the map remains responsive.

**Comment by magrinj** [comment]
@simonstewart Your bug is really strange, what is your version of RN and RN-maps ?

**Comment by simonstewart** [comment]
@magrinj 
"react-native": "~0.37.0",
"react-native-maps": "^0.11.0"

**Comment by magrinj** [comment]
@simonstewart Hmmm, if you remove the `onPress` on the marker everything is working again ?

**Comment by simonstewart** [comment]
@magrinj have no idea what was happening, but seems fine now :-|

**Comment by alvelig** [comment]
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment]
That's fixed in the latest version

**Comment by ShaikhKabeer** [comment]
I want to show Custom Callout on marker press. Anyone have example of it ?

**Comment by ShaikhKabeer** [comment]
Hi, any update on this ?
