### ISSUE TITLE
Android example app is broken

### ISSUE THREAD

**Issue by btoueg** [react-community/react-native-maps#783]
With the current master commit https://github.com/airbnb/react-native-maps/commit/27f9c30474f20c6911e9d6eade52fc5f11e4aa3a and react-native@0.35.0, I can't run the android example app:

```
Process: com.airbnb.android.react.maps.example, PID: 5937
                                                 java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.airbnb.android.react.maps.example/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
``` 

Seems related to https://github.com/airbnb/react-native-maps/issues/453

**Comment by programoo** [comment]
+1 . this problem should be fixed asap

**Comment by maysam** [comment]
the actual package in not working on my android app and even their example is broken too
this package should have primary focus on android as the original mapview does work for ios anyway

**Comment by gilbox** [comment]
Unable to repro: Genymotion running Google Nexus 5 - 5.1.0 - API 22.

**Comment by maysam** [comment]
@gilbox try it on a 64bit ROM, instead of a 86x

**Comment by mkoo21** [comment]
+1

**Comment by btoueg** [comment]
@alvelig can you provide insights on why this issue has been closed?

**Comment by alvelig** [comment]
@btoueg Can you please checkout current branch, try examples and confirm if they work? We are trying to clean the repo to provide a better support for the library.
