### ISSUE TITLE
Need help to use Google Maps on iOS

### ISSUE THREAD

**Issue by therealgilles** [react-community/react-native-maps#789]
I am trying to understand what I have to do to use Google Maps on iOS. I am using the ignite boilerplate for react-native. My xcode libraries folder is shown in the screenshot below.

How and where should I add the AirGoogleMaps folder? and what, if anything else, do I have to do? Any help will be very much appreciated.

![screen shot 2016-11-11 at 2 33 27 pm](https://cloud.githubusercontent.com/assets/18076992/20232377/c5c7af5c-a81c-11e6-8923-377ba50082c6.png)

**Comment by therealgilles** [comment]
I got Google Maps on ios working. Here is how I did it, hopefully this will help a few people out there struggling with this:

1) Create a Podfile under your application ios directory (see ios/Podfile below).

2) Update <app>/ios/<app>/AppDelegate.m to include your google API key (see AppDelegate.m extract below).

3) Run the following from your <app> dir:

  # build all node modules
  npm install

  # fix react-native-maps (somewhat the react-native-maps installed by npm install is broken, even though the version number is the same, ie 0.11.0)
  cd node_modules
  /bin/rm -rf react-native-maps
  git clone https://github.com/airbnb/react-native-maps
  cd react-native-maps
  npm install
  /bin/rm -rf .git*
  cd ..

  # copy AirGoogleMaps & AirMaps to ios directory (AirMaps may not be necessary)
  cd ios
  /bin/rm -rf AirGoogleMaps AirMaps
  /bin/cp -r ../node_modules/react-native-maps/ios/AirGoogleMaps .
  /bin/cp -r ../node_modules/react-native-maps/ios/AirMaps .
  cd ..

  # install pods
  gem install bundler
  cd ios
  bundle install
  /bin/rm -rf Podfile.lock Pods
  bundle exec pod install --verbose
  cd ..

  # link and run
  react-native link
  react-native run-ios

4) Add provider to your MapView:

    <MapView
         provider={MapView.PROVIDER_GOOGLE}
         ...

That should be it. If your maps page appears blank, you have a problem connecting to the google API. It's either your API key setup (in AppDelegate.m or in the Google API console), or you have something blocking your app traffic (like Little Snitch).


--- ios/Podfile ---
```
# You Podfile should look similar to this file. Whether you use_frameworks! or not, the following configuration should work.
#
# However if you DO NOT use_frameworks! and you prefer to install pods instead of
# dragging the AirMaps directory into your project, refer to the comments below (steps 1~4)

source 'https://github.com/CocoaPods/Specs.git'
# specific your target ios version here
platform :ios, '10.0'
use_frameworks!

target '<put_your_app_name_here>' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'

  # add if you have a subproject like <app>Tests
  #target '<put_your_app_subproject_name_here>' do
  #  inherit! :search_paths
  #  pod 'GoogleMaps'
  #end
end
```

--- <app>/ios/<app>/AppDelegate.m extract ---
...
```
#import "AppDelegate.h"

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"
/* Add google maps header */
#import <GoogleMaps/GoogleMaps.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  /* Register your API key */
  [GMSServices provideAPIKey:@"<insert_your_Google_maps_API_key_here>"];
```
...

**Comment by cuongv** [comment]
I tried to run those steps, but it show: 
![screen shot 2016-11-22 at 11 58 29 am](https://cloud.githubusercontent.com/assets/992197/20511433/0d81a636-b0ab-11e6-9681-8f8c345c5237.png)

Btw, we can not you MapPolyline with google map? how can i draw line on google map?

Thanks in advance!

**Comment by therealgilles** [comment]
What code are you using to display the map view?

**Comment by cuongv** [comment]
Here's my code:

<MapView
          ref="map"
          provider={MapView.PROVIDER_GOOGLE}
          style={styles.map}
          initialRegion={this.props.region}
          showsUserLocation={true}
          onRegionChangeComplete={(region) => {
            //this.props.changeRegion(region);
          }}
        >

**Comment by therealgilles** [comment]
Can you check if your version of react-native-maps matches the master branch of the repo below?
    https://github.com/therealgilles/react-native-maps

It looks like that the version you are using does not have support for the animateToRegion function (which I know is supported for Google Maps if you use the correct version).

**Comment by cuongv** [comment]
I just checked. My version is 0.11.0 (latest one). Is there any chance that i did mistake when install google map?

**Comment by therealgilles** [comment]
Just getting the latest version (0.11.0) with a regular install won't work. I think npm install does not pull the master branch, which has the latest changes, but another branch instead.

Did you follow these instructions?

```
# fix react-native-maps (somewhat the react-native-maps installed by npm install is broken, even though the version number is the same, ie 0.11.0)
  cd node_modules
  /bin/rm -rf react-native-maps
  git clone https://github.com/airbnb/react-native-maps
  cd react-native-maps
  npm install
  /bin/rm -rf .git*
  cd ..
```

**Comment by cuongv** [comment]
You are right! npm did not get the proper version. After i clone it again, it works like a charm. Thank you very much.
But the icon for "user current location" look bad. Is it the same with you ?
![screen shot 2016-11-22 at 1 13 29 pm](https://cloud.githubusercontent.com/assets/992197/20512961/7c4caee4-b0b5-11e6-804d-ec727c8c56a0.png)

**Comment by therealgilles** [comment]
Yes, it's the same for me but that's not a real problem, it's just a display glitch on the simulator. It looks normal when ran on the phone. Glad I could help!

**Comment by cuongv** [comment]
yes, it looks good on devices. Thank you. Btw, is this possible to move Google logo from bottom to top? I have one button in the bottom that may overlay google logo.

**Comment by therealgilles** [comment]
I don't think it's possible to move the logo. That's also where it is on the Google Maps app on iOS.

**Comment by cuongv** [comment]
hmm, i saw one app can did it, i think it still possible to do it.
![img_3923](https://cloud.githubusercontent.com/assets/992197/20513230/3601b0d6-b0b7-11e6-8f52-487dd67e0996.PNG)

**Comment by therealgilles** [comment]
Is that a react-native app? There may be more options on native iOS. I would suggest to ask the developers if you can.

**Comment by cuongv** [comment]
yeah, it's may a native map. ill try to contact developers.

**Comment by therealgilles** [comment]
Adding padding to the map will probably move the logo some, but it won't do to move it to the top.

http://stackoverflow.com/questions/8885596/location-of-google-logo-on-map-in-ios-application

**Comment by therealgilles** [comment]
Here is another article: http://stackoverflow.com/questions/1645364/move-google-maps-logo-when-using-in-a-iphone-app

The functions to do it from react-native are probably not implemented.

**Comment by cuongv** [comment]
After digging it for a while. i have to do it in tricky way:

Change AirGoogleMap.m file:

- (void)setRegion:(MKCoordinateRegion)region {
  self.padding = UIEdgeInsetsMake(0.0, 100.0, 100.0, 0.0); // your intent position
  self.camera = [AIRGoogleMap makeGMSCameraPositionFromMap:self andMKCoordinateRegion:region];
}

**Comment by JeremDsgn** [comment]
@therealgilles I followed your process step by step. I came up with a `ld: framework not found React
` when I try to run the app.

I also tried to remove path to React, like mention in this thread http://stackoverflow.com/a/11391483 but didn't seem to work neither too.

**Comment by therealgilles** [comment]
@cuongv: You may want to look into this to move the Google logo:

```
  /**
   * Insets for the map's legal label, originally at bottom left of the map.
   * See `EdgeInsetsPropType.js` for more information.
   */
  legalLabelInsets: EdgeInsetsPropType,
```

**Comment by therealgilles** [comment]
@JeremDsgn: what is your starting point for your app? are you using the react-native-maps example app, some other boilerplate, or you started from scratch?

**Comment by JeremDsgn** [comment]
@therealgilles I followed up your post here https://github.com/airbnb/react-native-maps/issues/789#issuecomment-260153990 on a personal project.

**Comment by therealgilles** [comment]
@JeremDsgn: did you put the wrong comment link above? it seems to refer to this thread.

**Comment by JeremDsgn** [comment]
@therealgilles  Hum nope, that's what I tried to follow to setup Google Maps, but anyway, I finally make it works!

**Comment by gerard0315** [comment]
@therealgilles hi, i removed my previous pod related files and followed ur instruction but keeps getting ld: framework not found Pods_<project_name> error.

**Comment by therealgilles** [comment]
@JeremDsgn: can you share what the problem was for you? maybe it will help others too.

@gerard0315: maybe you need to run the code below before `pod install`. I would advise to do a search on stackoverflow for this issue.

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

Unfortunately I am neither a CocoaPods nor xcode expert.

**Comment by heron2014** [comment]
Can someone please tell me what I am doing wrong to be able to use GoogleMap on IOS.

These are my exact steps:
Starting new project:
1. ```react-native init Playground```
2. ```npm i --save react-native-maps```
3. ```react-native link```
4. create Podfile under ios dir

ios/Podfile
```
# You Podfile should look similar to this file. Whether you use_frameworks! or not, the following configuration should work.
#
# However if you DO NOT use_frameworks! and you prefer to install pods instead of
# dragging the AirMaps directory into your project, refer to the comments below (steps 1~4)

source 'https://github.com/CocoaPods/Specs.git'
# specific your target ios version here
platform :ios, '8.0'
use_frameworks!

target 'Playground' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'

  # add if you have a subproject like <app>Tests
  #target 'Playground' do
  #  inherit! :search_paths
  #  pod 'GoogleMaps'
  #end
end

```

5. 
```cd ios```
```pod install```

6.  Add API key to ```Playground/ios/Playground/AppDelegate.m```

AppDelegate.m file (with my fake api key):

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <GoogleMaps/GoogleMaps.h> 

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  [GMSServices provideAPIKey:@"abfhdfhdjfhdjfddfdfffdfdfdfdfd"];
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Playground"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end

```

7. open xCode and drag folders from ```node_modules/react-native-maps/ios/AirGoogleMaps``` and ```AirMaps``` 

- on pop up window I chose the default selected options (not create a group one)

8. ```react-native run-ios```

And I got this error: 

```
#import <yoga/Yoga.h>
        ^
1 error generated.


** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze Modules/RCTRedBox.m
(1 command with analyzer issues)

The following build commands failed:
	CompileC /Users/anita/Projects/react-native/react-native-club/Playground/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTActivityIndicatorViewManager.o /Users/anita/Projects/react-native/react-native-club/Playground/node_modules/react-native/React/Views/RCTActivityIndicatorViewManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/Playground.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Playground.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```

Am I missing something?

Thank you in advance!

```
"react": "15.4.2",
"react-native": "0.40.0",
"react-native-maps": "^0.12.4"
```

**Comment by haihoang88** [comment]
Hi @therealgilles ,
I followed your steps to try to add Google maps to the project. However I failed at the following step:

  # install pods
  gem install bundler
  cd ios
  bundle install

When I hit enter with bundle install, it said:

Hais-MacBook-Pro:ios haihoang$ bundle install
Ignoring ffi-1.9.8 because its extensions are not built.  Try: gem pristine ffi --version 1.9.8
Ignoring xcodeproj-0.17.0 because its extensions are not built.  Try: gem pristine xcodeproj --version 0.17.0
Ignoring xcodeproj-0.14.1 because its extensions are not built.  Try: gem pristine xcodeproj --version 0.14.1
Could not locate Gemfile or .bundle/ directory

Can you help me fix this?

**Comment by skeet** [comment]
@heron2014

I got it working on the iOS emulator by doing what you did but I had to explicitly set the version of react-native-maps to 0.13.0.

```
    "react": "15.4.2",
    "react-native": "0.40.0",
    "react-native-maps": "^0.13.0"
```

I get errors when trying to use a real device but it's a start...

**Comment by heron2014** [comment]
@skeet 

Thanks so much! I got it working after upgrading to the latest version! 

Also this time I followed the exact steps from the official docs.

**Comment by skeet** [comment]
@heron2014 

Thanks very much for that guide!

I followed it exactly and I can now push the app to my device for testing. 

Good work!

**Comment by heron2014** [comment]
@skeet That's awesome! Thanks! I haven't yet tested on my device so would be great to know if its working!

**Comment by ChenLi0830** [comment]
@heron2014 Fantastic step by step guide, thanks!

**Comment by eman1000** [comment]
@therealgilles I tried your solution but when run I am getting this error -> fatal error: 'yoga/Yoga.h' file not found
#import <yoga/Yoga.h>

**Comment by peterept** [comment]
*sigh* how can it be so difficult to install :-(

**Comment by ChenLi0830** [comment]
@peterept I've been using Exponent to solve this issue, it helps bundle phone system functionality into RN automatically. https://github.com/exponent/exponent

**Comment by joshuamataaraya** [comment]
Should I have to set somewhere my api key of google maps for IOS?

**Comment by anhtuank7c** [comment]
Follow my guide: https://github.com/anhtuank7c/maps-example

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by KiranHayer** [comment]
Hi, I am trying to run:

- react-native link
- gem install bundler
- cd ios
- bundle install 

in visual studio code and getting an error.(its basically not recognizing these commands)
My question is can I even integrate google maps in the visual studio code editor  via react native or no?
Please reply ASAP!
