### ISSUE TITLE
iOS:  'RCTImageLoader.h' file not found. in AirGoogleMapMarker.h

### ISSUE THREAD

**Issue by gerard0315** [react-community/react-native-maps#794]
I am using react-native@0.37 and react-native-maps@0.11.0. I followed option 1 in installation guide however I'm getting `'RCTImageLoader.h' file not found.` in AirGoogleMapMarker.m, I've tried to set the header search part in AirMaps.xcodeproj to static but still not working. Is there any steps I'm missing as in #660 it should be fixed in 0.11

**Comment by blackPeanut** [comment]
Same issue

**Comment by gerard0315** [comment]
@blackPeanut any progress on this?

**Comment by gerard0315** [comment]
@blackPeanut any progress on this? i've tried do an clean install of the package but no good

**Comment by zk** [comment]
@blackPeanut @gerard0315 try adding `$(SRCROOT)/../node_modules/react-native/Libraries/Image` to your root project's Header Search Paths.

See last in list:

![image](https://cloud.githubusercontent.com/assets/7194/20459600/857a5362-ae95-11e6-9a7d-813ed5b8b9e3.png)

**Comment by shavah** [comment]
This fix does not work for me, still having this issue.

**Comment by BuffMcBigHuge** [comment]
I solved this issue by running:
`react-native unlink react-native-maps`

Then I copied the AirGoogleMaps & AirMaps folders into my root directory in Xcode.

**Comment by ravin-kt** [comment]
I realized that I had not had all the necessary pods installed as specified in their sample Podfile. 

https://github.com/airbnb/react-native-maps/blob/master/example/ios/Podfile

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
