### ISSUE TITLE
Error while updating property 'region' of a view managed by: AIRMap

### ISSUE THREAD

**Issue by JemyDev** [react-community/react-native-maps#809]
Hi,

I have this problem when I want to geolocate me on an Android Studio Simulator. I found one an issue where my problem was solved by adding the following line in my AndroidManifest.xml :  

`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

Except that I already added this line on my xml file. I have a specific organization of my code where I have one Geolocation object :

```
import React, { Component } from 'react';
import styles from './Style';

class Geolocation extends Component {

    constructor(props) {
        super(props);
        this.state = {
            position : {
                coords: {}
            }
        }
    }

    componentDidMount() {
        navigator.geolocation.getCurrentPosition(
            (position) => {
                this.setState({position});
            },
            (error) => alert(error.message),
            {enableHighAccuracy: true, timeout: 20000}
        );
        navigator.geolocation.watchPosition((position) => {
            this.setState({position});
        });
    }
}

export default Geolocation;
```

And I have another Map object which extends of my Geolocation object : 

```
import React, { Component } from 'react';
import Geolocation from '../geolocation/Geolocation';
import {
  Text,
  View
} from 'react-native';
import MapView from 'react-native-maps';

import styles from './Style';

class Map extends Geolocation {

  render() {
    return (
      <MapView style={styles.map}
      initialRegion={{
        latitude: this.state.position.coords.latitude,
        latitudeDelta: 0.001,
        longitude: this.state.position.coords.longitude,
        longitudeDelta: 0.001,
      }} showsUserLocation={true} />
    );
  }
}

export default Map;
```

I don't understand why I have this problem, maybe it's because I am on a simulator and can't locate my position ?

Thanks for help, if you have any ideas.

**Comment by AndreVicenteW** [comment]
Same error here. Did you find the solution? I'm using genymotion and everything works fine, but when I run into the real android device I recive the red screen with this alert. And sometimes when I open the application load the map and when I go to another page and return to the map appers this message. I do not know why

**Comment by Roconda** [comment]
Same here, happens only on production builds on real device

**Comment by ludwigrubio** [comment]
Looks like the problem is because define  a states' value on terms of antoher state, I changed  my values from:
var region= {
           latitude: Number(this.state.position.coords.latitude),
           longitude: Number(this.state.position.coords.longitude),
           latitudeDelta:.1,
           longitudeDelta: .1,
         }
to
var region= {
           latitude: Number(position.coords.latitude),
           longitude: Number(position.coords.longitude),
           latitudeDelta:.1,
           longitudeDelta: .1,
         }
where position is the returned value of geolocation

I hope this works for you!

**Comment by spoeck** [comment]
I had the same error when my latitude and longitude was undefined in my state. Following code works for me:
```
componentDidMount() {
      navigator.geolocation.getCurrentPosition(
            (position) => {
                this.setState({
                    region: {
                        latitude: position.coords.latitude,
                        longitude: position.coords.longitude,
                        latitudeDelta: 0.0462,
                        longitudeDelta: 0.0261,
                    },
                });
            },
            (error) => alert(JSON.stringify(error)),
            {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}
        );
 }
```
```
<View style={styles.container}>
       <MapView
             style={styles.map}
             region={this.state.region}
        />
</View>
```

**Comment by rajeshkos** [comment]
Has anyone faced this issue :

Error while updating property 'coordinates' of a view managed by AIRMapPolyLine

While creating polyline on android ??

**Comment by jorge627** [comment]
I had the same error

even I add a validation but it doesn't work

{ this.state.region.latitude ?
	<MapView
		style={{flex: 1, width: width, height: height }}
		initialRegion={this.state.region}
	>
	
		<MapView.Marker 
			coordinate={this.marker()}
			title="I'm Here"
			description="Home"
		
		/>
	
	
	</MapView> : null
}

**Comment by jorge627** [comment]
I found that the problem is that props latitudeDelta and longitudeDelta should not be negative, In my case I was making some calculations to get that values and I was getting  negative values.

**Comment by alvelig** [comment]
See example https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by ppv94** [comment]
this one worked for me changed

  constructor(props) {
    super(props);
    this.state = {
      region: {
        latitude:this.props.navigation.state.params.data.item.LATITUDE,
        longitude: Numberthis.props.navigation.state.params.data.item.LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
      markers: [],
    };
  }

TO:

constructor(props) {
    super(props);

    this.state = {
      region: {
        latitude: Number(this.props.navigation.state.params.data.item.LATITUDE),
        longitude: Number(this.props.navigation.state.params.data.item.LONGITUDE),
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      }
    };
  }

**Comment by iamabdulhaseeb** [comment]
> I found that the problem is that props latitudeDelta and longitudeDelta should not be negative, In my case I was making some calculations to get that values and I was getting negative values.

This helped. Thankyou.
