### ISSUE TITLE
MapView inside swipe tabbar

### ISSUE THREAD

**Issue by veedeo** [react-community/react-native-maps#812]
How can I disable moving the map at the corners, and propagate these events to swipe tabbar. So when user swipes at the corners it will swipe the tabbar and not move the map

Thanks

**Comment by Ulydev** [comment]
Which component are you using? I'm using react-native-scrollable-tab-view and the feature you're mentioning works perfectly, without needing to add anything special.

**Comment by veedeo** [comment]
Im using it as well. What is the version of your react-native-scrollable-tab-view and react-native-maps. Ill check against them

**Comment by Ulydev** [comment]
Oops, I was used to react-native-mapbox-gl which has this feature and recently switched to react-native-maps. It would indeed be great to have such a functionality.

**Comment by kiwijus** [comment]
Hi guys - I'm using react-native-tab-view and I've managed to solve this with a bit of a dirty hack: 
```
<View style={{ flex: 1, position: 'relative' }} >
    <MapView 
        style={{ flex: 1 }}
        scrollEnabled={true}
        initialRegion={{
            latitude: this.state.lat,
            longitude: this.state.lng,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
        }} />
    <View style={{ position: 'absolute', top: 0, bottom: 0, right: 0, left: width - 20 }}></View>
</View>
```

Essentially the second view is acting as a transparent overlay - allowing the tab to be swiped.
