### ISSUE TITLE
Failed resolution of com.google.android.gms.maps.GoogleMapOptions

### ISSUE THREAD

**Issue by ericnograles** [react-community/react-native-maps#818]
Hi guys,

I'm hoping this is something incredibly silly that I'm overlooking.  I'm attempting to run a React Native app on an Android Emulator with the following settings:

![image](https://cloud.githubusercontent.com/assets/6023705/20527349/110fface-b096-11e6-905b-ae683c1067b8.png)

It's basically just a Nexus 6 + Nougat with Google API's installed.

I fire up the application and get a weird exception from `com.airbnb.android.react.maps.AirMapManager` as follows:

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
...
 Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
```

Does the exception imply that perhaps Google Play Services is not properly installed on my AVD?  I'm guessing yes since running this on my actual Nexus 6P device yields no issues.  

The even stranger part is it's already installed on my machine:

![image](https://cloud.githubusercontent.com/assets/6023705/20527570/f3cbb754-b096-11e6-9d0f-cd743927498c.png)

Is there an extra step I need to take to install Play Services on my emulator?

Thanks for the assist on this!

Eric

**Comment by DownMoney** [comment]
I had the same issue as you. I managed to get the app running but now I get a message on the map screen that I need to update Google Play services. To fix the compilation error I have added:

`compile 'com.google.android.gms:play-services-maps:10.0.0'`

to app.gradle. This seems a bit hacky and doesn't solve the map issue but at least you should be able to compile your app.

**Comment by ogtfaber** [comment]
Had to do the same thing, thanks @DownMoney

**Comment by dingbat** [comment]
I ran into the same thing, but the above fix didn't work for me.

I was able to resolve it differently without adding the dependency, if it helps anyone (I just followed the pattern in examples/android). In android/app/build.gradle, I updated the following values:

```
buildToolsVersion "23.0.3"
...
targetSdkVersion 23
```

**Comment by rknell** [comment]
Posting this here because I kept coming back from this page.

I found the final solution, that both compiled and restored maps working here:
https://github.com/googlemaps/android-maps-utils/issues/258

first follow @DownMoney's comments
then add:
```
    compile "com.google.android.gms:play-services-base:+"
    compile "com.google.android.gms:play-services-maps:+"
```
instead of compile 'com.google.android.gms:play-services-maps:10.0.0'

**Comment by aaronbuchanan** [comment]
after doing this I noticed that `react-native link` will re-link `react-native-maps` in my android setup... Anyone else? 

I noticed I can trick react-native into thinking it's already linked with a multiline comment:

`
dependencies {
    /*
    compile project(':react-native-maps')
    */
    compile(project(':react-native-maps')){
      exclude group: 'com.google.android.gms', module: 'play-services-base'
      exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    ...
`

**Comment by 0mkara** [comment]
https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

This explains how to solve this issue. This article made the right solution for me.

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by aswinramakrish** [comment]
Here is how I debugged this issue -

**1. Look at the logs**

Here is what I was seeing in mine -

      Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
       at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
       at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
       at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:792)
       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:175)
       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:55)
       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:132)
       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:129)
       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1202)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1172)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1107)
       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)

**2. Find out the dependencies**
Run `cd android && ./gradlew :app:dependencies` from your root application folder.

You'll see a massive tree (something like the following). Look at the culprits and see which one makes sense corresponding to your logs -

![screen shot 2018-03-19 at 5 54 05 pm](https://user-images.githubusercontent.com/1799620/37628374-d9c9c2ea-2b9e-11e8-93f3-d1ea9df50941.png)

**3. Fix the dependency**

As you can see that `com.google.android.gms:play-services-base` and `com.google.android.gms:play-services-maps` had different versions. So I added this to my app's `app\build.gradle` file dependencies and the app stopped crashing.

    `compile 'com.google.android.gms:play-services-maps:11.8.0'`

**Comment by valerybodak** [comment]
I solved it by adding this lines:

```
compile project(':react-native-maps')
compile ("com.google.android.gms:play-services-maps:+") {
      force = true;
}
compile 'com.android.support:multidex:1.0.0'
......
```

and

```
defaultConfig {
        ...
        multiDexEnabled true
}
```

**Comment by skout90** [comment]
@valerybodak Thanks a lot!!

**Comment by Ash-faq** [comment]
> Posting this here because I kept coming back from this page.
> 
> I found the final solution, that both compiled and restored maps working here:
> [googlemaps/android-maps-utils#258](https://github.com/googlemaps/android-maps-utils/issues/258)
> 
> first follow @DownMoney's comments
> then add:
> 
> ```
>     compile "com.google.android.gms:play-services-base:+"
>     compile "com.google.android.gms:play-services-maps:+"
> ```
> 
> instead of compile 'com.google.android.gms:play-services-maps:10.0.0'

this solution made my day
