### ISSUE TITLE
Warning: Failed prop type: Required prop 'region.latitude' was not specified in MapView

### ISSUE THREAD

**Issue by JemyDev** [react-community/react-native-maps#820]
Hi all,

I have a problem but I don't know if it's linked to this.

When I'm running my map on Android Emulator from Android Studio, I have this warning and I'm geolocate on Google plex on Palo alto and not on my actual geolocation. Is it because I use an emulator or not ?

Here is my code if you want to check :

Map.js
```
import React, { Component } from 'react';
import Geolocation from '../geolocation/Geolocation';
import Shops from '../shops/Shop';
import {
  Text,
  View
} from 'react-native';
import MapView from 'react-native-maps';
import styles from './Style';

class Map extends Geolocation {

  render() {
    return (
      <View>
        <MapView style={styles.map}
        region={{
          latitude: this.state.position.coords.latitude,
          latitudeDelta: 0.001,
          longitude: this.state.position.coords.longitude,
          longitudeDelta: 0.001
        }} />
        <Shops />
      </View>
    );
  }
}

export default Map;
```

Geolocation.js
```
import React, { Component } from 'react';
import styles from './Style';

class Geolocation extends Component {

    constructor(props) {
        super(props);
        this.state = {
            position : {
                coords: {}
            }
        }
    }

    componentDidMount() {
        navigator.geolocation.getCurrentPosition(
            (position) => {
                this.setState({position});
            },
            (error) => alert(error.message),
            {enableHighAccuracy: true, timeout: 20000}
        );
        navigator.geolocation.watchPosition((position) => {
            this.setState({position});
        });
    }
}

export default Geolocation;
```

Thanks for your answer if you have any ideas, I am a little bit lost with this issue.

**Comment by stephanemaillard** [comment]
Have you tried to log what's in `this.state.position` before using it in MapView in your render function?

**Comment by JemyDev** [comment]
Hi,

I have already tried to log this object et I have this on my log :

`{"mocked": false, "timestamp": 14798952000, "coords": {"speed": 0, "heading": 0, "accuracy":20,"longitude":-122.08400000000002, "altitude":0, "latitude":37.421998333333335}`

I checked on google maps and it's the same coordinates than google plex in palo alto. I don't understand.

**Comment by stephanemaillard** [comment]
The warning is displayed because your initialState doesn't contain any latitude or longitude. And yes I think that your emulator returns the coordinate of the google plex.

**Comment by alvelig** [comment]
See this https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by piyush565** [comment]
Hi, I am new to react native and i got warning: failed prop type : the prop 'coordinate' is marked as required in MapMarker, but its value is undefined.

here is my code
class Map extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isStore: false,
      modalVisible: false,
      
    };
   
  }
  openModal = () =>  {
    this.props.sendStoreInfo(this.props.index);

    this.setState({ modalVisible: true });    
  }
  closeModal = () =>  {
    console.log("close modal");
    this.setState({ modalVisible: false });    
  }
  componentDidMount() {
    const { handleCurrentLocationSearch } = this.props;
    handleCurrentLocationSearch();
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <ModalView modalVisible={this.state.modalVisible} closeModal={this.closeModal}/>
        <MapView
          region={this.props.regionCoordinates}
          mapType={MAP_TYPES.STANDARD}
          style={styles.map}
          showsUserLocation={false}
          followsUserLocation={false}
          zoomEnabled={true}
        >
          <Marker coordinate={this.props.searchCoordinates}>
            <Icon style={{ fontSize: 40 }} name="ios-pin" />
          </Marker>
          <Marker
            coordinate={this.props.regionCoordinates}
            onPress={this.openModal}
          >
            <Icon style={{ fontSize: 40,  }} name="ios-pin" />
          </Marker>
          {this.props.requiredCoordinates.map(item => (
            <Marker coordinate={item.loc}>
              <Icon style={{ fontSize: 40 }} name="ios-pin" />
            </Marker>
          ))}
        </MapView>
        <View style={styles.ButtonContainer}>
          <ActionPage />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  map: {
    flex: 1,
    ...StyleSheet.absoluteFillObject,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  },
  ButtonContainer: {
    top: "75%"
  },
  actionButtonIcon: {
    fontSize: 20,
    height: 22,
    color: "white"
  }
});
const mapStateToProps = store => {
  return {
    latLng: store.searchReducer.searchCoordinates,
    regionCoordinates: store.searchReducer.regionCoordinates,
    requiredCoordinates: store.multipleMarkerReducers.markers,
    searchStoreCoordinates: store.getStoreLocationReducer.storeValue,
    StoreInfo: store.storeInfoReducer.storeInfoData,
    modalVisible: store.storeInfoReducer.modalVisible

  };
};
const mapDispatchToProps = (dispatch, ownProps) => ({
  handleCurrentLocationSearch: () =>
    dispatch(searchActions.setCurrentLocation()),
    sendStoreInfo: (index) => dispatch(storeInfoAction.storeInfoAction(index, ownProps.storeType))
});

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Map);

and here is my reducer to call for it.
const initialState = {
  searchCoordinates: {
    latitude: 0,
    longitude: 0,
    type: null
  },
  storeNumber: null,
  regionCoordinates: {
    latitude: 0,
    longitude: 0,
    latitudeDelta: 0,
    longitudeDelta: 0
  },
  
};

const searchReducer = (state = initialState, action, storeType) => {
  if (action.type === "LOCATION_SEARCH") {
    const newSearchCoordinates = {
      latitude: action.value && action.value.lat,
      longitude: action.value && action.value.lng
    };
    const newRegionCoordinates = {
      ...newSearchCoordinates,
      latitudeDelta: 0.04,
      longitudeDelta: 0.05
    };
    return {
      ...state,
      searchCoordinates: newSearchCoordinates,
      regionCoordinates: newRegionCoordinates
    };
  }
  if (action.type === "CURRENT_LOCATION") {
    const currentCoordinate = {
      latitude: action.value && action.value.lat,
      longitude: action.value && action.value.lng
    };
    const newRegionCoordinates = {
      ...currentCoordinate,
      latitudeDelta: 0.04,
      longitudeDelta: 0.05
    };
    return {
      ...state,
      regionCoordinates: newRegionCoordinates
    };
  }
  if (action.type === "FETCH_STORE_LOCATION_SUCCESS") {
    let temp = action.data.filter(
      item => item.type.toLowerCase() === action.storeType.toLowerCase()
    );
    const newRegionCoordinates = {
      latitude: temp[0] && temp[0].latitude,
      longitude: temp[0] && temp[0].longitude,
      latitudeDelta: 0.04,
      longitudeDelta: 0.05
    };
    return {
      ...state,
      ...temp,
      regionCoordinates: newRegionCoordinates,
      storeNumber: action.storeNumber
    };
  }
  return state;
};
export default searchReducer;
and here is my Action class
import * as actionTypes from "../../constants/actionTypes";
import { baseURL, headers, mockApi } from "../../constants/api";

import axios from "axios";
export const locationSearch = location => {
  return { type: actionTypes.LOCATION_SEARCH, value: location };
};

export const asyncStoreSearch = location => {
  return { type: actionTypes.STORE_SEARCH, value: location };
};

// API FOR STORES
export const storeSearch = (storeNumber, storeType) => dispatch => {
  return axios
    .get(`${baseURL}/${storeNumber}`,{headers})
    .then(res =>{
      
      dispatch({
        type: actionTypes.FETCH_STORE_LOCATION_SUCCESS,
        data:res && res.data,
        storeType:storeType,
        storeNumber: storeNumber
      })
    }
    )
    .catch(err => 
      dispatch({
        type: actionTypes.FETCH_STORE_LOCATION_FAILURE,
        error: err
      })
    );
};

export const setCurrentLocation = () => {
  return dispatch => {
    const geolocation = navigator.geolocation;
    geolocation.getCurrentPosition(position => {
      dispatch(
        {
          type: "CURRENT_LOCATION",
          value: {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          }
        },
        error => {
          if (error.code === 1) {
            dispatch({ type: LOCATION_DENIED, payload: false });
          }
        },
        {
          enableHighAccuracy: true,
          timeout: 20000,
          maximumAge: 1000
        }
      );
    });
  };
};


what will be the issue? thanks
