### ISSUE TITLE
I need MapView.Marker onLongPress 

### ISSUE THREAD

**Issue by Kottidev** [react-community/react-native-maps#824]
When  i built  a custom marker , 

i  create  TouchableOpacity with onLongPress 

> <TouchableOpacity
    onLongPress={() => Actions.moments(index)}
    delayLongPress={2000}
  >
    <View style={styles.imageContainer}>
      <Image style={styles.image} source={{uri: image}} />   
    </View>
  </TouchableOpacity>

it work for IOS but not in android .

and  MapView.Marker don't has onLongPress

**Comment by rborn** [comment]
Closing, very old
