### ISSUE TITLE
Android build fails with:  Could not find react-native.jar 

### ISSUE THREAD

**Issue by uriklar** [react-community/react-native-maps#825]
Hi, 
1. I initialized a basic React Native project (version 0.37.0)
2. Installed react-native maps (version 0.11.0)
3. ran: react-native link
4. ran: react-native run-android 

Getting the following error:
```
* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Could not find react-native.jar (com.facebook.react:react-native:0.37.0).
     Searched in the following locations:
         file:/Users/uriklar/Documents/PhytechApp/node_modules/react-native/android/com/facebook/react/react-native/0.37.0/react-native-0.37.0.jar
```

Appreciate any help. 
Thanks!
Uri

**Comment by cyril94440** [comment]
I deleted the react-native folder in node_modules.
Then, make sure you are not on a restricted network or use a VPN.
npm install

Problem solved

**Comment by siddiquisabih** [comment]
I'm  facing same if any one solved  the plz help me as well

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by alvelig** [comment]
For those who still experience it, try to `react-native-git-upgrade` next or latest version.
