### ISSUE TITLE
pod install Unable to find a target named `AirMapsExplorer`

### ISSUE THREAD

**Issue by alexsbobylev** [react-community/react-native-maps#830]
Hello!

I followed the instructions to install Google Maps on iOS, (https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md)
but when I run **pod install**, I get this error:

Analyzing dependencies
**[!] Unable to find a target named `AirMapsExplorer`, did find `ACer` and `ACerTests`.** 

How to fix it? Help please!

--------
react-native 0.37
react-native-maps 0.11.0 (from git) npm installed

**Comment by mCzolko** [comment]
have you tried to change that `AirMapsExplorer` to `ACer ` ?

**Comment by alexsbobylev** [comment]
Thanks, it's work.
