### ISSUE TITLE
Marker/MapView onPress delay

### ISSUE THREAD

**Issue by Ocherednyara** [react-community/react-native-maps#833]
The onPress events for MapView and Marker have a delay before recognizing that a touch press has happened. The delay is considerable when compared to ordinary Touchables which recognize a press almost instantly. I've measured the delay to be around ~0.6 seconds on emulator and slightly longer on device. The delay also doesn't seem to be in correlation to the amount of markers being rendered or whether dev mode is enabled/disabled. Is there any way to make this delay less apparent? I should mention I'm using custom Marker Views and have also tried wrapping them in Touchables however the Touchables don't seem to register any presses despite being pressed. Has anyone experienced similar issues?

Edit: Perhaps worth noting is that the delay seems to be about the length of the centering animation that would happen upon a marker onPress. Disabling this centering does not change anything however.

This is on Android, react-native-maps version 0.10, react-native version 0.34.1.

**Comment by gilbox** [comment]
Similar thing happens in ios when you use google maps. So I suspect it's a google thing.

**Comment by grundmanise** [comment]
Same for me. `PROVIDER_GOOGLE`. Marker onPress is delayed. RN 0.42.0. iOS 5s (device)

**Comment by grundmanise** [comment]
Does anyone have any thought on how to remove this delay? And what causes it? Is it Google Maps issue or something with `react-native-map`? @spikebrehm

**Comment by luco** [comment]
+1 on this. Take 0.6s as @Ocherednyara said.

**Comment by ryancoughlin** [comment]
Same issue, not sure what is causing it. No difference if it's in dev or production

**Comment by LaszloDev** [comment]
+1 delay on RN 0.43 & 0.44 / Expo 16.0.0 & 17.0.0

**Comment by LaszloDev** [comment]
+1

**Comment by LaszloDev** [comment]
Any update on this?

**Comment by jmhuret** [comment]
I'm still seeing this behavior. It feels like the 300ms delay you get with onTouch events in web and some hybrid apps. I don't see any setting to specifically override this.

**Comment by Rudolph-Miller** [comment]
It may be because GMSMapView tries to detect double tap to zoom in. ;(

**Comment by marano** [comment]
@Rudolph-Miller nailed it! If you disable the map zoom the response is immediate. Not a good solution though.

**Comment by Rudolph-Miller** [comment]
I made [PR](https://github.com/airbnb/react-native-maps/pull/1737) to export `pointForCoordinate` (GMSMapView API) and use this to layout `View` instead of `MapView.Marker` in this [repo](https://github.com/Rudolph-Miller/RNGoogleMapExample).

As a result, it actually reduce tap delay (NO delay) but it's not awesome because of its delay when moving `MapView`. ;(

<img src='https://user-images.githubusercontent.com/6536064/32054462-69e63470-ba99-11e7-97c9-070e5e102aab.gif' width='375px' >

Source code for this app is below.
(It requires this [PR](https://github.com/airbnb/react-native-maps/pull/1737))

```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { PureComponent } from 'react';
import {
  StyleSheet, Text, View, Dimensions,
  TouchableWithoutFeedback, AlertIOS
} from 'react-native';
import MapView, { PROVIDER_GOOGLE }  from 'react-native-maps';

const { width, height } = Dimensions.get('window');

const INITIAL_LATITUDE = 35.6604361;
const INITIAL_LONGITUDE = 139.7289822;
const INITIAL_LATITUDE_DELTA = 0.06;
const INITIAL_LONGITUDE_DELTA = 0.06;

class Marker extends PureComponent {
  constructor() {
    super();

    this.state = {
      isReady: false,
      x: null,
      y: null
    };

    this.markers = [];
  }

  updatePosition() {
    const { map, latitude, longitude } = this.props;

    if (!map) return;

    map.pointForCoordinate({ latitude, longitude }).then(({ x, y }) => {
      this.setState({
        x, y,
        isReady: true
      });
    });
  }
  
  render() {
    const { isReady, x, y } = this.state;

    if (!isReady || x == null || y == null) return <View />;

    return (
      <View
        style={{
          position: 'absolute',
          top: Math.round(y) - 25,
          left: Math.round(x) - 25,
        }} >
        <TouchableWithoutFeedback
          onPress={this.props.onPress} >
            <View
              style={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                backgroundColor: 'pink',
                width: 50,
                height: 50,
                borderRadius: 25
              }} >
              <Text
                style={{
                  backgroundColor: 'transparent',
                  color: 'white',
                  fontSize: 14,
                  fontWeight: 'bold'
                }} >
                {this.props.index}
              </Text>
            </View>
        </TouchableWithoutFeedback>
      </View>
    );
  }
}

export default class App extends PureComponent {
  constructor() {
    super();

    this.state = {
      map: null
    };

    this.markers = [];

    this.onMapReady = this.onMapReady.bind(this);
    this.onRegionChange = this.onRegionChange.bind(this);
  }

  updateMarkers() {
    this.markers.map((marker) => marker.updatePosition());
  }

  onMapReady() {
    this.updateMarkers();
  }

  onRegionChange() {
    this.updateMarkers();
  }

  render() {
    const { map } = this.state;

    const markers = [
      {
        latitude: INITIAL_LATITUDE,
        longitude: INITIAL_LONGITUDE
      },
      {
        latitude: INITIAL_LATITUDE - 0.01,
        longitude: INITIAL_LONGITUDE
      },
      {
        latitude: INITIAL_LATITUDE,
        longitude: INITIAL_LONGITUDE - 0.01
      },
      {
        latitude: INITIAL_LATITUDE + 0.01,
        longitude: INITIAL_LONGITUDE
      },
      {
        latitude: INITIAL_LATITUDE,
        longitude: INITIAL_LONGITUDE + 0.01
      },
    ].map(({ latitude, longitude }, i) => {
      return (
        <Marker
          ref={(marker) => {
            if (marker && this.markers.indexOf(marker) < 0)
              this.markers.push(marker);
          }}
          key={i}
          zIndex={i}
          index={i}
          latitude={latitude}
          longitude={longitude}
          map={map}
          onPress={() => AlertIOS.alert(String(i))} />
      );
    });

    return (
      <View style={styles.container}>
        <MapView
          ref={(map) => {
            if (!this.state.map) this.setState({ map });
          }}
          style={{ height }}
          provider={PROVIDER_GOOGLE}
          initialRegion={{
            latitude: INITIAL_LATITUDE,
            longitude: INITIAL_LONGITUDE,
            latitudeDelta: INITIAL_LATITUDE_DELTA,
            longitudeDelta: INITIAL_LONGITUDE_DELTA
          }}
          zoomEnabled={true}
          showsUserLocation={true}
          followsUserLocation={true}
          onMapReady={this.onMapReady}
          onRegionChange={this.onRegionChange} >
          {markers}
        </MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
});
```

**Comment by alvelig** [comment]
Duplicate #741

**Comment by PiTiLeZarD** [comment]
Hey @alvelig I reckon you closed this based on the last comment which was off-topic.

The problem here is not about rendering lots of markers but about the onPress delay.

I have 1 marker on my map, I don't have any problems displaying it, performances are great, but I still have the delay between the moment I press it and the moment the onPress event is fired only on Android/GoogleMaps.

Disabling the zoom did not fix this in my case but it does feel like the map is waiting to see if I'll doubletap or not. I don't know if I'm reading too much into this but if that's the problem: how about an option to disable double tap only?

Hope it helps

**Comment by alvelig** [comment]
@PiTiLeZarD let's give it a whirl. Create a new issue according to the template and the most complete study (that I see you've already done), and we'll move on with this problem.

**Comment by HerbertLim** [comment]
This issue happens to both iOS and Android.

**Comment by martsie** [comment]
I'm also facing this issue, it's creating a substandard experience for Android users.

**Comment by iremlopsum** [comment]
Same issue still happening, any solution to it?

**Comment by juergengunz** [comment]
@Rudolph-Miller did you find a solution to fix the delay when moving using pointForCoordinate?

**Comment by mikelis-kaneps** [comment]
@Rudolph-Miller is it possible to add disableDoubleClickZoom or gestureHandling option? That could help with the double click expectations from the map.

**Comment by EnclaveAnthony** [comment]
any solution for delay when press marker

**Comment by vasydragan** [comment]
same issue :(

**Comment by edi** [comment]
I can see this is still happening. One thing to mention is the fact that `<Callout />` also takes a considerable amount of time to open (after the actual press).

As the two issues are probably caused by the same thing.

**Comment by EnclaveAnthony** [comment]
I think this is [a good solution](https://github.com/react-native-community/react-native-maps/issues/741#issuecomment-566777308)

**Comment by edi** [comment]
Just wanted to add, this delay only happens on google maps provider (so it's on Android, or iOS with Google Maps).

Using default Apple maps, works perfectly, no delay between tapping and the event trigger.

**Comment by geekazoid-at** [comment]
Please upvote my issue templated report #3429 if you want it to get some attention. This one is closed, nothing will come out of commenting here.

**Comment by EhsanSarshar** [comment]
this problem exist since 2016 that really @#$!$@!@!@

**Comment by EhsanSarshar** [comment]
@Rudolph-Miller how you know this can you plz explain the steps

**Comment by EhsanSarshar** [comment]
along side onPress() I just added onPoiClick() and onLongPress() to the same callBack and it make it 2x faster than before

**Comment by geekazoid-at** [comment]
> onPoiClick

Only works with markers natively on the map, i.e. landmarks that are on google maps by default. For my custom markers it makes no difference as `onPoiClick` is not called in that case. This is quite worthless for me, as google maps POIs is the least interesting thing on my maps.

**Comment by AlixH** [comment]
This issue still exists
