### ISSUE TITLE
showCallout not working

### ISSUE THREAD

**Issue by i8wu** [react-community/react-native-maps#849]
Hi, I am trying to show a custom callout when the map is rendered.

`<MapView.Marker
				ref={(MarkRef) => {
					if (MarkRef != null) {
						MarkRef.showCallout();
					}
				}}`

In Android, a callout is shown but it is empty (When I don't use showCallout() and press the marker it looks fine)
In iOS, no callout is opened

**Comment by eggytronixx** [comment]
I had the same issue. What version of react-native-maps are you using?

**Comment by i8wu** [comment]
Still having the issue on RN0.39.0 and RNM0.12.4

**Comment by arnsa** [comment]
+1 also having this issue. I noticed that it doesn't work if you add "tooltip" to the callout like this:

<MapView.Callout tooltip>...</MapView.Callout>

But if you remove the tooltip part, showCallout() works just fine. Any solutions?

**Comment by i8wu** [comment]
@arnsa Not if I use showCallout()

**Comment by buckhx** [comment]
Does not work w/ custom callouts either. If you tooltip is removed only the caret shows and none of the custom callout.

**Comment by jianjiade** [comment]
I also having this issue

**Comment by jeffreymendez1993** [comment]
its a issue with onPress not firing for the marker on android.

**Comment by alvelig** [comment]
merging to #1872
