### ISSUE TITLE
How to show Latitude and Longitude on MapView like this?

### ISSUE THREAD

**Issue by Xtreric** [react-community/react-native-maps#869]
Hi, 
I am new of React Native. 
Now I can show current location via `showUserLocation={true}`. But if I want to show latitude & longitude data of current location on the view like this [link](https://camo.githubusercontent.com/32d70397b08fb63aa1eb6cad31983958036b060d/687474703a2f2f692e67697068792e636f6d2f336f3655426f50534c6c494b5132647637712e676966).
How can I do? Has anyone can show the code for me?

Many thanks.

**Comment by gilbox** [comment]
the code for that example is included in this repo

**Comment by alvelig** [comment]
see onRegionChangeComplete in docs
And see examples.
