### ISSUE TITLE
Differentiate between region change by animation and interaction?

### ISSUE THREAD

**Issue by MiMaMuh** [react-community/react-native-maps#87]
It would be great it there were callbacks to differentiate between region-change by animation and by user interaction. 

I tried to handle it with a flag which tracks region change by animation using the onRegionChangeComplete handlers, but it doesn't work as sometimes it fires the complete-handler in the middle of an animation.

Maybe there could be an implementation like this:
onRegionChangeByAnimation
onRegionChangeByInteraction

I want to use it to hide and show an overlay depending if the map is used by the user. But when I animate the map by the Animation API the overlay will hide too. I can't figure out a solution right now.

Thx for all the work done so far!

**Comment by gunters63** [comment]
We had the same problem and fixed it by forking React Native.

We also submitted a PR, unfortunately it was not merged yet, and the PR is now stale because our repo had issues and we had to delete it.

https://github.com/facebook/react-native/pull/4939

If you want to patch it yourself: Look for mapViewWillStartRenderingMap in RCTMapManager.m and comment out the: 

````[self _emitRegionChangeEvent:mapView continuous:NO];````

**Comment by MiMaMuh** [comment]
Ah, okay, thanks! :) Hopefully it get fixed soon.

**Comment by lelandrichardson** [comment]
@MiMaMuh this is a good idea, but I don't want to split up the two event handlers. On the other hand, I think it would be a good idea to pass it into the event as data so you can choose to conditionally handle it that way.

For instance:
```
onChange(region, meta) {
  if (meta.source === 'user') {
    this.hideOverlay();
  }
  this.setState({ region });
}
```

**Comment by MiMaMuh** [comment]
@lelandrichardso jup, makes sense to pass the information into the event. Looks good for me!

**Comment by alvelig** [comment]
Merge to #1620
