### ISSUE TITLE
React-native build error: Execution failed for task ':react-native-maps:prepareComAndroidSupportAppcompatV72301Library'. > Could not expand ZIP

### ISSUE THREAD

**Issue by nyxynyx** [react-community/react-native-maps#880]
I created a new `react-native` project on a Windows 10 system, installed the `react-native-maps` package and `rnpm link`, but when starting the project I get a Build failed error.

What is causing this problem?

    react-native init myapp
    npm install react-native-maps --save
    rnpm link
    react-native run-android

**Versions**

    react-native-cli: 1.3.0
    react-native: 0.39.1
    node: v7.2.1
    npm: 3.10.10

[![enter image description here][1]][1]

**Error**

	JS server already running.
	Running C:\Users\y\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
	Building and installing the app on the device (cd android && gradlew.bat installDebug)...
	:app:preBuild UP-TO-DATE
	:app:preDebugBuild UP-TO-DATE
	:app:checkDebugManifest
	:app:preReleaseBuild UP-TO-DATE
	:react-native-maps:compileLint
	:react-native-maps:copyReleaseLint UP-TO-DATE
	:react-native-maps:preBuild UP-TO-DATE
	:react-native-maps:preReleaseBuild UP-TO-DATE
	:react-native-maps:checkReleaseManifest
	:react-native-maps:preDebugAndroidTestBuild UP-TO-DATE
	:react-native-maps:preDebugBuild UP-TO-DATE
	:react-native-maps:preDebugUnitTestBuild UP-TO-DATE
	:react-native-maps:preReleaseUnitTestBuild UP-TO-DATE
	:react-native-maps:prepareComAndroidSupportAppcompatV72301Library FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':react-native-maps:prepareComAndroidSupportAppcompatV72301Library'.
	> Could not expand ZIP 'C:\Users\y\AppData\Local\Android\sdk\extras\android\m2repository\com\android\support\appcompat-v
	7\23.0.1\appcompat-v7-23.0.1.aar'.

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

	Total time: 7.247 secs
	Could not install the app on the device, read the error above for details.
	Make sure you have an Android emulator running or a device connected and have
	set up your Android development environment:
	https://facebook.github.io/react-native/docs/android-setup.html

	(node:8824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read prop
	erty 'message' of undefined
	(node:8824) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
	not handled will terminate the Node.js process with a non-zero exit code.

  [1]: https://i.stack.imgur.com/SyTyG.png

**Comment by arthur-tse7** [comment]
Try running `react-native run-android` 5-6 times consecutively. Each time it got further and further, until it finally got past all the tasks that relate to `react-native-maps`. Kinda annoying to have to do this as a workaround.....

**Comment by minhchu** [comment]
I have the same problem. Waiting for a solution ...

**Comment by passabilities** [comment]
To clearify, my situation has nothing to do with this project.

So I've been stuck on my project not running for awhile. Getting a bunch of errors relating to my packages such as: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preparePocketConnectReactNativeOnesignalUnspecifiedLibrary'.
> Could not expand ZIP 'C:\Users\np\Documents\projects\Pockett\node_modules\react-native-onesignal\android\build\outputs\aar\react-native-onesignal-release.aar'.
```

What was the solution to get it working?? @arthur-tse7 
run `react-native run-android` literally 14 times...

**Comment by alexicum** [comment]
Helped with

> Execution failed for task ':app:prepareSrolkReactNativeFilePickerUnspecifiedLibrary'.
> Could not expand ZIP .....node_modules\react-native-file-picker\android\build\outputs\aar\react-native-file-picker-release.aar
> 

(on windows):
```
cd android 
gradlew clean 
cd ..
react-native run-android
```

or

`cd android && gradlew clean && cd .. && react-native run-android`

**Comment by nckraghu** [comment]
As suggested by @arthur-tse7 after running `react-native run-android`  multiple times, I am able to run the app successfully.

**Comment by athaseen** [comment]
It's weird but after running multiple time react-native run-android was able to build the app successfully.

**Comment by guneyozsan** [comment]
@arthur-tse7 I came here looking for the same error while installing react native image picker library to an empty react native project. Sounds crazy but building multiple times definitely worked. The one before the last build successfully deployed to the device but with the famous red screen. And a one last build even fixed that. Thanks!

**Comment by fliropp** [comment]
I42am1 - 5-6 complies and then it came through. Occourred after I installed react-native-maps.

**Comment by pricetula** [comment]
@alexicum instructions work although i got gradlew command doesn't exist should add ./ infront of gradlew

cd android && ./gradlew clean && cd .. && react-native run-android

**Comment by amkeener** [comment]
++^ add ./

**Comment by profiVideos** [comment]
Thanks guys!!!!! the "gradlew clean" solved another problem I was having.  You guys are the best.

**Comment by pthorsley** [comment]
Still fails for me. Oddly I get this when doing a "gradlew clean":

```
λ gradlew clean
:app:clean UP-TO-DATE
:react-native-google-analytics-bridge:clean
:react-native-vector-icons:clean UP-TO-DATE

BUILD SUCCESSFUL
```
Then I do:
`λ react-native run-android`

And still get:
```

:react-native-google-analytics-bridge:generateReleaseSources                                             
:react-native-google-analytics-bridge:processReleaseJavaRes UP-TO-DATE                                   
:react-native-google-analytics-bridge:compileReleaseJavaWithJavac FAILED                                 
                                                                                                         
FAILURE: Build failed with an exception.                                                                 
                                                                                                         
What went wrong:                                                                                       
Execution failed for task :react-native-google-analytics-bridge:compileReleaseJavaWithJavac.           
Could not find tools.jar                                                                               
                                                                                                         
Try:                                                                                                   
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log ou
tput.
```

Any other thoughts?                                                                                                   
                                                                                                         `

**Comment by pricetula** [comment]
make sure you are connected to internet

**Comment by pthorsley** [comment]
seem to be very connected, was just updating my version on gradle a few minutes before running this. Is there something I need to do to the react-native run-android call to get it to work?

Have run react-native run-android about 13 times.

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by bethwelt** [comment]
i just did npm update 
the react-native link  and it worked for me

**Comment by flotwig** [comment]
If you're looking for a solution less painful than doing `react-native run-android` over and over until it works, you can open the `android` directory as a project in Android Studio. Then, open the problematic submodule, build it in Android Studio, then try `react-native run-android` again.

**Comment by Mifayo** [comment]
@alexicum for windows 

> gradlew clean

replace it with 

> ./gradlew clean

your solution worked for me <3

**Comment by amkayondo** [comment]
> @alexicum instructions work although i got gradlew command doesn't exist should add ./ infront of gradlew
> 
> cd android && ./gradlew clean && cd .. && react-native run-android

This was helpful

**Comment by edilsonlm217** [comment]
> Try running `react-native run-android` 5-6 times consecutively. Each time it got further and further, until it finally got past all the tasks that relate to `react-native-maps`. Kinda annoying to have to do this as a workaround.....

Sounds utter non-sens but definitely works

**Comment by msalmankhalid23** [comment]
cd android 
gradlew clean 
cd ..
npx react-native run-android

This worked for me

**Comment by FaresGuerfala442** [comment]
cd android
gradlew clean
cd ..
npx react-native run-android 
 this one worked for me  :D

**Comment by cosp59** [comment]
**cd android
./gradlew clean
cd ..**
run your project again

**this worked for me**

**Comment by YisusJe** [comment]
> Try running `react-native run-android` 5-6 times consecutively. Each time it got further and further, until it finally got past all the tasks that relate to `react-native-maps`. Kinda annoying to have to do this as a workaround.....

It works haha

**Comment by saumyajit65** [comment]
CD android
gradlew clean

This is the key. I am not able to know the exact details but it works.

**Comment by saumyajit65** [comment]
CD android
gradlew clean

This is the key. I am not able to know the exact details but it works.

**Comment by usama-asfar** [comment]
I was getting this on Github Actions after removing Grandle caching solves the issue. and also after re-running a few times.

**Comment by fulltime117** [comment]
> **cd android ./gradlew clean cd ..** run your project again
> 
> **this worked for me**

It's works for me.
Thanks @cosfix

**Comment by ashwininaidu123** [comment]
> Helped with
> 
> > Execution failed for task ':app:prepareSrolkReactNativeFilePickerUnspecifiedLibrary'.
> > Could not expand ZIP .....node_modules\react-native-file-picker\android\build\outputs\aar\react-native-file-picker-release.aar
> 
> (on windows):
> 
> ```
> cd android 
> gradlew clean 
> cd ..
> react-native run-android
> ```
> 
> or
> 
> `cd android && gradlew clean && cd .. && react-native run-android`

this worked for me thank you.

**Comment by prince-housing** [comment]
you can try by forcing gradle to download again
`rm -rf ~/.gralde`
then start the android build again.
