### ISSUE TITLE
MapView.Marker with custom image shows in different size on the device vs simulator

### ISSUE THREAD

**Issue by ssimic2** [react-community/react-native-maps#882]
![iphone6](https://cloud.githubusercontent.com/assets/7103655/21078224/7d35c672-bf1c-11e6-8f0c-551f640e4c15.png)
iphone 6

<img width="369" alt="iphone6-simulator" src="https://cloud.githubusercontent.com/assets/7103655/21078235/d0c30f34-bf1c-11e6-9c2c-26dee6814ef4.png">

iphone 6 simulator

npm -v react-native-maps: 3.10.8

import orangeMarkerImg from '../assets/images/markers/48/orange.png'
<MapView.Marker
    key={i}
    title="Hello there"
    coordinate={{
       latitude: parseFloat(venue.lat),
       longitude: parseFloat(venue.lng),
    }}
    image={orangeMarkerImg}
/>

**Comment by ssimic2** [comment]
Further, the marker is not pointing to the correct lat/lat. Potentially, it could be an additional issue.

**Comment by ochanje210** [comment]
why don't you use Image component like below
```jsx
<MapView.Marker>
  <Image
    source={your_custom_image}
    style={your_custom_image_style}
  />
</MapView.Marker>
```
with this, you can give specific width and height to your custom marker image
Also, regarding the position which the markers are pointing to, try to give [anchor prop](https://github.com/airbnb/react-native-maps/blob/master/docs/marker.md#props)

**Comment by ssimic2** [comment]
@ochanje210 thanks for the help.

Nesting <Image definitely helped. Now, the marker image looks the right size on both simulator and device.

The 2nd issue (wrong anchor location) is still present event after setting anchor props. Two notes:

a. Setting anchor props on <MapView.Marker does not seem to affect location of the <Image when nested in within the marker. I have used: anchor={{ x: 0.5, y: 1 }}, anchor={{ x: 0, y: 0 }}, anchor={{ x: 1, y: 1 }} . All drop the image at the same location (see image below)

b. The issue is showing up only on lower zoom levels. Both simulator and device show markers anchored to a wrong place:

<img width="373" alt="smallerzoom-simulator" src="https://cloud.githubusercontent.com/assets/7103655/21239753/2103f33e-c2bd-11e6-97c3-6b19ef0ad9c5.png">
Lower Zoom (Simulator)

![smallerzoom-device](https://cloud.githubusercontent.com/assets/7103655/21239772/38596da2-c2bd-11e6-850e-2f393db57e0e.PNG)
Lower Zoom (Device)


On the higher zoom level, both device and simulator have marker anchored at the right lat/lng:
<img width="373" alt="higherzoom-simulator" src="https://cloud.githubusercontent.com/assets/7103655/21239934/e7565108-c2bd-11e6-9fa2-d8b67b95dc08.png">
Higher Zoom (Simulator)

![higherzoom-device](https://cloud.githubusercontent.com/assets/7103655/21239938/f0b795f4-c2bd-11e6-81b3-72c78ee1ad09.PNG)
Higher Zoom (Device)


Maybe I am missing something obvios. If not, I will open another issue, and close this one.

**Comment by peterept** [comment]
any updates on this? 

Could there some way to pass the width/height directly to the Image property on the MapView.Marker ?

**Comment by willyyang** [comment]
I've got the same issue, would love to hear some workarounds

**Comment by iiitmahesh** [comment]
@peterept @willyyang Any update??

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/1422#issuecomment-350894668

**Comment by alvelig** [comment]
For Android stick to #100

**Comment by OtacilioN** [comment]
I am trying to use: 
<MapView.Marker>
            <Image source={require('src/assets/marker.png')} style={{ width: 40, height: 40 }} />
            coordinate={{
              latitude: this.state.latitude,
              longitude: this.state.longitude
            }}
          </MapView.Marker>
And got this error:

<img width="375" alt="screen shot 2018-01-15 at 10 57 34" src="https://user-images.githubusercontent.com/10578275/34945706-f110fd44-f9e2-11e7-8a3c-838bd9cae667.png">

**Comment by rborn** [comment]
@OtacilioN don't ask the same question in multiple issues. https://github.com/react-community/react-native-maps/issues/733#issuecomment-357690763

**Comment by OtacilioN** [comment]
Okay, sorry for that! And thanks for the answer!

**Comment by emalazt2014** [comment]
@Andriiseer How did you make the route on the map? Thank you

**Comment by Andriiseer** [comment]
@emalazt2014 using Polyline. You can find instructions in [React-Native-Maps/Polyline](https://github.com/react-community/react-native-maps/blob/master/docs/polyline.md). I used the polyline from Gmaps API's JSON response and just rendered the array of coords using polyline. There are some limitations since "polyline_overview" in Gmaps Json isn't too precise when it comes to large distances therefore if you zoom in the path will be kind of skipping throughout the way instead of following the roads.

**Comment by emalazt2014** [comment]
I tried everything, and it only worked for me by changing the marker size

**Comment by Andriiseer** [comment]
@emalazt2014 what do you use as a marker picture? Format, Size, etc

**Comment by brownieboy** [comment]
I'm getting this issue too in a project of my own.

I haven't tried any of the workarounds here yet, but I noticed that on the [example code here](https://github.com/react-native-community/react-native-maps/blob/master/example/examples/MarkerTypes.js) they don't seem to be using any of them - not that I can see anyway.  And that _does_ work for me, on the emulator at least.

**Comment by RyanTG** [comment]
@ssimic2 I know this is an ancient issue. But judging from the screenshots in your first post, the resolution of your basemap is different in the simulator and build. What basemap/tileset are you using? Perhaps in the build, the basemap density changes, and then the assets switch from @2x to @3x based off of that - or something crazy like that. So while the device _should_ be showing @2x, it ends up showing @3x and thus they are large. Kind of a wild theory - but the differences in the basemaps is interesting.

**Comment by bigo104** [comment]
This issue has been going on 3 years, how can we resolve this?

**Comment by AshHogarth** [comment]
Keeping the thread alive as I'm now having this issue. Placement is ok but size is much larger on deployment

**Comment by andrepcg** [comment]
Same issue as @AshHogarth , works fine when using expo but when running in the standalone version the icons are much larger

**Comment by AshHogarth** [comment]
@andrepcg Hey dude, sorry to hear you're having this issue, hopefully my solution can offer some assistance. Somehow somewhere I found a solution someone was doing where they actually produce an Image wrapped by the Marker tag. Below is me conditionally rendering if there are results produce the markers, otherwise produce a default one to encourage the user to interact

`<MapView
                ref = {}
                initialRegion={}
                showsUserLocation={}
                style={}
                showsMyLocationButton={}
                showsCompass={}
                onRegionChangeComplete={}
                customMapStyle={}>

                {this.props.results ? this.props.results.map(marker => {          
                    return (
                        <Marker
                            key={}
                            coordinate={}
                            title={}
                            onPress={}
                            opacity={}
                        >
                            <Image 
                                style={styles.marker}
                                source={require('../assets/map/marker.png')}
                            />
                        </Marker>
                    )
                }) 
                : 
                <Marker 
                    key={{ 
                    coordinate={} 
                    title="Get Searching!" 
                />
                }                
            </MapView>`

**Comment by cinder92** [comment]
@AshHogarth i don't recommend that, if are rendering 100+ pins, you will have memory leaks

**Comment by naresh-rently** [comment]
The only way to fix this is to host the required image(size accordingly) somewhere and load it to the icon property of marker mentioning the uri.

**Comment by Rohit-Parte** [comment]
<Marker
                        key={}
                        coordinate={}
                        title={}
                        onPress={}
                        opacity={}
                    >
                        <Image 
                            style={styles.marker}
                            source={require('../assets/map/marker.png')}
                        />
                    </Marker>
                    
      This is working perfectly!
