### ISSUE TITLE
Calculate delta by Bounds

### ISSUE THREAD

**Issue by mxmtsk** [react-community/react-native-maps#884]
Hi,

so I have a set of places that are saved in my db with their bounds (nw_lat, nw_lng, se_lat, se_lng). I've used that with the Javascript Google Maps api but now we are creating an app for our service and with react-native-maps you can only set the longitudeDelta and latitudeDelta.

How can I calculate the right delta from bounds?

**Comment by almirfilho** [comment]
You can obtain the deltas just subtracting one coordinate from another.
I think in your case something like the following might work:

```javascript
const longitudeDelta = Math.abs(se_lng - nw_lng);
const latitudeDelta = Math.abs(se_lat - nw_lat);
```

**Comment by alvelig** [comment]
similar to #356 
But @almirfilho is right. Those are just differences.
