### ISSUE TITLE
TypeError: Cannot read property 'setNativeProps' of null

### ISSUE THREAD

**Issue by danbruegge** [react-community/react-native-maps#889]
Hi,

using the `MapView` component i got this error:
```bash
TypeError: Cannot read property 'setNativeProps' of null

  at MapView._updateStyle (node_modules/react-native-maps/components/MapView.js:412:9)
  at MapView.componentDidMount (node_modules/react-native-maps/components/MapView.js:406:6)
  at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
  at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
  at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
  at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
  at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
  at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
  at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
  at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
```
It only appears in `<MapView>`, `<MapView.Marker>` for example works fine.

test code:
```javascript
import React from 'react';

import renderer from 'react-test-renderer';

import MapView from 'react-native-maps';

describe('renders correctly', () => {
    it('on visible=true', () => {

        const component = (
            <MapView liteMode>
                <MapView.Marker />
            </MapView>
        );

        const tree = renderer.create(component).toJSON();

        expect(tree).toMatchSnapshot();
    });
});
```

```
"dependencies": {
    "moment": "^2.17.1",
    "react": "^15.4.1",
    "react-native": "^0.39.2",
    "react-native-maps": "^0.12.2",
    "react-native-vector-icons": "^3.0.0",
    "realm": "0.15.1-rc"
},
"devDependencies": {
    "babel-jest": "17.0.2",
    "babel-preset-react-native": "1.9.0",
    "jest": "17.0.3",
    "jest-react-native": "^17.1.0",
    "react-test-renderer": "^15.4.1"
},
"jest": {
    "preset": "react-native",
    "bail": true,
    "testPathIgnorePatterns": [
        "node_modules/?!react-native|react|realm|react-native-maps",
        "._.js"
    ]
}
```

**Comment by MyGuySi** [comment]
I'm getting this error too, if anyone knows a solution that would be great!

**Comment by iraycd** [comment]
@danbruegge Any updates?

**Comment by danbruegge** [comment]
I'll check it tomorrow. My last status was that it wasn't working.

**Comment by MrMatten** [comment]
+ 1

**Comment by tugorez** [comment]
Hi everyone, this problem is probably related to https://github.com/facebook/react/issues/7740 
Basically "ref" callbacks in the [\<MapView \/\> component](https://github.com/airbnb/react-native-maps/blob/master/lib/components/MapView.js#L641) are not called, 
So when the [componentDidMount](https://github.com/airbnb/react-native-maps/blob/master/lib/components/MapView.js#L420) is called and it calls the [_updateStyle method](https://github.com/airbnb/react-native-maps/blob/master/lib/components/MapView.js#L427) `this.map` is undefined.

The interesting part, in my case, is that the shallow rendering works and I did not know why, but as you can see [here](https://github.com/facebook/react/pull/8592#issuecomment-296204163)  shallow rendering doesn't call the componentDidMount method.

An easy workaround I found [here](http://stackoverflow.com/questions/41186199/unable-to-mock-native-module) is 

> jest.mock('react-native-maps', () => {                                           
>   const React = require('react');                                                
>   return class MockMapView extends React.Component {                             
>     static Marker = props => React.createElement('Marker', props, props.children);
>     static propTypes = { children: React.PropTypes.any };                        
>     render() {                                                                   
>       return React.createElement('MapView', this.props, this.props.children);    
>     }                                                                            
>   }                                                                              
> });

**Comment by DevanB** [comment]
@tugorez When I try to use the snippet you provided, I run into a `TypeError: Cannot read property 'propTypes' of undefined` error. 

I've tried importing the `prop-types` package and requiring it, but no luck.

Have any suggestions?

**Comment by alvelig** [comment]
Update to latest and comment if not solved

**Comment by zibs** [comment]
I was running into the error on latest, used @tugorez snippet and issue was resolved.

**Comment by javc86** [comment]
I applyed the @tugorez solution, but it don't work for me. Here my code:
`import 'react-native';
import React, {Component, createElement} from 'react';
import {Provider} from 'react-redux';
import renderer from 'react-test-renderer';
import configureMockStore from 'redux-mock-store';
import Proptypes from 'prop-types';
import Maps from '../../app/src/screens/Maps';

const mockStore = configureMockStore();
const store = mockStore({});

jest.mock('react-native-maps', () => (
    class MockMapView extends Component {
      static Marker = props => createElement('Marker', props, props.children);

      static propTypes = {
          children: Proptypes.any.isRequired
      };

      render() {
          const {children} = this.props;
          return createElement('MapView', this.props, children);
      }
    }
));

it('renders correctly', () => {
    const navigation = {navigate: jest.fn()};

    const tree = renderer.create(
        <Provider store={store}>
            <Maps navigation={navigation}/>
        </Provider>
    ).toJSON();
    expect(tree).toMatchSnapshot();
});
`
Maps component

`import React, {Component} from 'react';
import {
    View,
    BackHandler,
    Animated
} from 'react-native';
import {bindActionCreators} from 'redux';
import {connect} from 'react-redux';
import Proptypes from 'prop-types';
import MapView, {UrlTile, Marker, Callout} from 'react-native-maps';
import Picker from 'react-native-picker';
import styles from './styles';
import * as actions from '../../modules/projects/reducers';

import ServicesInfoBox from '../../components/ServicesInfoBox';
import ServiceNoOkDetailBox from '../../components/ServiceNoOkDetailBox';
import ArrowBack from '../../components/ArrowBack';

class Maps extends Component {
    static navigationOptions = {
        header: null
    }

    static propTypes = {
        // projects: Proptypes.shape({}).isRequired,
        navigation: Proptypes.shape({
            navigate: Proptypes.func.isRequired
        }).isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            initialRegion: {
                latitude: -34.5737,
                longitude: -58.4630,
                latitudeDelta: 0.005,
                longitudeDelta: 0
            },
            markerLatLng: {
                latitude: -34.5737,
                longitude: -58.4630
            },
            services: [
                {
                    name: 'Luz',
                    status: 'no-ok',
                    icon: 'lightbulb-o'
                },
                {
                    name: 'Internet',
                    status: 'no-ok',
                    icon: 'wifi'
                },
                {
                    name: 'Cable',
                    status: 'ok',
                    icon: 'television'
                },
                {
                    name: 'Luz',
                    status: 'ok',
                    icon: 'phone'
                }
            ],
            showServiceNoOkDetailBox: false,
            animate: new Animated.Value(0)
        };
    }

    componentDidMount() {
        this.backHandler = BackHandler.addEventListener('hardwareBackPress', () => {
            this.handleBackPress();
            return true;
        });
    }

    componentWillUnmount() {
        this.backHandler.remove();
    }

    handleBackPress() {
        const {navigation} = this.props;
        navigation.goBack();
    }

    createDateData() {
        const {services} = this.state;

        const servicesNoOk = [];

        services.forEach(service => {
            if (service.status === 'no-ok') {
                servicesNoOk.push(service.name);
            }
        });

        return servicesNoOk;
    }

    render() {
        const {
            initialRegion,
            services,
            showServiceNoOkDetailBox,
            markerLatLng,
            animate
        } = this.state;

        const onShowHideServiceNoOkDetailBox = () => {
            if (!showServiceNoOkDetailBox) {
                Animated.timing(animate, {
                    toValue: 250,
                    duration: 800
                }).start();
            } else {
                Animated.timing(animate, {
                    toValue: 0,
                    duration: 800
                }).start();
            }

            this.setState({
                showServiceNoOkDetailBox: !showServiceNoOkDetailBox
            });
        };

        const showDatePicker = () => {
            Picker.init({
                pickerData: this.createDateData(),
                pickerFontColor: [255, 0, 0, 1],
                onPickerConfirm: (pickedValue, pickedIndex) => {
                    console.log('date', pickedValue, pickedIndex);
                    onShowHideServiceNoOkDetailBox();
                },
                onPickerCancel: (pickedValue, pickedIndex) => {
                    console.log('date', pickedValue, pickedIndex);
                },
                onPickerSelect: (pickedValue, pickedIndex) => {
                    console.log('date', pickedValue, pickedIndex);
                }
            });
            Picker.show();
        };

        const back = () => {
            const {navigation} = this.props;
            navigation.goBack();
        };

        return (
            <View style={styles.container}>
                <ArrowBack back={back}/>
                <MapView
                    provider={null}
                    mapType="none"
                    style={styles.map}
                    initialRegion={initialRegion}
                >
                    <UrlTile
                        urlTemplate="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        maximumZ={20}
                    />
                    <Marker
                        coordinate={markerLatLng}
                    >
                        <Callout
                            style={styles.callout}
                            onPress={() => showDatePicker()}
                        >
                            <ServicesInfoBox
                                services={services}
                            />
                        </Callout>
                    </Marker>
                </MapView>
                <ServiceNoOkDetailBox
                    address="Escobar 3101, CABA"
                    onShowHideServiceNoOkDetailBox={onShowHideServiceNoOkDetailBox}
                    animate={animate}
                />
            </View>
        );
    }
}

const mapStateToProps = state => ({projects: state.projects});
const mapDispatchToProps = dispatch => (bindActionCreators(actions, dispatch));

export default connect(mapStateToProps, mapDispatchToProps)(Maps);
`

The error

> renders correctly

    TypeError: this.map.setNativeProps is not a function

      at MapView._updateStyle (node_modules/react-native-maps/lib/components/MapView.js:490:16)
      at MapView.componentDidMount (node_modules/react-native-maps/lib/components/MapView.js:484:14)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6444:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7540:7)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1841:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1986:29)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7681:7)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8650:34)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8595:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8527:7)

**Comment by lucasluca** [comment]
Great, thanks a lot! it resolved here

**Comment by MoOx** [comment]
I recently got issues with Polyline so I am now using this

```js
jest.mock('react-native-maps', () => {
  const React = jest.requireActual('react');
  const MapView = jest.requireActual('react-native-maps');
  
  class MockMapView extends React.Component {
    render() {
      return React.createElement('MapView', this.props, this.props.children);
    }
  }
  MockMapView.propTypes = MapView.propTypes;

  class MockCallout extends React.Component {
    render() {
      return React.createElement('Callout', this.props, this.props.children);
    }
  }
  MockCallout.propTypes = MapView.Callout.propTypes;
  MockMapView.Callout = MockCallout;

  class MockMarker extends React.Component {
    render() {
      return React.createElement('Marker', this.props, this.props.children);
    }
  }
  MockMarker.propTypes = MapView.Marker.propTypes;
  MockMapView.Marker = MockMarker;
  
  class MockPolyline extends React.Component {
    render() {
      return React.createElement('Polyline', this.props, this.props.children);
    }
  }
  MockPolyline.propTypes = MapView.Polyline.propTypes;
  MockMapView.Polyline = MockPolyline;
  /* eslint-enable react/prefer-stateless-function */

  return MockMapView;
});
```

**Comment by christinavarghese06** [comment]
I recently got issues with MapView and DropDownPicker and I resolved this issue by mocking the respective packages.

`jest.mock("react-native-maps", () => "MapView");`

`jest.mock("react-native-dropdown-picker", () => "DropDownPicker");`
