### ISSUE TITLE
The function fitToElements doesn't work with MapView.Animated

### ISSUE THREAD

**Issue by KarlosQ** [react-community/react-native-maps#896]
The function fitToElements doesn't work with MapView.Animated. 

When i try:

`this.map.fitToElements(true);`

undefined is not a function (evaluating this.map.fitToElements(true)

Obviously I ref the map `ref={ref => { this.map = ref } }`

With MapView works fine..

How can make a fitToElements with MapView.Animated?

Missing documentation of MapView.Animted :(

**Comment by leandrobortolotto** [comment]
Hi @KarlosQ. I'm facing this trouble too. Did you solve this issue / problem?

Thanks

**Comment by KarlosQ** [comment]
No, i'm waiting for a answer :/

**Comment by symmetriccurve** [comment]
Check for the ref is set before you can call a  property on it.Try this out
ref = { (MapRef)=> if( MapRef !=null ) { MapRef.fitToElements(true) } }

**Comment by KarlosQ** [comment]
@symmetriccurve 
I don't understand your code. 

I have a MapView

```
        <MapView
          provider={ANDROID ? PROVIDER_GOOGLE : PROVIDER_DEFAULT}
          style={styles.map}
          initialRegion={this.initialRegion}
          showsUserLocation={true}
          ref={ref => { this.map = ref } }
          onRegionChangeComplete={(region) => this._changeRegion(region)}
          onPress={() => this._deselectMark()}>
          {...}
```

And when socket give me the array with the markers I do fitToElements with the ref.

```
socketCallback(markers){
this.setState({markers});
this.map.fitToElements(true);
}
```

This works if is a simple MapView but if is a MapView.Animated doesn't work.

**Comment by symmetriccurve** [comment]
This line here is setting the reference of the Map component to the this.map variable.
`ref={ref => { this.map = ref } }`
I doubt that the ref may be null when you try to access it i.e the reference has not been set yet(which is null).
Probably you have to console log and see what is inside this.map before you call a fitToElements method on it.

**Comment by niftylettuce** [comment]
thanks @symmetriccurve

**Comment by niftylettuce** [comment]
This is still an open issue should be fixed, MapView works fine but not Animated

**Comment by sean-macfarlane** [comment]
I too still have this issue with MapView.Animated

**Comment by rborn** [comment]
@KarlosQ please see https://github.com/react-community/react-native-maps/issues/896#issuecomment-387545969
Closing.

**Comment by lucasmouse** [comment]
Use `refThis.mapView.current.animateToRegion(region, 400)`
init `mapView = React.createRef()`
`<MapView ref={this.mapView}/>`
