### ISSUE TITLE
showsMyLocationButton only appears when I change device orientation

### ISSUE THREAD

**Issue by PigJuicer** [react-community/react-native-maps#905]
**showsMyLocationButton** component of MapView seems to only appear in map after I change device orientation.

Starting app in landscape or portrait doesn't make a difference. As soon as I change orientation to Portrait or Landscape once, button appears on the top right corner. However, it is not there when the MapView appears for the first time.

![image](https://cloud.githubusercontent.com/assets/6059835/21293789/c5b6d90c-c536-11e6-9475-3fd8f6f2fbc5.png)

![image](https://cloud.githubusercontent.com/assets/6059835/21293787/c058d08c-c536-11e6-8b76-14e47f584005.png)

**Comment by sagark1510** [comment]
I also face the same issue. Any solution?

**Comment by sagark1510** [comment]
Any update? @PigJuicer did you find any workaround?

**Comment by PigJuicer** [comment]
Nope, I tried for a couple days but then didn't bother with it since it's not necessary for my project.

**Comment by jeffreymendez1993** [comment]
same issue here

**Comment by psam44** [comment]
Please follow the issue on #1033.

**Comment by alvelig** [comment]
Duplicate of #1033
