### ISSUE TITLE
Сluster MapView.Markers on large scale

### ISSUE THREAD

**Issue by Clcll** [react-community/react-native-maps#908]
how to use marker clusters to display a large number of markers on a map ?
https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by Clcll** [comment]
@machard

**Comment by saberking** [comment]
I used https://github.com/mapbox/supercluster
Here is a great gist showing how to use with React-Native https://gist.github.com/i-tu/05e79737adfe36935ec869125a686f82

**Comment by alvelig** [comment]
Duplicate #213
