### ISSUE TITLE
Set zoom level

### ISSUE THREAD

**Issue by nhatchimai111** [react-community/react-native-maps#920]
How to set zoom level for google map?
Help me!

**Comment by symmetriccurve** [comment]
use longitudeDelta and latitudeDelta values to the region object to set the Zoom level.

**Comment by Mubeena17** [comment]
+1

**Comment by maggialejandro** [comment]
I use this code

```javascript
const { region } = this.state;
const newRegion = {
  latitude: coordinates.latitude,
  longitude: coordinates.longitude,
  latitudeDelta: region.latitudeDelta - (region.latitudeDelta / 1.2),
  longitudeDelta: region.longitudeDelta - (region.longitudeDelta / 1.2),
};

this.mapRef.animateToRegion(newRegion, 500);
```

**Comment by alvelig** [comment]
The deltas are zoomControls

**Comment by shrikantkunte** [comment]
@alvelig I am using default zoom controller by  zoomControlEnabled={true}. Can we change the position of this zoom controller?

**Comment by miracle2k** [comment]
@shrikantkunte Hopefully in the future, https://github.com/react-community/react-native-maps/pull/2563 will provide this.
