### ISSUE TITLE
Conflict with react-native-google-place-picker

### ISSUE THREAD

**Issue by KamWis** [react-community/react-native-maps#921]
Hi!

Thanks for awesome package! :) I have some trouble with building my app since I met with react-native-google-place-picker and react-native-maps conflict. Error is small:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException:
com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzsk;
```

It seems it's because react-native-google-place-picker using in dependencies `compile 'com.google.android.gms:play-services-location:8.4.0'`. But is there a way to prevent such conflicts? So react-native-maps will be save from other packages?

Any ideas? :)

**Comment by kevinhury** [comment]
did you manage to fix the problem?

**Comment by KamWis** [comment]
Hello @kevinhury - for now I decided to move from `google-place-picker` to `react-native-google-places`. Those were compatible. There is no easy fix for dependencies of each package.

Also take a look at Expo - it has many packages you probably would like to use and they took the hard part of handling dependencies for you :)

**Comment by sibelius** [comment]
try this on build.gradle

```groovy
compile (project(':react-native-maps')) {
        exclude group: "com.google.android.gms"
    }
```
