### ISSUE TITLE
GMSMapStyle is not present issue

### ISSUE THREAD

**Issue by Vinu-MysteriousTechVision** [react-community/react-native-maps#931]
HI 
Download the SDK from npm then installs the pod for Google Maps to support google map in iOS. Installed Google map version is seem to be a lower version, that's  why getting build error **GMSMapStyle is not present**. When I am checking the **`https://github.com/airbnb/react-native-maps/blob/master/react-native-google-maps.podspec`** dependency updated to the new version, but npm installed SDK gets the old version dependency **s.dependency 'GoogleMaps', '2.0.1'**.

Please suggest a solution to get the latest update of **react-native-maps SDK** in **npm install**

**Comment by kanhaic** [comment]
I am having the same issue.
+1

**Comment by kanhaic** [comment]
using version GoogleMaps ios SDK 2.1.0 or 2.1.1 solves the issue.

**Comment by kanhaic** [comment]
Issue is resolved when google maps sdk is upgraded to 2.1.0 or 2.1.1

**Comment by alvelig** [comment]
On iOS stick to the latest always. On Android it's complicated #1773
