### ISSUE TITLE
Ability to Customize "My Location" Text

### ISSUE THREAD

**Issue by joncursi** [react-community/react-native-maps#934]
Would be great if this text were customizable via prop, especially for internationalized apps that use different languages based on user locale.

![screen shot 2017-01-04 at 3 19 35 pm](https://cloud.githubusercontent.com/assets/4974609/21657654/418e4c06-d291-11e6-8871-c109da1c3573.png)

**Comment by americool** [comment]
I did a little triaging and I think I've found the relevant component(s) inside MApView that generating the AIRMap on the fly. https://github.com/airbnb/react-native-maps/blob/master/components/MapView.js#L646-L648 

I'm new to react-native and this project, but I'm eager to help out. Would this require extensive objective C/Java knowledge?  

I'll continue to read the code for know, but any direction would be greatly appreciated.
