### ISSUE TITLE
(Android - fitToCoordinates ) map is null

### ISSUE THREAD

**Issue by DennisSnijder** [react-community/react-native-maps#941]
ComponentDidMount is being called too early, which resolves the fitToCoordinates is trying to execute on a null variable.

a cheap fix for this is setting a TimeOut of 500ms and call the function in the callback.

Tried this on a clean install.
Also tried this using ExponentJS which comes with react-native-maps.

**Comment by DennisSnijder** [comment]
fitToCoordinates still works on IOS.

**Comment by kevinnguy** [comment]
Had the same issue where I would get the error:
`Attempt to invoke virtual method setPadding on a null object reference` in the fitToCoordinates method.

**Comment by kevinnguy** [comment]
![0](https://cloud.githubusercontent.com/assets/1483123/22132543/6da09c2e-de6f-11e6-8298-5bbb0fa92527.png)

**Comment by okarakose** [comment]
any updates on this issue ? I have same problem too in 0.13.0 

and what was your react-native-maps version ?

**Comment by alvelig** [comment]
You need to wait for onMapReady https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
