### ISSUE TITLE
Andriod Emulator Showing Blank Screen

### ISSUE THREAD

**Issue by Newbieyh** [react-community/react-native-maps#942]
Hi, 

I followed the issue being posted about the same topic and did everything that was posted on it. but still no luck. 
![googleblank](https://cloud.githubusercontent.com/assets/24843470/21744303/9d491be2-d4e0-11e6-8e48-b60b7c580b30.jpg)

The code is:

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import MapView from 'react-native-maps';

export default class ReactNativeMaps extends Component {
  render() {
   const { region } = this.props;
   console.log(region);

   return (
     <View style ={styles.container}>
       <MapView
         style={styles.map}
         region={{
           latitude: 39.1329,
           longitude: 84.5150,
           latitudeDelta: 0.015,
           longitudeDelta: 0.0121,
         }}
       >
       </MapView>
     </View>
   );
 }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});

AppRegistry.registerComponent('ReactNativeMaps', () => ReactNativeMaps);

**Comment by codesidekick** [comment]
I'm stuck on this issue too. API key is definitely in AndroidManifest. Works perfect in iOS with exactly the same view (but using iOS native maps).

**Comment by Newbieyh** [comment]
@codesidekick you can follow issue #118 for all the steps to configure. I think it might help you. For me I have tried all the things in that issue and still have a blank screen. Need someone who can help.

**Comment by codesidekick** [comment]
Thanks for the tip. I'd followed all steps on 118 and pull requested some of the documentation as well before commenting on this issue. I'm running on an absolutely fresh react-native and react-native-maps on a totally sandboxed project. Next step is to try the react-native-maps example project and see if it still occurs.

Just to clarify I get the exact same view as in the screenshot of this issue. The map is seemingly rendered, but rendered grey with the Google logo on the bottom right. iOS works perfectly fine.

**Comment by codesidekick** [comment]
Got the example running, still the same grey maps issue. Swapped out the API keys and no luck. Changed google play version to 10.0.1 and still no luck.

AND THEN ... I noticed logcat had a message about Google Maps requiring OpenGL.

I went back to my AVD settings and checked the 'Use host GPU' setting and all of a sudden the maps come alive! I've attached a screenshot of the Android Virtual Device settings.

I've created a pull request at https://github.com/airbnb/react-native-maps/pull/947 to add this to troubleshooting instructions.

![avd](https://cloud.githubusercontent.com/assets/11308291/21790234/ea1a7ae2-d72e-11e6-8b7c-06319b709fcd.png)

**Comment by IamJoseph** [comment]
Thank you @codesidekick that worked for me. Finally!

**Comment by philberg** [comment]
### Issue
@codesidekick I also had a ton of trouble getting the example to run, but for a different reason.  Do you have any insight as to why this happens?  Maybe I'll make a PR to the troubleshooting guide.

This error message was displayed on screen, in the place of the map.  I'm leaving it here because I couldn't find it with any other google search.

> MyApp won't run without Google Play Services, which are no supported by your device.

I'm running the latest version of OSX and react-native 0.40 (all brand new installation).

### Solution
When I run AVD manager using the command line (as suggested in the react native tutorial), I can't use a CPU with google APIs.  They are definitely installed in the SDK mange, but they don't show up as an option.  It seems that the AVD that is launched from inside of android studio is different, and has the available options I need.  Once I created the correct device, I still couldn't launch it from the cmd line AVD manager, only the one inside of android studio.

**Comment by codesidekick** [comment]
The entire AVD experience unfortunately is still difficult to set up compared to the iOS simulator. I'm finding working on a hardware device using adb a lot smoother. Not a solution but rather a suggestion.

**Comment by thanhnha1103** [comment]
I'm stuck on this issue too.
Then I found my misstake when I create my AVD:
1. I must select "Google APIs Intel Atom ....." for CPU/ABI
2. I need to check "Use Host GPU"

**Comment by muyang** [comment]
I met the same problem as yours when I use my own google API keys.
But when I used the key from the react-native-maps/examples, it worked well.

**Comment by vsherms** [comment]
Had an issue where there is no option for "Use Host GPU" or "CPU/ABI" in the AVD manager. Any ideas for this?

**Comment by philberg** [comment]
@vsherms did you install HAXM?

**Comment by alvelig** [comment]
GOOGLEMAPS API_KEY problem.

**Comment by flamesoft** [comment]
You need to install all the SDKs in the SDK manager for the version that you want to test and then create a new emulator at this SDK level.

**Comment by Areeeb** [comment]
I changed my AVD emulated performance to Hardware - GLES 2.0 and replaced my API key with the one in react-native-maps/examples, still standing where i was, the map is not visible, map gets visible when i close the application and re-open it [Not stopping the running project, just pressing the back button to close], the map doesn't show itself as moving, but it is actually moving. How to solve this.
![screenshot_1523207425](https://user-images.githubusercontent.com/22966183/38470265-aa70a1e0-3b79-11e8-9aed-241f7fd5bee4.png)

**Comment by rborn** [comment]
@Areeeb this is a key problem, be sure you you use your own key and that the key is not limited in any way in the google console.
