### ISSUE TITLE
Googlemaps and IOS

### ISSUE THREAD

**Issue by hosusan6** [react-community/react-native-maps#943]
Two problems for me. 

1. If i dont include the airmaps folder in my project i can get a successfull build in the simulator and a fully working googlemaps. 

but when i try to build out to a device i get this error showing me that the airmaps resources are missing

Lexical  or preprocessor issue
AirMapCoordinate.h fiel not found

2. If i then add the airmaps folder back into the project i get mutliple errors indidcatiing duplicate symbols
There are 179 so i just copied a few. but if more needed please let me know
````
AIRMapCircleManager.o
    /Users/william/Library/Developer/Xcode/DerivedData/Model_App-efdkaixyaidupmacstbxxfyvbfwm/Build/Products/Debug-iphoneos/libAirMaps.a(AIRMapCircleManager.o)
duplicate symbol _OBJC_CLASS_$_AIRMapCalloutManager in:
    /Users/william/Library/Developer/Xcode/DerivedData/Model_App-efdkaixyaidupmacstbxxfyvbfwm/Build/Intermediates/Model_App.build/Debug-iphoneos/Model_App.build/Objects-normal/arm64/AIRMapCalloutManager.o
    /Users/william/Library/Developer/Xcode/DerivedData/Model_App-efdkaixyaidupmacstbxxfyvbfwm/Build/Products/Debug-iphoneos/libAirMaps.a(AIRMapCalloutManager.o)
duplicate symbol _OBJC_METACLASS_$_AIRMapCalloutManager in:
    /Users/william/Library/Developer/Xcode/DerivedData/Model_App-efdkaixyaidupmacstbxxfyvbfwm/Build/Intermediates/Model_App.build/Debug-iphoneos/Model_App.build/Objects-normal/arm64/AIRMapCalloutManager.o
    /Users/william/Library/Developer/Xcode/DerivedData/Model_App-efdkaixyaidupmacstbxxfyvbfwm/Build/Products/Debug-iphoneos/libAirMaps.a(AIRMapCalloutManager.o)
ld: 179 duplicate symbols for architecture arm64

**Comment by yourcontainer** [comment]
which version of react native do you use?

**Comment by hosusan6** [comment]
react-native: 0.40.0

**Comment by amejia49** [comment]
experiencing the same issue, RN version .40

**Comment by nrathi** [comment]
+1, except here were some assumptions I made: 

Since we no longer have `use_framworks!' in the Podfile, I added:

```
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
```

And deleted the references to the drag-and-dropped AirMaps and AirGoogleMaps folders, per https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md. 

This caused a "module not found" error, which I resolved by setting Enable Modules in Build Settings to NO. 

It should be known that I experienced this "duplicate symbols" error even before I did all this, and only when archiving.

**Comment by vinceyuan** [comment]
I successfully added `GoogleMaps` support for iOS. I updated the doc in PR #950. You can follow my steps to solve this issue.

Versions:
```
    "react": "15.4.2",
    "react-native": "0.40.0",
    "react-native-maps": "^0.13.0"
```

**Comment by gilbox** [comment]
Can anyone confirm that vinceyuan's suggestion works?

**Comment by hosusan6** [comment]
for me it didn't im afraid

**Comment by vinceyuan** [comment]
@hosusan6 It should work in a new project. What didn't work for you? If you are upgrading an existing project, probably you need to run `react-native upgrade` very carefully first, because react-native has some changes in 0.40.0. When you upgrade your project, I suggest you create a new project for references.

**Comment by binzailani3136** [comment]
Same issue here.
It works very well on simulator but when I am trying to achive, it shows error.
```
ld: 396 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Tried everything above but all failed.
I am using
    "react": "~15.4.0-rc.4",
    "react-native": "0.40.0",
    "react-native-maps": "^0.13.0"
Anybody can help?

**Comment by wyattlindsey** [comment]
I'm getting the exact same error with 396 duplicate symbols:

`ld: 396 duplicate symbols for architecture arm64`

```
"react": "^15.4.2",
"react-native": "^0.40.0",
"react-native-maps": "^0.13.0"
```

**Comment by wyattlindsey** [comment]
@binzailani3136 I was able to archive my project by removing the following in my Podfile

```
pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
```

...and replacing it with:

```
pod 'React', path: '../node_modules/react-native'
```

After another `pod install` I was able to archive.  I think the sub dependencies specified in the Podfile were redundant.

**Comment by jordanmkoncz** [comment]
@wyattlindsey Thanks for posting this, I was having the same issue with duplicate symbols when trying to create an Archive in Xcode.

For reference, here's my relevant dependencies:
```json
"react": "~15.4.0",
"react-native": "0.41.2",
"react-native-maps": "0.13.0",
```

And here's my modified (and now *working*) Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Crave' do
  pod 'React', path: '../node_modules/react-native'

  pod 'GoogleMaps'

end
```

I followed the instructions at https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md and did Option 1 under iOS and now have Google Maps fully working on iOS.

**Comment by dorthwein** [comment]
I mean this is a bit of a joke - why not just have google maps work through linking.  The number of dead end map implementations & out of date guides in this repo is breath taking for being the "Officially Suggested" package.

**Comment by Moumene** [comment]
thanks for the solution @jordanmkoncz, just in new versions of react you need this
`pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'`

**Comment by RWOverdijk** [comment]
Is there a new guide for this somewhere? The current one seems to not work. I tried the suggestions in here which only seems to make matters worse.

**Comment by jordanmkoncz** [comment]
I just had to add react-native-maps to a new app I'm working on, and unfortunately it looks like the instructions at https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md are still incorrect and do not work. I tried following the instructions under Option 1, and also tried Option 3, and neither of these actually worked, I always ended up with errors when trying to build the app for iOS.

In the end I was able to get everything working by following the instructions at https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14. The only thing I did differently from the instructions was a slight difference in my Podfile, as the Podfile in those instructions was resulting in an error "The name of the given podspec `yoga` doesn't match the expected one `Yoga`".

Below is my working Podfile:

```
platform :ios, '8.0'

target 'MyAppName' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'GoogleMaps'
end
```

And here's my dependencies:

```js
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-maps": "0.17.1",
```

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by senseialex** [comment]
@alvelig  Do you use react-link?

**Comment by senseialex** [comment]
@alvelig Do you use react-native link?

**Comment by alvelig** [comment]
@senseialex With pods you should not use `react-native link`

**Comment by senseialex** [comment]
Thanks!, I resolve the problem with your guide

On Jan 2, 2018, at 1:55 PM, Alexander Veligurov <notifications@github.com<mailto:notifications@github.com>> wrote:


@senseialex<https://github.com/senseialex> With pods you should not use react-native link

**Comment by bportman** [comment]
I had a similar problem trying to use react-native-maps in conjunction with a detached ExpoKit project.  Seems ExpoKit includes react-native-maps, so linking it separately created duplicate references.  Fortunately, I was able to use `react-native unlink react-native-maps` and then my project would build.  The full procedure described in the documentation was not necessary.

**Comment by tomgit2016** [comment]
> @senseialex With pods you should not use `react-native link`

The documentation should clearly state that.

**Comment by nomi9995** [comment]
add these three line and install pod again

```
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'  # If you need GoogleMaps ```
