### ISSUE TITLE
v0.13.0, code is breaking in iOS

### ISSUE THREAD

**Issue by kvs-db** [react-community/react-native-maps#948]
I am using v0.13.0 in my project, but the code is breaking. When I tried to run the application in iOS, I am getting the following error message, and build is getting failed.

CompileC /Users/username/Desktop/projectname/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCallout.o AirMaps/AIRMapCallout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

But it is working properly in v0.12.2.

**Comment by davidtran** [comment]
I am having this issue too. I am using React Native 0.40.0

**Comment by infinitey** [comment]
The following build commands failed:
	CompileC /Users/username/project/FoodProject/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCallout.o AirMaps/AIRMapCallout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Same here. Using 0.40.0 and I having the exact same issue.

**Comment by anhdbknws** [comment]
you can try to change port "react-native start --port=8088"

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
