### ISSUE TITLE
In android the current location is not zooming in when loading the map initially

### ISSUE THREAD

**Issue by swaroopa94** [react-community/react-native-maps#949]
Hi,
I am using your module for the maps. In iOS it working fine and when initally loads its showing the current position in zoom.

But in Androd it showing the current location pointer but its not zooming in.
Here is my code:

For iOS:
```
 <MapView style={{height:height,width:width}}
         showsUserLocation ={true} 
         followsUserLocation = {true} />
```

for Android:
here is the screenshot
![screenshot_2017-01-11-01-27-03](https://cloud.githubusercontent.com/assets/19324363/21837989/80f61b1c-d7f5-11e6-9857-131bf138afab.png)

  ```
      <MapView style={styles.map}
         showsUserLocation ={true} 
         rotateEnabled = {true}
         zoomEnabled = {true}
         showsMyLocationButton = {true}
          />
```
For android the followUserLocationis not working 
Can anyone help me to solve this.

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
