### ISSUE TITLE
animateToCoordinate in iOS with Google Maps

### ISSUE THREAD

**Issue by KarlosQ** [react-community/react-native-maps#955]
If I execute the method animateToCoordinate in iOS using the google maps the app crash and show me this stack trace:

![captura de pantalla 2017-01-12 a las 13 28 07](https://cloud.githubusercontent.com/assets/15233913/21889820/1a50cd86-d8cb-11e6-9c78-367ab820933f.png)

Can anybody tell me what I should do? Thanks!

**Comment by KarlosQ** [comment]
The problem is easy resolved if instead animateToCoordinate I use animateToRegion with current region.longitudeDelta and region.latitudeDelta.

**Comment by jpgarcia** [comment]
I'm facing the same issue

**Comment by boytainnt** [comment]
i think because you use Google Map and rn-maps stil get AirMap 
<img width="673" alt="screen shot 2017-02-17 at 3 08 12 pm" src="https://cloud.githubusercontent.com/assets/15927583/23057472/f19f7968-f522-11e6-86e9-220691e659cb.png">
