### ISSUE TITLE
Marker with custom view as children is not re-rendering on the same location

### ISSUE THREAD

**Issue by lucasbento** [react-community/react-native-maps#959]
I have a marker like this:
```
     <MapView.Marker.Animated
        coordinate={userLocation}
        title="I'm here"
      >
        <View style={styles.mapMarker}>
          <View style={styles.marker} />
        </View>
      </MapView.Marker.Animated>
```

When I change a part of the code, it renders **another marker** which doesn't change anything else except its location and the **region** of the map, the first marker's (mentioned above) content keeps on the same place **of the screen**, fixed on it without leaving even if the map moves.

This is happening on iOS (did not test on Android) and only happens with a component specified as a child.

**Comment by jchiefelk** [comment]
+1

**Comment by lucasbento** [comment]
This bug seems to be related to iOS only, running fine on Android.

**Comment by unboundfire** [comment]
@lucasbento running into this as well, do you have any idea what could be causing it?

**Comment by alvelig** [comment]
Might be related to #483

**Comment by Khsed4** [comment]
@alvelig  why u like to close the issue before there be a reasonable answer , I see you closed the issue in so many issues , and it made me sad .
