### ISSUE TITLE
fitToElements to include overlays on iOS

### ISSUE THREAD

**Issue by micksabox** [react-community/react-native-maps#96]
Great library here.

I need to be able to zoom the map to fit one or more overlays. I've accomplished this on iOS using these changes: in AIRMapManager.m -fitToElements:animated:

```
MKMapRect concatedMapRect = MKMapRectNull;

for( id<MKOverlay>overlay  in mapView.overlays){

    concatedMapRect = MKMapRectUnion(concatedMapRect, [overlay boundingMapRect]);
}

[mapView setVisibleMapRect:concatedMapRect
               edgePadding:UIEdgeInsetsMake(10.0f, 10.0f, 10.0f, 10.0f)
                  animated:animated];
```

I can submit a pull request when I have some extra time. Just posting here in case anyone wants to contribute to the discussion of the API.

**Comment by micksabox** [comment]
See pull request #97

**Comment by rborn** [comment]
closing very old
