### ISSUE TITLE
Rounded Opaque Buttons

### ISSUE THREAD

**Issue by bingle87** [react-community/react-native-maps#963]
How do I get the rounded opaque buttons on the map that are shown in numerous examples?

**Comment by salilbajaj** [comment]
Did you find any workaround for this yet??

**Comment by bingle87** [comment]
No. I am still looking for a way to place a button on the map area.

**Comment by salilbajaj** [comment]
Did it. Here's my code:

 <MapView onPress={this.onPre.bind(this)} scrollEnabled={false} style={{width:devWidth,height:devHeight/1.6}}
    initialRegion={{
      latitude: data.loc.coordinates[0],
      longitude: data.loc.coordinates[1],
       latitudeDelta: 0.0722,
      longitudeDelta: 0.0521
    }}
  >
  <TouchableOpacity style={{position:'absolute',top:5,left:5,backgroundColor:'rgba(0,0,0,.2)'}}>
    <Icon name="times" size={11} color="#fff" />
  </TouchableOpacity>
 <MapView.Marker pinColor='#e12f27'
                                coordinate={{
                                  latitude: data.loc.coordinates[0],
                                  longitude: data.loc.coordinates[1]
                                }}
                          />
  </MapView>

**Comment by bingle87** [comment]
Thanks I'll try it out.

**Comment by salilbajaj** [comment]
It was not copied properly


<MapView onPress={this.onPre.bind(this)} scrollEnabled={false} style={{width:devWidth,height:devHeight/1.6}}
                  initialRegion={{
                      latitude: data.loc.coordinates[0],
                      longitude: data.loc.coordinates[1],
                       latitudeDelta: 0.0722,
                      longitudeDelta: 0.0521
                    }}
                  >
            <TouchableOpacity style={{position:'absolute',top:5,left:5,backgroundColor:'rgba(0,0,0,.2)'}}>
               <Icon name="times" size={11} color="#fff" />
            </TouchableOpacity>
               <MapView.Marker pinColor='#e12f27'
                                coordinate={{
                                  latitude: data.loc.coordinates[0],
                                  longitude: data.loc.coordinates[1]
                                }}
                          />
               </MapView>

**Comment by alvelig** [comment]
Not related.
