### ISSUE TITLE
RN 40 with Maps 13 - framework not found GoogleMaps - iOS

### ISSUE THREAD

**Issue by vinceprofeta** [react-community/react-native-maps#965]
Following the instructors for the recommended installation instructions creates an error

```
ld: framework not found GoogleMaps
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I may have misunderstod instructions but I have a few questions:
- "Drag the following folder into your project" - does it matter where in the project you drag it to?
- Nothing mentions modifying the app delegate file, but a number of comments in issues describe adding an import and api keys?
- I get the following warning on pod install. The `[Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Tyro/Pods-Tyro.release.xcconfig'. This can lead to problems with the CocoaPods installation.

Can you clarify and add a FAQ to the readme. Everything was working fine until I upgraded. Please help.

**Comment by tyleragypt** [comment]
@vinceprofeta Did you ever figure this out? If so, do you recall the correct steps? Currently upgrading my project and running into the same error... Thanks

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.
