### ISSUE TITLE
Show current location with a marker when opening app

### ISSUE THREAD

**Issue by AndriesLSteenkamp** [react-community/react-native-maps#968]
How can I get my current location and then display it on the app?

**Comment by amejia49** [comment]
React Native uses the browser Geolocation API [https://facebook.github.io/react-native/docs/geolocation.html](https://facebook.github.io/react-native/docs/geolocation.html) ... you can get your coordinates using that and pass it on to a marker

**Comment by milon87** [comment]
is it possible to get current coordinate using react native maps?

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by robintsunny** [comment]
how would I be able to open the map up to have my current location in the center of the screen? right now, i'm hard coding it in, but can't get the state to update and re-render when my current location is calculated

**Comment by amit13091992** [comment]
> how would I be able to open the map up to have my current location in the center of the screen? right now, i'm hard coding it in, but can't get the state to update and re-render when my current location is calculated

@robintsunny  Did you get any solutions?

**Comment by richardbumm** [comment]
@robintsunny I suggest looking into the Geolocation feature and using geolocation.getCurrentPosition to get the current position of the user, and then update the map region in the function using component state. This will trigger a re-render of the component and place the map above the current region of the user.

**Comment by AmitPandya007** [comment]
> @robintsunny I suggest looking into the Geolocation feature and using geolocation.getCurrentPosition to get the current position of the user, and then update the map region in the function using component state. This will trigger a re-render of the component and place the map above the current region of the user.

@richardbumm 
I am getting some unwanted behavior from maps when using gelocation.watchposition().
Are you familiar with this issue?
