### ISSUE TITLE
RN 0.40 and React-native-maps 0.13.0 Android Warning: Native component for "AIRMap" does not exist

### ISSUE THREAD

**Issue by GarimaMathur07** [react-community/react-native-maps#970]
Hello All,

I am adding airbnb map view to existing android native application.

I am using RN 0.40 and react-native-maps 0.13.0.

after the react-link commands. Then android always have the Warning: 
**Native component for "AIRMap" does not exist.**
Running application "App" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

Here is complete code
https://github.com/GarimaMathur07/CustomReactComponent

Please tell any solution
Thanks

**Comment by GarimaMathur07** [comment]
@jayhuang75 have you deal with this issue.

Can you please suggest for it

**Comment by jayhuang75** [comment]
Yes! For sure here is the solution and command line https://github.com/airbnb/react-native-maps/issues/969#issuecomment-273182643

**Comment by sahir** [comment]
i am facing same issue @jayhuang75 i try your solution command line #969 (comment) but still facing Warning. i also try code provide by @GarimaMathur07 https://github.com/GarimaMathur07/CustomReactComponent can you please look into this code 
![mapview](https://cloud.githubusercontent.com/assets/452706/22071564/8625de26-ddc5-11e6-9214-30656c5cb734.png)

**Comment by jayhuang75** [comment]
@sahir in this case I think will more be the style issues:
try style 
` mapContainer: {
        flex: 1,
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height
    }`

**Comment by leonciocaminha** [comment]
same issue
![screen shot 2017-01-18 at 4 37 51 pm](https://cloud.githubusercontent.com/assets/620401/22079973/8624fbb0-dd9c-11e6-926c-094429f68a1a.png)
![screen shot 2017-01-18 at 4 37 12 pm](https://cloud.githubusercontent.com/assets/620401/22079982/8aed51b0-dd9c-11e6-919a-40ba2c862c2b.png)

**Comment by jayhuang75** [comment]
@leonciocaminha Did you try this? https://github.com/airbnb/react-native-maps/issues/969#issuecomment-273182643

**Comment by GarimaMathur07** [comment]
@jayhuang75 as mentioned above I have successfully integrated map in react app. 

But in exisitng native android app i am getting this warning.

I am using following style but no success.

```
containerStyle: {
    flex: 1,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height
  }
```
node_modules maven entry is:

```
 maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/node_modules/react-native/android"
        }
```
I am not getting what is difference between react app and native existing android app structure.

I am doing same setup for existing app but always getting this **Warning (Native component for "AIRMap" does not exist)** 

and in react app i had successfully added map view.

I have done with all basic steps and npm linking commands mentioned in installation guide for existing app in android and always getting empty map with red border.

Can you please help in brief. I spent many hours for integration in existing but no success.

**Comment by sahir** [comment]
@leonciocaminha you fix the issue.

**Comment by sahir** [comment]
@jayhuang75 i try with provided style sheet but no luck.

**Comment by leonciocaminha** [comment]
@sahir nothing dude...i tried downgrade to React-Native 0.38 but no success...

**Comment by peteleco** [comment]
I was getting the same error then i realize that i was using 0.12.4 after updating to 0.13.0 started work again. 

But i run the code below: 
```
$ react-native unlink react-native-maps
$ react-native link react-native-maps
```

And recompile the project.

**Comment by leonciocaminha** [comment]
@peteleco what your react-native version? 040? working maps into it?

**Comment by leonciocaminha** [comment]
Hello Everybody! 

I downgrade my app to 0.38.0 and react-native-maps to 0.12.4 and it working!

the react-native link is not working properly, as we can see, the airmaps appears into list but not properly, remove it and add again.

![screen shot 2017-01-19 at 10 22 27 pm](https://cloud.githubusercontent.com/assets/620401/22144037/0aab714a-dedb-11e6-9077-ce1525fc1406.png)

should appear like this

![Uploading Screen Shot 2017-01-19 at 10.03.19 PM.png…]()

and this step should be done too:

![screen shot 2017-01-19 at 9 42 16 pm](https://cloud.githubusercontent.com/assets/620401/22144167/8dc13e34-dedb-11e6-8892-c982c8f03119.png)

and voila!

its working

![screen shot 2017-01-20 at 6 42 12 am](https://cloud.githubusercontent.com/assets/620401/22144197/a158ec62-dedb-11e6-95a8-22d37bcd4d69.png)

**Comment by GarimaMathur07** [comment]
@leonciocaminha 

As mentioned above I have successfully integrated map in react app.

But in exisitng native android app i am getting this warning **(Native component for "AIRMap" does not exist)**

When I downgrade my app to 0.38.0 and react-native-maps to 0.12.4 then it is not working in android

So, how can i identify the reason of this warning.

**Comment by magrinj** [comment]
@GarimaMathur07 Can you copy-paste your `build.gradle`, `app/build.graldle` and your `MainApplication.java` please ? (Sometimes if you do `react-native link` command twice, the package will be added two time in `MainApplication.java`)

**Comment by assitaliroma** [comment]
I had the issue yesterday in `iOS` and as @leonciocaminha said, if you link the library manually it should work. I installed `react-native-maps` `0.12.4` and later on I just linked the library as described in: https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md (Option 3) and it's working now, perhaps it's the same issue in Android? did you try to link the library manually there @GarimaMathur07 ?

**Comment by sahir** [comment]
@magrinj i think @GarimaMathur07  open sources complete project. i also try this project but no luck.

Git Repo : https://github.com/GarimaMathur07/CustomReactComponent

MainApplication : https://github.com/GarimaMathur07/CustomReactComponent/blob/master/app/src/main/java/punchh/customreactcomponent/MainApplication.java 

build.gradle
https://github.com/GarimaMathur07/CustomReactComponent/blob/master/app/build.gradle

**Comment by magrinj** [comment]
@sahir Thanks, I didn't see that all the project is imported on GitHub :/ 

@GarimaMathur07 In your `settings.gradle` this one:

https://github.com/GarimaMathur07/CustomReactComponent/blob/master/settings.gradle

Try to change this line:

`project(':react-native-maps').projectDir = new File(rootProject.projectDir, '/node_modules/react-native-maps/android')`

to this one:

`project(':react-native-maps').projectDir = new File(rootProject.projectDir, './node_modules/react-native-maps/android')`

(I just add the dot in the absolute path, because '/' redirect on the root of your machine and not the root of the project)

and run it again :)

Tell me if it's working

**Comment by GarimaMathur07** [comment]
@magrinj Thanks for your answer. Is it also changed for top level build.gradle file.

```
allprojects {
    repositories {
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/node_modules/react-native/android"
        }
    }
}
```

**Comment by magrinj** [comment]
@GarimaMathur07 I think it's good for the top level `build.gradle` because `$rootDir` actually point on the root of your project, did the solution fix your problem ?

**Comment by varunrayen** [comment]
I had the same issue in ios, just closed the simulator and re-run `react-native run-ios`. It worked.

**Comment by LuisMesa** [comment]
From the beginning this is what I did:

1. Create project
`react-native init MAP`

2. In android/app/src/main/AndroidManifest.xml add a new `meta-data` child to the `application` tag:
```
<meta-data
                android:name="com.google.android.maps.v2.API_KEY"
                android:value="YOUR_API_KEY"/>
```

3. Enable your API for Android or IOs:
https://console.cloud.google.com/apis/api/maps_android_backend/overview?project=sage-etching-147318&duration=PT1H

4. Install and Link the package:
`npm i react-native-maps --save `
`react-native link`

5. Add the MapView in index.android.js:
```
import React, { Component } from 'react';
import {AppRegistry, StyleSheet, Text, View, Dimensions} from 'react-native';
import MapView from 'react-native-maps';

export default class MAP extends Component {
  render() {
    return (
        <View style ={styles.container}>
          <MapView
              style={styles.map}
              region={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121,
          }}
          >
          </MapView>
        </View>
    );
  }
}

let { width, height } = Dimensions.get('window');
const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    height: 400,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    flex: 1,
    width: width,
    height: height,
  },
});

AppRegistry.registerComponent('MAP', () => MAP);

```
6. Run:
`npm start --clear-cache`
`react-native run-android` 

**In Case Of Error**
`cd android`
`gradlew clean`
`cd ..`
`react-native run-android`

It works for me, I hope it helps someone in the future.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by MarkOSullivan94** [comment]
@alvelig why did you close this? I can't see anything in your link about Android

**Comment by alvelig** [comment]
@MarkOSullivan94 

can you make a reproducible example? Could you please provide
