### ISSUE TITLE
Get coordinates of corners of visible map

### ISSUE THREAD

**Issue by Clcll** [react-community/react-native-maps#975]
How to get coordinates of corners of visible bing map?

**Comment by DVassilev** [comment]
Get the current region of the map, then add and remove the latitudeDelta to latitude and do the same with longitude. This will give you the coordinates of the corners.

**Comment by beerteam** [comment]
Did you solve the problem?

**Comment by jDeppen** [comment]
Related (no solution yet) https://github.com/airbnb/react-native-maps/issues/356

**Comment by alvelig** [comment]
Duplicate of #356
