### ISSUE TITLE
Get Callout to appear on top left of screen

### ISSUE THREAD

**Issue by amejia49** [react-community/react-native-maps#978]
Hey I'm trying to get the Callout to appear in the top left of screen, but I can't seem to get the callout to escape the marker's viewpoint. How do I go about doing this?

**Comment by i8wu** [comment]
I think you need to look at calloutOffset or calloutAnchor https://github.com/airbnb/react-native-maps/blob/master/docs/marker.md

**Comment by alvelig** [comment]
Use onMarkerPress and show a View above the Map where you want.
