### ISSUE TITLE
Center Button & Funky initial location

### ISSUE THREAD

**Issue by thundenilla** [react-community/react-native-maps#980]
Greeting earthling ! 

1. I noticed the center button of the map is not showing at the first time the map is loaded, but it will show after few times i load it. how can i control this and why this happened? (its at the top right corner of the map)

2. Every time I load the map, it's not showing my current location right away, but its showing middle of Arctic OCEAN! (85.05048175505233,3.1467991322278976) which is super odd btw. can some explain why this happen? and how can I fix this?  Btw i tried with few different devices and all came out with the same result. which is firstly load the map in ARCTIC OCEAN. 

```
<MapView
	initialRegion={this.state.region}
	style={styles.map}
	showsUserLocation={true}
	followsUserLocation={true}
	pitchEnabled={true}
	region={this.state.region}
	onPress={() => this.checkIsVisible()}
	onRegionChange={(region) => this.onRegionChange(region)}>
</MapView>
```

**Comment by kaueDM** [comment]
Probably your map is rendering before you get the current location. I got this problem here too ( working on this now btw ).

**Comment by alvelig** [comment]
1. #1033 
2. See this and remove initialRegion https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
