### ISSUE TITLE
[googlemap for ios/android]how to get current location information?

### ISSUE THREAD

**Issue by qq326646683** [react-community/react-native-maps#986]

**Comment by mariodev12** [comment]
Using navigator.geolocation.

https://facebook.github.io/react-native/docs/geolocation.html

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Comment by manu006** [comment]
If you just want to access latitude and longitude then you can you Geolocation come as a default in React Native 

navigator.geolocation.getCurrentPosition(
      (position) => {
        this.setState({
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          error: null,
        });
      },
      (error) => this.setState({ error: error.message }),
      { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },
    );
