### ISSUE TITLE
showsMyLocationButton does not work on android

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-native-maps#993]
Currently showsMyLocationButton does not appear unless the device is rotated or a change of the styling on the map is updated through hot-reload. Current device galaxy s5.

**Comment by MatthiasDebaere** [comment]
Same problem as in #549 , map component needs to rerender.

**Comment by psam44** [comment]
Please follow the issue on #1033.

**Comment by ashutosh-akss** [comment]
Same Problem here, cannot see myLocationButton

**Comment by alvelig** [comment]
Duplicate of #1033
