### ISSUE TITLE
Example completely broken for iOS

### ISSUE THREAD

**Issue by coltonone20** [react-community/react-native-maps#996]
When I follow the instructions for iOS at 

https://github.com/airbnb/react-native-maps/blob/master/docs/examples-setup.md 

The example fails to build with

```
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Based on this issue:  https://github.com/facebook/react-native/issues/7308

I tried running `react-native upgrade` and answered "y" to all the prompts.

This allows the application to build and install.  When I try to open any of the map screens in the app, like "Static Map", I receive the error `Warning: Native Component for "AirMapMarker" does not exist`.  
The solution described here (Change products path in Xcode) did not work for me:  https://github.com/facebook/react-native/pull/11899

Neither does a clean install and running `react-native link` just after `npm install`

**Comment by doei** [comment]
Same here, above the error message already mentioned by @coltonone20 is:
```
The following build commands failed:
	CompileC /Users/awez/Desktop/maptest/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapCallout.o AirMaps/AIRMapCallout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

The installation instruction are a little unclear for somebody not extremely familiar with native iOS development (what steps can be skipped exactly ? Is a podfile necessary since option 3 doesn't require one ? Is it necessary to follow any option at all since option 3 tells you react-native link should have taken care of it ? What is required for Gmaps support and what is not ?). 
I've tried all options and the build fails every time.

**Comment by coltonone20** [comment]
@doei  I was able to get react-native-maps running on iOS by creating a new project with `react-native init` and then following the install instructions here https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md, disregarding the react-native-maps example project completely.  Still no success with getting google maps working on iOS though, I will open a separate issue about that.

**Comment by unboundfire** [comment]
@coltonone20 @doei I have google maps working on iOS. I have dragged the AIRMaps and AIRGoogleMaps directories from react-native-maps into my xcode project as groups and I have a podfile that looks like this.

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
def shared_pods
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'
end
```

I do **not** run `react-native link react-native-maps` as that will add libAIRMaps.a to our xcode project and cause duplicate symbol compile errors

**Comment by skeet** [comment]
I was able to get Google maps working on iOS following the guide in this comment - https://github.com/airbnb/react-native-maps/issues/789#issuecomment-273890706

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
